import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour FACILITY
    const data = [
      {
        fcy_0: 'VALUE_1',
        payban_0: 'VALUE_1',
        dadflg_0: 'VALUE_1',
        ivyflg_0: 'VALUE_1',
        hrmpayban_0: 'VALUE_1',
        prf_0: 'VALUE_1',
        cntnam_0: 'Nom contact 1',
        dadfcy_0: 'VALUE_1',
        hrmdadfcy_0: 'VALUE_1',
        strhou_0: 'VALUE_1',
        endhou_0: 'VALUE_1',
        srv_0: 'VALUE_1',
        xtypsit_0: 'VALUE_1',
        rskwrk_0: 'VALUE_1',
        fcysho_0: 'VALUE_1',
        insctyflg_0: 'VALUE_1',
        ivyfcy_0: 'VALUE_1',
        acccod_0: 'VALUE_1',
        cce_0: 'VALUE_1',
        uvyday_0: 'VALUE_1',
        uvycod_0: 'VALUE_1',
        fcynam_0: 'VALUE_1',
        bpadcl_0: 'VALUE_1',
        die_0: 'VALUE_1',
        cry_0: 'VALUE_1',
        wrhflg_0: 'VALUE_1',
        bptnum_0: 'FAC0001',
        creusr_0: 'VALUE_1',
        legcpy_0: 'VALUE_1',
        mfgflg_0: 'VALUE_1',
        salflg_0: 'VALUE_1',
        purflg_0: 'VALUE_1',
        finflg_0: 'VALUE_1',
        chef_0: 'VALUE_1',
        naf_0: 'VALUE_1',
        bidnum_0: 'VALUE_1',
        finrspfcy_0: 'VALUE_1',
        updusr_0: 'VALUE_1',
        bpaadd_0: 'VALUE_1',
        credat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        secprh_0: 'VALUE_1',
        hrmtaxwag_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        oricerflg_0: 'VALUE_1',
        x1wmsflg_0: 'VALUE_1',
        eorinum_0: 'VALUE_1',
        x4envaut_0: 'VALUE_1',
        crn_0: 'VALUE_1',
        rexnum_0: 'VALUE_1',
        trawrh_0: 'VALUE_1',
        rtnwrh_0: 'VALUE_1',
        mfrwrh_0: 'VALUE_1',
        trfwrh_0: 'VALUE_1',
        cllcvt_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        hrmdadflg_0: 'VALUE_1',
        bpasge_0: 'VALUE_1',
        cntdds_0: 'VALUE_1',
        codcra_0: 'VALUE_1',
        payflg_0: 'VALUE_1',
        wrhges_0: 'VALUE_1',
        rcpwrh_0: 'VALUE_1',
        mfpwrh_0: 'VALUE_1',
        shiwrh_0: 'VALUE_1',
        mfgwrh_0: 'VALUE_1',
        scowrh_0: 'VALUE_1',
        sccwrh_0: 'VALUE_1',
        spaopeigic_0: 'VALUE_1',
        flgpec_0: true,
        flgapp_0: true,
        flgfor_0: true,
        regprh_0: 'VALUE_1',
        leg_0: 'VALUE_1',
        geocod_0: 'VALUE_1',
      },
      {
        fcy_0: 'VALUE_2',
        payban_0: 'VALUE_2',
        dadflg_0: 'VALUE_2',
        ivyflg_0: 'VALUE_2',
        hrmpayban_0: 'VALUE_2',
        prf_0: 'VALUE_2',
        cntnam_0: 'Nom contact 2',
        dadfcy_0: 'VALUE_2',
        hrmdadfcy_0: 'VALUE_2',
        strhou_0: 'VALUE_2',
        endhou_0: 'VALUE_2',
        srv_0: 'VALUE_2',
        xtypsit_0: 'VALUE_2',
        rskwrk_0: 'VALUE_2',
        fcysho_0: 'VALUE_2',
        insctyflg_0: 'VALUE_2',
        ivyfcy_0: 'VALUE_2',
        acccod_0: 'VALUE_2',
        cce_0: 'VALUE_2',
        uvyday_0: 'VALUE_2',
        uvycod_0: 'VALUE_2',
        fcynam_0: 'VALUE_2',
        bpadcl_0: 'VALUE_2',
        die_0: 'VALUE_2',
        cry_0: 'VALUE_2',
        wrhflg_0: 'VALUE_2',
        bptnum_0: 'FAC0002',
        creusr_0: 'VALUE_2',
        legcpy_0: 'VALUE_2',
        mfgflg_0: 'VALUE_2',
        salflg_0: 'VALUE_2',
        purflg_0: 'VALUE_2',
        finflg_0: 'VALUE_2',
        chef_0: 'VALUE_2',
        naf_0: 'VALUE_2',
        bidnum_0: 'VALUE_2',
        finrspfcy_0: 'VALUE_2',
        updusr_0: 'VALUE_2',
        bpaadd_0: 'VALUE_2',
        credat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        secprh_0: 'VALUE_2',
        hrmtaxwag_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        oricerflg_0: 'VALUE_2',
        x1wmsflg_0: 'VALUE_2',
        eorinum_0: 'VALUE_2',
        x4envaut_0: 'VALUE_2',
        crn_0: 'VALUE_2',
        rexnum_0: 'VALUE_2',
        trawrh_0: 'VALUE_2',
        rtnwrh_0: 'VALUE_2',
        mfrwrh_0: 'VALUE_2',
        trfwrh_0: 'VALUE_2',
        cllcvt_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        hrmdadflg_0: 'VALUE_2',
        bpasge_0: 'VALUE_2',
        cntdds_0: 'VALUE_2',
        codcra_0: 'VALUE_2',
        payflg_0: 'VALUE_2',
        wrhges_0: 'VALUE_2',
        rcpwrh_0: 'VALUE_2',
        mfpwrh_0: 'VALUE_2',
        shiwrh_0: 'VALUE_2',
        mfgwrh_0: 'VALUE_2',
        scowrh_0: 'VALUE_2',
        sccwrh_0: 'VALUE_2',
        spaopeigic_0: 'VALUE_2',
        flgpec_0: true,
        flgapp_0: true,
        flgfor_0: true,
        regprh_0: 'VALUE_2',
        leg_0: 'VALUE_2',
        geocod_0: 'VALUE_2',
      },
      {
        fcy_0: 'VALUE_3',
        payban_0: 'VALUE_3',
        dadflg_0: 'VALUE_3',
        ivyflg_0: 'VALUE_3',
        hrmpayban_0: 'VALUE_3',
        prf_0: 'VALUE_3',
        cntnam_0: 'Nom contact 3',
        dadfcy_0: 'VALUE_3',
        hrmdadfcy_0: 'VALUE_3',
        strhou_0: 'VALUE_3',
        endhou_0: 'VALUE_3',
        srv_0: 'VALUE_3',
        xtypsit_0: 'VALUE_3',
        rskwrk_0: 'VALUE_3',
        fcysho_0: 'VALUE_3',
        insctyflg_0: 'VALUE_3',
        ivyfcy_0: 'VALUE_3',
        acccod_0: 'VALUE_3',
        cce_0: 'VALUE_3',
        uvyday_0: 'VALUE_3',
        uvycod_0: 'VALUE_3',
        fcynam_0: 'VALUE_3',
        bpadcl_0: 'VALUE_3',
        die_0: 'VALUE_3',
        cry_0: 'VALUE_3',
        wrhflg_0: 'VALUE_3',
        bptnum_0: 'FAC0003',
        creusr_0: 'VALUE_3',
        legcpy_0: 'VALUE_3',
        mfgflg_0: 'VALUE_3',
        salflg_0: 'VALUE_3',
        purflg_0: 'VALUE_3',
        finflg_0: 'VALUE_3',
        chef_0: 'VALUE_3',
        naf_0: 'VALUE_3',
        bidnum_0: 'VALUE_3',
        finrspfcy_0: 'VALUE_3',
        updusr_0: 'VALUE_3',
        bpaadd_0: 'VALUE_3',
        credat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        secprh_0: 'VALUE_3',
        hrmtaxwag_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        oricerflg_0: 'VALUE_3',
        x1wmsflg_0: 'VALUE_3',
        eorinum_0: 'VALUE_3',
        x4envaut_0: 'VALUE_3',
        crn_0: 'VALUE_3',
        rexnum_0: 'VALUE_3',
        trawrh_0: 'VALUE_3',
        rtnwrh_0: 'VALUE_3',
        mfrwrh_0: 'VALUE_3',
        trfwrh_0: 'VALUE_3',
        cllcvt_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        hrmdadflg_0: 'VALUE_3',
        bpasge_0: 'VALUE_3',
        cntdds_0: 'VALUE_3',
        codcra_0: 'VALUE_3',
        payflg_0: 'VALUE_3',
        wrhges_0: 'VALUE_3',
        rcpwrh_0: 'VALUE_3',
        mfpwrh_0: 'VALUE_3',
        shiwrh_0: 'VALUE_3',
        mfgwrh_0: 'VALUE_3',
        scowrh_0: 'VALUE_3',
        sccwrh_0: 'VALUE_3',
        spaopeigic_0: 'VALUE_3',
        flgpec_0: true,
        flgapp_0: true,
        flgfor_0: true,
        regprh_0: 'VALUE_3',
        leg_0: 'VALUE_3',
        geocod_0: 'VALUE_3',
      },
      {
        fcy_0: 'VALUE_4',
        payban_0: 'VALUE_4',
        dadflg_0: 'VALUE_4',
        ivyflg_0: 'VALUE_4',
        hrmpayban_0: 'VALUE_4',
        prf_0: 'VALUE_4',
        cntnam_0: 'Nom contact 4',
        dadfcy_0: 'VALUE_4',
        hrmdadfcy_0: 'VALUE_4',
        strhou_0: 'VALUE_4',
        endhou_0: 'VALUE_4',
        srv_0: 'VALUE_4',
        xtypsit_0: 'VALUE_4',
        rskwrk_0: 'VALUE_4',
        fcysho_0: 'VALUE_4',
        insctyflg_0: 'VALUE_4',
        ivyfcy_0: 'VALUE_4',
        acccod_0: 'VALUE_4',
        cce_0: 'VALUE_4',
        uvyday_0: 'VALUE_4',
        uvycod_0: 'VALUE_4',
        fcynam_0: 'VALUE_4',
        bpadcl_0: 'VALUE_4',
        die_0: 'VALUE_4',
        cry_0: 'VALUE_4',
        wrhflg_0: 'VALUE_4',
        bptnum_0: 'FAC0004',
        creusr_0: 'VALUE_4',
        legcpy_0: 'VALUE_4',
        mfgflg_0: 'VALUE_4',
        salflg_0: 'VALUE_4',
        purflg_0: 'VALUE_4',
        finflg_0: 'VALUE_4',
        chef_0: 'VALUE_4',
        naf_0: 'VALUE_4',
        bidnum_0: 'VALUE_4',
        finrspfcy_0: 'VALUE_4',
        updusr_0: 'VALUE_4',
        bpaadd_0: 'VALUE_4',
        credat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        secprh_0: 'VALUE_4',
        hrmtaxwag_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        oricerflg_0: 'VALUE_4',
        x1wmsflg_0: 'VALUE_4',
        eorinum_0: 'VALUE_4',
        x4envaut_0: 'VALUE_4',
        crn_0: 'VALUE_4',
        rexnum_0: 'VALUE_4',
        trawrh_0: 'VALUE_4',
        rtnwrh_0: 'VALUE_4',
        mfrwrh_0: 'VALUE_4',
        trfwrh_0: 'VALUE_4',
        cllcvt_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        hrmdadflg_0: 'VALUE_4',
        bpasge_0: 'VALUE_4',
        cntdds_0: 'VALUE_4',
        codcra_0: 'VALUE_4',
        payflg_0: 'VALUE_4',
        wrhges_0: 'VALUE_4',
        rcpwrh_0: 'VALUE_4',
        mfpwrh_0: 'VALUE_4',
        shiwrh_0: 'VALUE_4',
        mfgwrh_0: 'VALUE_4',
        scowrh_0: 'VALUE_4',
        sccwrh_0: 'VALUE_4',
        spaopeigic_0: 'VALUE_4',
        flgpec_0: true,
        flgapp_0: true,
        flgfor_0: true,
        regprh_0: 'VALUE_4',
        leg_0: 'VALUE_4',
        geocod_0: 'VALUE_4',
      },
      {
        fcy_0: 'VALUE_5',
        payban_0: 'VALUE_5',
        dadflg_0: 'VALUE_5',
        ivyflg_0: 'VALUE_5',
        hrmpayban_0: 'VALUE_5',
        prf_0: 'VALUE_5',
        cntnam_0: 'Nom contact 5',
        dadfcy_0: 'VALUE_5',
        hrmdadfcy_0: 'VALUE_5',
        strhou_0: 'VALUE_5',
        endhou_0: 'VALUE_5',
        srv_0: 'VALUE_5',
        xtypsit_0: 'VALUE_5',
        rskwrk_0: 'VALUE_5',
        fcysho_0: 'VALUE_5',
        insctyflg_0: 'VALUE_5',
        ivyfcy_0: 'VALUE_5',
        acccod_0: 'VALUE_5',
        cce_0: 'VALUE_5',
        uvyday_0: 'VALUE_5',
        uvycod_0: 'VALUE_5',
        fcynam_0: 'VALUE_5',
        bpadcl_0: 'VALUE_5',
        die_0: 'VALUE_5',
        cry_0: 'VALUE_5',
        wrhflg_0: 'VALUE_5',
        bptnum_0: 'FAC0005',
        creusr_0: 'VALUE_5',
        legcpy_0: 'VALUE_5',
        mfgflg_0: 'VALUE_5',
        salflg_0: 'VALUE_5',
        purflg_0: 'VALUE_5',
        finflg_0: 'VALUE_5',
        chef_0: 'VALUE_5',
        naf_0: 'VALUE_5',
        bidnum_0: 'VALUE_5',
        finrspfcy_0: 'VALUE_5',
        updusr_0: 'VALUE_5',
        bpaadd_0: 'VALUE_5',
        credat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        secprh_0: 'VALUE_5',
        hrmtaxwag_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        oricerflg_0: 'VALUE_5',
        x1wmsflg_0: 'VALUE_5',
        eorinum_0: 'VALUE_5',
        x4envaut_0: 'VALUE_5',
        crn_0: 'VALUE_5',
        rexnum_0: 'VALUE_5',
        trawrh_0: 'VALUE_5',
        rtnwrh_0: 'VALUE_5',
        mfrwrh_0: 'VALUE_5',
        trfwrh_0: 'VALUE_5',
        cllcvt_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        hrmdadflg_0: 'VALUE_5',
        bpasge_0: 'VALUE_5',
        cntdds_0: 'VALUE_5',
        codcra_0: 'VALUE_5',
        payflg_0: 'VALUE_5',
        wrhges_0: 'VALUE_5',
        rcpwrh_0: 'VALUE_5',
        mfpwrh_0: 'VALUE_5',
        shiwrh_0: 'VALUE_5',
        mfgwrh_0: 'VALUE_5',
        scowrh_0: 'VALUE_5',
        sccwrh_0: 'VALUE_5',
        spaopeigic_0: 'VALUE_5',
        flgpec_0: true,
        flgapp_0: true,
        flgfor_0: true,
        regprh_0: 'VALUE_5',
        leg_0: 'VALUE_5',
        geocod_0: 'VALUE_5',
      },
      {
        fcy_0: 'VALUE_6',
        payban_0: 'VALUE_6',
        dadflg_0: 'VALUE_6',
        ivyflg_0: 'VALUE_6',
        hrmpayban_0: 'VALUE_6',
        prf_0: 'VALUE_6',
        cntnam_0: 'Nom contact 6',
        dadfcy_0: 'VALUE_6',
        hrmdadfcy_0: 'VALUE_6',
        strhou_0: 'VALUE_6',
        endhou_0: 'VALUE_6',
        srv_0: 'VALUE_6',
        xtypsit_0: 'VALUE_6',
        rskwrk_0: 'VALUE_6',
        fcysho_0: 'VALUE_6',
        insctyflg_0: 'VALUE_6',
        ivyfcy_0: 'VALUE_6',
        acccod_0: 'VALUE_6',
        cce_0: 'VALUE_6',
        uvyday_0: 'VALUE_6',
        uvycod_0: 'VALUE_6',
        fcynam_0: 'VALUE_6',
        bpadcl_0: 'VALUE_6',
        die_0: 'VALUE_6',
        cry_0: 'VALUE_6',
        wrhflg_0: 'VALUE_6',
        bptnum_0: 'FAC0006',
        creusr_0: 'VALUE_6',
        legcpy_0: 'VALUE_6',
        mfgflg_0: 'VALUE_6',
        salflg_0: 'VALUE_6',
        purflg_0: 'VALUE_6',
        finflg_0: 'VALUE_6',
        chef_0: 'VALUE_6',
        naf_0: 'VALUE_6',
        bidnum_0: 'VALUE_6',
        finrspfcy_0: 'VALUE_6',
        updusr_0: 'VALUE_6',
        bpaadd_0: 'VALUE_6',
        credat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        secprh_0: 'VALUE_6',
        hrmtaxwag_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        oricerflg_0: 'VALUE_6',
        x1wmsflg_0: 'VALUE_6',
        eorinum_0: 'VALUE_6',
        x4envaut_0: 'VALUE_6',
        crn_0: 'VALUE_6',
        rexnum_0: 'VALUE_6',
        trawrh_0: 'VALUE_6',
        rtnwrh_0: 'VALUE_6',
        mfrwrh_0: 'VALUE_6',
        trfwrh_0: 'VALUE_6',
        cllcvt_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        hrmdadflg_0: 'VALUE_6',
        bpasge_0: 'VALUE_6',
        cntdds_0: 'VALUE_6',
        codcra_0: 'VALUE_6',
        payflg_0: 'VALUE_6',
        wrhges_0: 'VALUE_6',
        rcpwrh_0: 'VALUE_6',
        mfpwrh_0: 'VALUE_6',
        shiwrh_0: 'VALUE_6',
        mfgwrh_0: 'VALUE_6',
        scowrh_0: 'VALUE_6',
        sccwrh_0: 'VALUE_6',
        spaopeigic_0: 'VALUE_6',
        flgpec_0: true,
        flgapp_0: true,
        flgfor_0: true,
        regprh_0: 'VALUE_6',
        leg_0: 'VALUE_6',
        geocod_0: 'VALUE_6',
      },
      {
        fcy_0: 'VALUE_7',
        payban_0: 'VALUE_7',
        dadflg_0: 'VALUE_7',
        ivyflg_0: 'VALUE_7',
        hrmpayban_0: 'VALUE_7',
        prf_0: 'VALUE_7',
        cntnam_0: 'Nom contact 7',
        dadfcy_0: 'VALUE_7',
        hrmdadfcy_0: 'VALUE_7',
        strhou_0: 'VALUE_7',
        endhou_0: 'VALUE_7',
        srv_0: 'VALUE_7',
        xtypsit_0: 'VALUE_7',
        rskwrk_0: 'VALUE_7',
        fcysho_0: 'VALUE_7',
        insctyflg_0: 'VALUE_7',
        ivyfcy_0: 'VALUE_7',
        acccod_0: 'VALUE_7',
        cce_0: 'VALUE_7',
        uvyday_0: 'VALUE_7',
        uvycod_0: 'VALUE_7',
        fcynam_0: 'VALUE_7',
        bpadcl_0: 'VALUE_7',
        die_0: 'VALUE_7',
        cry_0: 'VALUE_7',
        wrhflg_0: 'VALUE_7',
        bptnum_0: 'FAC0007',
        creusr_0: 'VALUE_7',
        legcpy_0: 'VALUE_7',
        mfgflg_0: 'VALUE_7',
        salflg_0: 'VALUE_7',
        purflg_0: 'VALUE_7',
        finflg_0: 'VALUE_7',
        chef_0: 'VALUE_7',
        naf_0: 'VALUE_7',
        bidnum_0: 'VALUE_7',
        finrspfcy_0: 'VALUE_7',
        updusr_0: 'VALUE_7',
        bpaadd_0: 'VALUE_7',
        credat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        secprh_0: 'VALUE_7',
        hrmtaxwag_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        oricerflg_0: 'VALUE_7',
        x1wmsflg_0: 'VALUE_7',
        eorinum_0: 'VALUE_7',
        x4envaut_0: 'VALUE_7',
        crn_0: 'VALUE_7',
        rexnum_0: 'VALUE_7',
        trawrh_0: 'VALUE_7',
        rtnwrh_0: 'VALUE_7',
        mfrwrh_0: 'VALUE_7',
        trfwrh_0: 'VALUE_7',
        cllcvt_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        hrmdadflg_0: 'VALUE_7',
        bpasge_0: 'VALUE_7',
        cntdds_0: 'VALUE_7',
        codcra_0: 'VALUE_7',
        payflg_0: 'VALUE_7',
        wrhges_0: 'VALUE_7',
        rcpwrh_0: 'VALUE_7',
        mfpwrh_0: 'VALUE_7',
        shiwrh_0: 'VALUE_7',
        mfgwrh_0: 'VALUE_7',
        scowrh_0: 'VALUE_7',
        sccwrh_0: 'VALUE_7',
        spaopeigic_0: 'VALUE_7',
        flgpec_0: true,
        flgapp_0: true,
        flgfor_0: true,
        regprh_0: 'VALUE_7',
        leg_0: 'VALUE_7',
        geocod_0: 'VALUE_7',
      },
      {
        fcy_0: 'VALUE_8',
        payban_0: 'VALUE_8',
        dadflg_0: 'VALUE_8',
        ivyflg_0: 'VALUE_8',
        hrmpayban_0: 'VALUE_8',
        prf_0: 'VALUE_8',
        cntnam_0: 'Nom contact 8',
        dadfcy_0: 'VALUE_8',
        hrmdadfcy_0: 'VALUE_8',
        strhou_0: 'VALUE_8',
        endhou_0: 'VALUE_8',
        srv_0: 'VALUE_8',
        xtypsit_0: 'VALUE_8',
        rskwrk_0: 'VALUE_8',
        fcysho_0: 'VALUE_8',
        insctyflg_0: 'VALUE_8',
        ivyfcy_0: 'VALUE_8',
        acccod_0: 'VALUE_8',
        cce_0: 'VALUE_8',
        uvyday_0: 'VALUE_8',
        uvycod_0: 'VALUE_8',
        fcynam_0: 'VALUE_8',
        bpadcl_0: 'VALUE_8',
        die_0: 'VALUE_8',
        cry_0: 'VALUE_8',
        wrhflg_0: 'VALUE_8',
        bptnum_0: 'FAC0008',
        creusr_0: 'VALUE_8',
        legcpy_0: 'VALUE_8',
        mfgflg_0: 'VALUE_8',
        salflg_0: 'VALUE_8',
        purflg_0: 'VALUE_8',
        finflg_0: 'VALUE_8',
        chef_0: 'VALUE_8',
        naf_0: 'VALUE_8',
        bidnum_0: 'VALUE_8',
        finrspfcy_0: 'VALUE_8',
        updusr_0: 'VALUE_8',
        bpaadd_0: 'VALUE_8',
        credat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        secprh_0: 'VALUE_8',
        hrmtaxwag_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        oricerflg_0: 'VALUE_8',
        x1wmsflg_0: 'VALUE_8',
        eorinum_0: 'VALUE_8',
        x4envaut_0: 'VALUE_8',
        crn_0: 'VALUE_8',
        rexnum_0: 'VALUE_8',
        trawrh_0: 'VALUE_8',
        rtnwrh_0: 'VALUE_8',
        mfrwrh_0: 'VALUE_8',
        trfwrh_0: 'VALUE_8',
        cllcvt_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        hrmdadflg_0: 'VALUE_8',
        bpasge_0: 'VALUE_8',
        cntdds_0: 'VALUE_8',
        codcra_0: 'VALUE_8',
        payflg_0: 'VALUE_8',
        wrhges_0: 'VALUE_8',
        rcpwrh_0: 'VALUE_8',
        mfpwrh_0: 'VALUE_8',
        shiwrh_0: 'VALUE_8',
        mfgwrh_0: 'VALUE_8',
        scowrh_0: 'VALUE_8',
        sccwrh_0: 'VALUE_8',
        spaopeigic_0: 'VALUE_8',
        flgpec_0: true,
        flgapp_0: true,
        flgfor_0: true,
        regprh_0: 'VALUE_8',
        leg_0: 'VALUE_8',
        geocod_0: 'VALUE_8',
      },
      {
        fcy_0: 'VALUE_9',
        payban_0: 'VALUE_9',
        dadflg_0: 'VALUE_9',
        ivyflg_0: 'VALUE_9',
        hrmpayban_0: 'VALUE_9',
        prf_0: 'VALUE_9',
        cntnam_0: 'Nom contact 9',
        dadfcy_0: 'VALUE_9',
        hrmdadfcy_0: 'VALUE_9',
        strhou_0: 'VALUE_9',
        endhou_0: 'VALUE_9',
        srv_0: 'VALUE_9',
        xtypsit_0: 'VALUE_9',
        rskwrk_0: 'VALUE_9',
        fcysho_0: 'VALUE_9',
        insctyflg_0: 'VALUE_9',
        ivyfcy_0: 'VALUE_9',
        acccod_0: 'VALUE_9',
        cce_0: 'VALUE_9',
        uvyday_0: 'VALUE_9',
        uvycod_0: 'VALUE_9',
        fcynam_0: 'VALUE_9',
        bpadcl_0: 'VALUE_9',
        die_0: 'VALUE_9',
        cry_0: 'VALUE_9',
        wrhflg_0: 'VALUE_9',
        bptnum_0: 'FAC0009',
        creusr_0: 'VALUE_9',
        legcpy_0: 'VALUE_9',
        mfgflg_0: 'VALUE_9',
        salflg_0: 'VALUE_9',
        purflg_0: 'VALUE_9',
        finflg_0: 'VALUE_9',
        chef_0: 'VALUE_9',
        naf_0: 'VALUE_9',
        bidnum_0: 'VALUE_9',
        finrspfcy_0: 'VALUE_9',
        updusr_0: 'VALUE_9',
        bpaadd_0: 'VALUE_9',
        credat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        secprh_0: 'VALUE_9',
        hrmtaxwag_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        oricerflg_0: 'VALUE_9',
        x1wmsflg_0: 'VALUE_9',
        eorinum_0: 'VALUE_9',
        x4envaut_0: 'VALUE_9',
        crn_0: 'VALUE_9',
        rexnum_0: 'VALUE_9',
        trawrh_0: 'VALUE_9',
        rtnwrh_0: 'VALUE_9',
        mfrwrh_0: 'VALUE_9',
        trfwrh_0: 'VALUE_9',
        cllcvt_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        hrmdadflg_0: 'VALUE_9',
        bpasge_0: 'VALUE_9',
        cntdds_0: 'VALUE_9',
        codcra_0: 'VALUE_9',
        payflg_0: 'VALUE_9',
        wrhges_0: 'VALUE_9',
        rcpwrh_0: 'VALUE_9',
        mfpwrh_0: 'VALUE_9',
        shiwrh_0: 'VALUE_9',
        mfgwrh_0: 'VALUE_9',
        scowrh_0: 'VALUE_9',
        sccwrh_0: 'VALUE_9',
        spaopeigic_0: 'VALUE_9',
        flgpec_0: true,
        flgapp_0: true,
        flgfor_0: true,
        regprh_0: 'VALUE_9',
        leg_0: 'VALUE_9',
        geocod_0: 'VALUE_9',
      },
      {
        fcy_0: 'VALUE_10',
        payban_0: 'VALUE_10',
        dadflg_0: 'VALUE_10',
        ivyflg_0: 'VALUE_10',
        hrmpayban_0: 'VALUE_10',
        prf_0: 'VALUE_10',
        cntnam_0: 'Nom contact 10',
        dadfcy_0: 'VALUE_10',
        hrmdadfcy_0: 'VALUE_10',
        strhou_0: 'VALUE_10',
        endhou_0: 'VALUE_10',
        srv_0: 'VALUE_10',
        xtypsit_0: 'VALUE_10',
        rskwrk_0: 'VALUE_10',
        fcysho_0: 'VALUE_10',
        insctyflg_0: 'VALUE_10',
        ivyfcy_0: 'VALUE_10',
        acccod_0: 'VALUE_10',
        cce_0: 'VALUE_10',
        uvyday_0: 'VALUE_10',
        uvycod_0: 'VALUE_10',
        fcynam_0: 'VALUE_10',
        bpadcl_0: 'VALUE_10',
        die_0: 'VALUE_10',
        cry_0: 'VALUE_10',
        wrhflg_0: 'VALUE_10',
        bptnum_0: 'FAC0010',
        creusr_0: 'VALUE_10',
        legcpy_0: 'VALUE_10',
        mfgflg_0: 'VALUE_10',
        salflg_0: 'VALUE_10',
        purflg_0: 'VALUE_10',
        finflg_0: 'VALUE_10',
        chef_0: 'VALUE_10',
        naf_0: 'VALUE_10',
        bidnum_0: 'VALUE_10',
        finrspfcy_0: 'VALUE_10',
        updusr_0: 'VALUE_10',
        bpaadd_0: 'VALUE_10',
        credat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        secprh_0: 'VALUE_10',
        hrmtaxwag_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        oricerflg_0: 'VALUE_10',
        x1wmsflg_0: 'VALUE_10',
        eorinum_0: 'VALUE_10',
        x4envaut_0: 'VALUE_10',
        crn_0: 'VALUE_10',
        rexnum_0: 'VALUE_10',
        trawrh_0: 'VALUE_10',
        rtnwrh_0: 'VALUE_10',
        mfrwrh_0: 'VALUE_10',
        trfwrh_0: 'VALUE_10',
        cllcvt_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        hrmdadflg_0: 'VALUE_10',
        bpasge_0: 'VALUE_10',
        cntdds_0: 'VALUE_10',
        codcra_0: 'VALUE_10',
        payflg_0: 'VALUE_10',
        wrhges_0: 'VALUE_10',
        rcpwrh_0: 'VALUE_10',
        mfpwrh_0: 'VALUE_10',
        shiwrh_0: 'VALUE_10',
        mfgwrh_0: 'VALUE_10',
        scowrh_0: 'VALUE_10',
        sccwrh_0: 'VALUE_10',
        spaopeigic_0: 'VALUE_10',
        flgpec_0: true,
        flgapp_0: true,
        flgfor_0: true,
        regprh_0: 'VALUE_10',
        leg_0: 'VALUE_10',
        geocod_0: 'VALUE_10',
      },
    ]

    await Database.table('facility').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans facility`)
  }
}
