import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour BPARTNER
    const data = [
      {
        bidcry_0: 'VALUE_1',
        cntnam_0: 'Nom contact par defaut 1',
        cslbpr_0: 'VALUE_1',
        bpsflg_0: 'VALUE_1',
        crn_0: 'VALUE_1',
        bptflg_0: 'VALUE_1',
        naf_0: 'VALUE_1',
        eorinum_0: 'BPA0001',
        regnum_0: 'VALUE_1',
        vatno_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cpyrel_0: 'VALUE_1',
        xfabflg_0: 'VALUE_1',
        bppflg_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        brgobj_0: 'VALUE_1',
        acs_0: 'VALUE_1',
        eecnum_0: 'VALUE_1',
        cfoexd_0: 'VALUE_1',
        doctyp_0: 'VALUE_1',
        bprnam_0: 'VALUE_1',
        pptflg_0: 'VALUE_1',
        prvflg_0: 'VALUE_1',
        bprlog_0: 'VALUE_1',
        vatnum_0: 'VALUE_1',
        fiscod_0: 'VALUE_1',
        bprnum_0: 'VALUE_1',
        grugpy_0: 'VALUE_1',
        pthflg_0: 'VALUE_1',
        bidnum_0: 'VALUE_1',
        bprsho_0: 'VALUE_1',
        repflg_0: 'VALUE_1',
        brgcod_0: 'VALUE_1',
        fcy_0: 'VALUE_1',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        bprgtetyp_0: 'VALUE_1',
        dooflg_0: 'VALUE_1',
        ccnflg_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        lan_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        bpcflg_0: 'VALUE_1',
        fctflg_0: 'VALUE_1',
        cur_0: 'VALUE_1',
        cry_0: 'VALUE_1',
        grucod_0: 'VALUE_1',
        legett_0: 'VALUE_1',
        bprfbdmag_0: 'VALUE_1',
        accnonrei_0: 'VALUE_1',
        modpam_0: 'VALUE_1',
        betfcy_0: 'VALUE_1',
        enaflg_0: true,
        bpracc_0: 'VALUE_1',
        acccod_0: 'VALUE_1',
        bprflg_0: 'VALUE_1',
        bpaadd_0: 'VALUE_1',
      },
      {
        bidcry_0: 'VALUE_2',
        cntnam_0: 'Nom contact par defaut 2',
        cslbpr_0: 'VALUE_2',
        bpsflg_0: 'VALUE_2',
        crn_0: 'VALUE_2',
        bptflg_0: 'VALUE_2',
        naf_0: 'VALUE_2',
        eorinum_0: 'BPA0002',
        regnum_0: 'VALUE_2',
        vatno_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cpyrel_0: 'VALUE_2',
        xfabflg_0: 'VALUE_2',
        bppflg_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        brgobj_0: 'VALUE_2',
        acs_0: 'VALUE_2',
        eecnum_0: 'VALUE_2',
        cfoexd_0: 'VALUE_2',
        doctyp_0: 'VALUE_2',
        bprnam_0: 'VALUE_2',
        pptflg_0: 'VALUE_2',
        prvflg_0: 'VALUE_2',
        bprlog_0: 'VALUE_2',
        vatnum_0: 'VALUE_2',
        fiscod_0: 'VALUE_2',
        bprnum_0: 'VALUE_2',
        grugpy_0: 'VALUE_2',
        pthflg_0: 'VALUE_2',
        bidnum_0: 'VALUE_2',
        bprsho_0: 'VALUE_2',
        repflg_0: 'VALUE_2',
        brgcod_0: 'VALUE_2',
        fcy_0: 'VALUE_2',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        bprgtetyp_0: 'VALUE_2',
        dooflg_0: 'VALUE_2',
        ccnflg_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        lan_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        bpcflg_0: 'VALUE_2',
        fctflg_0: 'VALUE_2',
        cur_0: 'VALUE_2',
        cry_0: 'VALUE_2',
        grucod_0: 'VALUE_2',
        legett_0: 'VALUE_2',
        bprfbdmag_0: 'VALUE_2',
        accnonrei_0: 'VALUE_2',
        modpam_0: 'VALUE_2',
        betfcy_0: 'VALUE_2',
        enaflg_0: true,
        bpracc_0: 'VALUE_2',
        acccod_0: 'VALUE_2',
        bprflg_0: 'VALUE_2',
        bpaadd_0: 'VALUE_2',
      },
      {
        bidcry_0: 'VALUE_3',
        cntnam_0: 'Nom contact par defaut 3',
        cslbpr_0: 'VALUE_3',
        bpsflg_0: 'VALUE_3',
        crn_0: 'VALUE_3',
        bptflg_0: 'VALUE_3',
        naf_0: 'VALUE_3',
        eorinum_0: 'BPA0003',
        regnum_0: 'VALUE_3',
        vatno_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cpyrel_0: 'VALUE_3',
        xfabflg_0: 'VALUE_3',
        bppflg_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        brgobj_0: 'VALUE_3',
        acs_0: 'VALUE_3',
        eecnum_0: 'VALUE_3',
        cfoexd_0: 'VALUE_3',
        doctyp_0: 'VALUE_3',
        bprnam_0: 'VALUE_3',
        pptflg_0: 'VALUE_3',
        prvflg_0: 'VALUE_3',
        bprlog_0: 'VALUE_3',
        vatnum_0: 'VALUE_3',
        fiscod_0: 'VALUE_3',
        bprnum_0: 'VALUE_3',
        grugpy_0: 'VALUE_3',
        pthflg_0: 'VALUE_3',
        bidnum_0: 'VALUE_3',
        bprsho_0: 'VALUE_3',
        repflg_0: 'VALUE_3',
        brgcod_0: 'VALUE_3',
        fcy_0: 'VALUE_3',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        bprgtetyp_0: 'VALUE_3',
        dooflg_0: 'VALUE_3',
        ccnflg_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        lan_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        bpcflg_0: 'VALUE_3',
        fctflg_0: 'VALUE_3',
        cur_0: 'VALUE_3',
        cry_0: 'VALUE_3',
        grucod_0: 'VALUE_3',
        legett_0: 'VALUE_3',
        bprfbdmag_0: 'VALUE_3',
        accnonrei_0: 'VALUE_3',
        modpam_0: 'VALUE_3',
        betfcy_0: 'VALUE_3',
        enaflg_0: true,
        bpracc_0: 'VALUE_3',
        acccod_0: 'VALUE_3',
        bprflg_0: 'VALUE_3',
        bpaadd_0: 'VALUE_3',
      },
      {
        bidcry_0: 'VALUE_4',
        cntnam_0: 'Nom contact par defaut 4',
        cslbpr_0: 'VALUE_4',
        bpsflg_0: 'VALUE_4',
        crn_0: 'VALUE_4',
        bptflg_0: 'VALUE_4',
        naf_0: 'VALUE_4',
        eorinum_0: 'BPA0004',
        regnum_0: 'VALUE_4',
        vatno_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cpyrel_0: 'VALUE_4',
        xfabflg_0: 'VALUE_4',
        bppflg_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        brgobj_0: 'VALUE_4',
        acs_0: 'VALUE_4',
        eecnum_0: 'VALUE_4',
        cfoexd_0: 'VALUE_4',
        doctyp_0: 'VALUE_4',
        bprnam_0: 'VALUE_4',
        pptflg_0: 'VALUE_4',
        prvflg_0: 'VALUE_4',
        bprlog_0: 'VALUE_4',
        vatnum_0: 'VALUE_4',
        fiscod_0: 'VALUE_4',
        bprnum_0: 'VALUE_4',
        grugpy_0: 'VALUE_4',
        pthflg_0: 'VALUE_4',
        bidnum_0: 'VALUE_4',
        bprsho_0: 'VALUE_4',
        repflg_0: 'VALUE_4',
        brgcod_0: 'VALUE_4',
        fcy_0: 'VALUE_4',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        bprgtetyp_0: 'VALUE_4',
        dooflg_0: 'VALUE_4',
        ccnflg_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        lan_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        bpcflg_0: 'VALUE_4',
        fctflg_0: 'VALUE_4',
        cur_0: 'VALUE_4',
        cry_0: 'VALUE_4',
        grucod_0: 'VALUE_4',
        legett_0: 'VALUE_4',
        bprfbdmag_0: 'VALUE_4',
        accnonrei_0: 'VALUE_4',
        modpam_0: 'VALUE_4',
        betfcy_0: 'VALUE_4',
        enaflg_0: true,
        bpracc_0: 'VALUE_4',
        acccod_0: 'VALUE_4',
        bprflg_0: 'VALUE_4',
        bpaadd_0: 'VALUE_4',
      },
      {
        bidcry_0: 'VALUE_5',
        cntnam_0: 'Nom contact par defaut 5',
        cslbpr_0: 'VALUE_5',
        bpsflg_0: 'VALUE_5',
        crn_0: 'VALUE_5',
        bptflg_0: 'VALUE_5',
        naf_0: 'VALUE_5',
        eorinum_0: 'BPA0005',
        regnum_0: 'VALUE_5',
        vatno_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cpyrel_0: 'VALUE_5',
        xfabflg_0: 'VALUE_5',
        bppflg_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        brgobj_0: 'VALUE_5',
        acs_0: 'VALUE_5',
        eecnum_0: 'VALUE_5',
        cfoexd_0: 'VALUE_5',
        doctyp_0: 'VALUE_5',
        bprnam_0: 'VALUE_5',
        pptflg_0: 'VALUE_5',
        prvflg_0: 'VALUE_5',
        bprlog_0: 'VALUE_5',
        vatnum_0: 'VALUE_5',
        fiscod_0: 'VALUE_5',
        bprnum_0: 'VALUE_5',
        grugpy_0: 'VALUE_5',
        pthflg_0: 'VALUE_5',
        bidnum_0: 'VALUE_5',
        bprsho_0: 'VALUE_5',
        repflg_0: 'VALUE_5',
        brgcod_0: 'VALUE_5',
        fcy_0: 'VALUE_5',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        bprgtetyp_0: 'VALUE_5',
        dooflg_0: 'VALUE_5',
        ccnflg_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        lan_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        bpcflg_0: 'VALUE_5',
        fctflg_0: 'VALUE_5',
        cur_0: 'VALUE_5',
        cry_0: 'VALUE_5',
        grucod_0: 'VALUE_5',
        legett_0: 'VALUE_5',
        bprfbdmag_0: 'VALUE_5',
        accnonrei_0: 'VALUE_5',
        modpam_0: 'VALUE_5',
        betfcy_0: 'VALUE_5',
        enaflg_0: true,
        bpracc_0: 'VALUE_5',
        acccod_0: 'VALUE_5',
        bprflg_0: 'VALUE_5',
        bpaadd_0: 'VALUE_5',
      },
      {
        bidcry_0: 'VALUE_6',
        cntnam_0: 'Nom contact par defaut 6',
        cslbpr_0: 'VALUE_6',
        bpsflg_0: 'VALUE_6',
        crn_0: 'VALUE_6',
        bptflg_0: 'VALUE_6',
        naf_0: 'VALUE_6',
        eorinum_0: 'BPA0006',
        regnum_0: 'VALUE_6',
        vatno_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cpyrel_0: 'VALUE_6',
        xfabflg_0: 'VALUE_6',
        bppflg_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        brgobj_0: 'VALUE_6',
        acs_0: 'VALUE_6',
        eecnum_0: 'VALUE_6',
        cfoexd_0: 'VALUE_6',
        doctyp_0: 'VALUE_6',
        bprnam_0: 'VALUE_6',
        pptflg_0: 'VALUE_6',
        prvflg_0: 'VALUE_6',
        bprlog_0: 'VALUE_6',
        vatnum_0: 'VALUE_6',
        fiscod_0: 'VALUE_6',
        bprnum_0: 'VALUE_6',
        grugpy_0: 'VALUE_6',
        pthflg_0: 'VALUE_6',
        bidnum_0: 'VALUE_6',
        bprsho_0: 'VALUE_6',
        repflg_0: 'VALUE_6',
        brgcod_0: 'VALUE_6',
        fcy_0: 'VALUE_6',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        bprgtetyp_0: 'VALUE_6',
        dooflg_0: 'VALUE_6',
        ccnflg_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        lan_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        bpcflg_0: 'VALUE_6',
        fctflg_0: 'VALUE_6',
        cur_0: 'VALUE_6',
        cry_0: 'VALUE_6',
        grucod_0: 'VALUE_6',
        legett_0: 'VALUE_6',
        bprfbdmag_0: 'VALUE_6',
        accnonrei_0: 'VALUE_6',
        modpam_0: 'VALUE_6',
        betfcy_0: 'VALUE_6',
        enaflg_0: true,
        bpracc_0: 'VALUE_6',
        acccod_0: 'VALUE_6',
        bprflg_0: 'VALUE_6',
        bpaadd_0: 'VALUE_6',
      },
      {
        bidcry_0: 'VALUE_7',
        cntnam_0: 'Nom contact par defaut 7',
        cslbpr_0: 'VALUE_7',
        bpsflg_0: 'VALUE_7',
        crn_0: 'VALUE_7',
        bptflg_0: 'VALUE_7',
        naf_0: 'VALUE_7',
        eorinum_0: 'BPA0007',
        regnum_0: 'VALUE_7',
        vatno_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cpyrel_0: 'VALUE_7',
        xfabflg_0: 'VALUE_7',
        bppflg_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        brgobj_0: 'VALUE_7',
        acs_0: 'VALUE_7',
        eecnum_0: 'VALUE_7',
        cfoexd_0: 'VALUE_7',
        doctyp_0: 'VALUE_7',
        bprnam_0: 'VALUE_7',
        pptflg_0: 'VALUE_7',
        prvflg_0: 'VALUE_7',
        bprlog_0: 'VALUE_7',
        vatnum_0: 'VALUE_7',
        fiscod_0: 'VALUE_7',
        bprnum_0: 'VALUE_7',
        grugpy_0: 'VALUE_7',
        pthflg_0: 'VALUE_7',
        bidnum_0: 'VALUE_7',
        bprsho_0: 'VALUE_7',
        repflg_0: 'VALUE_7',
        brgcod_0: 'VALUE_7',
        fcy_0: 'VALUE_7',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        bprgtetyp_0: 'VALUE_7',
        dooflg_0: 'VALUE_7',
        ccnflg_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        lan_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        bpcflg_0: 'VALUE_7',
        fctflg_0: 'VALUE_7',
        cur_0: 'VALUE_7',
        cry_0: 'VALUE_7',
        grucod_0: 'VALUE_7',
        legett_0: 'VALUE_7',
        bprfbdmag_0: 'VALUE_7',
        accnonrei_0: 'VALUE_7',
        modpam_0: 'VALUE_7',
        betfcy_0: 'VALUE_7',
        enaflg_0: true,
        bpracc_0: 'VALUE_7',
        acccod_0: 'VALUE_7',
        bprflg_0: 'VALUE_7',
        bpaadd_0: 'VALUE_7',
      },
      {
        bidcry_0: 'VALUE_8',
        cntnam_0: 'Nom contact par defaut 8',
        cslbpr_0: 'VALUE_8',
        bpsflg_0: 'VALUE_8',
        crn_0: 'VALUE_8',
        bptflg_0: 'VALUE_8',
        naf_0: 'VALUE_8',
        eorinum_0: 'BPA0008',
        regnum_0: 'VALUE_8',
        vatno_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cpyrel_0: 'VALUE_8',
        xfabflg_0: 'VALUE_8',
        bppflg_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        brgobj_0: 'VALUE_8',
        acs_0: 'VALUE_8',
        eecnum_0: 'VALUE_8',
        cfoexd_0: 'VALUE_8',
        doctyp_0: 'VALUE_8',
        bprnam_0: 'VALUE_8',
        pptflg_0: 'VALUE_8',
        prvflg_0: 'VALUE_8',
        bprlog_0: 'VALUE_8',
        vatnum_0: 'VALUE_8',
        fiscod_0: 'VALUE_8',
        bprnum_0: 'VALUE_8',
        grugpy_0: 'VALUE_8',
        pthflg_0: 'VALUE_8',
        bidnum_0: 'VALUE_8',
        bprsho_0: 'VALUE_8',
        repflg_0: 'VALUE_8',
        brgcod_0: 'VALUE_8',
        fcy_0: 'VALUE_8',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        bprgtetyp_0: 'VALUE_8',
        dooflg_0: 'VALUE_8',
        ccnflg_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        lan_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        bpcflg_0: 'VALUE_8',
        fctflg_0: 'VALUE_8',
        cur_0: 'VALUE_8',
        cry_0: 'VALUE_8',
        grucod_0: 'VALUE_8',
        legett_0: 'VALUE_8',
        bprfbdmag_0: 'VALUE_8',
        accnonrei_0: 'VALUE_8',
        modpam_0: 'VALUE_8',
        betfcy_0: 'VALUE_8',
        enaflg_0: true,
        bpracc_0: 'VALUE_8',
        acccod_0: 'VALUE_8',
        bprflg_0: 'VALUE_8',
        bpaadd_0: 'VALUE_8',
      },
      {
        bidcry_0: 'VALUE_9',
        cntnam_0: 'Nom contact par defaut 9',
        cslbpr_0: 'VALUE_9',
        bpsflg_0: 'VALUE_9',
        crn_0: 'VALUE_9',
        bptflg_0: 'VALUE_9',
        naf_0: 'VALUE_9',
        eorinum_0: 'BPA0009',
        regnum_0: 'VALUE_9',
        vatno_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cpyrel_0: 'VALUE_9',
        xfabflg_0: 'VALUE_9',
        bppflg_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        brgobj_0: 'VALUE_9',
        acs_0: 'VALUE_9',
        eecnum_0: 'VALUE_9',
        cfoexd_0: 'VALUE_9',
        doctyp_0: 'VALUE_9',
        bprnam_0: 'VALUE_9',
        pptflg_0: 'VALUE_9',
        prvflg_0: 'VALUE_9',
        bprlog_0: 'VALUE_9',
        vatnum_0: 'VALUE_9',
        fiscod_0: 'VALUE_9',
        bprnum_0: 'VALUE_9',
        grugpy_0: 'VALUE_9',
        pthflg_0: 'VALUE_9',
        bidnum_0: 'VALUE_9',
        bprsho_0: 'VALUE_9',
        repflg_0: 'VALUE_9',
        brgcod_0: 'VALUE_9',
        fcy_0: 'VALUE_9',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        bprgtetyp_0: 'VALUE_9',
        dooflg_0: 'VALUE_9',
        ccnflg_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        lan_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        bpcflg_0: 'VALUE_9',
        fctflg_0: 'VALUE_9',
        cur_0: 'VALUE_9',
        cry_0: 'VALUE_9',
        grucod_0: 'VALUE_9',
        legett_0: 'VALUE_9',
        bprfbdmag_0: 'VALUE_9',
        accnonrei_0: 'VALUE_9',
        modpam_0: 'VALUE_9',
        betfcy_0: 'VALUE_9',
        enaflg_0: true,
        bpracc_0: 'VALUE_9',
        acccod_0: 'VALUE_9',
        bprflg_0: 'VALUE_9',
        bpaadd_0: 'VALUE_9',
      },
      {
        bidcry_0: 'VALUE_10',
        cntnam_0: 'Nom contact par defaut 10',
        cslbpr_0: 'VALUE_10',
        bpsflg_0: 'VALUE_10',
        crn_0: 'VALUE_10',
        bptflg_0: 'VALUE_10',
        naf_0: 'VALUE_10',
        eorinum_0: 'BPA0010',
        regnum_0: 'VALUE_10',
        vatno_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cpyrel_0: 'VALUE_10',
        xfabflg_0: 'VALUE_10',
        bppflg_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        brgobj_0: 'VALUE_10',
        acs_0: 'VALUE_10',
        eecnum_0: 'VALUE_10',
        cfoexd_0: 'VALUE_10',
        doctyp_0: 'VALUE_10',
        bprnam_0: 'VALUE_10',
        pptflg_0: 'VALUE_10',
        prvflg_0: 'VALUE_10',
        bprlog_0: 'VALUE_10',
        vatnum_0: 'VALUE_10',
        fiscod_0: 'VALUE_10',
        bprnum_0: 'VALUE_10',
        grugpy_0: 'VALUE_10',
        pthflg_0: 'VALUE_10',
        bidnum_0: 'VALUE_10',
        bprsho_0: 'VALUE_10',
        repflg_0: 'VALUE_10',
        brgcod_0: 'VALUE_10',
        fcy_0: 'VALUE_10',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        bprgtetyp_0: 'VALUE_10',
        dooflg_0: 'VALUE_10',
        ccnflg_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        lan_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        bpcflg_0: 'VALUE_10',
        fctflg_0: 'VALUE_10',
        cur_0: 'VALUE_10',
        cry_0: 'VALUE_10',
        grucod_0: 'VALUE_10',
        legett_0: 'VALUE_10',
        bprfbdmag_0: 'VALUE_10',
        accnonrei_0: 'VALUE_10',
        modpam_0: 'VALUE_10',
        betfcy_0: 'VALUE_10',
        enaflg_0: true,
        bpracc_0: 'VALUE_10',
        acccod_0: 'VALUE_10',
        bprflg_0: 'VALUE_10',
        bpaadd_0: 'VALUE_10',
      },
    ]

    await Database.table('bpartner').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans bpartner`)
  }
}
