import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour BPADDRESS
    const data = [
      {
        crn_0: 'VALUE_1',
        adrval_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        glncod_0: 'VALUE_1',
        fcyweb_0: 'VALUE_1',
        xedicod_0: 'VALUE_1',
        xext2num_0: 'BPA0001',
        x4valid_0: 'VALUE_1',
        x4adrfab_0: 'VALUE_1',
        x4adrexp_0: 'VALUE_1',
        x4eecnum_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        x4ediqual_0: 'VALUE_1',
        fax_0: 'VALUE_1',
        bpaaddlig_0: 'VALUE_1',
        crynam_0: 'Nom pays 1',
        web_0: 'VALUE_1',
        mob_0: 'VALUE_1',
        sat_0: 'VALUE_1',
        poscod_0: 'VALUE_1',
        codsee_0: 'VALUE_1',
        updusr_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        bpades_0: 'VALUE_1',
        credat_0: new Date().toISOString().split('T')[0],
        extnum_0: 'VALUE_1',
        bpatyp_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        bpaadd_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        bpanum_0: 'VALUE_1',
        bpaaddflg_0: 'VALUE_1',
        tel_0: 'VALUE_1',
        bpabid_0: 'VALUE_1',
        cty_0: 'VALUE_1',
        cry_0: 'VALUE_1',
        xsrvfac_0: 'VALUE_1',
        ypohmel_0: 'VALUE_1',
      },
      {
        crn_0: 'VALUE_2',
        adrval_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        glncod_0: 'VALUE_2',
        fcyweb_0: 'VALUE_2',
        xedicod_0: 'VALUE_2',
        xext2num_0: 'BPA0002',
        x4valid_0: 'VALUE_2',
        x4adrfab_0: 'VALUE_2',
        x4adrexp_0: 'VALUE_2',
        x4eecnum_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        x4ediqual_0: 'VALUE_2',
        fax_0: 'VALUE_2',
        bpaaddlig_0: 'VALUE_2',
        crynam_0: 'Nom pays 2',
        web_0: 'VALUE_2',
        mob_0: 'VALUE_2',
        sat_0: 'VALUE_2',
        poscod_0: 'VALUE_2',
        codsee_0: 'VALUE_2',
        updusr_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        bpades_0: 'VALUE_2',
        credat_0: new Date().toISOString().split('T')[0],
        extnum_0: 'VALUE_2',
        bpatyp_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        bpaadd_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        bpanum_0: 'VALUE_2',
        bpaaddflg_0: 'VALUE_2',
        tel_0: 'VALUE_2',
        bpabid_0: 'VALUE_2',
        cty_0: 'VALUE_2',
        cry_0: 'VALUE_2',
        xsrvfac_0: 'VALUE_2',
        ypohmel_0: 'VALUE_2',
      },
      {
        crn_0: 'VALUE_3',
        adrval_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        glncod_0: 'VALUE_3',
        fcyweb_0: 'VALUE_3',
        xedicod_0: 'VALUE_3',
        xext2num_0: 'BPA0003',
        x4valid_0: 'VALUE_3',
        x4adrfab_0: 'VALUE_3',
        x4adrexp_0: 'VALUE_3',
        x4eecnum_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        x4ediqual_0: 'VALUE_3',
        fax_0: 'VALUE_3',
        bpaaddlig_0: 'VALUE_3',
        crynam_0: 'Nom pays 3',
        web_0: 'VALUE_3',
        mob_0: 'VALUE_3',
        sat_0: 'VALUE_3',
        poscod_0: 'VALUE_3',
        codsee_0: 'VALUE_3',
        updusr_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        bpades_0: 'VALUE_3',
        credat_0: new Date().toISOString().split('T')[0],
        extnum_0: 'VALUE_3',
        bpatyp_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        bpaadd_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        bpanum_0: 'VALUE_3',
        bpaaddflg_0: 'VALUE_3',
        tel_0: 'VALUE_3',
        bpabid_0: 'VALUE_3',
        cty_0: 'VALUE_3',
        cry_0: 'VALUE_3',
        xsrvfac_0: 'VALUE_3',
        ypohmel_0: 'VALUE_3',
      },
      {
        crn_0: 'VALUE_4',
        adrval_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        glncod_0: 'VALUE_4',
        fcyweb_0: 'VALUE_4',
        xedicod_0: 'VALUE_4',
        xext2num_0: 'BPA0004',
        x4valid_0: 'VALUE_4',
        x4adrfab_0: 'VALUE_4',
        x4adrexp_0: 'VALUE_4',
        x4eecnum_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        x4ediqual_0: 'VALUE_4',
        fax_0: 'VALUE_4',
        bpaaddlig_0: 'VALUE_4',
        crynam_0: 'Nom pays 4',
        web_0: 'VALUE_4',
        mob_0: 'VALUE_4',
        sat_0: 'VALUE_4',
        poscod_0: 'VALUE_4',
        codsee_0: 'VALUE_4',
        updusr_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        bpades_0: 'VALUE_4',
        credat_0: new Date().toISOString().split('T')[0],
        extnum_0: 'VALUE_4',
        bpatyp_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        bpaadd_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        bpanum_0: 'VALUE_4',
        bpaaddflg_0: 'VALUE_4',
        tel_0: 'VALUE_4',
        bpabid_0: 'VALUE_4',
        cty_0: 'VALUE_4',
        cry_0: 'VALUE_4',
        xsrvfac_0: 'VALUE_4',
        ypohmel_0: 'VALUE_4',
      },
      {
        crn_0: 'VALUE_5',
        adrval_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        glncod_0: 'VALUE_5',
        fcyweb_0: 'VALUE_5',
        xedicod_0: 'VALUE_5',
        xext2num_0: 'BPA0005',
        x4valid_0: 'VALUE_5',
        x4adrfab_0: 'VALUE_5',
        x4adrexp_0: 'VALUE_5',
        x4eecnum_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        x4ediqual_0: 'VALUE_5',
        fax_0: 'VALUE_5',
        bpaaddlig_0: 'VALUE_5',
        crynam_0: 'Nom pays 5',
        web_0: 'VALUE_5',
        mob_0: 'VALUE_5',
        sat_0: 'VALUE_5',
        poscod_0: 'VALUE_5',
        codsee_0: 'VALUE_5',
        updusr_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        bpades_0: 'VALUE_5',
        credat_0: new Date().toISOString().split('T')[0],
        extnum_0: 'VALUE_5',
        bpatyp_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        bpaadd_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        bpanum_0: 'VALUE_5',
        bpaaddflg_0: 'VALUE_5',
        tel_0: 'VALUE_5',
        bpabid_0: 'VALUE_5',
        cty_0: 'VALUE_5',
        cry_0: 'VALUE_5',
        xsrvfac_0: 'VALUE_5',
        ypohmel_0: 'VALUE_5',
      },
      {
        crn_0: 'VALUE_6',
        adrval_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        glncod_0: 'VALUE_6',
        fcyweb_0: 'VALUE_6',
        xedicod_0: 'VALUE_6',
        xext2num_0: 'BPA0006',
        x4valid_0: 'VALUE_6',
        x4adrfab_0: 'VALUE_6',
        x4adrexp_0: 'VALUE_6',
        x4eecnum_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        x4ediqual_0: 'VALUE_6',
        fax_0: 'VALUE_6',
        bpaaddlig_0: 'VALUE_6',
        crynam_0: 'Nom pays 6',
        web_0: 'VALUE_6',
        mob_0: 'VALUE_6',
        sat_0: 'VALUE_6',
        poscod_0: 'VALUE_6',
        codsee_0: 'VALUE_6',
        updusr_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        bpades_0: 'VALUE_6',
        credat_0: new Date().toISOString().split('T')[0],
        extnum_0: 'VALUE_6',
        bpatyp_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        bpaadd_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        bpanum_0: 'VALUE_6',
        bpaaddflg_0: 'VALUE_6',
        tel_0: 'VALUE_6',
        bpabid_0: 'VALUE_6',
        cty_0: 'VALUE_6',
        cry_0: 'VALUE_6',
        xsrvfac_0: 'VALUE_6',
        ypohmel_0: 'VALUE_6',
      },
      {
        crn_0: 'VALUE_7',
        adrval_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        glncod_0: 'VALUE_7',
        fcyweb_0: 'VALUE_7',
        xedicod_0: 'VALUE_7',
        xext2num_0: 'BPA0007',
        x4valid_0: 'VALUE_7',
        x4adrfab_0: 'VALUE_7',
        x4adrexp_0: 'VALUE_7',
        x4eecnum_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        x4ediqual_0: 'VALUE_7',
        fax_0: 'VALUE_7',
        bpaaddlig_0: 'VALUE_7',
        crynam_0: 'Nom pays 7',
        web_0: 'VALUE_7',
        mob_0: 'VALUE_7',
        sat_0: 'VALUE_7',
        poscod_0: 'VALUE_7',
        codsee_0: 'VALUE_7',
        updusr_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        bpades_0: 'VALUE_7',
        credat_0: new Date().toISOString().split('T')[0],
        extnum_0: 'VALUE_7',
        bpatyp_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        bpaadd_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        bpanum_0: 'VALUE_7',
        bpaaddflg_0: 'VALUE_7',
        tel_0: 'VALUE_7',
        bpabid_0: 'VALUE_7',
        cty_0: 'VALUE_7',
        cry_0: 'VALUE_7',
        xsrvfac_0: 'VALUE_7',
        ypohmel_0: 'VALUE_7',
      },
      {
        crn_0: 'VALUE_8',
        adrval_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        glncod_0: 'VALUE_8',
        fcyweb_0: 'VALUE_8',
        xedicod_0: 'VALUE_8',
        xext2num_0: 'BPA0008',
        x4valid_0: 'VALUE_8',
        x4adrfab_0: 'VALUE_8',
        x4adrexp_0: 'VALUE_8',
        x4eecnum_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        x4ediqual_0: 'VALUE_8',
        fax_0: 'VALUE_8',
        bpaaddlig_0: 'VALUE_8',
        crynam_0: 'Nom pays 8',
        web_0: 'VALUE_8',
        mob_0: 'VALUE_8',
        sat_0: 'VALUE_8',
        poscod_0: 'VALUE_8',
        codsee_0: 'VALUE_8',
        updusr_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        bpades_0: 'VALUE_8',
        credat_0: new Date().toISOString().split('T')[0],
        extnum_0: 'VALUE_8',
        bpatyp_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        bpaadd_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        bpanum_0: 'VALUE_8',
        bpaaddflg_0: 'VALUE_8',
        tel_0: 'VALUE_8',
        bpabid_0: 'VALUE_8',
        cty_0: 'VALUE_8',
        cry_0: 'VALUE_8',
        xsrvfac_0: 'VALUE_8',
        ypohmel_0: 'VALUE_8',
      },
      {
        crn_0: 'VALUE_9',
        adrval_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        glncod_0: 'VALUE_9',
        fcyweb_0: 'VALUE_9',
        xedicod_0: 'VALUE_9',
        xext2num_0: 'BPA0009',
        x4valid_0: 'VALUE_9',
        x4adrfab_0: 'VALUE_9',
        x4adrexp_0: 'VALUE_9',
        x4eecnum_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        x4ediqual_0: 'VALUE_9',
        fax_0: 'VALUE_9',
        bpaaddlig_0: 'VALUE_9',
        crynam_0: 'Nom pays 9',
        web_0: 'VALUE_9',
        mob_0: 'VALUE_9',
        sat_0: 'VALUE_9',
        poscod_0: 'VALUE_9',
        codsee_0: 'VALUE_9',
        updusr_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        bpades_0: 'VALUE_9',
        credat_0: new Date().toISOString().split('T')[0],
        extnum_0: 'VALUE_9',
        bpatyp_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        bpaadd_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        bpanum_0: 'VALUE_9',
        bpaaddflg_0: 'VALUE_9',
        tel_0: 'VALUE_9',
        bpabid_0: 'VALUE_9',
        cty_0: 'VALUE_9',
        cry_0: 'VALUE_9',
        xsrvfac_0: 'VALUE_9',
        ypohmel_0: 'VALUE_9',
      },
      {
        crn_0: 'VALUE_10',
        adrval_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        glncod_0: 'VALUE_10',
        fcyweb_0: 'VALUE_10',
        xedicod_0: 'VALUE_10',
        xext2num_0: 'BPA0010',
        x4valid_0: 'VALUE_10',
        x4adrfab_0: 'VALUE_10',
        x4adrexp_0: 'VALUE_10',
        x4eecnum_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        x4ediqual_0: 'VALUE_10',
        fax_0: 'VALUE_10',
        bpaaddlig_0: 'VALUE_10',
        crynam_0: 'Nom pays 10',
        web_0: 'VALUE_10',
        mob_0: 'VALUE_10',
        sat_0: 'VALUE_10',
        poscod_0: 'VALUE_10',
        codsee_0: 'VALUE_10',
        updusr_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        bpades_0: 'VALUE_10',
        credat_0: new Date().toISOString().split('T')[0],
        extnum_0: 'VALUE_10',
        bpatyp_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        bpaadd_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        bpanum_0: 'VALUE_10',
        bpaaddflg_0: 'VALUE_10',
        tel_0: 'VALUE_10',
        bpabid_0: 'VALUE_10',
        cty_0: 'VALUE_10',
        cry_0: 'VALUE_10',
        xsrvfac_0: 'VALUE_10',
        ypohmel_0: 'VALUE_10',
      },
    ]

    await Database.table('bpaddress').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans bpaddress`)
  }
}
