import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour BPCUSTOMER
    const data = [
      {
        ime_0: 'VALUE_1',
        cntlasdat_0: new Date().toISOString().split('T')[0],
        cntlastyp_0: 'VALUE_1',
        pitcdt_0: 'VALUE_1',
        cotpitrqd_0: 'VALUE_1',
        cntfirdat_0: new Date().toISOString().split('T')[0],
        ordfirdat_0: new Date().toISOString().split('T')[0],
        x_blcnbr_0: 'VALUE_1',
        x_blvalo_0: 'VALUE_1',
        cdtisrdat_0: new Date().toISOString().split('T')[0],
        soiper_0: 'VALUE_1',
        vatexn_0: 'VALUE_1',
        bpaadd_0: 'VALUE_1',
        cntnam_0: 'Nom contact par defaut 1',
        cntnexdat_0: new Date().toISOString().split('T')[0],
        daymon_0: 'VALUE_1',
        ostctl_0: 'VALUE_1',
        bpcrem_0: 'VALUE_1',
        strdatefat_0: new Date().toISOString().split('T')[0],
        cntefat_0: 'VALUE_1',
        agtpcp_0: 'VALUE_1',
        ostauz_0: 1,
        cdtisr_0: 'VALUE_1',
        fuptyp_0: 'VALUE_1',
        acccod_0: 'VALUE_1',
        xsitemad_0: 'VALUE_1',
        bpcsncdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_1',
        uvycod2_0: 'VALUE_1',
        x4demchor_0: 'VALUE_1',
        x4service_0: 'VALUE_1',
        x4engagement_0: 'VALUE_1',
        electinv_0: 'VALUE_1',
        aeiflg_0: 'VALUE_1',
        die_0: 'VALUE_1',
        bpcrsk_0: 'VALUE_1',
        belvatsub_0: 'VALUE_1',
        xicmajbl_0: 'VALUE_1',
        xyeaexo_0: 'VALUE_1',
        xautofact_0: 'VALUE_1',
        x4fctcli_0: 'VALUE_1',
        x4filflg_0: 'VALUE_1',
        x4regrel_0: 'VALUE_1',
        x4tolgen_0: 'VALUE_1',
        x4mrgtrsapp_0: 'VALUE_1',
        x1cdprsp_0: 'VALUE_1',
        x1site_0: 'VALUE_1',
        x1tolflg_0: 'VALUE_1',
        x1tolmax_0: 'VALUE_1',
        x1tolmin_0: 'VALUE_1',
        bpccdtisr_0: 'VALUE_1',
        vatstrdat_0: new Date().toISOString().split('T')[0],
        vatenddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        invcnd_0: 'VALUE_1',
        bpdadd_0: 'VALUE_1',
        prityp_0: 10.5,
        tpmcod_0: 'VALUE_1',
        bpcnam_0: 'VALUE_1',
        bpcinv_0: 'VALUE_1',
        bpcpyr_0: 'VALUE_1',
        bpcgru_0: 'VALUE_1',
        bpcsta_0: 1,
        pptflg_0: 'VALUE_1',
        bpcbpsnum_0: 'BPC0001',
        freinv_0: 'VALUE_1',
        fupminamt_0: 10.5,
        invdtaamt_0: 10.5,
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        agtsattax_0: 'VALUE_1',
        flgsattax_0: true,
        sattax_0: 'VALUE_1',
        cotchx_0: 'VALUE_1',
        totpit_0: 'VALUE_1',
        bus_0: 'VALUE_1',
        xamtexo_0: 10.5,
        dep_0: 'VALUE_1',
        tsccod_0: 'VALUE_1',
        orippt_0: 'VALUE_1',
        pitcpt_0: 'VALUE_1',
        payban_0: 'VALUE_1',
        cce_0: 'VALUE_1',
        bpcsho_0: 'VALUE_1',
        bcgcod_0: 'VALUE_1',
        grp_0: 'VALUE_1',
        bpctyp_0: 'VALUE_1',
        lndauz_0: 'VALUE_1',
        xcur_0: 'VALUE_1',
        dia_0: 'VALUE_1',
        copnbr_0: 'VALUE_1',
        invper_0: 'VALUE_1',
        ordcle_0: 'VALUE_1',
        odl_0: 'VALUE_1',
        quolasdat_0: new Date().toISOString().split('T')[0],
        rep_0: 'VALUE_1',
        chgtyp_0: 'VALUE_1',
        ordminamt_0: 10.5,
        cntnextyp_0: 'VALUE_1',
        updusr_0: 'VALUE_1',
        abccls_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        bpainv_0: 'VALUE_1',
        bpapyr_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        cshvatrgm_0: 'VALUE_1',
        pte_0: 'VALUE_1',
        invdta_0: 'VALUE_1',
        bpcnum_0: 'VALUE_1',
        fctnum_0: 'VALUE_1',
        comcat_0: 'VALUE_1',
        vacbpr_0: 'VALUE_1',
        xvacbpr_0: 'VALUE_1',
        cur_0: 'VALUE_1',
        mtcflg_0: 'VALUE_1',
        ordtex_0: 'VALUE_1',
        invtex_0: 'VALUE_1',
        ocnflg_0: 'VALUE_1',
        dudclc_0: 'VALUE_1',
        dme_0: 'VALUE_1',
      },
      {
        ime_0: 'VALUE_2',
        cntlasdat_0: new Date().toISOString().split('T')[0],
        cntlastyp_0: 'VALUE_2',
        pitcdt_0: 'VALUE_2',
        cotpitrqd_0: 'VALUE_2',
        cntfirdat_0: new Date().toISOString().split('T')[0],
        ordfirdat_0: new Date().toISOString().split('T')[0],
        x_blcnbr_0: 'VALUE_2',
        x_blvalo_0: 'VALUE_2',
        cdtisrdat_0: new Date().toISOString().split('T')[0],
        soiper_0: 'VALUE_2',
        vatexn_0: 'VALUE_2',
        bpaadd_0: 'VALUE_2',
        cntnam_0: 'Nom contact par defaut 2',
        cntnexdat_0: new Date().toISOString().split('T')[0],
        daymon_0: 'VALUE_2',
        ostctl_0: 'VALUE_2',
        bpcrem_0: 'VALUE_2',
        strdatefat_0: new Date().toISOString().split('T')[0],
        cntefat_0: 'VALUE_2',
        agtpcp_0: 'VALUE_2',
        ostauz_0: 2,
        cdtisr_0: 'VALUE_2',
        fuptyp_0: 'VALUE_2',
        acccod_0: 'VALUE_2',
        xsitemad_0: 'VALUE_2',
        bpcsncdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_2',
        uvycod2_0: 'VALUE_2',
        x4demchor_0: 'VALUE_2',
        x4service_0: 'VALUE_2',
        x4engagement_0: 'VALUE_2',
        electinv_0: 'VALUE_2',
        aeiflg_0: 'VALUE_2',
        die_0: 'VALUE_2',
        bpcrsk_0: 'VALUE_2',
        belvatsub_0: 'VALUE_2',
        xicmajbl_0: 'VALUE_2',
        xyeaexo_0: 'VALUE_2',
        xautofact_0: 'VALUE_2',
        x4fctcli_0: 'VALUE_2',
        x4filflg_0: 'VALUE_2',
        x4regrel_0: 'VALUE_2',
        x4tolgen_0: 'VALUE_2',
        x4mrgtrsapp_0: 'VALUE_2',
        x1cdprsp_0: 'VALUE_2',
        x1site_0: 'VALUE_2',
        x1tolflg_0: 'VALUE_2',
        x1tolmax_0: 'VALUE_2',
        x1tolmin_0: 'VALUE_2',
        bpccdtisr_0: 'VALUE_2',
        vatstrdat_0: new Date().toISOString().split('T')[0],
        vatenddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        invcnd_0: 'VALUE_2',
        bpdadd_0: 'VALUE_2',
        prityp_0: 21.0,
        tpmcod_0: 'VALUE_2',
        bpcnam_0: 'VALUE_2',
        bpcinv_0: 'VALUE_2',
        bpcpyr_0: 'VALUE_2',
        bpcgru_0: 'VALUE_2',
        bpcsta_0: 1,
        pptflg_0: 'VALUE_2',
        bpcbpsnum_0: 'BPC0002',
        freinv_0: 'VALUE_2',
        fupminamt_0: 21.0,
        invdtaamt_0: 21.0,
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        agtsattax_0: 'VALUE_2',
        flgsattax_0: true,
        sattax_0: 'VALUE_2',
        cotchx_0: 'VALUE_2',
        totpit_0: 'VALUE_2',
        bus_0: 'VALUE_2',
        xamtexo_0: 21.0,
        dep_0: 'VALUE_2',
        tsccod_0: 'VALUE_2',
        orippt_0: 'VALUE_2',
        pitcpt_0: 'VALUE_2',
        payban_0: 'VALUE_2',
        cce_0: 'VALUE_2',
        bpcsho_0: 'VALUE_2',
        bcgcod_0: 'VALUE_2',
        grp_0: 'VALUE_2',
        bpctyp_0: 'VALUE_2',
        lndauz_0: 'VALUE_2',
        xcur_0: 'VALUE_2',
        dia_0: 'VALUE_2',
        copnbr_0: 'VALUE_2',
        invper_0: 'VALUE_2',
        ordcle_0: 'VALUE_2',
        odl_0: 'VALUE_2',
        quolasdat_0: new Date().toISOString().split('T')[0],
        rep_0: 'VALUE_2',
        chgtyp_0: 'VALUE_2',
        ordminamt_0: 21.0,
        cntnextyp_0: 'VALUE_2',
        updusr_0: 'VALUE_2',
        abccls_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        bpainv_0: 'VALUE_2',
        bpapyr_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        cshvatrgm_0: 'VALUE_2',
        pte_0: 'VALUE_2',
        invdta_0: 'VALUE_2',
        bpcnum_0: 'VALUE_2',
        fctnum_0: 'VALUE_2',
        comcat_0: 'VALUE_2',
        vacbpr_0: 'VALUE_2',
        xvacbpr_0: 'VALUE_2',
        cur_0: 'VALUE_2',
        mtcflg_0: 'VALUE_2',
        ordtex_0: 'VALUE_2',
        invtex_0: 'VALUE_2',
        ocnflg_0: 'VALUE_2',
        dudclc_0: 'VALUE_2',
        dme_0: 'VALUE_2',
      },
      {
        ime_0: 'VALUE_3',
        cntlasdat_0: new Date().toISOString().split('T')[0],
        cntlastyp_0: 'VALUE_3',
        pitcdt_0: 'VALUE_3',
        cotpitrqd_0: 'VALUE_3',
        cntfirdat_0: new Date().toISOString().split('T')[0],
        ordfirdat_0: new Date().toISOString().split('T')[0],
        x_blcnbr_0: 'VALUE_3',
        x_blvalo_0: 'VALUE_3',
        cdtisrdat_0: new Date().toISOString().split('T')[0],
        soiper_0: 'VALUE_3',
        vatexn_0: 'VALUE_3',
        bpaadd_0: 'VALUE_3',
        cntnam_0: 'Nom contact par defaut 3',
        cntnexdat_0: new Date().toISOString().split('T')[0],
        daymon_0: 'VALUE_3',
        ostctl_0: 'VALUE_3',
        bpcrem_0: 'VALUE_3',
        strdatefat_0: new Date().toISOString().split('T')[0],
        cntefat_0: 'VALUE_3',
        agtpcp_0: 'VALUE_3',
        ostauz_0: 3,
        cdtisr_0: 'VALUE_3',
        fuptyp_0: 'VALUE_3',
        acccod_0: 'VALUE_3',
        xsitemad_0: 'VALUE_3',
        bpcsncdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_3',
        uvycod2_0: 'VALUE_3',
        x4demchor_0: 'VALUE_3',
        x4service_0: 'VALUE_3',
        x4engagement_0: 'VALUE_3',
        electinv_0: 'VALUE_3',
        aeiflg_0: 'VALUE_3',
        die_0: 'VALUE_3',
        bpcrsk_0: 'VALUE_3',
        belvatsub_0: 'VALUE_3',
        xicmajbl_0: 'VALUE_3',
        xyeaexo_0: 'VALUE_3',
        xautofact_0: 'VALUE_3',
        x4fctcli_0: 'VALUE_3',
        x4filflg_0: 'VALUE_3',
        x4regrel_0: 'VALUE_3',
        x4tolgen_0: 'VALUE_3',
        x4mrgtrsapp_0: 'VALUE_3',
        x1cdprsp_0: 'VALUE_3',
        x1site_0: 'VALUE_3',
        x1tolflg_0: 'VALUE_3',
        x1tolmax_0: 'VALUE_3',
        x1tolmin_0: 'VALUE_3',
        bpccdtisr_0: 'VALUE_3',
        vatstrdat_0: new Date().toISOString().split('T')[0],
        vatenddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        invcnd_0: 'VALUE_3',
        bpdadd_0: 'VALUE_3',
        prityp_0: 31.5,
        tpmcod_0: 'VALUE_3',
        bpcnam_0: 'VALUE_3',
        bpcinv_0: 'VALUE_3',
        bpcpyr_0: 'VALUE_3',
        bpcgru_0: 'VALUE_3',
        bpcsta_0: 1,
        pptflg_0: 'VALUE_3',
        bpcbpsnum_0: 'BPC0003',
        freinv_0: 'VALUE_3',
        fupminamt_0: 31.5,
        invdtaamt_0: 31.5,
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        agtsattax_0: 'VALUE_3',
        flgsattax_0: true,
        sattax_0: 'VALUE_3',
        cotchx_0: 'VALUE_3',
        totpit_0: 'VALUE_3',
        bus_0: 'VALUE_3',
        xamtexo_0: 31.5,
        dep_0: 'VALUE_3',
        tsccod_0: 'VALUE_3',
        orippt_0: 'VALUE_3',
        pitcpt_0: 'VALUE_3',
        payban_0: 'VALUE_3',
        cce_0: 'VALUE_3',
        bpcsho_0: 'VALUE_3',
        bcgcod_0: 'VALUE_3',
        grp_0: 'VALUE_3',
        bpctyp_0: 'VALUE_3',
        lndauz_0: 'VALUE_3',
        xcur_0: 'VALUE_3',
        dia_0: 'VALUE_3',
        copnbr_0: 'VALUE_3',
        invper_0: 'VALUE_3',
        ordcle_0: 'VALUE_3',
        odl_0: 'VALUE_3',
        quolasdat_0: new Date().toISOString().split('T')[0],
        rep_0: 'VALUE_3',
        chgtyp_0: 'VALUE_3',
        ordminamt_0: 31.5,
        cntnextyp_0: 'VALUE_3',
        updusr_0: 'VALUE_3',
        abccls_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        bpainv_0: 'VALUE_3',
        bpapyr_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        cshvatrgm_0: 'VALUE_3',
        pte_0: 'VALUE_3',
        invdta_0: 'VALUE_3',
        bpcnum_0: 'VALUE_3',
        fctnum_0: 'VALUE_3',
        comcat_0: 'VALUE_3',
        vacbpr_0: 'VALUE_3',
        xvacbpr_0: 'VALUE_3',
        cur_0: 'VALUE_3',
        mtcflg_0: 'VALUE_3',
        ordtex_0: 'VALUE_3',
        invtex_0: 'VALUE_3',
        ocnflg_0: 'VALUE_3',
        dudclc_0: 'VALUE_3',
        dme_0: 'VALUE_3',
      },
      {
        ime_0: 'VALUE_4',
        cntlasdat_0: new Date().toISOString().split('T')[0],
        cntlastyp_0: 'VALUE_4',
        pitcdt_0: 'VALUE_4',
        cotpitrqd_0: 'VALUE_4',
        cntfirdat_0: new Date().toISOString().split('T')[0],
        ordfirdat_0: new Date().toISOString().split('T')[0],
        x_blcnbr_0: 'VALUE_4',
        x_blvalo_0: 'VALUE_4',
        cdtisrdat_0: new Date().toISOString().split('T')[0],
        soiper_0: 'VALUE_4',
        vatexn_0: 'VALUE_4',
        bpaadd_0: 'VALUE_4',
        cntnam_0: 'Nom contact par defaut 4',
        cntnexdat_0: new Date().toISOString().split('T')[0],
        daymon_0: 'VALUE_4',
        ostctl_0: 'VALUE_4',
        bpcrem_0: 'VALUE_4',
        strdatefat_0: new Date().toISOString().split('T')[0],
        cntefat_0: 'VALUE_4',
        agtpcp_0: 'VALUE_4',
        ostauz_0: 4,
        cdtisr_0: 'VALUE_4',
        fuptyp_0: 'VALUE_4',
        acccod_0: 'VALUE_4',
        xsitemad_0: 'VALUE_4',
        bpcsncdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_4',
        uvycod2_0: 'VALUE_4',
        x4demchor_0: 'VALUE_4',
        x4service_0: 'VALUE_4',
        x4engagement_0: 'VALUE_4',
        electinv_0: 'VALUE_4',
        aeiflg_0: 'VALUE_4',
        die_0: 'VALUE_4',
        bpcrsk_0: 'VALUE_4',
        belvatsub_0: 'VALUE_4',
        xicmajbl_0: 'VALUE_4',
        xyeaexo_0: 'VALUE_4',
        xautofact_0: 'VALUE_4',
        x4fctcli_0: 'VALUE_4',
        x4filflg_0: 'VALUE_4',
        x4regrel_0: 'VALUE_4',
        x4tolgen_0: 'VALUE_4',
        x4mrgtrsapp_0: 'VALUE_4',
        x1cdprsp_0: 'VALUE_4',
        x1site_0: 'VALUE_4',
        x1tolflg_0: 'VALUE_4',
        x1tolmax_0: 'VALUE_4',
        x1tolmin_0: 'VALUE_4',
        bpccdtisr_0: 'VALUE_4',
        vatstrdat_0: new Date().toISOString().split('T')[0],
        vatenddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        invcnd_0: 'VALUE_4',
        bpdadd_0: 'VALUE_4',
        prityp_0: 42.0,
        tpmcod_0: 'VALUE_4',
        bpcnam_0: 'VALUE_4',
        bpcinv_0: 'VALUE_4',
        bpcpyr_0: 'VALUE_4',
        bpcgru_0: 'VALUE_4',
        bpcsta_0: 1,
        pptflg_0: 'VALUE_4',
        bpcbpsnum_0: 'BPC0004',
        freinv_0: 'VALUE_4',
        fupminamt_0: 42.0,
        invdtaamt_0: 42.0,
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        agtsattax_0: 'VALUE_4',
        flgsattax_0: true,
        sattax_0: 'VALUE_4',
        cotchx_0: 'VALUE_4',
        totpit_0: 'VALUE_4',
        bus_0: 'VALUE_4',
        xamtexo_0: 42.0,
        dep_0: 'VALUE_4',
        tsccod_0: 'VALUE_4',
        orippt_0: 'VALUE_4',
        pitcpt_0: 'VALUE_4',
        payban_0: 'VALUE_4',
        cce_0: 'VALUE_4',
        bpcsho_0: 'VALUE_4',
        bcgcod_0: 'VALUE_4',
        grp_0: 'VALUE_4',
        bpctyp_0: 'VALUE_4',
        lndauz_0: 'VALUE_4',
        xcur_0: 'VALUE_4',
        dia_0: 'VALUE_4',
        copnbr_0: 'VALUE_4',
        invper_0: 'VALUE_4',
        ordcle_0: 'VALUE_4',
        odl_0: 'VALUE_4',
        quolasdat_0: new Date().toISOString().split('T')[0],
        rep_0: 'VALUE_4',
        chgtyp_0: 'VALUE_4',
        ordminamt_0: 42.0,
        cntnextyp_0: 'VALUE_4',
        updusr_0: 'VALUE_4',
        abccls_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        bpainv_0: 'VALUE_4',
        bpapyr_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        cshvatrgm_0: 'VALUE_4',
        pte_0: 'VALUE_4',
        invdta_0: 'VALUE_4',
        bpcnum_0: 'VALUE_4',
        fctnum_0: 'VALUE_4',
        comcat_0: 'VALUE_4',
        vacbpr_0: 'VALUE_4',
        xvacbpr_0: 'VALUE_4',
        cur_0: 'VALUE_4',
        mtcflg_0: 'VALUE_4',
        ordtex_0: 'VALUE_4',
        invtex_0: 'VALUE_4',
        ocnflg_0: 'VALUE_4',
        dudclc_0: 'VALUE_4',
        dme_0: 'VALUE_4',
      },
      {
        ime_0: 'VALUE_5',
        cntlasdat_0: new Date().toISOString().split('T')[0],
        cntlastyp_0: 'VALUE_5',
        pitcdt_0: 'VALUE_5',
        cotpitrqd_0: 'VALUE_5',
        cntfirdat_0: new Date().toISOString().split('T')[0],
        ordfirdat_0: new Date().toISOString().split('T')[0],
        x_blcnbr_0: 'VALUE_5',
        x_blvalo_0: 'VALUE_5',
        cdtisrdat_0: new Date().toISOString().split('T')[0],
        soiper_0: 'VALUE_5',
        vatexn_0: 'VALUE_5',
        bpaadd_0: 'VALUE_5',
        cntnam_0: 'Nom contact par defaut 5',
        cntnexdat_0: new Date().toISOString().split('T')[0],
        daymon_0: 'VALUE_5',
        ostctl_0: 'VALUE_5',
        bpcrem_0: 'VALUE_5',
        strdatefat_0: new Date().toISOString().split('T')[0],
        cntefat_0: 'VALUE_5',
        agtpcp_0: 'VALUE_5',
        ostauz_0: 5,
        cdtisr_0: 'VALUE_5',
        fuptyp_0: 'VALUE_5',
        acccod_0: 'VALUE_5',
        xsitemad_0: 'VALUE_5',
        bpcsncdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_5',
        uvycod2_0: 'VALUE_5',
        x4demchor_0: 'VALUE_5',
        x4service_0: 'VALUE_5',
        x4engagement_0: 'VALUE_5',
        electinv_0: 'VALUE_5',
        aeiflg_0: 'VALUE_5',
        die_0: 'VALUE_5',
        bpcrsk_0: 'VALUE_5',
        belvatsub_0: 'VALUE_5',
        xicmajbl_0: 'VALUE_5',
        xyeaexo_0: 'VALUE_5',
        xautofact_0: 'VALUE_5',
        x4fctcli_0: 'VALUE_5',
        x4filflg_0: 'VALUE_5',
        x4regrel_0: 'VALUE_5',
        x4tolgen_0: 'VALUE_5',
        x4mrgtrsapp_0: 'VALUE_5',
        x1cdprsp_0: 'VALUE_5',
        x1site_0: 'VALUE_5',
        x1tolflg_0: 'VALUE_5',
        x1tolmax_0: 'VALUE_5',
        x1tolmin_0: 'VALUE_5',
        bpccdtisr_0: 'VALUE_5',
        vatstrdat_0: new Date().toISOString().split('T')[0],
        vatenddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        invcnd_0: 'VALUE_5',
        bpdadd_0: 'VALUE_5',
        prityp_0: 52.5,
        tpmcod_0: 'VALUE_5',
        bpcnam_0: 'VALUE_5',
        bpcinv_0: 'VALUE_5',
        bpcpyr_0: 'VALUE_5',
        bpcgru_0: 'VALUE_5',
        bpcsta_0: 1,
        pptflg_0: 'VALUE_5',
        bpcbpsnum_0: 'BPC0005',
        freinv_0: 'VALUE_5',
        fupminamt_0: 52.5,
        invdtaamt_0: 52.5,
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        agtsattax_0: 'VALUE_5',
        flgsattax_0: true,
        sattax_0: 'VALUE_5',
        cotchx_0: 'VALUE_5',
        totpit_0: 'VALUE_5',
        bus_0: 'VALUE_5',
        xamtexo_0: 52.5,
        dep_0: 'VALUE_5',
        tsccod_0: 'VALUE_5',
        orippt_0: 'VALUE_5',
        pitcpt_0: 'VALUE_5',
        payban_0: 'VALUE_5',
        cce_0: 'VALUE_5',
        bpcsho_0: 'VALUE_5',
        bcgcod_0: 'VALUE_5',
        grp_0: 'VALUE_5',
        bpctyp_0: 'VALUE_5',
        lndauz_0: 'VALUE_5',
        xcur_0: 'VALUE_5',
        dia_0: 'VALUE_5',
        copnbr_0: 'VALUE_5',
        invper_0: 'VALUE_5',
        ordcle_0: 'VALUE_5',
        odl_0: 'VALUE_5',
        quolasdat_0: new Date().toISOString().split('T')[0],
        rep_0: 'VALUE_5',
        chgtyp_0: 'VALUE_5',
        ordminamt_0: 52.5,
        cntnextyp_0: 'VALUE_5',
        updusr_0: 'VALUE_5',
        abccls_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        bpainv_0: 'VALUE_5',
        bpapyr_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        cshvatrgm_0: 'VALUE_5',
        pte_0: 'VALUE_5',
        invdta_0: 'VALUE_5',
        bpcnum_0: 'VALUE_5',
        fctnum_0: 'VALUE_5',
        comcat_0: 'VALUE_5',
        vacbpr_0: 'VALUE_5',
        xvacbpr_0: 'VALUE_5',
        cur_0: 'VALUE_5',
        mtcflg_0: 'VALUE_5',
        ordtex_0: 'VALUE_5',
        invtex_0: 'VALUE_5',
        ocnflg_0: 'VALUE_5',
        dudclc_0: 'VALUE_5',
        dme_0: 'VALUE_5',
      },
      {
        ime_0: 'VALUE_6',
        cntlasdat_0: new Date().toISOString().split('T')[0],
        cntlastyp_0: 'VALUE_6',
        pitcdt_0: 'VALUE_6',
        cotpitrqd_0: 'VALUE_6',
        cntfirdat_0: new Date().toISOString().split('T')[0],
        ordfirdat_0: new Date().toISOString().split('T')[0],
        x_blcnbr_0: 'VALUE_6',
        x_blvalo_0: 'VALUE_6',
        cdtisrdat_0: new Date().toISOString().split('T')[0],
        soiper_0: 'VALUE_6',
        vatexn_0: 'VALUE_6',
        bpaadd_0: 'VALUE_6',
        cntnam_0: 'Nom contact par defaut 6',
        cntnexdat_0: new Date().toISOString().split('T')[0],
        daymon_0: 'VALUE_6',
        ostctl_0: 'VALUE_6',
        bpcrem_0: 'VALUE_6',
        strdatefat_0: new Date().toISOString().split('T')[0],
        cntefat_0: 'VALUE_6',
        agtpcp_0: 'VALUE_6',
        ostauz_0: 6,
        cdtisr_0: 'VALUE_6',
        fuptyp_0: 'VALUE_6',
        acccod_0: 'VALUE_6',
        xsitemad_0: 'VALUE_6',
        bpcsncdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_6',
        uvycod2_0: 'VALUE_6',
        x4demchor_0: 'VALUE_6',
        x4service_0: 'VALUE_6',
        x4engagement_0: 'VALUE_6',
        electinv_0: 'VALUE_6',
        aeiflg_0: 'VALUE_6',
        die_0: 'VALUE_6',
        bpcrsk_0: 'VALUE_6',
        belvatsub_0: 'VALUE_6',
        xicmajbl_0: 'VALUE_6',
        xyeaexo_0: 'VALUE_6',
        xautofact_0: 'VALUE_6',
        x4fctcli_0: 'VALUE_6',
        x4filflg_0: 'VALUE_6',
        x4regrel_0: 'VALUE_6',
        x4tolgen_0: 'VALUE_6',
        x4mrgtrsapp_0: 'VALUE_6',
        x1cdprsp_0: 'VALUE_6',
        x1site_0: 'VALUE_6',
        x1tolflg_0: 'VALUE_6',
        x1tolmax_0: 'VALUE_6',
        x1tolmin_0: 'VALUE_6',
        bpccdtisr_0: 'VALUE_6',
        vatstrdat_0: new Date().toISOString().split('T')[0],
        vatenddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        invcnd_0: 'VALUE_6',
        bpdadd_0: 'VALUE_6',
        prityp_0: 63.0,
        tpmcod_0: 'VALUE_6',
        bpcnam_0: 'VALUE_6',
        bpcinv_0: 'VALUE_6',
        bpcpyr_0: 'VALUE_6',
        bpcgru_0: 'VALUE_6',
        bpcsta_0: 1,
        pptflg_0: 'VALUE_6',
        bpcbpsnum_0: 'BPC0006',
        freinv_0: 'VALUE_6',
        fupminamt_0: 63.0,
        invdtaamt_0: 63.0,
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        agtsattax_0: 'VALUE_6',
        flgsattax_0: true,
        sattax_0: 'VALUE_6',
        cotchx_0: 'VALUE_6',
        totpit_0: 'VALUE_6',
        bus_0: 'VALUE_6',
        xamtexo_0: 63.0,
        dep_0: 'VALUE_6',
        tsccod_0: 'VALUE_6',
        orippt_0: 'VALUE_6',
        pitcpt_0: 'VALUE_6',
        payban_0: 'VALUE_6',
        cce_0: 'VALUE_6',
        bpcsho_0: 'VALUE_6',
        bcgcod_0: 'VALUE_6',
        grp_0: 'VALUE_6',
        bpctyp_0: 'VALUE_6',
        lndauz_0: 'VALUE_6',
        xcur_0: 'VALUE_6',
        dia_0: 'VALUE_6',
        copnbr_0: 'VALUE_6',
        invper_0: 'VALUE_6',
        ordcle_0: 'VALUE_6',
        odl_0: 'VALUE_6',
        quolasdat_0: new Date().toISOString().split('T')[0],
        rep_0: 'VALUE_6',
        chgtyp_0: 'VALUE_6',
        ordminamt_0: 63.0,
        cntnextyp_0: 'VALUE_6',
        updusr_0: 'VALUE_6',
        abccls_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        bpainv_0: 'VALUE_6',
        bpapyr_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        cshvatrgm_0: 'VALUE_6',
        pte_0: 'VALUE_6',
        invdta_0: 'VALUE_6',
        bpcnum_0: 'VALUE_6',
        fctnum_0: 'VALUE_6',
        comcat_0: 'VALUE_6',
        vacbpr_0: 'VALUE_6',
        xvacbpr_0: 'VALUE_6',
        cur_0: 'VALUE_6',
        mtcflg_0: 'VALUE_6',
        ordtex_0: 'VALUE_6',
        invtex_0: 'VALUE_6',
        ocnflg_0: 'VALUE_6',
        dudclc_0: 'VALUE_6',
        dme_0: 'VALUE_6',
      },
      {
        ime_0: 'VALUE_7',
        cntlasdat_0: new Date().toISOString().split('T')[0],
        cntlastyp_0: 'VALUE_7',
        pitcdt_0: 'VALUE_7',
        cotpitrqd_0: 'VALUE_7',
        cntfirdat_0: new Date().toISOString().split('T')[0],
        ordfirdat_0: new Date().toISOString().split('T')[0],
        x_blcnbr_0: 'VALUE_7',
        x_blvalo_0: 'VALUE_7',
        cdtisrdat_0: new Date().toISOString().split('T')[0],
        soiper_0: 'VALUE_7',
        vatexn_0: 'VALUE_7',
        bpaadd_0: 'VALUE_7',
        cntnam_0: 'Nom contact par defaut 7',
        cntnexdat_0: new Date().toISOString().split('T')[0],
        daymon_0: 'VALUE_7',
        ostctl_0: 'VALUE_7',
        bpcrem_0: 'VALUE_7',
        strdatefat_0: new Date().toISOString().split('T')[0],
        cntefat_0: 'VALUE_7',
        agtpcp_0: 'VALUE_7',
        ostauz_0: 7,
        cdtisr_0: 'VALUE_7',
        fuptyp_0: 'VALUE_7',
        acccod_0: 'VALUE_7',
        xsitemad_0: 'VALUE_7',
        bpcsncdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_7',
        uvycod2_0: 'VALUE_7',
        x4demchor_0: 'VALUE_7',
        x4service_0: 'VALUE_7',
        x4engagement_0: 'VALUE_7',
        electinv_0: 'VALUE_7',
        aeiflg_0: 'VALUE_7',
        die_0: 'VALUE_7',
        bpcrsk_0: 'VALUE_7',
        belvatsub_0: 'VALUE_7',
        xicmajbl_0: 'VALUE_7',
        xyeaexo_0: 'VALUE_7',
        xautofact_0: 'VALUE_7',
        x4fctcli_0: 'VALUE_7',
        x4filflg_0: 'VALUE_7',
        x4regrel_0: 'VALUE_7',
        x4tolgen_0: 'VALUE_7',
        x4mrgtrsapp_0: 'VALUE_7',
        x1cdprsp_0: 'VALUE_7',
        x1site_0: 'VALUE_7',
        x1tolflg_0: 'VALUE_7',
        x1tolmax_0: 'VALUE_7',
        x1tolmin_0: 'VALUE_7',
        bpccdtisr_0: 'VALUE_7',
        vatstrdat_0: new Date().toISOString().split('T')[0],
        vatenddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        invcnd_0: 'VALUE_7',
        bpdadd_0: 'VALUE_7',
        prityp_0: 73.5,
        tpmcod_0: 'VALUE_7',
        bpcnam_0: 'VALUE_7',
        bpcinv_0: 'VALUE_7',
        bpcpyr_0: 'VALUE_7',
        bpcgru_0: 'VALUE_7',
        bpcsta_0: 1,
        pptflg_0: 'VALUE_7',
        bpcbpsnum_0: 'BPC0007',
        freinv_0: 'VALUE_7',
        fupminamt_0: 73.5,
        invdtaamt_0: 73.5,
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        agtsattax_0: 'VALUE_7',
        flgsattax_0: true,
        sattax_0: 'VALUE_7',
        cotchx_0: 'VALUE_7',
        totpit_0: 'VALUE_7',
        bus_0: 'VALUE_7',
        xamtexo_0: 73.5,
        dep_0: 'VALUE_7',
        tsccod_0: 'VALUE_7',
        orippt_0: 'VALUE_7',
        pitcpt_0: 'VALUE_7',
        payban_0: 'VALUE_7',
        cce_0: 'VALUE_7',
        bpcsho_0: 'VALUE_7',
        bcgcod_0: 'VALUE_7',
        grp_0: 'VALUE_7',
        bpctyp_0: 'VALUE_7',
        lndauz_0: 'VALUE_7',
        xcur_0: 'VALUE_7',
        dia_0: 'VALUE_7',
        copnbr_0: 'VALUE_7',
        invper_0: 'VALUE_7',
        ordcle_0: 'VALUE_7',
        odl_0: 'VALUE_7',
        quolasdat_0: new Date().toISOString().split('T')[0],
        rep_0: 'VALUE_7',
        chgtyp_0: 'VALUE_7',
        ordminamt_0: 73.5,
        cntnextyp_0: 'VALUE_7',
        updusr_0: 'VALUE_7',
        abccls_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        bpainv_0: 'VALUE_7',
        bpapyr_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        cshvatrgm_0: 'VALUE_7',
        pte_0: 'VALUE_7',
        invdta_0: 'VALUE_7',
        bpcnum_0: 'VALUE_7',
        fctnum_0: 'VALUE_7',
        comcat_0: 'VALUE_7',
        vacbpr_0: 'VALUE_7',
        xvacbpr_0: 'VALUE_7',
        cur_0: 'VALUE_7',
        mtcflg_0: 'VALUE_7',
        ordtex_0: 'VALUE_7',
        invtex_0: 'VALUE_7',
        ocnflg_0: 'VALUE_7',
        dudclc_0: 'VALUE_7',
        dme_0: 'VALUE_7',
      },
      {
        ime_0: 'VALUE_8',
        cntlasdat_0: new Date().toISOString().split('T')[0],
        cntlastyp_0: 'VALUE_8',
        pitcdt_0: 'VALUE_8',
        cotpitrqd_0: 'VALUE_8',
        cntfirdat_0: new Date().toISOString().split('T')[0],
        ordfirdat_0: new Date().toISOString().split('T')[0],
        x_blcnbr_0: 'VALUE_8',
        x_blvalo_0: 'VALUE_8',
        cdtisrdat_0: new Date().toISOString().split('T')[0],
        soiper_0: 'VALUE_8',
        vatexn_0: 'VALUE_8',
        bpaadd_0: 'VALUE_8',
        cntnam_0: 'Nom contact par defaut 8',
        cntnexdat_0: new Date().toISOString().split('T')[0],
        daymon_0: 'VALUE_8',
        ostctl_0: 'VALUE_8',
        bpcrem_0: 'VALUE_8',
        strdatefat_0: new Date().toISOString().split('T')[0],
        cntefat_0: 'VALUE_8',
        agtpcp_0: 'VALUE_8',
        ostauz_0: 8,
        cdtisr_0: 'VALUE_8',
        fuptyp_0: 'VALUE_8',
        acccod_0: 'VALUE_8',
        xsitemad_0: 'VALUE_8',
        bpcsncdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_8',
        uvycod2_0: 'VALUE_8',
        x4demchor_0: 'VALUE_8',
        x4service_0: 'VALUE_8',
        x4engagement_0: 'VALUE_8',
        electinv_0: 'VALUE_8',
        aeiflg_0: 'VALUE_8',
        die_0: 'VALUE_8',
        bpcrsk_0: 'VALUE_8',
        belvatsub_0: 'VALUE_8',
        xicmajbl_0: 'VALUE_8',
        xyeaexo_0: 'VALUE_8',
        xautofact_0: 'VALUE_8',
        x4fctcli_0: 'VALUE_8',
        x4filflg_0: 'VALUE_8',
        x4regrel_0: 'VALUE_8',
        x4tolgen_0: 'VALUE_8',
        x4mrgtrsapp_0: 'VALUE_8',
        x1cdprsp_0: 'VALUE_8',
        x1site_0: 'VALUE_8',
        x1tolflg_0: 'VALUE_8',
        x1tolmax_0: 'VALUE_8',
        x1tolmin_0: 'VALUE_8',
        bpccdtisr_0: 'VALUE_8',
        vatstrdat_0: new Date().toISOString().split('T')[0],
        vatenddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        invcnd_0: 'VALUE_8',
        bpdadd_0: 'VALUE_8',
        prityp_0: 84.0,
        tpmcod_0: 'VALUE_8',
        bpcnam_0: 'VALUE_8',
        bpcinv_0: 'VALUE_8',
        bpcpyr_0: 'VALUE_8',
        bpcgru_0: 'VALUE_8',
        bpcsta_0: 1,
        pptflg_0: 'VALUE_8',
        bpcbpsnum_0: 'BPC0008',
        freinv_0: 'VALUE_8',
        fupminamt_0: 84.0,
        invdtaamt_0: 84.0,
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        agtsattax_0: 'VALUE_8',
        flgsattax_0: true,
        sattax_0: 'VALUE_8',
        cotchx_0: 'VALUE_8',
        totpit_0: 'VALUE_8',
        bus_0: 'VALUE_8',
        xamtexo_0: 84.0,
        dep_0: 'VALUE_8',
        tsccod_0: 'VALUE_8',
        orippt_0: 'VALUE_8',
        pitcpt_0: 'VALUE_8',
        payban_0: 'VALUE_8',
        cce_0: 'VALUE_8',
        bpcsho_0: 'VALUE_8',
        bcgcod_0: 'VALUE_8',
        grp_0: 'VALUE_8',
        bpctyp_0: 'VALUE_8',
        lndauz_0: 'VALUE_8',
        xcur_0: 'VALUE_8',
        dia_0: 'VALUE_8',
        copnbr_0: 'VALUE_8',
        invper_0: 'VALUE_8',
        ordcle_0: 'VALUE_8',
        odl_0: 'VALUE_8',
        quolasdat_0: new Date().toISOString().split('T')[0],
        rep_0: 'VALUE_8',
        chgtyp_0: 'VALUE_8',
        ordminamt_0: 84.0,
        cntnextyp_0: 'VALUE_8',
        updusr_0: 'VALUE_8',
        abccls_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        bpainv_0: 'VALUE_8',
        bpapyr_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        cshvatrgm_0: 'VALUE_8',
        pte_0: 'VALUE_8',
        invdta_0: 'VALUE_8',
        bpcnum_0: 'VALUE_8',
        fctnum_0: 'VALUE_8',
        comcat_0: 'VALUE_8',
        vacbpr_0: 'VALUE_8',
        xvacbpr_0: 'VALUE_8',
        cur_0: 'VALUE_8',
        mtcflg_0: 'VALUE_8',
        ordtex_0: 'VALUE_8',
        invtex_0: 'VALUE_8',
        ocnflg_0: 'VALUE_8',
        dudclc_0: 'VALUE_8',
        dme_0: 'VALUE_8',
      },
      {
        ime_0: 'VALUE_9',
        cntlasdat_0: new Date().toISOString().split('T')[0],
        cntlastyp_0: 'VALUE_9',
        pitcdt_0: 'VALUE_9',
        cotpitrqd_0: 'VALUE_9',
        cntfirdat_0: new Date().toISOString().split('T')[0],
        ordfirdat_0: new Date().toISOString().split('T')[0],
        x_blcnbr_0: 'VALUE_9',
        x_blvalo_0: 'VALUE_9',
        cdtisrdat_0: new Date().toISOString().split('T')[0],
        soiper_0: 'VALUE_9',
        vatexn_0: 'VALUE_9',
        bpaadd_0: 'VALUE_9',
        cntnam_0: 'Nom contact par defaut 9',
        cntnexdat_0: new Date().toISOString().split('T')[0],
        daymon_0: 'VALUE_9',
        ostctl_0: 'VALUE_9',
        bpcrem_0: 'VALUE_9',
        strdatefat_0: new Date().toISOString().split('T')[0],
        cntefat_0: 'VALUE_9',
        agtpcp_0: 'VALUE_9',
        ostauz_0: 9,
        cdtisr_0: 'VALUE_9',
        fuptyp_0: 'VALUE_9',
        acccod_0: 'VALUE_9',
        xsitemad_0: 'VALUE_9',
        bpcsncdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_9',
        uvycod2_0: 'VALUE_9',
        x4demchor_0: 'VALUE_9',
        x4service_0: 'VALUE_9',
        x4engagement_0: 'VALUE_9',
        electinv_0: 'VALUE_9',
        aeiflg_0: 'VALUE_9',
        die_0: 'VALUE_9',
        bpcrsk_0: 'VALUE_9',
        belvatsub_0: 'VALUE_9',
        xicmajbl_0: 'VALUE_9',
        xyeaexo_0: 'VALUE_9',
        xautofact_0: 'VALUE_9',
        x4fctcli_0: 'VALUE_9',
        x4filflg_0: 'VALUE_9',
        x4regrel_0: 'VALUE_9',
        x4tolgen_0: 'VALUE_9',
        x4mrgtrsapp_0: 'VALUE_9',
        x1cdprsp_0: 'VALUE_9',
        x1site_0: 'VALUE_9',
        x1tolflg_0: 'VALUE_9',
        x1tolmax_0: 'VALUE_9',
        x1tolmin_0: 'VALUE_9',
        bpccdtisr_0: 'VALUE_9',
        vatstrdat_0: new Date().toISOString().split('T')[0],
        vatenddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        invcnd_0: 'VALUE_9',
        bpdadd_0: 'VALUE_9',
        prityp_0: 94.5,
        tpmcod_0: 'VALUE_9',
        bpcnam_0: 'VALUE_9',
        bpcinv_0: 'VALUE_9',
        bpcpyr_0: 'VALUE_9',
        bpcgru_0: 'VALUE_9',
        bpcsta_0: 1,
        pptflg_0: 'VALUE_9',
        bpcbpsnum_0: 'BPC0009',
        freinv_0: 'VALUE_9',
        fupminamt_0: 94.5,
        invdtaamt_0: 94.5,
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        agtsattax_0: 'VALUE_9',
        flgsattax_0: true,
        sattax_0: 'VALUE_9',
        cotchx_0: 'VALUE_9',
        totpit_0: 'VALUE_9',
        bus_0: 'VALUE_9',
        xamtexo_0: 94.5,
        dep_0: 'VALUE_9',
        tsccod_0: 'VALUE_9',
        orippt_0: 'VALUE_9',
        pitcpt_0: 'VALUE_9',
        payban_0: 'VALUE_9',
        cce_0: 'VALUE_9',
        bpcsho_0: 'VALUE_9',
        bcgcod_0: 'VALUE_9',
        grp_0: 'VALUE_9',
        bpctyp_0: 'VALUE_9',
        lndauz_0: 'VALUE_9',
        xcur_0: 'VALUE_9',
        dia_0: 'VALUE_9',
        copnbr_0: 'VALUE_9',
        invper_0: 'VALUE_9',
        ordcle_0: 'VALUE_9',
        odl_0: 'VALUE_9',
        quolasdat_0: new Date().toISOString().split('T')[0],
        rep_0: 'VALUE_9',
        chgtyp_0: 'VALUE_9',
        ordminamt_0: 94.5,
        cntnextyp_0: 'VALUE_9',
        updusr_0: 'VALUE_9',
        abccls_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        bpainv_0: 'VALUE_9',
        bpapyr_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        cshvatrgm_0: 'VALUE_9',
        pte_0: 'VALUE_9',
        invdta_0: 'VALUE_9',
        bpcnum_0: 'VALUE_9',
        fctnum_0: 'VALUE_9',
        comcat_0: 'VALUE_9',
        vacbpr_0: 'VALUE_9',
        xvacbpr_0: 'VALUE_9',
        cur_0: 'VALUE_9',
        mtcflg_0: 'VALUE_9',
        ordtex_0: 'VALUE_9',
        invtex_0: 'VALUE_9',
        ocnflg_0: 'VALUE_9',
        dudclc_0: 'VALUE_9',
        dme_0: 'VALUE_9',
      },
      {
        ime_0: 'VALUE_10',
        cntlasdat_0: new Date().toISOString().split('T')[0],
        cntlastyp_0: 'VALUE_10',
        pitcdt_0: 'VALUE_10',
        cotpitrqd_0: 'VALUE_10',
        cntfirdat_0: new Date().toISOString().split('T')[0],
        ordfirdat_0: new Date().toISOString().split('T')[0],
        x_blcnbr_0: 'VALUE_10',
        x_blvalo_0: 'VALUE_10',
        cdtisrdat_0: new Date().toISOString().split('T')[0],
        soiper_0: 'VALUE_10',
        vatexn_0: 'VALUE_10',
        bpaadd_0: 'VALUE_10',
        cntnam_0: 'Nom contact par defaut 10',
        cntnexdat_0: new Date().toISOString().split('T')[0],
        daymon_0: 'VALUE_10',
        ostctl_0: 'VALUE_10',
        bpcrem_0: 'VALUE_10',
        strdatefat_0: new Date().toISOString().split('T')[0],
        cntefat_0: 'VALUE_10',
        agtpcp_0: 'VALUE_10',
        ostauz_0: 10,
        cdtisr_0: 'VALUE_10',
        fuptyp_0: 'VALUE_10',
        acccod_0: 'VALUE_10',
        xsitemad_0: 'VALUE_10',
        bpcsncdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_10',
        uvycod2_0: 'VALUE_10',
        x4demchor_0: 'VALUE_10',
        x4service_0: 'VALUE_10',
        x4engagement_0: 'VALUE_10',
        electinv_0: 'VALUE_10',
        aeiflg_0: 'VALUE_10',
        die_0: 'VALUE_10',
        bpcrsk_0: 'VALUE_10',
        belvatsub_0: 'VALUE_10',
        xicmajbl_0: 'VALUE_10',
        xyeaexo_0: 'VALUE_10',
        xautofact_0: 'VALUE_10',
        x4fctcli_0: 'VALUE_10',
        x4filflg_0: 'VALUE_10',
        x4regrel_0: 'VALUE_10',
        x4tolgen_0: 'VALUE_10',
        x4mrgtrsapp_0: 'VALUE_10',
        x1cdprsp_0: 'VALUE_10',
        x1site_0: 'VALUE_10',
        x1tolflg_0: 'VALUE_10',
        x1tolmax_0: 'VALUE_10',
        x1tolmin_0: 'VALUE_10',
        bpccdtisr_0: 'VALUE_10',
        vatstrdat_0: new Date().toISOString().split('T')[0],
        vatenddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        invcnd_0: 'VALUE_10',
        bpdadd_0: 'VALUE_10',
        prityp_0: 105.0,
        tpmcod_0: 'VALUE_10',
        bpcnam_0: 'VALUE_10',
        bpcinv_0: 'VALUE_10',
        bpcpyr_0: 'VALUE_10',
        bpcgru_0: 'VALUE_10',
        bpcsta_0: 1,
        pptflg_0: 'VALUE_10',
        bpcbpsnum_0: 'BPC0010',
        freinv_0: 'VALUE_10',
        fupminamt_0: 105.0,
        invdtaamt_0: 105.0,
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        agtsattax_0: 'VALUE_10',
        flgsattax_0: true,
        sattax_0: 'VALUE_10',
        cotchx_0: 'VALUE_10',
        totpit_0: 'VALUE_10',
        bus_0: 'VALUE_10',
        xamtexo_0: 105.0,
        dep_0: 'VALUE_10',
        tsccod_0: 'VALUE_10',
        orippt_0: 'VALUE_10',
        pitcpt_0: 'VALUE_10',
        payban_0: 'VALUE_10',
        cce_0: 'VALUE_10',
        bpcsho_0: 'VALUE_10',
        bcgcod_0: 'VALUE_10',
        grp_0: 'VALUE_10',
        bpctyp_0: 'VALUE_10',
        lndauz_0: 'VALUE_10',
        xcur_0: 'VALUE_10',
        dia_0: 'VALUE_10',
        copnbr_0: 'VALUE_10',
        invper_0: 'VALUE_10',
        ordcle_0: 'VALUE_10',
        odl_0: 'VALUE_10',
        quolasdat_0: new Date().toISOString().split('T')[0],
        rep_0: 'VALUE_10',
        chgtyp_0: 'VALUE_10',
        ordminamt_0: 105.0,
        cntnextyp_0: 'VALUE_10',
        updusr_0: 'VALUE_10',
        abccls_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        bpainv_0: 'VALUE_10',
        bpapyr_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        cshvatrgm_0: 'VALUE_10',
        pte_0: 'VALUE_10',
        invdta_0: 'VALUE_10',
        bpcnum_0: 'VALUE_10',
        fctnum_0: 'VALUE_10',
        comcat_0: 'VALUE_10',
        vacbpr_0: 'VALUE_10',
        xvacbpr_0: 'VALUE_10',
        cur_0: 'VALUE_10',
        mtcflg_0: 'VALUE_10',
        ordtex_0: 'VALUE_10',
        invtex_0: 'VALUE_10',
        ocnflg_0: 'VALUE_10',
        dudclc_0: 'VALUE_10',
        dme_0: 'VALUE_10',
      },
    ]

    await Database.table('bpcustomer').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans bpcustomer`)
  }
}
