import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour BPSUPPLIER
    const data = [
      {
        x4eltpoiapp_0: 'VALUE_1',
        xrskmrktgt_0: 'VALUE_1',
        flg281_0: true,
        die_0: 'VALUE_1',
        cshdat_0: new Date().toISOString().split('T')[0],
        cshvat_0: 'VALUE_1',
        iptexs_0: 'VALUE_1',
        bpcnum_0: 'BPS0001',
        rexnum_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        autinvcod_0: 'VALUE_1',
        wlflg_0: 'VALUE_1',
        ordfrefrt_0: 'VALUE_1',
        bprdsp_0: 'VALUE_1',
        ynbdoc_0: 'VALUE_1',
        xseuilrad_0: 'VALUE_1',
        bpsrsk_0: 'VALUE_1',
        loc_0: 'VALUE_1',
        pte_0: 'VALUE_1',
        invdta_0: 'VALUE_1',
        vacbpr_0: 'VALUE_1',
        cai_0: 'VALUE_1',
        datvlycai_0: new Date().toISOString().split('T')[0],
        bpsinv_0: 'VALUE_1',
        bpsnum_0: 'VALUE_1',
        bpstyp_0: 'VALUE_1',
        qlymrkcoe_0: 'VALUE_1',
        qtymrkcoe_0: 10.5,
        rskmrkcoe_0: 'VALUE_1',
        rskmrk_0: 'VALUE_1',
        ostauzamt_0: 10.5,
        eecincrat_0: 'VALUE_1',
        bpaadd_0: 'VALUE_1',
        prvnum_0: 'VALUE_1',
        cntnam_0: 'Nom contact par defaut 1',
        purprityp_0: 10.5,
        nreprnflg_0: 'VALUE_1',
        nrtprnflg_0: 'VALUE_1',
        ritnbr_0: 'VALUE_1',
        ritrat_0: 'VALUE_1',
        ritparnbr_0: 'VALUE_1',
        ritparnam_0: 'VALUE_1',
        ritparcoe_0: 'VALUE_1',
        bpsgru_0: 'VALUE_1',
        douflg_0: 'VALUE_1',
        mdl_0: 'VALUE_1',
        uvycod_0: 'VALUE_1',
        ltimrk_0: new Date().toISOString(),
        primrk_0: 10.5,
        qlymrk_0: 'VALUE_1',
        qtymrk_0: 10.5,
        genmrk_0: 'VALUE_1',
        bpsrem_0: 'VALUE_1',
        enaflg_0: true,
        agtpcp_0: 'VALUE_1',
        acccod_0: 'VALUE_1',
        mattol_0: 'VALUE_1',
        frm1099_0: 'VALUE_1',
        box1099_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        x4aexpdlach_0: 'VALUE_1',
        xdmrpar_0: 'VALUE_1',
        xltimrktgt_0: new Date().toISOString(),
        xprimrktgt_0: 10.5,
        xqlymrktgt_0: 'VALUE_1',
        xqtymrktgt_0: 10.5,
        x4eltnbrcol_0: 'VALUE_1',
        x4eltpoi_0: 'VALUE_1',
        tsscod_0: 'VALUE_1',
        tpmcod_0: 'VALUE_1',
        bpsnam_0: 'VALUE_1',
        bptnum_0: 'VALUE_1',
        plistc_0: 'VALUE_1',
        eecict_0: 'VALUE_1',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_1',
        xpohtypbps_0: 'VALUE_1',
        curclc_0: 'VALUE_1',
        amtcod_0: 10.5,
        agtsattax_0: 'VALUE_1',
        flgsattax_0: true,
        sattax_0: 'VALUE_1',
        ritcod_0: 'VALUE_1',
        xaudit_0: 'VALUE_1',
        bpapay_0: 'VALUE_1',
        zsigfab_0: 'VALUE_1',
        dep_0: 'VALUE_1',
        dadflg_0: 'VALUE_1',
        payban_0: 'VALUE_1',
        fupflg_0: 'VALUE_1',
        ocnflg_0: 'VALUE_1',
        ordtex_0: 'VALUE_1',
        rtntex_0: 'VALUE_1',
        cce_0: 'VALUE_1',
        bsgcod_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_1',
        cur_0: 'VALUE_1',
        ostctl_0: 'VALUE_1',
        chgtyp_0: 'VALUE_1',
        dia_0: 'VALUE_1',
        sevlin_0: 'VALUE_1',
        bpcnumbps_0: 'VALUE_1',
        invdtaamt_0: 10.5,
        ltimrkcoe_0: new Date().toISOString(),
        ordminamt_0: 10.5,
        dudclc_0: 'VALUE_1',
        paylokflg_0: 'VALUE_1',
        norprnflg_0: 'VALUE_1',
        bpssho_0: 'VALUE_1',
        primrkcoe_0: 10.5,
        bpainv_0: 'VALUE_1',
        eecloc_0: 'VALUE_1',
        abccls_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
      },
      {
        x4eltpoiapp_0: 'VALUE_2',
        xrskmrktgt_0: 'VALUE_2',
        flg281_0: true,
        die_0: 'VALUE_2',
        cshdat_0: new Date().toISOString().split('T')[0],
        cshvat_0: 'VALUE_2',
        iptexs_0: 'VALUE_2',
        bpcnum_0: 'BPS0002',
        rexnum_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        autinvcod_0: 'VALUE_2',
        wlflg_0: 'VALUE_2',
        ordfrefrt_0: 'VALUE_2',
        bprdsp_0: 'VALUE_2',
        ynbdoc_0: 'VALUE_2',
        xseuilrad_0: 'VALUE_2',
        bpsrsk_0: 'VALUE_2',
        loc_0: 'VALUE_2',
        pte_0: 'VALUE_2',
        invdta_0: 'VALUE_2',
        vacbpr_0: 'VALUE_2',
        cai_0: 'VALUE_2',
        datvlycai_0: new Date().toISOString().split('T')[0],
        bpsinv_0: 'VALUE_2',
        bpsnum_0: 'VALUE_2',
        bpstyp_0: 'VALUE_2',
        qlymrkcoe_0: 'VALUE_2',
        qtymrkcoe_0: 21.0,
        rskmrkcoe_0: 'VALUE_2',
        rskmrk_0: 'VALUE_2',
        ostauzamt_0: 21.0,
        eecincrat_0: 'VALUE_2',
        bpaadd_0: 'VALUE_2',
        prvnum_0: 'VALUE_2',
        cntnam_0: 'Nom contact par defaut 2',
        purprityp_0: 21.0,
        nreprnflg_0: 'VALUE_2',
        nrtprnflg_0: 'VALUE_2',
        ritnbr_0: 'VALUE_2',
        ritrat_0: 'VALUE_2',
        ritparnbr_0: 'VALUE_2',
        ritparnam_0: 'VALUE_2',
        ritparcoe_0: 'VALUE_2',
        bpsgru_0: 'VALUE_2',
        douflg_0: 'VALUE_2',
        mdl_0: 'VALUE_2',
        uvycod_0: 'VALUE_2',
        ltimrk_0: new Date().toISOString(),
        primrk_0: 21.0,
        qlymrk_0: 'VALUE_2',
        qtymrk_0: 21.0,
        genmrk_0: 'VALUE_2',
        bpsrem_0: 'VALUE_2',
        enaflg_0: true,
        agtpcp_0: 'VALUE_2',
        acccod_0: 'VALUE_2',
        mattol_0: 'VALUE_2',
        frm1099_0: 'VALUE_2',
        box1099_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        x4aexpdlach_0: 'VALUE_2',
        xdmrpar_0: 'VALUE_2',
        xltimrktgt_0: new Date().toISOString(),
        xprimrktgt_0: 21.0,
        xqlymrktgt_0: 'VALUE_2',
        xqtymrktgt_0: 21.0,
        x4eltnbrcol_0: 'VALUE_2',
        x4eltpoi_0: 'VALUE_2',
        tsscod_0: 'VALUE_2',
        tpmcod_0: 'VALUE_2',
        bpsnam_0: 'VALUE_2',
        bptnum_0: 'VALUE_2',
        plistc_0: 'VALUE_2',
        eecict_0: 'VALUE_2',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_2',
        xpohtypbps_0: 'VALUE_2',
        curclc_0: 'VALUE_2',
        amtcod_0: 21.0,
        agtsattax_0: 'VALUE_2',
        flgsattax_0: true,
        sattax_0: 'VALUE_2',
        ritcod_0: 'VALUE_2',
        xaudit_0: 'VALUE_2',
        bpapay_0: 'VALUE_2',
        zsigfab_0: 'VALUE_2',
        dep_0: 'VALUE_2',
        dadflg_0: 'VALUE_2',
        payban_0: 'VALUE_2',
        fupflg_0: 'VALUE_2',
        ocnflg_0: 'VALUE_2',
        ordtex_0: 'VALUE_2',
        rtntex_0: 'VALUE_2',
        cce_0: 'VALUE_2',
        bsgcod_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_2',
        cur_0: 'VALUE_2',
        ostctl_0: 'VALUE_2',
        chgtyp_0: 'VALUE_2',
        dia_0: 'VALUE_2',
        sevlin_0: 'VALUE_2',
        bpcnumbps_0: 'VALUE_2',
        invdtaamt_0: 21.0,
        ltimrkcoe_0: new Date().toISOString(),
        ordminamt_0: 21.0,
        dudclc_0: 'VALUE_2',
        paylokflg_0: 'VALUE_2',
        norprnflg_0: 'VALUE_2',
        bpssho_0: 'VALUE_2',
        primrkcoe_0: 21.0,
        bpainv_0: 'VALUE_2',
        eecloc_0: 'VALUE_2',
        abccls_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
      },
      {
        x4eltpoiapp_0: 'VALUE_3',
        xrskmrktgt_0: 'VALUE_3',
        flg281_0: true,
        die_0: 'VALUE_3',
        cshdat_0: new Date().toISOString().split('T')[0],
        cshvat_0: 'VALUE_3',
        iptexs_0: 'VALUE_3',
        bpcnum_0: 'BPS0003',
        rexnum_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        autinvcod_0: 'VALUE_3',
        wlflg_0: 'VALUE_3',
        ordfrefrt_0: 'VALUE_3',
        bprdsp_0: 'VALUE_3',
        ynbdoc_0: 'VALUE_3',
        xseuilrad_0: 'VALUE_3',
        bpsrsk_0: 'VALUE_3',
        loc_0: 'VALUE_3',
        pte_0: 'VALUE_3',
        invdta_0: 'VALUE_3',
        vacbpr_0: 'VALUE_3',
        cai_0: 'VALUE_3',
        datvlycai_0: new Date().toISOString().split('T')[0],
        bpsinv_0: 'VALUE_3',
        bpsnum_0: 'VALUE_3',
        bpstyp_0: 'VALUE_3',
        qlymrkcoe_0: 'VALUE_3',
        qtymrkcoe_0: 31.5,
        rskmrkcoe_0: 'VALUE_3',
        rskmrk_0: 'VALUE_3',
        ostauzamt_0: 31.5,
        eecincrat_0: 'VALUE_3',
        bpaadd_0: 'VALUE_3',
        prvnum_0: 'VALUE_3',
        cntnam_0: 'Nom contact par defaut 3',
        purprityp_0: 31.5,
        nreprnflg_0: 'VALUE_3',
        nrtprnflg_0: 'VALUE_3',
        ritnbr_0: 'VALUE_3',
        ritrat_0: 'VALUE_3',
        ritparnbr_0: 'VALUE_3',
        ritparnam_0: 'VALUE_3',
        ritparcoe_0: 'VALUE_3',
        bpsgru_0: 'VALUE_3',
        douflg_0: 'VALUE_3',
        mdl_0: 'VALUE_3',
        uvycod_0: 'VALUE_3',
        ltimrk_0: new Date().toISOString(),
        primrk_0: 31.5,
        qlymrk_0: 'VALUE_3',
        qtymrk_0: 31.5,
        genmrk_0: 'VALUE_3',
        bpsrem_0: 'VALUE_3',
        enaflg_0: true,
        agtpcp_0: 'VALUE_3',
        acccod_0: 'VALUE_3',
        mattol_0: 'VALUE_3',
        frm1099_0: 'VALUE_3',
        box1099_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        x4aexpdlach_0: 'VALUE_3',
        xdmrpar_0: 'VALUE_3',
        xltimrktgt_0: new Date().toISOString(),
        xprimrktgt_0: 31.5,
        xqlymrktgt_0: 'VALUE_3',
        xqtymrktgt_0: 31.5,
        x4eltnbrcol_0: 'VALUE_3',
        x4eltpoi_0: 'VALUE_3',
        tsscod_0: 'VALUE_3',
        tpmcod_0: 'VALUE_3',
        bpsnam_0: 'VALUE_3',
        bptnum_0: 'VALUE_3',
        plistc_0: 'VALUE_3',
        eecict_0: 'VALUE_3',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_3',
        xpohtypbps_0: 'VALUE_3',
        curclc_0: 'VALUE_3',
        amtcod_0: 31.5,
        agtsattax_0: 'VALUE_3',
        flgsattax_0: true,
        sattax_0: 'VALUE_3',
        ritcod_0: 'VALUE_3',
        xaudit_0: 'VALUE_3',
        bpapay_0: 'VALUE_3',
        zsigfab_0: 'VALUE_3',
        dep_0: 'VALUE_3',
        dadflg_0: 'VALUE_3',
        payban_0: 'VALUE_3',
        fupflg_0: 'VALUE_3',
        ocnflg_0: 'VALUE_3',
        ordtex_0: 'VALUE_3',
        rtntex_0: 'VALUE_3',
        cce_0: 'VALUE_3',
        bsgcod_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_3',
        cur_0: 'VALUE_3',
        ostctl_0: 'VALUE_3',
        chgtyp_0: 'VALUE_3',
        dia_0: 'VALUE_3',
        sevlin_0: 'VALUE_3',
        bpcnumbps_0: 'VALUE_3',
        invdtaamt_0: 31.5,
        ltimrkcoe_0: new Date().toISOString(),
        ordminamt_0: 31.5,
        dudclc_0: 'VALUE_3',
        paylokflg_0: 'VALUE_3',
        norprnflg_0: 'VALUE_3',
        bpssho_0: 'VALUE_3',
        primrkcoe_0: 31.5,
        bpainv_0: 'VALUE_3',
        eecloc_0: 'VALUE_3',
        abccls_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
      },
      {
        x4eltpoiapp_0: 'VALUE_4',
        xrskmrktgt_0: 'VALUE_4',
        flg281_0: true,
        die_0: 'VALUE_4',
        cshdat_0: new Date().toISOString().split('T')[0],
        cshvat_0: 'VALUE_4',
        iptexs_0: 'VALUE_4',
        bpcnum_0: 'BPS0004',
        rexnum_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        autinvcod_0: 'VALUE_4',
        wlflg_0: 'VALUE_4',
        ordfrefrt_0: 'VALUE_4',
        bprdsp_0: 'VALUE_4',
        ynbdoc_0: 'VALUE_4',
        xseuilrad_0: 'VALUE_4',
        bpsrsk_0: 'VALUE_4',
        loc_0: 'VALUE_4',
        pte_0: 'VALUE_4',
        invdta_0: 'VALUE_4',
        vacbpr_0: 'VALUE_4',
        cai_0: 'VALUE_4',
        datvlycai_0: new Date().toISOString().split('T')[0],
        bpsinv_0: 'VALUE_4',
        bpsnum_0: 'VALUE_4',
        bpstyp_0: 'VALUE_4',
        qlymrkcoe_0: 'VALUE_4',
        qtymrkcoe_0: 42.0,
        rskmrkcoe_0: 'VALUE_4',
        rskmrk_0: 'VALUE_4',
        ostauzamt_0: 42.0,
        eecincrat_0: 'VALUE_4',
        bpaadd_0: 'VALUE_4',
        prvnum_0: 'VALUE_4',
        cntnam_0: 'Nom contact par defaut 4',
        purprityp_0: 42.0,
        nreprnflg_0: 'VALUE_4',
        nrtprnflg_0: 'VALUE_4',
        ritnbr_0: 'VALUE_4',
        ritrat_0: 'VALUE_4',
        ritparnbr_0: 'VALUE_4',
        ritparnam_0: 'VALUE_4',
        ritparcoe_0: 'VALUE_4',
        bpsgru_0: 'VALUE_4',
        douflg_0: 'VALUE_4',
        mdl_0: 'VALUE_4',
        uvycod_0: 'VALUE_4',
        ltimrk_0: new Date().toISOString(),
        primrk_0: 42.0,
        qlymrk_0: 'VALUE_4',
        qtymrk_0: 42.0,
        genmrk_0: 'VALUE_4',
        bpsrem_0: 'VALUE_4',
        enaflg_0: true,
        agtpcp_0: 'VALUE_4',
        acccod_0: 'VALUE_4',
        mattol_0: 'VALUE_4',
        frm1099_0: 'VALUE_4',
        box1099_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        x4aexpdlach_0: 'VALUE_4',
        xdmrpar_0: 'VALUE_4',
        xltimrktgt_0: new Date().toISOString(),
        xprimrktgt_0: 42.0,
        xqlymrktgt_0: 'VALUE_4',
        xqtymrktgt_0: 42.0,
        x4eltnbrcol_0: 'VALUE_4',
        x4eltpoi_0: 'VALUE_4',
        tsscod_0: 'VALUE_4',
        tpmcod_0: 'VALUE_4',
        bpsnam_0: 'VALUE_4',
        bptnum_0: 'VALUE_4',
        plistc_0: 'VALUE_4',
        eecict_0: 'VALUE_4',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_4',
        xpohtypbps_0: 'VALUE_4',
        curclc_0: 'VALUE_4',
        amtcod_0: 42.0,
        agtsattax_0: 'VALUE_4',
        flgsattax_0: true,
        sattax_0: 'VALUE_4',
        ritcod_0: 'VALUE_4',
        xaudit_0: 'VALUE_4',
        bpapay_0: 'VALUE_4',
        zsigfab_0: 'VALUE_4',
        dep_0: 'VALUE_4',
        dadflg_0: 'VALUE_4',
        payban_0: 'VALUE_4',
        fupflg_0: 'VALUE_4',
        ocnflg_0: 'VALUE_4',
        ordtex_0: 'VALUE_4',
        rtntex_0: 'VALUE_4',
        cce_0: 'VALUE_4',
        bsgcod_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_4',
        cur_0: 'VALUE_4',
        ostctl_0: 'VALUE_4',
        chgtyp_0: 'VALUE_4',
        dia_0: 'VALUE_4',
        sevlin_0: 'VALUE_4',
        bpcnumbps_0: 'VALUE_4',
        invdtaamt_0: 42.0,
        ltimrkcoe_0: new Date().toISOString(),
        ordminamt_0: 42.0,
        dudclc_0: 'VALUE_4',
        paylokflg_0: 'VALUE_4',
        norprnflg_0: 'VALUE_4',
        bpssho_0: 'VALUE_4',
        primrkcoe_0: 42.0,
        bpainv_0: 'VALUE_4',
        eecloc_0: 'VALUE_4',
        abccls_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
      },
      {
        x4eltpoiapp_0: 'VALUE_5',
        xrskmrktgt_0: 'VALUE_5',
        flg281_0: true,
        die_0: 'VALUE_5',
        cshdat_0: new Date().toISOString().split('T')[0],
        cshvat_0: 'VALUE_5',
        iptexs_0: 'VALUE_5',
        bpcnum_0: 'BPS0005',
        rexnum_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        autinvcod_0: 'VALUE_5',
        wlflg_0: 'VALUE_5',
        ordfrefrt_0: 'VALUE_5',
        bprdsp_0: 'VALUE_5',
        ynbdoc_0: 'VALUE_5',
        xseuilrad_0: 'VALUE_5',
        bpsrsk_0: 'VALUE_5',
        loc_0: 'VALUE_5',
        pte_0: 'VALUE_5',
        invdta_0: 'VALUE_5',
        vacbpr_0: 'VALUE_5',
        cai_0: 'VALUE_5',
        datvlycai_0: new Date().toISOString().split('T')[0],
        bpsinv_0: 'VALUE_5',
        bpsnum_0: 'VALUE_5',
        bpstyp_0: 'VALUE_5',
        qlymrkcoe_0: 'VALUE_5',
        qtymrkcoe_0: 52.5,
        rskmrkcoe_0: 'VALUE_5',
        rskmrk_0: 'VALUE_5',
        ostauzamt_0: 52.5,
        eecincrat_0: 'VALUE_5',
        bpaadd_0: 'VALUE_5',
        prvnum_0: 'VALUE_5',
        cntnam_0: 'Nom contact par defaut 5',
        purprityp_0: 52.5,
        nreprnflg_0: 'VALUE_5',
        nrtprnflg_0: 'VALUE_5',
        ritnbr_0: 'VALUE_5',
        ritrat_0: 'VALUE_5',
        ritparnbr_0: 'VALUE_5',
        ritparnam_0: 'VALUE_5',
        ritparcoe_0: 'VALUE_5',
        bpsgru_0: 'VALUE_5',
        douflg_0: 'VALUE_5',
        mdl_0: 'VALUE_5',
        uvycod_0: 'VALUE_5',
        ltimrk_0: new Date().toISOString(),
        primrk_0: 52.5,
        qlymrk_0: 'VALUE_5',
        qtymrk_0: 52.5,
        genmrk_0: 'VALUE_5',
        bpsrem_0: 'VALUE_5',
        enaflg_0: true,
        agtpcp_0: 'VALUE_5',
        acccod_0: 'VALUE_5',
        mattol_0: 'VALUE_5',
        frm1099_0: 'VALUE_5',
        box1099_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        x4aexpdlach_0: 'VALUE_5',
        xdmrpar_0: 'VALUE_5',
        xltimrktgt_0: new Date().toISOString(),
        xprimrktgt_0: 52.5,
        xqlymrktgt_0: 'VALUE_5',
        xqtymrktgt_0: 52.5,
        x4eltnbrcol_0: 'VALUE_5',
        x4eltpoi_0: 'VALUE_5',
        tsscod_0: 'VALUE_5',
        tpmcod_0: 'VALUE_5',
        bpsnam_0: 'VALUE_5',
        bptnum_0: 'VALUE_5',
        plistc_0: 'VALUE_5',
        eecict_0: 'VALUE_5',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_5',
        xpohtypbps_0: 'VALUE_5',
        curclc_0: 'VALUE_5',
        amtcod_0: 52.5,
        agtsattax_0: 'VALUE_5',
        flgsattax_0: true,
        sattax_0: 'VALUE_5',
        ritcod_0: 'VALUE_5',
        xaudit_0: 'VALUE_5',
        bpapay_0: 'VALUE_5',
        zsigfab_0: 'VALUE_5',
        dep_0: 'VALUE_5',
        dadflg_0: 'VALUE_5',
        payban_0: 'VALUE_5',
        fupflg_0: 'VALUE_5',
        ocnflg_0: 'VALUE_5',
        ordtex_0: 'VALUE_5',
        rtntex_0: 'VALUE_5',
        cce_0: 'VALUE_5',
        bsgcod_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_5',
        cur_0: 'VALUE_5',
        ostctl_0: 'VALUE_5',
        chgtyp_0: 'VALUE_5',
        dia_0: 'VALUE_5',
        sevlin_0: 'VALUE_5',
        bpcnumbps_0: 'VALUE_5',
        invdtaamt_0: 52.5,
        ltimrkcoe_0: new Date().toISOString(),
        ordminamt_0: 52.5,
        dudclc_0: 'VALUE_5',
        paylokflg_0: 'VALUE_5',
        norprnflg_0: 'VALUE_5',
        bpssho_0: 'VALUE_5',
        primrkcoe_0: 52.5,
        bpainv_0: 'VALUE_5',
        eecloc_0: 'VALUE_5',
        abccls_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
      },
      {
        x4eltpoiapp_0: 'VALUE_6',
        xrskmrktgt_0: 'VALUE_6',
        flg281_0: true,
        die_0: 'VALUE_6',
        cshdat_0: new Date().toISOString().split('T')[0],
        cshvat_0: 'VALUE_6',
        iptexs_0: 'VALUE_6',
        bpcnum_0: 'BPS0006',
        rexnum_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        autinvcod_0: 'VALUE_6',
        wlflg_0: 'VALUE_6',
        ordfrefrt_0: 'VALUE_6',
        bprdsp_0: 'VALUE_6',
        ynbdoc_0: 'VALUE_6',
        xseuilrad_0: 'VALUE_6',
        bpsrsk_0: 'VALUE_6',
        loc_0: 'VALUE_6',
        pte_0: 'VALUE_6',
        invdta_0: 'VALUE_6',
        vacbpr_0: 'VALUE_6',
        cai_0: 'VALUE_6',
        datvlycai_0: new Date().toISOString().split('T')[0],
        bpsinv_0: 'VALUE_6',
        bpsnum_0: 'VALUE_6',
        bpstyp_0: 'VALUE_6',
        qlymrkcoe_0: 'VALUE_6',
        qtymrkcoe_0: 63.0,
        rskmrkcoe_0: 'VALUE_6',
        rskmrk_0: 'VALUE_6',
        ostauzamt_0: 63.0,
        eecincrat_0: 'VALUE_6',
        bpaadd_0: 'VALUE_6',
        prvnum_0: 'VALUE_6',
        cntnam_0: 'Nom contact par defaut 6',
        purprityp_0: 63.0,
        nreprnflg_0: 'VALUE_6',
        nrtprnflg_0: 'VALUE_6',
        ritnbr_0: 'VALUE_6',
        ritrat_0: 'VALUE_6',
        ritparnbr_0: 'VALUE_6',
        ritparnam_0: 'VALUE_6',
        ritparcoe_0: 'VALUE_6',
        bpsgru_0: 'VALUE_6',
        douflg_0: 'VALUE_6',
        mdl_0: 'VALUE_6',
        uvycod_0: 'VALUE_6',
        ltimrk_0: new Date().toISOString(),
        primrk_0: 63.0,
        qlymrk_0: 'VALUE_6',
        qtymrk_0: 63.0,
        genmrk_0: 'VALUE_6',
        bpsrem_0: 'VALUE_6',
        enaflg_0: true,
        agtpcp_0: 'VALUE_6',
        acccod_0: 'VALUE_6',
        mattol_0: 'VALUE_6',
        frm1099_0: 'VALUE_6',
        box1099_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        x4aexpdlach_0: 'VALUE_6',
        xdmrpar_0: 'VALUE_6',
        xltimrktgt_0: new Date().toISOString(),
        xprimrktgt_0: 63.0,
        xqlymrktgt_0: 'VALUE_6',
        xqtymrktgt_0: 63.0,
        x4eltnbrcol_0: 'VALUE_6',
        x4eltpoi_0: 'VALUE_6',
        tsscod_0: 'VALUE_6',
        tpmcod_0: 'VALUE_6',
        bpsnam_0: 'VALUE_6',
        bptnum_0: 'VALUE_6',
        plistc_0: 'VALUE_6',
        eecict_0: 'VALUE_6',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_6',
        xpohtypbps_0: 'VALUE_6',
        curclc_0: 'VALUE_6',
        amtcod_0: 63.0,
        agtsattax_0: 'VALUE_6',
        flgsattax_0: true,
        sattax_0: 'VALUE_6',
        ritcod_0: 'VALUE_6',
        xaudit_0: 'VALUE_6',
        bpapay_0: 'VALUE_6',
        zsigfab_0: 'VALUE_6',
        dep_0: 'VALUE_6',
        dadflg_0: 'VALUE_6',
        payban_0: 'VALUE_6',
        fupflg_0: 'VALUE_6',
        ocnflg_0: 'VALUE_6',
        ordtex_0: 'VALUE_6',
        rtntex_0: 'VALUE_6',
        cce_0: 'VALUE_6',
        bsgcod_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_6',
        cur_0: 'VALUE_6',
        ostctl_0: 'VALUE_6',
        chgtyp_0: 'VALUE_6',
        dia_0: 'VALUE_6',
        sevlin_0: 'VALUE_6',
        bpcnumbps_0: 'VALUE_6',
        invdtaamt_0: 63.0,
        ltimrkcoe_0: new Date().toISOString(),
        ordminamt_0: 63.0,
        dudclc_0: 'VALUE_6',
        paylokflg_0: 'VALUE_6',
        norprnflg_0: 'VALUE_6',
        bpssho_0: 'VALUE_6',
        primrkcoe_0: 63.0,
        bpainv_0: 'VALUE_6',
        eecloc_0: 'VALUE_6',
        abccls_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
      },
      {
        x4eltpoiapp_0: 'VALUE_7',
        xrskmrktgt_0: 'VALUE_7',
        flg281_0: true,
        die_0: 'VALUE_7',
        cshdat_0: new Date().toISOString().split('T')[0],
        cshvat_0: 'VALUE_7',
        iptexs_0: 'VALUE_7',
        bpcnum_0: 'BPS0007',
        rexnum_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        autinvcod_0: 'VALUE_7',
        wlflg_0: 'VALUE_7',
        ordfrefrt_0: 'VALUE_7',
        bprdsp_0: 'VALUE_7',
        ynbdoc_0: 'VALUE_7',
        xseuilrad_0: 'VALUE_7',
        bpsrsk_0: 'VALUE_7',
        loc_0: 'VALUE_7',
        pte_0: 'VALUE_7',
        invdta_0: 'VALUE_7',
        vacbpr_0: 'VALUE_7',
        cai_0: 'VALUE_7',
        datvlycai_0: new Date().toISOString().split('T')[0],
        bpsinv_0: 'VALUE_7',
        bpsnum_0: 'VALUE_7',
        bpstyp_0: 'VALUE_7',
        qlymrkcoe_0: 'VALUE_7',
        qtymrkcoe_0: 73.5,
        rskmrkcoe_0: 'VALUE_7',
        rskmrk_0: 'VALUE_7',
        ostauzamt_0: 73.5,
        eecincrat_0: 'VALUE_7',
        bpaadd_0: 'VALUE_7',
        prvnum_0: 'VALUE_7',
        cntnam_0: 'Nom contact par defaut 7',
        purprityp_0: 73.5,
        nreprnflg_0: 'VALUE_7',
        nrtprnflg_0: 'VALUE_7',
        ritnbr_0: 'VALUE_7',
        ritrat_0: 'VALUE_7',
        ritparnbr_0: 'VALUE_7',
        ritparnam_0: 'VALUE_7',
        ritparcoe_0: 'VALUE_7',
        bpsgru_0: 'VALUE_7',
        douflg_0: 'VALUE_7',
        mdl_0: 'VALUE_7',
        uvycod_0: 'VALUE_7',
        ltimrk_0: new Date().toISOString(),
        primrk_0: 73.5,
        qlymrk_0: 'VALUE_7',
        qtymrk_0: 73.5,
        genmrk_0: 'VALUE_7',
        bpsrem_0: 'VALUE_7',
        enaflg_0: true,
        agtpcp_0: 'VALUE_7',
        acccod_0: 'VALUE_7',
        mattol_0: 'VALUE_7',
        frm1099_0: 'VALUE_7',
        box1099_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        x4aexpdlach_0: 'VALUE_7',
        xdmrpar_0: 'VALUE_7',
        xltimrktgt_0: new Date().toISOString(),
        xprimrktgt_0: 73.5,
        xqlymrktgt_0: 'VALUE_7',
        xqtymrktgt_0: 73.5,
        x4eltnbrcol_0: 'VALUE_7',
        x4eltpoi_0: 'VALUE_7',
        tsscod_0: 'VALUE_7',
        tpmcod_0: 'VALUE_7',
        bpsnam_0: 'VALUE_7',
        bptnum_0: 'VALUE_7',
        plistc_0: 'VALUE_7',
        eecict_0: 'VALUE_7',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_7',
        xpohtypbps_0: 'VALUE_7',
        curclc_0: 'VALUE_7',
        amtcod_0: 73.5,
        agtsattax_0: 'VALUE_7',
        flgsattax_0: true,
        sattax_0: 'VALUE_7',
        ritcod_0: 'VALUE_7',
        xaudit_0: 'VALUE_7',
        bpapay_0: 'VALUE_7',
        zsigfab_0: 'VALUE_7',
        dep_0: 'VALUE_7',
        dadflg_0: 'VALUE_7',
        payban_0: 'VALUE_7',
        fupflg_0: 'VALUE_7',
        ocnflg_0: 'VALUE_7',
        ordtex_0: 'VALUE_7',
        rtntex_0: 'VALUE_7',
        cce_0: 'VALUE_7',
        bsgcod_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_7',
        cur_0: 'VALUE_7',
        ostctl_0: 'VALUE_7',
        chgtyp_0: 'VALUE_7',
        dia_0: 'VALUE_7',
        sevlin_0: 'VALUE_7',
        bpcnumbps_0: 'VALUE_7',
        invdtaamt_0: 73.5,
        ltimrkcoe_0: new Date().toISOString(),
        ordminamt_0: 73.5,
        dudclc_0: 'VALUE_7',
        paylokflg_0: 'VALUE_7',
        norprnflg_0: 'VALUE_7',
        bpssho_0: 'VALUE_7',
        primrkcoe_0: 73.5,
        bpainv_0: 'VALUE_7',
        eecloc_0: 'VALUE_7',
        abccls_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
      },
      {
        x4eltpoiapp_0: 'VALUE_8',
        xrskmrktgt_0: 'VALUE_8',
        flg281_0: true,
        die_0: 'VALUE_8',
        cshdat_0: new Date().toISOString().split('T')[0],
        cshvat_0: 'VALUE_8',
        iptexs_0: 'VALUE_8',
        bpcnum_0: 'BPS0008',
        rexnum_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        autinvcod_0: 'VALUE_8',
        wlflg_0: 'VALUE_8',
        ordfrefrt_0: 'VALUE_8',
        bprdsp_0: 'VALUE_8',
        ynbdoc_0: 'VALUE_8',
        xseuilrad_0: 'VALUE_8',
        bpsrsk_0: 'VALUE_8',
        loc_0: 'VALUE_8',
        pte_0: 'VALUE_8',
        invdta_0: 'VALUE_8',
        vacbpr_0: 'VALUE_8',
        cai_0: 'VALUE_8',
        datvlycai_0: new Date().toISOString().split('T')[0],
        bpsinv_0: 'VALUE_8',
        bpsnum_0: 'VALUE_8',
        bpstyp_0: 'VALUE_8',
        qlymrkcoe_0: 'VALUE_8',
        qtymrkcoe_0: 84.0,
        rskmrkcoe_0: 'VALUE_8',
        rskmrk_0: 'VALUE_8',
        ostauzamt_0: 84.0,
        eecincrat_0: 'VALUE_8',
        bpaadd_0: 'VALUE_8',
        prvnum_0: 'VALUE_8',
        cntnam_0: 'Nom contact par defaut 8',
        purprityp_0: 84.0,
        nreprnflg_0: 'VALUE_8',
        nrtprnflg_0: 'VALUE_8',
        ritnbr_0: 'VALUE_8',
        ritrat_0: 'VALUE_8',
        ritparnbr_0: 'VALUE_8',
        ritparnam_0: 'VALUE_8',
        ritparcoe_0: 'VALUE_8',
        bpsgru_0: 'VALUE_8',
        douflg_0: 'VALUE_8',
        mdl_0: 'VALUE_8',
        uvycod_0: 'VALUE_8',
        ltimrk_0: new Date().toISOString(),
        primrk_0: 84.0,
        qlymrk_0: 'VALUE_8',
        qtymrk_0: 84.0,
        genmrk_0: 'VALUE_8',
        bpsrem_0: 'VALUE_8',
        enaflg_0: true,
        agtpcp_0: 'VALUE_8',
        acccod_0: 'VALUE_8',
        mattol_0: 'VALUE_8',
        frm1099_0: 'VALUE_8',
        box1099_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        x4aexpdlach_0: 'VALUE_8',
        xdmrpar_0: 'VALUE_8',
        xltimrktgt_0: new Date().toISOString(),
        xprimrktgt_0: 84.0,
        xqlymrktgt_0: 'VALUE_8',
        xqtymrktgt_0: 84.0,
        x4eltnbrcol_0: 'VALUE_8',
        x4eltpoi_0: 'VALUE_8',
        tsscod_0: 'VALUE_8',
        tpmcod_0: 'VALUE_8',
        bpsnam_0: 'VALUE_8',
        bptnum_0: 'VALUE_8',
        plistc_0: 'VALUE_8',
        eecict_0: 'VALUE_8',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_8',
        xpohtypbps_0: 'VALUE_8',
        curclc_0: 'VALUE_8',
        amtcod_0: 84.0,
        agtsattax_0: 'VALUE_8',
        flgsattax_0: true,
        sattax_0: 'VALUE_8',
        ritcod_0: 'VALUE_8',
        xaudit_0: 'VALUE_8',
        bpapay_0: 'VALUE_8',
        zsigfab_0: 'VALUE_8',
        dep_0: 'VALUE_8',
        dadflg_0: 'VALUE_8',
        payban_0: 'VALUE_8',
        fupflg_0: 'VALUE_8',
        ocnflg_0: 'VALUE_8',
        ordtex_0: 'VALUE_8',
        rtntex_0: 'VALUE_8',
        cce_0: 'VALUE_8',
        bsgcod_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_8',
        cur_0: 'VALUE_8',
        ostctl_0: 'VALUE_8',
        chgtyp_0: 'VALUE_8',
        dia_0: 'VALUE_8',
        sevlin_0: 'VALUE_8',
        bpcnumbps_0: 'VALUE_8',
        invdtaamt_0: 84.0,
        ltimrkcoe_0: new Date().toISOString(),
        ordminamt_0: 84.0,
        dudclc_0: 'VALUE_8',
        paylokflg_0: 'VALUE_8',
        norprnflg_0: 'VALUE_8',
        bpssho_0: 'VALUE_8',
        primrkcoe_0: 84.0,
        bpainv_0: 'VALUE_8',
        eecloc_0: 'VALUE_8',
        abccls_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
      },
      {
        x4eltpoiapp_0: 'VALUE_9',
        xrskmrktgt_0: 'VALUE_9',
        flg281_0: true,
        die_0: 'VALUE_9',
        cshdat_0: new Date().toISOString().split('T')[0],
        cshvat_0: 'VALUE_9',
        iptexs_0: 'VALUE_9',
        bpcnum_0: 'BPS0009',
        rexnum_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        autinvcod_0: 'VALUE_9',
        wlflg_0: 'VALUE_9',
        ordfrefrt_0: 'VALUE_9',
        bprdsp_0: 'VALUE_9',
        ynbdoc_0: 'VALUE_9',
        xseuilrad_0: 'VALUE_9',
        bpsrsk_0: 'VALUE_9',
        loc_0: 'VALUE_9',
        pte_0: 'VALUE_9',
        invdta_0: 'VALUE_9',
        vacbpr_0: 'VALUE_9',
        cai_0: 'VALUE_9',
        datvlycai_0: new Date().toISOString().split('T')[0],
        bpsinv_0: 'VALUE_9',
        bpsnum_0: 'VALUE_9',
        bpstyp_0: 'VALUE_9',
        qlymrkcoe_0: 'VALUE_9',
        qtymrkcoe_0: 94.5,
        rskmrkcoe_0: 'VALUE_9',
        rskmrk_0: 'VALUE_9',
        ostauzamt_0: 94.5,
        eecincrat_0: 'VALUE_9',
        bpaadd_0: 'VALUE_9',
        prvnum_0: 'VALUE_9',
        cntnam_0: 'Nom contact par defaut 9',
        purprityp_0: 94.5,
        nreprnflg_0: 'VALUE_9',
        nrtprnflg_0: 'VALUE_9',
        ritnbr_0: 'VALUE_9',
        ritrat_0: 'VALUE_9',
        ritparnbr_0: 'VALUE_9',
        ritparnam_0: 'VALUE_9',
        ritparcoe_0: 'VALUE_9',
        bpsgru_0: 'VALUE_9',
        douflg_0: 'VALUE_9',
        mdl_0: 'VALUE_9',
        uvycod_0: 'VALUE_9',
        ltimrk_0: new Date().toISOString(),
        primrk_0: 94.5,
        qlymrk_0: 'VALUE_9',
        qtymrk_0: 94.5,
        genmrk_0: 'VALUE_9',
        bpsrem_0: 'VALUE_9',
        enaflg_0: true,
        agtpcp_0: 'VALUE_9',
        acccod_0: 'VALUE_9',
        mattol_0: 'VALUE_9',
        frm1099_0: 'VALUE_9',
        box1099_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        x4aexpdlach_0: 'VALUE_9',
        xdmrpar_0: 'VALUE_9',
        xltimrktgt_0: new Date().toISOString(),
        xprimrktgt_0: 94.5,
        xqlymrktgt_0: 'VALUE_9',
        xqtymrktgt_0: 94.5,
        x4eltnbrcol_0: 'VALUE_9',
        x4eltpoi_0: 'VALUE_9',
        tsscod_0: 'VALUE_9',
        tpmcod_0: 'VALUE_9',
        bpsnam_0: 'VALUE_9',
        bptnum_0: 'VALUE_9',
        plistc_0: 'VALUE_9',
        eecict_0: 'VALUE_9',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_9',
        xpohtypbps_0: 'VALUE_9',
        curclc_0: 'VALUE_9',
        amtcod_0: 94.5,
        agtsattax_0: 'VALUE_9',
        flgsattax_0: true,
        sattax_0: 'VALUE_9',
        ritcod_0: 'VALUE_9',
        xaudit_0: 'VALUE_9',
        bpapay_0: 'VALUE_9',
        zsigfab_0: 'VALUE_9',
        dep_0: 'VALUE_9',
        dadflg_0: 'VALUE_9',
        payban_0: 'VALUE_9',
        fupflg_0: 'VALUE_9',
        ocnflg_0: 'VALUE_9',
        ordtex_0: 'VALUE_9',
        rtntex_0: 'VALUE_9',
        cce_0: 'VALUE_9',
        bsgcod_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_9',
        cur_0: 'VALUE_9',
        ostctl_0: 'VALUE_9',
        chgtyp_0: 'VALUE_9',
        dia_0: 'VALUE_9',
        sevlin_0: 'VALUE_9',
        bpcnumbps_0: 'VALUE_9',
        invdtaamt_0: 94.5,
        ltimrkcoe_0: new Date().toISOString(),
        ordminamt_0: 94.5,
        dudclc_0: 'VALUE_9',
        paylokflg_0: 'VALUE_9',
        norprnflg_0: 'VALUE_9',
        bpssho_0: 'VALUE_9',
        primrkcoe_0: 94.5,
        bpainv_0: 'VALUE_9',
        eecloc_0: 'VALUE_9',
        abccls_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
      },
      {
        x4eltpoiapp_0: 'VALUE_10',
        xrskmrktgt_0: 'VALUE_10',
        flg281_0: true,
        die_0: 'VALUE_10',
        cshdat_0: new Date().toISOString().split('T')[0],
        cshvat_0: 'VALUE_10',
        iptexs_0: 'VALUE_10',
        bpcnum_0: 'BPS0010',
        rexnum_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        autinvcod_0: 'VALUE_10',
        wlflg_0: 'VALUE_10',
        ordfrefrt_0: 'VALUE_10',
        bprdsp_0: 'VALUE_10',
        ynbdoc_0: 'VALUE_10',
        xseuilrad_0: 'VALUE_10',
        bpsrsk_0: 'VALUE_10',
        loc_0: 'VALUE_10',
        pte_0: 'VALUE_10',
        invdta_0: 'VALUE_10',
        vacbpr_0: 'VALUE_10',
        cai_0: 'VALUE_10',
        datvlycai_0: new Date().toISOString().split('T')[0],
        bpsinv_0: 'VALUE_10',
        bpsnum_0: 'VALUE_10',
        bpstyp_0: 'VALUE_10',
        qlymrkcoe_0: 'VALUE_10',
        qtymrkcoe_0: 105.0,
        rskmrkcoe_0: 'VALUE_10',
        rskmrk_0: 'VALUE_10',
        ostauzamt_0: 105.0,
        eecincrat_0: 'VALUE_10',
        bpaadd_0: 'VALUE_10',
        prvnum_0: 'VALUE_10',
        cntnam_0: 'Nom contact par defaut 10',
        purprityp_0: 105.0,
        nreprnflg_0: 'VALUE_10',
        nrtprnflg_0: 'VALUE_10',
        ritnbr_0: 'VALUE_10',
        ritrat_0: 'VALUE_10',
        ritparnbr_0: 'VALUE_10',
        ritparnam_0: 'VALUE_10',
        ritparcoe_0: 'VALUE_10',
        bpsgru_0: 'VALUE_10',
        douflg_0: 'VALUE_10',
        mdl_0: 'VALUE_10',
        uvycod_0: 'VALUE_10',
        ltimrk_0: new Date().toISOString(),
        primrk_0: 105.0,
        qlymrk_0: 'VALUE_10',
        qtymrk_0: 105.0,
        genmrk_0: 'VALUE_10',
        bpsrem_0: 'VALUE_10',
        enaflg_0: true,
        agtpcp_0: 'VALUE_10',
        acccod_0: 'VALUE_10',
        mattol_0: 'VALUE_10',
        frm1099_0: 'VALUE_10',
        box1099_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        x4aexpdlach_0: 'VALUE_10',
        xdmrpar_0: 'VALUE_10',
        xltimrktgt_0: new Date().toISOString(),
        xprimrktgt_0: 105.0,
        xqlymrktgt_0: 'VALUE_10',
        xqtymrktgt_0: 105.0,
        x4eltnbrcol_0: 'VALUE_10',
        x4eltpoi_0: 'VALUE_10',
        tsscod_0: 'VALUE_10',
        tpmcod_0: 'VALUE_10',
        bpsnam_0: 'VALUE_10',
        bptnum_0: 'VALUE_10',
        plistc_0: 'VALUE_10',
        eecict_0: 'VALUE_10',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_10',
        xpohtypbps_0: 'VALUE_10',
        curclc_0: 'VALUE_10',
        amtcod_0: 105.0,
        agtsattax_0: 'VALUE_10',
        flgsattax_0: true,
        sattax_0: 'VALUE_10',
        ritcod_0: 'VALUE_10',
        xaudit_0: 'VALUE_10',
        bpapay_0: 'VALUE_10',
        zsigfab_0: 'VALUE_10',
        dep_0: 'VALUE_10',
        dadflg_0: 'VALUE_10',
        payban_0: 'VALUE_10',
        fupflg_0: 'VALUE_10',
        ocnflg_0: 'VALUE_10',
        ordtex_0: 'VALUE_10',
        rtntex_0: 'VALUE_10',
        cce_0: 'VALUE_10',
        bsgcod_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_10',
        cur_0: 'VALUE_10',
        ostctl_0: 'VALUE_10',
        chgtyp_0: 'VALUE_10',
        dia_0: 'VALUE_10',
        sevlin_0: 'VALUE_10',
        bpcnumbps_0: 'VALUE_10',
        invdtaamt_0: 105.0,
        ltimrkcoe_0: new Date().toISOString(),
        ordminamt_0: 105.0,
        dudclc_0: 'VALUE_10',
        paylokflg_0: 'VALUE_10',
        norprnflg_0: 'VALUE_10',
        bpssho_0: 'VALUE_10',
        primrkcoe_0: 105.0,
        bpainv_0: 'VALUE_10',
        eecloc_0: 'VALUE_10',
        abccls_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
      },
    ]

    await Database.table('bpsupplier').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans bpsupplier`)
  }
}
