import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour ITMBPS
    const data = [
      {
        zfabnum_0: 'ITM0001',
        zitmreffab_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcryorig_0: 'VALUE_1',
        defbpsflg_0: 'VALUE_1',
        stcnum_0: 'VALUE_1',
        loaeccflg_0: 'VALUE_1',
        cpramt_0: 10.5,
        mattol_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        qlymrk_0: 'VALUE_1',
        pcu_0: 'VALUE_1',
        pio_0: 'VALUE_1',
        bomalt_0: 'VALUE_1',
        scolti_0: 'VALUE_1',
        xftscod_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        xdmrpar_0: 'VALUE_1',
        xpntmonte_0: 'VALUE_1',
        x4multisou_0: 'VALUE_1',
        quafry_0: 'VALUE_1',
        quanum_0: 'VALUE_1',
        itmdesbps_0: 'Désignation article chez fourn 1',
        eancodbps_0: 'VALUE_1',
        puu_0: 'VALUE_1',
        defctmbpsflg_0: 'VALUE_1',
        qlycrd_0: 'VALUE_1',
        quaadxuid_0: 'VALUE_1',
        quanumuid_0: 'VALUE_1',
        ctmbpsflg_0: 'VALUE_1',
        tex_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        zsigfab_0: 'VALUE_1',
        cfgvcrnum_0: 'VALUE_1',
        itmref_0: 'VALUE_1',
        douflg_0: 'VALUE_1',
        cprcoe_0: 'VALUE_1',
        itmrefbps_0: 'VALUE_1',
        updusr_0: 'VALUE_1',
        puustucoe_0: 'VALUE_1',
        pcupuucoe_0: 'VALUE_1',
        purminqty_0: 10.5,
        zbpsnum_0: 'VALUE_1',
        bpsnum_0: 'VALUE_1',
        eecincrat_0: 'VALUE_1',
        quaflg_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
      },
      {
        zfabnum_0: 'ITM0002',
        zitmreffab_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcryorig_0: 'VALUE_2',
        defbpsflg_0: 'VALUE_2',
        stcnum_0: 'VALUE_2',
        loaeccflg_0: 'VALUE_2',
        cpramt_0: 21.0,
        mattol_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        qlymrk_0: 'VALUE_2',
        pcu_0: 'VALUE_2',
        pio_0: 'VALUE_2',
        bomalt_0: 'VALUE_2',
        scolti_0: 'VALUE_2',
        xftscod_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        xdmrpar_0: 'VALUE_2',
        xpntmonte_0: 'VALUE_2',
        x4multisou_0: 'VALUE_2',
        quafry_0: 'VALUE_2',
        quanum_0: 'VALUE_2',
        itmdesbps_0: 'Désignation article chez fourn 2',
        eancodbps_0: 'VALUE_2',
        puu_0: 'VALUE_2',
        defctmbpsflg_0: 'VALUE_2',
        qlycrd_0: 'VALUE_2',
        quaadxuid_0: 'VALUE_2',
        quanumuid_0: 'VALUE_2',
        ctmbpsflg_0: 'VALUE_2',
        tex_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        zsigfab_0: 'VALUE_2',
        cfgvcrnum_0: 'VALUE_2',
        itmref_0: 'VALUE_2',
        douflg_0: 'VALUE_2',
        cprcoe_0: 'VALUE_2',
        itmrefbps_0: 'VALUE_2',
        updusr_0: 'VALUE_2',
        puustucoe_0: 'VALUE_2',
        pcupuucoe_0: 'VALUE_2',
        purminqty_0: 21.0,
        zbpsnum_0: 'VALUE_2',
        bpsnum_0: 'VALUE_2',
        eecincrat_0: 'VALUE_2',
        quaflg_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
      },
      {
        zfabnum_0: 'ITM0003',
        zitmreffab_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcryorig_0: 'VALUE_3',
        defbpsflg_0: 'VALUE_3',
        stcnum_0: 'VALUE_3',
        loaeccflg_0: 'VALUE_3',
        cpramt_0: 31.5,
        mattol_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        qlymrk_0: 'VALUE_3',
        pcu_0: 'VALUE_3',
        pio_0: 'VALUE_3',
        bomalt_0: 'VALUE_3',
        scolti_0: 'VALUE_3',
        xftscod_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        xdmrpar_0: 'VALUE_3',
        xpntmonte_0: 'VALUE_3',
        x4multisou_0: 'VALUE_3',
        quafry_0: 'VALUE_3',
        quanum_0: 'VALUE_3',
        itmdesbps_0: 'Désignation article chez fourn 3',
        eancodbps_0: 'VALUE_3',
        puu_0: 'VALUE_3',
        defctmbpsflg_0: 'VALUE_3',
        qlycrd_0: 'VALUE_3',
        quaadxuid_0: 'VALUE_3',
        quanumuid_0: 'VALUE_3',
        ctmbpsflg_0: 'VALUE_3',
        tex_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        zsigfab_0: 'VALUE_3',
        cfgvcrnum_0: 'VALUE_3',
        itmref_0: 'VALUE_3',
        douflg_0: 'VALUE_3',
        cprcoe_0: 'VALUE_3',
        itmrefbps_0: 'VALUE_3',
        updusr_0: 'VALUE_3',
        puustucoe_0: 'VALUE_3',
        pcupuucoe_0: 'VALUE_3',
        purminqty_0: 31.5,
        zbpsnum_0: 'VALUE_3',
        bpsnum_0: 'VALUE_3',
        eecincrat_0: 'VALUE_3',
        quaflg_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
      },
      {
        zfabnum_0: 'ITM0004',
        zitmreffab_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcryorig_0: 'VALUE_4',
        defbpsflg_0: 'VALUE_4',
        stcnum_0: 'VALUE_4',
        loaeccflg_0: 'VALUE_4',
        cpramt_0: 42.0,
        mattol_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        qlymrk_0: 'VALUE_4',
        pcu_0: 'VALUE_4',
        pio_0: 'VALUE_4',
        bomalt_0: 'VALUE_4',
        scolti_0: 'VALUE_4',
        xftscod_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        xdmrpar_0: 'VALUE_4',
        xpntmonte_0: 'VALUE_4',
        x4multisou_0: 'VALUE_4',
        quafry_0: 'VALUE_4',
        quanum_0: 'VALUE_4',
        itmdesbps_0: 'Désignation article chez fourn 4',
        eancodbps_0: 'VALUE_4',
        puu_0: 'VALUE_4',
        defctmbpsflg_0: 'VALUE_4',
        qlycrd_0: 'VALUE_4',
        quaadxuid_0: 'VALUE_4',
        quanumuid_0: 'VALUE_4',
        ctmbpsflg_0: 'VALUE_4',
        tex_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        zsigfab_0: 'VALUE_4',
        cfgvcrnum_0: 'VALUE_4',
        itmref_0: 'VALUE_4',
        douflg_0: 'VALUE_4',
        cprcoe_0: 'VALUE_4',
        itmrefbps_0: 'VALUE_4',
        updusr_0: 'VALUE_4',
        puustucoe_0: 'VALUE_4',
        pcupuucoe_0: 'VALUE_4',
        purminqty_0: 42.0,
        zbpsnum_0: 'VALUE_4',
        bpsnum_0: 'VALUE_4',
        eecincrat_0: 'VALUE_4',
        quaflg_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
      },
      {
        zfabnum_0: 'ITM0005',
        zitmreffab_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcryorig_0: 'VALUE_5',
        defbpsflg_0: 'VALUE_5',
        stcnum_0: 'VALUE_5',
        loaeccflg_0: 'VALUE_5',
        cpramt_0: 52.5,
        mattol_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        qlymrk_0: 'VALUE_5',
        pcu_0: 'VALUE_5',
        pio_0: 'VALUE_5',
        bomalt_0: 'VALUE_5',
        scolti_0: 'VALUE_5',
        xftscod_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        xdmrpar_0: 'VALUE_5',
        xpntmonte_0: 'VALUE_5',
        x4multisou_0: 'VALUE_5',
        quafry_0: 'VALUE_5',
        quanum_0: 'VALUE_5',
        itmdesbps_0: 'Désignation article chez fourn 5',
        eancodbps_0: 'VALUE_5',
        puu_0: 'VALUE_5',
        defctmbpsflg_0: 'VALUE_5',
        qlycrd_0: 'VALUE_5',
        quaadxuid_0: 'VALUE_5',
        quanumuid_0: 'VALUE_5',
        ctmbpsflg_0: 'VALUE_5',
        tex_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        zsigfab_0: 'VALUE_5',
        cfgvcrnum_0: 'VALUE_5',
        itmref_0: 'VALUE_5',
        douflg_0: 'VALUE_5',
        cprcoe_0: 'VALUE_5',
        itmrefbps_0: 'VALUE_5',
        updusr_0: 'VALUE_5',
        puustucoe_0: 'VALUE_5',
        pcupuucoe_0: 'VALUE_5',
        purminqty_0: 52.5,
        zbpsnum_0: 'VALUE_5',
        bpsnum_0: 'VALUE_5',
        eecincrat_0: 'VALUE_5',
        quaflg_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
      },
      {
        zfabnum_0: 'ITM0006',
        zitmreffab_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcryorig_0: 'VALUE_6',
        defbpsflg_0: 'VALUE_6',
        stcnum_0: 'VALUE_6',
        loaeccflg_0: 'VALUE_6',
        cpramt_0: 63.0,
        mattol_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        qlymrk_0: 'VALUE_6',
        pcu_0: 'VALUE_6',
        pio_0: 'VALUE_6',
        bomalt_0: 'VALUE_6',
        scolti_0: 'VALUE_6',
        xftscod_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        xdmrpar_0: 'VALUE_6',
        xpntmonte_0: 'VALUE_6',
        x4multisou_0: 'VALUE_6',
        quafry_0: 'VALUE_6',
        quanum_0: 'VALUE_6',
        itmdesbps_0: 'Désignation article chez fourn 6',
        eancodbps_0: 'VALUE_6',
        puu_0: 'VALUE_6',
        defctmbpsflg_0: 'VALUE_6',
        qlycrd_0: 'VALUE_6',
        quaadxuid_0: 'VALUE_6',
        quanumuid_0: 'VALUE_6',
        ctmbpsflg_0: 'VALUE_6',
        tex_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        zsigfab_0: 'VALUE_6',
        cfgvcrnum_0: 'VALUE_6',
        itmref_0: 'VALUE_6',
        douflg_0: 'VALUE_6',
        cprcoe_0: 'VALUE_6',
        itmrefbps_0: 'VALUE_6',
        updusr_0: 'VALUE_6',
        puustucoe_0: 'VALUE_6',
        pcupuucoe_0: 'VALUE_6',
        purminqty_0: 63.0,
        zbpsnum_0: 'VALUE_6',
        bpsnum_0: 'VALUE_6',
        eecincrat_0: 'VALUE_6',
        quaflg_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
      },
      {
        zfabnum_0: 'ITM0007',
        zitmreffab_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcryorig_0: 'VALUE_7',
        defbpsflg_0: 'VALUE_7',
        stcnum_0: 'VALUE_7',
        loaeccflg_0: 'VALUE_7',
        cpramt_0: 73.5,
        mattol_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        qlymrk_0: 'VALUE_7',
        pcu_0: 'VALUE_7',
        pio_0: 'VALUE_7',
        bomalt_0: 'VALUE_7',
        scolti_0: 'VALUE_7',
        xftscod_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        xdmrpar_0: 'VALUE_7',
        xpntmonte_0: 'VALUE_7',
        x4multisou_0: 'VALUE_7',
        quafry_0: 'VALUE_7',
        quanum_0: 'VALUE_7',
        itmdesbps_0: 'Désignation article chez fourn 7',
        eancodbps_0: 'VALUE_7',
        puu_0: 'VALUE_7',
        defctmbpsflg_0: 'VALUE_7',
        qlycrd_0: 'VALUE_7',
        quaadxuid_0: 'VALUE_7',
        quanumuid_0: 'VALUE_7',
        ctmbpsflg_0: 'VALUE_7',
        tex_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        zsigfab_0: 'VALUE_7',
        cfgvcrnum_0: 'VALUE_7',
        itmref_0: 'VALUE_7',
        douflg_0: 'VALUE_7',
        cprcoe_0: 'VALUE_7',
        itmrefbps_0: 'VALUE_7',
        updusr_0: 'VALUE_7',
        puustucoe_0: 'VALUE_7',
        pcupuucoe_0: 'VALUE_7',
        purminqty_0: 73.5,
        zbpsnum_0: 'VALUE_7',
        bpsnum_0: 'VALUE_7',
        eecincrat_0: 'VALUE_7',
        quaflg_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
      },
      {
        zfabnum_0: 'ITM0008',
        zitmreffab_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcryorig_0: 'VALUE_8',
        defbpsflg_0: 'VALUE_8',
        stcnum_0: 'VALUE_8',
        loaeccflg_0: 'VALUE_8',
        cpramt_0: 84.0,
        mattol_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        qlymrk_0: 'VALUE_8',
        pcu_0: 'VALUE_8',
        pio_0: 'VALUE_8',
        bomalt_0: 'VALUE_8',
        scolti_0: 'VALUE_8',
        xftscod_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        xdmrpar_0: 'VALUE_8',
        xpntmonte_0: 'VALUE_8',
        x4multisou_0: 'VALUE_8',
        quafry_0: 'VALUE_8',
        quanum_0: 'VALUE_8',
        itmdesbps_0: 'Désignation article chez fourn 8',
        eancodbps_0: 'VALUE_8',
        puu_0: 'VALUE_8',
        defctmbpsflg_0: 'VALUE_8',
        qlycrd_0: 'VALUE_8',
        quaadxuid_0: 'VALUE_8',
        quanumuid_0: 'VALUE_8',
        ctmbpsflg_0: 'VALUE_8',
        tex_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        zsigfab_0: 'VALUE_8',
        cfgvcrnum_0: 'VALUE_8',
        itmref_0: 'VALUE_8',
        douflg_0: 'VALUE_8',
        cprcoe_0: 'VALUE_8',
        itmrefbps_0: 'VALUE_8',
        updusr_0: 'VALUE_8',
        puustucoe_0: 'VALUE_8',
        pcupuucoe_0: 'VALUE_8',
        purminqty_0: 84.0,
        zbpsnum_0: 'VALUE_8',
        bpsnum_0: 'VALUE_8',
        eecincrat_0: 'VALUE_8',
        quaflg_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
      },
      {
        zfabnum_0: 'ITM0009',
        zitmreffab_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcryorig_0: 'VALUE_9',
        defbpsflg_0: 'VALUE_9',
        stcnum_0: 'VALUE_9',
        loaeccflg_0: 'VALUE_9',
        cpramt_0: 94.5,
        mattol_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        qlymrk_0: 'VALUE_9',
        pcu_0: 'VALUE_9',
        pio_0: 'VALUE_9',
        bomalt_0: 'VALUE_9',
        scolti_0: 'VALUE_9',
        xftscod_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        xdmrpar_0: 'VALUE_9',
        xpntmonte_0: 'VALUE_9',
        x4multisou_0: 'VALUE_9',
        quafry_0: 'VALUE_9',
        quanum_0: 'VALUE_9',
        itmdesbps_0: 'Désignation article chez fourn 9',
        eancodbps_0: 'VALUE_9',
        puu_0: 'VALUE_9',
        defctmbpsflg_0: 'VALUE_9',
        qlycrd_0: 'VALUE_9',
        quaadxuid_0: 'VALUE_9',
        quanumuid_0: 'VALUE_9',
        ctmbpsflg_0: 'VALUE_9',
        tex_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        zsigfab_0: 'VALUE_9',
        cfgvcrnum_0: 'VALUE_9',
        itmref_0: 'VALUE_9',
        douflg_0: 'VALUE_9',
        cprcoe_0: 'VALUE_9',
        itmrefbps_0: 'VALUE_9',
        updusr_0: 'VALUE_9',
        puustucoe_0: 'VALUE_9',
        pcupuucoe_0: 'VALUE_9',
        purminqty_0: 94.5,
        zbpsnum_0: 'VALUE_9',
        bpsnum_0: 'VALUE_9',
        eecincrat_0: 'VALUE_9',
        quaflg_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
      },
      {
        zfabnum_0: 'ITM0010',
        zitmreffab_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcryorig_0: 'VALUE_10',
        defbpsflg_0: 'VALUE_10',
        stcnum_0: 'VALUE_10',
        loaeccflg_0: 'VALUE_10',
        cpramt_0: 105.0,
        mattol_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        qlymrk_0: 'VALUE_10',
        pcu_0: 'VALUE_10',
        pio_0: 'VALUE_10',
        bomalt_0: 'VALUE_10',
        scolti_0: 'VALUE_10',
        xftscod_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        xdmrpar_0: 'VALUE_10',
        xpntmonte_0: 'VALUE_10',
        x4multisou_0: 'VALUE_10',
        quafry_0: 'VALUE_10',
        quanum_0: 'VALUE_10',
        itmdesbps_0: 'Désignation article chez fourn 10',
        eancodbps_0: 'VALUE_10',
        puu_0: 'VALUE_10',
        defctmbpsflg_0: 'VALUE_10',
        qlycrd_0: 'VALUE_10',
        quaadxuid_0: 'VALUE_10',
        quanumuid_0: 'VALUE_10',
        ctmbpsflg_0: 'VALUE_10',
        tex_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        zsigfab_0: 'VALUE_10',
        cfgvcrnum_0: 'VALUE_10',
        itmref_0: 'VALUE_10',
        douflg_0: 'VALUE_10',
        cprcoe_0: 'VALUE_10',
        itmrefbps_0: 'VALUE_10',
        updusr_0: 'VALUE_10',
        puustucoe_0: 'VALUE_10',
        pcupuucoe_0: 'VALUE_10',
        purminqty_0: 105.0,
        zbpsnum_0: 'VALUE_10',
        bpsnum_0: 'VALUE_10',
        eecincrat_0: 'VALUE_10',
        quaflg_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
      },
    ]

    await Database.table('itmbps').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans itmbps`)
  }
}
