import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour STOCK
    const data = [
      {
        sta_0: 1,
        loc_0: 'VALUE_1',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        pcustucoe_0: 'VALUE_1',
        stofcy_0: 'VALUE_1',
        qlyctldem_0: 'VALUE_1',
        qtystu_0: 10.5,
        wrh_0: 'VALUE_1',
        bpslot_0: 'VALUE_1',
        itmref_0: 'STO0001',
        loccat_0: 'VALUE_1',
        cumwipqty_0: 10.5,
        credat_0: new Date().toISOString().split('T')[0],
        qtystuori_0: 10.5,
        qtypcu_0: 10.5,
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_1',
        cumallqta_0: 'VALUE_1',
        qtystuact_0: 10.5,
        stofld1_0: 'VALUE_1',
        stofld2_0: 'VALUE_1',
        owner_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cumwipqta_0: 'VALUE_1',
        pcuori_0: 'VALUE_1',
        qtypcuori_0: 10.5,
        auuid_0: 'VALUE_1',
        eccvalmaj_0: 'VALUE_1',
        pjt_0: 'VALUE_1',
        lot_0: 'VALUE_1',
        slo_0: 'VALUE_1',
        cunlisnum_0: 'VALUE_1',
        cunlokflg_0: 'VALUE_1',
        palnum_0: 'VALUE_1',
        rcpdat_0: new Date().toISOString().split('T')[0],
        lpnnum_0: 'VALUE_1',
        pcu_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        ctrnum_0: 'VALUE_1',
        cumallqty_0: 10.5,
        edtflg_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        stocou_0: 'VALUE_1',
        lasissdat_0: new Date().toISOString().split('T')[0],
        lascundat_0: new Date().toISOString().split('T')[0],
        sernum_0: 'VALUE_1',
        loctyp_0: 'VALUE_1',
      },
      {
        sta_0: 1,
        loc_0: 'VALUE_2',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        pcustucoe_0: 'VALUE_2',
        stofcy_0: 'VALUE_2',
        qlyctldem_0: 'VALUE_2',
        qtystu_0: 21.0,
        wrh_0: 'VALUE_2',
        bpslot_0: 'VALUE_2',
        itmref_0: 'STO0002',
        loccat_0: 'VALUE_2',
        cumwipqty_0: 21.0,
        credat_0: new Date().toISOString().split('T')[0],
        qtystuori_0: 21.0,
        qtypcu_0: 21.0,
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_2',
        cumallqta_0: 'VALUE_2',
        qtystuact_0: 21.0,
        stofld1_0: 'VALUE_2',
        stofld2_0: 'VALUE_2',
        owner_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cumwipqta_0: 'VALUE_2',
        pcuori_0: 'VALUE_2',
        qtypcuori_0: 21.0,
        auuid_0: 'VALUE_2',
        eccvalmaj_0: 'VALUE_2',
        pjt_0: 'VALUE_2',
        lot_0: 'VALUE_2',
        slo_0: 'VALUE_2',
        cunlisnum_0: 'VALUE_2',
        cunlokflg_0: 'VALUE_2',
        palnum_0: 'VALUE_2',
        rcpdat_0: new Date().toISOString().split('T')[0],
        lpnnum_0: 'VALUE_2',
        pcu_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        ctrnum_0: 'VALUE_2',
        cumallqty_0: 21.0,
        edtflg_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        stocou_0: 'VALUE_2',
        lasissdat_0: new Date().toISOString().split('T')[0],
        lascundat_0: new Date().toISOString().split('T')[0],
        sernum_0: 'VALUE_2',
        loctyp_0: 'VALUE_2',
      },
      {
        sta_0: 1,
        loc_0: 'VALUE_3',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        pcustucoe_0: 'VALUE_3',
        stofcy_0: 'VALUE_3',
        qlyctldem_0: 'VALUE_3',
        qtystu_0: 31.5,
        wrh_0: 'VALUE_3',
        bpslot_0: 'VALUE_3',
        itmref_0: 'STO0003',
        loccat_0: 'VALUE_3',
        cumwipqty_0: 31.5,
        credat_0: new Date().toISOString().split('T')[0],
        qtystuori_0: 31.5,
        qtypcu_0: 31.5,
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_3',
        cumallqta_0: 'VALUE_3',
        qtystuact_0: 31.5,
        stofld1_0: 'VALUE_3',
        stofld2_0: 'VALUE_3',
        owner_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cumwipqta_0: 'VALUE_3',
        pcuori_0: 'VALUE_3',
        qtypcuori_0: 31.5,
        auuid_0: 'VALUE_3',
        eccvalmaj_0: 'VALUE_3',
        pjt_0: 'VALUE_3',
        lot_0: 'VALUE_3',
        slo_0: 'VALUE_3',
        cunlisnum_0: 'VALUE_3',
        cunlokflg_0: 'VALUE_3',
        palnum_0: 'VALUE_3',
        rcpdat_0: new Date().toISOString().split('T')[0],
        lpnnum_0: 'VALUE_3',
        pcu_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        ctrnum_0: 'VALUE_3',
        cumallqty_0: 31.5,
        edtflg_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        stocou_0: 'VALUE_3',
        lasissdat_0: new Date().toISOString().split('T')[0],
        lascundat_0: new Date().toISOString().split('T')[0],
        sernum_0: 'VALUE_3',
        loctyp_0: 'VALUE_3',
      },
      {
        sta_0: 1,
        loc_0: 'VALUE_4',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        pcustucoe_0: 'VALUE_4',
        stofcy_0: 'VALUE_4',
        qlyctldem_0: 'VALUE_4',
        qtystu_0: 42.0,
        wrh_0: 'VALUE_4',
        bpslot_0: 'VALUE_4',
        itmref_0: 'STO0004',
        loccat_0: 'VALUE_4',
        cumwipqty_0: 42.0,
        credat_0: new Date().toISOString().split('T')[0],
        qtystuori_0: 42.0,
        qtypcu_0: 42.0,
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_4',
        cumallqta_0: 'VALUE_4',
        qtystuact_0: 42.0,
        stofld1_0: 'VALUE_4',
        stofld2_0: 'VALUE_4',
        owner_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cumwipqta_0: 'VALUE_4',
        pcuori_0: 'VALUE_4',
        qtypcuori_0: 42.0,
        auuid_0: 'VALUE_4',
        eccvalmaj_0: 'VALUE_4',
        pjt_0: 'VALUE_4',
        lot_0: 'VALUE_4',
        slo_0: 'VALUE_4',
        cunlisnum_0: 'VALUE_4',
        cunlokflg_0: 'VALUE_4',
        palnum_0: 'VALUE_4',
        rcpdat_0: new Date().toISOString().split('T')[0],
        lpnnum_0: 'VALUE_4',
        pcu_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        ctrnum_0: 'VALUE_4',
        cumallqty_0: 42.0,
        edtflg_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        stocou_0: 'VALUE_4',
        lasissdat_0: new Date().toISOString().split('T')[0],
        lascundat_0: new Date().toISOString().split('T')[0],
        sernum_0: 'VALUE_4',
        loctyp_0: 'VALUE_4',
      },
      {
        sta_0: 1,
        loc_0: 'VALUE_5',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        pcustucoe_0: 'VALUE_5',
        stofcy_0: 'VALUE_5',
        qlyctldem_0: 'VALUE_5',
        qtystu_0: 52.5,
        wrh_0: 'VALUE_5',
        bpslot_0: 'VALUE_5',
        itmref_0: 'STO0005',
        loccat_0: 'VALUE_5',
        cumwipqty_0: 52.5,
        credat_0: new Date().toISOString().split('T')[0],
        qtystuori_0: 52.5,
        qtypcu_0: 52.5,
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_5',
        cumallqta_0: 'VALUE_5',
        qtystuact_0: 52.5,
        stofld1_0: 'VALUE_5',
        stofld2_0: 'VALUE_5',
        owner_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cumwipqta_0: 'VALUE_5',
        pcuori_0: 'VALUE_5',
        qtypcuori_0: 52.5,
        auuid_0: 'VALUE_5',
        eccvalmaj_0: 'VALUE_5',
        pjt_0: 'VALUE_5',
        lot_0: 'VALUE_5',
        slo_0: 'VALUE_5',
        cunlisnum_0: 'VALUE_5',
        cunlokflg_0: 'VALUE_5',
        palnum_0: 'VALUE_5',
        rcpdat_0: new Date().toISOString().split('T')[0],
        lpnnum_0: 'VALUE_5',
        pcu_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        ctrnum_0: 'VALUE_5',
        cumallqty_0: 52.5,
        edtflg_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        stocou_0: 'VALUE_5',
        lasissdat_0: new Date().toISOString().split('T')[0],
        lascundat_0: new Date().toISOString().split('T')[0],
        sernum_0: 'VALUE_5',
        loctyp_0: 'VALUE_5',
      },
      {
        sta_0: 1,
        loc_0: 'VALUE_6',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        pcustucoe_0: 'VALUE_6',
        stofcy_0: 'VALUE_6',
        qlyctldem_0: 'VALUE_6',
        qtystu_0: 63.0,
        wrh_0: 'VALUE_6',
        bpslot_0: 'VALUE_6',
        itmref_0: 'STO0006',
        loccat_0: 'VALUE_6',
        cumwipqty_0: 63.0,
        credat_0: new Date().toISOString().split('T')[0],
        qtystuori_0: 63.0,
        qtypcu_0: 63.0,
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_6',
        cumallqta_0: 'VALUE_6',
        qtystuact_0: 63.0,
        stofld1_0: 'VALUE_6',
        stofld2_0: 'VALUE_6',
        owner_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cumwipqta_0: 'VALUE_6',
        pcuori_0: 'VALUE_6',
        qtypcuori_0: 63.0,
        auuid_0: 'VALUE_6',
        eccvalmaj_0: 'VALUE_6',
        pjt_0: 'VALUE_6',
        lot_0: 'VALUE_6',
        slo_0: 'VALUE_6',
        cunlisnum_0: 'VALUE_6',
        cunlokflg_0: 'VALUE_6',
        palnum_0: 'VALUE_6',
        rcpdat_0: new Date().toISOString().split('T')[0],
        lpnnum_0: 'VALUE_6',
        pcu_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        ctrnum_0: 'VALUE_6',
        cumallqty_0: 63.0,
        edtflg_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        stocou_0: 'VALUE_6',
        lasissdat_0: new Date().toISOString().split('T')[0],
        lascundat_0: new Date().toISOString().split('T')[0],
        sernum_0: 'VALUE_6',
        loctyp_0: 'VALUE_6',
      },
      {
        sta_0: 1,
        loc_0: 'VALUE_7',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        pcustucoe_0: 'VALUE_7',
        stofcy_0: 'VALUE_7',
        qlyctldem_0: 'VALUE_7',
        qtystu_0: 73.5,
        wrh_0: 'VALUE_7',
        bpslot_0: 'VALUE_7',
        itmref_0: 'STO0007',
        loccat_0: 'VALUE_7',
        cumwipqty_0: 73.5,
        credat_0: new Date().toISOString().split('T')[0],
        qtystuori_0: 73.5,
        qtypcu_0: 73.5,
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_7',
        cumallqta_0: 'VALUE_7',
        qtystuact_0: 73.5,
        stofld1_0: 'VALUE_7',
        stofld2_0: 'VALUE_7',
        owner_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cumwipqta_0: 'VALUE_7',
        pcuori_0: 'VALUE_7',
        qtypcuori_0: 73.5,
        auuid_0: 'VALUE_7',
        eccvalmaj_0: 'VALUE_7',
        pjt_0: 'VALUE_7',
        lot_0: 'VALUE_7',
        slo_0: 'VALUE_7',
        cunlisnum_0: 'VALUE_7',
        cunlokflg_0: 'VALUE_7',
        palnum_0: 'VALUE_7',
        rcpdat_0: new Date().toISOString().split('T')[0],
        lpnnum_0: 'VALUE_7',
        pcu_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        ctrnum_0: 'VALUE_7',
        cumallqty_0: 73.5,
        edtflg_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        stocou_0: 'VALUE_7',
        lasissdat_0: new Date().toISOString().split('T')[0],
        lascundat_0: new Date().toISOString().split('T')[0],
        sernum_0: 'VALUE_7',
        loctyp_0: 'VALUE_7',
      },
      {
        sta_0: 1,
        loc_0: 'VALUE_8',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        pcustucoe_0: 'VALUE_8',
        stofcy_0: 'VALUE_8',
        qlyctldem_0: 'VALUE_8',
        qtystu_0: 84.0,
        wrh_0: 'VALUE_8',
        bpslot_0: 'VALUE_8',
        itmref_0: 'STO0008',
        loccat_0: 'VALUE_8',
        cumwipqty_0: 84.0,
        credat_0: new Date().toISOString().split('T')[0],
        qtystuori_0: 84.0,
        qtypcu_0: 84.0,
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_8',
        cumallqta_0: 'VALUE_8',
        qtystuact_0: 84.0,
        stofld1_0: 'VALUE_8',
        stofld2_0: 'VALUE_8',
        owner_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cumwipqta_0: 'VALUE_8',
        pcuori_0: 'VALUE_8',
        qtypcuori_0: 84.0,
        auuid_0: 'VALUE_8',
        eccvalmaj_0: 'VALUE_8',
        pjt_0: 'VALUE_8',
        lot_0: 'VALUE_8',
        slo_0: 'VALUE_8',
        cunlisnum_0: 'VALUE_8',
        cunlokflg_0: 'VALUE_8',
        palnum_0: 'VALUE_8',
        rcpdat_0: new Date().toISOString().split('T')[0],
        lpnnum_0: 'VALUE_8',
        pcu_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        ctrnum_0: 'VALUE_8',
        cumallqty_0: 84.0,
        edtflg_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        stocou_0: 'VALUE_8',
        lasissdat_0: new Date().toISOString().split('T')[0],
        lascundat_0: new Date().toISOString().split('T')[0],
        sernum_0: 'VALUE_8',
        loctyp_0: 'VALUE_8',
      },
      {
        sta_0: 1,
        loc_0: 'VALUE_9',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        pcustucoe_0: 'VALUE_9',
        stofcy_0: 'VALUE_9',
        qlyctldem_0: 'VALUE_9',
        qtystu_0: 94.5,
        wrh_0: 'VALUE_9',
        bpslot_0: 'VALUE_9',
        itmref_0: 'STO0009',
        loccat_0: 'VALUE_9',
        cumwipqty_0: 94.5,
        credat_0: new Date().toISOString().split('T')[0],
        qtystuori_0: 94.5,
        qtypcu_0: 94.5,
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_9',
        cumallqta_0: 'VALUE_9',
        qtystuact_0: 94.5,
        stofld1_0: 'VALUE_9',
        stofld2_0: 'VALUE_9',
        owner_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cumwipqta_0: 'VALUE_9',
        pcuori_0: 'VALUE_9',
        qtypcuori_0: 94.5,
        auuid_0: 'VALUE_9',
        eccvalmaj_0: 'VALUE_9',
        pjt_0: 'VALUE_9',
        lot_0: 'VALUE_9',
        slo_0: 'VALUE_9',
        cunlisnum_0: 'VALUE_9',
        cunlokflg_0: 'VALUE_9',
        palnum_0: 'VALUE_9',
        rcpdat_0: new Date().toISOString().split('T')[0],
        lpnnum_0: 'VALUE_9',
        pcu_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        ctrnum_0: 'VALUE_9',
        cumallqty_0: 94.5,
        edtflg_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        stocou_0: 'VALUE_9',
        lasissdat_0: new Date().toISOString().split('T')[0],
        lascundat_0: new Date().toISOString().split('T')[0],
        sernum_0: 'VALUE_9',
        loctyp_0: 'VALUE_9',
      },
      {
        sta_0: 1,
        loc_0: 'VALUE_10',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        pcustucoe_0: 'VALUE_10',
        stofcy_0: 'VALUE_10',
        qlyctldem_0: 'VALUE_10',
        qtystu_0: 105.0,
        wrh_0: 'VALUE_10',
        bpslot_0: 'VALUE_10',
        itmref_0: 'STO0010',
        loccat_0: 'VALUE_10',
        cumwipqty_0: 105.0,
        credat_0: new Date().toISOString().split('T')[0],
        qtystuori_0: 105.0,
        qtypcu_0: 105.0,
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_10',
        cumallqta_0: 'VALUE_10',
        qtystuact_0: 105.0,
        stofld1_0: 'VALUE_10',
        stofld2_0: 'VALUE_10',
        owner_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cumwipqta_0: 'VALUE_10',
        pcuori_0: 'VALUE_10',
        qtypcuori_0: 105.0,
        auuid_0: 'VALUE_10',
        eccvalmaj_0: 'VALUE_10',
        pjt_0: 'VALUE_10',
        lot_0: 'VALUE_10',
        slo_0: 'VALUE_10',
        cunlisnum_0: 'VALUE_10',
        cunlokflg_0: 'VALUE_10',
        palnum_0: 'VALUE_10',
        rcpdat_0: new Date().toISOString().split('T')[0],
        lpnnum_0: 'VALUE_10',
        pcu_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        ctrnum_0: 'VALUE_10',
        cumallqty_0: 105.0,
        edtflg_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        stocou_0: 'VALUE_10',
        lasissdat_0: new Date().toISOString().split('T')[0],
        lascundat_0: new Date().toISOString().split('T')[0],
        sernum_0: 'VALUE_10',
        loctyp_0: 'VALUE_10',
      },
    ]

    await Database.table('stock').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans stock`)
  }
}
