import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour STOJOU
    const data = [
      {
        owner_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_1',
        amtdev_0: 10.5,
        amtdev2_0: 10.5,
        serfin_0: 'VALUE_1',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        betcpy_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        die_0: 'VALUE_1',
        eccvalmin_0: 'VALUE_1',
        pjt_0: 'VALUE_1',
        lot_0: 'VALUE_1',
        slo_0: 'VALUE_1',
        aggifaflg_0: 'VALUE_1',
        pitvalflg_0: 'VALUE_1',
        pitvalflg2_0: 'VALUE_1',
        serdeb_0: 'VALUE_1',
        pronum_0: 'STO0001',
        vcrnumori_0: 'VALUE_1',
        vcrtypori_0: 'VALUE_1',
        stu_0: 'VALUE_1',
        regflg_0: 'VALUE_1',
        palnum_0: 'VALUE_1',
        vcrtypreg_0: 'VALUE_1',
        stofcy_0: 'VALUE_1',
        cce_0: 'VALUE_1',
        lpnnum_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        updcod_0: 'VALUE_1',
        ctrnum_0: 'VALUE_1',
        iptdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_1',
        sernum_0: 'VALUE_1',
        trstyp_0: 'VALUE_1',
        finrspfcy_0: 'VALUE_1',
        vcrnum_0: 'VALUE_1',
        pcustuori_0: 'VALUE_1',
        vcrlinori_0: 'VALUE_1',
        cstcou_0: 'VALUE_1',
        vcrseqori_0: 'VALUE_1',
        vcrnumreg_0: 'VALUE_1',
        vcrlinreg_0: 'VALUE_1',
        itmref_0: 'VALUE_1',
        xmaccstreg_0: 'VALUE_1',
        xmaccst_0: 'VALUE_1',
        xlabcstreg_0: 'VALUE_1',
        xlabcst_0: 'VALUE_1',
        xscocstreg_0: 'VALUE_1',
        xscocst_0: 'VALUE_1',
        xovematreg_0: 'VALUE_1',
        xovematcst_0: 'VALUE_1',
        xovemacreg_0: 'VALUE_1',
        xovemaccst_0: 'VALUE_1',
        xovelabreg_0: 'VALUE_1',
        xovelabcst_0: 'VALUE_1',
        sta_0: 1,
        xmatcstreg_0: 'VALUE_1',
        xmatcst_0: 'VALUE_1',
        usrfld1_0: 'VALUE_1',
        xovescocst_0: 'VALUE_1',
        xovescoreg_0: 'VALUE_1',
        bprnum_0: 'VALUE_1',
        vcrlin_0: 'VALUE_1',
        usrfld3_0: 'VALUE_1',
        usrfld4_0: 'VALUE_1',
        prnflg_0: 'VALUE_1',
        lbefmt_0: 'VALUE_1',
        qlyctldem_0: 'VALUE_1',
        qtystu_0: 10.5,
        qtypcu_0: 10.5,
        wrh_0: 'VALUE_1',
        loc_0: 'VALUE_1',
        gte_0: 'VALUE_1',
        pot_0: 'VALUE_1',
        mvtseq_0: 'VALUE_1',
        pcu_0: 'VALUE_1',
        bpslot_0: 'VALUE_1',
        amtord_0: 10.5,
        amtval_0: 10.5,
        amtval2_0: 10.5,
        varord_0: 'VALUE_1',
        varval_0: 'VALUE_1',
        varval2_0: 'VALUE_1',
        cstdat_0: new Date().toISOString().split('T')[0],
        csttim_0: new Date().toISOString(),
        priord_0: 10.5,
        upddat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_1',
        credat_0: new Date().toISOString().split('T')[0],
        cremvtdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_1',
        mvtdes_0: 'Désignation mouvement 1',
        prinat_0: 10.5,
        prinat2_0: 10.5,
        act_0: 'VALUE_1',
        actqty_0: 10.5,
        accdat_0: new Date().toISOString().split('T')[0],
        vcrtyp_0: 'VALUE_1',
        mvtind_0: 'VALUE_1',
        pcustucoe_0: 'VALUE_1',
        priregflg_0: 10.5,
        numvcr_0: 'VALUE_1',
        shldat_0: new Date().toISOString().split('T')[0],
        cremvtseq_0: 'VALUE_1',
        entcod_0: 'VALUE_1',
        lbenbr_0: 'VALUE_1',
        trsfam_0: 'VALUE_1',
        cremvttim_0: new Date().toISOString(),
        cretim_0: new Date().toISOString(),
        stofld1_0: 'VALUE_1',
        stofld2_0: 'VALUE_1',
        prival_0: 10.5,
        prival2_0: 10.5,
        pcuori_0: 'VALUE_1',
      },
      {
        owner_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_2',
        amtdev_0: 21.0,
        amtdev2_0: 21.0,
        serfin_0: 'VALUE_2',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        betcpy_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        die_0: 'VALUE_2',
        eccvalmin_0: 'VALUE_2',
        pjt_0: 'VALUE_2',
        lot_0: 'VALUE_2',
        slo_0: 'VALUE_2',
        aggifaflg_0: 'VALUE_2',
        pitvalflg_0: 'VALUE_2',
        pitvalflg2_0: 'VALUE_2',
        serdeb_0: 'VALUE_2',
        pronum_0: 'STO0002',
        vcrnumori_0: 'VALUE_2',
        vcrtypori_0: 'VALUE_2',
        stu_0: 'VALUE_2',
        regflg_0: 'VALUE_2',
        palnum_0: 'VALUE_2',
        vcrtypreg_0: 'VALUE_2',
        stofcy_0: 'VALUE_2',
        cce_0: 'VALUE_2',
        lpnnum_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        updcod_0: 'VALUE_2',
        ctrnum_0: 'VALUE_2',
        iptdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_2',
        sernum_0: 'VALUE_2',
        trstyp_0: 'VALUE_2',
        finrspfcy_0: 'VALUE_2',
        vcrnum_0: 'VALUE_2',
        pcustuori_0: 'VALUE_2',
        vcrlinori_0: 'VALUE_2',
        cstcou_0: 'VALUE_2',
        vcrseqori_0: 'VALUE_2',
        vcrnumreg_0: 'VALUE_2',
        vcrlinreg_0: 'VALUE_2',
        itmref_0: 'VALUE_2',
        xmaccstreg_0: 'VALUE_2',
        xmaccst_0: 'VALUE_2',
        xlabcstreg_0: 'VALUE_2',
        xlabcst_0: 'VALUE_2',
        xscocstreg_0: 'VALUE_2',
        xscocst_0: 'VALUE_2',
        xovematreg_0: 'VALUE_2',
        xovematcst_0: 'VALUE_2',
        xovemacreg_0: 'VALUE_2',
        xovemaccst_0: 'VALUE_2',
        xovelabreg_0: 'VALUE_2',
        xovelabcst_0: 'VALUE_2',
        sta_0: 1,
        xmatcstreg_0: 'VALUE_2',
        xmatcst_0: 'VALUE_2',
        usrfld1_0: 'VALUE_2',
        xovescocst_0: 'VALUE_2',
        xovescoreg_0: 'VALUE_2',
        bprnum_0: 'VALUE_2',
        vcrlin_0: 'VALUE_2',
        usrfld3_0: 'VALUE_2',
        usrfld4_0: 'VALUE_2',
        prnflg_0: 'VALUE_2',
        lbefmt_0: 'VALUE_2',
        qlyctldem_0: 'VALUE_2',
        qtystu_0: 21.0,
        qtypcu_0: 21.0,
        wrh_0: 'VALUE_2',
        loc_0: 'VALUE_2',
        gte_0: 'VALUE_2',
        pot_0: 'VALUE_2',
        mvtseq_0: 'VALUE_2',
        pcu_0: 'VALUE_2',
        bpslot_0: 'VALUE_2',
        amtord_0: 21.0,
        amtval_0: 21.0,
        amtval2_0: 21.0,
        varord_0: 'VALUE_2',
        varval_0: 'VALUE_2',
        varval2_0: 'VALUE_2',
        cstdat_0: new Date().toISOString().split('T')[0],
        csttim_0: new Date().toISOString(),
        priord_0: 21.0,
        upddat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_2',
        credat_0: new Date().toISOString().split('T')[0],
        cremvtdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_2',
        mvtdes_0: 'Désignation mouvement 2',
        prinat_0: 21.0,
        prinat2_0: 21.0,
        act_0: 'VALUE_2',
        actqty_0: 21.0,
        accdat_0: new Date().toISOString().split('T')[0],
        vcrtyp_0: 'VALUE_2',
        mvtind_0: 'VALUE_2',
        pcustucoe_0: 'VALUE_2',
        priregflg_0: 21.0,
        numvcr_0: 'VALUE_2',
        shldat_0: new Date().toISOString().split('T')[0],
        cremvtseq_0: 'VALUE_2',
        entcod_0: 'VALUE_2',
        lbenbr_0: 'VALUE_2',
        trsfam_0: 'VALUE_2',
        cremvttim_0: new Date().toISOString(),
        cretim_0: new Date().toISOString(),
        stofld1_0: 'VALUE_2',
        stofld2_0: 'VALUE_2',
        prival_0: 21.0,
        prival2_0: 21.0,
        pcuori_0: 'VALUE_2',
      },
      {
        owner_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_3',
        amtdev_0: 31.5,
        amtdev2_0: 31.5,
        serfin_0: 'VALUE_3',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        betcpy_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        die_0: 'VALUE_3',
        eccvalmin_0: 'VALUE_3',
        pjt_0: 'VALUE_3',
        lot_0: 'VALUE_3',
        slo_0: 'VALUE_3',
        aggifaflg_0: 'VALUE_3',
        pitvalflg_0: 'VALUE_3',
        pitvalflg2_0: 'VALUE_3',
        serdeb_0: 'VALUE_3',
        pronum_0: 'STO0003',
        vcrnumori_0: 'VALUE_3',
        vcrtypori_0: 'VALUE_3',
        stu_0: 'VALUE_3',
        regflg_0: 'VALUE_3',
        palnum_0: 'VALUE_3',
        vcrtypreg_0: 'VALUE_3',
        stofcy_0: 'VALUE_3',
        cce_0: 'VALUE_3',
        lpnnum_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        updcod_0: 'VALUE_3',
        ctrnum_0: 'VALUE_3',
        iptdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_3',
        sernum_0: 'VALUE_3',
        trstyp_0: 'VALUE_3',
        finrspfcy_0: 'VALUE_3',
        vcrnum_0: 'VALUE_3',
        pcustuori_0: 'VALUE_3',
        vcrlinori_0: 'VALUE_3',
        cstcou_0: 'VALUE_3',
        vcrseqori_0: 'VALUE_3',
        vcrnumreg_0: 'VALUE_3',
        vcrlinreg_0: 'VALUE_3',
        itmref_0: 'VALUE_3',
        xmaccstreg_0: 'VALUE_3',
        xmaccst_0: 'VALUE_3',
        xlabcstreg_0: 'VALUE_3',
        xlabcst_0: 'VALUE_3',
        xscocstreg_0: 'VALUE_3',
        xscocst_0: 'VALUE_3',
        xovematreg_0: 'VALUE_3',
        xovematcst_0: 'VALUE_3',
        xovemacreg_0: 'VALUE_3',
        xovemaccst_0: 'VALUE_3',
        xovelabreg_0: 'VALUE_3',
        xovelabcst_0: 'VALUE_3',
        sta_0: 1,
        xmatcstreg_0: 'VALUE_3',
        xmatcst_0: 'VALUE_3',
        usrfld1_0: 'VALUE_3',
        xovescocst_0: 'VALUE_3',
        xovescoreg_0: 'VALUE_3',
        bprnum_0: 'VALUE_3',
        vcrlin_0: 'VALUE_3',
        usrfld3_0: 'VALUE_3',
        usrfld4_0: 'VALUE_3',
        prnflg_0: 'VALUE_3',
        lbefmt_0: 'VALUE_3',
        qlyctldem_0: 'VALUE_3',
        qtystu_0: 31.5,
        qtypcu_0: 31.5,
        wrh_0: 'VALUE_3',
        loc_0: 'VALUE_3',
        gte_0: 'VALUE_3',
        pot_0: 'VALUE_3',
        mvtseq_0: 'VALUE_3',
        pcu_0: 'VALUE_3',
        bpslot_0: 'VALUE_3',
        amtord_0: 31.5,
        amtval_0: 31.5,
        amtval2_0: 31.5,
        varord_0: 'VALUE_3',
        varval_0: 'VALUE_3',
        varval2_0: 'VALUE_3',
        cstdat_0: new Date().toISOString().split('T')[0],
        csttim_0: new Date().toISOString(),
        priord_0: 31.5,
        upddat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_3',
        credat_0: new Date().toISOString().split('T')[0],
        cremvtdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_3',
        mvtdes_0: 'Désignation mouvement 3',
        prinat_0: 31.5,
        prinat2_0: 31.5,
        act_0: 'VALUE_3',
        actqty_0: 31.5,
        accdat_0: new Date().toISOString().split('T')[0],
        vcrtyp_0: 'VALUE_3',
        mvtind_0: 'VALUE_3',
        pcustucoe_0: 'VALUE_3',
        priregflg_0: 31.5,
        numvcr_0: 'VALUE_3',
        shldat_0: new Date().toISOString().split('T')[0],
        cremvtseq_0: 'VALUE_3',
        entcod_0: 'VALUE_3',
        lbenbr_0: 'VALUE_3',
        trsfam_0: 'VALUE_3',
        cremvttim_0: new Date().toISOString(),
        cretim_0: new Date().toISOString(),
        stofld1_0: 'VALUE_3',
        stofld2_0: 'VALUE_3',
        prival_0: 31.5,
        prival2_0: 31.5,
        pcuori_0: 'VALUE_3',
      },
      {
        owner_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_4',
        amtdev_0: 42.0,
        amtdev2_0: 42.0,
        serfin_0: 'VALUE_4',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        betcpy_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        die_0: 'VALUE_4',
        eccvalmin_0: 'VALUE_4',
        pjt_0: 'VALUE_4',
        lot_0: 'VALUE_4',
        slo_0: 'VALUE_4',
        aggifaflg_0: 'VALUE_4',
        pitvalflg_0: 'VALUE_4',
        pitvalflg2_0: 'VALUE_4',
        serdeb_0: 'VALUE_4',
        pronum_0: 'STO0004',
        vcrnumori_0: 'VALUE_4',
        vcrtypori_0: 'VALUE_4',
        stu_0: 'VALUE_4',
        regflg_0: 'VALUE_4',
        palnum_0: 'VALUE_4',
        vcrtypreg_0: 'VALUE_4',
        stofcy_0: 'VALUE_4',
        cce_0: 'VALUE_4',
        lpnnum_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        updcod_0: 'VALUE_4',
        ctrnum_0: 'VALUE_4',
        iptdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_4',
        sernum_0: 'VALUE_4',
        trstyp_0: 'VALUE_4',
        finrspfcy_0: 'VALUE_4',
        vcrnum_0: 'VALUE_4',
        pcustuori_0: 'VALUE_4',
        vcrlinori_0: 'VALUE_4',
        cstcou_0: 'VALUE_4',
        vcrseqori_0: 'VALUE_4',
        vcrnumreg_0: 'VALUE_4',
        vcrlinreg_0: 'VALUE_4',
        itmref_0: 'VALUE_4',
        xmaccstreg_0: 'VALUE_4',
        xmaccst_0: 'VALUE_4',
        xlabcstreg_0: 'VALUE_4',
        xlabcst_0: 'VALUE_4',
        xscocstreg_0: 'VALUE_4',
        xscocst_0: 'VALUE_4',
        xovematreg_0: 'VALUE_4',
        xovematcst_0: 'VALUE_4',
        xovemacreg_0: 'VALUE_4',
        xovemaccst_0: 'VALUE_4',
        xovelabreg_0: 'VALUE_4',
        xovelabcst_0: 'VALUE_4',
        sta_0: 1,
        xmatcstreg_0: 'VALUE_4',
        xmatcst_0: 'VALUE_4',
        usrfld1_0: 'VALUE_4',
        xovescocst_0: 'VALUE_4',
        xovescoreg_0: 'VALUE_4',
        bprnum_0: 'VALUE_4',
        vcrlin_0: 'VALUE_4',
        usrfld3_0: 'VALUE_4',
        usrfld4_0: 'VALUE_4',
        prnflg_0: 'VALUE_4',
        lbefmt_0: 'VALUE_4',
        qlyctldem_0: 'VALUE_4',
        qtystu_0: 42.0,
        qtypcu_0: 42.0,
        wrh_0: 'VALUE_4',
        loc_0: 'VALUE_4',
        gte_0: 'VALUE_4',
        pot_0: 'VALUE_4',
        mvtseq_0: 'VALUE_4',
        pcu_0: 'VALUE_4',
        bpslot_0: 'VALUE_4',
        amtord_0: 42.0,
        amtval_0: 42.0,
        amtval2_0: 42.0,
        varord_0: 'VALUE_4',
        varval_0: 'VALUE_4',
        varval2_0: 'VALUE_4',
        cstdat_0: new Date().toISOString().split('T')[0],
        csttim_0: new Date().toISOString(),
        priord_0: 42.0,
        upddat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_4',
        credat_0: new Date().toISOString().split('T')[0],
        cremvtdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_4',
        mvtdes_0: 'Désignation mouvement 4',
        prinat_0: 42.0,
        prinat2_0: 42.0,
        act_0: 'VALUE_4',
        actqty_0: 42.0,
        accdat_0: new Date().toISOString().split('T')[0],
        vcrtyp_0: 'VALUE_4',
        mvtind_0: 'VALUE_4',
        pcustucoe_0: 'VALUE_4',
        priregflg_0: 42.0,
        numvcr_0: 'VALUE_4',
        shldat_0: new Date().toISOString().split('T')[0],
        cremvtseq_0: 'VALUE_4',
        entcod_0: 'VALUE_4',
        lbenbr_0: 'VALUE_4',
        trsfam_0: 'VALUE_4',
        cremvttim_0: new Date().toISOString(),
        cretim_0: new Date().toISOString(),
        stofld1_0: 'VALUE_4',
        stofld2_0: 'VALUE_4',
        prival_0: 42.0,
        prival2_0: 42.0,
        pcuori_0: 'VALUE_4',
      },
      {
        owner_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_5',
        amtdev_0: 52.5,
        amtdev2_0: 52.5,
        serfin_0: 'VALUE_5',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        betcpy_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        die_0: 'VALUE_5',
        eccvalmin_0: 'VALUE_5',
        pjt_0: 'VALUE_5',
        lot_0: 'VALUE_5',
        slo_0: 'VALUE_5',
        aggifaflg_0: 'VALUE_5',
        pitvalflg_0: 'VALUE_5',
        pitvalflg2_0: 'VALUE_5',
        serdeb_0: 'VALUE_5',
        pronum_0: 'STO0005',
        vcrnumori_0: 'VALUE_5',
        vcrtypori_0: 'VALUE_5',
        stu_0: 'VALUE_5',
        regflg_0: 'VALUE_5',
        palnum_0: 'VALUE_5',
        vcrtypreg_0: 'VALUE_5',
        stofcy_0: 'VALUE_5',
        cce_0: 'VALUE_5',
        lpnnum_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        updcod_0: 'VALUE_5',
        ctrnum_0: 'VALUE_5',
        iptdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_5',
        sernum_0: 'VALUE_5',
        trstyp_0: 'VALUE_5',
        finrspfcy_0: 'VALUE_5',
        vcrnum_0: 'VALUE_5',
        pcustuori_0: 'VALUE_5',
        vcrlinori_0: 'VALUE_5',
        cstcou_0: 'VALUE_5',
        vcrseqori_0: 'VALUE_5',
        vcrnumreg_0: 'VALUE_5',
        vcrlinreg_0: 'VALUE_5',
        itmref_0: 'VALUE_5',
        xmaccstreg_0: 'VALUE_5',
        xmaccst_0: 'VALUE_5',
        xlabcstreg_0: 'VALUE_5',
        xlabcst_0: 'VALUE_5',
        xscocstreg_0: 'VALUE_5',
        xscocst_0: 'VALUE_5',
        xovematreg_0: 'VALUE_5',
        xovematcst_0: 'VALUE_5',
        xovemacreg_0: 'VALUE_5',
        xovemaccst_0: 'VALUE_5',
        xovelabreg_0: 'VALUE_5',
        xovelabcst_0: 'VALUE_5',
        sta_0: 1,
        xmatcstreg_0: 'VALUE_5',
        xmatcst_0: 'VALUE_5',
        usrfld1_0: 'VALUE_5',
        xovescocst_0: 'VALUE_5',
        xovescoreg_0: 'VALUE_5',
        bprnum_0: 'VALUE_5',
        vcrlin_0: 'VALUE_5',
        usrfld3_0: 'VALUE_5',
        usrfld4_0: 'VALUE_5',
        prnflg_0: 'VALUE_5',
        lbefmt_0: 'VALUE_5',
        qlyctldem_0: 'VALUE_5',
        qtystu_0: 52.5,
        qtypcu_0: 52.5,
        wrh_0: 'VALUE_5',
        loc_0: 'VALUE_5',
        gte_0: 'VALUE_5',
        pot_0: 'VALUE_5',
        mvtseq_0: 'VALUE_5',
        pcu_0: 'VALUE_5',
        bpslot_0: 'VALUE_5',
        amtord_0: 52.5,
        amtval_0: 52.5,
        amtval2_0: 52.5,
        varord_0: 'VALUE_5',
        varval_0: 'VALUE_5',
        varval2_0: 'VALUE_5',
        cstdat_0: new Date().toISOString().split('T')[0],
        csttim_0: new Date().toISOString(),
        priord_0: 52.5,
        upddat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_5',
        credat_0: new Date().toISOString().split('T')[0],
        cremvtdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_5',
        mvtdes_0: 'Désignation mouvement 5',
        prinat_0: 52.5,
        prinat2_0: 52.5,
        act_0: 'VALUE_5',
        actqty_0: 52.5,
        accdat_0: new Date().toISOString().split('T')[0],
        vcrtyp_0: 'VALUE_5',
        mvtind_0: 'VALUE_5',
        pcustucoe_0: 'VALUE_5',
        priregflg_0: 52.5,
        numvcr_0: 'VALUE_5',
        shldat_0: new Date().toISOString().split('T')[0],
        cremvtseq_0: 'VALUE_5',
        entcod_0: 'VALUE_5',
        lbenbr_0: 'VALUE_5',
        trsfam_0: 'VALUE_5',
        cremvttim_0: new Date().toISOString(),
        cretim_0: new Date().toISOString(),
        stofld1_0: 'VALUE_5',
        stofld2_0: 'VALUE_5',
        prival_0: 52.5,
        prival2_0: 52.5,
        pcuori_0: 'VALUE_5',
      },
      {
        owner_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_6',
        amtdev_0: 63.0,
        amtdev2_0: 63.0,
        serfin_0: 'VALUE_6',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        betcpy_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        die_0: 'VALUE_6',
        eccvalmin_0: 'VALUE_6',
        pjt_0: 'VALUE_6',
        lot_0: 'VALUE_6',
        slo_0: 'VALUE_6',
        aggifaflg_0: 'VALUE_6',
        pitvalflg_0: 'VALUE_6',
        pitvalflg2_0: 'VALUE_6',
        serdeb_0: 'VALUE_6',
        pronum_0: 'STO0006',
        vcrnumori_0: 'VALUE_6',
        vcrtypori_0: 'VALUE_6',
        stu_0: 'VALUE_6',
        regflg_0: 'VALUE_6',
        palnum_0: 'VALUE_6',
        vcrtypreg_0: 'VALUE_6',
        stofcy_0: 'VALUE_6',
        cce_0: 'VALUE_6',
        lpnnum_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        updcod_0: 'VALUE_6',
        ctrnum_0: 'VALUE_6',
        iptdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_6',
        sernum_0: 'VALUE_6',
        trstyp_0: 'VALUE_6',
        finrspfcy_0: 'VALUE_6',
        vcrnum_0: 'VALUE_6',
        pcustuori_0: 'VALUE_6',
        vcrlinori_0: 'VALUE_6',
        cstcou_0: 'VALUE_6',
        vcrseqori_0: 'VALUE_6',
        vcrnumreg_0: 'VALUE_6',
        vcrlinreg_0: 'VALUE_6',
        itmref_0: 'VALUE_6',
        xmaccstreg_0: 'VALUE_6',
        xmaccst_0: 'VALUE_6',
        xlabcstreg_0: 'VALUE_6',
        xlabcst_0: 'VALUE_6',
        xscocstreg_0: 'VALUE_6',
        xscocst_0: 'VALUE_6',
        xovematreg_0: 'VALUE_6',
        xovematcst_0: 'VALUE_6',
        xovemacreg_0: 'VALUE_6',
        xovemaccst_0: 'VALUE_6',
        xovelabreg_0: 'VALUE_6',
        xovelabcst_0: 'VALUE_6',
        sta_0: 1,
        xmatcstreg_0: 'VALUE_6',
        xmatcst_0: 'VALUE_6',
        usrfld1_0: 'VALUE_6',
        xovescocst_0: 'VALUE_6',
        xovescoreg_0: 'VALUE_6',
        bprnum_0: 'VALUE_6',
        vcrlin_0: 'VALUE_6',
        usrfld3_0: 'VALUE_6',
        usrfld4_0: 'VALUE_6',
        prnflg_0: 'VALUE_6',
        lbefmt_0: 'VALUE_6',
        qlyctldem_0: 'VALUE_6',
        qtystu_0: 63.0,
        qtypcu_0: 63.0,
        wrh_0: 'VALUE_6',
        loc_0: 'VALUE_6',
        gte_0: 'VALUE_6',
        pot_0: 'VALUE_6',
        mvtseq_0: 'VALUE_6',
        pcu_0: 'VALUE_6',
        bpslot_0: 'VALUE_6',
        amtord_0: 63.0,
        amtval_0: 63.0,
        amtval2_0: 63.0,
        varord_0: 'VALUE_6',
        varval_0: 'VALUE_6',
        varval2_0: 'VALUE_6',
        cstdat_0: new Date().toISOString().split('T')[0],
        csttim_0: new Date().toISOString(),
        priord_0: 63.0,
        upddat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_6',
        credat_0: new Date().toISOString().split('T')[0],
        cremvtdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_6',
        mvtdes_0: 'Désignation mouvement 6',
        prinat_0: 63.0,
        prinat2_0: 63.0,
        act_0: 'VALUE_6',
        actqty_0: 63.0,
        accdat_0: new Date().toISOString().split('T')[0],
        vcrtyp_0: 'VALUE_6',
        mvtind_0: 'VALUE_6',
        pcustucoe_0: 'VALUE_6',
        priregflg_0: 63.0,
        numvcr_0: 'VALUE_6',
        shldat_0: new Date().toISOString().split('T')[0],
        cremvtseq_0: 'VALUE_6',
        entcod_0: 'VALUE_6',
        lbenbr_0: 'VALUE_6',
        trsfam_0: 'VALUE_6',
        cremvttim_0: new Date().toISOString(),
        cretim_0: new Date().toISOString(),
        stofld1_0: 'VALUE_6',
        stofld2_0: 'VALUE_6',
        prival_0: 63.0,
        prival2_0: 63.0,
        pcuori_0: 'VALUE_6',
      },
      {
        owner_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_7',
        amtdev_0: 73.5,
        amtdev2_0: 73.5,
        serfin_0: 'VALUE_7',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        betcpy_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        die_0: 'VALUE_7',
        eccvalmin_0: 'VALUE_7',
        pjt_0: 'VALUE_7',
        lot_0: 'VALUE_7',
        slo_0: 'VALUE_7',
        aggifaflg_0: 'VALUE_7',
        pitvalflg_0: 'VALUE_7',
        pitvalflg2_0: 'VALUE_7',
        serdeb_0: 'VALUE_7',
        pronum_0: 'STO0007',
        vcrnumori_0: 'VALUE_7',
        vcrtypori_0: 'VALUE_7',
        stu_0: 'VALUE_7',
        regflg_0: 'VALUE_7',
        palnum_0: 'VALUE_7',
        vcrtypreg_0: 'VALUE_7',
        stofcy_0: 'VALUE_7',
        cce_0: 'VALUE_7',
        lpnnum_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        updcod_0: 'VALUE_7',
        ctrnum_0: 'VALUE_7',
        iptdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_7',
        sernum_0: 'VALUE_7',
        trstyp_0: 'VALUE_7',
        finrspfcy_0: 'VALUE_7',
        vcrnum_0: 'VALUE_7',
        pcustuori_0: 'VALUE_7',
        vcrlinori_0: 'VALUE_7',
        cstcou_0: 'VALUE_7',
        vcrseqori_0: 'VALUE_7',
        vcrnumreg_0: 'VALUE_7',
        vcrlinreg_0: 'VALUE_7',
        itmref_0: 'VALUE_7',
        xmaccstreg_0: 'VALUE_7',
        xmaccst_0: 'VALUE_7',
        xlabcstreg_0: 'VALUE_7',
        xlabcst_0: 'VALUE_7',
        xscocstreg_0: 'VALUE_7',
        xscocst_0: 'VALUE_7',
        xovematreg_0: 'VALUE_7',
        xovematcst_0: 'VALUE_7',
        xovemacreg_0: 'VALUE_7',
        xovemaccst_0: 'VALUE_7',
        xovelabreg_0: 'VALUE_7',
        xovelabcst_0: 'VALUE_7',
        sta_0: 1,
        xmatcstreg_0: 'VALUE_7',
        xmatcst_0: 'VALUE_7',
        usrfld1_0: 'VALUE_7',
        xovescocst_0: 'VALUE_7',
        xovescoreg_0: 'VALUE_7',
        bprnum_0: 'VALUE_7',
        vcrlin_0: 'VALUE_7',
        usrfld3_0: 'VALUE_7',
        usrfld4_0: 'VALUE_7',
        prnflg_0: 'VALUE_7',
        lbefmt_0: 'VALUE_7',
        qlyctldem_0: 'VALUE_7',
        qtystu_0: 73.5,
        qtypcu_0: 73.5,
        wrh_0: 'VALUE_7',
        loc_0: 'VALUE_7',
        gte_0: 'VALUE_7',
        pot_0: 'VALUE_7',
        mvtseq_0: 'VALUE_7',
        pcu_0: 'VALUE_7',
        bpslot_0: 'VALUE_7',
        amtord_0: 73.5,
        amtval_0: 73.5,
        amtval2_0: 73.5,
        varord_0: 'VALUE_7',
        varval_0: 'VALUE_7',
        varval2_0: 'VALUE_7',
        cstdat_0: new Date().toISOString().split('T')[0],
        csttim_0: new Date().toISOString(),
        priord_0: 73.5,
        upddat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_7',
        credat_0: new Date().toISOString().split('T')[0],
        cremvtdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_7',
        mvtdes_0: 'Désignation mouvement 7',
        prinat_0: 73.5,
        prinat2_0: 73.5,
        act_0: 'VALUE_7',
        actqty_0: 73.5,
        accdat_0: new Date().toISOString().split('T')[0],
        vcrtyp_0: 'VALUE_7',
        mvtind_0: 'VALUE_7',
        pcustucoe_0: 'VALUE_7',
        priregflg_0: 73.5,
        numvcr_0: 'VALUE_7',
        shldat_0: new Date().toISOString().split('T')[0],
        cremvtseq_0: 'VALUE_7',
        entcod_0: 'VALUE_7',
        lbenbr_0: 'VALUE_7',
        trsfam_0: 'VALUE_7',
        cremvttim_0: new Date().toISOString(),
        cretim_0: new Date().toISOString(),
        stofld1_0: 'VALUE_7',
        stofld2_0: 'VALUE_7',
        prival_0: 73.5,
        prival2_0: 73.5,
        pcuori_0: 'VALUE_7',
      },
      {
        owner_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_8',
        amtdev_0: 84.0,
        amtdev2_0: 84.0,
        serfin_0: 'VALUE_8',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        betcpy_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        die_0: 'VALUE_8',
        eccvalmin_0: 'VALUE_8',
        pjt_0: 'VALUE_8',
        lot_0: 'VALUE_8',
        slo_0: 'VALUE_8',
        aggifaflg_0: 'VALUE_8',
        pitvalflg_0: 'VALUE_8',
        pitvalflg2_0: 'VALUE_8',
        serdeb_0: 'VALUE_8',
        pronum_0: 'STO0008',
        vcrnumori_0: 'VALUE_8',
        vcrtypori_0: 'VALUE_8',
        stu_0: 'VALUE_8',
        regflg_0: 'VALUE_8',
        palnum_0: 'VALUE_8',
        vcrtypreg_0: 'VALUE_8',
        stofcy_0: 'VALUE_8',
        cce_0: 'VALUE_8',
        lpnnum_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        updcod_0: 'VALUE_8',
        ctrnum_0: 'VALUE_8',
        iptdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_8',
        sernum_0: 'VALUE_8',
        trstyp_0: 'VALUE_8',
        finrspfcy_0: 'VALUE_8',
        vcrnum_0: 'VALUE_8',
        pcustuori_0: 'VALUE_8',
        vcrlinori_0: 'VALUE_8',
        cstcou_0: 'VALUE_8',
        vcrseqori_0: 'VALUE_8',
        vcrnumreg_0: 'VALUE_8',
        vcrlinreg_0: 'VALUE_8',
        itmref_0: 'VALUE_8',
        xmaccstreg_0: 'VALUE_8',
        xmaccst_0: 'VALUE_8',
        xlabcstreg_0: 'VALUE_8',
        xlabcst_0: 'VALUE_8',
        xscocstreg_0: 'VALUE_8',
        xscocst_0: 'VALUE_8',
        xovematreg_0: 'VALUE_8',
        xovematcst_0: 'VALUE_8',
        xovemacreg_0: 'VALUE_8',
        xovemaccst_0: 'VALUE_8',
        xovelabreg_0: 'VALUE_8',
        xovelabcst_0: 'VALUE_8',
        sta_0: 1,
        xmatcstreg_0: 'VALUE_8',
        xmatcst_0: 'VALUE_8',
        usrfld1_0: 'VALUE_8',
        xovescocst_0: 'VALUE_8',
        xovescoreg_0: 'VALUE_8',
        bprnum_0: 'VALUE_8',
        vcrlin_0: 'VALUE_8',
        usrfld3_0: 'VALUE_8',
        usrfld4_0: 'VALUE_8',
        prnflg_0: 'VALUE_8',
        lbefmt_0: 'VALUE_8',
        qlyctldem_0: 'VALUE_8',
        qtystu_0: 84.0,
        qtypcu_0: 84.0,
        wrh_0: 'VALUE_8',
        loc_0: 'VALUE_8',
        gte_0: 'VALUE_8',
        pot_0: 'VALUE_8',
        mvtseq_0: 'VALUE_8',
        pcu_0: 'VALUE_8',
        bpslot_0: 'VALUE_8',
        amtord_0: 84.0,
        amtval_0: 84.0,
        amtval2_0: 84.0,
        varord_0: 'VALUE_8',
        varval_0: 'VALUE_8',
        varval2_0: 'VALUE_8',
        cstdat_0: new Date().toISOString().split('T')[0],
        csttim_0: new Date().toISOString(),
        priord_0: 84.0,
        upddat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_8',
        credat_0: new Date().toISOString().split('T')[0],
        cremvtdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_8',
        mvtdes_0: 'Désignation mouvement 8',
        prinat_0: 84.0,
        prinat2_0: 84.0,
        act_0: 'VALUE_8',
        actqty_0: 84.0,
        accdat_0: new Date().toISOString().split('T')[0],
        vcrtyp_0: 'VALUE_8',
        mvtind_0: 'VALUE_8',
        pcustucoe_0: 'VALUE_8',
        priregflg_0: 84.0,
        numvcr_0: 'VALUE_8',
        shldat_0: new Date().toISOString().split('T')[0],
        cremvtseq_0: 'VALUE_8',
        entcod_0: 'VALUE_8',
        lbenbr_0: 'VALUE_8',
        trsfam_0: 'VALUE_8',
        cremvttim_0: new Date().toISOString(),
        cretim_0: new Date().toISOString(),
        stofld1_0: 'VALUE_8',
        stofld2_0: 'VALUE_8',
        prival_0: 84.0,
        prival2_0: 84.0,
        pcuori_0: 'VALUE_8',
      },
      {
        owner_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_9',
        amtdev_0: 94.5,
        amtdev2_0: 94.5,
        serfin_0: 'VALUE_9',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        betcpy_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        die_0: 'VALUE_9',
        eccvalmin_0: 'VALUE_9',
        pjt_0: 'VALUE_9',
        lot_0: 'VALUE_9',
        slo_0: 'VALUE_9',
        aggifaflg_0: 'VALUE_9',
        pitvalflg_0: 'VALUE_9',
        pitvalflg2_0: 'VALUE_9',
        serdeb_0: 'VALUE_9',
        pronum_0: 'STO0009',
        vcrnumori_0: 'VALUE_9',
        vcrtypori_0: 'VALUE_9',
        stu_0: 'VALUE_9',
        regflg_0: 'VALUE_9',
        palnum_0: 'VALUE_9',
        vcrtypreg_0: 'VALUE_9',
        stofcy_0: 'VALUE_9',
        cce_0: 'VALUE_9',
        lpnnum_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        updcod_0: 'VALUE_9',
        ctrnum_0: 'VALUE_9',
        iptdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_9',
        sernum_0: 'VALUE_9',
        trstyp_0: 'VALUE_9',
        finrspfcy_0: 'VALUE_9',
        vcrnum_0: 'VALUE_9',
        pcustuori_0: 'VALUE_9',
        vcrlinori_0: 'VALUE_9',
        cstcou_0: 'VALUE_9',
        vcrseqori_0: 'VALUE_9',
        vcrnumreg_0: 'VALUE_9',
        vcrlinreg_0: 'VALUE_9',
        itmref_0: 'VALUE_9',
        xmaccstreg_0: 'VALUE_9',
        xmaccst_0: 'VALUE_9',
        xlabcstreg_0: 'VALUE_9',
        xlabcst_0: 'VALUE_9',
        xscocstreg_0: 'VALUE_9',
        xscocst_0: 'VALUE_9',
        xovematreg_0: 'VALUE_9',
        xovematcst_0: 'VALUE_9',
        xovemacreg_0: 'VALUE_9',
        xovemaccst_0: 'VALUE_9',
        xovelabreg_0: 'VALUE_9',
        xovelabcst_0: 'VALUE_9',
        sta_0: 1,
        xmatcstreg_0: 'VALUE_9',
        xmatcst_0: 'VALUE_9',
        usrfld1_0: 'VALUE_9',
        xovescocst_0: 'VALUE_9',
        xovescoreg_0: 'VALUE_9',
        bprnum_0: 'VALUE_9',
        vcrlin_0: 'VALUE_9',
        usrfld3_0: 'VALUE_9',
        usrfld4_0: 'VALUE_9',
        prnflg_0: 'VALUE_9',
        lbefmt_0: 'VALUE_9',
        qlyctldem_0: 'VALUE_9',
        qtystu_0: 94.5,
        qtypcu_0: 94.5,
        wrh_0: 'VALUE_9',
        loc_0: 'VALUE_9',
        gte_0: 'VALUE_9',
        pot_0: 'VALUE_9',
        mvtseq_0: 'VALUE_9',
        pcu_0: 'VALUE_9',
        bpslot_0: 'VALUE_9',
        amtord_0: 94.5,
        amtval_0: 94.5,
        amtval2_0: 94.5,
        varord_0: 'VALUE_9',
        varval_0: 'VALUE_9',
        varval2_0: 'VALUE_9',
        cstdat_0: new Date().toISOString().split('T')[0],
        csttim_0: new Date().toISOString(),
        priord_0: 94.5,
        upddat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_9',
        credat_0: new Date().toISOString().split('T')[0],
        cremvtdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_9',
        mvtdes_0: 'Désignation mouvement 9',
        prinat_0: 94.5,
        prinat2_0: 94.5,
        act_0: 'VALUE_9',
        actqty_0: 94.5,
        accdat_0: new Date().toISOString().split('T')[0],
        vcrtyp_0: 'VALUE_9',
        mvtind_0: 'VALUE_9',
        pcustucoe_0: 'VALUE_9',
        priregflg_0: 94.5,
        numvcr_0: 'VALUE_9',
        shldat_0: new Date().toISOString().split('T')[0],
        cremvtseq_0: 'VALUE_9',
        entcod_0: 'VALUE_9',
        lbenbr_0: 'VALUE_9',
        trsfam_0: 'VALUE_9',
        cremvttim_0: new Date().toISOString(),
        cretim_0: new Date().toISOString(),
        stofld1_0: 'VALUE_9',
        stofld2_0: 'VALUE_9',
        prival_0: 94.5,
        prival2_0: 94.5,
        pcuori_0: 'VALUE_9',
      },
      {
        owner_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_10',
        amtdev_0: 105.0,
        amtdev2_0: 105.0,
        serfin_0: 'VALUE_10',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        betcpy_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        die_0: 'VALUE_10',
        eccvalmin_0: 'VALUE_10',
        pjt_0: 'VALUE_10',
        lot_0: 'VALUE_10',
        slo_0: 'VALUE_10',
        aggifaflg_0: 'VALUE_10',
        pitvalflg_0: 'VALUE_10',
        pitvalflg2_0: 'VALUE_10',
        serdeb_0: 'VALUE_10',
        pronum_0: 'STO0010',
        vcrnumori_0: 'VALUE_10',
        vcrtypori_0: 'VALUE_10',
        stu_0: 'VALUE_10',
        regflg_0: 'VALUE_10',
        palnum_0: 'VALUE_10',
        vcrtypreg_0: 'VALUE_10',
        stofcy_0: 'VALUE_10',
        cce_0: 'VALUE_10',
        lpnnum_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        updcod_0: 'VALUE_10',
        ctrnum_0: 'VALUE_10',
        iptdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_10',
        sernum_0: 'VALUE_10',
        trstyp_0: 'VALUE_10',
        finrspfcy_0: 'VALUE_10',
        vcrnum_0: 'VALUE_10',
        pcustuori_0: 'VALUE_10',
        vcrlinori_0: 'VALUE_10',
        cstcou_0: 'VALUE_10',
        vcrseqori_0: 'VALUE_10',
        vcrnumreg_0: 'VALUE_10',
        vcrlinreg_0: 'VALUE_10',
        itmref_0: 'VALUE_10',
        xmaccstreg_0: 'VALUE_10',
        xmaccst_0: 'VALUE_10',
        xlabcstreg_0: 'VALUE_10',
        xlabcst_0: 'VALUE_10',
        xscocstreg_0: 'VALUE_10',
        xscocst_0: 'VALUE_10',
        xovematreg_0: 'VALUE_10',
        xovematcst_0: 'VALUE_10',
        xovemacreg_0: 'VALUE_10',
        xovemaccst_0: 'VALUE_10',
        xovelabreg_0: 'VALUE_10',
        xovelabcst_0: 'VALUE_10',
        sta_0: 1,
        xmatcstreg_0: 'VALUE_10',
        xmatcst_0: 'VALUE_10',
        usrfld1_0: 'VALUE_10',
        xovescocst_0: 'VALUE_10',
        xovescoreg_0: 'VALUE_10',
        bprnum_0: 'VALUE_10',
        vcrlin_0: 'VALUE_10',
        usrfld3_0: 'VALUE_10',
        usrfld4_0: 'VALUE_10',
        prnflg_0: 'VALUE_10',
        lbefmt_0: 'VALUE_10',
        qlyctldem_0: 'VALUE_10',
        qtystu_0: 105.0,
        qtypcu_0: 105.0,
        wrh_0: 'VALUE_10',
        loc_0: 'VALUE_10',
        gte_0: 'VALUE_10',
        pot_0: 'VALUE_10',
        mvtseq_0: 'VALUE_10',
        pcu_0: 'VALUE_10',
        bpslot_0: 'VALUE_10',
        amtord_0: 105.0,
        amtval_0: 105.0,
        amtval2_0: 105.0,
        varord_0: 'VALUE_10',
        varval_0: 'VALUE_10',
        varval2_0: 'VALUE_10',
        cstdat_0: new Date().toISOString().split('T')[0],
        csttim_0: new Date().toISOString(),
        priord_0: 105.0,
        upddat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_10',
        credat_0: new Date().toISOString().split('T')[0],
        cremvtdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_10',
        mvtdes_0: 'Désignation mouvement 10',
        prinat_0: 105.0,
        prinat2_0: 105.0,
        act_0: 'VALUE_10',
        actqty_0: 105.0,
        accdat_0: new Date().toISOString().split('T')[0],
        vcrtyp_0: 'VALUE_10',
        mvtind_0: 'VALUE_10',
        pcustucoe_0: 'VALUE_10',
        priregflg_0: 105.0,
        numvcr_0: 'VALUE_10',
        shldat_0: new Date().toISOString().split('T')[0],
        cremvtseq_0: 'VALUE_10',
        entcod_0: 'VALUE_10',
        lbenbr_0: 'VALUE_10',
        trsfam_0: 'VALUE_10',
        cremvttim_0: new Date().toISOString(),
        cretim_0: new Date().toISOString(),
        stofld1_0: 'VALUE_10',
        stofld2_0: 'VALUE_10',
        prival_0: 105.0,
        prival2_0: 105.0,
        pcuori_0: 'VALUE_10',
      },
    ]

    await Database.table('stojou').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans stojou`)
  }
}
