import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour STOLOC
    const data = [
      {
        updusr_0: 'VALUE_1',
        pcustucoe_0: 'VALUE_1',
        ocpcod_0: 'VALUE_1',
        ppsseq_0: 'VALUE_1',
        avadat_0: new Date().toISOString().split('T')[0],
        avahou_0: 'VALUE_1',
        maxqtypcu_0: 10.5,
        allusr_0: 'VALUE_1',
        alldat_0: new Date().toISOString().split('T')[0],
        allhou_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        expnum_0: 'STO0001',
        loc_0: 'VALUE_1',
        loctyp_0: 'VALUE_1',
        stofcy_0: 'VALUE_1',
        qtypcu_0: 10.5,
        wrh_0: 'VALUE_1',
        locnumfmt_0: 'VALUE_1',
        frgmgtmod_0: 'VALUE_1',
        temlti_0: 'VALUE_1',
        wid_0: 'VALUE_1',
        maxauzwei_0: 'VALUE_1',
        loccat_0: 'VALUE_1',
        credat_0: new Date().toISOString().split('T')[0],
        x1loctyp_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1nocbn_0: 'VALUE_1',
        x1claffcod_0: 'VALUE_1',
        x1clrotcod_0: 'VALUE_1',
        x1locallee_0: 'VALUE_1',
        x1locrangee_0: 'VALUE_1',
        x1assignauto_0: 'VALUE_1',
        x1localveole_0: 'VALUE_1',
        filmgtflg_0: 'VALUE_1',
        reaflg_0: 'VALUE_1',
        monitmflg_0: 'VALUE_1',
        dedflg_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        x1locniveau_0: 'VALUE_1',
        loksta_0: 1,
        auzsst_0: 'VALUE_1',
        hei_0: 'VALUE_1',
        dth_0: 'VALUE_1',
        cunlokflg_0: 'VALUE_1',
        pcu_0: 'VALUE_1',
      },
      {
        updusr_0: 'VALUE_2',
        pcustucoe_0: 'VALUE_2',
        ocpcod_0: 'VALUE_2',
        ppsseq_0: 'VALUE_2',
        avadat_0: new Date().toISOString().split('T')[0],
        avahou_0: 'VALUE_2',
        maxqtypcu_0: 21.0,
        allusr_0: 'VALUE_2',
        alldat_0: new Date().toISOString().split('T')[0],
        allhou_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        expnum_0: 'STO0002',
        loc_0: 'VALUE_2',
        loctyp_0: 'VALUE_2',
        stofcy_0: 'VALUE_2',
        qtypcu_0: 21.0,
        wrh_0: 'VALUE_2',
        locnumfmt_0: 'VALUE_2',
        frgmgtmod_0: 'VALUE_2',
        temlti_0: 'VALUE_2',
        wid_0: 'VALUE_2',
        maxauzwei_0: 'VALUE_2',
        loccat_0: 'VALUE_2',
        credat_0: new Date().toISOString().split('T')[0],
        x1loctyp_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1nocbn_0: 'VALUE_2',
        x1claffcod_0: 'VALUE_2',
        x1clrotcod_0: 'VALUE_2',
        x1locallee_0: 'VALUE_2',
        x1locrangee_0: 'VALUE_2',
        x1assignauto_0: 'VALUE_2',
        x1localveole_0: 'VALUE_2',
        filmgtflg_0: 'VALUE_2',
        reaflg_0: 'VALUE_2',
        monitmflg_0: 'VALUE_2',
        dedflg_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        x1locniveau_0: 'VALUE_2',
        loksta_0: 1,
        auzsst_0: 'VALUE_2',
        hei_0: 'VALUE_2',
        dth_0: 'VALUE_2',
        cunlokflg_0: 'VALUE_2',
        pcu_0: 'VALUE_2',
      },
      {
        updusr_0: 'VALUE_3',
        pcustucoe_0: 'VALUE_3',
        ocpcod_0: 'VALUE_3',
        ppsseq_0: 'VALUE_3',
        avadat_0: new Date().toISOString().split('T')[0],
        avahou_0: 'VALUE_3',
        maxqtypcu_0: 31.5,
        allusr_0: 'VALUE_3',
        alldat_0: new Date().toISOString().split('T')[0],
        allhou_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        expnum_0: 'STO0003',
        loc_0: 'VALUE_3',
        loctyp_0: 'VALUE_3',
        stofcy_0: 'VALUE_3',
        qtypcu_0: 31.5,
        wrh_0: 'VALUE_3',
        locnumfmt_0: 'VALUE_3',
        frgmgtmod_0: 'VALUE_3',
        temlti_0: 'VALUE_3',
        wid_0: 'VALUE_3',
        maxauzwei_0: 'VALUE_3',
        loccat_0: 'VALUE_3',
        credat_0: new Date().toISOString().split('T')[0],
        x1loctyp_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1nocbn_0: 'VALUE_3',
        x1claffcod_0: 'VALUE_3',
        x1clrotcod_0: 'VALUE_3',
        x1locallee_0: 'VALUE_3',
        x1locrangee_0: 'VALUE_3',
        x1assignauto_0: 'VALUE_3',
        x1localveole_0: 'VALUE_3',
        filmgtflg_0: 'VALUE_3',
        reaflg_0: 'VALUE_3',
        monitmflg_0: 'VALUE_3',
        dedflg_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        x1locniveau_0: 'VALUE_3',
        loksta_0: 1,
        auzsst_0: 'VALUE_3',
        hei_0: 'VALUE_3',
        dth_0: 'VALUE_3',
        cunlokflg_0: 'VALUE_3',
        pcu_0: 'VALUE_3',
      },
      {
        updusr_0: 'VALUE_4',
        pcustucoe_0: 'VALUE_4',
        ocpcod_0: 'VALUE_4',
        ppsseq_0: 'VALUE_4',
        avadat_0: new Date().toISOString().split('T')[0],
        avahou_0: 'VALUE_4',
        maxqtypcu_0: 42.0,
        allusr_0: 'VALUE_4',
        alldat_0: new Date().toISOString().split('T')[0],
        allhou_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        expnum_0: 'STO0004',
        loc_0: 'VALUE_4',
        loctyp_0: 'VALUE_4',
        stofcy_0: 'VALUE_4',
        qtypcu_0: 42.0,
        wrh_0: 'VALUE_4',
        locnumfmt_0: 'VALUE_4',
        frgmgtmod_0: 'VALUE_4',
        temlti_0: 'VALUE_4',
        wid_0: 'VALUE_4',
        maxauzwei_0: 'VALUE_4',
        loccat_0: 'VALUE_4',
        credat_0: new Date().toISOString().split('T')[0],
        x1loctyp_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1nocbn_0: 'VALUE_4',
        x1claffcod_0: 'VALUE_4',
        x1clrotcod_0: 'VALUE_4',
        x1locallee_0: 'VALUE_4',
        x1locrangee_0: 'VALUE_4',
        x1assignauto_0: 'VALUE_4',
        x1localveole_0: 'VALUE_4',
        filmgtflg_0: 'VALUE_4',
        reaflg_0: 'VALUE_4',
        monitmflg_0: 'VALUE_4',
        dedflg_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        x1locniveau_0: 'VALUE_4',
        loksta_0: 1,
        auzsst_0: 'VALUE_4',
        hei_0: 'VALUE_4',
        dth_0: 'VALUE_4',
        cunlokflg_0: 'VALUE_4',
        pcu_0: 'VALUE_4',
      },
      {
        updusr_0: 'VALUE_5',
        pcustucoe_0: 'VALUE_5',
        ocpcod_0: 'VALUE_5',
        ppsseq_0: 'VALUE_5',
        avadat_0: new Date().toISOString().split('T')[0],
        avahou_0: 'VALUE_5',
        maxqtypcu_0: 52.5,
        allusr_0: 'VALUE_5',
        alldat_0: new Date().toISOString().split('T')[0],
        allhou_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        expnum_0: 'STO0005',
        loc_0: 'VALUE_5',
        loctyp_0: 'VALUE_5',
        stofcy_0: 'VALUE_5',
        qtypcu_0: 52.5,
        wrh_0: 'VALUE_5',
        locnumfmt_0: 'VALUE_5',
        frgmgtmod_0: 'VALUE_5',
        temlti_0: 'VALUE_5',
        wid_0: 'VALUE_5',
        maxauzwei_0: 'VALUE_5',
        loccat_0: 'VALUE_5',
        credat_0: new Date().toISOString().split('T')[0],
        x1loctyp_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1nocbn_0: 'VALUE_5',
        x1claffcod_0: 'VALUE_5',
        x1clrotcod_0: 'VALUE_5',
        x1locallee_0: 'VALUE_5',
        x1locrangee_0: 'VALUE_5',
        x1assignauto_0: 'VALUE_5',
        x1localveole_0: 'VALUE_5',
        filmgtflg_0: 'VALUE_5',
        reaflg_0: 'VALUE_5',
        monitmflg_0: 'VALUE_5',
        dedflg_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        x1locniveau_0: 'VALUE_5',
        loksta_0: 1,
        auzsst_0: 'VALUE_5',
        hei_0: 'VALUE_5',
        dth_0: 'VALUE_5',
        cunlokflg_0: 'VALUE_5',
        pcu_0: 'VALUE_5',
      },
      {
        updusr_0: 'VALUE_6',
        pcustucoe_0: 'VALUE_6',
        ocpcod_0: 'VALUE_6',
        ppsseq_0: 'VALUE_6',
        avadat_0: new Date().toISOString().split('T')[0],
        avahou_0: 'VALUE_6',
        maxqtypcu_0: 63.0,
        allusr_0: 'VALUE_6',
        alldat_0: new Date().toISOString().split('T')[0],
        allhou_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        expnum_0: 'STO0006',
        loc_0: 'VALUE_6',
        loctyp_0: 'VALUE_6',
        stofcy_0: 'VALUE_6',
        qtypcu_0: 63.0,
        wrh_0: 'VALUE_6',
        locnumfmt_0: 'VALUE_6',
        frgmgtmod_0: 'VALUE_6',
        temlti_0: 'VALUE_6',
        wid_0: 'VALUE_6',
        maxauzwei_0: 'VALUE_6',
        loccat_0: 'VALUE_6',
        credat_0: new Date().toISOString().split('T')[0],
        x1loctyp_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1nocbn_0: 'VALUE_6',
        x1claffcod_0: 'VALUE_6',
        x1clrotcod_0: 'VALUE_6',
        x1locallee_0: 'VALUE_6',
        x1locrangee_0: 'VALUE_6',
        x1assignauto_0: 'VALUE_6',
        x1localveole_0: 'VALUE_6',
        filmgtflg_0: 'VALUE_6',
        reaflg_0: 'VALUE_6',
        monitmflg_0: 'VALUE_6',
        dedflg_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        x1locniveau_0: 'VALUE_6',
        loksta_0: 1,
        auzsst_0: 'VALUE_6',
        hei_0: 'VALUE_6',
        dth_0: 'VALUE_6',
        cunlokflg_0: 'VALUE_6',
        pcu_0: 'VALUE_6',
      },
      {
        updusr_0: 'VALUE_7',
        pcustucoe_0: 'VALUE_7',
        ocpcod_0: 'VALUE_7',
        ppsseq_0: 'VALUE_7',
        avadat_0: new Date().toISOString().split('T')[0],
        avahou_0: 'VALUE_7',
        maxqtypcu_0: 73.5,
        allusr_0: 'VALUE_7',
        alldat_0: new Date().toISOString().split('T')[0],
        allhou_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        expnum_0: 'STO0007',
        loc_0: 'VALUE_7',
        loctyp_0: 'VALUE_7',
        stofcy_0: 'VALUE_7',
        qtypcu_0: 73.5,
        wrh_0: 'VALUE_7',
        locnumfmt_0: 'VALUE_7',
        frgmgtmod_0: 'VALUE_7',
        temlti_0: 'VALUE_7',
        wid_0: 'VALUE_7',
        maxauzwei_0: 'VALUE_7',
        loccat_0: 'VALUE_7',
        credat_0: new Date().toISOString().split('T')[0],
        x1loctyp_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1nocbn_0: 'VALUE_7',
        x1claffcod_0: 'VALUE_7',
        x1clrotcod_0: 'VALUE_7',
        x1locallee_0: 'VALUE_7',
        x1locrangee_0: 'VALUE_7',
        x1assignauto_0: 'VALUE_7',
        x1localveole_0: 'VALUE_7',
        filmgtflg_0: 'VALUE_7',
        reaflg_0: 'VALUE_7',
        monitmflg_0: 'VALUE_7',
        dedflg_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        x1locniveau_0: 'VALUE_7',
        loksta_0: 1,
        auzsst_0: 'VALUE_7',
        hei_0: 'VALUE_7',
        dth_0: 'VALUE_7',
        cunlokflg_0: 'VALUE_7',
        pcu_0: 'VALUE_7',
      },
      {
        updusr_0: 'VALUE_8',
        pcustucoe_0: 'VALUE_8',
        ocpcod_0: 'VALUE_8',
        ppsseq_0: 'VALUE_8',
        avadat_0: new Date().toISOString().split('T')[0],
        avahou_0: 'VALUE_8',
        maxqtypcu_0: 84.0,
        allusr_0: 'VALUE_8',
        alldat_0: new Date().toISOString().split('T')[0],
        allhou_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        expnum_0: 'STO0008',
        loc_0: 'VALUE_8',
        loctyp_0: 'VALUE_8',
        stofcy_0: 'VALUE_8',
        qtypcu_0: 84.0,
        wrh_0: 'VALUE_8',
        locnumfmt_0: 'VALUE_8',
        frgmgtmod_0: 'VALUE_8',
        temlti_0: 'VALUE_8',
        wid_0: 'VALUE_8',
        maxauzwei_0: 'VALUE_8',
        loccat_0: 'VALUE_8',
        credat_0: new Date().toISOString().split('T')[0],
        x1loctyp_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1nocbn_0: 'VALUE_8',
        x1claffcod_0: 'VALUE_8',
        x1clrotcod_0: 'VALUE_8',
        x1locallee_0: 'VALUE_8',
        x1locrangee_0: 'VALUE_8',
        x1assignauto_0: 'VALUE_8',
        x1localveole_0: 'VALUE_8',
        filmgtflg_0: 'VALUE_8',
        reaflg_0: 'VALUE_8',
        monitmflg_0: 'VALUE_8',
        dedflg_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        x1locniveau_0: 'VALUE_8',
        loksta_0: 1,
        auzsst_0: 'VALUE_8',
        hei_0: 'VALUE_8',
        dth_0: 'VALUE_8',
        cunlokflg_0: 'VALUE_8',
        pcu_0: 'VALUE_8',
      },
      {
        updusr_0: 'VALUE_9',
        pcustucoe_0: 'VALUE_9',
        ocpcod_0: 'VALUE_9',
        ppsseq_0: 'VALUE_9',
        avadat_0: new Date().toISOString().split('T')[0],
        avahou_0: 'VALUE_9',
        maxqtypcu_0: 94.5,
        allusr_0: 'VALUE_9',
        alldat_0: new Date().toISOString().split('T')[0],
        allhou_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        expnum_0: 'STO0009',
        loc_0: 'VALUE_9',
        loctyp_0: 'VALUE_9',
        stofcy_0: 'VALUE_9',
        qtypcu_0: 94.5,
        wrh_0: 'VALUE_9',
        locnumfmt_0: 'VALUE_9',
        frgmgtmod_0: 'VALUE_9',
        temlti_0: 'VALUE_9',
        wid_0: 'VALUE_9',
        maxauzwei_0: 'VALUE_9',
        loccat_0: 'VALUE_9',
        credat_0: new Date().toISOString().split('T')[0],
        x1loctyp_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1nocbn_0: 'VALUE_9',
        x1claffcod_0: 'VALUE_9',
        x1clrotcod_0: 'VALUE_9',
        x1locallee_0: 'VALUE_9',
        x1locrangee_0: 'VALUE_9',
        x1assignauto_0: 'VALUE_9',
        x1localveole_0: 'VALUE_9',
        filmgtflg_0: 'VALUE_9',
        reaflg_0: 'VALUE_9',
        monitmflg_0: 'VALUE_9',
        dedflg_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        x1locniveau_0: 'VALUE_9',
        loksta_0: 1,
        auzsst_0: 'VALUE_9',
        hei_0: 'VALUE_9',
        dth_0: 'VALUE_9',
        cunlokflg_0: 'VALUE_9',
        pcu_0: 'VALUE_9',
      },
      {
        updusr_0: 'VALUE_10',
        pcustucoe_0: 'VALUE_10',
        ocpcod_0: 'VALUE_10',
        ppsseq_0: 'VALUE_10',
        avadat_0: new Date().toISOString().split('T')[0],
        avahou_0: 'VALUE_10',
        maxqtypcu_0: 105.0,
        allusr_0: 'VALUE_10',
        alldat_0: new Date().toISOString().split('T')[0],
        allhou_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        expnum_0: 'STO0010',
        loc_0: 'VALUE_10',
        loctyp_0: 'VALUE_10',
        stofcy_0: 'VALUE_10',
        qtypcu_0: 105.0,
        wrh_0: 'VALUE_10',
        locnumfmt_0: 'VALUE_10',
        frgmgtmod_0: 'VALUE_10',
        temlti_0: 'VALUE_10',
        wid_0: 'VALUE_10',
        maxauzwei_0: 'VALUE_10',
        loccat_0: 'VALUE_10',
        credat_0: new Date().toISOString().split('T')[0],
        x1loctyp_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1nocbn_0: 'VALUE_10',
        x1claffcod_0: 'VALUE_10',
        x1clrotcod_0: 'VALUE_10',
        x1locallee_0: 'VALUE_10',
        x1locrangee_0: 'VALUE_10',
        x1assignauto_0: 'VALUE_10',
        x1localveole_0: 'VALUE_10',
        filmgtflg_0: 'VALUE_10',
        reaflg_0: 'VALUE_10',
        monitmflg_0: 'VALUE_10',
        dedflg_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        x1locniveau_0: 'VALUE_10',
        loksta_0: 1,
        auzsst_0: 'VALUE_10',
        hei_0: 'VALUE_10',
        dth_0: 'VALUE_10',
        cunlokflg_0: 'VALUE_10',
        pcu_0: 'VALUE_10',
      },
    ]

    await Database.table('stoloc').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans stoloc`)
  }
}
