import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour STOLOT
    const data = [
      {
        updusr_0: 'VALUE_1',
        act_0: 'VALUE_1',
        vcrtyp_0: 'VALUE_1',
        shldat_0: new Date().toISOString().split('T')[0],
        lotcredat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_1',
        expnum_0: 'STO0001',
        vcrnum_0: 'VALUE_1',
        usrfld1_0: 'VALUE_1',
        vcrlin_0: 'VALUE_1',
        usrfld4_0: 'VALUE_1',
        shl_0: 'VALUE_1',
        pot_0: 'VALUE_1',
        bpslot_0: 'VALUE_1',
        itmref_0: 'VALUE_1',
        shllti_0: 'VALUE_1',
        x1opendat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_1',
        usrfld3_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_1',
        dlu_0: 'VALUE_1',
        shluom_0: 'VALUE_1',
        shlltiuom_0: 'VALUE_1',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        ltidat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_1',
        eccvalmin_0: 'VALUE_1',
        lot_0: 'VALUE_1',
        slo_0: 'VALUE_1',
        refper_0: 'VALUE_1',
        bpsnum_0: 'VALUE_1',
      },
      {
        updusr_0: 'VALUE_2',
        act_0: 'VALUE_2',
        vcrtyp_0: 'VALUE_2',
        shldat_0: new Date().toISOString().split('T')[0],
        lotcredat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_2',
        expnum_0: 'STO0002',
        vcrnum_0: 'VALUE_2',
        usrfld1_0: 'VALUE_2',
        vcrlin_0: 'VALUE_2',
        usrfld4_0: 'VALUE_2',
        shl_0: 'VALUE_2',
        pot_0: 'VALUE_2',
        bpslot_0: 'VALUE_2',
        itmref_0: 'VALUE_2',
        shllti_0: 'VALUE_2',
        x1opendat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_2',
        usrfld3_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_2',
        dlu_0: 'VALUE_2',
        shluom_0: 'VALUE_2',
        shlltiuom_0: 'VALUE_2',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        ltidat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_2',
        eccvalmin_0: 'VALUE_2',
        lot_0: 'VALUE_2',
        slo_0: 'VALUE_2',
        refper_0: 'VALUE_2',
        bpsnum_0: 'VALUE_2',
      },
      {
        updusr_0: 'VALUE_3',
        act_0: 'VALUE_3',
        vcrtyp_0: 'VALUE_3',
        shldat_0: new Date().toISOString().split('T')[0],
        lotcredat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_3',
        expnum_0: 'STO0003',
        vcrnum_0: 'VALUE_3',
        usrfld1_0: 'VALUE_3',
        vcrlin_0: 'VALUE_3',
        usrfld4_0: 'VALUE_3',
        shl_0: 'VALUE_3',
        pot_0: 'VALUE_3',
        bpslot_0: 'VALUE_3',
        itmref_0: 'VALUE_3',
        shllti_0: 'VALUE_3',
        x1opendat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_3',
        usrfld3_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_3',
        dlu_0: 'VALUE_3',
        shluom_0: 'VALUE_3',
        shlltiuom_0: 'VALUE_3',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        ltidat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_3',
        eccvalmin_0: 'VALUE_3',
        lot_0: 'VALUE_3',
        slo_0: 'VALUE_3',
        refper_0: 'VALUE_3',
        bpsnum_0: 'VALUE_3',
      },
      {
        updusr_0: 'VALUE_4',
        act_0: 'VALUE_4',
        vcrtyp_0: 'VALUE_4',
        shldat_0: new Date().toISOString().split('T')[0],
        lotcredat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_4',
        expnum_0: 'STO0004',
        vcrnum_0: 'VALUE_4',
        usrfld1_0: 'VALUE_4',
        vcrlin_0: 'VALUE_4',
        usrfld4_0: 'VALUE_4',
        shl_0: 'VALUE_4',
        pot_0: 'VALUE_4',
        bpslot_0: 'VALUE_4',
        itmref_0: 'VALUE_4',
        shllti_0: 'VALUE_4',
        x1opendat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_4',
        usrfld3_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_4',
        dlu_0: 'VALUE_4',
        shluom_0: 'VALUE_4',
        shlltiuom_0: 'VALUE_4',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        ltidat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_4',
        eccvalmin_0: 'VALUE_4',
        lot_0: 'VALUE_4',
        slo_0: 'VALUE_4',
        refper_0: 'VALUE_4',
        bpsnum_0: 'VALUE_4',
      },
      {
        updusr_0: 'VALUE_5',
        act_0: 'VALUE_5',
        vcrtyp_0: 'VALUE_5',
        shldat_0: new Date().toISOString().split('T')[0],
        lotcredat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_5',
        expnum_0: 'STO0005',
        vcrnum_0: 'VALUE_5',
        usrfld1_0: 'VALUE_5',
        vcrlin_0: 'VALUE_5',
        usrfld4_0: 'VALUE_5',
        shl_0: 'VALUE_5',
        pot_0: 'VALUE_5',
        bpslot_0: 'VALUE_5',
        itmref_0: 'VALUE_5',
        shllti_0: 'VALUE_5',
        x1opendat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_5',
        usrfld3_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_5',
        dlu_0: 'VALUE_5',
        shluom_0: 'VALUE_5',
        shlltiuom_0: 'VALUE_5',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        ltidat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_5',
        eccvalmin_0: 'VALUE_5',
        lot_0: 'VALUE_5',
        slo_0: 'VALUE_5',
        refper_0: 'VALUE_5',
        bpsnum_0: 'VALUE_5',
      },
      {
        updusr_0: 'VALUE_6',
        act_0: 'VALUE_6',
        vcrtyp_0: 'VALUE_6',
        shldat_0: new Date().toISOString().split('T')[0],
        lotcredat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_6',
        expnum_0: 'STO0006',
        vcrnum_0: 'VALUE_6',
        usrfld1_0: 'VALUE_6',
        vcrlin_0: 'VALUE_6',
        usrfld4_0: 'VALUE_6',
        shl_0: 'VALUE_6',
        pot_0: 'VALUE_6',
        bpslot_0: 'VALUE_6',
        itmref_0: 'VALUE_6',
        shllti_0: 'VALUE_6',
        x1opendat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_6',
        usrfld3_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_6',
        dlu_0: 'VALUE_6',
        shluom_0: 'VALUE_6',
        shlltiuom_0: 'VALUE_6',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        ltidat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_6',
        eccvalmin_0: 'VALUE_6',
        lot_0: 'VALUE_6',
        slo_0: 'VALUE_6',
        refper_0: 'VALUE_6',
        bpsnum_0: 'VALUE_6',
      },
      {
        updusr_0: 'VALUE_7',
        act_0: 'VALUE_7',
        vcrtyp_0: 'VALUE_7',
        shldat_0: new Date().toISOString().split('T')[0],
        lotcredat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_7',
        expnum_0: 'STO0007',
        vcrnum_0: 'VALUE_7',
        usrfld1_0: 'VALUE_7',
        vcrlin_0: 'VALUE_7',
        usrfld4_0: 'VALUE_7',
        shl_0: 'VALUE_7',
        pot_0: 'VALUE_7',
        bpslot_0: 'VALUE_7',
        itmref_0: 'VALUE_7',
        shllti_0: 'VALUE_7',
        x1opendat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_7',
        usrfld3_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_7',
        dlu_0: 'VALUE_7',
        shluom_0: 'VALUE_7',
        shlltiuom_0: 'VALUE_7',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        ltidat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_7',
        eccvalmin_0: 'VALUE_7',
        lot_0: 'VALUE_7',
        slo_0: 'VALUE_7',
        refper_0: 'VALUE_7',
        bpsnum_0: 'VALUE_7',
      },
      {
        updusr_0: 'VALUE_8',
        act_0: 'VALUE_8',
        vcrtyp_0: 'VALUE_8',
        shldat_0: new Date().toISOString().split('T')[0],
        lotcredat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_8',
        expnum_0: 'STO0008',
        vcrnum_0: 'VALUE_8',
        usrfld1_0: 'VALUE_8',
        vcrlin_0: 'VALUE_8',
        usrfld4_0: 'VALUE_8',
        shl_0: 'VALUE_8',
        pot_0: 'VALUE_8',
        bpslot_0: 'VALUE_8',
        itmref_0: 'VALUE_8',
        shllti_0: 'VALUE_8',
        x1opendat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_8',
        usrfld3_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_8',
        dlu_0: 'VALUE_8',
        shluom_0: 'VALUE_8',
        shlltiuom_0: 'VALUE_8',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        ltidat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_8',
        eccvalmin_0: 'VALUE_8',
        lot_0: 'VALUE_8',
        slo_0: 'VALUE_8',
        refper_0: 'VALUE_8',
        bpsnum_0: 'VALUE_8',
      },
      {
        updusr_0: 'VALUE_9',
        act_0: 'VALUE_9',
        vcrtyp_0: 'VALUE_9',
        shldat_0: new Date().toISOString().split('T')[0],
        lotcredat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_9',
        expnum_0: 'STO0009',
        vcrnum_0: 'VALUE_9',
        usrfld1_0: 'VALUE_9',
        vcrlin_0: 'VALUE_9',
        usrfld4_0: 'VALUE_9',
        shl_0: 'VALUE_9',
        pot_0: 'VALUE_9',
        bpslot_0: 'VALUE_9',
        itmref_0: 'VALUE_9',
        shllti_0: 'VALUE_9',
        x1opendat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_9',
        usrfld3_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_9',
        dlu_0: 'VALUE_9',
        shluom_0: 'VALUE_9',
        shlltiuom_0: 'VALUE_9',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        ltidat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_9',
        eccvalmin_0: 'VALUE_9',
        lot_0: 'VALUE_9',
        slo_0: 'VALUE_9',
        refper_0: 'VALUE_9',
        bpsnum_0: 'VALUE_9',
      },
      {
        updusr_0: 'VALUE_10',
        act_0: 'VALUE_10',
        vcrtyp_0: 'VALUE_10',
        shldat_0: new Date().toISOString().split('T')[0],
        lotcredat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_10',
        expnum_0: 'STO0010',
        vcrnum_0: 'VALUE_10',
        usrfld1_0: 'VALUE_10',
        vcrlin_0: 'VALUE_10',
        usrfld4_0: 'VALUE_10',
        shl_0: 'VALUE_10',
        pot_0: 'VALUE_10',
        bpslot_0: 'VALUE_10',
        itmref_0: 'VALUE_10',
        shllti_0: 'VALUE_10',
        x1opendat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        usrfld2_0: 'VALUE_10',
        usrfld3_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_10',
        dlu_0: 'VALUE_10',
        shluom_0: 'VALUE_10',
        shlltiuom_0: 'VALUE_10',
        newltidat_0: new Date().toISOString().split('T')[0],
        dludat_0: new Date().toISOString().split('T')[0],
        ltidat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_10',
        eccvalmin_0: 'VALUE_10',
        lot_0: 'VALUE_10',
        slo_0: 'VALUE_10',
        refper_0: 'VALUE_10',
        bpsnum_0: 'VALUE_10',
      },
    ]

    await Database.table('stolot').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans stolot`)
  }
}
