import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour SORDER
    const data = [
      {
        hldsta_0: 1,
        hldcod_0: 'VALUE_1',
        hldcodp_0: 'VALUE_1',
        hlddat_0: new Date().toISOString().split('T')[0],
        hlddatp_0: new Date().toISOString().split('T')[0],
        hldtim_0: new Date().toISOString(),
        hldtimp_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpapyr_0: 'VALUE_1',
        ordnotl_0: 'VALUE_1',
        ordatil_0: new Date().toISOString().split('T')[0],
        ordinvnotl_0: 'VALUE_1',
        ordinvatil_0: 'VALUE_1',
        sinum_0: 'SOR0001',
        dsptotwei_0: 'VALUE_1',
        dsptotvol_0: 'VALUE_1',
        invsta_0: 1,
        dlvsta_0: 1,
        betcpy_0: 'VALUE_1',
        cndnam_0: 'Contact livraison 1',
        bpiposcod_0: 'VALUE_1',
        bpicry_0: 'VALUE_1',
        bpicrynam_0: 'VALUE_1',
        ocnprn_0: 'VALUE_1',
        sqhnum_0: 'VALUE_1',
        pfmtot_0: 'VALUE_1',
        unl_0: 'VALUE_1',
        betfcy_0: 'VALUE_1',
        pjt_0: 'VALUE_1',
        sfisstcod_0: 'VALUE_1',
        cdtstap_0: 1,
        x4avmotcom_0: 'VALUE_1',
        invcnd_0: 'VALUE_1',
        sstentcod_0: 'VALUE_1',
        bpaord_0: 'VALUE_1',
        bpainv_0: 'VALUE_1',
        draftstatus_0: 1,
        demdlvhou_0: 'VALUE_1',
        sohvaldat_0: new Date().toISOString().split('T')[0],
        zdatok_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_1',
        sohcfmflg_0: 'VALUE_1',
        inrati_0: 'VALUE_1',
        inrnot_0: 'VALUE_1',
        inrschati_0: 'VALUE_1',
        inrschnot_0: 'VALUE_1',
        sohnumend_0: 'VALUE_1',
        die_0: 'VALUE_1',
        zbyedi_0: 'VALUE_1',
        zflgedi_0: 'VALUE_1',
        zsuedi_0: 'VALUE_1',
        zctaedi_0: 'VALUE_1',
        zcodlivedi_0: 'VALUE_1',
        zcdeclifin_0: 'VALUE_1',
        zn1clifin_0: 'VALUE_1',
        zn2clifin_0: 'VALUE_1',
        zlieuexp_0: 'VALUE_1',
        x4sohenvaut_0: 'VALUE_1',
        x4avmot_0: 'VALUE_1',
        x4debctlcon_0: 'VALUE_1',
        x4forrel_0: 'VALUE_1',
        x4trtrel_0: 'VALUE_1',
        xcolsouple_0: 'VALUE_1',
        x4exclrfa_0: 'VALUE_1',
        x1typprepa_0: 'VALUE_1',
        x4rgop_0: 'VALUE_1',
        x1precodman_0: 'VALUE_1',
        draftrej_0: 'VALUE_1',
        draftrejren_0: 'VALUE_1',
        x1typprepman_0: 'VALUE_1',
        x4regrel_0: 'VALUE_1',
        hldusr_0: 'VALUE_1',
        hldusrp_0: 'VALUE_1',
        cur_0: 'VALUE_1',
        lasdlvnum_0: 'VALUE_1',
        lasdlvdat_0: new Date().toISOString().split('T')[0],
        lasinvnum_0: 'VALUE_1',
        dlrnot_0: 'VALUE_1',
        dspvou_0: 'VALUE_1',
        prfnum_0: 'VALUE_1',
        shiadecod_0: 'VALUE_1',
        salfcy_0: 'VALUE_1',
        bpcpyr_0: 'VALUE_1',
        xnbedt_0: 'VALUE_1',
        opgnum_0: 'VALUE_1',
        opgtyp_0: 'VALUE_1',
        bpcnam_0: 'VALUE_1',
        bpcaddlig_0: 'VALUE_1',
        bpcposcod_0: 'VALUE_1',
        bpccty_0: 'VALUE_1',
        bpccry_0: 'VALUE_1',
        bpccrynam_0: 'VALUE_1',
        copnbr_0: 'VALUE_1',
        eecloc_0: 'VALUE_1',
        clelinnbr_0: 'VALUE_1',
        bpcsat_0: 'VALUE_1',
        ordsta_0: 1,
        bpdsat_0: 'VALUE_1',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        daylti_0: 'VALUE_1',
        bpinam_0: 'VALUE_1',
        bpiaddlig_0: 'VALUE_1',
        bpicty_0: 'VALUE_1',
        bpdposcod_0: 'VALUE_1',
        bpdcty_0: 'VALUE_1',
        bpdcry_0: 'VALUE_1',
        sohcat_0: 'VALUE_1',
        bpcord_0: 'VALUE_1',
        ffwnum_0: 'VALUE_1',
        cusordref_0: 'VALUE_1',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        vlydatcon_0: new Date().toISOString().split('T')[0],
        alltyp_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        lan_0: 'VALUE_1',
        allsta_0: 1,
        adrval_0: 'VALUE_1',
        mdl_0: 'VALUE_1',
        drn_0: 'VALUE_1',
        dlvpio_0: 'VALUE_1',
        ime_0: 'VALUE_1',
        bpaadd_0: 'VALUE_1',
        bpdaddlig_0: 'VALUE_1',
        ordinvnot_0: 'VALUE_1',
        ordnot_0: 'VALUE_1',
        ordati_0: new Date().toISOString().split('T')[0],
        sohtex1_0: 'VALUE_1',
        ocnflg_0: 'VALUE_1',
        dme_0: 'VALUE_1',
        alllinnbr_0: 'VALUE_1',
        dlvlinnbr_0: 'VALUE_1',
        orifcy_0: 'VALUE_1',
        geocod_0: 'VALUE_1',
        insctyflg_0: 'VALUE_1',
        ffwadd_0: 'VALUE_1',
        ordinvati_0: 'VALUE_1',
        ictcty_0: 'VALUE_1',
        x4sohexp_0: 'VALUE_1',
        bpcinv_0: 'VALUE_1',
        bpcgru_0: 'VALUE_1',
        dep_0: 'VALUE_1',
        sohtyp_0: 'VALUE_1',
        revnum_0: 'VALUE_1',
        orddat_0: new Date().toISOString().split('T')[0],
        appflg_0: 'VALUE_1',
        linnbr_0: 'VALUE_1',
        dsptotqty_0: 10.5,
        bpieecnum_0: 'VALUE_1',
        invdtadsp_0: 'VALUE_1',
        eecict_0: 'VALUE_1',
        cntnam_0: 'VALUE_1',
        invlinnbr_0: 'VALUE_1',
        credat_0: new Date().toISOString().split('T')[0],
        cclren_0: 'VALUE_1',
        ccldat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_1',
        srenum_0: 'VALUE_1',
        vcrinvcnddat_0: new Date().toISOString().split('T')[0],
        xcmqint_0: 'VALUE_1',
        xmodgfi_0: 'VALUE_1',
        x4numint_0: 'VALUE_1',
        cninam_0: 'VALUE_1',
        cmgnum_0: 'VALUE_1',
        vtt_0: 'VALUE_1',
        sohtex2_0: 'VALUE_1',
        tsccod_0: 'VALUE_1',
        prityp_0: 10.5,
        invdtalin_0: 'VALUE_1',
        amttax_0: 10.5,
        bastax_0: 1,
        invdtaamt_0: 10.5,
        ordcle_0: 'VALUE_1',
        odl_0: 'VALUE_1',
        sohnum_0: 'VALUE_1',
        sdhtyp_0: 'VALUE_1',
        shidat_0: new Date().toISOString().split('T')[0],
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_1',
        bpdcrynam_0: 'VALUE_1',
        chgtyp_0: 'VALUE_1',
        invdtatyp_0: 'VALUE_1',
        rep_0: 'VALUE_1',
        chgrat_0: 'VALUE_1',
        plistc_0: 'VALUE_1',
        cce_0: 'VALUE_1',
        cpy_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        dlrati_0: 'VALUE_1',
        updusr_0: 'VALUE_1',
        bpisat_0: 'VALUE_1',
        cdtsta_0: 1,
        bptnum_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        discrgtyp_0: 'VALUE_1',
        z01statut_0: 1,
        x4sohdest_0: 'VALUE_1',
        invdta_0: 'VALUE_1',
        vacbpr_0: 'VALUE_1',
        stofcy_0: 'VALUE_1',
        dspweu_0: 'VALUE_1',
        pte_0: 'VALUE_1',
      },
      {
        hldsta_0: 1,
        hldcod_0: 'VALUE_2',
        hldcodp_0: 'VALUE_2',
        hlddat_0: new Date().toISOString().split('T')[0],
        hlddatp_0: new Date().toISOString().split('T')[0],
        hldtim_0: new Date().toISOString(),
        hldtimp_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpapyr_0: 'VALUE_2',
        ordnotl_0: 'VALUE_2',
        ordatil_0: new Date().toISOString().split('T')[0],
        ordinvnotl_0: 'VALUE_2',
        ordinvatil_0: 'VALUE_2',
        sinum_0: 'SOR0002',
        dsptotwei_0: 'VALUE_2',
        dsptotvol_0: 'VALUE_2',
        invsta_0: 2,
        dlvsta_0: 2,
        betcpy_0: 'VALUE_2',
        cndnam_0: 'Contact livraison 2',
        bpiposcod_0: 'VALUE_2',
        bpicry_0: 'VALUE_2',
        bpicrynam_0: 'VALUE_2',
        ocnprn_0: 'VALUE_2',
        sqhnum_0: 'VALUE_2',
        pfmtot_0: 'VALUE_2',
        unl_0: 'VALUE_2',
        betfcy_0: 'VALUE_2',
        pjt_0: 'VALUE_2',
        sfisstcod_0: 'VALUE_2',
        cdtstap_0: 2,
        x4avmotcom_0: 'VALUE_2',
        invcnd_0: 'VALUE_2',
        sstentcod_0: 'VALUE_2',
        bpaord_0: 'VALUE_2',
        bpainv_0: 'VALUE_2',
        draftstatus_0: 2,
        demdlvhou_0: 'VALUE_2',
        sohvaldat_0: new Date().toISOString().split('T')[0],
        zdatok_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_2',
        sohcfmflg_0: 'VALUE_2',
        inrati_0: 'VALUE_2',
        inrnot_0: 'VALUE_2',
        inrschati_0: 'VALUE_2',
        inrschnot_0: 'VALUE_2',
        sohnumend_0: 'VALUE_2',
        die_0: 'VALUE_2',
        zbyedi_0: 'VALUE_2',
        zflgedi_0: 'VALUE_2',
        zsuedi_0: 'VALUE_2',
        zctaedi_0: 'VALUE_2',
        zcodlivedi_0: 'VALUE_2',
        zcdeclifin_0: 'VALUE_2',
        zn1clifin_0: 'VALUE_2',
        zn2clifin_0: 'VALUE_2',
        zlieuexp_0: 'VALUE_2',
        x4sohenvaut_0: 'VALUE_2',
        x4avmot_0: 'VALUE_2',
        x4debctlcon_0: 'VALUE_2',
        x4forrel_0: 'VALUE_2',
        x4trtrel_0: 'VALUE_2',
        xcolsouple_0: 'VALUE_2',
        x4exclrfa_0: 'VALUE_2',
        x1typprepa_0: 'VALUE_2',
        x4rgop_0: 'VALUE_2',
        x1precodman_0: 'VALUE_2',
        draftrej_0: 'VALUE_2',
        draftrejren_0: 'VALUE_2',
        x1typprepman_0: 'VALUE_2',
        x4regrel_0: 'VALUE_2',
        hldusr_0: 'VALUE_2',
        hldusrp_0: 'VALUE_2',
        cur_0: 'VALUE_2',
        lasdlvnum_0: 'VALUE_2',
        lasdlvdat_0: new Date().toISOString().split('T')[0],
        lasinvnum_0: 'VALUE_2',
        dlrnot_0: 'VALUE_2',
        dspvou_0: 'VALUE_2',
        prfnum_0: 'VALUE_2',
        shiadecod_0: 'VALUE_2',
        salfcy_0: 'VALUE_2',
        bpcpyr_0: 'VALUE_2',
        xnbedt_0: 'VALUE_2',
        opgnum_0: 'VALUE_2',
        opgtyp_0: 'VALUE_2',
        bpcnam_0: 'VALUE_2',
        bpcaddlig_0: 'VALUE_2',
        bpcposcod_0: 'VALUE_2',
        bpccty_0: 'VALUE_2',
        bpccry_0: 'VALUE_2',
        bpccrynam_0: 'VALUE_2',
        copnbr_0: 'VALUE_2',
        eecloc_0: 'VALUE_2',
        clelinnbr_0: 'VALUE_2',
        bpcsat_0: 'VALUE_2',
        ordsta_0: 2,
        bpdsat_0: 'VALUE_2',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        daylti_0: 'VALUE_2',
        bpinam_0: 'VALUE_2',
        bpiaddlig_0: 'VALUE_2',
        bpicty_0: 'VALUE_2',
        bpdposcod_0: 'VALUE_2',
        bpdcty_0: 'VALUE_2',
        bpdcry_0: 'VALUE_2',
        sohcat_0: 'VALUE_2',
        bpcord_0: 'VALUE_2',
        ffwnum_0: 'VALUE_2',
        cusordref_0: 'VALUE_2',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        vlydatcon_0: new Date().toISOString().split('T')[0],
        alltyp_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        lan_0: 'VALUE_2',
        allsta_0: 2,
        adrval_0: 'VALUE_2',
        mdl_0: 'VALUE_2',
        drn_0: 'VALUE_2',
        dlvpio_0: 'VALUE_2',
        ime_0: 'VALUE_2',
        bpaadd_0: 'VALUE_2',
        bpdaddlig_0: 'VALUE_2',
        ordinvnot_0: 'VALUE_2',
        ordnot_0: 'VALUE_2',
        ordati_0: new Date().toISOString().split('T')[0],
        sohtex1_0: 'VALUE_2',
        ocnflg_0: 'VALUE_2',
        dme_0: 'VALUE_2',
        alllinnbr_0: 'VALUE_2',
        dlvlinnbr_0: 'VALUE_2',
        orifcy_0: 'VALUE_2',
        geocod_0: 'VALUE_2',
        insctyflg_0: 'VALUE_2',
        ffwadd_0: 'VALUE_2',
        ordinvati_0: 'VALUE_2',
        ictcty_0: 'VALUE_2',
        x4sohexp_0: 'VALUE_2',
        bpcinv_0: 'VALUE_2',
        bpcgru_0: 'VALUE_2',
        dep_0: 'VALUE_2',
        sohtyp_0: 'VALUE_2',
        revnum_0: 'VALUE_2',
        orddat_0: new Date().toISOString().split('T')[0],
        appflg_0: 'VALUE_2',
        linnbr_0: 'VALUE_2',
        dsptotqty_0: 21.0,
        bpieecnum_0: 'VALUE_2',
        invdtadsp_0: 'VALUE_2',
        eecict_0: 'VALUE_2',
        cntnam_0: 'VALUE_2',
        invlinnbr_0: 'VALUE_2',
        credat_0: new Date().toISOString().split('T')[0],
        cclren_0: 'VALUE_2',
        ccldat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_2',
        srenum_0: 'VALUE_2',
        vcrinvcnddat_0: new Date().toISOString().split('T')[0],
        xcmqint_0: 'VALUE_2',
        xmodgfi_0: 'VALUE_2',
        x4numint_0: 'VALUE_2',
        cninam_0: 'VALUE_2',
        cmgnum_0: 'VALUE_2',
        vtt_0: 'VALUE_2',
        sohtex2_0: 'VALUE_2',
        tsccod_0: 'VALUE_2',
        prityp_0: 21.0,
        invdtalin_0: 'VALUE_2',
        amttax_0: 21.0,
        bastax_0: 2,
        invdtaamt_0: 21.0,
        ordcle_0: 'VALUE_2',
        odl_0: 'VALUE_2',
        sohnum_0: 'VALUE_2',
        sdhtyp_0: 'VALUE_2',
        shidat_0: new Date().toISOString().split('T')[0],
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_2',
        bpdcrynam_0: 'VALUE_2',
        chgtyp_0: 'VALUE_2',
        invdtatyp_0: 'VALUE_2',
        rep_0: 'VALUE_2',
        chgrat_0: 'VALUE_2',
        plistc_0: 'VALUE_2',
        cce_0: 'VALUE_2',
        cpy_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        dlrati_0: 'VALUE_2',
        updusr_0: 'VALUE_2',
        bpisat_0: 'VALUE_2',
        cdtsta_0: 2,
        bptnum_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        discrgtyp_0: 'VALUE_2',
        z01statut_0: 2,
        x4sohdest_0: 'VALUE_2',
        invdta_0: 'VALUE_2',
        vacbpr_0: 'VALUE_2',
        stofcy_0: 'VALUE_2',
        dspweu_0: 'VALUE_2',
        pte_0: 'VALUE_2',
      },
      {
        hldsta_0: 1,
        hldcod_0: 'VALUE_3',
        hldcodp_0: 'VALUE_3',
        hlddat_0: new Date().toISOString().split('T')[0],
        hlddatp_0: new Date().toISOString().split('T')[0],
        hldtim_0: new Date().toISOString(),
        hldtimp_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpapyr_0: 'VALUE_3',
        ordnotl_0: 'VALUE_3',
        ordatil_0: new Date().toISOString().split('T')[0],
        ordinvnotl_0: 'VALUE_3',
        ordinvatil_0: 'VALUE_3',
        sinum_0: 'SOR0003',
        dsptotwei_0: 'VALUE_3',
        dsptotvol_0: 'VALUE_3',
        invsta_0: 3,
        dlvsta_0: 3,
        betcpy_0: 'VALUE_3',
        cndnam_0: 'Contact livraison 3',
        bpiposcod_0: 'VALUE_3',
        bpicry_0: 'VALUE_3',
        bpicrynam_0: 'VALUE_3',
        ocnprn_0: 'VALUE_3',
        sqhnum_0: 'VALUE_3',
        pfmtot_0: 'VALUE_3',
        unl_0: 'VALUE_3',
        betfcy_0: 'VALUE_3',
        pjt_0: 'VALUE_3',
        sfisstcod_0: 'VALUE_3',
        cdtstap_0: 3,
        x4avmotcom_0: 'VALUE_3',
        invcnd_0: 'VALUE_3',
        sstentcod_0: 'VALUE_3',
        bpaord_0: 'VALUE_3',
        bpainv_0: 'VALUE_3',
        draftstatus_0: 3,
        demdlvhou_0: 'VALUE_3',
        sohvaldat_0: new Date().toISOString().split('T')[0],
        zdatok_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_3',
        sohcfmflg_0: 'VALUE_3',
        inrati_0: 'VALUE_3',
        inrnot_0: 'VALUE_3',
        inrschati_0: 'VALUE_3',
        inrschnot_0: 'VALUE_3',
        sohnumend_0: 'VALUE_3',
        die_0: 'VALUE_3',
        zbyedi_0: 'VALUE_3',
        zflgedi_0: 'VALUE_3',
        zsuedi_0: 'VALUE_3',
        zctaedi_0: 'VALUE_3',
        zcodlivedi_0: 'VALUE_3',
        zcdeclifin_0: 'VALUE_3',
        zn1clifin_0: 'VALUE_3',
        zn2clifin_0: 'VALUE_3',
        zlieuexp_0: 'VALUE_3',
        x4sohenvaut_0: 'VALUE_3',
        x4avmot_0: 'VALUE_3',
        x4debctlcon_0: 'VALUE_3',
        x4forrel_0: 'VALUE_3',
        x4trtrel_0: 'VALUE_3',
        xcolsouple_0: 'VALUE_3',
        x4exclrfa_0: 'VALUE_3',
        x1typprepa_0: 'VALUE_3',
        x4rgop_0: 'VALUE_3',
        x1precodman_0: 'VALUE_3',
        draftrej_0: 'VALUE_3',
        draftrejren_0: 'VALUE_3',
        x1typprepman_0: 'VALUE_3',
        x4regrel_0: 'VALUE_3',
        hldusr_0: 'VALUE_3',
        hldusrp_0: 'VALUE_3',
        cur_0: 'VALUE_3',
        lasdlvnum_0: 'VALUE_3',
        lasdlvdat_0: new Date().toISOString().split('T')[0],
        lasinvnum_0: 'VALUE_3',
        dlrnot_0: 'VALUE_3',
        dspvou_0: 'VALUE_3',
        prfnum_0: 'VALUE_3',
        shiadecod_0: 'VALUE_3',
        salfcy_0: 'VALUE_3',
        bpcpyr_0: 'VALUE_3',
        xnbedt_0: 'VALUE_3',
        opgnum_0: 'VALUE_3',
        opgtyp_0: 'VALUE_3',
        bpcnam_0: 'VALUE_3',
        bpcaddlig_0: 'VALUE_3',
        bpcposcod_0: 'VALUE_3',
        bpccty_0: 'VALUE_3',
        bpccry_0: 'VALUE_3',
        bpccrynam_0: 'VALUE_3',
        copnbr_0: 'VALUE_3',
        eecloc_0: 'VALUE_3',
        clelinnbr_0: 'VALUE_3',
        bpcsat_0: 'VALUE_3',
        ordsta_0: 3,
        bpdsat_0: 'VALUE_3',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        daylti_0: 'VALUE_3',
        bpinam_0: 'VALUE_3',
        bpiaddlig_0: 'VALUE_3',
        bpicty_0: 'VALUE_3',
        bpdposcod_0: 'VALUE_3',
        bpdcty_0: 'VALUE_3',
        bpdcry_0: 'VALUE_3',
        sohcat_0: 'VALUE_3',
        bpcord_0: 'VALUE_3',
        ffwnum_0: 'VALUE_3',
        cusordref_0: 'VALUE_3',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        vlydatcon_0: new Date().toISOString().split('T')[0],
        alltyp_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        lan_0: 'VALUE_3',
        allsta_0: 3,
        adrval_0: 'VALUE_3',
        mdl_0: 'VALUE_3',
        drn_0: 'VALUE_3',
        dlvpio_0: 'VALUE_3',
        ime_0: 'VALUE_3',
        bpaadd_0: 'VALUE_3',
        bpdaddlig_0: 'VALUE_3',
        ordinvnot_0: 'VALUE_3',
        ordnot_0: 'VALUE_3',
        ordati_0: new Date().toISOString().split('T')[0],
        sohtex1_0: 'VALUE_3',
        ocnflg_0: 'VALUE_3',
        dme_0: 'VALUE_3',
        alllinnbr_0: 'VALUE_3',
        dlvlinnbr_0: 'VALUE_3',
        orifcy_0: 'VALUE_3',
        geocod_0: 'VALUE_3',
        insctyflg_0: 'VALUE_3',
        ffwadd_0: 'VALUE_3',
        ordinvati_0: 'VALUE_3',
        ictcty_0: 'VALUE_3',
        x4sohexp_0: 'VALUE_3',
        bpcinv_0: 'VALUE_3',
        bpcgru_0: 'VALUE_3',
        dep_0: 'VALUE_3',
        sohtyp_0: 'VALUE_3',
        revnum_0: 'VALUE_3',
        orddat_0: new Date().toISOString().split('T')[0],
        appflg_0: 'VALUE_3',
        linnbr_0: 'VALUE_3',
        dsptotqty_0: 31.5,
        bpieecnum_0: 'VALUE_3',
        invdtadsp_0: 'VALUE_3',
        eecict_0: 'VALUE_3',
        cntnam_0: 'VALUE_3',
        invlinnbr_0: 'VALUE_3',
        credat_0: new Date().toISOString().split('T')[0],
        cclren_0: 'VALUE_3',
        ccldat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_3',
        srenum_0: 'VALUE_3',
        vcrinvcnddat_0: new Date().toISOString().split('T')[0],
        xcmqint_0: 'VALUE_3',
        xmodgfi_0: 'VALUE_3',
        x4numint_0: 'VALUE_3',
        cninam_0: 'VALUE_3',
        cmgnum_0: 'VALUE_3',
        vtt_0: 'VALUE_3',
        sohtex2_0: 'VALUE_3',
        tsccod_0: 'VALUE_3',
        prityp_0: 31.5,
        invdtalin_0: 'VALUE_3',
        amttax_0: 31.5,
        bastax_0: 3,
        invdtaamt_0: 31.5,
        ordcle_0: 'VALUE_3',
        odl_0: 'VALUE_3',
        sohnum_0: 'VALUE_3',
        sdhtyp_0: 'VALUE_3',
        shidat_0: new Date().toISOString().split('T')[0],
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_3',
        bpdcrynam_0: 'VALUE_3',
        chgtyp_0: 'VALUE_3',
        invdtatyp_0: 'VALUE_3',
        rep_0: 'VALUE_3',
        chgrat_0: 'VALUE_3',
        plistc_0: 'VALUE_3',
        cce_0: 'VALUE_3',
        cpy_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        dlrati_0: 'VALUE_3',
        updusr_0: 'VALUE_3',
        bpisat_0: 'VALUE_3',
        cdtsta_0: 3,
        bptnum_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        discrgtyp_0: 'VALUE_3',
        z01statut_0: 3,
        x4sohdest_0: 'VALUE_3',
        invdta_0: 'VALUE_3',
        vacbpr_0: 'VALUE_3',
        stofcy_0: 'VALUE_3',
        dspweu_0: 'VALUE_3',
        pte_0: 'VALUE_3',
      },
      {
        hldsta_0: 1,
        hldcod_0: 'VALUE_4',
        hldcodp_0: 'VALUE_4',
        hlddat_0: new Date().toISOString().split('T')[0],
        hlddatp_0: new Date().toISOString().split('T')[0],
        hldtim_0: new Date().toISOString(),
        hldtimp_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpapyr_0: 'VALUE_4',
        ordnotl_0: 'VALUE_4',
        ordatil_0: new Date().toISOString().split('T')[0],
        ordinvnotl_0: 'VALUE_4',
        ordinvatil_0: 'VALUE_4',
        sinum_0: 'SOR0004',
        dsptotwei_0: 'VALUE_4',
        dsptotvol_0: 'VALUE_4',
        invsta_0: 4,
        dlvsta_0: 4,
        betcpy_0: 'VALUE_4',
        cndnam_0: 'Contact livraison 4',
        bpiposcod_0: 'VALUE_4',
        bpicry_0: 'VALUE_4',
        bpicrynam_0: 'VALUE_4',
        ocnprn_0: 'VALUE_4',
        sqhnum_0: 'VALUE_4',
        pfmtot_0: 'VALUE_4',
        unl_0: 'VALUE_4',
        betfcy_0: 'VALUE_4',
        pjt_0: 'VALUE_4',
        sfisstcod_0: 'VALUE_4',
        cdtstap_0: 4,
        x4avmotcom_0: 'VALUE_4',
        invcnd_0: 'VALUE_4',
        sstentcod_0: 'VALUE_4',
        bpaord_0: 'VALUE_4',
        bpainv_0: 'VALUE_4',
        draftstatus_0: 4,
        demdlvhou_0: 'VALUE_4',
        sohvaldat_0: new Date().toISOString().split('T')[0],
        zdatok_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_4',
        sohcfmflg_0: 'VALUE_4',
        inrati_0: 'VALUE_4',
        inrnot_0: 'VALUE_4',
        inrschati_0: 'VALUE_4',
        inrschnot_0: 'VALUE_4',
        sohnumend_0: 'VALUE_4',
        die_0: 'VALUE_4',
        zbyedi_0: 'VALUE_4',
        zflgedi_0: 'VALUE_4',
        zsuedi_0: 'VALUE_4',
        zctaedi_0: 'VALUE_4',
        zcodlivedi_0: 'VALUE_4',
        zcdeclifin_0: 'VALUE_4',
        zn1clifin_0: 'VALUE_4',
        zn2clifin_0: 'VALUE_4',
        zlieuexp_0: 'VALUE_4',
        x4sohenvaut_0: 'VALUE_4',
        x4avmot_0: 'VALUE_4',
        x4debctlcon_0: 'VALUE_4',
        x4forrel_0: 'VALUE_4',
        x4trtrel_0: 'VALUE_4',
        xcolsouple_0: 'VALUE_4',
        x4exclrfa_0: 'VALUE_4',
        x1typprepa_0: 'VALUE_4',
        x4rgop_0: 'VALUE_4',
        x1precodman_0: 'VALUE_4',
        draftrej_0: 'VALUE_4',
        draftrejren_0: 'VALUE_4',
        x1typprepman_0: 'VALUE_4',
        x4regrel_0: 'VALUE_4',
        hldusr_0: 'VALUE_4',
        hldusrp_0: 'VALUE_4',
        cur_0: 'VALUE_4',
        lasdlvnum_0: 'VALUE_4',
        lasdlvdat_0: new Date().toISOString().split('T')[0],
        lasinvnum_0: 'VALUE_4',
        dlrnot_0: 'VALUE_4',
        dspvou_0: 'VALUE_4',
        prfnum_0: 'VALUE_4',
        shiadecod_0: 'VALUE_4',
        salfcy_0: 'VALUE_4',
        bpcpyr_0: 'VALUE_4',
        xnbedt_0: 'VALUE_4',
        opgnum_0: 'VALUE_4',
        opgtyp_0: 'VALUE_4',
        bpcnam_0: 'VALUE_4',
        bpcaddlig_0: 'VALUE_4',
        bpcposcod_0: 'VALUE_4',
        bpccty_0: 'VALUE_4',
        bpccry_0: 'VALUE_4',
        bpccrynam_0: 'VALUE_4',
        copnbr_0: 'VALUE_4',
        eecloc_0: 'VALUE_4',
        clelinnbr_0: 'VALUE_4',
        bpcsat_0: 'VALUE_4',
        ordsta_0: 4,
        bpdsat_0: 'VALUE_4',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        daylti_0: 'VALUE_4',
        bpinam_0: 'VALUE_4',
        bpiaddlig_0: 'VALUE_4',
        bpicty_0: 'VALUE_4',
        bpdposcod_0: 'VALUE_4',
        bpdcty_0: 'VALUE_4',
        bpdcry_0: 'VALUE_4',
        sohcat_0: 'VALUE_4',
        bpcord_0: 'VALUE_4',
        ffwnum_0: 'VALUE_4',
        cusordref_0: 'VALUE_4',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        vlydatcon_0: new Date().toISOString().split('T')[0],
        alltyp_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        lan_0: 'VALUE_4',
        allsta_0: 4,
        adrval_0: 'VALUE_4',
        mdl_0: 'VALUE_4',
        drn_0: 'VALUE_4',
        dlvpio_0: 'VALUE_4',
        ime_0: 'VALUE_4',
        bpaadd_0: 'VALUE_4',
        bpdaddlig_0: 'VALUE_4',
        ordinvnot_0: 'VALUE_4',
        ordnot_0: 'VALUE_4',
        ordati_0: new Date().toISOString().split('T')[0],
        sohtex1_0: 'VALUE_4',
        ocnflg_0: 'VALUE_4',
        dme_0: 'VALUE_4',
        alllinnbr_0: 'VALUE_4',
        dlvlinnbr_0: 'VALUE_4',
        orifcy_0: 'VALUE_4',
        geocod_0: 'VALUE_4',
        insctyflg_0: 'VALUE_4',
        ffwadd_0: 'VALUE_4',
        ordinvati_0: 'VALUE_4',
        ictcty_0: 'VALUE_4',
        x4sohexp_0: 'VALUE_4',
        bpcinv_0: 'VALUE_4',
        bpcgru_0: 'VALUE_4',
        dep_0: 'VALUE_4',
        sohtyp_0: 'VALUE_4',
        revnum_0: 'VALUE_4',
        orddat_0: new Date().toISOString().split('T')[0],
        appflg_0: 'VALUE_4',
        linnbr_0: 'VALUE_4',
        dsptotqty_0: 42.0,
        bpieecnum_0: 'VALUE_4',
        invdtadsp_0: 'VALUE_4',
        eecict_0: 'VALUE_4',
        cntnam_0: 'VALUE_4',
        invlinnbr_0: 'VALUE_4',
        credat_0: new Date().toISOString().split('T')[0],
        cclren_0: 'VALUE_4',
        ccldat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_4',
        srenum_0: 'VALUE_4',
        vcrinvcnddat_0: new Date().toISOString().split('T')[0],
        xcmqint_0: 'VALUE_4',
        xmodgfi_0: 'VALUE_4',
        x4numint_0: 'VALUE_4',
        cninam_0: 'VALUE_4',
        cmgnum_0: 'VALUE_4',
        vtt_0: 'VALUE_4',
        sohtex2_0: 'VALUE_4',
        tsccod_0: 'VALUE_4',
        prityp_0: 42.0,
        invdtalin_0: 'VALUE_4',
        amttax_0: 42.0,
        bastax_0: 4,
        invdtaamt_0: 42.0,
        ordcle_0: 'VALUE_4',
        odl_0: 'VALUE_4',
        sohnum_0: 'VALUE_4',
        sdhtyp_0: 'VALUE_4',
        shidat_0: new Date().toISOString().split('T')[0],
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_4',
        bpdcrynam_0: 'VALUE_4',
        chgtyp_0: 'VALUE_4',
        invdtatyp_0: 'VALUE_4',
        rep_0: 'VALUE_4',
        chgrat_0: 'VALUE_4',
        plistc_0: 'VALUE_4',
        cce_0: 'VALUE_4',
        cpy_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        dlrati_0: 'VALUE_4',
        updusr_0: 'VALUE_4',
        bpisat_0: 'VALUE_4',
        cdtsta_0: 4,
        bptnum_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        discrgtyp_0: 'VALUE_4',
        z01statut_0: 4,
        x4sohdest_0: 'VALUE_4',
        invdta_0: 'VALUE_4',
        vacbpr_0: 'VALUE_4',
        stofcy_0: 'VALUE_4',
        dspweu_0: 'VALUE_4',
        pte_0: 'VALUE_4',
      },
      {
        hldsta_0: 1,
        hldcod_0: 'VALUE_5',
        hldcodp_0: 'VALUE_5',
        hlddat_0: new Date().toISOString().split('T')[0],
        hlddatp_0: new Date().toISOString().split('T')[0],
        hldtim_0: new Date().toISOString(),
        hldtimp_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpapyr_0: 'VALUE_5',
        ordnotl_0: 'VALUE_5',
        ordatil_0: new Date().toISOString().split('T')[0],
        ordinvnotl_0: 'VALUE_5',
        ordinvatil_0: 'VALUE_5',
        sinum_0: 'SOR0005',
        dsptotwei_0: 'VALUE_5',
        dsptotvol_0: 'VALUE_5',
        invsta_0: 5,
        dlvsta_0: 5,
        betcpy_0: 'VALUE_5',
        cndnam_0: 'Contact livraison 5',
        bpiposcod_0: 'VALUE_5',
        bpicry_0: 'VALUE_5',
        bpicrynam_0: 'VALUE_5',
        ocnprn_0: 'VALUE_5',
        sqhnum_0: 'VALUE_5',
        pfmtot_0: 'VALUE_5',
        unl_0: 'VALUE_5',
        betfcy_0: 'VALUE_5',
        pjt_0: 'VALUE_5',
        sfisstcod_0: 'VALUE_5',
        cdtstap_0: 5,
        x4avmotcom_0: 'VALUE_5',
        invcnd_0: 'VALUE_5',
        sstentcod_0: 'VALUE_5',
        bpaord_0: 'VALUE_5',
        bpainv_0: 'VALUE_5',
        draftstatus_0: 5,
        demdlvhou_0: 'VALUE_5',
        sohvaldat_0: new Date().toISOString().split('T')[0],
        zdatok_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_5',
        sohcfmflg_0: 'VALUE_5',
        inrati_0: 'VALUE_5',
        inrnot_0: 'VALUE_5',
        inrschati_0: 'VALUE_5',
        inrschnot_0: 'VALUE_5',
        sohnumend_0: 'VALUE_5',
        die_0: 'VALUE_5',
        zbyedi_0: 'VALUE_5',
        zflgedi_0: 'VALUE_5',
        zsuedi_0: 'VALUE_5',
        zctaedi_0: 'VALUE_5',
        zcodlivedi_0: 'VALUE_5',
        zcdeclifin_0: 'VALUE_5',
        zn1clifin_0: 'VALUE_5',
        zn2clifin_0: 'VALUE_5',
        zlieuexp_0: 'VALUE_5',
        x4sohenvaut_0: 'VALUE_5',
        x4avmot_0: 'VALUE_5',
        x4debctlcon_0: 'VALUE_5',
        x4forrel_0: 'VALUE_5',
        x4trtrel_0: 'VALUE_5',
        xcolsouple_0: 'VALUE_5',
        x4exclrfa_0: 'VALUE_5',
        x1typprepa_0: 'VALUE_5',
        x4rgop_0: 'VALUE_5',
        x1precodman_0: 'VALUE_5',
        draftrej_0: 'VALUE_5',
        draftrejren_0: 'VALUE_5',
        x1typprepman_0: 'VALUE_5',
        x4regrel_0: 'VALUE_5',
        hldusr_0: 'VALUE_5',
        hldusrp_0: 'VALUE_5',
        cur_0: 'VALUE_5',
        lasdlvnum_0: 'VALUE_5',
        lasdlvdat_0: new Date().toISOString().split('T')[0],
        lasinvnum_0: 'VALUE_5',
        dlrnot_0: 'VALUE_5',
        dspvou_0: 'VALUE_5',
        prfnum_0: 'VALUE_5',
        shiadecod_0: 'VALUE_5',
        salfcy_0: 'VALUE_5',
        bpcpyr_0: 'VALUE_5',
        xnbedt_0: 'VALUE_5',
        opgnum_0: 'VALUE_5',
        opgtyp_0: 'VALUE_5',
        bpcnam_0: 'VALUE_5',
        bpcaddlig_0: 'VALUE_5',
        bpcposcod_0: 'VALUE_5',
        bpccty_0: 'VALUE_5',
        bpccry_0: 'VALUE_5',
        bpccrynam_0: 'VALUE_5',
        copnbr_0: 'VALUE_5',
        eecloc_0: 'VALUE_5',
        clelinnbr_0: 'VALUE_5',
        bpcsat_0: 'VALUE_5',
        ordsta_0: 5,
        bpdsat_0: 'VALUE_5',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        daylti_0: 'VALUE_5',
        bpinam_0: 'VALUE_5',
        bpiaddlig_0: 'VALUE_5',
        bpicty_0: 'VALUE_5',
        bpdposcod_0: 'VALUE_5',
        bpdcty_0: 'VALUE_5',
        bpdcry_0: 'VALUE_5',
        sohcat_0: 'VALUE_5',
        bpcord_0: 'VALUE_5',
        ffwnum_0: 'VALUE_5',
        cusordref_0: 'VALUE_5',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        vlydatcon_0: new Date().toISOString().split('T')[0],
        alltyp_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        lan_0: 'VALUE_5',
        allsta_0: 5,
        adrval_0: 'VALUE_5',
        mdl_0: 'VALUE_5',
        drn_0: 'VALUE_5',
        dlvpio_0: 'VALUE_5',
        ime_0: 'VALUE_5',
        bpaadd_0: 'VALUE_5',
        bpdaddlig_0: 'VALUE_5',
        ordinvnot_0: 'VALUE_5',
        ordnot_0: 'VALUE_5',
        ordati_0: new Date().toISOString().split('T')[0],
        sohtex1_0: 'VALUE_5',
        ocnflg_0: 'VALUE_5',
        dme_0: 'VALUE_5',
        alllinnbr_0: 'VALUE_5',
        dlvlinnbr_0: 'VALUE_5',
        orifcy_0: 'VALUE_5',
        geocod_0: 'VALUE_5',
        insctyflg_0: 'VALUE_5',
        ffwadd_0: 'VALUE_5',
        ordinvati_0: 'VALUE_5',
        ictcty_0: 'VALUE_5',
        x4sohexp_0: 'VALUE_5',
        bpcinv_0: 'VALUE_5',
        bpcgru_0: 'VALUE_5',
        dep_0: 'VALUE_5',
        sohtyp_0: 'VALUE_5',
        revnum_0: 'VALUE_5',
        orddat_0: new Date().toISOString().split('T')[0],
        appflg_0: 'VALUE_5',
        linnbr_0: 'VALUE_5',
        dsptotqty_0: 52.5,
        bpieecnum_0: 'VALUE_5',
        invdtadsp_0: 'VALUE_5',
        eecict_0: 'VALUE_5',
        cntnam_0: 'VALUE_5',
        invlinnbr_0: 'VALUE_5',
        credat_0: new Date().toISOString().split('T')[0],
        cclren_0: 'VALUE_5',
        ccldat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_5',
        srenum_0: 'VALUE_5',
        vcrinvcnddat_0: new Date().toISOString().split('T')[0],
        xcmqint_0: 'VALUE_5',
        xmodgfi_0: 'VALUE_5',
        x4numint_0: 'VALUE_5',
        cninam_0: 'VALUE_5',
        cmgnum_0: 'VALUE_5',
        vtt_0: 'VALUE_5',
        sohtex2_0: 'VALUE_5',
        tsccod_0: 'VALUE_5',
        prityp_0: 52.5,
        invdtalin_0: 'VALUE_5',
        amttax_0: 52.5,
        bastax_0: 5,
        invdtaamt_0: 52.5,
        ordcle_0: 'VALUE_5',
        odl_0: 'VALUE_5',
        sohnum_0: 'VALUE_5',
        sdhtyp_0: 'VALUE_5',
        shidat_0: new Date().toISOString().split('T')[0],
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_5',
        bpdcrynam_0: 'VALUE_5',
        chgtyp_0: 'VALUE_5',
        invdtatyp_0: 'VALUE_5',
        rep_0: 'VALUE_5',
        chgrat_0: 'VALUE_5',
        plistc_0: 'VALUE_5',
        cce_0: 'VALUE_5',
        cpy_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        dlrati_0: 'VALUE_5',
        updusr_0: 'VALUE_5',
        bpisat_0: 'VALUE_5',
        cdtsta_0: 5,
        bptnum_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        discrgtyp_0: 'VALUE_5',
        z01statut_0: 5,
        x4sohdest_0: 'VALUE_5',
        invdta_0: 'VALUE_5',
        vacbpr_0: 'VALUE_5',
        stofcy_0: 'VALUE_5',
        dspweu_0: 'VALUE_5',
        pte_0: 'VALUE_5',
      },
      {
        hldsta_0: 1,
        hldcod_0: 'VALUE_6',
        hldcodp_0: 'VALUE_6',
        hlddat_0: new Date().toISOString().split('T')[0],
        hlddatp_0: new Date().toISOString().split('T')[0],
        hldtim_0: new Date().toISOString(),
        hldtimp_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpapyr_0: 'VALUE_6',
        ordnotl_0: 'VALUE_6',
        ordatil_0: new Date().toISOString().split('T')[0],
        ordinvnotl_0: 'VALUE_6',
        ordinvatil_0: 'VALUE_6',
        sinum_0: 'SOR0006',
        dsptotwei_0: 'VALUE_6',
        dsptotvol_0: 'VALUE_6',
        invsta_0: 6,
        dlvsta_0: 6,
        betcpy_0: 'VALUE_6',
        cndnam_0: 'Contact livraison 6',
        bpiposcod_0: 'VALUE_6',
        bpicry_0: 'VALUE_6',
        bpicrynam_0: 'VALUE_6',
        ocnprn_0: 'VALUE_6',
        sqhnum_0: 'VALUE_6',
        pfmtot_0: 'VALUE_6',
        unl_0: 'VALUE_6',
        betfcy_0: 'VALUE_6',
        pjt_0: 'VALUE_6',
        sfisstcod_0: 'VALUE_6',
        cdtstap_0: 6,
        x4avmotcom_0: 'VALUE_6',
        invcnd_0: 'VALUE_6',
        sstentcod_0: 'VALUE_6',
        bpaord_0: 'VALUE_6',
        bpainv_0: 'VALUE_6',
        draftstatus_0: 6,
        demdlvhou_0: 'VALUE_6',
        sohvaldat_0: new Date().toISOString().split('T')[0],
        zdatok_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_6',
        sohcfmflg_0: 'VALUE_6',
        inrati_0: 'VALUE_6',
        inrnot_0: 'VALUE_6',
        inrschati_0: 'VALUE_6',
        inrschnot_0: 'VALUE_6',
        sohnumend_0: 'VALUE_6',
        die_0: 'VALUE_6',
        zbyedi_0: 'VALUE_6',
        zflgedi_0: 'VALUE_6',
        zsuedi_0: 'VALUE_6',
        zctaedi_0: 'VALUE_6',
        zcodlivedi_0: 'VALUE_6',
        zcdeclifin_0: 'VALUE_6',
        zn1clifin_0: 'VALUE_6',
        zn2clifin_0: 'VALUE_6',
        zlieuexp_0: 'VALUE_6',
        x4sohenvaut_0: 'VALUE_6',
        x4avmot_0: 'VALUE_6',
        x4debctlcon_0: 'VALUE_6',
        x4forrel_0: 'VALUE_6',
        x4trtrel_0: 'VALUE_6',
        xcolsouple_0: 'VALUE_6',
        x4exclrfa_0: 'VALUE_6',
        x1typprepa_0: 'VALUE_6',
        x4rgop_0: 'VALUE_6',
        x1precodman_0: 'VALUE_6',
        draftrej_0: 'VALUE_6',
        draftrejren_0: 'VALUE_6',
        x1typprepman_0: 'VALUE_6',
        x4regrel_0: 'VALUE_6',
        hldusr_0: 'VALUE_6',
        hldusrp_0: 'VALUE_6',
        cur_0: 'VALUE_6',
        lasdlvnum_0: 'VALUE_6',
        lasdlvdat_0: new Date().toISOString().split('T')[0],
        lasinvnum_0: 'VALUE_6',
        dlrnot_0: 'VALUE_6',
        dspvou_0: 'VALUE_6',
        prfnum_0: 'VALUE_6',
        shiadecod_0: 'VALUE_6',
        salfcy_0: 'VALUE_6',
        bpcpyr_0: 'VALUE_6',
        xnbedt_0: 'VALUE_6',
        opgnum_0: 'VALUE_6',
        opgtyp_0: 'VALUE_6',
        bpcnam_0: 'VALUE_6',
        bpcaddlig_0: 'VALUE_6',
        bpcposcod_0: 'VALUE_6',
        bpccty_0: 'VALUE_6',
        bpccry_0: 'VALUE_6',
        bpccrynam_0: 'VALUE_6',
        copnbr_0: 'VALUE_6',
        eecloc_0: 'VALUE_6',
        clelinnbr_0: 'VALUE_6',
        bpcsat_0: 'VALUE_6',
        ordsta_0: 6,
        bpdsat_0: 'VALUE_6',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        daylti_0: 'VALUE_6',
        bpinam_0: 'VALUE_6',
        bpiaddlig_0: 'VALUE_6',
        bpicty_0: 'VALUE_6',
        bpdposcod_0: 'VALUE_6',
        bpdcty_0: 'VALUE_6',
        bpdcry_0: 'VALUE_6',
        sohcat_0: 'VALUE_6',
        bpcord_0: 'VALUE_6',
        ffwnum_0: 'VALUE_6',
        cusordref_0: 'VALUE_6',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        vlydatcon_0: new Date().toISOString().split('T')[0],
        alltyp_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        lan_0: 'VALUE_6',
        allsta_0: 6,
        adrval_0: 'VALUE_6',
        mdl_0: 'VALUE_6',
        drn_0: 'VALUE_6',
        dlvpio_0: 'VALUE_6',
        ime_0: 'VALUE_6',
        bpaadd_0: 'VALUE_6',
        bpdaddlig_0: 'VALUE_6',
        ordinvnot_0: 'VALUE_6',
        ordnot_0: 'VALUE_6',
        ordati_0: new Date().toISOString().split('T')[0],
        sohtex1_0: 'VALUE_6',
        ocnflg_0: 'VALUE_6',
        dme_0: 'VALUE_6',
        alllinnbr_0: 'VALUE_6',
        dlvlinnbr_0: 'VALUE_6',
        orifcy_0: 'VALUE_6',
        geocod_0: 'VALUE_6',
        insctyflg_0: 'VALUE_6',
        ffwadd_0: 'VALUE_6',
        ordinvati_0: 'VALUE_6',
        ictcty_0: 'VALUE_6',
        x4sohexp_0: 'VALUE_6',
        bpcinv_0: 'VALUE_6',
        bpcgru_0: 'VALUE_6',
        dep_0: 'VALUE_6',
        sohtyp_0: 'VALUE_6',
        revnum_0: 'VALUE_6',
        orddat_0: new Date().toISOString().split('T')[0],
        appflg_0: 'VALUE_6',
        linnbr_0: 'VALUE_6',
        dsptotqty_0: 63.0,
        bpieecnum_0: 'VALUE_6',
        invdtadsp_0: 'VALUE_6',
        eecict_0: 'VALUE_6',
        cntnam_0: 'VALUE_6',
        invlinnbr_0: 'VALUE_6',
        credat_0: new Date().toISOString().split('T')[0],
        cclren_0: 'VALUE_6',
        ccldat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_6',
        srenum_0: 'VALUE_6',
        vcrinvcnddat_0: new Date().toISOString().split('T')[0],
        xcmqint_0: 'VALUE_6',
        xmodgfi_0: 'VALUE_6',
        x4numint_0: 'VALUE_6',
        cninam_0: 'VALUE_6',
        cmgnum_0: 'VALUE_6',
        vtt_0: 'VALUE_6',
        sohtex2_0: 'VALUE_6',
        tsccod_0: 'VALUE_6',
        prityp_0: 63.0,
        invdtalin_0: 'VALUE_6',
        amttax_0: 63.0,
        bastax_0: 6,
        invdtaamt_0: 63.0,
        ordcle_0: 'VALUE_6',
        odl_0: 'VALUE_6',
        sohnum_0: 'VALUE_6',
        sdhtyp_0: 'VALUE_6',
        shidat_0: new Date().toISOString().split('T')[0],
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_6',
        bpdcrynam_0: 'VALUE_6',
        chgtyp_0: 'VALUE_6',
        invdtatyp_0: 'VALUE_6',
        rep_0: 'VALUE_6',
        chgrat_0: 'VALUE_6',
        plistc_0: 'VALUE_6',
        cce_0: 'VALUE_6',
        cpy_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        dlrati_0: 'VALUE_6',
        updusr_0: 'VALUE_6',
        bpisat_0: 'VALUE_6',
        cdtsta_0: 6,
        bptnum_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        discrgtyp_0: 'VALUE_6',
        z01statut_0: 6,
        x4sohdest_0: 'VALUE_6',
        invdta_0: 'VALUE_6',
        vacbpr_0: 'VALUE_6',
        stofcy_0: 'VALUE_6',
        dspweu_0: 'VALUE_6',
        pte_0: 'VALUE_6',
      },
      {
        hldsta_0: 1,
        hldcod_0: 'VALUE_7',
        hldcodp_0: 'VALUE_7',
        hlddat_0: new Date().toISOString().split('T')[0],
        hlddatp_0: new Date().toISOString().split('T')[0],
        hldtim_0: new Date().toISOString(),
        hldtimp_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpapyr_0: 'VALUE_7',
        ordnotl_0: 'VALUE_7',
        ordatil_0: new Date().toISOString().split('T')[0],
        ordinvnotl_0: 'VALUE_7',
        ordinvatil_0: 'VALUE_7',
        sinum_0: 'SOR0007',
        dsptotwei_0: 'VALUE_7',
        dsptotvol_0: 'VALUE_7',
        invsta_0: 7,
        dlvsta_0: 7,
        betcpy_0: 'VALUE_7',
        cndnam_0: 'Contact livraison 7',
        bpiposcod_0: 'VALUE_7',
        bpicry_0: 'VALUE_7',
        bpicrynam_0: 'VALUE_7',
        ocnprn_0: 'VALUE_7',
        sqhnum_0: 'VALUE_7',
        pfmtot_0: 'VALUE_7',
        unl_0: 'VALUE_7',
        betfcy_0: 'VALUE_7',
        pjt_0: 'VALUE_7',
        sfisstcod_0: 'VALUE_7',
        cdtstap_0: 7,
        x4avmotcom_0: 'VALUE_7',
        invcnd_0: 'VALUE_7',
        sstentcod_0: 'VALUE_7',
        bpaord_0: 'VALUE_7',
        bpainv_0: 'VALUE_7',
        draftstatus_0: 7,
        demdlvhou_0: 'VALUE_7',
        sohvaldat_0: new Date().toISOString().split('T')[0],
        zdatok_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_7',
        sohcfmflg_0: 'VALUE_7',
        inrati_0: 'VALUE_7',
        inrnot_0: 'VALUE_7',
        inrschati_0: 'VALUE_7',
        inrschnot_0: 'VALUE_7',
        sohnumend_0: 'VALUE_7',
        die_0: 'VALUE_7',
        zbyedi_0: 'VALUE_7',
        zflgedi_0: 'VALUE_7',
        zsuedi_0: 'VALUE_7',
        zctaedi_0: 'VALUE_7',
        zcodlivedi_0: 'VALUE_7',
        zcdeclifin_0: 'VALUE_7',
        zn1clifin_0: 'VALUE_7',
        zn2clifin_0: 'VALUE_7',
        zlieuexp_0: 'VALUE_7',
        x4sohenvaut_0: 'VALUE_7',
        x4avmot_0: 'VALUE_7',
        x4debctlcon_0: 'VALUE_7',
        x4forrel_0: 'VALUE_7',
        x4trtrel_0: 'VALUE_7',
        xcolsouple_0: 'VALUE_7',
        x4exclrfa_0: 'VALUE_7',
        x1typprepa_0: 'VALUE_7',
        x4rgop_0: 'VALUE_7',
        x1precodman_0: 'VALUE_7',
        draftrej_0: 'VALUE_7',
        draftrejren_0: 'VALUE_7',
        x1typprepman_0: 'VALUE_7',
        x4regrel_0: 'VALUE_7',
        hldusr_0: 'VALUE_7',
        hldusrp_0: 'VALUE_7',
        cur_0: 'VALUE_7',
        lasdlvnum_0: 'VALUE_7',
        lasdlvdat_0: new Date().toISOString().split('T')[0],
        lasinvnum_0: 'VALUE_7',
        dlrnot_0: 'VALUE_7',
        dspvou_0: 'VALUE_7',
        prfnum_0: 'VALUE_7',
        shiadecod_0: 'VALUE_7',
        salfcy_0: 'VALUE_7',
        bpcpyr_0: 'VALUE_7',
        xnbedt_0: 'VALUE_7',
        opgnum_0: 'VALUE_7',
        opgtyp_0: 'VALUE_7',
        bpcnam_0: 'VALUE_7',
        bpcaddlig_0: 'VALUE_7',
        bpcposcod_0: 'VALUE_7',
        bpccty_0: 'VALUE_7',
        bpccry_0: 'VALUE_7',
        bpccrynam_0: 'VALUE_7',
        copnbr_0: 'VALUE_7',
        eecloc_0: 'VALUE_7',
        clelinnbr_0: 'VALUE_7',
        bpcsat_0: 'VALUE_7',
        ordsta_0: 7,
        bpdsat_0: 'VALUE_7',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        daylti_0: 'VALUE_7',
        bpinam_0: 'VALUE_7',
        bpiaddlig_0: 'VALUE_7',
        bpicty_0: 'VALUE_7',
        bpdposcod_0: 'VALUE_7',
        bpdcty_0: 'VALUE_7',
        bpdcry_0: 'VALUE_7',
        sohcat_0: 'VALUE_7',
        bpcord_0: 'VALUE_7',
        ffwnum_0: 'VALUE_7',
        cusordref_0: 'VALUE_7',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        vlydatcon_0: new Date().toISOString().split('T')[0],
        alltyp_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        lan_0: 'VALUE_7',
        allsta_0: 7,
        adrval_0: 'VALUE_7',
        mdl_0: 'VALUE_7',
        drn_0: 'VALUE_7',
        dlvpio_0: 'VALUE_7',
        ime_0: 'VALUE_7',
        bpaadd_0: 'VALUE_7',
        bpdaddlig_0: 'VALUE_7',
        ordinvnot_0: 'VALUE_7',
        ordnot_0: 'VALUE_7',
        ordati_0: new Date().toISOString().split('T')[0],
        sohtex1_0: 'VALUE_7',
        ocnflg_0: 'VALUE_7',
        dme_0: 'VALUE_7',
        alllinnbr_0: 'VALUE_7',
        dlvlinnbr_0: 'VALUE_7',
        orifcy_0: 'VALUE_7',
        geocod_0: 'VALUE_7',
        insctyflg_0: 'VALUE_7',
        ffwadd_0: 'VALUE_7',
        ordinvati_0: 'VALUE_7',
        ictcty_0: 'VALUE_7',
        x4sohexp_0: 'VALUE_7',
        bpcinv_0: 'VALUE_7',
        bpcgru_0: 'VALUE_7',
        dep_0: 'VALUE_7',
        sohtyp_0: 'VALUE_7',
        revnum_0: 'VALUE_7',
        orddat_0: new Date().toISOString().split('T')[0],
        appflg_0: 'VALUE_7',
        linnbr_0: 'VALUE_7',
        dsptotqty_0: 73.5,
        bpieecnum_0: 'VALUE_7',
        invdtadsp_0: 'VALUE_7',
        eecict_0: 'VALUE_7',
        cntnam_0: 'VALUE_7',
        invlinnbr_0: 'VALUE_7',
        credat_0: new Date().toISOString().split('T')[0],
        cclren_0: 'VALUE_7',
        ccldat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_7',
        srenum_0: 'VALUE_7',
        vcrinvcnddat_0: new Date().toISOString().split('T')[0],
        xcmqint_0: 'VALUE_7',
        xmodgfi_0: 'VALUE_7',
        x4numint_0: 'VALUE_7',
        cninam_0: 'VALUE_7',
        cmgnum_0: 'VALUE_7',
        vtt_0: 'VALUE_7',
        sohtex2_0: 'VALUE_7',
        tsccod_0: 'VALUE_7',
        prityp_0: 73.5,
        invdtalin_0: 'VALUE_7',
        amttax_0: 73.5,
        bastax_0: 7,
        invdtaamt_0: 73.5,
        ordcle_0: 'VALUE_7',
        odl_0: 'VALUE_7',
        sohnum_0: 'VALUE_7',
        sdhtyp_0: 'VALUE_7',
        shidat_0: new Date().toISOString().split('T')[0],
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_7',
        bpdcrynam_0: 'VALUE_7',
        chgtyp_0: 'VALUE_7',
        invdtatyp_0: 'VALUE_7',
        rep_0: 'VALUE_7',
        chgrat_0: 'VALUE_7',
        plistc_0: 'VALUE_7',
        cce_0: 'VALUE_7',
        cpy_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        dlrati_0: 'VALUE_7',
        updusr_0: 'VALUE_7',
        bpisat_0: 'VALUE_7',
        cdtsta_0: 7,
        bptnum_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        discrgtyp_0: 'VALUE_7',
        z01statut_0: 7,
        x4sohdest_0: 'VALUE_7',
        invdta_0: 'VALUE_7',
        vacbpr_0: 'VALUE_7',
        stofcy_0: 'VALUE_7',
        dspweu_0: 'VALUE_7',
        pte_0: 'VALUE_7',
      },
      {
        hldsta_0: 1,
        hldcod_0: 'VALUE_8',
        hldcodp_0: 'VALUE_8',
        hlddat_0: new Date().toISOString().split('T')[0],
        hlddatp_0: new Date().toISOString().split('T')[0],
        hldtim_0: new Date().toISOString(),
        hldtimp_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpapyr_0: 'VALUE_8',
        ordnotl_0: 'VALUE_8',
        ordatil_0: new Date().toISOString().split('T')[0],
        ordinvnotl_0: 'VALUE_8',
        ordinvatil_0: 'VALUE_8',
        sinum_0: 'SOR0008',
        dsptotwei_0: 'VALUE_8',
        dsptotvol_0: 'VALUE_8',
        invsta_0: 8,
        dlvsta_0: 8,
        betcpy_0: 'VALUE_8',
        cndnam_0: 'Contact livraison 8',
        bpiposcod_0: 'VALUE_8',
        bpicry_0: 'VALUE_8',
        bpicrynam_0: 'VALUE_8',
        ocnprn_0: 'VALUE_8',
        sqhnum_0: 'VALUE_8',
        pfmtot_0: 'VALUE_8',
        unl_0: 'VALUE_8',
        betfcy_0: 'VALUE_8',
        pjt_0: 'VALUE_8',
        sfisstcod_0: 'VALUE_8',
        cdtstap_0: 8,
        x4avmotcom_0: 'VALUE_8',
        invcnd_0: 'VALUE_8',
        sstentcod_0: 'VALUE_8',
        bpaord_0: 'VALUE_8',
        bpainv_0: 'VALUE_8',
        draftstatus_0: 8,
        demdlvhou_0: 'VALUE_8',
        sohvaldat_0: new Date().toISOString().split('T')[0],
        zdatok_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_8',
        sohcfmflg_0: 'VALUE_8',
        inrati_0: 'VALUE_8',
        inrnot_0: 'VALUE_8',
        inrschati_0: 'VALUE_8',
        inrschnot_0: 'VALUE_8',
        sohnumend_0: 'VALUE_8',
        die_0: 'VALUE_8',
        zbyedi_0: 'VALUE_8',
        zflgedi_0: 'VALUE_8',
        zsuedi_0: 'VALUE_8',
        zctaedi_0: 'VALUE_8',
        zcodlivedi_0: 'VALUE_8',
        zcdeclifin_0: 'VALUE_8',
        zn1clifin_0: 'VALUE_8',
        zn2clifin_0: 'VALUE_8',
        zlieuexp_0: 'VALUE_8',
        x4sohenvaut_0: 'VALUE_8',
        x4avmot_0: 'VALUE_8',
        x4debctlcon_0: 'VALUE_8',
        x4forrel_0: 'VALUE_8',
        x4trtrel_0: 'VALUE_8',
        xcolsouple_0: 'VALUE_8',
        x4exclrfa_0: 'VALUE_8',
        x1typprepa_0: 'VALUE_8',
        x4rgop_0: 'VALUE_8',
        x1precodman_0: 'VALUE_8',
        draftrej_0: 'VALUE_8',
        draftrejren_0: 'VALUE_8',
        x1typprepman_0: 'VALUE_8',
        x4regrel_0: 'VALUE_8',
        hldusr_0: 'VALUE_8',
        hldusrp_0: 'VALUE_8',
        cur_0: 'VALUE_8',
        lasdlvnum_0: 'VALUE_8',
        lasdlvdat_0: new Date().toISOString().split('T')[0],
        lasinvnum_0: 'VALUE_8',
        dlrnot_0: 'VALUE_8',
        dspvou_0: 'VALUE_8',
        prfnum_0: 'VALUE_8',
        shiadecod_0: 'VALUE_8',
        salfcy_0: 'VALUE_8',
        bpcpyr_0: 'VALUE_8',
        xnbedt_0: 'VALUE_8',
        opgnum_0: 'VALUE_8',
        opgtyp_0: 'VALUE_8',
        bpcnam_0: 'VALUE_8',
        bpcaddlig_0: 'VALUE_8',
        bpcposcod_0: 'VALUE_8',
        bpccty_0: 'VALUE_8',
        bpccry_0: 'VALUE_8',
        bpccrynam_0: 'VALUE_8',
        copnbr_0: 'VALUE_8',
        eecloc_0: 'VALUE_8',
        clelinnbr_0: 'VALUE_8',
        bpcsat_0: 'VALUE_8',
        ordsta_0: 8,
        bpdsat_0: 'VALUE_8',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        daylti_0: 'VALUE_8',
        bpinam_0: 'VALUE_8',
        bpiaddlig_0: 'VALUE_8',
        bpicty_0: 'VALUE_8',
        bpdposcod_0: 'VALUE_8',
        bpdcty_0: 'VALUE_8',
        bpdcry_0: 'VALUE_8',
        sohcat_0: 'VALUE_8',
        bpcord_0: 'VALUE_8',
        ffwnum_0: 'VALUE_8',
        cusordref_0: 'VALUE_8',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        vlydatcon_0: new Date().toISOString().split('T')[0],
        alltyp_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        lan_0: 'VALUE_8',
        allsta_0: 8,
        adrval_0: 'VALUE_8',
        mdl_0: 'VALUE_8',
        drn_0: 'VALUE_8',
        dlvpio_0: 'VALUE_8',
        ime_0: 'VALUE_8',
        bpaadd_0: 'VALUE_8',
        bpdaddlig_0: 'VALUE_8',
        ordinvnot_0: 'VALUE_8',
        ordnot_0: 'VALUE_8',
        ordati_0: new Date().toISOString().split('T')[0],
        sohtex1_0: 'VALUE_8',
        ocnflg_0: 'VALUE_8',
        dme_0: 'VALUE_8',
        alllinnbr_0: 'VALUE_8',
        dlvlinnbr_0: 'VALUE_8',
        orifcy_0: 'VALUE_8',
        geocod_0: 'VALUE_8',
        insctyflg_0: 'VALUE_8',
        ffwadd_0: 'VALUE_8',
        ordinvati_0: 'VALUE_8',
        ictcty_0: 'VALUE_8',
        x4sohexp_0: 'VALUE_8',
        bpcinv_0: 'VALUE_8',
        bpcgru_0: 'VALUE_8',
        dep_0: 'VALUE_8',
        sohtyp_0: 'VALUE_8',
        revnum_0: 'VALUE_8',
        orddat_0: new Date().toISOString().split('T')[0],
        appflg_0: 'VALUE_8',
        linnbr_0: 'VALUE_8',
        dsptotqty_0: 84.0,
        bpieecnum_0: 'VALUE_8',
        invdtadsp_0: 'VALUE_8',
        eecict_0: 'VALUE_8',
        cntnam_0: 'VALUE_8',
        invlinnbr_0: 'VALUE_8',
        credat_0: new Date().toISOString().split('T')[0],
        cclren_0: 'VALUE_8',
        ccldat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_8',
        srenum_0: 'VALUE_8',
        vcrinvcnddat_0: new Date().toISOString().split('T')[0],
        xcmqint_0: 'VALUE_8',
        xmodgfi_0: 'VALUE_8',
        x4numint_0: 'VALUE_8',
        cninam_0: 'VALUE_8',
        cmgnum_0: 'VALUE_8',
        vtt_0: 'VALUE_8',
        sohtex2_0: 'VALUE_8',
        tsccod_0: 'VALUE_8',
        prityp_0: 84.0,
        invdtalin_0: 'VALUE_8',
        amttax_0: 84.0,
        bastax_0: 8,
        invdtaamt_0: 84.0,
        ordcle_0: 'VALUE_8',
        odl_0: 'VALUE_8',
        sohnum_0: 'VALUE_8',
        sdhtyp_0: 'VALUE_8',
        shidat_0: new Date().toISOString().split('T')[0],
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_8',
        bpdcrynam_0: 'VALUE_8',
        chgtyp_0: 'VALUE_8',
        invdtatyp_0: 'VALUE_8',
        rep_0: 'VALUE_8',
        chgrat_0: 'VALUE_8',
        plistc_0: 'VALUE_8',
        cce_0: 'VALUE_8',
        cpy_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        dlrati_0: 'VALUE_8',
        updusr_0: 'VALUE_8',
        bpisat_0: 'VALUE_8',
        cdtsta_0: 8,
        bptnum_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        discrgtyp_0: 'VALUE_8',
        z01statut_0: 8,
        x4sohdest_0: 'VALUE_8',
        invdta_0: 'VALUE_8',
        vacbpr_0: 'VALUE_8',
        stofcy_0: 'VALUE_8',
        dspweu_0: 'VALUE_8',
        pte_0: 'VALUE_8',
      },
      {
        hldsta_0: 1,
        hldcod_0: 'VALUE_9',
        hldcodp_0: 'VALUE_9',
        hlddat_0: new Date().toISOString().split('T')[0],
        hlddatp_0: new Date().toISOString().split('T')[0],
        hldtim_0: new Date().toISOString(),
        hldtimp_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpapyr_0: 'VALUE_9',
        ordnotl_0: 'VALUE_9',
        ordatil_0: new Date().toISOString().split('T')[0],
        ordinvnotl_0: 'VALUE_9',
        ordinvatil_0: 'VALUE_9',
        sinum_0: 'SOR0009',
        dsptotwei_0: 'VALUE_9',
        dsptotvol_0: 'VALUE_9',
        invsta_0: 9,
        dlvsta_0: 9,
        betcpy_0: 'VALUE_9',
        cndnam_0: 'Contact livraison 9',
        bpiposcod_0: 'VALUE_9',
        bpicry_0: 'VALUE_9',
        bpicrynam_0: 'VALUE_9',
        ocnprn_0: 'VALUE_9',
        sqhnum_0: 'VALUE_9',
        pfmtot_0: 'VALUE_9',
        unl_0: 'VALUE_9',
        betfcy_0: 'VALUE_9',
        pjt_0: 'VALUE_9',
        sfisstcod_0: 'VALUE_9',
        cdtstap_0: 9,
        x4avmotcom_0: 'VALUE_9',
        invcnd_0: 'VALUE_9',
        sstentcod_0: 'VALUE_9',
        bpaord_0: 'VALUE_9',
        bpainv_0: 'VALUE_9',
        draftstatus_0: 9,
        demdlvhou_0: 'VALUE_9',
        sohvaldat_0: new Date().toISOString().split('T')[0],
        zdatok_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_9',
        sohcfmflg_0: 'VALUE_9',
        inrati_0: 'VALUE_9',
        inrnot_0: 'VALUE_9',
        inrschati_0: 'VALUE_9',
        inrschnot_0: 'VALUE_9',
        sohnumend_0: 'VALUE_9',
        die_0: 'VALUE_9',
        zbyedi_0: 'VALUE_9',
        zflgedi_0: 'VALUE_9',
        zsuedi_0: 'VALUE_9',
        zctaedi_0: 'VALUE_9',
        zcodlivedi_0: 'VALUE_9',
        zcdeclifin_0: 'VALUE_9',
        zn1clifin_0: 'VALUE_9',
        zn2clifin_0: 'VALUE_9',
        zlieuexp_0: 'VALUE_9',
        x4sohenvaut_0: 'VALUE_9',
        x4avmot_0: 'VALUE_9',
        x4debctlcon_0: 'VALUE_9',
        x4forrel_0: 'VALUE_9',
        x4trtrel_0: 'VALUE_9',
        xcolsouple_0: 'VALUE_9',
        x4exclrfa_0: 'VALUE_9',
        x1typprepa_0: 'VALUE_9',
        x4rgop_0: 'VALUE_9',
        x1precodman_0: 'VALUE_9',
        draftrej_0: 'VALUE_9',
        draftrejren_0: 'VALUE_9',
        x1typprepman_0: 'VALUE_9',
        x4regrel_0: 'VALUE_9',
        hldusr_0: 'VALUE_9',
        hldusrp_0: 'VALUE_9',
        cur_0: 'VALUE_9',
        lasdlvnum_0: 'VALUE_9',
        lasdlvdat_0: new Date().toISOString().split('T')[0],
        lasinvnum_0: 'VALUE_9',
        dlrnot_0: 'VALUE_9',
        dspvou_0: 'VALUE_9',
        prfnum_0: 'VALUE_9',
        shiadecod_0: 'VALUE_9',
        salfcy_0: 'VALUE_9',
        bpcpyr_0: 'VALUE_9',
        xnbedt_0: 'VALUE_9',
        opgnum_0: 'VALUE_9',
        opgtyp_0: 'VALUE_9',
        bpcnam_0: 'VALUE_9',
        bpcaddlig_0: 'VALUE_9',
        bpcposcod_0: 'VALUE_9',
        bpccty_0: 'VALUE_9',
        bpccry_0: 'VALUE_9',
        bpccrynam_0: 'VALUE_9',
        copnbr_0: 'VALUE_9',
        eecloc_0: 'VALUE_9',
        clelinnbr_0: 'VALUE_9',
        bpcsat_0: 'VALUE_9',
        ordsta_0: 9,
        bpdsat_0: 'VALUE_9',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        daylti_0: 'VALUE_9',
        bpinam_0: 'VALUE_9',
        bpiaddlig_0: 'VALUE_9',
        bpicty_0: 'VALUE_9',
        bpdposcod_0: 'VALUE_9',
        bpdcty_0: 'VALUE_9',
        bpdcry_0: 'VALUE_9',
        sohcat_0: 'VALUE_9',
        bpcord_0: 'VALUE_9',
        ffwnum_0: 'VALUE_9',
        cusordref_0: 'VALUE_9',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        vlydatcon_0: new Date().toISOString().split('T')[0],
        alltyp_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        lan_0: 'VALUE_9',
        allsta_0: 9,
        adrval_0: 'VALUE_9',
        mdl_0: 'VALUE_9',
        drn_0: 'VALUE_9',
        dlvpio_0: 'VALUE_9',
        ime_0: 'VALUE_9',
        bpaadd_0: 'VALUE_9',
        bpdaddlig_0: 'VALUE_9',
        ordinvnot_0: 'VALUE_9',
        ordnot_0: 'VALUE_9',
        ordati_0: new Date().toISOString().split('T')[0],
        sohtex1_0: 'VALUE_9',
        ocnflg_0: 'VALUE_9',
        dme_0: 'VALUE_9',
        alllinnbr_0: 'VALUE_9',
        dlvlinnbr_0: 'VALUE_9',
        orifcy_0: 'VALUE_9',
        geocod_0: 'VALUE_9',
        insctyflg_0: 'VALUE_9',
        ffwadd_0: 'VALUE_9',
        ordinvati_0: 'VALUE_9',
        ictcty_0: 'VALUE_9',
        x4sohexp_0: 'VALUE_9',
        bpcinv_0: 'VALUE_9',
        bpcgru_0: 'VALUE_9',
        dep_0: 'VALUE_9',
        sohtyp_0: 'VALUE_9',
        revnum_0: 'VALUE_9',
        orddat_0: new Date().toISOString().split('T')[0],
        appflg_0: 'VALUE_9',
        linnbr_0: 'VALUE_9',
        dsptotqty_0: 94.5,
        bpieecnum_0: 'VALUE_9',
        invdtadsp_0: 'VALUE_9',
        eecict_0: 'VALUE_9',
        cntnam_0: 'VALUE_9',
        invlinnbr_0: 'VALUE_9',
        credat_0: new Date().toISOString().split('T')[0],
        cclren_0: 'VALUE_9',
        ccldat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_9',
        srenum_0: 'VALUE_9',
        vcrinvcnddat_0: new Date().toISOString().split('T')[0],
        xcmqint_0: 'VALUE_9',
        xmodgfi_0: 'VALUE_9',
        x4numint_0: 'VALUE_9',
        cninam_0: 'VALUE_9',
        cmgnum_0: 'VALUE_9',
        vtt_0: 'VALUE_9',
        sohtex2_0: 'VALUE_9',
        tsccod_0: 'VALUE_9',
        prityp_0: 94.5,
        invdtalin_0: 'VALUE_9',
        amttax_0: 94.5,
        bastax_0: 9,
        invdtaamt_0: 94.5,
        ordcle_0: 'VALUE_9',
        odl_0: 'VALUE_9',
        sohnum_0: 'VALUE_9',
        sdhtyp_0: 'VALUE_9',
        shidat_0: new Date().toISOString().split('T')[0],
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_9',
        bpdcrynam_0: 'VALUE_9',
        chgtyp_0: 'VALUE_9',
        invdtatyp_0: 'VALUE_9',
        rep_0: 'VALUE_9',
        chgrat_0: 'VALUE_9',
        plistc_0: 'VALUE_9',
        cce_0: 'VALUE_9',
        cpy_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        dlrati_0: 'VALUE_9',
        updusr_0: 'VALUE_9',
        bpisat_0: 'VALUE_9',
        cdtsta_0: 9,
        bptnum_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        discrgtyp_0: 'VALUE_9',
        z01statut_0: 9,
        x4sohdest_0: 'VALUE_9',
        invdta_0: 'VALUE_9',
        vacbpr_0: 'VALUE_9',
        stofcy_0: 'VALUE_9',
        dspweu_0: 'VALUE_9',
        pte_0: 'VALUE_9',
      },
      {
        hldsta_0: 1,
        hldcod_0: 'VALUE_10',
        hldcodp_0: 'VALUE_10',
        hlddat_0: new Date().toISOString().split('T')[0],
        hlddatp_0: new Date().toISOString().split('T')[0],
        hldtim_0: new Date().toISOString(),
        hldtimp_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpapyr_0: 'VALUE_10',
        ordnotl_0: 'VALUE_10',
        ordatil_0: new Date().toISOString().split('T')[0],
        ordinvnotl_0: 'VALUE_10',
        ordinvatil_0: 'VALUE_10',
        sinum_0: 'SOR0010',
        dsptotwei_0: 'VALUE_10',
        dsptotvol_0: 'VALUE_10',
        invsta_0: 10,
        dlvsta_0: 10,
        betcpy_0: 'VALUE_10',
        cndnam_0: 'Contact livraison 10',
        bpiposcod_0: 'VALUE_10',
        bpicry_0: 'VALUE_10',
        bpicrynam_0: 'VALUE_10',
        ocnprn_0: 'VALUE_10',
        sqhnum_0: 'VALUE_10',
        pfmtot_0: 'VALUE_10',
        unl_0: 'VALUE_10',
        betfcy_0: 'VALUE_10',
        pjt_0: 'VALUE_10',
        sfisstcod_0: 'VALUE_10',
        cdtstap_0: 10,
        x4avmotcom_0: 'VALUE_10',
        invcnd_0: 'VALUE_10',
        sstentcod_0: 'VALUE_10',
        bpaord_0: 'VALUE_10',
        bpainv_0: 'VALUE_10',
        draftstatus_0: 10,
        demdlvhou_0: 'VALUE_10',
        sohvaldat_0: new Date().toISOString().split('T')[0],
        zdatok_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_10',
        sohcfmflg_0: 'VALUE_10',
        inrati_0: 'VALUE_10',
        inrnot_0: 'VALUE_10',
        inrschati_0: 'VALUE_10',
        inrschnot_0: 'VALUE_10',
        sohnumend_0: 'VALUE_10',
        die_0: 'VALUE_10',
        zbyedi_0: 'VALUE_10',
        zflgedi_0: 'VALUE_10',
        zsuedi_0: 'VALUE_10',
        zctaedi_0: 'VALUE_10',
        zcodlivedi_0: 'VALUE_10',
        zcdeclifin_0: 'VALUE_10',
        zn1clifin_0: 'VALUE_10',
        zn2clifin_0: 'VALUE_10',
        zlieuexp_0: 'VALUE_10',
        x4sohenvaut_0: 'VALUE_10',
        x4avmot_0: 'VALUE_10',
        x4debctlcon_0: 'VALUE_10',
        x4forrel_0: 'VALUE_10',
        x4trtrel_0: 'VALUE_10',
        xcolsouple_0: 'VALUE_10',
        x4exclrfa_0: 'VALUE_10',
        x1typprepa_0: 'VALUE_10',
        x4rgop_0: 'VALUE_10',
        x1precodman_0: 'VALUE_10',
        draftrej_0: 'VALUE_10',
        draftrejren_0: 'VALUE_10',
        x1typprepman_0: 'VALUE_10',
        x4regrel_0: 'VALUE_10',
        hldusr_0: 'VALUE_10',
        hldusrp_0: 'VALUE_10',
        cur_0: 'VALUE_10',
        lasdlvnum_0: 'VALUE_10',
        lasdlvdat_0: new Date().toISOString().split('T')[0],
        lasinvnum_0: 'VALUE_10',
        dlrnot_0: 'VALUE_10',
        dspvou_0: 'VALUE_10',
        prfnum_0: 'VALUE_10',
        shiadecod_0: 'VALUE_10',
        salfcy_0: 'VALUE_10',
        bpcpyr_0: 'VALUE_10',
        xnbedt_0: 'VALUE_10',
        opgnum_0: 'VALUE_10',
        opgtyp_0: 'VALUE_10',
        bpcnam_0: 'VALUE_10',
        bpcaddlig_0: 'VALUE_10',
        bpcposcod_0: 'VALUE_10',
        bpccty_0: 'VALUE_10',
        bpccry_0: 'VALUE_10',
        bpccrynam_0: 'VALUE_10',
        copnbr_0: 'VALUE_10',
        eecloc_0: 'VALUE_10',
        clelinnbr_0: 'VALUE_10',
        bpcsat_0: 'VALUE_10',
        ordsta_0: 10,
        bpdsat_0: 'VALUE_10',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        daylti_0: 'VALUE_10',
        bpinam_0: 'VALUE_10',
        bpiaddlig_0: 'VALUE_10',
        bpicty_0: 'VALUE_10',
        bpdposcod_0: 'VALUE_10',
        bpdcty_0: 'VALUE_10',
        bpdcry_0: 'VALUE_10',
        sohcat_0: 'VALUE_10',
        bpcord_0: 'VALUE_10',
        ffwnum_0: 'VALUE_10',
        cusordref_0: 'VALUE_10',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        vlydatcon_0: new Date().toISOString().split('T')[0],
        alltyp_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        lan_0: 'VALUE_10',
        allsta_0: 10,
        adrval_0: 'VALUE_10',
        mdl_0: 'VALUE_10',
        drn_0: 'VALUE_10',
        dlvpio_0: 'VALUE_10',
        ime_0: 'VALUE_10',
        bpaadd_0: 'VALUE_10',
        bpdaddlig_0: 'VALUE_10',
        ordinvnot_0: 'VALUE_10',
        ordnot_0: 'VALUE_10',
        ordati_0: new Date().toISOString().split('T')[0],
        sohtex1_0: 'VALUE_10',
        ocnflg_0: 'VALUE_10',
        dme_0: 'VALUE_10',
        alllinnbr_0: 'VALUE_10',
        dlvlinnbr_0: 'VALUE_10',
        orifcy_0: 'VALUE_10',
        geocod_0: 'VALUE_10',
        insctyflg_0: 'VALUE_10',
        ffwadd_0: 'VALUE_10',
        ordinvati_0: 'VALUE_10',
        ictcty_0: 'VALUE_10',
        x4sohexp_0: 'VALUE_10',
        bpcinv_0: 'VALUE_10',
        bpcgru_0: 'VALUE_10',
        dep_0: 'VALUE_10',
        sohtyp_0: 'VALUE_10',
        revnum_0: 'VALUE_10',
        orddat_0: new Date().toISOString().split('T')[0],
        appflg_0: 'VALUE_10',
        linnbr_0: 'VALUE_10',
        dsptotqty_0: 105.0,
        bpieecnum_0: 'VALUE_10',
        invdtadsp_0: 'VALUE_10',
        eecict_0: 'VALUE_10',
        cntnam_0: 'VALUE_10',
        invlinnbr_0: 'VALUE_10',
        credat_0: new Date().toISOString().split('T')[0],
        cclren_0: 'VALUE_10',
        ccldat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_10',
        srenum_0: 'VALUE_10',
        vcrinvcnddat_0: new Date().toISOString().split('T')[0],
        xcmqint_0: 'VALUE_10',
        xmodgfi_0: 'VALUE_10',
        x4numint_0: 'VALUE_10',
        cninam_0: 'VALUE_10',
        cmgnum_0: 'VALUE_10',
        vtt_0: 'VALUE_10',
        sohtex2_0: 'VALUE_10',
        tsccod_0: 'VALUE_10',
        prityp_0: 105.0,
        invdtalin_0: 'VALUE_10',
        amttax_0: 105.0,
        bastax_0: 10,
        invdtaamt_0: 105.0,
        ordcle_0: 'VALUE_10',
        odl_0: 'VALUE_10',
        sohnum_0: 'VALUE_10',
        sdhtyp_0: 'VALUE_10',
        shidat_0: new Date().toISOString().split('T')[0],
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_10',
        bpdcrynam_0: 'VALUE_10',
        chgtyp_0: 'VALUE_10',
        invdtatyp_0: 'VALUE_10',
        rep_0: 'VALUE_10',
        chgrat_0: 'VALUE_10',
        plistc_0: 'VALUE_10',
        cce_0: 'VALUE_10',
        cpy_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        dlrati_0: 'VALUE_10',
        updusr_0: 'VALUE_10',
        bpisat_0: 'VALUE_10',
        cdtsta_0: 10,
        bptnum_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        discrgtyp_0: 'VALUE_10',
        z01statut_0: 10,
        x4sohdest_0: 'VALUE_10',
        invdta_0: 'VALUE_10',
        vacbpr_0: 'VALUE_10',
        stofcy_0: 'VALUE_10',
        dspweu_0: 'VALUE_10',
        pte_0: 'VALUE_10',
      },
    ]

    await Database.table('sorder').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans sorder`)
  }
}
