import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour SORDERQ
    const data = [
      {
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_1',
        xpntmonte_0: 'VALUE_1',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xsvcemet_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        x4hdemdlvd_0: 'VALUE_1',
        odlqty_0: 10.5,
        odlqtystu_0: 10.5,
        xniveng_0: 'VALUE_1',
        xnbetiimpp_0: 'VALUE_1',
        soqpsonum_0: 'SOR0001',
        lprqtystu_0: 10.5,
        xligori_0: 'VALUE_1',
        fmi_0: 'VALUE_1',
        lprqty_0: 10.5,
        prgbilnum_0: 'VALUE_1',
        x4avmotd_0: 'VALUE_1',
        xssligori_0: 'VALUE_1',
        x4rgopl_0: 'VALUE_1',
        x4exclrfad_0: 'VALUE_1',
        xdestfin_0: 'Destination Finale 1',
        xdesint_0: 'VALUE_1',
        xligmerori_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        maxdlvdat_0: new Date().toISOString().split('T')[0],
        uselimdat_0: new Date().toISOString().split('T')[0],
        x4hshidat_0: new Date().toISOString().split('T')[0],
        demdlvref_0: 'VALUE_1',
        rattaxlin_0: 'VALUE_1',
        oriqty_0: 10.5,
        precod_0: 'VALUE_1',
        soqseq_0: 'VALUE_1',
        poqseq_0: 'VALUE_1',
        updusr_0: 'VALUE_1',
        invqtystu_0: 10.5,
        qtystu_0: 10.5,
        sohcat_0: 'VALUE_1',
        bpcord_0: 'VALUE_1',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_1',
        alltyp_0: 'VALUE_1',
        mdl_0: 'VALUE_1',
        drn_0: 'VALUE_1',
        dlvpio_0: 'VALUE_1',
        daylti_0: 'VALUE_1',
        bpaadd_0: 'VALUE_1',
        ndeprnbom_0: 'VALUE_1',
        invprnbom_0: 'VALUE_1',
        invqty_0: 10.5,
        impnumlig_0: 'VALUE_1',
        geocod_0: 'VALUE_1',
        insctyflg_0: 'VALUE_1',
        x4qtyini_0: 10.5,
        tdlqtystu_0: 10.5,
        bastaxlin_0: 1,
        ocnprnbom_0: 'VALUE_1',
        xtext0_0: 'VALUE_1',
        xkanban_0: 'VALUE_1',
        xqteret_0: 'VALUE_1',
        oprqty_0: 10.5,
        preqty_0: 10.5,
        oprqtystu_0: 10.5,
        preqtystu_0: 10.5,
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        xnbetiimp_0: 'VALUE_1',
        xpcusauc01_0: 'VALUE_1',
        xpldeliv_0: 'VALUE_1',
        dsplinwei_0: 'VALUE_1',
        dsplinvol_0: 'VALUE_1',
        invamt_0: 10.5,
        dlvpiocmp_0: 'VALUE_1',
        lot_0: 'VALUE_1',
        sta_0: 1,
        xregroup_0: 'VALUE_1',
        loc_0: 'VALUE_1',
        mon_0: 'VALUE_1',
        sddlin_0: 'VALUE_1',
        pckcap_0: 'VALUE_1',
        yea_0: 'VALUE_1',
        pjt_0: 'VALUE_1',
        x4facture_0: 'VALUE_1',
        pck_0: 'VALUE_1',
        x4avmotcomd_0: 'VALUE_1',
        maxdlvhou_0: 'VALUE_1',
        eccvalmaj_0: 'VALUE_1',
        eccvalmin_0: 'VALUE_1',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_1',
        xpcu1itm_0: 'VALUE_1',
        xtimmes_0: new Date().toISOString(),
        xalert_0: 'VALUE_1',
        fminum_0: 'VALUE_1',
        fmilin_0: 'VALUE_1',
        fmiseq_0: 'VALUE_1',
        orddat_0: new Date().toISOString().split('T')[0],
        linordnum_0: 'VALUE_1',
        demdlvhou_0: 'VALUE_1',
        soqsta_0: 1,
        ddtanum_0: 'VALUE_1',
        ddtanot_0: 'VALUE_1',
        dlvday_0: 'VALUE_1',
        cad_0: 'VALUE_1',
        wee_0: 'VALUE_1',
        ynbcolis_0: 'VALUE_1',
        demsta_0: 1,
        shtqty_0: 10.5,
        shtqtystu_0: 10.5,
        invflg_0: 'VALUE_1',
        credat_0: new Date().toISOString().split('T')[0],
        pitflg_0: 'VALUE_1',
        cclren_0: 'VALUE_1',
        ccldat_0: new Date().toISOString().split('T')[0],
        xflgret_0: 'VALUE_1',
        dlvflg_0: 'VALUE_1',
        xcmqint_0: 'VALUE_1',
        poplin_0: 'VALUE_1',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_1',
        vtc_0: 'VALUE_1',
        taxgeoflg_0: 'VALUE_1',
        taxflg_0: 'VALUE_1',
        taxregflg_0: 'VALUE_1',
        soqtex_0: 'VALUE_1',
        sdhnum_0: 'VALUE_1',
        sohnum_0: 'VALUE_1',
        pohnum_0: 'VALUE_1',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_1',
        dlvqtystu_0: 10.5,
        perstrdat_0: new Date().toISOString().split('T')[0],
        perenddat_0: new Date().toISOString().split('T')[0],
        pernbrday_0: 'VALUE_1',
        useplc_0: 'VALUE_1',
        qty_0: 10.5,
        allqty_0: 10.5,
        cpy_0: 'VALUE_1',
        soplin_0: 'VALUE_1',
        soqseqnum_0: 'VALUE_1',
        shihou_0: 'VALUE_1',
        extdlvdat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        bptnum_0: 'VALUE_1',
        demnum_0: 'VALUE_1',
        allqtystu_0: 10.5,
        creusr_0: 'VALUE_1',
        xversion_0: 'VALUE_1',
        z01statut_0: 1,
        stofcy_0: 'VALUE_1',
        stomgtcod_0: 'VALUE_1',
        itmref_0: 'VALUE_1',
        dspvou_0: 'VALUE_1',
        dspweu_0: 'VALUE_1',
        salfcy_0: 'VALUE_1',
        tdlqty_0: 10.5,
        dlvqty_0: 10.5,
      },
      {
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_2',
        xpntmonte_0: 'VALUE_2',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xsvcemet_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        x4hdemdlvd_0: 'VALUE_2',
        odlqty_0: 21.0,
        odlqtystu_0: 21.0,
        xniveng_0: 'VALUE_2',
        xnbetiimpp_0: 'VALUE_2',
        soqpsonum_0: 'SOR0002',
        lprqtystu_0: 21.0,
        xligori_0: 'VALUE_2',
        fmi_0: 'VALUE_2',
        lprqty_0: 21.0,
        prgbilnum_0: 'VALUE_2',
        x4avmotd_0: 'VALUE_2',
        xssligori_0: 'VALUE_2',
        x4rgopl_0: 'VALUE_2',
        x4exclrfad_0: 'VALUE_2',
        xdestfin_0: 'Destination Finale 2',
        xdesint_0: 'VALUE_2',
        xligmerori_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        maxdlvdat_0: new Date().toISOString().split('T')[0],
        uselimdat_0: new Date().toISOString().split('T')[0],
        x4hshidat_0: new Date().toISOString().split('T')[0],
        demdlvref_0: 'VALUE_2',
        rattaxlin_0: 'VALUE_2',
        oriqty_0: 21.0,
        precod_0: 'VALUE_2',
        soqseq_0: 'VALUE_2',
        poqseq_0: 'VALUE_2',
        updusr_0: 'VALUE_2',
        invqtystu_0: 21.0,
        qtystu_0: 21.0,
        sohcat_0: 'VALUE_2',
        bpcord_0: 'VALUE_2',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_2',
        alltyp_0: 'VALUE_2',
        mdl_0: 'VALUE_2',
        drn_0: 'VALUE_2',
        dlvpio_0: 'VALUE_2',
        daylti_0: 'VALUE_2',
        bpaadd_0: 'VALUE_2',
        ndeprnbom_0: 'VALUE_2',
        invprnbom_0: 'VALUE_2',
        invqty_0: 21.0,
        impnumlig_0: 'VALUE_2',
        geocod_0: 'VALUE_2',
        insctyflg_0: 'VALUE_2',
        x4qtyini_0: 21.0,
        tdlqtystu_0: 21.0,
        bastaxlin_0: 2,
        ocnprnbom_0: 'VALUE_2',
        xtext0_0: 'VALUE_2',
        xkanban_0: 'VALUE_2',
        xqteret_0: 'VALUE_2',
        oprqty_0: 21.0,
        preqty_0: 21.0,
        oprqtystu_0: 21.0,
        preqtystu_0: 21.0,
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        xnbetiimp_0: 'VALUE_2',
        xpcusauc01_0: 'VALUE_2',
        xpldeliv_0: 'VALUE_2',
        dsplinwei_0: 'VALUE_2',
        dsplinvol_0: 'VALUE_2',
        invamt_0: 21.0,
        dlvpiocmp_0: 'VALUE_2',
        lot_0: 'VALUE_2',
        sta_0: 1,
        xregroup_0: 'VALUE_2',
        loc_0: 'VALUE_2',
        mon_0: 'VALUE_2',
        sddlin_0: 'VALUE_2',
        pckcap_0: 'VALUE_2',
        yea_0: 'VALUE_2',
        pjt_0: 'VALUE_2',
        x4facture_0: 'VALUE_2',
        pck_0: 'VALUE_2',
        x4avmotcomd_0: 'VALUE_2',
        maxdlvhou_0: 'VALUE_2',
        eccvalmaj_0: 'VALUE_2',
        eccvalmin_0: 'VALUE_2',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_2',
        xpcu1itm_0: 'VALUE_2',
        xtimmes_0: new Date().toISOString(),
        xalert_0: 'VALUE_2',
        fminum_0: 'VALUE_2',
        fmilin_0: 'VALUE_2',
        fmiseq_0: 'VALUE_2',
        orddat_0: new Date().toISOString().split('T')[0],
        linordnum_0: 'VALUE_2',
        demdlvhou_0: 'VALUE_2',
        soqsta_0: 2,
        ddtanum_0: 'VALUE_2',
        ddtanot_0: 'VALUE_2',
        dlvday_0: 'VALUE_2',
        cad_0: 'VALUE_2',
        wee_0: 'VALUE_2',
        ynbcolis_0: 'VALUE_2',
        demsta_0: 2,
        shtqty_0: 21.0,
        shtqtystu_0: 21.0,
        invflg_0: 'VALUE_2',
        credat_0: new Date().toISOString().split('T')[0],
        pitflg_0: 'VALUE_2',
        cclren_0: 'VALUE_2',
        ccldat_0: new Date().toISOString().split('T')[0],
        xflgret_0: 'VALUE_2',
        dlvflg_0: 'VALUE_2',
        xcmqint_0: 'VALUE_2',
        poplin_0: 'VALUE_2',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_2',
        vtc_0: 'VALUE_2',
        taxgeoflg_0: 'VALUE_2',
        taxflg_0: 'VALUE_2',
        taxregflg_0: 'VALUE_2',
        soqtex_0: 'VALUE_2',
        sdhnum_0: 'VALUE_2',
        sohnum_0: 'VALUE_2',
        pohnum_0: 'VALUE_2',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_2',
        dlvqtystu_0: 21.0,
        perstrdat_0: new Date().toISOString().split('T')[0],
        perenddat_0: new Date().toISOString().split('T')[0],
        pernbrday_0: 'VALUE_2',
        useplc_0: 'VALUE_2',
        qty_0: 21.0,
        allqty_0: 21.0,
        cpy_0: 'VALUE_2',
        soplin_0: 'VALUE_2',
        soqseqnum_0: 'VALUE_2',
        shihou_0: 'VALUE_2',
        extdlvdat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        bptnum_0: 'VALUE_2',
        demnum_0: 'VALUE_2',
        allqtystu_0: 21.0,
        creusr_0: 'VALUE_2',
        xversion_0: 'VALUE_2',
        z01statut_0: 2,
        stofcy_0: 'VALUE_2',
        stomgtcod_0: 'VALUE_2',
        itmref_0: 'VALUE_2',
        dspvou_0: 'VALUE_2',
        dspweu_0: 'VALUE_2',
        salfcy_0: 'VALUE_2',
        tdlqty_0: 21.0,
        dlvqty_0: 21.0,
      },
      {
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_3',
        xpntmonte_0: 'VALUE_3',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xsvcemet_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        x4hdemdlvd_0: 'VALUE_3',
        odlqty_0: 31.5,
        odlqtystu_0: 31.5,
        xniveng_0: 'VALUE_3',
        xnbetiimpp_0: 'VALUE_3',
        soqpsonum_0: 'SOR0003',
        lprqtystu_0: 31.5,
        xligori_0: 'VALUE_3',
        fmi_0: 'VALUE_3',
        lprqty_0: 31.5,
        prgbilnum_0: 'VALUE_3',
        x4avmotd_0: 'VALUE_3',
        xssligori_0: 'VALUE_3',
        x4rgopl_0: 'VALUE_3',
        x4exclrfad_0: 'VALUE_3',
        xdestfin_0: 'Destination Finale 3',
        xdesint_0: 'VALUE_3',
        xligmerori_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        maxdlvdat_0: new Date().toISOString().split('T')[0],
        uselimdat_0: new Date().toISOString().split('T')[0],
        x4hshidat_0: new Date().toISOString().split('T')[0],
        demdlvref_0: 'VALUE_3',
        rattaxlin_0: 'VALUE_3',
        oriqty_0: 31.5,
        precod_0: 'VALUE_3',
        soqseq_0: 'VALUE_3',
        poqseq_0: 'VALUE_3',
        updusr_0: 'VALUE_3',
        invqtystu_0: 31.5,
        qtystu_0: 31.5,
        sohcat_0: 'VALUE_3',
        bpcord_0: 'VALUE_3',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_3',
        alltyp_0: 'VALUE_3',
        mdl_0: 'VALUE_3',
        drn_0: 'VALUE_3',
        dlvpio_0: 'VALUE_3',
        daylti_0: 'VALUE_3',
        bpaadd_0: 'VALUE_3',
        ndeprnbom_0: 'VALUE_3',
        invprnbom_0: 'VALUE_3',
        invqty_0: 31.5,
        impnumlig_0: 'VALUE_3',
        geocod_0: 'VALUE_3',
        insctyflg_0: 'VALUE_3',
        x4qtyini_0: 31.5,
        tdlqtystu_0: 31.5,
        bastaxlin_0: 3,
        ocnprnbom_0: 'VALUE_3',
        xtext0_0: 'VALUE_3',
        xkanban_0: 'VALUE_3',
        xqteret_0: 'VALUE_3',
        oprqty_0: 31.5,
        preqty_0: 31.5,
        oprqtystu_0: 31.5,
        preqtystu_0: 31.5,
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        xnbetiimp_0: 'VALUE_3',
        xpcusauc01_0: 'VALUE_3',
        xpldeliv_0: 'VALUE_3',
        dsplinwei_0: 'VALUE_3',
        dsplinvol_0: 'VALUE_3',
        invamt_0: 31.5,
        dlvpiocmp_0: 'VALUE_3',
        lot_0: 'VALUE_3',
        sta_0: 1,
        xregroup_0: 'VALUE_3',
        loc_0: 'VALUE_3',
        mon_0: 'VALUE_3',
        sddlin_0: 'VALUE_3',
        pckcap_0: 'VALUE_3',
        yea_0: 'VALUE_3',
        pjt_0: 'VALUE_3',
        x4facture_0: 'VALUE_3',
        pck_0: 'VALUE_3',
        x4avmotcomd_0: 'VALUE_3',
        maxdlvhou_0: 'VALUE_3',
        eccvalmaj_0: 'VALUE_3',
        eccvalmin_0: 'VALUE_3',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_3',
        xpcu1itm_0: 'VALUE_3',
        xtimmes_0: new Date().toISOString(),
        xalert_0: 'VALUE_3',
        fminum_0: 'VALUE_3',
        fmilin_0: 'VALUE_3',
        fmiseq_0: 'VALUE_3',
        orddat_0: new Date().toISOString().split('T')[0],
        linordnum_0: 'VALUE_3',
        demdlvhou_0: 'VALUE_3',
        soqsta_0: 3,
        ddtanum_0: 'VALUE_3',
        ddtanot_0: 'VALUE_3',
        dlvday_0: 'VALUE_3',
        cad_0: 'VALUE_3',
        wee_0: 'VALUE_3',
        ynbcolis_0: 'VALUE_3',
        demsta_0: 3,
        shtqty_0: 31.5,
        shtqtystu_0: 31.5,
        invflg_0: 'VALUE_3',
        credat_0: new Date().toISOString().split('T')[0],
        pitflg_0: 'VALUE_3',
        cclren_0: 'VALUE_3',
        ccldat_0: new Date().toISOString().split('T')[0],
        xflgret_0: 'VALUE_3',
        dlvflg_0: 'VALUE_3',
        xcmqint_0: 'VALUE_3',
        poplin_0: 'VALUE_3',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_3',
        vtc_0: 'VALUE_3',
        taxgeoflg_0: 'VALUE_3',
        taxflg_0: 'VALUE_3',
        taxregflg_0: 'VALUE_3',
        soqtex_0: 'VALUE_3',
        sdhnum_0: 'VALUE_3',
        sohnum_0: 'VALUE_3',
        pohnum_0: 'VALUE_3',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_3',
        dlvqtystu_0: 31.5,
        perstrdat_0: new Date().toISOString().split('T')[0],
        perenddat_0: new Date().toISOString().split('T')[0],
        pernbrday_0: 'VALUE_3',
        useplc_0: 'VALUE_3',
        qty_0: 31.5,
        allqty_0: 31.5,
        cpy_0: 'VALUE_3',
        soplin_0: 'VALUE_3',
        soqseqnum_0: 'VALUE_3',
        shihou_0: 'VALUE_3',
        extdlvdat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        bptnum_0: 'VALUE_3',
        demnum_0: 'VALUE_3',
        allqtystu_0: 31.5,
        creusr_0: 'VALUE_3',
        xversion_0: 'VALUE_3',
        z01statut_0: 3,
        stofcy_0: 'VALUE_3',
        stomgtcod_0: 'VALUE_3',
        itmref_0: 'VALUE_3',
        dspvou_0: 'VALUE_3',
        dspweu_0: 'VALUE_3',
        salfcy_0: 'VALUE_3',
        tdlqty_0: 31.5,
        dlvqty_0: 31.5,
      },
      {
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_4',
        xpntmonte_0: 'VALUE_4',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xsvcemet_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        x4hdemdlvd_0: 'VALUE_4',
        odlqty_0: 42.0,
        odlqtystu_0: 42.0,
        xniveng_0: 'VALUE_4',
        xnbetiimpp_0: 'VALUE_4',
        soqpsonum_0: 'SOR0004',
        lprqtystu_0: 42.0,
        xligori_0: 'VALUE_4',
        fmi_0: 'VALUE_4',
        lprqty_0: 42.0,
        prgbilnum_0: 'VALUE_4',
        x4avmotd_0: 'VALUE_4',
        xssligori_0: 'VALUE_4',
        x4rgopl_0: 'VALUE_4',
        x4exclrfad_0: 'VALUE_4',
        xdestfin_0: 'Destination Finale 4',
        xdesint_0: 'VALUE_4',
        xligmerori_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        maxdlvdat_0: new Date().toISOString().split('T')[0],
        uselimdat_0: new Date().toISOString().split('T')[0],
        x4hshidat_0: new Date().toISOString().split('T')[0],
        demdlvref_0: 'VALUE_4',
        rattaxlin_0: 'VALUE_4',
        oriqty_0: 42.0,
        precod_0: 'VALUE_4',
        soqseq_0: 'VALUE_4',
        poqseq_0: 'VALUE_4',
        updusr_0: 'VALUE_4',
        invqtystu_0: 42.0,
        qtystu_0: 42.0,
        sohcat_0: 'VALUE_4',
        bpcord_0: 'VALUE_4',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_4',
        alltyp_0: 'VALUE_4',
        mdl_0: 'VALUE_4',
        drn_0: 'VALUE_4',
        dlvpio_0: 'VALUE_4',
        daylti_0: 'VALUE_4',
        bpaadd_0: 'VALUE_4',
        ndeprnbom_0: 'VALUE_4',
        invprnbom_0: 'VALUE_4',
        invqty_0: 42.0,
        impnumlig_0: 'VALUE_4',
        geocod_0: 'VALUE_4',
        insctyflg_0: 'VALUE_4',
        x4qtyini_0: 42.0,
        tdlqtystu_0: 42.0,
        bastaxlin_0: 4,
        ocnprnbom_0: 'VALUE_4',
        xtext0_0: 'VALUE_4',
        xkanban_0: 'VALUE_4',
        xqteret_0: 'VALUE_4',
        oprqty_0: 42.0,
        preqty_0: 42.0,
        oprqtystu_0: 42.0,
        preqtystu_0: 42.0,
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        xnbetiimp_0: 'VALUE_4',
        xpcusauc01_0: 'VALUE_4',
        xpldeliv_0: 'VALUE_4',
        dsplinwei_0: 'VALUE_4',
        dsplinvol_0: 'VALUE_4',
        invamt_0: 42.0,
        dlvpiocmp_0: 'VALUE_4',
        lot_0: 'VALUE_4',
        sta_0: 1,
        xregroup_0: 'VALUE_4',
        loc_0: 'VALUE_4',
        mon_0: 'VALUE_4',
        sddlin_0: 'VALUE_4',
        pckcap_0: 'VALUE_4',
        yea_0: 'VALUE_4',
        pjt_0: 'VALUE_4',
        x4facture_0: 'VALUE_4',
        pck_0: 'VALUE_4',
        x4avmotcomd_0: 'VALUE_4',
        maxdlvhou_0: 'VALUE_4',
        eccvalmaj_0: 'VALUE_4',
        eccvalmin_0: 'VALUE_4',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_4',
        xpcu1itm_0: 'VALUE_4',
        xtimmes_0: new Date().toISOString(),
        xalert_0: 'VALUE_4',
        fminum_0: 'VALUE_4',
        fmilin_0: 'VALUE_4',
        fmiseq_0: 'VALUE_4',
        orddat_0: new Date().toISOString().split('T')[0],
        linordnum_0: 'VALUE_4',
        demdlvhou_0: 'VALUE_4',
        soqsta_0: 4,
        ddtanum_0: 'VALUE_4',
        ddtanot_0: 'VALUE_4',
        dlvday_0: 'VALUE_4',
        cad_0: 'VALUE_4',
        wee_0: 'VALUE_4',
        ynbcolis_0: 'VALUE_4',
        demsta_0: 4,
        shtqty_0: 42.0,
        shtqtystu_0: 42.0,
        invflg_0: 'VALUE_4',
        credat_0: new Date().toISOString().split('T')[0],
        pitflg_0: 'VALUE_4',
        cclren_0: 'VALUE_4',
        ccldat_0: new Date().toISOString().split('T')[0],
        xflgret_0: 'VALUE_4',
        dlvflg_0: 'VALUE_4',
        xcmqint_0: 'VALUE_4',
        poplin_0: 'VALUE_4',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_4',
        vtc_0: 'VALUE_4',
        taxgeoflg_0: 'VALUE_4',
        taxflg_0: 'VALUE_4',
        taxregflg_0: 'VALUE_4',
        soqtex_0: 'VALUE_4',
        sdhnum_0: 'VALUE_4',
        sohnum_0: 'VALUE_4',
        pohnum_0: 'VALUE_4',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_4',
        dlvqtystu_0: 42.0,
        perstrdat_0: new Date().toISOString().split('T')[0],
        perenddat_0: new Date().toISOString().split('T')[0],
        pernbrday_0: 'VALUE_4',
        useplc_0: 'VALUE_4',
        qty_0: 42.0,
        allqty_0: 42.0,
        cpy_0: 'VALUE_4',
        soplin_0: 'VALUE_4',
        soqseqnum_0: 'VALUE_4',
        shihou_0: 'VALUE_4',
        extdlvdat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        bptnum_0: 'VALUE_4',
        demnum_0: 'VALUE_4',
        allqtystu_0: 42.0,
        creusr_0: 'VALUE_4',
        xversion_0: 'VALUE_4',
        z01statut_0: 4,
        stofcy_0: 'VALUE_4',
        stomgtcod_0: 'VALUE_4',
        itmref_0: 'VALUE_4',
        dspvou_0: 'VALUE_4',
        dspweu_0: 'VALUE_4',
        salfcy_0: 'VALUE_4',
        tdlqty_0: 42.0,
        dlvqty_0: 42.0,
      },
      {
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_5',
        xpntmonte_0: 'VALUE_5',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xsvcemet_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        x4hdemdlvd_0: 'VALUE_5',
        odlqty_0: 52.5,
        odlqtystu_0: 52.5,
        xniveng_0: 'VALUE_5',
        xnbetiimpp_0: 'VALUE_5',
        soqpsonum_0: 'SOR0005',
        lprqtystu_0: 52.5,
        xligori_0: 'VALUE_5',
        fmi_0: 'VALUE_5',
        lprqty_0: 52.5,
        prgbilnum_0: 'VALUE_5',
        x4avmotd_0: 'VALUE_5',
        xssligori_0: 'VALUE_5',
        x4rgopl_0: 'VALUE_5',
        x4exclrfad_0: 'VALUE_5',
        xdestfin_0: 'Destination Finale 5',
        xdesint_0: 'VALUE_5',
        xligmerori_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        maxdlvdat_0: new Date().toISOString().split('T')[0],
        uselimdat_0: new Date().toISOString().split('T')[0],
        x4hshidat_0: new Date().toISOString().split('T')[0],
        demdlvref_0: 'VALUE_5',
        rattaxlin_0: 'VALUE_5',
        oriqty_0: 52.5,
        precod_0: 'VALUE_5',
        soqseq_0: 'VALUE_5',
        poqseq_0: 'VALUE_5',
        updusr_0: 'VALUE_5',
        invqtystu_0: 52.5,
        qtystu_0: 52.5,
        sohcat_0: 'VALUE_5',
        bpcord_0: 'VALUE_5',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_5',
        alltyp_0: 'VALUE_5',
        mdl_0: 'VALUE_5',
        drn_0: 'VALUE_5',
        dlvpio_0: 'VALUE_5',
        daylti_0: 'VALUE_5',
        bpaadd_0: 'VALUE_5',
        ndeprnbom_0: 'VALUE_5',
        invprnbom_0: 'VALUE_5',
        invqty_0: 52.5,
        impnumlig_0: 'VALUE_5',
        geocod_0: 'VALUE_5',
        insctyflg_0: 'VALUE_5',
        x4qtyini_0: 52.5,
        tdlqtystu_0: 52.5,
        bastaxlin_0: 5,
        ocnprnbom_0: 'VALUE_5',
        xtext0_0: 'VALUE_5',
        xkanban_0: 'VALUE_5',
        xqteret_0: 'VALUE_5',
        oprqty_0: 52.5,
        preqty_0: 52.5,
        oprqtystu_0: 52.5,
        preqtystu_0: 52.5,
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        xnbetiimp_0: 'VALUE_5',
        xpcusauc01_0: 'VALUE_5',
        xpldeliv_0: 'VALUE_5',
        dsplinwei_0: 'VALUE_5',
        dsplinvol_0: 'VALUE_5',
        invamt_0: 52.5,
        dlvpiocmp_0: 'VALUE_5',
        lot_0: 'VALUE_5',
        sta_0: 1,
        xregroup_0: 'VALUE_5',
        loc_0: 'VALUE_5',
        mon_0: 'VALUE_5',
        sddlin_0: 'VALUE_5',
        pckcap_0: 'VALUE_5',
        yea_0: 'VALUE_5',
        pjt_0: 'VALUE_5',
        x4facture_0: 'VALUE_5',
        pck_0: 'VALUE_5',
        x4avmotcomd_0: 'VALUE_5',
        maxdlvhou_0: 'VALUE_5',
        eccvalmaj_0: 'VALUE_5',
        eccvalmin_0: 'VALUE_5',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_5',
        xpcu1itm_0: 'VALUE_5',
        xtimmes_0: new Date().toISOString(),
        xalert_0: 'VALUE_5',
        fminum_0: 'VALUE_5',
        fmilin_0: 'VALUE_5',
        fmiseq_0: 'VALUE_5',
        orddat_0: new Date().toISOString().split('T')[0],
        linordnum_0: 'VALUE_5',
        demdlvhou_0: 'VALUE_5',
        soqsta_0: 5,
        ddtanum_0: 'VALUE_5',
        ddtanot_0: 'VALUE_5',
        dlvday_0: 'VALUE_5',
        cad_0: 'VALUE_5',
        wee_0: 'VALUE_5',
        ynbcolis_0: 'VALUE_5',
        demsta_0: 5,
        shtqty_0: 52.5,
        shtqtystu_0: 52.5,
        invflg_0: 'VALUE_5',
        credat_0: new Date().toISOString().split('T')[0],
        pitflg_0: 'VALUE_5',
        cclren_0: 'VALUE_5',
        ccldat_0: new Date().toISOString().split('T')[0],
        xflgret_0: 'VALUE_5',
        dlvflg_0: 'VALUE_5',
        xcmqint_0: 'VALUE_5',
        poplin_0: 'VALUE_5',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_5',
        vtc_0: 'VALUE_5',
        taxgeoflg_0: 'VALUE_5',
        taxflg_0: 'VALUE_5',
        taxregflg_0: 'VALUE_5',
        soqtex_0: 'VALUE_5',
        sdhnum_0: 'VALUE_5',
        sohnum_0: 'VALUE_5',
        pohnum_0: 'VALUE_5',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_5',
        dlvqtystu_0: 52.5,
        perstrdat_0: new Date().toISOString().split('T')[0],
        perenddat_0: new Date().toISOString().split('T')[0],
        pernbrday_0: 'VALUE_5',
        useplc_0: 'VALUE_5',
        qty_0: 52.5,
        allqty_0: 52.5,
        cpy_0: 'VALUE_5',
        soplin_0: 'VALUE_5',
        soqseqnum_0: 'VALUE_5',
        shihou_0: 'VALUE_5',
        extdlvdat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        bptnum_0: 'VALUE_5',
        demnum_0: 'VALUE_5',
        allqtystu_0: 52.5,
        creusr_0: 'VALUE_5',
        xversion_0: 'VALUE_5',
        z01statut_0: 5,
        stofcy_0: 'VALUE_5',
        stomgtcod_0: 'VALUE_5',
        itmref_0: 'VALUE_5',
        dspvou_0: 'VALUE_5',
        dspweu_0: 'VALUE_5',
        salfcy_0: 'VALUE_5',
        tdlqty_0: 52.5,
        dlvqty_0: 52.5,
      },
      {
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_6',
        xpntmonte_0: 'VALUE_6',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xsvcemet_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        x4hdemdlvd_0: 'VALUE_6',
        odlqty_0: 63.0,
        odlqtystu_0: 63.0,
        xniveng_0: 'VALUE_6',
        xnbetiimpp_0: 'VALUE_6',
        soqpsonum_0: 'SOR0006',
        lprqtystu_0: 63.0,
        xligori_0: 'VALUE_6',
        fmi_0: 'VALUE_6',
        lprqty_0: 63.0,
        prgbilnum_0: 'VALUE_6',
        x4avmotd_0: 'VALUE_6',
        xssligori_0: 'VALUE_6',
        x4rgopl_0: 'VALUE_6',
        x4exclrfad_0: 'VALUE_6',
        xdestfin_0: 'Destination Finale 6',
        xdesint_0: 'VALUE_6',
        xligmerori_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        maxdlvdat_0: new Date().toISOString().split('T')[0],
        uselimdat_0: new Date().toISOString().split('T')[0],
        x4hshidat_0: new Date().toISOString().split('T')[0],
        demdlvref_0: 'VALUE_6',
        rattaxlin_0: 'VALUE_6',
        oriqty_0: 63.0,
        precod_0: 'VALUE_6',
        soqseq_0: 'VALUE_6',
        poqseq_0: 'VALUE_6',
        updusr_0: 'VALUE_6',
        invqtystu_0: 63.0,
        qtystu_0: 63.0,
        sohcat_0: 'VALUE_6',
        bpcord_0: 'VALUE_6',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_6',
        alltyp_0: 'VALUE_6',
        mdl_0: 'VALUE_6',
        drn_0: 'VALUE_6',
        dlvpio_0: 'VALUE_6',
        daylti_0: 'VALUE_6',
        bpaadd_0: 'VALUE_6',
        ndeprnbom_0: 'VALUE_6',
        invprnbom_0: 'VALUE_6',
        invqty_0: 63.0,
        impnumlig_0: 'VALUE_6',
        geocod_0: 'VALUE_6',
        insctyflg_0: 'VALUE_6',
        x4qtyini_0: 63.0,
        tdlqtystu_0: 63.0,
        bastaxlin_0: 6,
        ocnprnbom_0: 'VALUE_6',
        xtext0_0: 'VALUE_6',
        xkanban_0: 'VALUE_6',
        xqteret_0: 'VALUE_6',
        oprqty_0: 63.0,
        preqty_0: 63.0,
        oprqtystu_0: 63.0,
        preqtystu_0: 63.0,
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        xnbetiimp_0: 'VALUE_6',
        xpcusauc01_0: 'VALUE_6',
        xpldeliv_0: 'VALUE_6',
        dsplinwei_0: 'VALUE_6',
        dsplinvol_0: 'VALUE_6',
        invamt_0: 63.0,
        dlvpiocmp_0: 'VALUE_6',
        lot_0: 'VALUE_6',
        sta_0: 1,
        xregroup_0: 'VALUE_6',
        loc_0: 'VALUE_6',
        mon_0: 'VALUE_6',
        sddlin_0: 'VALUE_6',
        pckcap_0: 'VALUE_6',
        yea_0: 'VALUE_6',
        pjt_0: 'VALUE_6',
        x4facture_0: 'VALUE_6',
        pck_0: 'VALUE_6',
        x4avmotcomd_0: 'VALUE_6',
        maxdlvhou_0: 'VALUE_6',
        eccvalmaj_0: 'VALUE_6',
        eccvalmin_0: 'VALUE_6',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_6',
        xpcu1itm_0: 'VALUE_6',
        xtimmes_0: new Date().toISOString(),
        xalert_0: 'VALUE_6',
        fminum_0: 'VALUE_6',
        fmilin_0: 'VALUE_6',
        fmiseq_0: 'VALUE_6',
        orddat_0: new Date().toISOString().split('T')[0],
        linordnum_0: 'VALUE_6',
        demdlvhou_0: 'VALUE_6',
        soqsta_0: 6,
        ddtanum_0: 'VALUE_6',
        ddtanot_0: 'VALUE_6',
        dlvday_0: 'VALUE_6',
        cad_0: 'VALUE_6',
        wee_0: 'VALUE_6',
        ynbcolis_0: 'VALUE_6',
        demsta_0: 6,
        shtqty_0: 63.0,
        shtqtystu_0: 63.0,
        invflg_0: 'VALUE_6',
        credat_0: new Date().toISOString().split('T')[0],
        pitflg_0: 'VALUE_6',
        cclren_0: 'VALUE_6',
        ccldat_0: new Date().toISOString().split('T')[0],
        xflgret_0: 'VALUE_6',
        dlvflg_0: 'VALUE_6',
        xcmqint_0: 'VALUE_6',
        poplin_0: 'VALUE_6',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_6',
        vtc_0: 'VALUE_6',
        taxgeoflg_0: 'VALUE_6',
        taxflg_0: 'VALUE_6',
        taxregflg_0: 'VALUE_6',
        soqtex_0: 'VALUE_6',
        sdhnum_0: 'VALUE_6',
        sohnum_0: 'VALUE_6',
        pohnum_0: 'VALUE_6',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_6',
        dlvqtystu_0: 63.0,
        perstrdat_0: new Date().toISOString().split('T')[0],
        perenddat_0: new Date().toISOString().split('T')[0],
        pernbrday_0: 'VALUE_6',
        useplc_0: 'VALUE_6',
        qty_0: 63.0,
        allqty_0: 63.0,
        cpy_0: 'VALUE_6',
        soplin_0: 'VALUE_6',
        soqseqnum_0: 'VALUE_6',
        shihou_0: 'VALUE_6',
        extdlvdat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        bptnum_0: 'VALUE_6',
        demnum_0: 'VALUE_6',
        allqtystu_0: 63.0,
        creusr_0: 'VALUE_6',
        xversion_0: 'VALUE_6',
        z01statut_0: 6,
        stofcy_0: 'VALUE_6',
        stomgtcod_0: 'VALUE_6',
        itmref_0: 'VALUE_6',
        dspvou_0: 'VALUE_6',
        dspweu_0: 'VALUE_6',
        salfcy_0: 'VALUE_6',
        tdlqty_0: 63.0,
        dlvqty_0: 63.0,
      },
      {
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_7',
        xpntmonte_0: 'VALUE_7',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xsvcemet_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        x4hdemdlvd_0: 'VALUE_7',
        odlqty_0: 73.5,
        odlqtystu_0: 73.5,
        xniveng_0: 'VALUE_7',
        xnbetiimpp_0: 'VALUE_7',
        soqpsonum_0: 'SOR0007',
        lprqtystu_0: 73.5,
        xligori_0: 'VALUE_7',
        fmi_0: 'VALUE_7',
        lprqty_0: 73.5,
        prgbilnum_0: 'VALUE_7',
        x4avmotd_0: 'VALUE_7',
        xssligori_0: 'VALUE_7',
        x4rgopl_0: 'VALUE_7',
        x4exclrfad_0: 'VALUE_7',
        xdestfin_0: 'Destination Finale 7',
        xdesint_0: 'VALUE_7',
        xligmerori_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        maxdlvdat_0: new Date().toISOString().split('T')[0],
        uselimdat_0: new Date().toISOString().split('T')[0],
        x4hshidat_0: new Date().toISOString().split('T')[0],
        demdlvref_0: 'VALUE_7',
        rattaxlin_0: 'VALUE_7',
        oriqty_0: 73.5,
        precod_0: 'VALUE_7',
        soqseq_0: 'VALUE_7',
        poqseq_0: 'VALUE_7',
        updusr_0: 'VALUE_7',
        invqtystu_0: 73.5,
        qtystu_0: 73.5,
        sohcat_0: 'VALUE_7',
        bpcord_0: 'VALUE_7',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_7',
        alltyp_0: 'VALUE_7',
        mdl_0: 'VALUE_7',
        drn_0: 'VALUE_7',
        dlvpio_0: 'VALUE_7',
        daylti_0: 'VALUE_7',
        bpaadd_0: 'VALUE_7',
        ndeprnbom_0: 'VALUE_7',
        invprnbom_0: 'VALUE_7',
        invqty_0: 73.5,
        impnumlig_0: 'VALUE_7',
        geocod_0: 'VALUE_7',
        insctyflg_0: 'VALUE_7',
        x4qtyini_0: 73.5,
        tdlqtystu_0: 73.5,
        bastaxlin_0: 7,
        ocnprnbom_0: 'VALUE_7',
        xtext0_0: 'VALUE_7',
        xkanban_0: 'VALUE_7',
        xqteret_0: 'VALUE_7',
        oprqty_0: 73.5,
        preqty_0: 73.5,
        oprqtystu_0: 73.5,
        preqtystu_0: 73.5,
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        xnbetiimp_0: 'VALUE_7',
        xpcusauc01_0: 'VALUE_7',
        xpldeliv_0: 'VALUE_7',
        dsplinwei_0: 'VALUE_7',
        dsplinvol_0: 'VALUE_7',
        invamt_0: 73.5,
        dlvpiocmp_0: 'VALUE_7',
        lot_0: 'VALUE_7',
        sta_0: 1,
        xregroup_0: 'VALUE_7',
        loc_0: 'VALUE_7',
        mon_0: 'VALUE_7',
        sddlin_0: 'VALUE_7',
        pckcap_0: 'VALUE_7',
        yea_0: 'VALUE_7',
        pjt_0: 'VALUE_7',
        x4facture_0: 'VALUE_7',
        pck_0: 'VALUE_7',
        x4avmotcomd_0: 'VALUE_7',
        maxdlvhou_0: 'VALUE_7',
        eccvalmaj_0: 'VALUE_7',
        eccvalmin_0: 'VALUE_7',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_7',
        xpcu1itm_0: 'VALUE_7',
        xtimmes_0: new Date().toISOString(),
        xalert_0: 'VALUE_7',
        fminum_0: 'VALUE_7',
        fmilin_0: 'VALUE_7',
        fmiseq_0: 'VALUE_7',
        orddat_0: new Date().toISOString().split('T')[0],
        linordnum_0: 'VALUE_7',
        demdlvhou_0: 'VALUE_7',
        soqsta_0: 7,
        ddtanum_0: 'VALUE_7',
        ddtanot_0: 'VALUE_7',
        dlvday_0: 'VALUE_7',
        cad_0: 'VALUE_7',
        wee_0: 'VALUE_7',
        ynbcolis_0: 'VALUE_7',
        demsta_0: 7,
        shtqty_0: 73.5,
        shtqtystu_0: 73.5,
        invflg_0: 'VALUE_7',
        credat_0: new Date().toISOString().split('T')[0],
        pitflg_0: 'VALUE_7',
        cclren_0: 'VALUE_7',
        ccldat_0: new Date().toISOString().split('T')[0],
        xflgret_0: 'VALUE_7',
        dlvflg_0: 'VALUE_7',
        xcmqint_0: 'VALUE_7',
        poplin_0: 'VALUE_7',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_7',
        vtc_0: 'VALUE_7',
        taxgeoflg_0: 'VALUE_7',
        taxflg_0: 'VALUE_7',
        taxregflg_0: 'VALUE_7',
        soqtex_0: 'VALUE_7',
        sdhnum_0: 'VALUE_7',
        sohnum_0: 'VALUE_7',
        pohnum_0: 'VALUE_7',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_7',
        dlvqtystu_0: 73.5,
        perstrdat_0: new Date().toISOString().split('T')[0],
        perenddat_0: new Date().toISOString().split('T')[0],
        pernbrday_0: 'VALUE_7',
        useplc_0: 'VALUE_7',
        qty_0: 73.5,
        allqty_0: 73.5,
        cpy_0: 'VALUE_7',
        soplin_0: 'VALUE_7',
        soqseqnum_0: 'VALUE_7',
        shihou_0: 'VALUE_7',
        extdlvdat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        bptnum_0: 'VALUE_7',
        demnum_0: 'VALUE_7',
        allqtystu_0: 73.5,
        creusr_0: 'VALUE_7',
        xversion_0: 'VALUE_7',
        z01statut_0: 7,
        stofcy_0: 'VALUE_7',
        stomgtcod_0: 'VALUE_7',
        itmref_0: 'VALUE_7',
        dspvou_0: 'VALUE_7',
        dspweu_0: 'VALUE_7',
        salfcy_0: 'VALUE_7',
        tdlqty_0: 73.5,
        dlvqty_0: 73.5,
      },
      {
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_8',
        xpntmonte_0: 'VALUE_8',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xsvcemet_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        x4hdemdlvd_0: 'VALUE_8',
        odlqty_0: 84.0,
        odlqtystu_0: 84.0,
        xniveng_0: 'VALUE_8',
        xnbetiimpp_0: 'VALUE_8',
        soqpsonum_0: 'SOR0008',
        lprqtystu_0: 84.0,
        xligori_0: 'VALUE_8',
        fmi_0: 'VALUE_8',
        lprqty_0: 84.0,
        prgbilnum_0: 'VALUE_8',
        x4avmotd_0: 'VALUE_8',
        xssligori_0: 'VALUE_8',
        x4rgopl_0: 'VALUE_8',
        x4exclrfad_0: 'VALUE_8',
        xdestfin_0: 'Destination Finale 8',
        xdesint_0: 'VALUE_8',
        xligmerori_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        maxdlvdat_0: new Date().toISOString().split('T')[0],
        uselimdat_0: new Date().toISOString().split('T')[0],
        x4hshidat_0: new Date().toISOString().split('T')[0],
        demdlvref_0: 'VALUE_8',
        rattaxlin_0: 'VALUE_8',
        oriqty_0: 84.0,
        precod_0: 'VALUE_8',
        soqseq_0: 'VALUE_8',
        poqseq_0: 'VALUE_8',
        updusr_0: 'VALUE_8',
        invqtystu_0: 84.0,
        qtystu_0: 84.0,
        sohcat_0: 'VALUE_8',
        bpcord_0: 'VALUE_8',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_8',
        alltyp_0: 'VALUE_8',
        mdl_0: 'VALUE_8',
        drn_0: 'VALUE_8',
        dlvpio_0: 'VALUE_8',
        daylti_0: 'VALUE_8',
        bpaadd_0: 'VALUE_8',
        ndeprnbom_0: 'VALUE_8',
        invprnbom_0: 'VALUE_8',
        invqty_0: 84.0,
        impnumlig_0: 'VALUE_8',
        geocod_0: 'VALUE_8',
        insctyflg_0: 'VALUE_8',
        x4qtyini_0: 84.0,
        tdlqtystu_0: 84.0,
        bastaxlin_0: 8,
        ocnprnbom_0: 'VALUE_8',
        xtext0_0: 'VALUE_8',
        xkanban_0: 'VALUE_8',
        xqteret_0: 'VALUE_8',
        oprqty_0: 84.0,
        preqty_0: 84.0,
        oprqtystu_0: 84.0,
        preqtystu_0: 84.0,
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        xnbetiimp_0: 'VALUE_8',
        xpcusauc01_0: 'VALUE_8',
        xpldeliv_0: 'VALUE_8',
        dsplinwei_0: 'VALUE_8',
        dsplinvol_0: 'VALUE_8',
        invamt_0: 84.0,
        dlvpiocmp_0: 'VALUE_8',
        lot_0: 'VALUE_8',
        sta_0: 1,
        xregroup_0: 'VALUE_8',
        loc_0: 'VALUE_8',
        mon_0: 'VALUE_8',
        sddlin_0: 'VALUE_8',
        pckcap_0: 'VALUE_8',
        yea_0: 'VALUE_8',
        pjt_0: 'VALUE_8',
        x4facture_0: 'VALUE_8',
        pck_0: 'VALUE_8',
        x4avmotcomd_0: 'VALUE_8',
        maxdlvhou_0: 'VALUE_8',
        eccvalmaj_0: 'VALUE_8',
        eccvalmin_0: 'VALUE_8',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_8',
        xpcu1itm_0: 'VALUE_8',
        xtimmes_0: new Date().toISOString(),
        xalert_0: 'VALUE_8',
        fminum_0: 'VALUE_8',
        fmilin_0: 'VALUE_8',
        fmiseq_0: 'VALUE_8',
        orddat_0: new Date().toISOString().split('T')[0],
        linordnum_0: 'VALUE_8',
        demdlvhou_0: 'VALUE_8',
        soqsta_0: 8,
        ddtanum_0: 'VALUE_8',
        ddtanot_0: 'VALUE_8',
        dlvday_0: 'VALUE_8',
        cad_0: 'VALUE_8',
        wee_0: 'VALUE_8',
        ynbcolis_0: 'VALUE_8',
        demsta_0: 8,
        shtqty_0: 84.0,
        shtqtystu_0: 84.0,
        invflg_0: 'VALUE_8',
        credat_0: new Date().toISOString().split('T')[0],
        pitflg_0: 'VALUE_8',
        cclren_0: 'VALUE_8',
        ccldat_0: new Date().toISOString().split('T')[0],
        xflgret_0: 'VALUE_8',
        dlvflg_0: 'VALUE_8',
        xcmqint_0: 'VALUE_8',
        poplin_0: 'VALUE_8',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_8',
        vtc_0: 'VALUE_8',
        taxgeoflg_0: 'VALUE_8',
        taxflg_0: 'VALUE_8',
        taxregflg_0: 'VALUE_8',
        soqtex_0: 'VALUE_8',
        sdhnum_0: 'VALUE_8',
        sohnum_0: 'VALUE_8',
        pohnum_0: 'VALUE_8',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_8',
        dlvqtystu_0: 84.0,
        perstrdat_0: new Date().toISOString().split('T')[0],
        perenddat_0: new Date().toISOString().split('T')[0],
        pernbrday_0: 'VALUE_8',
        useplc_0: 'VALUE_8',
        qty_0: 84.0,
        allqty_0: 84.0,
        cpy_0: 'VALUE_8',
        soplin_0: 'VALUE_8',
        soqseqnum_0: 'VALUE_8',
        shihou_0: 'VALUE_8',
        extdlvdat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        bptnum_0: 'VALUE_8',
        demnum_0: 'VALUE_8',
        allqtystu_0: 84.0,
        creusr_0: 'VALUE_8',
        xversion_0: 'VALUE_8',
        z01statut_0: 8,
        stofcy_0: 'VALUE_8',
        stomgtcod_0: 'VALUE_8',
        itmref_0: 'VALUE_8',
        dspvou_0: 'VALUE_8',
        dspweu_0: 'VALUE_8',
        salfcy_0: 'VALUE_8',
        tdlqty_0: 84.0,
        dlvqty_0: 84.0,
      },
      {
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_9',
        xpntmonte_0: 'VALUE_9',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xsvcemet_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        x4hdemdlvd_0: 'VALUE_9',
        odlqty_0: 94.5,
        odlqtystu_0: 94.5,
        xniveng_0: 'VALUE_9',
        xnbetiimpp_0: 'VALUE_9',
        soqpsonum_0: 'SOR0009',
        lprqtystu_0: 94.5,
        xligori_0: 'VALUE_9',
        fmi_0: 'VALUE_9',
        lprqty_0: 94.5,
        prgbilnum_0: 'VALUE_9',
        x4avmotd_0: 'VALUE_9',
        xssligori_0: 'VALUE_9',
        x4rgopl_0: 'VALUE_9',
        x4exclrfad_0: 'VALUE_9',
        xdestfin_0: 'Destination Finale 9',
        xdesint_0: 'VALUE_9',
        xligmerori_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        maxdlvdat_0: new Date().toISOString().split('T')[0],
        uselimdat_0: new Date().toISOString().split('T')[0],
        x4hshidat_0: new Date().toISOString().split('T')[0],
        demdlvref_0: 'VALUE_9',
        rattaxlin_0: 'VALUE_9',
        oriqty_0: 94.5,
        precod_0: 'VALUE_9',
        soqseq_0: 'VALUE_9',
        poqseq_0: 'VALUE_9',
        updusr_0: 'VALUE_9',
        invqtystu_0: 94.5,
        qtystu_0: 94.5,
        sohcat_0: 'VALUE_9',
        bpcord_0: 'VALUE_9',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_9',
        alltyp_0: 'VALUE_9',
        mdl_0: 'VALUE_9',
        drn_0: 'VALUE_9',
        dlvpio_0: 'VALUE_9',
        daylti_0: 'VALUE_9',
        bpaadd_0: 'VALUE_9',
        ndeprnbom_0: 'VALUE_9',
        invprnbom_0: 'VALUE_9',
        invqty_0: 94.5,
        impnumlig_0: 'VALUE_9',
        geocod_0: 'VALUE_9',
        insctyflg_0: 'VALUE_9',
        x4qtyini_0: 94.5,
        tdlqtystu_0: 94.5,
        bastaxlin_0: 9,
        ocnprnbom_0: 'VALUE_9',
        xtext0_0: 'VALUE_9',
        xkanban_0: 'VALUE_9',
        xqteret_0: 'VALUE_9',
        oprqty_0: 94.5,
        preqty_0: 94.5,
        oprqtystu_0: 94.5,
        preqtystu_0: 94.5,
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        xnbetiimp_0: 'VALUE_9',
        xpcusauc01_0: 'VALUE_9',
        xpldeliv_0: 'VALUE_9',
        dsplinwei_0: 'VALUE_9',
        dsplinvol_0: 'VALUE_9',
        invamt_0: 94.5,
        dlvpiocmp_0: 'VALUE_9',
        lot_0: 'VALUE_9',
        sta_0: 1,
        xregroup_0: 'VALUE_9',
        loc_0: 'VALUE_9',
        mon_0: 'VALUE_9',
        sddlin_0: 'VALUE_9',
        pckcap_0: 'VALUE_9',
        yea_0: 'VALUE_9',
        pjt_0: 'VALUE_9',
        x4facture_0: 'VALUE_9',
        pck_0: 'VALUE_9',
        x4avmotcomd_0: 'VALUE_9',
        maxdlvhou_0: 'VALUE_9',
        eccvalmaj_0: 'VALUE_9',
        eccvalmin_0: 'VALUE_9',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_9',
        xpcu1itm_0: 'VALUE_9',
        xtimmes_0: new Date().toISOString(),
        xalert_0: 'VALUE_9',
        fminum_0: 'VALUE_9',
        fmilin_0: 'VALUE_9',
        fmiseq_0: 'VALUE_9',
        orddat_0: new Date().toISOString().split('T')[0],
        linordnum_0: 'VALUE_9',
        demdlvhou_0: 'VALUE_9',
        soqsta_0: 9,
        ddtanum_0: 'VALUE_9',
        ddtanot_0: 'VALUE_9',
        dlvday_0: 'VALUE_9',
        cad_0: 'VALUE_9',
        wee_0: 'VALUE_9',
        ynbcolis_0: 'VALUE_9',
        demsta_0: 9,
        shtqty_0: 94.5,
        shtqtystu_0: 94.5,
        invflg_0: 'VALUE_9',
        credat_0: new Date().toISOString().split('T')[0],
        pitflg_0: 'VALUE_9',
        cclren_0: 'VALUE_9',
        ccldat_0: new Date().toISOString().split('T')[0],
        xflgret_0: 'VALUE_9',
        dlvflg_0: 'VALUE_9',
        xcmqint_0: 'VALUE_9',
        poplin_0: 'VALUE_9',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_9',
        vtc_0: 'VALUE_9',
        taxgeoflg_0: 'VALUE_9',
        taxflg_0: 'VALUE_9',
        taxregflg_0: 'VALUE_9',
        soqtex_0: 'VALUE_9',
        sdhnum_0: 'VALUE_9',
        sohnum_0: 'VALUE_9',
        pohnum_0: 'VALUE_9',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_9',
        dlvqtystu_0: 94.5,
        perstrdat_0: new Date().toISOString().split('T')[0],
        perenddat_0: new Date().toISOString().split('T')[0],
        pernbrday_0: 'VALUE_9',
        useplc_0: 'VALUE_9',
        qty_0: 94.5,
        allqty_0: 94.5,
        cpy_0: 'VALUE_9',
        soplin_0: 'VALUE_9',
        soqseqnum_0: 'VALUE_9',
        shihou_0: 'VALUE_9',
        extdlvdat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        bptnum_0: 'VALUE_9',
        demnum_0: 'VALUE_9',
        allqtystu_0: 94.5,
        creusr_0: 'VALUE_9',
        xversion_0: 'VALUE_9',
        z01statut_0: 9,
        stofcy_0: 'VALUE_9',
        stomgtcod_0: 'VALUE_9',
        itmref_0: 'VALUE_9',
        dspvou_0: 'VALUE_9',
        dspweu_0: 'VALUE_9',
        salfcy_0: 'VALUE_9',
        tdlqty_0: 94.5,
        dlvqty_0: 94.5,
      },
      {
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_10',
        xpntmonte_0: 'VALUE_10',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xsvcemet_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        x4hdemdlvd_0: 'VALUE_10',
        odlqty_0: 105.0,
        odlqtystu_0: 105.0,
        xniveng_0: 'VALUE_10',
        xnbetiimpp_0: 'VALUE_10',
        soqpsonum_0: 'SOR0010',
        lprqtystu_0: 105.0,
        xligori_0: 'VALUE_10',
        fmi_0: 'VALUE_10',
        lprqty_0: 105.0,
        prgbilnum_0: 'VALUE_10',
        x4avmotd_0: 'VALUE_10',
        xssligori_0: 'VALUE_10',
        x4rgopl_0: 'VALUE_10',
        x4exclrfad_0: 'VALUE_10',
        xdestfin_0: 'Destination Finale 10',
        xdesint_0: 'VALUE_10',
        xligmerori_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        maxdlvdat_0: new Date().toISOString().split('T')[0],
        uselimdat_0: new Date().toISOString().split('T')[0],
        x4hshidat_0: new Date().toISOString().split('T')[0],
        demdlvref_0: 'VALUE_10',
        rattaxlin_0: 'VALUE_10',
        oriqty_0: 105.0,
        precod_0: 'VALUE_10',
        soqseq_0: 'VALUE_10',
        poqseq_0: 'VALUE_10',
        updusr_0: 'VALUE_10',
        invqtystu_0: 105.0,
        qtystu_0: 105.0,
        sohcat_0: 'VALUE_10',
        bpcord_0: 'VALUE_10',
        demdlvdat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_10',
        alltyp_0: 'VALUE_10',
        mdl_0: 'VALUE_10',
        drn_0: 'VALUE_10',
        dlvpio_0: 'VALUE_10',
        daylti_0: 'VALUE_10',
        bpaadd_0: 'VALUE_10',
        ndeprnbom_0: 'VALUE_10',
        invprnbom_0: 'VALUE_10',
        invqty_0: 105.0,
        impnumlig_0: 'VALUE_10',
        geocod_0: 'VALUE_10',
        insctyflg_0: 'VALUE_10',
        x4qtyini_0: 105.0,
        tdlqtystu_0: 105.0,
        bastaxlin_0: 10,
        ocnprnbom_0: 'VALUE_10',
        xtext0_0: 'VALUE_10',
        xkanban_0: 'VALUE_10',
        xqteret_0: 'VALUE_10',
        oprqty_0: 105.0,
        preqty_0: 105.0,
        oprqtystu_0: 105.0,
        preqtystu_0: 105.0,
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        xnbetiimp_0: 'VALUE_10',
        xpcusauc01_0: 'VALUE_10',
        xpldeliv_0: 'VALUE_10',
        dsplinwei_0: 'VALUE_10',
        dsplinvol_0: 'VALUE_10',
        invamt_0: 105.0,
        dlvpiocmp_0: 'VALUE_10',
        lot_0: 'VALUE_10',
        sta_0: 1,
        xregroup_0: 'VALUE_10',
        loc_0: 'VALUE_10',
        mon_0: 'VALUE_10',
        sddlin_0: 'VALUE_10',
        pckcap_0: 'VALUE_10',
        yea_0: 'VALUE_10',
        pjt_0: 'VALUE_10',
        x4facture_0: 'VALUE_10',
        pck_0: 'VALUE_10',
        x4avmotcomd_0: 'VALUE_10',
        maxdlvhou_0: 'VALUE_10',
        eccvalmaj_0: 'VALUE_10',
        eccvalmin_0: 'VALUE_10',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_10',
        xpcu1itm_0: 'VALUE_10',
        xtimmes_0: new Date().toISOString(),
        xalert_0: 'VALUE_10',
        fminum_0: 'VALUE_10',
        fmilin_0: 'VALUE_10',
        fmiseq_0: 'VALUE_10',
        orddat_0: new Date().toISOString().split('T')[0],
        linordnum_0: 'VALUE_10',
        demdlvhou_0: 'VALUE_10',
        soqsta_0: 10,
        ddtanum_0: 'VALUE_10',
        ddtanot_0: 'VALUE_10',
        dlvday_0: 'VALUE_10',
        cad_0: 'VALUE_10',
        wee_0: 'VALUE_10',
        ynbcolis_0: 'VALUE_10',
        demsta_0: 10,
        shtqty_0: 105.0,
        shtqtystu_0: 105.0,
        invflg_0: 'VALUE_10',
        credat_0: new Date().toISOString().split('T')[0],
        pitflg_0: 'VALUE_10',
        cclren_0: 'VALUE_10',
        ccldat_0: new Date().toISOString().split('T')[0],
        xflgret_0: 'VALUE_10',
        dlvflg_0: 'VALUE_10',
        xcmqint_0: 'VALUE_10',
        poplin_0: 'VALUE_10',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_10',
        vtc_0: 'VALUE_10',
        taxgeoflg_0: 'VALUE_10',
        taxflg_0: 'VALUE_10',
        taxregflg_0: 'VALUE_10',
        soqtex_0: 'VALUE_10',
        sdhnum_0: 'VALUE_10',
        sohnum_0: 'VALUE_10',
        pohnum_0: 'VALUE_10',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_10',
        dlvqtystu_0: 105.0,
        perstrdat_0: new Date().toISOString().split('T')[0],
        perenddat_0: new Date().toISOString().split('T')[0],
        pernbrday_0: 'VALUE_10',
        useplc_0: 'VALUE_10',
        qty_0: 105.0,
        allqty_0: 105.0,
        cpy_0: 'VALUE_10',
        soplin_0: 'VALUE_10',
        soqseqnum_0: 'VALUE_10',
        shihou_0: 'VALUE_10',
        extdlvdat_0: new Date().toISOString().split('T')[0],
        upddat_0: new Date().toISOString().split('T')[0],
        bptnum_0: 'VALUE_10',
        demnum_0: 'VALUE_10',
        allqtystu_0: 105.0,
        creusr_0: 'VALUE_10',
        xversion_0: 'VALUE_10',
        z01statut_0: 10,
        stofcy_0: 'VALUE_10',
        stomgtcod_0: 'VALUE_10',
        itmref_0: 'VALUE_10',
        dspvou_0: 'VALUE_10',
        dspweu_0: 'VALUE_10',
        salfcy_0: 'VALUE_10',
        tdlqty_0: 105.0,
        dlvqty_0: 105.0,
      },
    ]

    await Database.table('sorderq').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans sorderq`)
  }
}
