import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour SORDERP
    const data = [
      {
        discrgren7_0: 'VALUE_1',
        discrgren8_0: 'VALUE_1',
        discrgren9_0: 'VALUE_1',
        reprat2_0: 'VALUE_1',
        discrgval6_0: 'VALUE_1',
        discrgval7_0: 'VALUE_1',
        discrgval8_0: 'VALUE_1',
        discrgval9_0: 'VALUE_1',
        discrgren1_0: 'VALUE_1',
        sstcod_0: 'VALUE_1',
        invcnd_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        zcdeclifin_0: 'VALUE_1',
        zn1clifin_0: 'VALUE_1',
        zn2clifin_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpcsalpri_0: 10.5,
        bpcinv_0: 'VALUE_1',
        clcamt1_0: 10.5,
        clcamt2_0: 10.5,
        linrevnum_0: 'SOR0001',
        repcoe_0: 'VALUE_1',
        gropri_0: 10.5,
        priren_0: 10.5,
        vat_0: 'VALUE_1',
        rep1_0: 'VALUE_1',
        rep2_0: 'VALUE_1',
        soqsta_0: 1,
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_1',
        itmdes1_0: 'Désignation article 1',
        xflaglm_0: 'VALUE_1',
        pcntnum_0: 'VALUE_1',
        tsicod_0: 'VALUE_1',
        sohnum_0: 'VALUE_1',
        reprat1_0: 'VALUE_1',
        saustucoe_0: 'VALUE_1',
        cpy_0: 'VALUE_1',
        soplin_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_1',
        orilin_0: 'VALUE_1',
        itmrefbpc_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        stofcy_0: 'VALUE_1',
        itmref_0: 'VALUE_1',
        pfm_0: 'VALUE_1',
        sopseq_0: 'VALUE_1',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        netpri_0: 10.5,
        salfcy_0: 'VALUE_1',
        stu_0: 'VALUE_1',
        sohcat_0: 'VALUE_1',
        bpcord_0: 'VALUE_1',
        sqdlin_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        discrgren2_0: 'VALUE_1',
        discrgren3_0: 'VALUE_1',
        discrgren4_0: 'VALUE_1',
        discrgren5_0: 'VALUE_1',
        discrgren6_0: 'VALUE_1',
        discrgval1_0: 'VALUE_1',
        discrgval2_0: 'VALUE_1',
        discrgval3_0: 'VALUE_1',
        discrgval4_0: 'VALUE_1',
        discrgval5_0: 'VALUE_1',
        cprpri_0: 10.5,
        bpaadd_0: 'VALUE_1',
        connum_0: 'VALUE_1',
        xtypof_0: 'VALUE_1',
        netprinot_0: 10.5,
        netpriati_0: 10.5,
        zligoriedi_0: 'VALUE_1',
        itmdes_0: 'VALUE_1',
        x4savliv_0: 'VALUE_1',
        cndnam_0: 'VALUE_1',
        lintyp_0: 'VALUE_1',
        focflg_0: 'VALUE_1',
        sqhnum_0: 'VALUE_1',
        sau_0: 'VALUE_1',
      },
      {
        discrgren7_0: 'VALUE_2',
        discrgren8_0: 'VALUE_2',
        discrgren9_0: 'VALUE_2',
        reprat2_0: 'VALUE_2',
        discrgval6_0: 'VALUE_2',
        discrgval7_0: 'VALUE_2',
        discrgval8_0: 'VALUE_2',
        discrgval9_0: 'VALUE_2',
        discrgren1_0: 'VALUE_2',
        sstcod_0: 'VALUE_2',
        invcnd_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        zcdeclifin_0: 'VALUE_2',
        zn1clifin_0: 'VALUE_2',
        zn2clifin_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpcsalpri_0: 21.0,
        bpcinv_0: 'VALUE_2',
        clcamt1_0: 21.0,
        clcamt2_0: 21.0,
        linrevnum_0: 'SOR0002',
        repcoe_0: 'VALUE_2',
        gropri_0: 21.0,
        priren_0: 21.0,
        vat_0: 'VALUE_2',
        rep1_0: 'VALUE_2',
        rep2_0: 'VALUE_2',
        soqsta_0: 1,
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_2',
        itmdes1_0: 'Désignation article 2',
        xflaglm_0: 'VALUE_2',
        pcntnum_0: 'VALUE_2',
        tsicod_0: 'VALUE_2',
        sohnum_0: 'VALUE_2',
        reprat1_0: 'VALUE_2',
        saustucoe_0: 'VALUE_2',
        cpy_0: 'VALUE_2',
        soplin_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_2',
        orilin_0: 'VALUE_2',
        itmrefbpc_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        stofcy_0: 'VALUE_2',
        itmref_0: 'VALUE_2',
        pfm_0: 'VALUE_2',
        sopseq_0: 'VALUE_2',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        netpri_0: 21.0,
        salfcy_0: 'VALUE_2',
        stu_0: 'VALUE_2',
        sohcat_0: 'VALUE_2',
        bpcord_0: 'VALUE_2',
        sqdlin_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        discrgren2_0: 'VALUE_2',
        discrgren3_0: 'VALUE_2',
        discrgren4_0: 'VALUE_2',
        discrgren5_0: 'VALUE_2',
        discrgren6_0: 'VALUE_2',
        discrgval1_0: 'VALUE_2',
        discrgval2_0: 'VALUE_2',
        discrgval3_0: 'VALUE_2',
        discrgval4_0: 'VALUE_2',
        discrgval5_0: 'VALUE_2',
        cprpri_0: 21.0,
        bpaadd_0: 'VALUE_2',
        connum_0: 'VALUE_2',
        xtypof_0: 'VALUE_2',
        netprinot_0: 21.0,
        netpriati_0: 21.0,
        zligoriedi_0: 'VALUE_2',
        itmdes_0: 'VALUE_2',
        x4savliv_0: 'VALUE_2',
        cndnam_0: 'VALUE_2',
        lintyp_0: 'VALUE_2',
        focflg_0: 'VALUE_2',
        sqhnum_0: 'VALUE_2',
        sau_0: 'VALUE_2',
      },
      {
        discrgren7_0: 'VALUE_3',
        discrgren8_0: 'VALUE_3',
        discrgren9_0: 'VALUE_3',
        reprat2_0: 'VALUE_3',
        discrgval6_0: 'VALUE_3',
        discrgval7_0: 'VALUE_3',
        discrgval8_0: 'VALUE_3',
        discrgval9_0: 'VALUE_3',
        discrgren1_0: 'VALUE_3',
        sstcod_0: 'VALUE_3',
        invcnd_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        zcdeclifin_0: 'VALUE_3',
        zn1clifin_0: 'VALUE_3',
        zn2clifin_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpcsalpri_0: 31.5,
        bpcinv_0: 'VALUE_3',
        clcamt1_0: 31.5,
        clcamt2_0: 31.5,
        linrevnum_0: 'SOR0003',
        repcoe_0: 'VALUE_3',
        gropri_0: 31.5,
        priren_0: 31.5,
        vat_0: 'VALUE_3',
        rep1_0: 'VALUE_3',
        rep2_0: 'VALUE_3',
        soqsta_0: 1,
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_3',
        itmdes1_0: 'Désignation article 3',
        xflaglm_0: 'VALUE_3',
        pcntnum_0: 'VALUE_3',
        tsicod_0: 'VALUE_3',
        sohnum_0: 'VALUE_3',
        reprat1_0: 'VALUE_3',
        saustucoe_0: 'VALUE_3',
        cpy_0: 'VALUE_3',
        soplin_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_3',
        orilin_0: 'VALUE_3',
        itmrefbpc_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        stofcy_0: 'VALUE_3',
        itmref_0: 'VALUE_3',
        pfm_0: 'VALUE_3',
        sopseq_0: 'VALUE_3',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        netpri_0: 31.5,
        salfcy_0: 'VALUE_3',
        stu_0: 'VALUE_3',
        sohcat_0: 'VALUE_3',
        bpcord_0: 'VALUE_3',
        sqdlin_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        discrgren2_0: 'VALUE_3',
        discrgren3_0: 'VALUE_3',
        discrgren4_0: 'VALUE_3',
        discrgren5_0: 'VALUE_3',
        discrgren6_0: 'VALUE_3',
        discrgval1_0: 'VALUE_3',
        discrgval2_0: 'VALUE_3',
        discrgval3_0: 'VALUE_3',
        discrgval4_0: 'VALUE_3',
        discrgval5_0: 'VALUE_3',
        cprpri_0: 31.5,
        bpaadd_0: 'VALUE_3',
        connum_0: 'VALUE_3',
        xtypof_0: 'VALUE_3',
        netprinot_0: 31.5,
        netpriati_0: 31.5,
        zligoriedi_0: 'VALUE_3',
        itmdes_0: 'VALUE_3',
        x4savliv_0: 'VALUE_3',
        cndnam_0: 'VALUE_3',
        lintyp_0: 'VALUE_3',
        focflg_0: 'VALUE_3',
        sqhnum_0: 'VALUE_3',
        sau_0: 'VALUE_3',
      },
      {
        discrgren7_0: 'VALUE_4',
        discrgren8_0: 'VALUE_4',
        discrgren9_0: 'VALUE_4',
        reprat2_0: 'VALUE_4',
        discrgval6_0: 'VALUE_4',
        discrgval7_0: 'VALUE_4',
        discrgval8_0: 'VALUE_4',
        discrgval9_0: 'VALUE_4',
        discrgren1_0: 'VALUE_4',
        sstcod_0: 'VALUE_4',
        invcnd_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        zcdeclifin_0: 'VALUE_4',
        zn1clifin_0: 'VALUE_4',
        zn2clifin_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpcsalpri_0: 42.0,
        bpcinv_0: 'VALUE_4',
        clcamt1_0: 42.0,
        clcamt2_0: 42.0,
        linrevnum_0: 'SOR0004',
        repcoe_0: 'VALUE_4',
        gropri_0: 42.0,
        priren_0: 42.0,
        vat_0: 'VALUE_4',
        rep1_0: 'VALUE_4',
        rep2_0: 'VALUE_4',
        soqsta_0: 1,
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_4',
        itmdes1_0: 'Désignation article 4',
        xflaglm_0: 'VALUE_4',
        pcntnum_0: 'VALUE_4',
        tsicod_0: 'VALUE_4',
        sohnum_0: 'VALUE_4',
        reprat1_0: 'VALUE_4',
        saustucoe_0: 'VALUE_4',
        cpy_0: 'VALUE_4',
        soplin_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_4',
        orilin_0: 'VALUE_4',
        itmrefbpc_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        stofcy_0: 'VALUE_4',
        itmref_0: 'VALUE_4',
        pfm_0: 'VALUE_4',
        sopseq_0: 'VALUE_4',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        netpri_0: 42.0,
        salfcy_0: 'VALUE_4',
        stu_0: 'VALUE_4',
        sohcat_0: 'VALUE_4',
        bpcord_0: 'VALUE_4',
        sqdlin_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        discrgren2_0: 'VALUE_4',
        discrgren3_0: 'VALUE_4',
        discrgren4_0: 'VALUE_4',
        discrgren5_0: 'VALUE_4',
        discrgren6_0: 'VALUE_4',
        discrgval1_0: 'VALUE_4',
        discrgval2_0: 'VALUE_4',
        discrgval3_0: 'VALUE_4',
        discrgval4_0: 'VALUE_4',
        discrgval5_0: 'VALUE_4',
        cprpri_0: 42.0,
        bpaadd_0: 'VALUE_4',
        connum_0: 'VALUE_4',
        xtypof_0: 'VALUE_4',
        netprinot_0: 42.0,
        netpriati_0: 42.0,
        zligoriedi_0: 'VALUE_4',
        itmdes_0: 'VALUE_4',
        x4savliv_0: 'VALUE_4',
        cndnam_0: 'VALUE_4',
        lintyp_0: 'VALUE_4',
        focflg_0: 'VALUE_4',
        sqhnum_0: 'VALUE_4',
        sau_0: 'VALUE_4',
      },
      {
        discrgren7_0: 'VALUE_5',
        discrgren8_0: 'VALUE_5',
        discrgren9_0: 'VALUE_5',
        reprat2_0: 'VALUE_5',
        discrgval6_0: 'VALUE_5',
        discrgval7_0: 'VALUE_5',
        discrgval8_0: 'VALUE_5',
        discrgval9_0: 'VALUE_5',
        discrgren1_0: 'VALUE_5',
        sstcod_0: 'VALUE_5',
        invcnd_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        zcdeclifin_0: 'VALUE_5',
        zn1clifin_0: 'VALUE_5',
        zn2clifin_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpcsalpri_0: 52.5,
        bpcinv_0: 'VALUE_5',
        clcamt1_0: 52.5,
        clcamt2_0: 52.5,
        linrevnum_0: 'SOR0005',
        repcoe_0: 'VALUE_5',
        gropri_0: 52.5,
        priren_0: 52.5,
        vat_0: 'VALUE_5',
        rep1_0: 'VALUE_5',
        rep2_0: 'VALUE_5',
        soqsta_0: 1,
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_5',
        itmdes1_0: 'Désignation article 5',
        xflaglm_0: 'VALUE_5',
        pcntnum_0: 'VALUE_5',
        tsicod_0: 'VALUE_5',
        sohnum_0: 'VALUE_5',
        reprat1_0: 'VALUE_5',
        saustucoe_0: 'VALUE_5',
        cpy_0: 'VALUE_5',
        soplin_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_5',
        orilin_0: 'VALUE_5',
        itmrefbpc_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        stofcy_0: 'VALUE_5',
        itmref_0: 'VALUE_5',
        pfm_0: 'VALUE_5',
        sopseq_0: 'VALUE_5',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        netpri_0: 52.5,
        salfcy_0: 'VALUE_5',
        stu_0: 'VALUE_5',
        sohcat_0: 'VALUE_5',
        bpcord_0: 'VALUE_5',
        sqdlin_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        discrgren2_0: 'VALUE_5',
        discrgren3_0: 'VALUE_5',
        discrgren4_0: 'VALUE_5',
        discrgren5_0: 'VALUE_5',
        discrgren6_0: 'VALUE_5',
        discrgval1_0: 'VALUE_5',
        discrgval2_0: 'VALUE_5',
        discrgval3_0: 'VALUE_5',
        discrgval4_0: 'VALUE_5',
        discrgval5_0: 'VALUE_5',
        cprpri_0: 52.5,
        bpaadd_0: 'VALUE_5',
        connum_0: 'VALUE_5',
        xtypof_0: 'VALUE_5',
        netprinot_0: 52.5,
        netpriati_0: 52.5,
        zligoriedi_0: 'VALUE_5',
        itmdes_0: 'VALUE_5',
        x4savliv_0: 'VALUE_5',
        cndnam_0: 'VALUE_5',
        lintyp_0: 'VALUE_5',
        focflg_0: 'VALUE_5',
        sqhnum_0: 'VALUE_5',
        sau_0: 'VALUE_5',
      },
      {
        discrgren7_0: 'VALUE_6',
        discrgren8_0: 'VALUE_6',
        discrgren9_0: 'VALUE_6',
        reprat2_0: 'VALUE_6',
        discrgval6_0: 'VALUE_6',
        discrgval7_0: 'VALUE_6',
        discrgval8_0: 'VALUE_6',
        discrgval9_0: 'VALUE_6',
        discrgren1_0: 'VALUE_6',
        sstcod_0: 'VALUE_6',
        invcnd_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        zcdeclifin_0: 'VALUE_6',
        zn1clifin_0: 'VALUE_6',
        zn2clifin_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpcsalpri_0: 63.0,
        bpcinv_0: 'VALUE_6',
        clcamt1_0: 63.0,
        clcamt2_0: 63.0,
        linrevnum_0: 'SOR0006',
        repcoe_0: 'VALUE_6',
        gropri_0: 63.0,
        priren_0: 63.0,
        vat_0: 'VALUE_6',
        rep1_0: 'VALUE_6',
        rep2_0: 'VALUE_6',
        soqsta_0: 1,
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_6',
        itmdes1_0: 'Désignation article 6',
        xflaglm_0: 'VALUE_6',
        pcntnum_0: 'VALUE_6',
        tsicod_0: 'VALUE_6',
        sohnum_0: 'VALUE_6',
        reprat1_0: 'VALUE_6',
        saustucoe_0: 'VALUE_6',
        cpy_0: 'VALUE_6',
        soplin_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_6',
        orilin_0: 'VALUE_6',
        itmrefbpc_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        stofcy_0: 'VALUE_6',
        itmref_0: 'VALUE_6',
        pfm_0: 'VALUE_6',
        sopseq_0: 'VALUE_6',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        netpri_0: 63.0,
        salfcy_0: 'VALUE_6',
        stu_0: 'VALUE_6',
        sohcat_0: 'VALUE_6',
        bpcord_0: 'VALUE_6',
        sqdlin_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        discrgren2_0: 'VALUE_6',
        discrgren3_0: 'VALUE_6',
        discrgren4_0: 'VALUE_6',
        discrgren5_0: 'VALUE_6',
        discrgren6_0: 'VALUE_6',
        discrgval1_0: 'VALUE_6',
        discrgval2_0: 'VALUE_6',
        discrgval3_0: 'VALUE_6',
        discrgval4_0: 'VALUE_6',
        discrgval5_0: 'VALUE_6',
        cprpri_0: 63.0,
        bpaadd_0: 'VALUE_6',
        connum_0: 'VALUE_6',
        xtypof_0: 'VALUE_6',
        netprinot_0: 63.0,
        netpriati_0: 63.0,
        zligoriedi_0: 'VALUE_6',
        itmdes_0: 'VALUE_6',
        x4savliv_0: 'VALUE_6',
        cndnam_0: 'VALUE_6',
        lintyp_0: 'VALUE_6',
        focflg_0: 'VALUE_6',
        sqhnum_0: 'VALUE_6',
        sau_0: 'VALUE_6',
      },
      {
        discrgren7_0: 'VALUE_7',
        discrgren8_0: 'VALUE_7',
        discrgren9_0: 'VALUE_7',
        reprat2_0: 'VALUE_7',
        discrgval6_0: 'VALUE_7',
        discrgval7_0: 'VALUE_7',
        discrgval8_0: 'VALUE_7',
        discrgval9_0: 'VALUE_7',
        discrgren1_0: 'VALUE_7',
        sstcod_0: 'VALUE_7',
        invcnd_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        zcdeclifin_0: 'VALUE_7',
        zn1clifin_0: 'VALUE_7',
        zn2clifin_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpcsalpri_0: 73.5,
        bpcinv_0: 'VALUE_7',
        clcamt1_0: 73.5,
        clcamt2_0: 73.5,
        linrevnum_0: 'SOR0007',
        repcoe_0: 'VALUE_7',
        gropri_0: 73.5,
        priren_0: 73.5,
        vat_0: 'VALUE_7',
        rep1_0: 'VALUE_7',
        rep2_0: 'VALUE_7',
        soqsta_0: 1,
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_7',
        itmdes1_0: 'Désignation article 7',
        xflaglm_0: 'VALUE_7',
        pcntnum_0: 'VALUE_7',
        tsicod_0: 'VALUE_7',
        sohnum_0: 'VALUE_7',
        reprat1_0: 'VALUE_7',
        saustucoe_0: 'VALUE_7',
        cpy_0: 'VALUE_7',
        soplin_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_7',
        orilin_0: 'VALUE_7',
        itmrefbpc_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        stofcy_0: 'VALUE_7',
        itmref_0: 'VALUE_7',
        pfm_0: 'VALUE_7',
        sopseq_0: 'VALUE_7',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        netpri_0: 73.5,
        salfcy_0: 'VALUE_7',
        stu_0: 'VALUE_7',
        sohcat_0: 'VALUE_7',
        bpcord_0: 'VALUE_7',
        sqdlin_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        discrgren2_0: 'VALUE_7',
        discrgren3_0: 'VALUE_7',
        discrgren4_0: 'VALUE_7',
        discrgren5_0: 'VALUE_7',
        discrgren6_0: 'VALUE_7',
        discrgval1_0: 'VALUE_7',
        discrgval2_0: 'VALUE_7',
        discrgval3_0: 'VALUE_7',
        discrgval4_0: 'VALUE_7',
        discrgval5_0: 'VALUE_7',
        cprpri_0: 73.5,
        bpaadd_0: 'VALUE_7',
        connum_0: 'VALUE_7',
        xtypof_0: 'VALUE_7',
        netprinot_0: 73.5,
        netpriati_0: 73.5,
        zligoriedi_0: 'VALUE_7',
        itmdes_0: 'VALUE_7',
        x4savliv_0: 'VALUE_7',
        cndnam_0: 'VALUE_7',
        lintyp_0: 'VALUE_7',
        focflg_0: 'VALUE_7',
        sqhnum_0: 'VALUE_7',
        sau_0: 'VALUE_7',
      },
      {
        discrgren7_0: 'VALUE_8',
        discrgren8_0: 'VALUE_8',
        discrgren9_0: 'VALUE_8',
        reprat2_0: 'VALUE_8',
        discrgval6_0: 'VALUE_8',
        discrgval7_0: 'VALUE_8',
        discrgval8_0: 'VALUE_8',
        discrgval9_0: 'VALUE_8',
        discrgren1_0: 'VALUE_8',
        sstcod_0: 'VALUE_8',
        invcnd_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        zcdeclifin_0: 'VALUE_8',
        zn1clifin_0: 'VALUE_8',
        zn2clifin_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpcsalpri_0: 84.0,
        bpcinv_0: 'VALUE_8',
        clcamt1_0: 84.0,
        clcamt2_0: 84.0,
        linrevnum_0: 'SOR0008',
        repcoe_0: 'VALUE_8',
        gropri_0: 84.0,
        priren_0: 84.0,
        vat_0: 'VALUE_8',
        rep1_0: 'VALUE_8',
        rep2_0: 'VALUE_8',
        soqsta_0: 1,
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_8',
        itmdes1_0: 'Désignation article 8',
        xflaglm_0: 'VALUE_8',
        pcntnum_0: 'VALUE_8',
        tsicod_0: 'VALUE_8',
        sohnum_0: 'VALUE_8',
        reprat1_0: 'VALUE_8',
        saustucoe_0: 'VALUE_8',
        cpy_0: 'VALUE_8',
        soplin_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_8',
        orilin_0: 'VALUE_8',
        itmrefbpc_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        stofcy_0: 'VALUE_8',
        itmref_0: 'VALUE_8',
        pfm_0: 'VALUE_8',
        sopseq_0: 'VALUE_8',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        netpri_0: 84.0,
        salfcy_0: 'VALUE_8',
        stu_0: 'VALUE_8',
        sohcat_0: 'VALUE_8',
        bpcord_0: 'VALUE_8',
        sqdlin_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        discrgren2_0: 'VALUE_8',
        discrgren3_0: 'VALUE_8',
        discrgren4_0: 'VALUE_8',
        discrgren5_0: 'VALUE_8',
        discrgren6_0: 'VALUE_8',
        discrgval1_0: 'VALUE_8',
        discrgval2_0: 'VALUE_8',
        discrgval3_0: 'VALUE_8',
        discrgval4_0: 'VALUE_8',
        discrgval5_0: 'VALUE_8',
        cprpri_0: 84.0,
        bpaadd_0: 'VALUE_8',
        connum_0: 'VALUE_8',
        xtypof_0: 'VALUE_8',
        netprinot_0: 84.0,
        netpriati_0: 84.0,
        zligoriedi_0: 'VALUE_8',
        itmdes_0: 'VALUE_8',
        x4savliv_0: 'VALUE_8',
        cndnam_0: 'VALUE_8',
        lintyp_0: 'VALUE_8',
        focflg_0: 'VALUE_8',
        sqhnum_0: 'VALUE_8',
        sau_0: 'VALUE_8',
      },
      {
        discrgren7_0: 'VALUE_9',
        discrgren8_0: 'VALUE_9',
        discrgren9_0: 'VALUE_9',
        reprat2_0: 'VALUE_9',
        discrgval6_0: 'VALUE_9',
        discrgval7_0: 'VALUE_9',
        discrgval8_0: 'VALUE_9',
        discrgval9_0: 'VALUE_9',
        discrgren1_0: 'VALUE_9',
        sstcod_0: 'VALUE_9',
        invcnd_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        zcdeclifin_0: 'VALUE_9',
        zn1clifin_0: 'VALUE_9',
        zn2clifin_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpcsalpri_0: 94.5,
        bpcinv_0: 'VALUE_9',
        clcamt1_0: 94.5,
        clcamt2_0: 94.5,
        linrevnum_0: 'SOR0009',
        repcoe_0: 'VALUE_9',
        gropri_0: 94.5,
        priren_0: 94.5,
        vat_0: 'VALUE_9',
        rep1_0: 'VALUE_9',
        rep2_0: 'VALUE_9',
        soqsta_0: 1,
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_9',
        itmdes1_0: 'Désignation article 9',
        xflaglm_0: 'VALUE_9',
        pcntnum_0: 'VALUE_9',
        tsicod_0: 'VALUE_9',
        sohnum_0: 'VALUE_9',
        reprat1_0: 'VALUE_9',
        saustucoe_0: 'VALUE_9',
        cpy_0: 'VALUE_9',
        soplin_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_9',
        orilin_0: 'VALUE_9',
        itmrefbpc_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        stofcy_0: 'VALUE_9',
        itmref_0: 'VALUE_9',
        pfm_0: 'VALUE_9',
        sopseq_0: 'VALUE_9',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        netpri_0: 94.5,
        salfcy_0: 'VALUE_9',
        stu_0: 'VALUE_9',
        sohcat_0: 'VALUE_9',
        bpcord_0: 'VALUE_9',
        sqdlin_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        discrgren2_0: 'VALUE_9',
        discrgren3_0: 'VALUE_9',
        discrgren4_0: 'VALUE_9',
        discrgren5_0: 'VALUE_9',
        discrgren6_0: 'VALUE_9',
        discrgval1_0: 'VALUE_9',
        discrgval2_0: 'VALUE_9',
        discrgval3_0: 'VALUE_9',
        discrgval4_0: 'VALUE_9',
        discrgval5_0: 'VALUE_9',
        cprpri_0: 94.5,
        bpaadd_0: 'VALUE_9',
        connum_0: 'VALUE_9',
        xtypof_0: 'VALUE_9',
        netprinot_0: 94.5,
        netpriati_0: 94.5,
        zligoriedi_0: 'VALUE_9',
        itmdes_0: 'VALUE_9',
        x4savliv_0: 'VALUE_9',
        cndnam_0: 'VALUE_9',
        lintyp_0: 'VALUE_9',
        focflg_0: 'VALUE_9',
        sqhnum_0: 'VALUE_9',
        sau_0: 'VALUE_9',
      },
      {
        discrgren7_0: 'VALUE_10',
        discrgren8_0: 'VALUE_10',
        discrgren9_0: 'VALUE_10',
        reprat2_0: 'VALUE_10',
        discrgval6_0: 'VALUE_10',
        discrgval7_0: 'VALUE_10',
        discrgval8_0: 'VALUE_10',
        discrgval9_0: 'VALUE_10',
        discrgren1_0: 'VALUE_10',
        sstcod_0: 'VALUE_10',
        invcnd_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        zcdeclifin_0: 'VALUE_10',
        zn1clifin_0: 'VALUE_10',
        zn2clifin_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        bpcsalpri_0: 105.0,
        bpcinv_0: 'VALUE_10',
        clcamt1_0: 105.0,
        clcamt2_0: 105.0,
        linrevnum_0: 'SOR0010',
        repcoe_0: 'VALUE_10',
        gropri_0: 105.0,
        priren_0: 105.0,
        vat_0: 'VALUE_10',
        rep1_0: 'VALUE_10',
        rep2_0: 'VALUE_10',
        soqsta_0: 1,
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_10',
        itmdes1_0: 'Désignation article 10',
        xflaglm_0: 'VALUE_10',
        pcntnum_0: 'VALUE_10',
        tsicod_0: 'VALUE_10',
        sohnum_0: 'VALUE_10',
        reprat1_0: 'VALUE_10',
        saustucoe_0: 'VALUE_10',
        cpy_0: 'VALUE_10',
        soplin_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_10',
        orilin_0: 'VALUE_10',
        itmrefbpc_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        stofcy_0: 'VALUE_10',
        itmref_0: 'VALUE_10',
        pfm_0: 'VALUE_10',
        sopseq_0: 'VALUE_10',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        netpri_0: 105.0,
        salfcy_0: 'VALUE_10',
        stu_0: 'VALUE_10',
        sohcat_0: 'VALUE_10',
        bpcord_0: 'VALUE_10',
        sqdlin_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        discrgren2_0: 'VALUE_10',
        discrgren3_0: 'VALUE_10',
        discrgren4_0: 'VALUE_10',
        discrgren5_0: 'VALUE_10',
        discrgren6_0: 'VALUE_10',
        discrgval1_0: 'VALUE_10',
        discrgval2_0: 'VALUE_10',
        discrgval3_0: 'VALUE_10',
        discrgval4_0: 'VALUE_10',
        discrgval5_0: 'VALUE_10',
        cprpri_0: 105.0,
        bpaadd_0: 'VALUE_10',
        connum_0: 'VALUE_10',
        xtypof_0: 'VALUE_10',
        netprinot_0: 105.0,
        netpriati_0: 105.0,
        zligoriedi_0: 'VALUE_10',
        itmdes_0: 'VALUE_10',
        x4savliv_0: 'VALUE_10',
        cndnam_0: 'VALUE_10',
        lintyp_0: 'VALUE_10',
        focflg_0: 'VALUE_10',
        sqhnum_0: 'VALUE_10',
        sau_0: 'VALUE_10',
      },
    ]

    await Database.table('sorderp').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans sorderp`)
  }
}
