import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour SDELIVERY
    const data = [
      {
        credat_0: new Date().toISOString().split('T')[0],
        tmpsdhnum_0: 'SDE0001',
        x4numdemand_0: 'VALUE_1',
        sisdat_0: new Date().toISOString().split('T')[0],
        xsphtex1_0: 'VALUE_1',
        x4intident_0: 'VALUE_1',
        xgenfactis_0: 'VALUE_1',
        xmodgfi_0: 'VALUE_1',
        x4numint_0: 'VALUE_1',
        trsfam_0: 'VALUE_1',
        cninam_0: 'Contact facture 1',
        cretim_0: new Date().toISOString(),
        vtt_0: 'VALUE_1',
        prptex2_0: 'VALUE_1',
        sdhtex1_0: 'VALUE_1',
        sdhtex2_0: 'VALUE_1',
        tsccod_0: 'VALUE_1',
        prityp_0: 10.5,
        invdtalin_0: 'VALUE_1',
        licplate_0: 'VALUE_1',
        bpcinv_0: 'VALUE_1',
        bpcgru_0: 'VALUE_1',
        dep_0: 'VALUE_1',
        linnbr_0: 'VALUE_1',
        dsptotqty_0: 10.5,
        bpieecnum_0: 'VALUE_1',
        eecnumdeb_0: 'VALUE_1',
        prhfcy_0: 'VALUE_1',
        invdtadsp_0: 'VALUE_1',
        invdtaamt_0: 10.5,
        eectrn_0: 'VALUE_1',
        sihnum_0: 'VALUE_1',
        eecnat_0: 'VALUE_1',
        eecict_0: 'VALUE_1',
        bpcloc_0: 'VALUE_1',
        prnnpr_0: 'VALUE_1',
        x4sdhexp_0: 'VALUE_1',
        salfcy_0: 'VALUE_1',
        prfnum_0: 'VALUE_1',
        dlvdat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_1',
        amttax_0: 10.5,
        bastax_0: 1,
        invper_0: 'VALUE_1',
        x4cscode_0: 'VALUE_1',
        bpcpyr_0: 'VALUE_1',
        lbenum_0: 'VALUE_1',
        sdhnum_0: 'VALUE_1',
        sohnum_0: 'VALUE_1',
        netwei_0: 'VALUE_1',
        sdhtyp_0: 'VALUE_1',
        shidat_0: new Date().toISOString().split('T')[0],
        dlvhou_0: 'VALUE_1',
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_1',
        bpdcrynam_0: 'VALUE_1',
        chgtyp_0: 'VALUE_1',
        invdtatyp_0: 'VALUE_1',
        rep_0: 'VALUE_1',
        chgrat_0: 'VALUE_1',
        plistc_0: 'VALUE_1',
        cce_0: 'VALUE_1',
        cpy_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        shihou_0: 'VALUE_1',
        dlvnot_0: 'VALUE_1',
        dlvati_0: 'VALUE_1',
        pacflg_0: 'VALUE_1',
        updusr_0: 'VALUE_1',
        sisnum_0: 'VALUE_1',
        xblocage_0: 'VALUE_1',
        copnbr_0: 'VALUE_1',
        eecloc_0: 'VALUE_1',
        daylti_0: 'VALUE_1',
        houlti_0: 'VALUE_1',
        nprflg_0: 'VALUE_1',
        ndeflg_0: 'VALUE_1',
        bpdsat_0: 'VALUE_1',
        invorn_0: 'VALUE_1',
        adrval_0: 'VALUE_1',
        bpinam_0: 'VALUE_1',
        bpiaddlig_0: 'VALUE_1',
        bpicty_0: 'VALUE_1',
        bpdposcod_0: 'VALUE_1',
        bpdcty_0: 'VALUE_1',
        bpdcry_0: 'VALUE_1',
        bpcord_0: 'VALUE_1',
        ffwnum_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        lan_0: 'VALUE_1',
        bpisat_0: 'VALUE_1',
        bptnum_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        discrgtyp_0: 'VALUE_1',
        x4sdhdest_0: 'VALUE_1',
        invdta_0: 'VALUE_1',
        vacbpr_0: 'VALUE_1',
        stofcy_0: 'VALUE_1',
        x4achtrart_0: 'VALUE_1',
        weu_0: 'VALUE_1',
        dspweu_0: 'VALUE_1',
        pte_0: 'VALUE_1',
        cur_0: 'VALUE_1',
        vou_0: 'VALUE_1',
        dspvou_0: 'VALUE_1',
        ntrflg_0: 'VALUE_1',
        prnnde_0: 'VALUE_1',
        growei_0: 'VALUE_1',
        cfmflg_0: 'VALUE_1',
        prptex1_0: 'VALUE_1',
        mdl_0: 'VALUE_1',
        drn_0: 'VALUE_1',
        dudclc_0: 'VALUE_1',
        ime_0: 'VALUE_1',
        bpaadd_0: 'VALUE_1',
        bpdaddlig_0: 'VALUE_1',
        dlvinvnot_0: 'VALUE_1',
        lnd_0: 'VALUE_1',
        zlivpart_0: 'VALUE_1',
        rtnlinnbr_0: 'VALUE_1',
        rtnsta_0: 1,
        xncflg_0: 'VALUE_1',
        etd_0: 'VALUE_1',
        eta_0: 'VALUE_1',
        sdhcat_0: 'VALUE_1',
        orifcy_0: 'VALUE_1',
        geocod_0: 'VALUE_1',
        insctyflg_0: 'VALUE_1',
        ffwadd_0: 'VALUE_1',
        dlvinvati_0: 'VALUE_1',
        xvaldat_0: new Date().toISOString().split('T')[0],
        cai_0: 'VALUE_1',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_1',
        sco_0: 'VALUE_1',
        glbdoctyp_0: 'VALUE_1',
        bolnum_0: 'VALUE_1',
        x4sbi_0: 'VALUE_1',
        x4tierslog_0: 'VALUE_1',
        x4sdhnum_0: 'VALUE_1',
        die_0: 'VALUE_1',
        dlvinvnotl_0: 'VALUE_1',
        dlvinvatil_0: 'VALUE_1',
        x_nbedit_0: 'VALUE_1',
        dsptotwei_0: 'VALUE_1',
        dsptotvol_0: 'VALUE_1',
        entcod_0: 'VALUE_1',
        betcpy_0: 'VALUE_1',
        cndnam_0: 'VALUE_1',
        x1colman_0: 'VALUE_1',
        trscod_0: 'VALUE_1',
        bpiposcod_0: 'VALUE_1',
        bpicry_0: 'VALUE_1',
        bpicrynam_0: 'VALUE_1',
        betfcy_0: 'VALUE_1',
        vol_0: 'VALUE_1',
        pacnbr_0: 'VALUE_1',
        eecsch_0: 'VALUE_1',
        pjt_0: 'VALUE_1',
        invflg_0: 'VALUE_1',
        zflgedisdh_0: 'VALUE_1',
        ynavette_0: 'VALUE_1',
        x4sdhenvaut_0: 'VALUE_1',
        x4flgdup_0: 'VALUE_1',
        x4rgop_0: 'VALUE_1',
        xexptransb_0: 'VALUE_1',
        x4contratmaf_0: 'VALUE_1',
        x4nbrml_0: 'VALUE_1',
        x4tarachlck_0: 'VALUE_1',
        x4tarvenlck_0: 'VALUE_1',
        dpedat_0: new Date().toISOString().split('T')[0],
        trllicplate_0: 'VALUE_1',
        x1nbum_0: 'VALUE_1',
        glbdoc_0: 'VALUE_1',
        glbdocnum_0: 'VALUE_1',
        glbdocdat_0: new Date().toISOString().split('T')[0],
        atdtcod_0: 'VALUE_1',
        mandoc_0: 'VALUE_1',
        arvdat_0: new Date().toISOString().split('T')[0],
        xdlvdat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sfisstcod_0: 'VALUE_1',
        sstentcod_0: 'VALUE_1',
        bpainv_0: 'VALUE_1',
        dlvnotl_0: 'VALUE_1',
        dlvatil_0: 'VALUE_1',
        xsitemad_0: 'VALUE_1',
        xdemdlvref_0: 'VALUE_1',
        xsphtex2_0: 'VALUE_1',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_1',
        xtimmes_0: new Date().toISOString(),
        auuid_0: 'VALUE_1',
        x4achtrtar_0: 'VALUE_1',
        x4cmr_0: 'VALUE_1',
        x4poiapp_0: 'VALUE_1',
        x4poiappuom_0: 'VALUE_1',
        x4tartrs_0: 'VALUE_1',
        xblexterne_0: 'VALUE_1',
        xexpedi_0: 'VALUE_1',
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        tmpsdhnum_0: 'SDE0002',
        x4numdemand_0: 'VALUE_2',
        sisdat_0: new Date().toISOString().split('T')[0],
        xsphtex1_0: 'VALUE_2',
        x4intident_0: 'VALUE_2',
        xgenfactis_0: 'VALUE_2',
        xmodgfi_0: 'VALUE_2',
        x4numint_0: 'VALUE_2',
        trsfam_0: 'VALUE_2',
        cninam_0: 'Contact facture 2',
        cretim_0: new Date().toISOString(),
        vtt_0: 'VALUE_2',
        prptex2_0: 'VALUE_2',
        sdhtex1_0: 'VALUE_2',
        sdhtex2_0: 'VALUE_2',
        tsccod_0: 'VALUE_2',
        prityp_0: 21.0,
        invdtalin_0: 'VALUE_2',
        licplate_0: 'VALUE_2',
        bpcinv_0: 'VALUE_2',
        bpcgru_0: 'VALUE_2',
        dep_0: 'VALUE_2',
        linnbr_0: 'VALUE_2',
        dsptotqty_0: 21.0,
        bpieecnum_0: 'VALUE_2',
        eecnumdeb_0: 'VALUE_2',
        prhfcy_0: 'VALUE_2',
        invdtadsp_0: 'VALUE_2',
        invdtaamt_0: 21.0,
        eectrn_0: 'VALUE_2',
        sihnum_0: 'VALUE_2',
        eecnat_0: 'VALUE_2',
        eecict_0: 'VALUE_2',
        bpcloc_0: 'VALUE_2',
        prnnpr_0: 'VALUE_2',
        x4sdhexp_0: 'VALUE_2',
        salfcy_0: 'VALUE_2',
        prfnum_0: 'VALUE_2',
        dlvdat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_2',
        amttax_0: 21.0,
        bastax_0: 2,
        invper_0: 'VALUE_2',
        x4cscode_0: 'VALUE_2',
        bpcpyr_0: 'VALUE_2',
        lbenum_0: 'VALUE_2',
        sdhnum_0: 'VALUE_2',
        sohnum_0: 'VALUE_2',
        netwei_0: 'VALUE_2',
        sdhtyp_0: 'VALUE_2',
        shidat_0: new Date().toISOString().split('T')[0],
        dlvhou_0: 'VALUE_2',
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_2',
        bpdcrynam_0: 'VALUE_2',
        chgtyp_0: 'VALUE_2',
        invdtatyp_0: 'VALUE_2',
        rep_0: 'VALUE_2',
        chgrat_0: 'VALUE_2',
        plistc_0: 'VALUE_2',
        cce_0: 'VALUE_2',
        cpy_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        shihou_0: 'VALUE_2',
        dlvnot_0: 'VALUE_2',
        dlvati_0: 'VALUE_2',
        pacflg_0: 'VALUE_2',
        updusr_0: 'VALUE_2',
        sisnum_0: 'VALUE_2',
        xblocage_0: 'VALUE_2',
        copnbr_0: 'VALUE_2',
        eecloc_0: 'VALUE_2',
        daylti_0: 'VALUE_2',
        houlti_0: 'VALUE_2',
        nprflg_0: 'VALUE_2',
        ndeflg_0: 'VALUE_2',
        bpdsat_0: 'VALUE_2',
        invorn_0: 'VALUE_2',
        adrval_0: 'VALUE_2',
        bpinam_0: 'VALUE_2',
        bpiaddlig_0: 'VALUE_2',
        bpicty_0: 'VALUE_2',
        bpdposcod_0: 'VALUE_2',
        bpdcty_0: 'VALUE_2',
        bpdcry_0: 'VALUE_2',
        bpcord_0: 'VALUE_2',
        ffwnum_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        lan_0: 'VALUE_2',
        bpisat_0: 'VALUE_2',
        bptnum_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        discrgtyp_0: 'VALUE_2',
        x4sdhdest_0: 'VALUE_2',
        invdta_0: 'VALUE_2',
        vacbpr_0: 'VALUE_2',
        stofcy_0: 'VALUE_2',
        x4achtrart_0: 'VALUE_2',
        weu_0: 'VALUE_2',
        dspweu_0: 'VALUE_2',
        pte_0: 'VALUE_2',
        cur_0: 'VALUE_2',
        vou_0: 'VALUE_2',
        dspvou_0: 'VALUE_2',
        ntrflg_0: 'VALUE_2',
        prnnde_0: 'VALUE_2',
        growei_0: 'VALUE_2',
        cfmflg_0: 'VALUE_2',
        prptex1_0: 'VALUE_2',
        mdl_0: 'VALUE_2',
        drn_0: 'VALUE_2',
        dudclc_0: 'VALUE_2',
        ime_0: 'VALUE_2',
        bpaadd_0: 'VALUE_2',
        bpdaddlig_0: 'VALUE_2',
        dlvinvnot_0: 'VALUE_2',
        lnd_0: 'VALUE_2',
        zlivpart_0: 'VALUE_2',
        rtnlinnbr_0: 'VALUE_2',
        rtnsta_0: 1,
        xncflg_0: 'VALUE_2',
        etd_0: 'VALUE_2',
        eta_0: 'VALUE_2',
        sdhcat_0: 'VALUE_2',
        orifcy_0: 'VALUE_2',
        geocod_0: 'VALUE_2',
        insctyflg_0: 'VALUE_2',
        ffwadd_0: 'VALUE_2',
        dlvinvati_0: 'VALUE_2',
        xvaldat_0: new Date().toISOString().split('T')[0],
        cai_0: 'VALUE_2',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_2',
        sco_0: 'VALUE_2',
        glbdoctyp_0: 'VALUE_2',
        bolnum_0: 'VALUE_2',
        x4sbi_0: 'VALUE_2',
        x4tierslog_0: 'VALUE_2',
        x4sdhnum_0: 'VALUE_2',
        die_0: 'VALUE_2',
        dlvinvnotl_0: 'VALUE_2',
        dlvinvatil_0: 'VALUE_2',
        x_nbedit_0: 'VALUE_2',
        dsptotwei_0: 'VALUE_2',
        dsptotvol_0: 'VALUE_2',
        entcod_0: 'VALUE_2',
        betcpy_0: 'VALUE_2',
        cndnam_0: 'VALUE_2',
        x1colman_0: 'VALUE_2',
        trscod_0: 'VALUE_2',
        bpiposcod_0: 'VALUE_2',
        bpicry_0: 'VALUE_2',
        bpicrynam_0: 'VALUE_2',
        betfcy_0: 'VALUE_2',
        vol_0: 'VALUE_2',
        pacnbr_0: 'VALUE_2',
        eecsch_0: 'VALUE_2',
        pjt_0: 'VALUE_2',
        invflg_0: 'VALUE_2',
        zflgedisdh_0: 'VALUE_2',
        ynavette_0: 'VALUE_2',
        x4sdhenvaut_0: 'VALUE_2',
        x4flgdup_0: 'VALUE_2',
        x4rgop_0: 'VALUE_2',
        xexptransb_0: 'VALUE_2',
        x4contratmaf_0: 'VALUE_2',
        x4nbrml_0: 'VALUE_2',
        x4tarachlck_0: 'VALUE_2',
        x4tarvenlck_0: 'VALUE_2',
        dpedat_0: new Date().toISOString().split('T')[0],
        trllicplate_0: 'VALUE_2',
        x1nbum_0: 'VALUE_2',
        glbdoc_0: 'VALUE_2',
        glbdocnum_0: 'VALUE_2',
        glbdocdat_0: new Date().toISOString().split('T')[0],
        atdtcod_0: 'VALUE_2',
        mandoc_0: 'VALUE_2',
        arvdat_0: new Date().toISOString().split('T')[0],
        xdlvdat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sfisstcod_0: 'VALUE_2',
        sstentcod_0: 'VALUE_2',
        bpainv_0: 'VALUE_2',
        dlvnotl_0: 'VALUE_2',
        dlvatil_0: 'VALUE_2',
        xsitemad_0: 'VALUE_2',
        xdemdlvref_0: 'VALUE_2',
        xsphtex2_0: 'VALUE_2',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_2',
        xtimmes_0: new Date().toISOString(),
        auuid_0: 'VALUE_2',
        x4achtrtar_0: 'VALUE_2',
        x4cmr_0: 'VALUE_2',
        x4poiapp_0: 'VALUE_2',
        x4poiappuom_0: 'VALUE_2',
        x4tartrs_0: 'VALUE_2',
        xblexterne_0: 'VALUE_2',
        xexpedi_0: 'VALUE_2',
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        tmpsdhnum_0: 'SDE0003',
        x4numdemand_0: 'VALUE_3',
        sisdat_0: new Date().toISOString().split('T')[0],
        xsphtex1_0: 'VALUE_3',
        x4intident_0: 'VALUE_3',
        xgenfactis_0: 'VALUE_3',
        xmodgfi_0: 'VALUE_3',
        x4numint_0: 'VALUE_3',
        trsfam_0: 'VALUE_3',
        cninam_0: 'Contact facture 3',
        cretim_0: new Date().toISOString(),
        vtt_0: 'VALUE_3',
        prptex2_0: 'VALUE_3',
        sdhtex1_0: 'VALUE_3',
        sdhtex2_0: 'VALUE_3',
        tsccod_0: 'VALUE_3',
        prityp_0: 31.5,
        invdtalin_0: 'VALUE_3',
        licplate_0: 'VALUE_3',
        bpcinv_0: 'VALUE_3',
        bpcgru_0: 'VALUE_3',
        dep_0: 'VALUE_3',
        linnbr_0: 'VALUE_3',
        dsptotqty_0: 31.5,
        bpieecnum_0: 'VALUE_3',
        eecnumdeb_0: 'VALUE_3',
        prhfcy_0: 'VALUE_3',
        invdtadsp_0: 'VALUE_3',
        invdtaamt_0: 31.5,
        eectrn_0: 'VALUE_3',
        sihnum_0: 'VALUE_3',
        eecnat_0: 'VALUE_3',
        eecict_0: 'VALUE_3',
        bpcloc_0: 'VALUE_3',
        prnnpr_0: 'VALUE_3',
        x4sdhexp_0: 'VALUE_3',
        salfcy_0: 'VALUE_3',
        prfnum_0: 'VALUE_3',
        dlvdat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_3',
        amttax_0: 31.5,
        bastax_0: 3,
        invper_0: 'VALUE_3',
        x4cscode_0: 'VALUE_3',
        bpcpyr_0: 'VALUE_3',
        lbenum_0: 'VALUE_3',
        sdhnum_0: 'VALUE_3',
        sohnum_0: 'VALUE_3',
        netwei_0: 'VALUE_3',
        sdhtyp_0: 'VALUE_3',
        shidat_0: new Date().toISOString().split('T')[0],
        dlvhou_0: 'VALUE_3',
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_3',
        bpdcrynam_0: 'VALUE_3',
        chgtyp_0: 'VALUE_3',
        invdtatyp_0: 'VALUE_3',
        rep_0: 'VALUE_3',
        chgrat_0: 'VALUE_3',
        plistc_0: 'VALUE_3',
        cce_0: 'VALUE_3',
        cpy_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        shihou_0: 'VALUE_3',
        dlvnot_0: 'VALUE_3',
        dlvati_0: 'VALUE_3',
        pacflg_0: 'VALUE_3',
        updusr_0: 'VALUE_3',
        sisnum_0: 'VALUE_3',
        xblocage_0: 'VALUE_3',
        copnbr_0: 'VALUE_3',
        eecloc_0: 'VALUE_3',
        daylti_0: 'VALUE_3',
        houlti_0: 'VALUE_3',
        nprflg_0: 'VALUE_3',
        ndeflg_0: 'VALUE_3',
        bpdsat_0: 'VALUE_3',
        invorn_0: 'VALUE_3',
        adrval_0: 'VALUE_3',
        bpinam_0: 'VALUE_3',
        bpiaddlig_0: 'VALUE_3',
        bpicty_0: 'VALUE_3',
        bpdposcod_0: 'VALUE_3',
        bpdcty_0: 'VALUE_3',
        bpdcry_0: 'VALUE_3',
        bpcord_0: 'VALUE_3',
        ffwnum_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        lan_0: 'VALUE_3',
        bpisat_0: 'VALUE_3',
        bptnum_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        discrgtyp_0: 'VALUE_3',
        x4sdhdest_0: 'VALUE_3',
        invdta_0: 'VALUE_3',
        vacbpr_0: 'VALUE_3',
        stofcy_0: 'VALUE_3',
        x4achtrart_0: 'VALUE_3',
        weu_0: 'VALUE_3',
        dspweu_0: 'VALUE_3',
        pte_0: 'VALUE_3',
        cur_0: 'VALUE_3',
        vou_0: 'VALUE_3',
        dspvou_0: 'VALUE_3',
        ntrflg_0: 'VALUE_3',
        prnnde_0: 'VALUE_3',
        growei_0: 'VALUE_3',
        cfmflg_0: 'VALUE_3',
        prptex1_0: 'VALUE_3',
        mdl_0: 'VALUE_3',
        drn_0: 'VALUE_3',
        dudclc_0: 'VALUE_3',
        ime_0: 'VALUE_3',
        bpaadd_0: 'VALUE_3',
        bpdaddlig_0: 'VALUE_3',
        dlvinvnot_0: 'VALUE_3',
        lnd_0: 'VALUE_3',
        zlivpart_0: 'VALUE_3',
        rtnlinnbr_0: 'VALUE_3',
        rtnsta_0: 1,
        xncflg_0: 'VALUE_3',
        etd_0: 'VALUE_3',
        eta_0: 'VALUE_3',
        sdhcat_0: 'VALUE_3',
        orifcy_0: 'VALUE_3',
        geocod_0: 'VALUE_3',
        insctyflg_0: 'VALUE_3',
        ffwadd_0: 'VALUE_3',
        dlvinvati_0: 'VALUE_3',
        xvaldat_0: new Date().toISOString().split('T')[0],
        cai_0: 'VALUE_3',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_3',
        sco_0: 'VALUE_3',
        glbdoctyp_0: 'VALUE_3',
        bolnum_0: 'VALUE_3',
        x4sbi_0: 'VALUE_3',
        x4tierslog_0: 'VALUE_3',
        x4sdhnum_0: 'VALUE_3',
        die_0: 'VALUE_3',
        dlvinvnotl_0: 'VALUE_3',
        dlvinvatil_0: 'VALUE_3',
        x_nbedit_0: 'VALUE_3',
        dsptotwei_0: 'VALUE_3',
        dsptotvol_0: 'VALUE_3',
        entcod_0: 'VALUE_3',
        betcpy_0: 'VALUE_3',
        cndnam_0: 'VALUE_3',
        x1colman_0: 'VALUE_3',
        trscod_0: 'VALUE_3',
        bpiposcod_0: 'VALUE_3',
        bpicry_0: 'VALUE_3',
        bpicrynam_0: 'VALUE_3',
        betfcy_0: 'VALUE_3',
        vol_0: 'VALUE_3',
        pacnbr_0: 'VALUE_3',
        eecsch_0: 'VALUE_3',
        pjt_0: 'VALUE_3',
        invflg_0: 'VALUE_3',
        zflgedisdh_0: 'VALUE_3',
        ynavette_0: 'VALUE_3',
        x4sdhenvaut_0: 'VALUE_3',
        x4flgdup_0: 'VALUE_3',
        x4rgop_0: 'VALUE_3',
        xexptransb_0: 'VALUE_3',
        x4contratmaf_0: 'VALUE_3',
        x4nbrml_0: 'VALUE_3',
        x4tarachlck_0: 'VALUE_3',
        x4tarvenlck_0: 'VALUE_3',
        dpedat_0: new Date().toISOString().split('T')[0],
        trllicplate_0: 'VALUE_3',
        x1nbum_0: 'VALUE_3',
        glbdoc_0: 'VALUE_3',
        glbdocnum_0: 'VALUE_3',
        glbdocdat_0: new Date().toISOString().split('T')[0],
        atdtcod_0: 'VALUE_3',
        mandoc_0: 'VALUE_3',
        arvdat_0: new Date().toISOString().split('T')[0],
        xdlvdat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sfisstcod_0: 'VALUE_3',
        sstentcod_0: 'VALUE_3',
        bpainv_0: 'VALUE_3',
        dlvnotl_0: 'VALUE_3',
        dlvatil_0: 'VALUE_3',
        xsitemad_0: 'VALUE_3',
        xdemdlvref_0: 'VALUE_3',
        xsphtex2_0: 'VALUE_3',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_3',
        xtimmes_0: new Date().toISOString(),
        auuid_0: 'VALUE_3',
        x4achtrtar_0: 'VALUE_3',
        x4cmr_0: 'VALUE_3',
        x4poiapp_0: 'VALUE_3',
        x4poiappuom_0: 'VALUE_3',
        x4tartrs_0: 'VALUE_3',
        xblexterne_0: 'VALUE_3',
        xexpedi_0: 'VALUE_3',
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        tmpsdhnum_0: 'SDE0004',
        x4numdemand_0: 'VALUE_4',
        sisdat_0: new Date().toISOString().split('T')[0],
        xsphtex1_0: 'VALUE_4',
        x4intident_0: 'VALUE_4',
        xgenfactis_0: 'VALUE_4',
        xmodgfi_0: 'VALUE_4',
        x4numint_0: 'VALUE_4',
        trsfam_0: 'VALUE_4',
        cninam_0: 'Contact facture 4',
        cretim_0: new Date().toISOString(),
        vtt_0: 'VALUE_4',
        prptex2_0: 'VALUE_4',
        sdhtex1_0: 'VALUE_4',
        sdhtex2_0: 'VALUE_4',
        tsccod_0: 'VALUE_4',
        prityp_0: 42.0,
        invdtalin_0: 'VALUE_4',
        licplate_0: 'VALUE_4',
        bpcinv_0: 'VALUE_4',
        bpcgru_0: 'VALUE_4',
        dep_0: 'VALUE_4',
        linnbr_0: 'VALUE_4',
        dsptotqty_0: 42.0,
        bpieecnum_0: 'VALUE_4',
        eecnumdeb_0: 'VALUE_4',
        prhfcy_0: 'VALUE_4',
        invdtadsp_0: 'VALUE_4',
        invdtaamt_0: 42.0,
        eectrn_0: 'VALUE_4',
        sihnum_0: 'VALUE_4',
        eecnat_0: 'VALUE_4',
        eecict_0: 'VALUE_4',
        bpcloc_0: 'VALUE_4',
        prnnpr_0: 'VALUE_4',
        x4sdhexp_0: 'VALUE_4',
        salfcy_0: 'VALUE_4',
        prfnum_0: 'VALUE_4',
        dlvdat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_4',
        amttax_0: 42.0,
        bastax_0: 4,
        invper_0: 'VALUE_4',
        x4cscode_0: 'VALUE_4',
        bpcpyr_0: 'VALUE_4',
        lbenum_0: 'VALUE_4',
        sdhnum_0: 'VALUE_4',
        sohnum_0: 'VALUE_4',
        netwei_0: 'VALUE_4',
        sdhtyp_0: 'VALUE_4',
        shidat_0: new Date().toISOString().split('T')[0],
        dlvhou_0: 'VALUE_4',
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_4',
        bpdcrynam_0: 'VALUE_4',
        chgtyp_0: 'VALUE_4',
        invdtatyp_0: 'VALUE_4',
        rep_0: 'VALUE_4',
        chgrat_0: 'VALUE_4',
        plistc_0: 'VALUE_4',
        cce_0: 'VALUE_4',
        cpy_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        shihou_0: 'VALUE_4',
        dlvnot_0: 'VALUE_4',
        dlvati_0: 'VALUE_4',
        pacflg_0: 'VALUE_4',
        updusr_0: 'VALUE_4',
        sisnum_0: 'VALUE_4',
        xblocage_0: 'VALUE_4',
        copnbr_0: 'VALUE_4',
        eecloc_0: 'VALUE_4',
        daylti_0: 'VALUE_4',
        houlti_0: 'VALUE_4',
        nprflg_0: 'VALUE_4',
        ndeflg_0: 'VALUE_4',
        bpdsat_0: 'VALUE_4',
        invorn_0: 'VALUE_4',
        adrval_0: 'VALUE_4',
        bpinam_0: 'VALUE_4',
        bpiaddlig_0: 'VALUE_4',
        bpicty_0: 'VALUE_4',
        bpdposcod_0: 'VALUE_4',
        bpdcty_0: 'VALUE_4',
        bpdcry_0: 'VALUE_4',
        bpcord_0: 'VALUE_4',
        ffwnum_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        lan_0: 'VALUE_4',
        bpisat_0: 'VALUE_4',
        bptnum_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        discrgtyp_0: 'VALUE_4',
        x4sdhdest_0: 'VALUE_4',
        invdta_0: 'VALUE_4',
        vacbpr_0: 'VALUE_4',
        stofcy_0: 'VALUE_4',
        x4achtrart_0: 'VALUE_4',
        weu_0: 'VALUE_4',
        dspweu_0: 'VALUE_4',
        pte_0: 'VALUE_4',
        cur_0: 'VALUE_4',
        vou_0: 'VALUE_4',
        dspvou_0: 'VALUE_4',
        ntrflg_0: 'VALUE_4',
        prnnde_0: 'VALUE_4',
        growei_0: 'VALUE_4',
        cfmflg_0: 'VALUE_4',
        prptex1_0: 'VALUE_4',
        mdl_0: 'VALUE_4',
        drn_0: 'VALUE_4',
        dudclc_0: 'VALUE_4',
        ime_0: 'VALUE_4',
        bpaadd_0: 'VALUE_4',
        bpdaddlig_0: 'VALUE_4',
        dlvinvnot_0: 'VALUE_4',
        lnd_0: 'VALUE_4',
        zlivpart_0: 'VALUE_4',
        rtnlinnbr_0: 'VALUE_4',
        rtnsta_0: 1,
        xncflg_0: 'VALUE_4',
        etd_0: 'VALUE_4',
        eta_0: 'VALUE_4',
        sdhcat_0: 'VALUE_4',
        orifcy_0: 'VALUE_4',
        geocod_0: 'VALUE_4',
        insctyflg_0: 'VALUE_4',
        ffwadd_0: 'VALUE_4',
        dlvinvati_0: 'VALUE_4',
        xvaldat_0: new Date().toISOString().split('T')[0],
        cai_0: 'VALUE_4',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_4',
        sco_0: 'VALUE_4',
        glbdoctyp_0: 'VALUE_4',
        bolnum_0: 'VALUE_4',
        x4sbi_0: 'VALUE_4',
        x4tierslog_0: 'VALUE_4',
        x4sdhnum_0: 'VALUE_4',
        die_0: 'VALUE_4',
        dlvinvnotl_0: 'VALUE_4',
        dlvinvatil_0: 'VALUE_4',
        x_nbedit_0: 'VALUE_4',
        dsptotwei_0: 'VALUE_4',
        dsptotvol_0: 'VALUE_4',
        entcod_0: 'VALUE_4',
        betcpy_0: 'VALUE_4',
        cndnam_0: 'VALUE_4',
        x1colman_0: 'VALUE_4',
        trscod_0: 'VALUE_4',
        bpiposcod_0: 'VALUE_4',
        bpicry_0: 'VALUE_4',
        bpicrynam_0: 'VALUE_4',
        betfcy_0: 'VALUE_4',
        vol_0: 'VALUE_4',
        pacnbr_0: 'VALUE_4',
        eecsch_0: 'VALUE_4',
        pjt_0: 'VALUE_4',
        invflg_0: 'VALUE_4',
        zflgedisdh_0: 'VALUE_4',
        ynavette_0: 'VALUE_4',
        x4sdhenvaut_0: 'VALUE_4',
        x4flgdup_0: 'VALUE_4',
        x4rgop_0: 'VALUE_4',
        xexptransb_0: 'VALUE_4',
        x4contratmaf_0: 'VALUE_4',
        x4nbrml_0: 'VALUE_4',
        x4tarachlck_0: 'VALUE_4',
        x4tarvenlck_0: 'VALUE_4',
        dpedat_0: new Date().toISOString().split('T')[0],
        trllicplate_0: 'VALUE_4',
        x1nbum_0: 'VALUE_4',
        glbdoc_0: 'VALUE_4',
        glbdocnum_0: 'VALUE_4',
        glbdocdat_0: new Date().toISOString().split('T')[0],
        atdtcod_0: 'VALUE_4',
        mandoc_0: 'VALUE_4',
        arvdat_0: new Date().toISOString().split('T')[0],
        xdlvdat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sfisstcod_0: 'VALUE_4',
        sstentcod_0: 'VALUE_4',
        bpainv_0: 'VALUE_4',
        dlvnotl_0: 'VALUE_4',
        dlvatil_0: 'VALUE_4',
        xsitemad_0: 'VALUE_4',
        xdemdlvref_0: 'VALUE_4',
        xsphtex2_0: 'VALUE_4',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_4',
        xtimmes_0: new Date().toISOString(),
        auuid_0: 'VALUE_4',
        x4achtrtar_0: 'VALUE_4',
        x4cmr_0: 'VALUE_4',
        x4poiapp_0: 'VALUE_4',
        x4poiappuom_0: 'VALUE_4',
        x4tartrs_0: 'VALUE_4',
        xblexterne_0: 'VALUE_4',
        xexpedi_0: 'VALUE_4',
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        tmpsdhnum_0: 'SDE0005',
        x4numdemand_0: 'VALUE_5',
        sisdat_0: new Date().toISOString().split('T')[0],
        xsphtex1_0: 'VALUE_5',
        x4intident_0: 'VALUE_5',
        xgenfactis_0: 'VALUE_5',
        xmodgfi_0: 'VALUE_5',
        x4numint_0: 'VALUE_5',
        trsfam_0: 'VALUE_5',
        cninam_0: 'Contact facture 5',
        cretim_0: new Date().toISOString(),
        vtt_0: 'VALUE_5',
        prptex2_0: 'VALUE_5',
        sdhtex1_0: 'VALUE_5',
        sdhtex2_0: 'VALUE_5',
        tsccod_0: 'VALUE_5',
        prityp_0: 52.5,
        invdtalin_0: 'VALUE_5',
        licplate_0: 'VALUE_5',
        bpcinv_0: 'VALUE_5',
        bpcgru_0: 'VALUE_5',
        dep_0: 'VALUE_5',
        linnbr_0: 'VALUE_5',
        dsptotqty_0: 52.5,
        bpieecnum_0: 'VALUE_5',
        eecnumdeb_0: 'VALUE_5',
        prhfcy_0: 'VALUE_5',
        invdtadsp_0: 'VALUE_5',
        invdtaamt_0: 52.5,
        eectrn_0: 'VALUE_5',
        sihnum_0: 'VALUE_5',
        eecnat_0: 'VALUE_5',
        eecict_0: 'VALUE_5',
        bpcloc_0: 'VALUE_5',
        prnnpr_0: 'VALUE_5',
        x4sdhexp_0: 'VALUE_5',
        salfcy_0: 'VALUE_5',
        prfnum_0: 'VALUE_5',
        dlvdat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_5',
        amttax_0: 52.5,
        bastax_0: 5,
        invper_0: 'VALUE_5',
        x4cscode_0: 'VALUE_5',
        bpcpyr_0: 'VALUE_5',
        lbenum_0: 'VALUE_5',
        sdhnum_0: 'VALUE_5',
        sohnum_0: 'VALUE_5',
        netwei_0: 'VALUE_5',
        sdhtyp_0: 'VALUE_5',
        shidat_0: new Date().toISOString().split('T')[0],
        dlvhou_0: 'VALUE_5',
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_5',
        bpdcrynam_0: 'VALUE_5',
        chgtyp_0: 'VALUE_5',
        invdtatyp_0: 'VALUE_5',
        rep_0: 'VALUE_5',
        chgrat_0: 'VALUE_5',
        plistc_0: 'VALUE_5',
        cce_0: 'VALUE_5',
        cpy_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        shihou_0: 'VALUE_5',
        dlvnot_0: 'VALUE_5',
        dlvati_0: 'VALUE_5',
        pacflg_0: 'VALUE_5',
        updusr_0: 'VALUE_5',
        sisnum_0: 'VALUE_5',
        xblocage_0: 'VALUE_5',
        copnbr_0: 'VALUE_5',
        eecloc_0: 'VALUE_5',
        daylti_0: 'VALUE_5',
        houlti_0: 'VALUE_5',
        nprflg_0: 'VALUE_5',
        ndeflg_0: 'VALUE_5',
        bpdsat_0: 'VALUE_5',
        invorn_0: 'VALUE_5',
        adrval_0: 'VALUE_5',
        bpinam_0: 'VALUE_5',
        bpiaddlig_0: 'VALUE_5',
        bpicty_0: 'VALUE_5',
        bpdposcod_0: 'VALUE_5',
        bpdcty_0: 'VALUE_5',
        bpdcry_0: 'VALUE_5',
        bpcord_0: 'VALUE_5',
        ffwnum_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        lan_0: 'VALUE_5',
        bpisat_0: 'VALUE_5',
        bptnum_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        discrgtyp_0: 'VALUE_5',
        x4sdhdest_0: 'VALUE_5',
        invdta_0: 'VALUE_5',
        vacbpr_0: 'VALUE_5',
        stofcy_0: 'VALUE_5',
        x4achtrart_0: 'VALUE_5',
        weu_0: 'VALUE_5',
        dspweu_0: 'VALUE_5',
        pte_0: 'VALUE_5',
        cur_0: 'VALUE_5',
        vou_0: 'VALUE_5',
        dspvou_0: 'VALUE_5',
        ntrflg_0: 'VALUE_5',
        prnnde_0: 'VALUE_5',
        growei_0: 'VALUE_5',
        cfmflg_0: 'VALUE_5',
        prptex1_0: 'VALUE_5',
        mdl_0: 'VALUE_5',
        drn_0: 'VALUE_5',
        dudclc_0: 'VALUE_5',
        ime_0: 'VALUE_5',
        bpaadd_0: 'VALUE_5',
        bpdaddlig_0: 'VALUE_5',
        dlvinvnot_0: 'VALUE_5',
        lnd_0: 'VALUE_5',
        zlivpart_0: 'VALUE_5',
        rtnlinnbr_0: 'VALUE_5',
        rtnsta_0: 1,
        xncflg_0: 'VALUE_5',
        etd_0: 'VALUE_5',
        eta_0: 'VALUE_5',
        sdhcat_0: 'VALUE_5',
        orifcy_0: 'VALUE_5',
        geocod_0: 'VALUE_5',
        insctyflg_0: 'VALUE_5',
        ffwadd_0: 'VALUE_5',
        dlvinvati_0: 'VALUE_5',
        xvaldat_0: new Date().toISOString().split('T')[0],
        cai_0: 'VALUE_5',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_5',
        sco_0: 'VALUE_5',
        glbdoctyp_0: 'VALUE_5',
        bolnum_0: 'VALUE_5',
        x4sbi_0: 'VALUE_5',
        x4tierslog_0: 'VALUE_5',
        x4sdhnum_0: 'VALUE_5',
        die_0: 'VALUE_5',
        dlvinvnotl_0: 'VALUE_5',
        dlvinvatil_0: 'VALUE_5',
        x_nbedit_0: 'VALUE_5',
        dsptotwei_0: 'VALUE_5',
        dsptotvol_0: 'VALUE_5',
        entcod_0: 'VALUE_5',
        betcpy_0: 'VALUE_5',
        cndnam_0: 'VALUE_5',
        x1colman_0: 'VALUE_5',
        trscod_0: 'VALUE_5',
        bpiposcod_0: 'VALUE_5',
        bpicry_0: 'VALUE_5',
        bpicrynam_0: 'VALUE_5',
        betfcy_0: 'VALUE_5',
        vol_0: 'VALUE_5',
        pacnbr_0: 'VALUE_5',
        eecsch_0: 'VALUE_5',
        pjt_0: 'VALUE_5',
        invflg_0: 'VALUE_5',
        zflgedisdh_0: 'VALUE_5',
        ynavette_0: 'VALUE_5',
        x4sdhenvaut_0: 'VALUE_5',
        x4flgdup_0: 'VALUE_5',
        x4rgop_0: 'VALUE_5',
        xexptransb_0: 'VALUE_5',
        x4contratmaf_0: 'VALUE_5',
        x4nbrml_0: 'VALUE_5',
        x4tarachlck_0: 'VALUE_5',
        x4tarvenlck_0: 'VALUE_5',
        dpedat_0: new Date().toISOString().split('T')[0],
        trllicplate_0: 'VALUE_5',
        x1nbum_0: 'VALUE_5',
        glbdoc_0: 'VALUE_5',
        glbdocnum_0: 'VALUE_5',
        glbdocdat_0: new Date().toISOString().split('T')[0],
        atdtcod_0: 'VALUE_5',
        mandoc_0: 'VALUE_5',
        arvdat_0: new Date().toISOString().split('T')[0],
        xdlvdat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sfisstcod_0: 'VALUE_5',
        sstentcod_0: 'VALUE_5',
        bpainv_0: 'VALUE_5',
        dlvnotl_0: 'VALUE_5',
        dlvatil_0: 'VALUE_5',
        xsitemad_0: 'VALUE_5',
        xdemdlvref_0: 'VALUE_5',
        xsphtex2_0: 'VALUE_5',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_5',
        xtimmes_0: new Date().toISOString(),
        auuid_0: 'VALUE_5',
        x4achtrtar_0: 'VALUE_5',
        x4cmr_0: 'VALUE_5',
        x4poiapp_0: 'VALUE_5',
        x4poiappuom_0: 'VALUE_5',
        x4tartrs_0: 'VALUE_5',
        xblexterne_0: 'VALUE_5',
        xexpedi_0: 'VALUE_5',
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        tmpsdhnum_0: 'SDE0006',
        x4numdemand_0: 'VALUE_6',
        sisdat_0: new Date().toISOString().split('T')[0],
        xsphtex1_0: 'VALUE_6',
        x4intident_0: 'VALUE_6',
        xgenfactis_0: 'VALUE_6',
        xmodgfi_0: 'VALUE_6',
        x4numint_0: 'VALUE_6',
        trsfam_0: 'VALUE_6',
        cninam_0: 'Contact facture 6',
        cretim_0: new Date().toISOString(),
        vtt_0: 'VALUE_6',
        prptex2_0: 'VALUE_6',
        sdhtex1_0: 'VALUE_6',
        sdhtex2_0: 'VALUE_6',
        tsccod_0: 'VALUE_6',
        prityp_0: 63.0,
        invdtalin_0: 'VALUE_6',
        licplate_0: 'VALUE_6',
        bpcinv_0: 'VALUE_6',
        bpcgru_0: 'VALUE_6',
        dep_0: 'VALUE_6',
        linnbr_0: 'VALUE_6',
        dsptotqty_0: 63.0,
        bpieecnum_0: 'VALUE_6',
        eecnumdeb_0: 'VALUE_6',
        prhfcy_0: 'VALUE_6',
        invdtadsp_0: 'VALUE_6',
        invdtaamt_0: 63.0,
        eectrn_0: 'VALUE_6',
        sihnum_0: 'VALUE_6',
        eecnat_0: 'VALUE_6',
        eecict_0: 'VALUE_6',
        bpcloc_0: 'VALUE_6',
        prnnpr_0: 'VALUE_6',
        x4sdhexp_0: 'VALUE_6',
        salfcy_0: 'VALUE_6',
        prfnum_0: 'VALUE_6',
        dlvdat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_6',
        amttax_0: 63.0,
        bastax_0: 6,
        invper_0: 'VALUE_6',
        x4cscode_0: 'VALUE_6',
        bpcpyr_0: 'VALUE_6',
        lbenum_0: 'VALUE_6',
        sdhnum_0: 'VALUE_6',
        sohnum_0: 'VALUE_6',
        netwei_0: 'VALUE_6',
        sdhtyp_0: 'VALUE_6',
        shidat_0: new Date().toISOString().split('T')[0],
        dlvhou_0: 'VALUE_6',
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_6',
        bpdcrynam_0: 'VALUE_6',
        chgtyp_0: 'VALUE_6',
        invdtatyp_0: 'VALUE_6',
        rep_0: 'VALUE_6',
        chgrat_0: 'VALUE_6',
        plistc_0: 'VALUE_6',
        cce_0: 'VALUE_6',
        cpy_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        shihou_0: 'VALUE_6',
        dlvnot_0: 'VALUE_6',
        dlvati_0: 'VALUE_6',
        pacflg_0: 'VALUE_6',
        updusr_0: 'VALUE_6',
        sisnum_0: 'VALUE_6',
        xblocage_0: 'VALUE_6',
        copnbr_0: 'VALUE_6',
        eecloc_0: 'VALUE_6',
        daylti_0: 'VALUE_6',
        houlti_0: 'VALUE_6',
        nprflg_0: 'VALUE_6',
        ndeflg_0: 'VALUE_6',
        bpdsat_0: 'VALUE_6',
        invorn_0: 'VALUE_6',
        adrval_0: 'VALUE_6',
        bpinam_0: 'VALUE_6',
        bpiaddlig_0: 'VALUE_6',
        bpicty_0: 'VALUE_6',
        bpdposcod_0: 'VALUE_6',
        bpdcty_0: 'VALUE_6',
        bpdcry_0: 'VALUE_6',
        bpcord_0: 'VALUE_6',
        ffwnum_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        lan_0: 'VALUE_6',
        bpisat_0: 'VALUE_6',
        bptnum_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        discrgtyp_0: 'VALUE_6',
        x4sdhdest_0: 'VALUE_6',
        invdta_0: 'VALUE_6',
        vacbpr_0: 'VALUE_6',
        stofcy_0: 'VALUE_6',
        x4achtrart_0: 'VALUE_6',
        weu_0: 'VALUE_6',
        dspweu_0: 'VALUE_6',
        pte_0: 'VALUE_6',
        cur_0: 'VALUE_6',
        vou_0: 'VALUE_6',
        dspvou_0: 'VALUE_6',
        ntrflg_0: 'VALUE_6',
        prnnde_0: 'VALUE_6',
        growei_0: 'VALUE_6',
        cfmflg_0: 'VALUE_6',
        prptex1_0: 'VALUE_6',
        mdl_0: 'VALUE_6',
        drn_0: 'VALUE_6',
        dudclc_0: 'VALUE_6',
        ime_0: 'VALUE_6',
        bpaadd_0: 'VALUE_6',
        bpdaddlig_0: 'VALUE_6',
        dlvinvnot_0: 'VALUE_6',
        lnd_0: 'VALUE_6',
        zlivpart_0: 'VALUE_6',
        rtnlinnbr_0: 'VALUE_6',
        rtnsta_0: 1,
        xncflg_0: 'VALUE_6',
        etd_0: 'VALUE_6',
        eta_0: 'VALUE_6',
        sdhcat_0: 'VALUE_6',
        orifcy_0: 'VALUE_6',
        geocod_0: 'VALUE_6',
        insctyflg_0: 'VALUE_6',
        ffwadd_0: 'VALUE_6',
        dlvinvati_0: 'VALUE_6',
        xvaldat_0: new Date().toISOString().split('T')[0],
        cai_0: 'VALUE_6',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_6',
        sco_0: 'VALUE_6',
        glbdoctyp_0: 'VALUE_6',
        bolnum_0: 'VALUE_6',
        x4sbi_0: 'VALUE_6',
        x4tierslog_0: 'VALUE_6',
        x4sdhnum_0: 'VALUE_6',
        die_0: 'VALUE_6',
        dlvinvnotl_0: 'VALUE_6',
        dlvinvatil_0: 'VALUE_6',
        x_nbedit_0: 'VALUE_6',
        dsptotwei_0: 'VALUE_6',
        dsptotvol_0: 'VALUE_6',
        entcod_0: 'VALUE_6',
        betcpy_0: 'VALUE_6',
        cndnam_0: 'VALUE_6',
        x1colman_0: 'VALUE_6',
        trscod_0: 'VALUE_6',
        bpiposcod_0: 'VALUE_6',
        bpicry_0: 'VALUE_6',
        bpicrynam_0: 'VALUE_6',
        betfcy_0: 'VALUE_6',
        vol_0: 'VALUE_6',
        pacnbr_0: 'VALUE_6',
        eecsch_0: 'VALUE_6',
        pjt_0: 'VALUE_6',
        invflg_0: 'VALUE_6',
        zflgedisdh_0: 'VALUE_6',
        ynavette_0: 'VALUE_6',
        x4sdhenvaut_0: 'VALUE_6',
        x4flgdup_0: 'VALUE_6',
        x4rgop_0: 'VALUE_6',
        xexptransb_0: 'VALUE_6',
        x4contratmaf_0: 'VALUE_6',
        x4nbrml_0: 'VALUE_6',
        x4tarachlck_0: 'VALUE_6',
        x4tarvenlck_0: 'VALUE_6',
        dpedat_0: new Date().toISOString().split('T')[0],
        trllicplate_0: 'VALUE_6',
        x1nbum_0: 'VALUE_6',
        glbdoc_0: 'VALUE_6',
        glbdocnum_0: 'VALUE_6',
        glbdocdat_0: new Date().toISOString().split('T')[0],
        atdtcod_0: 'VALUE_6',
        mandoc_0: 'VALUE_6',
        arvdat_0: new Date().toISOString().split('T')[0],
        xdlvdat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sfisstcod_0: 'VALUE_6',
        sstentcod_0: 'VALUE_6',
        bpainv_0: 'VALUE_6',
        dlvnotl_0: 'VALUE_6',
        dlvatil_0: 'VALUE_6',
        xsitemad_0: 'VALUE_6',
        xdemdlvref_0: 'VALUE_6',
        xsphtex2_0: 'VALUE_6',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_6',
        xtimmes_0: new Date().toISOString(),
        auuid_0: 'VALUE_6',
        x4achtrtar_0: 'VALUE_6',
        x4cmr_0: 'VALUE_6',
        x4poiapp_0: 'VALUE_6',
        x4poiappuom_0: 'VALUE_6',
        x4tartrs_0: 'VALUE_6',
        xblexterne_0: 'VALUE_6',
        xexpedi_0: 'VALUE_6',
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        tmpsdhnum_0: 'SDE0007',
        x4numdemand_0: 'VALUE_7',
        sisdat_0: new Date().toISOString().split('T')[0],
        xsphtex1_0: 'VALUE_7',
        x4intident_0: 'VALUE_7',
        xgenfactis_0: 'VALUE_7',
        xmodgfi_0: 'VALUE_7',
        x4numint_0: 'VALUE_7',
        trsfam_0: 'VALUE_7',
        cninam_0: 'Contact facture 7',
        cretim_0: new Date().toISOString(),
        vtt_0: 'VALUE_7',
        prptex2_0: 'VALUE_7',
        sdhtex1_0: 'VALUE_7',
        sdhtex2_0: 'VALUE_7',
        tsccod_0: 'VALUE_7',
        prityp_0: 73.5,
        invdtalin_0: 'VALUE_7',
        licplate_0: 'VALUE_7',
        bpcinv_0: 'VALUE_7',
        bpcgru_0: 'VALUE_7',
        dep_0: 'VALUE_7',
        linnbr_0: 'VALUE_7',
        dsptotqty_0: 73.5,
        bpieecnum_0: 'VALUE_7',
        eecnumdeb_0: 'VALUE_7',
        prhfcy_0: 'VALUE_7',
        invdtadsp_0: 'VALUE_7',
        invdtaamt_0: 73.5,
        eectrn_0: 'VALUE_7',
        sihnum_0: 'VALUE_7',
        eecnat_0: 'VALUE_7',
        eecict_0: 'VALUE_7',
        bpcloc_0: 'VALUE_7',
        prnnpr_0: 'VALUE_7',
        x4sdhexp_0: 'VALUE_7',
        salfcy_0: 'VALUE_7',
        prfnum_0: 'VALUE_7',
        dlvdat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_7',
        amttax_0: 73.5,
        bastax_0: 7,
        invper_0: 'VALUE_7',
        x4cscode_0: 'VALUE_7',
        bpcpyr_0: 'VALUE_7',
        lbenum_0: 'VALUE_7',
        sdhnum_0: 'VALUE_7',
        sohnum_0: 'VALUE_7',
        netwei_0: 'VALUE_7',
        sdhtyp_0: 'VALUE_7',
        shidat_0: new Date().toISOString().split('T')[0],
        dlvhou_0: 'VALUE_7',
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_7',
        bpdcrynam_0: 'VALUE_7',
        chgtyp_0: 'VALUE_7',
        invdtatyp_0: 'VALUE_7',
        rep_0: 'VALUE_7',
        chgrat_0: 'VALUE_7',
        plistc_0: 'VALUE_7',
        cce_0: 'VALUE_7',
        cpy_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        shihou_0: 'VALUE_7',
        dlvnot_0: 'VALUE_7',
        dlvati_0: 'VALUE_7',
        pacflg_0: 'VALUE_7',
        updusr_0: 'VALUE_7',
        sisnum_0: 'VALUE_7',
        xblocage_0: 'VALUE_7',
        copnbr_0: 'VALUE_7',
        eecloc_0: 'VALUE_7',
        daylti_0: 'VALUE_7',
        houlti_0: 'VALUE_7',
        nprflg_0: 'VALUE_7',
        ndeflg_0: 'VALUE_7',
        bpdsat_0: 'VALUE_7',
        invorn_0: 'VALUE_7',
        adrval_0: 'VALUE_7',
        bpinam_0: 'VALUE_7',
        bpiaddlig_0: 'VALUE_7',
        bpicty_0: 'VALUE_7',
        bpdposcod_0: 'VALUE_7',
        bpdcty_0: 'VALUE_7',
        bpdcry_0: 'VALUE_7',
        bpcord_0: 'VALUE_7',
        ffwnum_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        lan_0: 'VALUE_7',
        bpisat_0: 'VALUE_7',
        bptnum_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        discrgtyp_0: 'VALUE_7',
        x4sdhdest_0: 'VALUE_7',
        invdta_0: 'VALUE_7',
        vacbpr_0: 'VALUE_7',
        stofcy_0: 'VALUE_7',
        x4achtrart_0: 'VALUE_7',
        weu_0: 'VALUE_7',
        dspweu_0: 'VALUE_7',
        pte_0: 'VALUE_7',
        cur_0: 'VALUE_7',
        vou_0: 'VALUE_7',
        dspvou_0: 'VALUE_7',
        ntrflg_0: 'VALUE_7',
        prnnde_0: 'VALUE_7',
        growei_0: 'VALUE_7',
        cfmflg_0: 'VALUE_7',
        prptex1_0: 'VALUE_7',
        mdl_0: 'VALUE_7',
        drn_0: 'VALUE_7',
        dudclc_0: 'VALUE_7',
        ime_0: 'VALUE_7',
        bpaadd_0: 'VALUE_7',
        bpdaddlig_0: 'VALUE_7',
        dlvinvnot_0: 'VALUE_7',
        lnd_0: 'VALUE_7',
        zlivpart_0: 'VALUE_7',
        rtnlinnbr_0: 'VALUE_7',
        rtnsta_0: 1,
        xncflg_0: 'VALUE_7',
        etd_0: 'VALUE_7',
        eta_0: 'VALUE_7',
        sdhcat_0: 'VALUE_7',
        orifcy_0: 'VALUE_7',
        geocod_0: 'VALUE_7',
        insctyflg_0: 'VALUE_7',
        ffwadd_0: 'VALUE_7',
        dlvinvati_0: 'VALUE_7',
        xvaldat_0: new Date().toISOString().split('T')[0],
        cai_0: 'VALUE_7',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_7',
        sco_0: 'VALUE_7',
        glbdoctyp_0: 'VALUE_7',
        bolnum_0: 'VALUE_7',
        x4sbi_0: 'VALUE_7',
        x4tierslog_0: 'VALUE_7',
        x4sdhnum_0: 'VALUE_7',
        die_0: 'VALUE_7',
        dlvinvnotl_0: 'VALUE_7',
        dlvinvatil_0: 'VALUE_7',
        x_nbedit_0: 'VALUE_7',
        dsptotwei_0: 'VALUE_7',
        dsptotvol_0: 'VALUE_7',
        entcod_0: 'VALUE_7',
        betcpy_0: 'VALUE_7',
        cndnam_0: 'VALUE_7',
        x1colman_0: 'VALUE_7',
        trscod_0: 'VALUE_7',
        bpiposcod_0: 'VALUE_7',
        bpicry_0: 'VALUE_7',
        bpicrynam_0: 'VALUE_7',
        betfcy_0: 'VALUE_7',
        vol_0: 'VALUE_7',
        pacnbr_0: 'VALUE_7',
        eecsch_0: 'VALUE_7',
        pjt_0: 'VALUE_7',
        invflg_0: 'VALUE_7',
        zflgedisdh_0: 'VALUE_7',
        ynavette_0: 'VALUE_7',
        x4sdhenvaut_0: 'VALUE_7',
        x4flgdup_0: 'VALUE_7',
        x4rgop_0: 'VALUE_7',
        xexptransb_0: 'VALUE_7',
        x4contratmaf_0: 'VALUE_7',
        x4nbrml_0: 'VALUE_7',
        x4tarachlck_0: 'VALUE_7',
        x4tarvenlck_0: 'VALUE_7',
        dpedat_0: new Date().toISOString().split('T')[0],
        trllicplate_0: 'VALUE_7',
        x1nbum_0: 'VALUE_7',
        glbdoc_0: 'VALUE_7',
        glbdocnum_0: 'VALUE_7',
        glbdocdat_0: new Date().toISOString().split('T')[0],
        atdtcod_0: 'VALUE_7',
        mandoc_0: 'VALUE_7',
        arvdat_0: new Date().toISOString().split('T')[0],
        xdlvdat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sfisstcod_0: 'VALUE_7',
        sstentcod_0: 'VALUE_7',
        bpainv_0: 'VALUE_7',
        dlvnotl_0: 'VALUE_7',
        dlvatil_0: 'VALUE_7',
        xsitemad_0: 'VALUE_7',
        xdemdlvref_0: 'VALUE_7',
        xsphtex2_0: 'VALUE_7',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_7',
        xtimmes_0: new Date().toISOString(),
        auuid_0: 'VALUE_7',
        x4achtrtar_0: 'VALUE_7',
        x4cmr_0: 'VALUE_7',
        x4poiapp_0: 'VALUE_7',
        x4poiappuom_0: 'VALUE_7',
        x4tartrs_0: 'VALUE_7',
        xblexterne_0: 'VALUE_7',
        xexpedi_0: 'VALUE_7',
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        tmpsdhnum_0: 'SDE0008',
        x4numdemand_0: 'VALUE_8',
        sisdat_0: new Date().toISOString().split('T')[0],
        xsphtex1_0: 'VALUE_8',
        x4intident_0: 'VALUE_8',
        xgenfactis_0: 'VALUE_8',
        xmodgfi_0: 'VALUE_8',
        x4numint_0: 'VALUE_8',
        trsfam_0: 'VALUE_8',
        cninam_0: 'Contact facture 8',
        cretim_0: new Date().toISOString(),
        vtt_0: 'VALUE_8',
        prptex2_0: 'VALUE_8',
        sdhtex1_0: 'VALUE_8',
        sdhtex2_0: 'VALUE_8',
        tsccod_0: 'VALUE_8',
        prityp_0: 84.0,
        invdtalin_0: 'VALUE_8',
        licplate_0: 'VALUE_8',
        bpcinv_0: 'VALUE_8',
        bpcgru_0: 'VALUE_8',
        dep_0: 'VALUE_8',
        linnbr_0: 'VALUE_8',
        dsptotqty_0: 84.0,
        bpieecnum_0: 'VALUE_8',
        eecnumdeb_0: 'VALUE_8',
        prhfcy_0: 'VALUE_8',
        invdtadsp_0: 'VALUE_8',
        invdtaamt_0: 84.0,
        eectrn_0: 'VALUE_8',
        sihnum_0: 'VALUE_8',
        eecnat_0: 'VALUE_8',
        eecict_0: 'VALUE_8',
        bpcloc_0: 'VALUE_8',
        prnnpr_0: 'VALUE_8',
        x4sdhexp_0: 'VALUE_8',
        salfcy_0: 'VALUE_8',
        prfnum_0: 'VALUE_8',
        dlvdat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_8',
        amttax_0: 84.0,
        bastax_0: 8,
        invper_0: 'VALUE_8',
        x4cscode_0: 'VALUE_8',
        bpcpyr_0: 'VALUE_8',
        lbenum_0: 'VALUE_8',
        sdhnum_0: 'VALUE_8',
        sohnum_0: 'VALUE_8',
        netwei_0: 'VALUE_8',
        sdhtyp_0: 'VALUE_8',
        shidat_0: new Date().toISOString().split('T')[0],
        dlvhou_0: 'VALUE_8',
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_8',
        bpdcrynam_0: 'VALUE_8',
        chgtyp_0: 'VALUE_8',
        invdtatyp_0: 'VALUE_8',
        rep_0: 'VALUE_8',
        chgrat_0: 'VALUE_8',
        plistc_0: 'VALUE_8',
        cce_0: 'VALUE_8',
        cpy_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        shihou_0: 'VALUE_8',
        dlvnot_0: 'VALUE_8',
        dlvati_0: 'VALUE_8',
        pacflg_0: 'VALUE_8',
        updusr_0: 'VALUE_8',
        sisnum_0: 'VALUE_8',
        xblocage_0: 'VALUE_8',
        copnbr_0: 'VALUE_8',
        eecloc_0: 'VALUE_8',
        daylti_0: 'VALUE_8',
        houlti_0: 'VALUE_8',
        nprflg_0: 'VALUE_8',
        ndeflg_0: 'VALUE_8',
        bpdsat_0: 'VALUE_8',
        invorn_0: 'VALUE_8',
        adrval_0: 'VALUE_8',
        bpinam_0: 'VALUE_8',
        bpiaddlig_0: 'VALUE_8',
        bpicty_0: 'VALUE_8',
        bpdposcod_0: 'VALUE_8',
        bpdcty_0: 'VALUE_8',
        bpdcry_0: 'VALUE_8',
        bpcord_0: 'VALUE_8',
        ffwnum_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        lan_0: 'VALUE_8',
        bpisat_0: 'VALUE_8',
        bptnum_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        discrgtyp_0: 'VALUE_8',
        x4sdhdest_0: 'VALUE_8',
        invdta_0: 'VALUE_8',
        vacbpr_0: 'VALUE_8',
        stofcy_0: 'VALUE_8',
        x4achtrart_0: 'VALUE_8',
        weu_0: 'VALUE_8',
        dspweu_0: 'VALUE_8',
        pte_0: 'VALUE_8',
        cur_0: 'VALUE_8',
        vou_0: 'VALUE_8',
        dspvou_0: 'VALUE_8',
        ntrflg_0: 'VALUE_8',
        prnnde_0: 'VALUE_8',
        growei_0: 'VALUE_8',
        cfmflg_0: 'VALUE_8',
        prptex1_0: 'VALUE_8',
        mdl_0: 'VALUE_8',
        drn_0: 'VALUE_8',
        dudclc_0: 'VALUE_8',
        ime_0: 'VALUE_8',
        bpaadd_0: 'VALUE_8',
        bpdaddlig_0: 'VALUE_8',
        dlvinvnot_0: 'VALUE_8',
        lnd_0: 'VALUE_8',
        zlivpart_0: 'VALUE_8',
        rtnlinnbr_0: 'VALUE_8',
        rtnsta_0: 1,
        xncflg_0: 'VALUE_8',
        etd_0: 'VALUE_8',
        eta_0: 'VALUE_8',
        sdhcat_0: 'VALUE_8',
        orifcy_0: 'VALUE_8',
        geocod_0: 'VALUE_8',
        insctyflg_0: 'VALUE_8',
        ffwadd_0: 'VALUE_8',
        dlvinvati_0: 'VALUE_8',
        xvaldat_0: new Date().toISOString().split('T')[0],
        cai_0: 'VALUE_8',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_8',
        sco_0: 'VALUE_8',
        glbdoctyp_0: 'VALUE_8',
        bolnum_0: 'VALUE_8',
        x4sbi_0: 'VALUE_8',
        x4tierslog_0: 'VALUE_8',
        x4sdhnum_0: 'VALUE_8',
        die_0: 'VALUE_8',
        dlvinvnotl_0: 'VALUE_8',
        dlvinvatil_0: 'VALUE_8',
        x_nbedit_0: 'VALUE_8',
        dsptotwei_0: 'VALUE_8',
        dsptotvol_0: 'VALUE_8',
        entcod_0: 'VALUE_8',
        betcpy_0: 'VALUE_8',
        cndnam_0: 'VALUE_8',
        x1colman_0: 'VALUE_8',
        trscod_0: 'VALUE_8',
        bpiposcod_0: 'VALUE_8',
        bpicry_0: 'VALUE_8',
        bpicrynam_0: 'VALUE_8',
        betfcy_0: 'VALUE_8',
        vol_0: 'VALUE_8',
        pacnbr_0: 'VALUE_8',
        eecsch_0: 'VALUE_8',
        pjt_0: 'VALUE_8',
        invflg_0: 'VALUE_8',
        zflgedisdh_0: 'VALUE_8',
        ynavette_0: 'VALUE_8',
        x4sdhenvaut_0: 'VALUE_8',
        x4flgdup_0: 'VALUE_8',
        x4rgop_0: 'VALUE_8',
        xexptransb_0: 'VALUE_8',
        x4contratmaf_0: 'VALUE_8',
        x4nbrml_0: 'VALUE_8',
        x4tarachlck_0: 'VALUE_8',
        x4tarvenlck_0: 'VALUE_8',
        dpedat_0: new Date().toISOString().split('T')[0],
        trllicplate_0: 'VALUE_8',
        x1nbum_0: 'VALUE_8',
        glbdoc_0: 'VALUE_8',
        glbdocnum_0: 'VALUE_8',
        glbdocdat_0: new Date().toISOString().split('T')[0],
        atdtcod_0: 'VALUE_8',
        mandoc_0: 'VALUE_8',
        arvdat_0: new Date().toISOString().split('T')[0],
        xdlvdat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sfisstcod_0: 'VALUE_8',
        sstentcod_0: 'VALUE_8',
        bpainv_0: 'VALUE_8',
        dlvnotl_0: 'VALUE_8',
        dlvatil_0: 'VALUE_8',
        xsitemad_0: 'VALUE_8',
        xdemdlvref_0: 'VALUE_8',
        xsphtex2_0: 'VALUE_8',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_8',
        xtimmes_0: new Date().toISOString(),
        auuid_0: 'VALUE_8',
        x4achtrtar_0: 'VALUE_8',
        x4cmr_0: 'VALUE_8',
        x4poiapp_0: 'VALUE_8',
        x4poiappuom_0: 'VALUE_8',
        x4tartrs_0: 'VALUE_8',
        xblexterne_0: 'VALUE_8',
        xexpedi_0: 'VALUE_8',
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        tmpsdhnum_0: 'SDE0009',
        x4numdemand_0: 'VALUE_9',
        sisdat_0: new Date().toISOString().split('T')[0],
        xsphtex1_0: 'VALUE_9',
        x4intident_0: 'VALUE_9',
        xgenfactis_0: 'VALUE_9',
        xmodgfi_0: 'VALUE_9',
        x4numint_0: 'VALUE_9',
        trsfam_0: 'VALUE_9',
        cninam_0: 'Contact facture 9',
        cretim_0: new Date().toISOString(),
        vtt_0: 'VALUE_9',
        prptex2_0: 'VALUE_9',
        sdhtex1_0: 'VALUE_9',
        sdhtex2_0: 'VALUE_9',
        tsccod_0: 'VALUE_9',
        prityp_0: 94.5,
        invdtalin_0: 'VALUE_9',
        licplate_0: 'VALUE_9',
        bpcinv_0: 'VALUE_9',
        bpcgru_0: 'VALUE_9',
        dep_0: 'VALUE_9',
        linnbr_0: 'VALUE_9',
        dsptotqty_0: 94.5,
        bpieecnum_0: 'VALUE_9',
        eecnumdeb_0: 'VALUE_9',
        prhfcy_0: 'VALUE_9',
        invdtadsp_0: 'VALUE_9',
        invdtaamt_0: 94.5,
        eectrn_0: 'VALUE_9',
        sihnum_0: 'VALUE_9',
        eecnat_0: 'VALUE_9',
        eecict_0: 'VALUE_9',
        bpcloc_0: 'VALUE_9',
        prnnpr_0: 'VALUE_9',
        x4sdhexp_0: 'VALUE_9',
        salfcy_0: 'VALUE_9',
        prfnum_0: 'VALUE_9',
        dlvdat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_9',
        amttax_0: 94.5,
        bastax_0: 9,
        invper_0: 'VALUE_9',
        x4cscode_0: 'VALUE_9',
        bpcpyr_0: 'VALUE_9',
        lbenum_0: 'VALUE_9',
        sdhnum_0: 'VALUE_9',
        sohnum_0: 'VALUE_9',
        netwei_0: 'VALUE_9',
        sdhtyp_0: 'VALUE_9',
        shidat_0: new Date().toISOString().split('T')[0],
        dlvhou_0: 'VALUE_9',
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_9',
        bpdcrynam_0: 'VALUE_9',
        chgtyp_0: 'VALUE_9',
        invdtatyp_0: 'VALUE_9',
        rep_0: 'VALUE_9',
        chgrat_0: 'VALUE_9',
        plistc_0: 'VALUE_9',
        cce_0: 'VALUE_9',
        cpy_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        shihou_0: 'VALUE_9',
        dlvnot_0: 'VALUE_9',
        dlvati_0: 'VALUE_9',
        pacflg_0: 'VALUE_9',
        updusr_0: 'VALUE_9',
        sisnum_0: 'VALUE_9',
        xblocage_0: 'VALUE_9',
        copnbr_0: 'VALUE_9',
        eecloc_0: 'VALUE_9',
        daylti_0: 'VALUE_9',
        houlti_0: 'VALUE_9',
        nprflg_0: 'VALUE_9',
        ndeflg_0: 'VALUE_9',
        bpdsat_0: 'VALUE_9',
        invorn_0: 'VALUE_9',
        adrval_0: 'VALUE_9',
        bpinam_0: 'VALUE_9',
        bpiaddlig_0: 'VALUE_9',
        bpicty_0: 'VALUE_9',
        bpdposcod_0: 'VALUE_9',
        bpdcty_0: 'VALUE_9',
        bpdcry_0: 'VALUE_9',
        bpcord_0: 'VALUE_9',
        ffwnum_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        lan_0: 'VALUE_9',
        bpisat_0: 'VALUE_9',
        bptnum_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        discrgtyp_0: 'VALUE_9',
        x4sdhdest_0: 'VALUE_9',
        invdta_0: 'VALUE_9',
        vacbpr_0: 'VALUE_9',
        stofcy_0: 'VALUE_9',
        x4achtrart_0: 'VALUE_9',
        weu_0: 'VALUE_9',
        dspweu_0: 'VALUE_9',
        pte_0: 'VALUE_9',
        cur_0: 'VALUE_9',
        vou_0: 'VALUE_9',
        dspvou_0: 'VALUE_9',
        ntrflg_0: 'VALUE_9',
        prnnde_0: 'VALUE_9',
        growei_0: 'VALUE_9',
        cfmflg_0: 'VALUE_9',
        prptex1_0: 'VALUE_9',
        mdl_0: 'VALUE_9',
        drn_0: 'VALUE_9',
        dudclc_0: 'VALUE_9',
        ime_0: 'VALUE_9',
        bpaadd_0: 'VALUE_9',
        bpdaddlig_0: 'VALUE_9',
        dlvinvnot_0: 'VALUE_9',
        lnd_0: 'VALUE_9',
        zlivpart_0: 'VALUE_9',
        rtnlinnbr_0: 'VALUE_9',
        rtnsta_0: 1,
        xncflg_0: 'VALUE_9',
        etd_0: 'VALUE_9',
        eta_0: 'VALUE_9',
        sdhcat_0: 'VALUE_9',
        orifcy_0: 'VALUE_9',
        geocod_0: 'VALUE_9',
        insctyflg_0: 'VALUE_9',
        ffwadd_0: 'VALUE_9',
        dlvinvati_0: 'VALUE_9',
        xvaldat_0: new Date().toISOString().split('T')[0],
        cai_0: 'VALUE_9',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_9',
        sco_0: 'VALUE_9',
        glbdoctyp_0: 'VALUE_9',
        bolnum_0: 'VALUE_9',
        x4sbi_0: 'VALUE_9',
        x4tierslog_0: 'VALUE_9',
        x4sdhnum_0: 'VALUE_9',
        die_0: 'VALUE_9',
        dlvinvnotl_0: 'VALUE_9',
        dlvinvatil_0: 'VALUE_9',
        x_nbedit_0: 'VALUE_9',
        dsptotwei_0: 'VALUE_9',
        dsptotvol_0: 'VALUE_9',
        entcod_0: 'VALUE_9',
        betcpy_0: 'VALUE_9',
        cndnam_0: 'VALUE_9',
        x1colman_0: 'VALUE_9',
        trscod_0: 'VALUE_9',
        bpiposcod_0: 'VALUE_9',
        bpicry_0: 'VALUE_9',
        bpicrynam_0: 'VALUE_9',
        betfcy_0: 'VALUE_9',
        vol_0: 'VALUE_9',
        pacnbr_0: 'VALUE_9',
        eecsch_0: 'VALUE_9',
        pjt_0: 'VALUE_9',
        invflg_0: 'VALUE_9',
        zflgedisdh_0: 'VALUE_9',
        ynavette_0: 'VALUE_9',
        x4sdhenvaut_0: 'VALUE_9',
        x4flgdup_0: 'VALUE_9',
        x4rgop_0: 'VALUE_9',
        xexptransb_0: 'VALUE_9',
        x4contratmaf_0: 'VALUE_9',
        x4nbrml_0: 'VALUE_9',
        x4tarachlck_0: 'VALUE_9',
        x4tarvenlck_0: 'VALUE_9',
        dpedat_0: new Date().toISOString().split('T')[0],
        trllicplate_0: 'VALUE_9',
        x1nbum_0: 'VALUE_9',
        glbdoc_0: 'VALUE_9',
        glbdocnum_0: 'VALUE_9',
        glbdocdat_0: new Date().toISOString().split('T')[0],
        atdtcod_0: 'VALUE_9',
        mandoc_0: 'VALUE_9',
        arvdat_0: new Date().toISOString().split('T')[0],
        xdlvdat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sfisstcod_0: 'VALUE_9',
        sstentcod_0: 'VALUE_9',
        bpainv_0: 'VALUE_9',
        dlvnotl_0: 'VALUE_9',
        dlvatil_0: 'VALUE_9',
        xsitemad_0: 'VALUE_9',
        xdemdlvref_0: 'VALUE_9',
        xsphtex2_0: 'VALUE_9',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_9',
        xtimmes_0: new Date().toISOString(),
        auuid_0: 'VALUE_9',
        x4achtrtar_0: 'VALUE_9',
        x4cmr_0: 'VALUE_9',
        x4poiapp_0: 'VALUE_9',
        x4poiappuom_0: 'VALUE_9',
        x4tartrs_0: 'VALUE_9',
        xblexterne_0: 'VALUE_9',
        xexpedi_0: 'VALUE_9',
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        tmpsdhnum_0: 'SDE0010',
        x4numdemand_0: 'VALUE_10',
        sisdat_0: new Date().toISOString().split('T')[0],
        xsphtex1_0: 'VALUE_10',
        x4intident_0: 'VALUE_10',
        xgenfactis_0: 'VALUE_10',
        xmodgfi_0: 'VALUE_10',
        x4numint_0: 'VALUE_10',
        trsfam_0: 'VALUE_10',
        cninam_0: 'Contact facture 10',
        cretim_0: new Date().toISOString(),
        vtt_0: 'VALUE_10',
        prptex2_0: 'VALUE_10',
        sdhtex1_0: 'VALUE_10',
        sdhtex2_0: 'VALUE_10',
        tsccod_0: 'VALUE_10',
        prityp_0: 105.0,
        invdtalin_0: 'VALUE_10',
        licplate_0: 'VALUE_10',
        bpcinv_0: 'VALUE_10',
        bpcgru_0: 'VALUE_10',
        dep_0: 'VALUE_10',
        linnbr_0: 'VALUE_10',
        dsptotqty_0: 105.0,
        bpieecnum_0: 'VALUE_10',
        eecnumdeb_0: 'VALUE_10',
        prhfcy_0: 'VALUE_10',
        invdtadsp_0: 'VALUE_10',
        invdtaamt_0: 105.0,
        eectrn_0: 'VALUE_10',
        sihnum_0: 'VALUE_10',
        eecnat_0: 'VALUE_10',
        eecict_0: 'VALUE_10',
        bpcloc_0: 'VALUE_10',
        prnnpr_0: 'VALUE_10',
        x4sdhexp_0: 'VALUE_10',
        salfcy_0: 'VALUE_10',
        prfnum_0: 'VALUE_10',
        dlvdat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_10',
        amttax_0: 105.0,
        bastax_0: 10,
        invper_0: 'VALUE_10',
        x4cscode_0: 'VALUE_10',
        bpcpyr_0: 'VALUE_10',
        lbenum_0: 'VALUE_10',
        sdhnum_0: 'VALUE_10',
        sohnum_0: 'VALUE_10',
        netwei_0: 'VALUE_10',
        sdhtyp_0: 'VALUE_10',
        shidat_0: new Date().toISOString().split('T')[0],
        dlvhou_0: 'VALUE_10',
        lndrtndat_0: new Date().toISOString().split('T')[0],
        bpdnam_0: 'VALUE_10',
        bpdcrynam_0: 'VALUE_10',
        chgtyp_0: 'VALUE_10',
        invdtatyp_0: 'VALUE_10',
        rep_0: 'VALUE_10',
        chgrat_0: 'VALUE_10',
        plistc_0: 'VALUE_10',
        cce_0: 'VALUE_10',
        cpy_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        shihou_0: 'VALUE_10',
        dlvnot_0: 'VALUE_10',
        dlvati_0: 'VALUE_10',
        pacflg_0: 'VALUE_10',
        updusr_0: 'VALUE_10',
        sisnum_0: 'VALUE_10',
        xblocage_0: 'VALUE_10',
        copnbr_0: 'VALUE_10',
        eecloc_0: 'VALUE_10',
        daylti_0: 'VALUE_10',
        houlti_0: 'VALUE_10',
        nprflg_0: 'VALUE_10',
        ndeflg_0: 'VALUE_10',
        bpdsat_0: 'VALUE_10',
        invorn_0: 'VALUE_10',
        adrval_0: 'VALUE_10',
        bpinam_0: 'VALUE_10',
        bpiaddlig_0: 'VALUE_10',
        bpicty_0: 'VALUE_10',
        bpdposcod_0: 'VALUE_10',
        bpdcty_0: 'VALUE_10',
        bpdcry_0: 'VALUE_10',
        bpcord_0: 'VALUE_10',
        ffwnum_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        lan_0: 'VALUE_10',
        bpisat_0: 'VALUE_10',
        bptnum_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        discrgtyp_0: 'VALUE_10',
        x4sdhdest_0: 'VALUE_10',
        invdta_0: 'VALUE_10',
        vacbpr_0: 'VALUE_10',
        stofcy_0: 'VALUE_10',
        x4achtrart_0: 'VALUE_10',
        weu_0: 'VALUE_10',
        dspweu_0: 'VALUE_10',
        pte_0: 'VALUE_10',
        cur_0: 'VALUE_10',
        vou_0: 'VALUE_10',
        dspvou_0: 'VALUE_10',
        ntrflg_0: 'VALUE_10',
        prnnde_0: 'VALUE_10',
        growei_0: 'VALUE_10',
        cfmflg_0: 'VALUE_10',
        prptex1_0: 'VALUE_10',
        mdl_0: 'VALUE_10',
        drn_0: 'VALUE_10',
        dudclc_0: 'VALUE_10',
        ime_0: 'VALUE_10',
        bpaadd_0: 'VALUE_10',
        bpdaddlig_0: 'VALUE_10',
        dlvinvnot_0: 'VALUE_10',
        lnd_0: 'VALUE_10',
        zlivpart_0: 'VALUE_10',
        rtnlinnbr_0: 'VALUE_10',
        rtnsta_0: 1,
        xncflg_0: 'VALUE_10',
        etd_0: 'VALUE_10',
        eta_0: 'VALUE_10',
        sdhcat_0: 'VALUE_10',
        orifcy_0: 'VALUE_10',
        geocod_0: 'VALUE_10',
        insctyflg_0: 'VALUE_10',
        ffwadd_0: 'VALUE_10',
        dlvinvati_0: 'VALUE_10',
        xvaldat_0: new Date().toISOString().split('T')[0],
        cai_0: 'VALUE_10',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_10',
        sco_0: 'VALUE_10',
        glbdoctyp_0: 'VALUE_10',
        bolnum_0: 'VALUE_10',
        x4sbi_0: 'VALUE_10',
        x4tierslog_0: 'VALUE_10',
        x4sdhnum_0: 'VALUE_10',
        die_0: 'VALUE_10',
        dlvinvnotl_0: 'VALUE_10',
        dlvinvatil_0: 'VALUE_10',
        x_nbedit_0: 'VALUE_10',
        dsptotwei_0: 'VALUE_10',
        dsptotvol_0: 'VALUE_10',
        entcod_0: 'VALUE_10',
        betcpy_0: 'VALUE_10',
        cndnam_0: 'VALUE_10',
        x1colman_0: 'VALUE_10',
        trscod_0: 'VALUE_10',
        bpiposcod_0: 'VALUE_10',
        bpicry_0: 'VALUE_10',
        bpicrynam_0: 'VALUE_10',
        betfcy_0: 'VALUE_10',
        vol_0: 'VALUE_10',
        pacnbr_0: 'VALUE_10',
        eecsch_0: 'VALUE_10',
        pjt_0: 'VALUE_10',
        invflg_0: 'VALUE_10',
        zflgedisdh_0: 'VALUE_10',
        ynavette_0: 'VALUE_10',
        x4sdhenvaut_0: 'VALUE_10',
        x4flgdup_0: 'VALUE_10',
        x4rgop_0: 'VALUE_10',
        xexptransb_0: 'VALUE_10',
        x4contratmaf_0: 'VALUE_10',
        x4nbrml_0: 'VALUE_10',
        x4tarachlck_0: 'VALUE_10',
        x4tarvenlck_0: 'VALUE_10',
        dpedat_0: new Date().toISOString().split('T')[0],
        trllicplate_0: 'VALUE_10',
        x1nbum_0: 'VALUE_10',
        glbdoc_0: 'VALUE_10',
        glbdocnum_0: 'VALUE_10',
        glbdocdat_0: new Date().toISOString().split('T')[0],
        atdtcod_0: 'VALUE_10',
        mandoc_0: 'VALUE_10',
        arvdat_0: new Date().toISOString().split('T')[0],
        xdlvdat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sfisstcod_0: 'VALUE_10',
        sstentcod_0: 'VALUE_10',
        bpainv_0: 'VALUE_10',
        dlvnotl_0: 'VALUE_10',
        dlvatil_0: 'VALUE_10',
        xsitemad_0: 'VALUE_10',
        xdemdlvref_0: 'VALUE_10',
        xsphtex2_0: 'VALUE_10',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_10',
        xtimmes_0: new Date().toISOString(),
        auuid_0: 'VALUE_10',
        x4achtrtar_0: 'VALUE_10',
        x4cmr_0: 'VALUE_10',
        x4poiapp_0: 'VALUE_10',
        x4poiappuom_0: 'VALUE_10',
        x4tartrs_0: 'VALUE_10',
        xblexterne_0: 'VALUE_10',
        xexpedi_0: 'VALUE_10',
      },
    ]

    await Database.table('sdelivery').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans sdelivery`)
  }
}
