import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour SDELIVERYD
    const data = [
      {
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_1',
        itmdes1_0: 'Désignation article 1',
        rcpqtystu_0: 10.5,
        xflaglm_0: 'VALUE_1',
        soplin_0: 'VALUE_1',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_1',
        vtc_0: 'VALUE_1',
        taxgeoflg_0: 'VALUE_1',
        taxflg_0: 'VALUE_1',
        taxregflg_0: 'VALUE_1',
        tsicod_0: 'VALUE_1',
        clcamt2_0: 10.5,
        repcoe_0: 'VALUE_1',
        gropri_0: 10.5,
        priren_0: 10.5,
        vat_0: 'VALUE_1',
        clcamt1_0: 10.5,
        prptex_0: 'VALUE_1',
        rep1_0: 'VALUE_1',
        rep2_0: 'VALUE_1',
        ddtanum_0: 'SDE0001',
        ddtanot_0: 'VALUE_1',
        prhnum_0: 'VALUE_1',
        netpri_0: 10.5,
        qty_0: 10.5,
        wrh_0: 'VALUE_1',
        rtnqty_0: 10.5,
        sddtex_0: 'VALUE_1',
        sdhnum_0: 'VALUE_1',
        sohnum_0: 'VALUE_1',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_1',
        qtystu_0: 10.5,
        reprat1_0: 'VALUE_1',
        saustucoe_0: 'VALUE_1',
        useplc_0: 'VALUE_1',
        cpy_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_1',
        xovelab_0: 'VALUE_1',
        xovesco_0: 'VALUE_1',
        vcrlinori_0: 'VALUE_1',
        rattaxlin_0: 'VALUE_1',
        pckflg_0: 'VALUE_1',
        vcrseqori_0: 'VALUE_1',
        vcrtypori_0: 'VALUE_1',
        stu_0: 'VALUE_1',
        soqseq_0: 'VALUE_1',
        rtnqtystu_0: 10.5,
        sohcat_0: 'VALUE_1',
        bpcord_0: 'VALUE_1',
        xcusordref_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        orilin_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        xversion_0: 'VALUE_1',
        stofcy_0: 'VALUE_1',
        itmref_0: 'VALUE_1',
        weu_0: 'VALUE_1',
        dspweu_0: 'VALUE_1',
        stomgtcod_0: 'VALUE_1',
        pfm_0: 'VALUE_1',
        dspvou_0: 'VALUE_1',
        discrgval8_0: 'VALUE_1',
        discrgval9_0: 'VALUE_1',
        discrgren1_0: 'VALUE_1',
        discrgren2_0: 'VALUE_1',
        discrgren3_0: 'VALUE_1',
        discrgren4_0: 'VALUE_1',
        discrgren5_0: 'VALUE_1',
        discrgren6_0: 'VALUE_1',
        discrgval1_0: 'VALUE_1',
        discrgval2_0: 'VALUE_1',
        discrgval3_0: 'VALUE_1',
        discrgval4_0: 'VALUE_1',
        lincfmflg_0: 'VALUE_1',
        discrgval5_0: 'VALUE_1',
        cprpri_0: 10.5,
        bpaadd_0: 'VALUE_1',
        ndeprnbom_0: 'VALUE_1',
        invprnbom_0: 'VALUE_1',
        netprinot_0: 10.5,
        netpriati_0: 10.5,
        x4qtyfac_0: 10.5,
        impnumlig_0: 'VALUE_1',
        sdhcat_0: 'VALUE_1',
        untwei_0: 'VALUE_1',
        geocod_0: 'VALUE_1',
        insctyflg_0: 'VALUE_1',
        itmdes_0: 'VALUE_1',
        bastaxlin_0: 1,
        rcpflg_0: 'VALUE_1',
        xmatcst_0: 'VALUE_1',
        xmaccst_0: 'VALUE_1',
        xlabcst_0: 'VALUE_1',
        xscocst_0: 'VALUE_1',
        xovemat_0: 'VALUE_1',
        xovemac_0: 'VALUE_1',
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xligori_0: 'VALUE_1',
        x4desadvlog_0: 'VALUE_1',
        vcrnumori_0: 'VALUE_1',
        pacqtystu_0: 10.5,
        dsplinvol_0: 'VALUE_1',
        xtext0_0: 'VALUE_1',
        xkanban_0: 'VALUE_1',
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        dsplinwei_0: 'VALUE_1',
        lot_0: 'VALUE_1',
        sta_0: 1,
        loc_0: 'VALUE_1',
        wrtqty_0: 10.5,
        wrtqtystu_0: 10.5,
        oalqtystu_0: 10.5,
        focflg_0: 'VALUE_1',
        sddlin_0: 'VALUE_1',
        sau_0: 'VALUE_1',
        lintyp_0: 'VALUE_1',
        pckcap_0: 'VALUE_1',
        pjt_0: 'VALUE_1',
        discrgren7_0: 'VALUE_1',
        discrgren8_0: 'VALUE_1',
        discrgren9_0: 'VALUE_1',
        reprat2_0: 'VALUE_1',
        x4facok_0: 'VALUE_1',
        pck_0: 'VALUE_1',
        discrgval6_0: 'VALUE_1',
        discrgval7_0: 'VALUE_1',
        xligmerori_0: 'VALUE_1',
        xssligori_0: 'VALUE_1',
        x4rgopl_0: 'VALUE_1',
        x4exclrfad_0: 'VALUE_1',
        xdestfin_0: 'VALUE_1',
        xdesint_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sstcod_0: 'VALUE_1',
        eccvalmin_0: 'VALUE_1',
        eccvalmaj_0: 'VALUE_1',
        prelin_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        xalert_0: 'VALUE_1',
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_1',
        xpntmonte_0: 'VALUE_1',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_2',
        itmdes1_0: 'Désignation article 2',
        rcpqtystu_0: 21.0,
        xflaglm_0: 'VALUE_2',
        soplin_0: 'VALUE_2',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_2',
        vtc_0: 'VALUE_2',
        taxgeoflg_0: 'VALUE_2',
        taxflg_0: 'VALUE_2',
        taxregflg_0: 'VALUE_2',
        tsicod_0: 'VALUE_2',
        clcamt2_0: 21.0,
        repcoe_0: 'VALUE_2',
        gropri_0: 21.0,
        priren_0: 21.0,
        vat_0: 'VALUE_2',
        clcamt1_0: 21.0,
        prptex_0: 'VALUE_2',
        rep1_0: 'VALUE_2',
        rep2_0: 'VALUE_2',
        ddtanum_0: 'SDE0002',
        ddtanot_0: 'VALUE_2',
        prhnum_0: 'VALUE_2',
        netpri_0: 21.0,
        qty_0: 21.0,
        wrh_0: 'VALUE_2',
        rtnqty_0: 21.0,
        sddtex_0: 'VALUE_2',
        sdhnum_0: 'VALUE_2',
        sohnum_0: 'VALUE_2',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_2',
        qtystu_0: 21.0,
        reprat1_0: 'VALUE_2',
        saustucoe_0: 'VALUE_2',
        useplc_0: 'VALUE_2',
        cpy_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_2',
        xovelab_0: 'VALUE_2',
        xovesco_0: 'VALUE_2',
        vcrlinori_0: 'VALUE_2',
        rattaxlin_0: 'VALUE_2',
        pckflg_0: 'VALUE_2',
        vcrseqori_0: 'VALUE_2',
        vcrtypori_0: 'VALUE_2',
        stu_0: 'VALUE_2',
        soqseq_0: 'VALUE_2',
        rtnqtystu_0: 21.0,
        sohcat_0: 'VALUE_2',
        bpcord_0: 'VALUE_2',
        xcusordref_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        orilin_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        xversion_0: 'VALUE_2',
        stofcy_0: 'VALUE_2',
        itmref_0: 'VALUE_2',
        weu_0: 'VALUE_2',
        dspweu_0: 'VALUE_2',
        stomgtcod_0: 'VALUE_2',
        pfm_0: 'VALUE_2',
        dspvou_0: 'VALUE_2',
        discrgval8_0: 'VALUE_2',
        discrgval9_0: 'VALUE_2',
        discrgren1_0: 'VALUE_2',
        discrgren2_0: 'VALUE_2',
        discrgren3_0: 'VALUE_2',
        discrgren4_0: 'VALUE_2',
        discrgren5_0: 'VALUE_2',
        discrgren6_0: 'VALUE_2',
        discrgval1_0: 'VALUE_2',
        discrgval2_0: 'VALUE_2',
        discrgval3_0: 'VALUE_2',
        discrgval4_0: 'VALUE_2',
        lincfmflg_0: 'VALUE_2',
        discrgval5_0: 'VALUE_2',
        cprpri_0: 21.0,
        bpaadd_0: 'VALUE_2',
        ndeprnbom_0: 'VALUE_2',
        invprnbom_0: 'VALUE_2',
        netprinot_0: 21.0,
        netpriati_0: 21.0,
        x4qtyfac_0: 21.0,
        impnumlig_0: 'VALUE_2',
        sdhcat_0: 'VALUE_2',
        untwei_0: 'VALUE_2',
        geocod_0: 'VALUE_2',
        insctyflg_0: 'VALUE_2',
        itmdes_0: 'VALUE_2',
        bastaxlin_0: 2,
        rcpflg_0: 'VALUE_2',
        xmatcst_0: 'VALUE_2',
        xmaccst_0: 'VALUE_2',
        xlabcst_0: 'VALUE_2',
        xscocst_0: 'VALUE_2',
        xovemat_0: 'VALUE_2',
        xovemac_0: 'VALUE_2',
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xligori_0: 'VALUE_2',
        x4desadvlog_0: 'VALUE_2',
        vcrnumori_0: 'VALUE_2',
        pacqtystu_0: 21.0,
        dsplinvol_0: 'VALUE_2',
        xtext0_0: 'VALUE_2',
        xkanban_0: 'VALUE_2',
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        dsplinwei_0: 'VALUE_2',
        lot_0: 'VALUE_2',
        sta_0: 1,
        loc_0: 'VALUE_2',
        wrtqty_0: 21.0,
        wrtqtystu_0: 21.0,
        oalqtystu_0: 21.0,
        focflg_0: 'VALUE_2',
        sddlin_0: 'VALUE_2',
        sau_0: 'VALUE_2',
        lintyp_0: 'VALUE_2',
        pckcap_0: 'VALUE_2',
        pjt_0: 'VALUE_2',
        discrgren7_0: 'VALUE_2',
        discrgren8_0: 'VALUE_2',
        discrgren9_0: 'VALUE_2',
        reprat2_0: 'VALUE_2',
        x4facok_0: 'VALUE_2',
        pck_0: 'VALUE_2',
        discrgval6_0: 'VALUE_2',
        discrgval7_0: 'VALUE_2',
        xligmerori_0: 'VALUE_2',
        xssligori_0: 'VALUE_2',
        x4rgopl_0: 'VALUE_2',
        x4exclrfad_0: 'VALUE_2',
        xdestfin_0: 'VALUE_2',
        xdesint_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sstcod_0: 'VALUE_2',
        eccvalmin_0: 'VALUE_2',
        eccvalmaj_0: 'VALUE_2',
        prelin_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        xalert_0: 'VALUE_2',
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_2',
        xpntmonte_0: 'VALUE_2',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_3',
        itmdes1_0: 'Désignation article 3',
        rcpqtystu_0: 31.5,
        xflaglm_0: 'VALUE_3',
        soplin_0: 'VALUE_3',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_3',
        vtc_0: 'VALUE_3',
        taxgeoflg_0: 'VALUE_3',
        taxflg_0: 'VALUE_3',
        taxregflg_0: 'VALUE_3',
        tsicod_0: 'VALUE_3',
        clcamt2_0: 31.5,
        repcoe_0: 'VALUE_3',
        gropri_0: 31.5,
        priren_0: 31.5,
        vat_0: 'VALUE_3',
        clcamt1_0: 31.5,
        prptex_0: 'VALUE_3',
        rep1_0: 'VALUE_3',
        rep2_0: 'VALUE_3',
        ddtanum_0: 'SDE0003',
        ddtanot_0: 'VALUE_3',
        prhnum_0: 'VALUE_3',
        netpri_0: 31.5,
        qty_0: 31.5,
        wrh_0: 'VALUE_3',
        rtnqty_0: 31.5,
        sddtex_0: 'VALUE_3',
        sdhnum_0: 'VALUE_3',
        sohnum_0: 'VALUE_3',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_3',
        qtystu_0: 31.5,
        reprat1_0: 'VALUE_3',
        saustucoe_0: 'VALUE_3',
        useplc_0: 'VALUE_3',
        cpy_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_3',
        xovelab_0: 'VALUE_3',
        xovesco_0: 'VALUE_3',
        vcrlinori_0: 'VALUE_3',
        rattaxlin_0: 'VALUE_3',
        pckflg_0: 'VALUE_3',
        vcrseqori_0: 'VALUE_3',
        vcrtypori_0: 'VALUE_3',
        stu_0: 'VALUE_3',
        soqseq_0: 'VALUE_3',
        rtnqtystu_0: 31.5,
        sohcat_0: 'VALUE_3',
        bpcord_0: 'VALUE_3',
        xcusordref_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        orilin_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        xversion_0: 'VALUE_3',
        stofcy_0: 'VALUE_3',
        itmref_0: 'VALUE_3',
        weu_0: 'VALUE_3',
        dspweu_0: 'VALUE_3',
        stomgtcod_0: 'VALUE_3',
        pfm_0: 'VALUE_3',
        dspvou_0: 'VALUE_3',
        discrgval8_0: 'VALUE_3',
        discrgval9_0: 'VALUE_3',
        discrgren1_0: 'VALUE_3',
        discrgren2_0: 'VALUE_3',
        discrgren3_0: 'VALUE_3',
        discrgren4_0: 'VALUE_3',
        discrgren5_0: 'VALUE_3',
        discrgren6_0: 'VALUE_3',
        discrgval1_0: 'VALUE_3',
        discrgval2_0: 'VALUE_3',
        discrgval3_0: 'VALUE_3',
        discrgval4_0: 'VALUE_3',
        lincfmflg_0: 'VALUE_3',
        discrgval5_0: 'VALUE_3',
        cprpri_0: 31.5,
        bpaadd_0: 'VALUE_3',
        ndeprnbom_0: 'VALUE_3',
        invprnbom_0: 'VALUE_3',
        netprinot_0: 31.5,
        netpriati_0: 31.5,
        x4qtyfac_0: 31.5,
        impnumlig_0: 'VALUE_3',
        sdhcat_0: 'VALUE_3',
        untwei_0: 'VALUE_3',
        geocod_0: 'VALUE_3',
        insctyflg_0: 'VALUE_3',
        itmdes_0: 'VALUE_3',
        bastaxlin_0: 3,
        rcpflg_0: 'VALUE_3',
        xmatcst_0: 'VALUE_3',
        xmaccst_0: 'VALUE_3',
        xlabcst_0: 'VALUE_3',
        xscocst_0: 'VALUE_3',
        xovemat_0: 'VALUE_3',
        xovemac_0: 'VALUE_3',
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xligori_0: 'VALUE_3',
        x4desadvlog_0: 'VALUE_3',
        vcrnumori_0: 'VALUE_3',
        pacqtystu_0: 31.5,
        dsplinvol_0: 'VALUE_3',
        xtext0_0: 'VALUE_3',
        xkanban_0: 'VALUE_3',
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        dsplinwei_0: 'VALUE_3',
        lot_0: 'VALUE_3',
        sta_0: 1,
        loc_0: 'VALUE_3',
        wrtqty_0: 31.5,
        wrtqtystu_0: 31.5,
        oalqtystu_0: 31.5,
        focflg_0: 'VALUE_3',
        sddlin_0: 'VALUE_3',
        sau_0: 'VALUE_3',
        lintyp_0: 'VALUE_3',
        pckcap_0: 'VALUE_3',
        pjt_0: 'VALUE_3',
        discrgren7_0: 'VALUE_3',
        discrgren8_0: 'VALUE_3',
        discrgren9_0: 'VALUE_3',
        reprat2_0: 'VALUE_3',
        x4facok_0: 'VALUE_3',
        pck_0: 'VALUE_3',
        discrgval6_0: 'VALUE_3',
        discrgval7_0: 'VALUE_3',
        xligmerori_0: 'VALUE_3',
        xssligori_0: 'VALUE_3',
        x4rgopl_0: 'VALUE_3',
        x4exclrfad_0: 'VALUE_3',
        xdestfin_0: 'VALUE_3',
        xdesint_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sstcod_0: 'VALUE_3',
        eccvalmin_0: 'VALUE_3',
        eccvalmaj_0: 'VALUE_3',
        prelin_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        xalert_0: 'VALUE_3',
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_3',
        xpntmonte_0: 'VALUE_3',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_4',
        itmdes1_0: 'Désignation article 4',
        rcpqtystu_0: 42.0,
        xflaglm_0: 'VALUE_4',
        soplin_0: 'VALUE_4',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_4',
        vtc_0: 'VALUE_4',
        taxgeoflg_0: 'VALUE_4',
        taxflg_0: 'VALUE_4',
        taxregflg_0: 'VALUE_4',
        tsicod_0: 'VALUE_4',
        clcamt2_0: 42.0,
        repcoe_0: 'VALUE_4',
        gropri_0: 42.0,
        priren_0: 42.0,
        vat_0: 'VALUE_4',
        clcamt1_0: 42.0,
        prptex_0: 'VALUE_4',
        rep1_0: 'VALUE_4',
        rep2_0: 'VALUE_4',
        ddtanum_0: 'SDE0004',
        ddtanot_0: 'VALUE_4',
        prhnum_0: 'VALUE_4',
        netpri_0: 42.0,
        qty_0: 42.0,
        wrh_0: 'VALUE_4',
        rtnqty_0: 42.0,
        sddtex_0: 'VALUE_4',
        sdhnum_0: 'VALUE_4',
        sohnum_0: 'VALUE_4',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_4',
        qtystu_0: 42.0,
        reprat1_0: 'VALUE_4',
        saustucoe_0: 'VALUE_4',
        useplc_0: 'VALUE_4',
        cpy_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_4',
        xovelab_0: 'VALUE_4',
        xovesco_0: 'VALUE_4',
        vcrlinori_0: 'VALUE_4',
        rattaxlin_0: 'VALUE_4',
        pckflg_0: 'VALUE_4',
        vcrseqori_0: 'VALUE_4',
        vcrtypori_0: 'VALUE_4',
        stu_0: 'VALUE_4',
        soqseq_0: 'VALUE_4',
        rtnqtystu_0: 42.0,
        sohcat_0: 'VALUE_4',
        bpcord_0: 'VALUE_4',
        xcusordref_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        orilin_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        xversion_0: 'VALUE_4',
        stofcy_0: 'VALUE_4',
        itmref_0: 'VALUE_4',
        weu_0: 'VALUE_4',
        dspweu_0: 'VALUE_4',
        stomgtcod_0: 'VALUE_4',
        pfm_0: 'VALUE_4',
        dspvou_0: 'VALUE_4',
        discrgval8_0: 'VALUE_4',
        discrgval9_0: 'VALUE_4',
        discrgren1_0: 'VALUE_4',
        discrgren2_0: 'VALUE_4',
        discrgren3_0: 'VALUE_4',
        discrgren4_0: 'VALUE_4',
        discrgren5_0: 'VALUE_4',
        discrgren6_0: 'VALUE_4',
        discrgval1_0: 'VALUE_4',
        discrgval2_0: 'VALUE_4',
        discrgval3_0: 'VALUE_4',
        discrgval4_0: 'VALUE_4',
        lincfmflg_0: 'VALUE_4',
        discrgval5_0: 'VALUE_4',
        cprpri_0: 42.0,
        bpaadd_0: 'VALUE_4',
        ndeprnbom_0: 'VALUE_4',
        invprnbom_0: 'VALUE_4',
        netprinot_0: 42.0,
        netpriati_0: 42.0,
        x4qtyfac_0: 42.0,
        impnumlig_0: 'VALUE_4',
        sdhcat_0: 'VALUE_4',
        untwei_0: 'VALUE_4',
        geocod_0: 'VALUE_4',
        insctyflg_0: 'VALUE_4',
        itmdes_0: 'VALUE_4',
        bastaxlin_0: 4,
        rcpflg_0: 'VALUE_4',
        xmatcst_0: 'VALUE_4',
        xmaccst_0: 'VALUE_4',
        xlabcst_0: 'VALUE_4',
        xscocst_0: 'VALUE_4',
        xovemat_0: 'VALUE_4',
        xovemac_0: 'VALUE_4',
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xligori_0: 'VALUE_4',
        x4desadvlog_0: 'VALUE_4',
        vcrnumori_0: 'VALUE_4',
        pacqtystu_0: 42.0,
        dsplinvol_0: 'VALUE_4',
        xtext0_0: 'VALUE_4',
        xkanban_0: 'VALUE_4',
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        dsplinwei_0: 'VALUE_4',
        lot_0: 'VALUE_4',
        sta_0: 1,
        loc_0: 'VALUE_4',
        wrtqty_0: 42.0,
        wrtqtystu_0: 42.0,
        oalqtystu_0: 42.0,
        focflg_0: 'VALUE_4',
        sddlin_0: 'VALUE_4',
        sau_0: 'VALUE_4',
        lintyp_0: 'VALUE_4',
        pckcap_0: 'VALUE_4',
        pjt_0: 'VALUE_4',
        discrgren7_0: 'VALUE_4',
        discrgren8_0: 'VALUE_4',
        discrgren9_0: 'VALUE_4',
        reprat2_0: 'VALUE_4',
        x4facok_0: 'VALUE_4',
        pck_0: 'VALUE_4',
        discrgval6_0: 'VALUE_4',
        discrgval7_0: 'VALUE_4',
        xligmerori_0: 'VALUE_4',
        xssligori_0: 'VALUE_4',
        x4rgopl_0: 'VALUE_4',
        x4exclrfad_0: 'VALUE_4',
        xdestfin_0: 'VALUE_4',
        xdesint_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sstcod_0: 'VALUE_4',
        eccvalmin_0: 'VALUE_4',
        eccvalmaj_0: 'VALUE_4',
        prelin_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        xalert_0: 'VALUE_4',
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_4',
        xpntmonte_0: 'VALUE_4',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_5',
        itmdes1_0: 'Désignation article 5',
        rcpqtystu_0: 52.5,
        xflaglm_0: 'VALUE_5',
        soplin_0: 'VALUE_5',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_5',
        vtc_0: 'VALUE_5',
        taxgeoflg_0: 'VALUE_5',
        taxflg_0: 'VALUE_5',
        taxregflg_0: 'VALUE_5',
        tsicod_0: 'VALUE_5',
        clcamt2_0: 52.5,
        repcoe_0: 'VALUE_5',
        gropri_0: 52.5,
        priren_0: 52.5,
        vat_0: 'VALUE_5',
        clcamt1_0: 52.5,
        prptex_0: 'VALUE_5',
        rep1_0: 'VALUE_5',
        rep2_0: 'VALUE_5',
        ddtanum_0: 'SDE0005',
        ddtanot_0: 'VALUE_5',
        prhnum_0: 'VALUE_5',
        netpri_0: 52.5,
        qty_0: 52.5,
        wrh_0: 'VALUE_5',
        rtnqty_0: 52.5,
        sddtex_0: 'VALUE_5',
        sdhnum_0: 'VALUE_5',
        sohnum_0: 'VALUE_5',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_5',
        qtystu_0: 52.5,
        reprat1_0: 'VALUE_5',
        saustucoe_0: 'VALUE_5',
        useplc_0: 'VALUE_5',
        cpy_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_5',
        xovelab_0: 'VALUE_5',
        xovesco_0: 'VALUE_5',
        vcrlinori_0: 'VALUE_5',
        rattaxlin_0: 'VALUE_5',
        pckflg_0: 'VALUE_5',
        vcrseqori_0: 'VALUE_5',
        vcrtypori_0: 'VALUE_5',
        stu_0: 'VALUE_5',
        soqseq_0: 'VALUE_5',
        rtnqtystu_0: 52.5,
        sohcat_0: 'VALUE_5',
        bpcord_0: 'VALUE_5',
        xcusordref_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        orilin_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        xversion_0: 'VALUE_5',
        stofcy_0: 'VALUE_5',
        itmref_0: 'VALUE_5',
        weu_0: 'VALUE_5',
        dspweu_0: 'VALUE_5',
        stomgtcod_0: 'VALUE_5',
        pfm_0: 'VALUE_5',
        dspvou_0: 'VALUE_5',
        discrgval8_0: 'VALUE_5',
        discrgval9_0: 'VALUE_5',
        discrgren1_0: 'VALUE_5',
        discrgren2_0: 'VALUE_5',
        discrgren3_0: 'VALUE_5',
        discrgren4_0: 'VALUE_5',
        discrgren5_0: 'VALUE_5',
        discrgren6_0: 'VALUE_5',
        discrgval1_0: 'VALUE_5',
        discrgval2_0: 'VALUE_5',
        discrgval3_0: 'VALUE_5',
        discrgval4_0: 'VALUE_5',
        lincfmflg_0: 'VALUE_5',
        discrgval5_0: 'VALUE_5',
        cprpri_0: 52.5,
        bpaadd_0: 'VALUE_5',
        ndeprnbom_0: 'VALUE_5',
        invprnbom_0: 'VALUE_5',
        netprinot_0: 52.5,
        netpriati_0: 52.5,
        x4qtyfac_0: 52.5,
        impnumlig_0: 'VALUE_5',
        sdhcat_0: 'VALUE_5',
        untwei_0: 'VALUE_5',
        geocod_0: 'VALUE_5',
        insctyflg_0: 'VALUE_5',
        itmdes_0: 'VALUE_5',
        bastaxlin_0: 5,
        rcpflg_0: 'VALUE_5',
        xmatcst_0: 'VALUE_5',
        xmaccst_0: 'VALUE_5',
        xlabcst_0: 'VALUE_5',
        xscocst_0: 'VALUE_5',
        xovemat_0: 'VALUE_5',
        xovemac_0: 'VALUE_5',
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xligori_0: 'VALUE_5',
        x4desadvlog_0: 'VALUE_5',
        vcrnumori_0: 'VALUE_5',
        pacqtystu_0: 52.5,
        dsplinvol_0: 'VALUE_5',
        xtext0_0: 'VALUE_5',
        xkanban_0: 'VALUE_5',
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        dsplinwei_0: 'VALUE_5',
        lot_0: 'VALUE_5',
        sta_0: 1,
        loc_0: 'VALUE_5',
        wrtqty_0: 52.5,
        wrtqtystu_0: 52.5,
        oalqtystu_0: 52.5,
        focflg_0: 'VALUE_5',
        sddlin_0: 'VALUE_5',
        sau_0: 'VALUE_5',
        lintyp_0: 'VALUE_5',
        pckcap_0: 'VALUE_5',
        pjt_0: 'VALUE_5',
        discrgren7_0: 'VALUE_5',
        discrgren8_0: 'VALUE_5',
        discrgren9_0: 'VALUE_5',
        reprat2_0: 'VALUE_5',
        x4facok_0: 'VALUE_5',
        pck_0: 'VALUE_5',
        discrgval6_0: 'VALUE_5',
        discrgval7_0: 'VALUE_5',
        xligmerori_0: 'VALUE_5',
        xssligori_0: 'VALUE_5',
        x4rgopl_0: 'VALUE_5',
        x4exclrfad_0: 'VALUE_5',
        xdestfin_0: 'VALUE_5',
        xdesint_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sstcod_0: 'VALUE_5',
        eccvalmin_0: 'VALUE_5',
        eccvalmaj_0: 'VALUE_5',
        prelin_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        xalert_0: 'VALUE_5',
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_5',
        xpntmonte_0: 'VALUE_5',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_6',
        itmdes1_0: 'Désignation article 6',
        rcpqtystu_0: 63.0,
        xflaglm_0: 'VALUE_6',
        soplin_0: 'VALUE_6',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_6',
        vtc_0: 'VALUE_6',
        taxgeoflg_0: 'VALUE_6',
        taxflg_0: 'VALUE_6',
        taxregflg_0: 'VALUE_6',
        tsicod_0: 'VALUE_6',
        clcamt2_0: 63.0,
        repcoe_0: 'VALUE_6',
        gropri_0: 63.0,
        priren_0: 63.0,
        vat_0: 'VALUE_6',
        clcamt1_0: 63.0,
        prptex_0: 'VALUE_6',
        rep1_0: 'VALUE_6',
        rep2_0: 'VALUE_6',
        ddtanum_0: 'SDE0006',
        ddtanot_0: 'VALUE_6',
        prhnum_0: 'VALUE_6',
        netpri_0: 63.0,
        qty_0: 63.0,
        wrh_0: 'VALUE_6',
        rtnqty_0: 63.0,
        sddtex_0: 'VALUE_6',
        sdhnum_0: 'VALUE_6',
        sohnum_0: 'VALUE_6',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_6',
        qtystu_0: 63.0,
        reprat1_0: 'VALUE_6',
        saustucoe_0: 'VALUE_6',
        useplc_0: 'VALUE_6',
        cpy_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_6',
        xovelab_0: 'VALUE_6',
        xovesco_0: 'VALUE_6',
        vcrlinori_0: 'VALUE_6',
        rattaxlin_0: 'VALUE_6',
        pckflg_0: 'VALUE_6',
        vcrseqori_0: 'VALUE_6',
        vcrtypori_0: 'VALUE_6',
        stu_0: 'VALUE_6',
        soqseq_0: 'VALUE_6',
        rtnqtystu_0: 63.0,
        sohcat_0: 'VALUE_6',
        bpcord_0: 'VALUE_6',
        xcusordref_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        orilin_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        xversion_0: 'VALUE_6',
        stofcy_0: 'VALUE_6',
        itmref_0: 'VALUE_6',
        weu_0: 'VALUE_6',
        dspweu_0: 'VALUE_6',
        stomgtcod_0: 'VALUE_6',
        pfm_0: 'VALUE_6',
        dspvou_0: 'VALUE_6',
        discrgval8_0: 'VALUE_6',
        discrgval9_0: 'VALUE_6',
        discrgren1_0: 'VALUE_6',
        discrgren2_0: 'VALUE_6',
        discrgren3_0: 'VALUE_6',
        discrgren4_0: 'VALUE_6',
        discrgren5_0: 'VALUE_6',
        discrgren6_0: 'VALUE_6',
        discrgval1_0: 'VALUE_6',
        discrgval2_0: 'VALUE_6',
        discrgval3_0: 'VALUE_6',
        discrgval4_0: 'VALUE_6',
        lincfmflg_0: 'VALUE_6',
        discrgval5_0: 'VALUE_6',
        cprpri_0: 63.0,
        bpaadd_0: 'VALUE_6',
        ndeprnbom_0: 'VALUE_6',
        invprnbom_0: 'VALUE_6',
        netprinot_0: 63.0,
        netpriati_0: 63.0,
        x4qtyfac_0: 63.0,
        impnumlig_0: 'VALUE_6',
        sdhcat_0: 'VALUE_6',
        untwei_0: 'VALUE_6',
        geocod_0: 'VALUE_6',
        insctyflg_0: 'VALUE_6',
        itmdes_0: 'VALUE_6',
        bastaxlin_0: 6,
        rcpflg_0: 'VALUE_6',
        xmatcst_0: 'VALUE_6',
        xmaccst_0: 'VALUE_6',
        xlabcst_0: 'VALUE_6',
        xscocst_0: 'VALUE_6',
        xovemat_0: 'VALUE_6',
        xovemac_0: 'VALUE_6',
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xligori_0: 'VALUE_6',
        x4desadvlog_0: 'VALUE_6',
        vcrnumori_0: 'VALUE_6',
        pacqtystu_0: 63.0,
        dsplinvol_0: 'VALUE_6',
        xtext0_0: 'VALUE_6',
        xkanban_0: 'VALUE_6',
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        dsplinwei_0: 'VALUE_6',
        lot_0: 'VALUE_6',
        sta_0: 1,
        loc_0: 'VALUE_6',
        wrtqty_0: 63.0,
        wrtqtystu_0: 63.0,
        oalqtystu_0: 63.0,
        focflg_0: 'VALUE_6',
        sddlin_0: 'VALUE_6',
        sau_0: 'VALUE_6',
        lintyp_0: 'VALUE_6',
        pckcap_0: 'VALUE_6',
        pjt_0: 'VALUE_6',
        discrgren7_0: 'VALUE_6',
        discrgren8_0: 'VALUE_6',
        discrgren9_0: 'VALUE_6',
        reprat2_0: 'VALUE_6',
        x4facok_0: 'VALUE_6',
        pck_0: 'VALUE_6',
        discrgval6_0: 'VALUE_6',
        discrgval7_0: 'VALUE_6',
        xligmerori_0: 'VALUE_6',
        xssligori_0: 'VALUE_6',
        x4rgopl_0: 'VALUE_6',
        x4exclrfad_0: 'VALUE_6',
        xdestfin_0: 'VALUE_6',
        xdesint_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sstcod_0: 'VALUE_6',
        eccvalmin_0: 'VALUE_6',
        eccvalmaj_0: 'VALUE_6',
        prelin_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        xalert_0: 'VALUE_6',
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_6',
        xpntmonte_0: 'VALUE_6',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_7',
        itmdes1_0: 'Désignation article 7',
        rcpqtystu_0: 73.5,
        xflaglm_0: 'VALUE_7',
        soplin_0: 'VALUE_7',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_7',
        vtc_0: 'VALUE_7',
        taxgeoflg_0: 'VALUE_7',
        taxflg_0: 'VALUE_7',
        taxregflg_0: 'VALUE_7',
        tsicod_0: 'VALUE_7',
        clcamt2_0: 73.5,
        repcoe_0: 'VALUE_7',
        gropri_0: 73.5,
        priren_0: 73.5,
        vat_0: 'VALUE_7',
        clcamt1_0: 73.5,
        prptex_0: 'VALUE_7',
        rep1_0: 'VALUE_7',
        rep2_0: 'VALUE_7',
        ddtanum_0: 'SDE0007',
        ddtanot_0: 'VALUE_7',
        prhnum_0: 'VALUE_7',
        netpri_0: 73.5,
        qty_0: 73.5,
        wrh_0: 'VALUE_7',
        rtnqty_0: 73.5,
        sddtex_0: 'VALUE_7',
        sdhnum_0: 'VALUE_7',
        sohnum_0: 'VALUE_7',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_7',
        qtystu_0: 73.5,
        reprat1_0: 'VALUE_7',
        saustucoe_0: 'VALUE_7',
        useplc_0: 'VALUE_7',
        cpy_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_7',
        xovelab_0: 'VALUE_7',
        xovesco_0: 'VALUE_7',
        vcrlinori_0: 'VALUE_7',
        rattaxlin_0: 'VALUE_7',
        pckflg_0: 'VALUE_7',
        vcrseqori_0: 'VALUE_7',
        vcrtypori_0: 'VALUE_7',
        stu_0: 'VALUE_7',
        soqseq_0: 'VALUE_7',
        rtnqtystu_0: 73.5,
        sohcat_0: 'VALUE_7',
        bpcord_0: 'VALUE_7',
        xcusordref_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        orilin_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        xversion_0: 'VALUE_7',
        stofcy_0: 'VALUE_7',
        itmref_0: 'VALUE_7',
        weu_0: 'VALUE_7',
        dspweu_0: 'VALUE_7',
        stomgtcod_0: 'VALUE_7',
        pfm_0: 'VALUE_7',
        dspvou_0: 'VALUE_7',
        discrgval8_0: 'VALUE_7',
        discrgval9_0: 'VALUE_7',
        discrgren1_0: 'VALUE_7',
        discrgren2_0: 'VALUE_7',
        discrgren3_0: 'VALUE_7',
        discrgren4_0: 'VALUE_7',
        discrgren5_0: 'VALUE_7',
        discrgren6_0: 'VALUE_7',
        discrgval1_0: 'VALUE_7',
        discrgval2_0: 'VALUE_7',
        discrgval3_0: 'VALUE_7',
        discrgval4_0: 'VALUE_7',
        lincfmflg_0: 'VALUE_7',
        discrgval5_0: 'VALUE_7',
        cprpri_0: 73.5,
        bpaadd_0: 'VALUE_7',
        ndeprnbom_0: 'VALUE_7',
        invprnbom_0: 'VALUE_7',
        netprinot_0: 73.5,
        netpriati_0: 73.5,
        x4qtyfac_0: 73.5,
        impnumlig_0: 'VALUE_7',
        sdhcat_0: 'VALUE_7',
        untwei_0: 'VALUE_7',
        geocod_0: 'VALUE_7',
        insctyflg_0: 'VALUE_7',
        itmdes_0: 'VALUE_7',
        bastaxlin_0: 7,
        rcpflg_0: 'VALUE_7',
        xmatcst_0: 'VALUE_7',
        xmaccst_0: 'VALUE_7',
        xlabcst_0: 'VALUE_7',
        xscocst_0: 'VALUE_7',
        xovemat_0: 'VALUE_7',
        xovemac_0: 'VALUE_7',
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xligori_0: 'VALUE_7',
        x4desadvlog_0: 'VALUE_7',
        vcrnumori_0: 'VALUE_7',
        pacqtystu_0: 73.5,
        dsplinvol_0: 'VALUE_7',
        xtext0_0: 'VALUE_7',
        xkanban_0: 'VALUE_7',
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        dsplinwei_0: 'VALUE_7',
        lot_0: 'VALUE_7',
        sta_0: 1,
        loc_0: 'VALUE_7',
        wrtqty_0: 73.5,
        wrtqtystu_0: 73.5,
        oalqtystu_0: 73.5,
        focflg_0: 'VALUE_7',
        sddlin_0: 'VALUE_7',
        sau_0: 'VALUE_7',
        lintyp_0: 'VALUE_7',
        pckcap_0: 'VALUE_7',
        pjt_0: 'VALUE_7',
        discrgren7_0: 'VALUE_7',
        discrgren8_0: 'VALUE_7',
        discrgren9_0: 'VALUE_7',
        reprat2_0: 'VALUE_7',
        x4facok_0: 'VALUE_7',
        pck_0: 'VALUE_7',
        discrgval6_0: 'VALUE_7',
        discrgval7_0: 'VALUE_7',
        xligmerori_0: 'VALUE_7',
        xssligori_0: 'VALUE_7',
        x4rgopl_0: 'VALUE_7',
        x4exclrfad_0: 'VALUE_7',
        xdestfin_0: 'VALUE_7',
        xdesint_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sstcod_0: 'VALUE_7',
        eccvalmin_0: 'VALUE_7',
        eccvalmaj_0: 'VALUE_7',
        prelin_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        xalert_0: 'VALUE_7',
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_7',
        xpntmonte_0: 'VALUE_7',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_8',
        itmdes1_0: 'Désignation article 8',
        rcpqtystu_0: 84.0,
        xflaglm_0: 'VALUE_8',
        soplin_0: 'VALUE_8',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_8',
        vtc_0: 'VALUE_8',
        taxgeoflg_0: 'VALUE_8',
        taxflg_0: 'VALUE_8',
        taxregflg_0: 'VALUE_8',
        tsicod_0: 'VALUE_8',
        clcamt2_0: 84.0,
        repcoe_0: 'VALUE_8',
        gropri_0: 84.0,
        priren_0: 84.0,
        vat_0: 'VALUE_8',
        clcamt1_0: 84.0,
        prptex_0: 'VALUE_8',
        rep1_0: 'VALUE_8',
        rep2_0: 'VALUE_8',
        ddtanum_0: 'SDE0008',
        ddtanot_0: 'VALUE_8',
        prhnum_0: 'VALUE_8',
        netpri_0: 84.0,
        qty_0: 84.0,
        wrh_0: 'VALUE_8',
        rtnqty_0: 84.0,
        sddtex_0: 'VALUE_8',
        sdhnum_0: 'VALUE_8',
        sohnum_0: 'VALUE_8',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_8',
        qtystu_0: 84.0,
        reprat1_0: 'VALUE_8',
        saustucoe_0: 'VALUE_8',
        useplc_0: 'VALUE_8',
        cpy_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_8',
        xovelab_0: 'VALUE_8',
        xovesco_0: 'VALUE_8',
        vcrlinori_0: 'VALUE_8',
        rattaxlin_0: 'VALUE_8',
        pckflg_0: 'VALUE_8',
        vcrseqori_0: 'VALUE_8',
        vcrtypori_0: 'VALUE_8',
        stu_0: 'VALUE_8',
        soqseq_0: 'VALUE_8',
        rtnqtystu_0: 84.0,
        sohcat_0: 'VALUE_8',
        bpcord_0: 'VALUE_8',
        xcusordref_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        orilin_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        xversion_0: 'VALUE_8',
        stofcy_0: 'VALUE_8',
        itmref_0: 'VALUE_8',
        weu_0: 'VALUE_8',
        dspweu_0: 'VALUE_8',
        stomgtcod_0: 'VALUE_8',
        pfm_0: 'VALUE_8',
        dspvou_0: 'VALUE_8',
        discrgval8_0: 'VALUE_8',
        discrgval9_0: 'VALUE_8',
        discrgren1_0: 'VALUE_8',
        discrgren2_0: 'VALUE_8',
        discrgren3_0: 'VALUE_8',
        discrgren4_0: 'VALUE_8',
        discrgren5_0: 'VALUE_8',
        discrgren6_0: 'VALUE_8',
        discrgval1_0: 'VALUE_8',
        discrgval2_0: 'VALUE_8',
        discrgval3_0: 'VALUE_8',
        discrgval4_0: 'VALUE_8',
        lincfmflg_0: 'VALUE_8',
        discrgval5_0: 'VALUE_8',
        cprpri_0: 84.0,
        bpaadd_0: 'VALUE_8',
        ndeprnbom_0: 'VALUE_8',
        invprnbom_0: 'VALUE_8',
        netprinot_0: 84.0,
        netpriati_0: 84.0,
        x4qtyfac_0: 84.0,
        impnumlig_0: 'VALUE_8',
        sdhcat_0: 'VALUE_8',
        untwei_0: 'VALUE_8',
        geocod_0: 'VALUE_8',
        insctyflg_0: 'VALUE_8',
        itmdes_0: 'VALUE_8',
        bastaxlin_0: 8,
        rcpflg_0: 'VALUE_8',
        xmatcst_0: 'VALUE_8',
        xmaccst_0: 'VALUE_8',
        xlabcst_0: 'VALUE_8',
        xscocst_0: 'VALUE_8',
        xovemat_0: 'VALUE_8',
        xovemac_0: 'VALUE_8',
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xligori_0: 'VALUE_8',
        x4desadvlog_0: 'VALUE_8',
        vcrnumori_0: 'VALUE_8',
        pacqtystu_0: 84.0,
        dsplinvol_0: 'VALUE_8',
        xtext0_0: 'VALUE_8',
        xkanban_0: 'VALUE_8',
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        dsplinwei_0: 'VALUE_8',
        lot_0: 'VALUE_8',
        sta_0: 1,
        loc_0: 'VALUE_8',
        wrtqty_0: 84.0,
        wrtqtystu_0: 84.0,
        oalqtystu_0: 84.0,
        focflg_0: 'VALUE_8',
        sddlin_0: 'VALUE_8',
        sau_0: 'VALUE_8',
        lintyp_0: 'VALUE_8',
        pckcap_0: 'VALUE_8',
        pjt_0: 'VALUE_8',
        discrgren7_0: 'VALUE_8',
        discrgren8_0: 'VALUE_8',
        discrgren9_0: 'VALUE_8',
        reprat2_0: 'VALUE_8',
        x4facok_0: 'VALUE_8',
        pck_0: 'VALUE_8',
        discrgval6_0: 'VALUE_8',
        discrgval7_0: 'VALUE_8',
        xligmerori_0: 'VALUE_8',
        xssligori_0: 'VALUE_8',
        x4rgopl_0: 'VALUE_8',
        x4exclrfad_0: 'VALUE_8',
        xdestfin_0: 'VALUE_8',
        xdesint_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sstcod_0: 'VALUE_8',
        eccvalmin_0: 'VALUE_8',
        eccvalmaj_0: 'VALUE_8',
        prelin_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        xalert_0: 'VALUE_8',
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_8',
        xpntmonte_0: 'VALUE_8',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_9',
        itmdes1_0: 'Désignation article 9',
        rcpqtystu_0: 94.5,
        xflaglm_0: 'VALUE_9',
        soplin_0: 'VALUE_9',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_9',
        vtc_0: 'VALUE_9',
        taxgeoflg_0: 'VALUE_9',
        taxflg_0: 'VALUE_9',
        taxregflg_0: 'VALUE_9',
        tsicod_0: 'VALUE_9',
        clcamt2_0: 94.5,
        repcoe_0: 'VALUE_9',
        gropri_0: 94.5,
        priren_0: 94.5,
        vat_0: 'VALUE_9',
        clcamt1_0: 94.5,
        prptex_0: 'VALUE_9',
        rep1_0: 'VALUE_9',
        rep2_0: 'VALUE_9',
        ddtanum_0: 'SDE0009',
        ddtanot_0: 'VALUE_9',
        prhnum_0: 'VALUE_9',
        netpri_0: 94.5,
        qty_0: 94.5,
        wrh_0: 'VALUE_9',
        rtnqty_0: 94.5,
        sddtex_0: 'VALUE_9',
        sdhnum_0: 'VALUE_9',
        sohnum_0: 'VALUE_9',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_9',
        qtystu_0: 94.5,
        reprat1_0: 'VALUE_9',
        saustucoe_0: 'VALUE_9',
        useplc_0: 'VALUE_9',
        cpy_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_9',
        xovelab_0: 'VALUE_9',
        xovesco_0: 'VALUE_9',
        vcrlinori_0: 'VALUE_9',
        rattaxlin_0: 'VALUE_9',
        pckflg_0: 'VALUE_9',
        vcrseqori_0: 'VALUE_9',
        vcrtypori_0: 'VALUE_9',
        stu_0: 'VALUE_9',
        soqseq_0: 'VALUE_9',
        rtnqtystu_0: 94.5,
        sohcat_0: 'VALUE_9',
        bpcord_0: 'VALUE_9',
        xcusordref_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        orilin_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        xversion_0: 'VALUE_9',
        stofcy_0: 'VALUE_9',
        itmref_0: 'VALUE_9',
        weu_0: 'VALUE_9',
        dspweu_0: 'VALUE_9',
        stomgtcod_0: 'VALUE_9',
        pfm_0: 'VALUE_9',
        dspvou_0: 'VALUE_9',
        discrgval8_0: 'VALUE_9',
        discrgval9_0: 'VALUE_9',
        discrgren1_0: 'VALUE_9',
        discrgren2_0: 'VALUE_9',
        discrgren3_0: 'VALUE_9',
        discrgren4_0: 'VALUE_9',
        discrgren5_0: 'VALUE_9',
        discrgren6_0: 'VALUE_9',
        discrgval1_0: 'VALUE_9',
        discrgval2_0: 'VALUE_9',
        discrgval3_0: 'VALUE_9',
        discrgval4_0: 'VALUE_9',
        lincfmflg_0: 'VALUE_9',
        discrgval5_0: 'VALUE_9',
        cprpri_0: 94.5,
        bpaadd_0: 'VALUE_9',
        ndeprnbom_0: 'VALUE_9',
        invprnbom_0: 'VALUE_9',
        netprinot_0: 94.5,
        netpriati_0: 94.5,
        x4qtyfac_0: 94.5,
        impnumlig_0: 'VALUE_9',
        sdhcat_0: 'VALUE_9',
        untwei_0: 'VALUE_9',
        geocod_0: 'VALUE_9',
        insctyflg_0: 'VALUE_9',
        itmdes_0: 'VALUE_9',
        bastaxlin_0: 9,
        rcpflg_0: 'VALUE_9',
        xmatcst_0: 'VALUE_9',
        xmaccst_0: 'VALUE_9',
        xlabcst_0: 'VALUE_9',
        xscocst_0: 'VALUE_9',
        xovemat_0: 'VALUE_9',
        xovemac_0: 'VALUE_9',
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xligori_0: 'VALUE_9',
        x4desadvlog_0: 'VALUE_9',
        vcrnumori_0: 'VALUE_9',
        pacqtystu_0: 94.5,
        dsplinvol_0: 'VALUE_9',
        xtext0_0: 'VALUE_9',
        xkanban_0: 'VALUE_9',
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        dsplinwei_0: 'VALUE_9',
        lot_0: 'VALUE_9',
        sta_0: 1,
        loc_0: 'VALUE_9',
        wrtqty_0: 94.5,
        wrtqtystu_0: 94.5,
        oalqtystu_0: 94.5,
        focflg_0: 'VALUE_9',
        sddlin_0: 'VALUE_9',
        sau_0: 'VALUE_9',
        lintyp_0: 'VALUE_9',
        pckcap_0: 'VALUE_9',
        pjt_0: 'VALUE_9',
        discrgren7_0: 'VALUE_9',
        discrgren8_0: 'VALUE_9',
        discrgren9_0: 'VALUE_9',
        reprat2_0: 'VALUE_9',
        x4facok_0: 'VALUE_9',
        pck_0: 'VALUE_9',
        discrgval6_0: 'VALUE_9',
        discrgval7_0: 'VALUE_9',
        xligmerori_0: 'VALUE_9',
        xssligori_0: 'VALUE_9',
        x4rgopl_0: 'VALUE_9',
        x4exclrfad_0: 'VALUE_9',
        xdestfin_0: 'VALUE_9',
        xdesint_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sstcod_0: 'VALUE_9',
        eccvalmin_0: 'VALUE_9',
        eccvalmaj_0: 'VALUE_9',
        prelin_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        xalert_0: 'VALUE_9',
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_9',
        xpntmonte_0: 'VALUE_9',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
      },
      {
        credat_0: new Date().toISOString().split('T')[0],
        vacitm_0: 'VALUE_10',
        itmdes1_0: 'Désignation article 10',
        rcpqtystu_0: 105.0,
        xflaglm_0: 'VALUE_10',
        soplin_0: 'VALUE_10',
        xdlvtimfin_0: new Date().toISOString(),
        vts_0: 'VALUE_10',
        vtc_0: 'VALUE_10',
        taxgeoflg_0: 'VALUE_10',
        taxflg_0: 'VALUE_10',
        taxregflg_0: 'VALUE_10',
        tsicod_0: 'VALUE_10',
        clcamt2_0: 105.0,
        repcoe_0: 'VALUE_10',
        gropri_0: 105.0,
        priren_0: 105.0,
        vat_0: 'VALUE_10',
        clcamt1_0: 105.0,
        prptex_0: 'VALUE_10',
        rep1_0: 'VALUE_10',
        rep2_0: 'VALUE_10',
        ddtanum_0: 'SDE0010',
        ddtanot_0: 'VALUE_10',
        prhnum_0: 'VALUE_10',
        netpri_0: 105.0,
        qty_0: 105.0,
        wrh_0: 'VALUE_10',
        rtnqty_0: 105.0,
        sddtex_0: 'VALUE_10',
        sdhnum_0: 'VALUE_10',
        sohnum_0: 'VALUE_10',
        shidat_0: new Date().toISOString().split('T')[0],
        dsplinflg_0: 'VALUE_10',
        qtystu_0: 105.0,
        reprat1_0: 'VALUE_10',
        saustucoe_0: 'VALUE_10',
        useplc_0: 'VALUE_10',
        cpy_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_10',
        xovelab_0: 'VALUE_10',
        xovesco_0: 'VALUE_10',
        vcrlinori_0: 'VALUE_10',
        rattaxlin_0: 'VALUE_10',
        pckflg_0: 'VALUE_10',
        vcrseqori_0: 'VALUE_10',
        vcrtypori_0: 'VALUE_10',
        stu_0: 'VALUE_10',
        soqseq_0: 'VALUE_10',
        rtnqtystu_0: 105.0,
        sohcat_0: 'VALUE_10',
        bpcord_0: 'VALUE_10',
        xcusordref_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        orilin_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        xversion_0: 'VALUE_10',
        stofcy_0: 'VALUE_10',
        itmref_0: 'VALUE_10',
        weu_0: 'VALUE_10',
        dspweu_0: 'VALUE_10',
        stomgtcod_0: 'VALUE_10',
        pfm_0: 'VALUE_10',
        dspvou_0: 'VALUE_10',
        discrgval8_0: 'VALUE_10',
        discrgval9_0: 'VALUE_10',
        discrgren1_0: 'VALUE_10',
        discrgren2_0: 'VALUE_10',
        discrgren3_0: 'VALUE_10',
        discrgren4_0: 'VALUE_10',
        discrgren5_0: 'VALUE_10',
        discrgren6_0: 'VALUE_10',
        discrgval1_0: 'VALUE_10',
        discrgval2_0: 'VALUE_10',
        discrgval3_0: 'VALUE_10',
        discrgval4_0: 'VALUE_10',
        lincfmflg_0: 'VALUE_10',
        discrgval5_0: 'VALUE_10',
        cprpri_0: 105.0,
        bpaadd_0: 'VALUE_10',
        ndeprnbom_0: 'VALUE_10',
        invprnbom_0: 'VALUE_10',
        netprinot_0: 105.0,
        netpriati_0: 105.0,
        x4qtyfac_0: 105.0,
        impnumlig_0: 'VALUE_10',
        sdhcat_0: 'VALUE_10',
        untwei_0: 'VALUE_10',
        geocod_0: 'VALUE_10',
        insctyflg_0: 'VALUE_10',
        itmdes_0: 'VALUE_10',
        bastaxlin_0: 10,
        rcpflg_0: 'VALUE_10',
        xmatcst_0: 'VALUE_10',
        xmaccst_0: 'VALUE_10',
        xlabcst_0: 'VALUE_10',
        xscocst_0: 'VALUE_10',
        xovemat_0: 'VALUE_10',
        xovemac_0: 'VALUE_10',
        xshidatfin_0: new Date().toISOString().split('T')[0],
        xshitimdeb_0: new Date().toISOString(),
        xshitimfin_0: new Date().toISOString(),
        xligori_0: 'VALUE_10',
        x4desadvlog_0: 'VALUE_10',
        vcrnumori_0: 'VALUE_10',
        pacqtystu_0: 105.0,
        dsplinvol_0: 'VALUE_10',
        xtext0_0: 'VALUE_10',
        xkanban_0: 'VALUE_10',
        xdlvdatdeb_0: new Date().toISOString().split('T')[0],
        dsplinwei_0: 'VALUE_10',
        lot_0: 'VALUE_10',
        sta_0: 1,
        loc_0: 'VALUE_10',
        wrtqty_0: 105.0,
        wrtqtystu_0: 105.0,
        oalqtystu_0: 105.0,
        focflg_0: 'VALUE_10',
        sddlin_0: 'VALUE_10',
        sau_0: 'VALUE_10',
        lintyp_0: 'VALUE_10',
        pckcap_0: 'VALUE_10',
        pjt_0: 'VALUE_10',
        discrgren7_0: 'VALUE_10',
        discrgren8_0: 'VALUE_10',
        discrgren9_0: 'VALUE_10',
        reprat2_0: 'VALUE_10',
        x4facok_0: 'VALUE_10',
        pck_0: 'VALUE_10',
        discrgval6_0: 'VALUE_10',
        discrgval7_0: 'VALUE_10',
        xligmerori_0: 'VALUE_10',
        xssligori_0: 'VALUE_10',
        x4rgopl_0: 'VALUE_10',
        x4exclrfad_0: 'VALUE_10',
        xdestfin_0: 'VALUE_10',
        xdesint_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        sstcod_0: 'VALUE_10',
        eccvalmin_0: 'VALUE_10',
        eccvalmaj_0: 'VALUE_10',
        prelin_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        xalert_0: 'VALUE_10',
        xdlvdatfin_0: new Date().toISOString().split('T')[0],
        xdlvtimdeb_0: new Date().toISOString(),
        xpntdecha_0: 'VALUE_10',
        xpntmonte_0: 'VALUE_10',
        xshidatdeb_0: new Date().toISOString().split('T')[0],
      },
    ]

    await Database.table('sdeliveryd').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans sdeliveryd`)
  }
}
