import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour SINVOICE
    const data = [
      {
        bpapay_0: 'VALUE_1',
        dep_0: 'VALUE_1',
        expnum_0: 'SIN0001',
        bpainv_0: 'VALUE_1',
        adrval_0: 'VALUE_1',
        perfin_0: 'VALUE_1',
        fiy_0: 'VALUE_1',
        bprvcr_0: 'VALUE_1',
        strduddat_0: new Date().toISOString().split('T')[0],
        xduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_1',
        xncflg_0: 'VALUE_1',
        qtcaccnum_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        deprat_0: 'VALUE_1',
        belvcs_0: 'VALUE_1',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_1',
        umrnum_0: 'VALUE_1',
        spadernum_0: 'VALUE_1',
        bvrrefnum_0: 'VALUE_1',
        fld40ren_0: 'VALUE_1',
        fld41ren_0: 'VALUE_1',
        cshvat_0: 'VALUE_1',
        x4sbi_0: 'VALUE_1',
        curled_0: 'VALUE_1',
        ratdiv_0: 'VALUE_1',
        ratmlt_0: 'VALUE_1',
        sinum_0: 'VALUE_1',
        die_0: 'VALUE_1',
        exeamttax_0: 10.5,
        metcor_0: 'VALUE_1',
        pjth_0: 'VALUE_1',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 10.5,
        amtatil_0: 10.5,
        xpam_0: 'VALUE_1',
        ratdat_0: new Date().toISOString().split('T')[0],
        x4sihenvaut_0: 'VALUE_1',
        invtypspa_0: 'VALUE_1',
        upddattim_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        dcleecnum_0: 'VALUE_1',
        sstentcod_0: 'VALUE_1',
        revcansta_0: 1,
        basdep_0: 'VALUE_1',
        porexpdcl_0: 'VALUE_1',
        bpynam_0: 'Raison sociale tiers payé 1',
        bpyaddlig_0: 'VALUE_1',
        bpyposcod_0: 'VALUE_1',
        bpycty_0: 'VALUE_1',
        bpysat_0: 'VALUE_1',
        bpycry_0: 'VALUE_1',
        bpycrynam_0: 'VALUE_1',
        nbrcpy_0: 'VALUE_1',
        led_0: 'VALUE_1',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_1',
        xtimmes_0: new Date().toISOString(),
        isextdoc_0: 'VALUE_1',
        amtati_0: 10.5,
        xamtati_0: 10.5,
        bpr_0: 'VALUE_1',
        sat_0: 'VALUE_1',
        orimod_0: 'VALUE_1',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_1',
        oridocnum_0: 'VALUE_1',
        sivtyp_0: 'VALUE_1',
        accdat_0: new Date().toISOString().split('T')[0],
        fctvcr_0: 'VALUE_1',
        dirinvflg_0: 'VALUE_1',
        invtyp_0: 'VALUE_1',
        x4sihexp_0: 'VALUE_1',
        theamttax_0: 10.5,
        trsfam_0: 'VALUE_1',
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        des_0: 'VALUE_1',
        perdeb_0: 'VALUE_1',
        starpt_0: 1,
        bilvcr_0: 'VALUE_1',
        bprnam_0: 'VALUE_1',
        bpaaddlig_0: 'VALUE_1',
        crynam_0: 'VALUE_1',
        eecnumdeb_0: 'VALUE_1',
        amtnot_0: 10.5,
        xamtnot_0: 10.5,
        bastax_0: 1,
        poscod_0: 'VALUE_1',
        vac_0: 'VALUE_1',
        bprpay_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        updusr_0: 'VALUE_1',
        cce_0: 'VALUE_1',
        payban_0: 'VALUE_1',
        cpy_0: 'VALUE_1',
        fcy_0: 'VALUE_1',
        per_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        crn_0: 'VALUE_1',
        tax_0: 'VALUE_1',
        sns_0: 'VALUE_1',
        x4sihdest_0: 'VALUE_1',
        bprfct_0: 'VALUE_1',
        pte_0: 'VALUE_1',
        cur_0: 'VALUE_1',
        num_0: 'VALUE_1',
        gte_0: 'VALUE_1',
        bprsac_0: 'VALUE_1',
        jou_0: 'VALUE_1',
        wrhe_0: 'VALUE_1',
        cty_0: 'VALUE_1',
        cry_0: 'VALUE_1',
        invnum_0: 'VALUE_1',
        nbrtax_0: 'VALUE_1',
        amttax_0: 10.5,
        amttaxusa_0: 10.5,
        fctvcrflg_0: 'VALUE_1',
        cai_0: 'VALUE_1',
        datvlycai_0: new Date().toISOString().split('T')[0],
        salprityp_0: 10.5,
      },
      {
        bpapay_0: 'VALUE_2',
        dep_0: 'VALUE_2',
        expnum_0: 'SIN0002',
        bpainv_0: 'VALUE_2',
        adrval_0: 'VALUE_2',
        perfin_0: 'VALUE_2',
        fiy_0: 'VALUE_2',
        bprvcr_0: 'VALUE_2',
        strduddat_0: new Date().toISOString().split('T')[0],
        xduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_2',
        xncflg_0: 'VALUE_2',
        qtcaccnum_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        deprat_0: 'VALUE_2',
        belvcs_0: 'VALUE_2',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_2',
        umrnum_0: 'VALUE_2',
        spadernum_0: 'VALUE_2',
        bvrrefnum_0: 'VALUE_2',
        fld40ren_0: 'VALUE_2',
        fld41ren_0: 'VALUE_2',
        cshvat_0: 'VALUE_2',
        x4sbi_0: 'VALUE_2',
        curled_0: 'VALUE_2',
        ratdiv_0: 'VALUE_2',
        ratmlt_0: 'VALUE_2',
        sinum_0: 'VALUE_2',
        die_0: 'VALUE_2',
        exeamttax_0: 21.0,
        metcor_0: 'VALUE_2',
        pjth_0: 'VALUE_2',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 21.0,
        amtatil_0: 21.0,
        xpam_0: 'VALUE_2',
        ratdat_0: new Date().toISOString().split('T')[0],
        x4sihenvaut_0: 'VALUE_2',
        invtypspa_0: 'VALUE_2',
        upddattim_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        dcleecnum_0: 'VALUE_2',
        sstentcod_0: 'VALUE_2',
        revcansta_0: 2,
        basdep_0: 'VALUE_2',
        porexpdcl_0: 'VALUE_2',
        bpynam_0: 'Raison sociale tiers payé 2',
        bpyaddlig_0: 'VALUE_2',
        bpyposcod_0: 'VALUE_2',
        bpycty_0: 'VALUE_2',
        bpysat_0: 'VALUE_2',
        bpycry_0: 'VALUE_2',
        bpycrynam_0: 'VALUE_2',
        nbrcpy_0: 'VALUE_2',
        led_0: 'VALUE_2',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_2',
        xtimmes_0: new Date().toISOString(),
        isextdoc_0: 'VALUE_2',
        amtati_0: 21.0,
        xamtati_0: 21.0,
        bpr_0: 'VALUE_2',
        sat_0: 'VALUE_2',
        orimod_0: 'VALUE_2',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_2',
        oridocnum_0: 'VALUE_2',
        sivtyp_0: 'VALUE_2',
        accdat_0: new Date().toISOString().split('T')[0],
        fctvcr_0: 'VALUE_2',
        dirinvflg_0: 'VALUE_2',
        invtyp_0: 'VALUE_2',
        x4sihexp_0: 'VALUE_2',
        theamttax_0: 21.0,
        trsfam_0: 'VALUE_2',
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        des_0: 'VALUE_2',
        perdeb_0: 'VALUE_2',
        starpt_0: 2,
        bilvcr_0: 'VALUE_2',
        bprnam_0: 'VALUE_2',
        bpaaddlig_0: 'VALUE_2',
        crynam_0: 'VALUE_2',
        eecnumdeb_0: 'VALUE_2',
        amtnot_0: 21.0,
        xamtnot_0: 21.0,
        bastax_0: 2,
        poscod_0: 'VALUE_2',
        vac_0: 'VALUE_2',
        bprpay_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        updusr_0: 'VALUE_2',
        cce_0: 'VALUE_2',
        payban_0: 'VALUE_2',
        cpy_0: 'VALUE_2',
        fcy_0: 'VALUE_2',
        per_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        crn_0: 'VALUE_2',
        tax_0: 'VALUE_2',
        sns_0: 'VALUE_2',
        x4sihdest_0: 'VALUE_2',
        bprfct_0: 'VALUE_2',
        pte_0: 'VALUE_2',
        cur_0: 'VALUE_2',
        num_0: 'VALUE_2',
        gte_0: 'VALUE_2',
        bprsac_0: 'VALUE_2',
        jou_0: 'VALUE_2',
        wrhe_0: 'VALUE_2',
        cty_0: 'VALUE_2',
        cry_0: 'VALUE_2',
        invnum_0: 'VALUE_2',
        nbrtax_0: 'VALUE_2',
        amttax_0: 21.0,
        amttaxusa_0: 21.0,
        fctvcrflg_0: 'VALUE_2',
        cai_0: 'VALUE_2',
        datvlycai_0: new Date().toISOString().split('T')[0],
        salprityp_0: 21.0,
      },
      {
        bpapay_0: 'VALUE_3',
        dep_0: 'VALUE_3',
        expnum_0: 'SIN0003',
        bpainv_0: 'VALUE_3',
        adrval_0: 'VALUE_3',
        perfin_0: 'VALUE_3',
        fiy_0: 'VALUE_3',
        bprvcr_0: 'VALUE_3',
        strduddat_0: new Date().toISOString().split('T')[0],
        xduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_3',
        xncflg_0: 'VALUE_3',
        qtcaccnum_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        deprat_0: 'VALUE_3',
        belvcs_0: 'VALUE_3',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_3',
        umrnum_0: 'VALUE_3',
        spadernum_0: 'VALUE_3',
        bvrrefnum_0: 'VALUE_3',
        fld40ren_0: 'VALUE_3',
        fld41ren_0: 'VALUE_3',
        cshvat_0: 'VALUE_3',
        x4sbi_0: 'VALUE_3',
        curled_0: 'VALUE_3',
        ratdiv_0: 'VALUE_3',
        ratmlt_0: 'VALUE_3',
        sinum_0: 'VALUE_3',
        die_0: 'VALUE_3',
        exeamttax_0: 31.5,
        metcor_0: 'VALUE_3',
        pjth_0: 'VALUE_3',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 31.5,
        amtatil_0: 31.5,
        xpam_0: 'VALUE_3',
        ratdat_0: new Date().toISOString().split('T')[0],
        x4sihenvaut_0: 'VALUE_3',
        invtypspa_0: 'VALUE_3',
        upddattim_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        dcleecnum_0: 'VALUE_3',
        sstentcod_0: 'VALUE_3',
        revcansta_0: 3,
        basdep_0: 'VALUE_3',
        porexpdcl_0: 'VALUE_3',
        bpynam_0: 'Raison sociale tiers payé 3',
        bpyaddlig_0: 'VALUE_3',
        bpyposcod_0: 'VALUE_3',
        bpycty_0: 'VALUE_3',
        bpysat_0: 'VALUE_3',
        bpycry_0: 'VALUE_3',
        bpycrynam_0: 'VALUE_3',
        nbrcpy_0: 'VALUE_3',
        led_0: 'VALUE_3',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_3',
        xtimmes_0: new Date().toISOString(),
        isextdoc_0: 'VALUE_3',
        amtati_0: 31.5,
        xamtati_0: 31.5,
        bpr_0: 'VALUE_3',
        sat_0: 'VALUE_3',
        orimod_0: 'VALUE_3',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_3',
        oridocnum_0: 'VALUE_3',
        sivtyp_0: 'VALUE_3',
        accdat_0: new Date().toISOString().split('T')[0],
        fctvcr_0: 'VALUE_3',
        dirinvflg_0: 'VALUE_3',
        invtyp_0: 'VALUE_3',
        x4sihexp_0: 'VALUE_3',
        theamttax_0: 31.5,
        trsfam_0: 'VALUE_3',
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        des_0: 'VALUE_3',
        perdeb_0: 'VALUE_3',
        starpt_0: 3,
        bilvcr_0: 'VALUE_3',
        bprnam_0: 'VALUE_3',
        bpaaddlig_0: 'VALUE_3',
        crynam_0: 'VALUE_3',
        eecnumdeb_0: 'VALUE_3',
        amtnot_0: 31.5,
        xamtnot_0: 31.5,
        bastax_0: 3,
        poscod_0: 'VALUE_3',
        vac_0: 'VALUE_3',
        bprpay_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        updusr_0: 'VALUE_3',
        cce_0: 'VALUE_3',
        payban_0: 'VALUE_3',
        cpy_0: 'VALUE_3',
        fcy_0: 'VALUE_3',
        per_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        crn_0: 'VALUE_3',
        tax_0: 'VALUE_3',
        sns_0: 'VALUE_3',
        x4sihdest_0: 'VALUE_3',
        bprfct_0: 'VALUE_3',
        pte_0: 'VALUE_3',
        cur_0: 'VALUE_3',
        num_0: 'VALUE_3',
        gte_0: 'VALUE_3',
        bprsac_0: 'VALUE_3',
        jou_0: 'VALUE_3',
        wrhe_0: 'VALUE_3',
        cty_0: 'VALUE_3',
        cry_0: 'VALUE_3',
        invnum_0: 'VALUE_3',
        nbrtax_0: 'VALUE_3',
        amttax_0: 31.5,
        amttaxusa_0: 31.5,
        fctvcrflg_0: 'VALUE_3',
        cai_0: 'VALUE_3',
        datvlycai_0: new Date().toISOString().split('T')[0],
        salprityp_0: 31.5,
      },
      {
        bpapay_0: 'VALUE_4',
        dep_0: 'VALUE_4',
        expnum_0: 'SIN0004',
        bpainv_0: 'VALUE_4',
        adrval_0: 'VALUE_4',
        perfin_0: 'VALUE_4',
        fiy_0: 'VALUE_4',
        bprvcr_0: 'VALUE_4',
        strduddat_0: new Date().toISOString().split('T')[0],
        xduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_4',
        xncflg_0: 'VALUE_4',
        qtcaccnum_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        deprat_0: 'VALUE_4',
        belvcs_0: 'VALUE_4',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_4',
        umrnum_0: 'VALUE_4',
        spadernum_0: 'VALUE_4',
        bvrrefnum_0: 'VALUE_4',
        fld40ren_0: 'VALUE_4',
        fld41ren_0: 'VALUE_4',
        cshvat_0: 'VALUE_4',
        x4sbi_0: 'VALUE_4',
        curled_0: 'VALUE_4',
        ratdiv_0: 'VALUE_4',
        ratmlt_0: 'VALUE_4',
        sinum_0: 'VALUE_4',
        die_0: 'VALUE_4',
        exeamttax_0: 42.0,
        metcor_0: 'VALUE_4',
        pjth_0: 'VALUE_4',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 42.0,
        amtatil_0: 42.0,
        xpam_0: 'VALUE_4',
        ratdat_0: new Date().toISOString().split('T')[0],
        x4sihenvaut_0: 'VALUE_4',
        invtypspa_0: 'VALUE_4',
        upddattim_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        dcleecnum_0: 'VALUE_4',
        sstentcod_0: 'VALUE_4',
        revcansta_0: 4,
        basdep_0: 'VALUE_4',
        porexpdcl_0: 'VALUE_4',
        bpynam_0: 'Raison sociale tiers payé 4',
        bpyaddlig_0: 'VALUE_4',
        bpyposcod_0: 'VALUE_4',
        bpycty_0: 'VALUE_4',
        bpysat_0: 'VALUE_4',
        bpycry_0: 'VALUE_4',
        bpycrynam_0: 'VALUE_4',
        nbrcpy_0: 'VALUE_4',
        led_0: 'VALUE_4',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_4',
        xtimmes_0: new Date().toISOString(),
        isextdoc_0: 'VALUE_4',
        amtati_0: 42.0,
        xamtati_0: 42.0,
        bpr_0: 'VALUE_4',
        sat_0: 'VALUE_4',
        orimod_0: 'VALUE_4',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_4',
        oridocnum_0: 'VALUE_4',
        sivtyp_0: 'VALUE_4',
        accdat_0: new Date().toISOString().split('T')[0],
        fctvcr_0: 'VALUE_4',
        dirinvflg_0: 'VALUE_4',
        invtyp_0: 'VALUE_4',
        x4sihexp_0: 'VALUE_4',
        theamttax_0: 42.0,
        trsfam_0: 'VALUE_4',
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        des_0: 'VALUE_4',
        perdeb_0: 'VALUE_4',
        starpt_0: 4,
        bilvcr_0: 'VALUE_4',
        bprnam_0: 'VALUE_4',
        bpaaddlig_0: 'VALUE_4',
        crynam_0: 'VALUE_4',
        eecnumdeb_0: 'VALUE_4',
        amtnot_0: 42.0,
        xamtnot_0: 42.0,
        bastax_0: 4,
        poscod_0: 'VALUE_4',
        vac_0: 'VALUE_4',
        bprpay_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        updusr_0: 'VALUE_4',
        cce_0: 'VALUE_4',
        payban_0: 'VALUE_4',
        cpy_0: 'VALUE_4',
        fcy_0: 'VALUE_4',
        per_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        crn_0: 'VALUE_4',
        tax_0: 'VALUE_4',
        sns_0: 'VALUE_4',
        x4sihdest_0: 'VALUE_4',
        bprfct_0: 'VALUE_4',
        pte_0: 'VALUE_4',
        cur_0: 'VALUE_4',
        num_0: 'VALUE_4',
        gte_0: 'VALUE_4',
        bprsac_0: 'VALUE_4',
        jou_0: 'VALUE_4',
        wrhe_0: 'VALUE_4',
        cty_0: 'VALUE_4',
        cry_0: 'VALUE_4',
        invnum_0: 'VALUE_4',
        nbrtax_0: 'VALUE_4',
        amttax_0: 42.0,
        amttaxusa_0: 42.0,
        fctvcrflg_0: 'VALUE_4',
        cai_0: 'VALUE_4',
        datvlycai_0: new Date().toISOString().split('T')[0],
        salprityp_0: 42.0,
      },
      {
        bpapay_0: 'VALUE_5',
        dep_0: 'VALUE_5',
        expnum_0: 'SIN0005',
        bpainv_0: 'VALUE_5',
        adrval_0: 'VALUE_5',
        perfin_0: 'VALUE_5',
        fiy_0: 'VALUE_5',
        bprvcr_0: 'VALUE_5',
        strduddat_0: new Date().toISOString().split('T')[0],
        xduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_5',
        xncflg_0: 'VALUE_5',
        qtcaccnum_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        deprat_0: 'VALUE_5',
        belvcs_0: 'VALUE_5',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_5',
        umrnum_0: 'VALUE_5',
        spadernum_0: 'VALUE_5',
        bvrrefnum_0: 'VALUE_5',
        fld40ren_0: 'VALUE_5',
        fld41ren_0: 'VALUE_5',
        cshvat_0: 'VALUE_5',
        x4sbi_0: 'VALUE_5',
        curled_0: 'VALUE_5',
        ratdiv_0: 'VALUE_5',
        ratmlt_0: 'VALUE_5',
        sinum_0: 'VALUE_5',
        die_0: 'VALUE_5',
        exeamttax_0: 52.5,
        metcor_0: 'VALUE_5',
        pjth_0: 'VALUE_5',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 52.5,
        amtatil_0: 52.5,
        xpam_0: 'VALUE_5',
        ratdat_0: new Date().toISOString().split('T')[0],
        x4sihenvaut_0: 'VALUE_5',
        invtypspa_0: 'VALUE_5',
        upddattim_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        dcleecnum_0: 'VALUE_5',
        sstentcod_0: 'VALUE_5',
        revcansta_0: 5,
        basdep_0: 'VALUE_5',
        porexpdcl_0: 'VALUE_5',
        bpynam_0: 'Raison sociale tiers payé 5',
        bpyaddlig_0: 'VALUE_5',
        bpyposcod_0: 'VALUE_5',
        bpycty_0: 'VALUE_5',
        bpysat_0: 'VALUE_5',
        bpycry_0: 'VALUE_5',
        bpycrynam_0: 'VALUE_5',
        nbrcpy_0: 'VALUE_5',
        led_0: 'VALUE_5',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_5',
        xtimmes_0: new Date().toISOString(),
        isextdoc_0: 'VALUE_5',
        amtati_0: 52.5,
        xamtati_0: 52.5,
        bpr_0: 'VALUE_5',
        sat_0: 'VALUE_5',
        orimod_0: 'VALUE_5',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_5',
        oridocnum_0: 'VALUE_5',
        sivtyp_0: 'VALUE_5',
        accdat_0: new Date().toISOString().split('T')[0],
        fctvcr_0: 'VALUE_5',
        dirinvflg_0: 'VALUE_5',
        invtyp_0: 'VALUE_5',
        x4sihexp_0: 'VALUE_5',
        theamttax_0: 52.5,
        trsfam_0: 'VALUE_5',
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        des_0: 'VALUE_5',
        perdeb_0: 'VALUE_5',
        starpt_0: 5,
        bilvcr_0: 'VALUE_5',
        bprnam_0: 'VALUE_5',
        bpaaddlig_0: 'VALUE_5',
        crynam_0: 'VALUE_5',
        eecnumdeb_0: 'VALUE_5',
        amtnot_0: 52.5,
        xamtnot_0: 52.5,
        bastax_0: 5,
        poscod_0: 'VALUE_5',
        vac_0: 'VALUE_5',
        bprpay_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        updusr_0: 'VALUE_5',
        cce_0: 'VALUE_5',
        payban_0: 'VALUE_5',
        cpy_0: 'VALUE_5',
        fcy_0: 'VALUE_5',
        per_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        crn_0: 'VALUE_5',
        tax_0: 'VALUE_5',
        sns_0: 'VALUE_5',
        x4sihdest_0: 'VALUE_5',
        bprfct_0: 'VALUE_5',
        pte_0: 'VALUE_5',
        cur_0: 'VALUE_5',
        num_0: 'VALUE_5',
        gte_0: 'VALUE_5',
        bprsac_0: 'VALUE_5',
        jou_0: 'VALUE_5',
        wrhe_0: 'VALUE_5',
        cty_0: 'VALUE_5',
        cry_0: 'VALUE_5',
        invnum_0: 'VALUE_5',
        nbrtax_0: 'VALUE_5',
        amttax_0: 52.5,
        amttaxusa_0: 52.5,
        fctvcrflg_0: 'VALUE_5',
        cai_0: 'VALUE_5',
        datvlycai_0: new Date().toISOString().split('T')[0],
        salprityp_0: 52.5,
      },
      {
        bpapay_0: 'VALUE_6',
        dep_0: 'VALUE_6',
        expnum_0: 'SIN0006',
        bpainv_0: 'VALUE_6',
        adrval_0: 'VALUE_6',
        perfin_0: 'VALUE_6',
        fiy_0: 'VALUE_6',
        bprvcr_0: 'VALUE_6',
        strduddat_0: new Date().toISOString().split('T')[0],
        xduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_6',
        xncflg_0: 'VALUE_6',
        qtcaccnum_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        deprat_0: 'VALUE_6',
        belvcs_0: 'VALUE_6',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_6',
        umrnum_0: 'VALUE_6',
        spadernum_0: 'VALUE_6',
        bvrrefnum_0: 'VALUE_6',
        fld40ren_0: 'VALUE_6',
        fld41ren_0: 'VALUE_6',
        cshvat_0: 'VALUE_6',
        x4sbi_0: 'VALUE_6',
        curled_0: 'VALUE_6',
        ratdiv_0: 'VALUE_6',
        ratmlt_0: 'VALUE_6',
        sinum_0: 'VALUE_6',
        die_0: 'VALUE_6',
        exeamttax_0: 63.0,
        metcor_0: 'VALUE_6',
        pjth_0: 'VALUE_6',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 63.0,
        amtatil_0: 63.0,
        xpam_0: 'VALUE_6',
        ratdat_0: new Date().toISOString().split('T')[0],
        x4sihenvaut_0: 'VALUE_6',
        invtypspa_0: 'VALUE_6',
        upddattim_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        dcleecnum_0: 'VALUE_6',
        sstentcod_0: 'VALUE_6',
        revcansta_0: 6,
        basdep_0: 'VALUE_6',
        porexpdcl_0: 'VALUE_6',
        bpynam_0: 'Raison sociale tiers payé 6',
        bpyaddlig_0: 'VALUE_6',
        bpyposcod_0: 'VALUE_6',
        bpycty_0: 'VALUE_6',
        bpysat_0: 'VALUE_6',
        bpycry_0: 'VALUE_6',
        bpycrynam_0: 'VALUE_6',
        nbrcpy_0: 'VALUE_6',
        led_0: 'VALUE_6',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_6',
        xtimmes_0: new Date().toISOString(),
        isextdoc_0: 'VALUE_6',
        amtati_0: 63.0,
        xamtati_0: 63.0,
        bpr_0: 'VALUE_6',
        sat_0: 'VALUE_6',
        orimod_0: 'VALUE_6',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_6',
        oridocnum_0: 'VALUE_6',
        sivtyp_0: 'VALUE_6',
        accdat_0: new Date().toISOString().split('T')[0],
        fctvcr_0: 'VALUE_6',
        dirinvflg_0: 'VALUE_6',
        invtyp_0: 'VALUE_6',
        x4sihexp_0: 'VALUE_6',
        theamttax_0: 63.0,
        trsfam_0: 'VALUE_6',
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        des_0: 'VALUE_6',
        perdeb_0: 'VALUE_6',
        starpt_0: 6,
        bilvcr_0: 'VALUE_6',
        bprnam_0: 'VALUE_6',
        bpaaddlig_0: 'VALUE_6',
        crynam_0: 'VALUE_6',
        eecnumdeb_0: 'VALUE_6',
        amtnot_0: 63.0,
        xamtnot_0: 63.0,
        bastax_0: 6,
        poscod_0: 'VALUE_6',
        vac_0: 'VALUE_6',
        bprpay_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        updusr_0: 'VALUE_6',
        cce_0: 'VALUE_6',
        payban_0: 'VALUE_6',
        cpy_0: 'VALUE_6',
        fcy_0: 'VALUE_6',
        per_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        crn_0: 'VALUE_6',
        tax_0: 'VALUE_6',
        sns_0: 'VALUE_6',
        x4sihdest_0: 'VALUE_6',
        bprfct_0: 'VALUE_6',
        pte_0: 'VALUE_6',
        cur_0: 'VALUE_6',
        num_0: 'VALUE_6',
        gte_0: 'VALUE_6',
        bprsac_0: 'VALUE_6',
        jou_0: 'VALUE_6',
        wrhe_0: 'VALUE_6',
        cty_0: 'VALUE_6',
        cry_0: 'VALUE_6',
        invnum_0: 'VALUE_6',
        nbrtax_0: 'VALUE_6',
        amttax_0: 63.0,
        amttaxusa_0: 63.0,
        fctvcrflg_0: 'VALUE_6',
        cai_0: 'VALUE_6',
        datvlycai_0: new Date().toISOString().split('T')[0],
        salprityp_0: 63.0,
      },
      {
        bpapay_0: 'VALUE_7',
        dep_0: 'VALUE_7',
        expnum_0: 'SIN0007',
        bpainv_0: 'VALUE_7',
        adrval_0: 'VALUE_7',
        perfin_0: 'VALUE_7',
        fiy_0: 'VALUE_7',
        bprvcr_0: 'VALUE_7',
        strduddat_0: new Date().toISOString().split('T')[0],
        xduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_7',
        xncflg_0: 'VALUE_7',
        qtcaccnum_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        deprat_0: 'VALUE_7',
        belvcs_0: 'VALUE_7',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_7',
        umrnum_0: 'VALUE_7',
        spadernum_0: 'VALUE_7',
        bvrrefnum_0: 'VALUE_7',
        fld40ren_0: 'VALUE_7',
        fld41ren_0: 'VALUE_7',
        cshvat_0: 'VALUE_7',
        x4sbi_0: 'VALUE_7',
        curled_0: 'VALUE_7',
        ratdiv_0: 'VALUE_7',
        ratmlt_0: 'VALUE_7',
        sinum_0: 'VALUE_7',
        die_0: 'VALUE_7',
        exeamttax_0: 73.5,
        metcor_0: 'VALUE_7',
        pjth_0: 'VALUE_7',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 73.5,
        amtatil_0: 73.5,
        xpam_0: 'VALUE_7',
        ratdat_0: new Date().toISOString().split('T')[0],
        x4sihenvaut_0: 'VALUE_7',
        invtypspa_0: 'VALUE_7',
        upddattim_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        dcleecnum_0: 'VALUE_7',
        sstentcod_0: 'VALUE_7',
        revcansta_0: 7,
        basdep_0: 'VALUE_7',
        porexpdcl_0: 'VALUE_7',
        bpynam_0: 'Raison sociale tiers payé 7',
        bpyaddlig_0: 'VALUE_7',
        bpyposcod_0: 'VALUE_7',
        bpycty_0: 'VALUE_7',
        bpysat_0: 'VALUE_7',
        bpycry_0: 'VALUE_7',
        bpycrynam_0: 'VALUE_7',
        nbrcpy_0: 'VALUE_7',
        led_0: 'VALUE_7',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_7',
        xtimmes_0: new Date().toISOString(),
        isextdoc_0: 'VALUE_7',
        amtati_0: 73.5,
        xamtati_0: 73.5,
        bpr_0: 'VALUE_7',
        sat_0: 'VALUE_7',
        orimod_0: 'VALUE_7',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_7',
        oridocnum_0: 'VALUE_7',
        sivtyp_0: 'VALUE_7',
        accdat_0: new Date().toISOString().split('T')[0],
        fctvcr_0: 'VALUE_7',
        dirinvflg_0: 'VALUE_7',
        invtyp_0: 'VALUE_7',
        x4sihexp_0: 'VALUE_7',
        theamttax_0: 73.5,
        trsfam_0: 'VALUE_7',
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        des_0: 'VALUE_7',
        perdeb_0: 'VALUE_7',
        starpt_0: 7,
        bilvcr_0: 'VALUE_7',
        bprnam_0: 'VALUE_7',
        bpaaddlig_0: 'VALUE_7',
        crynam_0: 'VALUE_7',
        eecnumdeb_0: 'VALUE_7',
        amtnot_0: 73.5,
        xamtnot_0: 73.5,
        bastax_0: 7,
        poscod_0: 'VALUE_7',
        vac_0: 'VALUE_7',
        bprpay_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        updusr_0: 'VALUE_7',
        cce_0: 'VALUE_7',
        payban_0: 'VALUE_7',
        cpy_0: 'VALUE_7',
        fcy_0: 'VALUE_7',
        per_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        crn_0: 'VALUE_7',
        tax_0: 'VALUE_7',
        sns_0: 'VALUE_7',
        x4sihdest_0: 'VALUE_7',
        bprfct_0: 'VALUE_7',
        pte_0: 'VALUE_7',
        cur_0: 'VALUE_7',
        num_0: 'VALUE_7',
        gte_0: 'VALUE_7',
        bprsac_0: 'VALUE_7',
        jou_0: 'VALUE_7',
        wrhe_0: 'VALUE_7',
        cty_0: 'VALUE_7',
        cry_0: 'VALUE_7',
        invnum_0: 'VALUE_7',
        nbrtax_0: 'VALUE_7',
        amttax_0: 73.5,
        amttaxusa_0: 73.5,
        fctvcrflg_0: 'VALUE_7',
        cai_0: 'VALUE_7',
        datvlycai_0: new Date().toISOString().split('T')[0],
        salprityp_0: 73.5,
      },
      {
        bpapay_0: 'VALUE_8',
        dep_0: 'VALUE_8',
        expnum_0: 'SIN0008',
        bpainv_0: 'VALUE_8',
        adrval_0: 'VALUE_8',
        perfin_0: 'VALUE_8',
        fiy_0: 'VALUE_8',
        bprvcr_0: 'VALUE_8',
        strduddat_0: new Date().toISOString().split('T')[0],
        xduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_8',
        xncflg_0: 'VALUE_8',
        qtcaccnum_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        deprat_0: 'VALUE_8',
        belvcs_0: 'VALUE_8',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_8',
        umrnum_0: 'VALUE_8',
        spadernum_0: 'VALUE_8',
        bvrrefnum_0: 'VALUE_8',
        fld40ren_0: 'VALUE_8',
        fld41ren_0: 'VALUE_8',
        cshvat_0: 'VALUE_8',
        x4sbi_0: 'VALUE_8',
        curled_0: 'VALUE_8',
        ratdiv_0: 'VALUE_8',
        ratmlt_0: 'VALUE_8',
        sinum_0: 'VALUE_8',
        die_0: 'VALUE_8',
        exeamttax_0: 84.0,
        metcor_0: 'VALUE_8',
        pjth_0: 'VALUE_8',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 84.0,
        amtatil_0: 84.0,
        xpam_0: 'VALUE_8',
        ratdat_0: new Date().toISOString().split('T')[0],
        x4sihenvaut_0: 'VALUE_8',
        invtypspa_0: 'VALUE_8',
        upddattim_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        dcleecnum_0: 'VALUE_8',
        sstentcod_0: 'VALUE_8',
        revcansta_0: 8,
        basdep_0: 'VALUE_8',
        porexpdcl_0: 'VALUE_8',
        bpynam_0: 'Raison sociale tiers payé 8',
        bpyaddlig_0: 'VALUE_8',
        bpyposcod_0: 'VALUE_8',
        bpycty_0: 'VALUE_8',
        bpysat_0: 'VALUE_8',
        bpycry_0: 'VALUE_8',
        bpycrynam_0: 'VALUE_8',
        nbrcpy_0: 'VALUE_8',
        led_0: 'VALUE_8',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_8',
        xtimmes_0: new Date().toISOString(),
        isextdoc_0: 'VALUE_8',
        amtati_0: 84.0,
        xamtati_0: 84.0,
        bpr_0: 'VALUE_8',
        sat_0: 'VALUE_8',
        orimod_0: 'VALUE_8',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_8',
        oridocnum_0: 'VALUE_8',
        sivtyp_0: 'VALUE_8',
        accdat_0: new Date().toISOString().split('T')[0],
        fctvcr_0: 'VALUE_8',
        dirinvflg_0: 'VALUE_8',
        invtyp_0: 'VALUE_8',
        x4sihexp_0: 'VALUE_8',
        theamttax_0: 84.0,
        trsfam_0: 'VALUE_8',
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        des_0: 'VALUE_8',
        perdeb_0: 'VALUE_8',
        starpt_0: 8,
        bilvcr_0: 'VALUE_8',
        bprnam_0: 'VALUE_8',
        bpaaddlig_0: 'VALUE_8',
        crynam_0: 'VALUE_8',
        eecnumdeb_0: 'VALUE_8',
        amtnot_0: 84.0,
        xamtnot_0: 84.0,
        bastax_0: 8,
        poscod_0: 'VALUE_8',
        vac_0: 'VALUE_8',
        bprpay_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        updusr_0: 'VALUE_8',
        cce_0: 'VALUE_8',
        payban_0: 'VALUE_8',
        cpy_0: 'VALUE_8',
        fcy_0: 'VALUE_8',
        per_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        crn_0: 'VALUE_8',
        tax_0: 'VALUE_8',
        sns_0: 'VALUE_8',
        x4sihdest_0: 'VALUE_8',
        bprfct_0: 'VALUE_8',
        pte_0: 'VALUE_8',
        cur_0: 'VALUE_8',
        num_0: 'VALUE_8',
        gte_0: 'VALUE_8',
        bprsac_0: 'VALUE_8',
        jou_0: 'VALUE_8',
        wrhe_0: 'VALUE_8',
        cty_0: 'VALUE_8',
        cry_0: 'VALUE_8',
        invnum_0: 'VALUE_8',
        nbrtax_0: 'VALUE_8',
        amttax_0: 84.0,
        amttaxusa_0: 84.0,
        fctvcrflg_0: 'VALUE_8',
        cai_0: 'VALUE_8',
        datvlycai_0: new Date().toISOString().split('T')[0],
        salprityp_0: 84.0,
      },
      {
        bpapay_0: 'VALUE_9',
        dep_0: 'VALUE_9',
        expnum_0: 'SIN0009',
        bpainv_0: 'VALUE_9',
        adrval_0: 'VALUE_9',
        perfin_0: 'VALUE_9',
        fiy_0: 'VALUE_9',
        bprvcr_0: 'VALUE_9',
        strduddat_0: new Date().toISOString().split('T')[0],
        xduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_9',
        xncflg_0: 'VALUE_9',
        qtcaccnum_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        deprat_0: 'VALUE_9',
        belvcs_0: 'VALUE_9',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_9',
        umrnum_0: 'VALUE_9',
        spadernum_0: 'VALUE_9',
        bvrrefnum_0: 'VALUE_9',
        fld40ren_0: 'VALUE_9',
        fld41ren_0: 'VALUE_9',
        cshvat_0: 'VALUE_9',
        x4sbi_0: 'VALUE_9',
        curled_0: 'VALUE_9',
        ratdiv_0: 'VALUE_9',
        ratmlt_0: 'VALUE_9',
        sinum_0: 'VALUE_9',
        die_0: 'VALUE_9',
        exeamttax_0: 94.5,
        metcor_0: 'VALUE_9',
        pjth_0: 'VALUE_9',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 94.5,
        amtatil_0: 94.5,
        xpam_0: 'VALUE_9',
        ratdat_0: new Date().toISOString().split('T')[0],
        x4sihenvaut_0: 'VALUE_9',
        invtypspa_0: 'VALUE_9',
        upddattim_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        dcleecnum_0: 'VALUE_9',
        sstentcod_0: 'VALUE_9',
        revcansta_0: 9,
        basdep_0: 'VALUE_9',
        porexpdcl_0: 'VALUE_9',
        bpynam_0: 'Raison sociale tiers payé 9',
        bpyaddlig_0: 'VALUE_9',
        bpyposcod_0: 'VALUE_9',
        bpycty_0: 'VALUE_9',
        bpysat_0: 'VALUE_9',
        bpycry_0: 'VALUE_9',
        bpycrynam_0: 'VALUE_9',
        nbrcpy_0: 'VALUE_9',
        led_0: 'VALUE_9',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_9',
        xtimmes_0: new Date().toISOString(),
        isextdoc_0: 'VALUE_9',
        amtati_0: 94.5,
        xamtati_0: 94.5,
        bpr_0: 'VALUE_9',
        sat_0: 'VALUE_9',
        orimod_0: 'VALUE_9',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_9',
        oridocnum_0: 'VALUE_9',
        sivtyp_0: 'VALUE_9',
        accdat_0: new Date().toISOString().split('T')[0],
        fctvcr_0: 'VALUE_9',
        dirinvflg_0: 'VALUE_9',
        invtyp_0: 'VALUE_9',
        x4sihexp_0: 'VALUE_9',
        theamttax_0: 94.5,
        trsfam_0: 'VALUE_9',
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        des_0: 'VALUE_9',
        perdeb_0: 'VALUE_9',
        starpt_0: 9,
        bilvcr_0: 'VALUE_9',
        bprnam_0: 'VALUE_9',
        bpaaddlig_0: 'VALUE_9',
        crynam_0: 'VALUE_9',
        eecnumdeb_0: 'VALUE_9',
        amtnot_0: 94.5,
        xamtnot_0: 94.5,
        bastax_0: 9,
        poscod_0: 'VALUE_9',
        vac_0: 'VALUE_9',
        bprpay_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        updusr_0: 'VALUE_9',
        cce_0: 'VALUE_9',
        payban_0: 'VALUE_9',
        cpy_0: 'VALUE_9',
        fcy_0: 'VALUE_9',
        per_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        crn_0: 'VALUE_9',
        tax_0: 'VALUE_9',
        sns_0: 'VALUE_9',
        x4sihdest_0: 'VALUE_9',
        bprfct_0: 'VALUE_9',
        pte_0: 'VALUE_9',
        cur_0: 'VALUE_9',
        num_0: 'VALUE_9',
        gte_0: 'VALUE_9',
        bprsac_0: 'VALUE_9',
        jou_0: 'VALUE_9',
        wrhe_0: 'VALUE_9',
        cty_0: 'VALUE_9',
        cry_0: 'VALUE_9',
        invnum_0: 'VALUE_9',
        nbrtax_0: 'VALUE_9',
        amttax_0: 94.5,
        amttaxusa_0: 94.5,
        fctvcrflg_0: 'VALUE_9',
        cai_0: 'VALUE_9',
        datvlycai_0: new Date().toISOString().split('T')[0],
        salprityp_0: 94.5,
      },
      {
        bpapay_0: 'VALUE_10',
        dep_0: 'VALUE_10',
        expnum_0: 'SIN0010',
        bpainv_0: 'VALUE_10',
        adrval_0: 'VALUE_10',
        perfin_0: 'VALUE_10',
        fiy_0: 'VALUE_10',
        bprvcr_0: 'VALUE_10',
        strduddat_0: new Date().toISOString().split('T')[0],
        xduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_10',
        xncflg_0: 'VALUE_10',
        qtcaccnum_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        deprat_0: 'VALUE_10',
        belvcs_0: 'VALUE_10',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_10',
        umrnum_0: 'VALUE_10',
        spadernum_0: 'VALUE_10',
        bvrrefnum_0: 'VALUE_10',
        fld40ren_0: 'VALUE_10',
        fld41ren_0: 'VALUE_10',
        cshvat_0: 'VALUE_10',
        x4sbi_0: 'VALUE_10',
        curled_0: 'VALUE_10',
        ratdiv_0: 'VALUE_10',
        ratmlt_0: 'VALUE_10',
        sinum_0: 'VALUE_10',
        die_0: 'VALUE_10',
        exeamttax_0: 105.0,
        metcor_0: 'VALUE_10',
        pjth_0: 'VALUE_10',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 105.0,
        amtatil_0: 105.0,
        xpam_0: 'VALUE_10',
        ratdat_0: new Date().toISOString().split('T')[0],
        x4sihenvaut_0: 'VALUE_10',
        invtypspa_0: 'VALUE_10',
        upddattim_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        dcleecnum_0: 'VALUE_10',
        sstentcod_0: 'VALUE_10',
        revcansta_0: 10,
        basdep_0: 'VALUE_10',
        porexpdcl_0: 'VALUE_10',
        bpynam_0: 'Raison sociale tiers payé 10',
        bpyaddlig_0: 'VALUE_10',
        bpyposcod_0: 'VALUE_10',
        bpycty_0: 'VALUE_10',
        bpysat_0: 'VALUE_10',
        bpycry_0: 'VALUE_10',
        bpycrynam_0: 'VALUE_10',
        nbrcpy_0: 'VALUE_10',
        led_0: 'VALUE_10',
        xdatmes_0: new Date().toISOString().split('T')[0],
        xnummes_0: 'VALUE_10',
        xtimmes_0: new Date().toISOString(),
        isextdoc_0: 'VALUE_10',
        amtati_0: 105.0,
        xamtati_0: 105.0,
        bpr_0: 'VALUE_10',
        sat_0: 'VALUE_10',
        orimod_0: 'VALUE_10',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_10',
        oridocnum_0: 'VALUE_10',
        sivtyp_0: 'VALUE_10',
        accdat_0: new Date().toISOString().split('T')[0],
        fctvcr_0: 'VALUE_10',
        dirinvflg_0: 'VALUE_10',
        invtyp_0: 'VALUE_10',
        x4sihexp_0: 'VALUE_10',
        theamttax_0: 105.0,
        trsfam_0: 'VALUE_10',
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        des_0: 'VALUE_10',
        perdeb_0: 'VALUE_10',
        starpt_0: 10,
        bilvcr_0: 'VALUE_10',
        bprnam_0: 'VALUE_10',
        bpaaddlig_0: 'VALUE_10',
        crynam_0: 'VALUE_10',
        eecnumdeb_0: 'VALUE_10',
        amtnot_0: 105.0,
        xamtnot_0: 105.0,
        bastax_0: 10,
        poscod_0: 'VALUE_10',
        vac_0: 'VALUE_10',
        bprpay_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        updusr_0: 'VALUE_10',
        cce_0: 'VALUE_10',
        payban_0: 'VALUE_10',
        cpy_0: 'VALUE_10',
        fcy_0: 'VALUE_10',
        per_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        crn_0: 'VALUE_10',
        tax_0: 'VALUE_10',
        sns_0: 'VALUE_10',
        x4sihdest_0: 'VALUE_10',
        bprfct_0: 'VALUE_10',
        pte_0: 'VALUE_10',
        cur_0: 'VALUE_10',
        num_0: 'VALUE_10',
        gte_0: 'VALUE_10',
        bprsac_0: 'VALUE_10',
        jou_0: 'VALUE_10',
        wrhe_0: 'VALUE_10',
        cty_0: 'VALUE_10',
        cry_0: 'VALUE_10',
        invnum_0: 'VALUE_10',
        nbrtax_0: 'VALUE_10',
        amttax_0: 105.0,
        amttaxusa_0: 105.0,
        fctvcrflg_0: 'VALUE_10',
        cai_0: 'VALUE_10',
        datvlycai_0: new Date().toISOString().split('T')[0],
        salprityp_0: 105.0,
      },
    ]

    await Database.table('sinvoice').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans sinvoice`)
  }
}
