import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour PORDERQ
    const data = [
      {
        x4avmotd_0: 'VALUE_1',
        zfabnum_0: 'POR0001',
        zitmreffab_0: 'VALUE_1',
        x4exclrfad_0: 'VALUE_1',
        zdatcof_0: new Date().toISOString().split('T')[0],
        x4hwee_0: 'VALUE_1',
        x4hyea_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cstpur_0: 'VALUE_1',
        lincstpur_0: 'VALUE_1',
        fcscstpur_0: 'VALUE_1',
        fcscpr_0: 'VALUE_1',
        reacstpur_0: 'VALUE_1',
        clcamt7_0: 10.5,
        stcnum_0: 'VALUE_1',
        x4avmotcomd_0: 'VALUE_1',
        x4hextrcpd_0: 'VALUE_1',
        x4hcad_0: 'VALUE_1',
        linamtcpr_0: 'Coût stock 1',
        x4flgblc_0: 'VALUE_1',
        cpramt_0: 10.5,
        xalerte_0: 'VALUE_1',
        cpr_0: 'VALUE_1',
        eccvalmaj_0: 'VALUE_1',
        eccvalmin_0: 'VALUE_1',
        clcamt3_0: 10.5,
        clcamt4_0: 10.5,
        clcamt5_0: 10.5,
        clcamt6_0: 10.5,
        xdlvtimdeb_0: new Date().toISOString(),
        likqtycoe_0: 10.5,
        cmmflg_0: 'VALUE_1',
        zsigfab_0: 'VALUE_1',
        x4pohfab_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        shiqtypuu_0: 10.5,
        x4pohagr_0: 'VALUE_1',
        x4pohbpa_0: 'VALUE_1',
        shiqtystu_0: 10.5,
        cprpri_0: 10.5,
        cmmtax_0: 'VALUE_1',
        discrgamt9_0: 10.5,
        fcyadd_0: 'VALUE_1',
        cprcur_0: 'VALUE_1',
        qtyvou_0: 10.5,
        sddlin_0: 'VALUE_1',
        lintyp_0: 'VALUE_1',
        puu_0: 'VALUE_1',
        yea_0: 'VALUE_1',
        wipnum_0: 'VALUE_1',
        mon_0: 'VALUE_1',
        discrgamt1_0: 10.5,
        pck_0: 'VALUE_1',
        lininvflg_0: 'VALUE_1',
        extrcpdat_0: new Date().toISOString().split('T')[0],
        poqlnk_0: 'VALUE_1',
        amttaxlin2_0: 10.5,
        discrgamt2_0: 10.5,
        discrgamt3_0: 10.5,
        uom_0: 'VALUE_1',
        uompuucoe_0: 'VALUE_1',
        uomflg_0: 'VALUE_1',
        dedtaxrcp_0: 'VALUE_1',
        dedtaxiss_0: 'VALUE_1',
        dedtaxoth1_0: 'VALUE_1',
        dedtaxoth2_0: 'VALUE_1',
        amttaxlin1_0: 10.5,
        rcpcleflg_0: 'VALUE_1',
        xobj1_0: 'VALUE_1',
        xobj2_0: 'VALUE_1',
        ocnlin_0: 'VALUE_1',
        ocnseq_0: 'VALUE_1',
        linocnflg_0: 'VALUE_1',
        vcrtypori_0: 'VALUE_1',
        vcrlinori_0: 'VALUE_1',
        itmrefori_0: 'VALUE_1',
        vcrseqori_0: 'VALUE_1',
        bpsnum_0: 'VALUE_1',
        vcrnumori_0: 'VALUE_1',
        poqseq_0: 'VALUE_1',
        xsoqseq_0: 'VALUE_1',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_1',
        bpainv_0: 'VALUE_1',
        invqtypuu_0: 10.5,
        invqtystu_0: 10.5,
        stu_0: 'VALUE_1',
        soqseq_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        linati_0: 'VALUE_1',
        linatiamt_0: 10.5,
        pqhnum_0: 'VALUE_1',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_1',
        linstofcy_0: 'VALUE_1',
        xversion_0: 'VALUE_1',
        linweu_0: 'VALUE_1',
        qtyweu_0: 10.5,
        itmref_0: 'VALUE_1',
        netcur_0: 'VALUE_1',
        cprcoe_0: 'VALUE_1',
        itmrefbps_0: 'VALUE_1',
        ori_0: 'VALUE_1',
        clcamt2_0: 10.5,
        demenddat_0: new Date().toISOString().split('T')[0],
        demendhou_0: 'VALUE_1',
        linocndat_0: new Date().toISOString().split('T')[0],
        linocnnum_0: 'VALUE_1',
        qtystu_0: 10.5,
        lincleflg_0: 'VALUE_1',
        linprnflg_0: 'VALUE_1',
        qtyuom_0: 10.5,
        sohnum_0: 'VALUE_1',
        clcamt1_0: 10.5,
        ofs_0: 'VALUE_1',
        sdhnum_0: 'VALUE_1',
        pohnum_0: 'VALUE_1',
        xsohnum_0: 'VALUE_1',
        wiptyp_0: 'VALUE_1',
        retrcpdat_0: new Date().toISOString().split('T')[0],
        retqtystu_0: 10.5,
        retqtypuu_0: 10.5,
        fbuflg_0: 'VALUE_1',
        useplc_0: 'VALUE_1',
        xqtystu_0: 10.5,
        ptdlin_0: 'VALUE_1',
        xsoplin_0: 'VALUE_1',
        cpy_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        rcpqtypuu_0: 10.5,
        rcpqtystu_0: 10.5,
        lininvnbr_0: 'VALUE_1',
        linrcpnbr_0: 'VALUE_1',
        invrcpnbr_0: 'VALUE_1',
        lintex_0: 'VALUE_1',
        linamt_0: 10.5,
        scoadd_0: 'VALUE_1',
        itmknd_0: 'VALUE_1',
        ybprliv_0: 'VALUE_1',
        yaddliv_0: 'VALUE_1',
        xexport_0: 'VALUE_1',
        xqty_0: 10.5,
        amttaxrcp_0: 10.5,
        amttaxiss_0: 10.5,
        amttaxoth1_0: 10.5,
        amttaxoth2_0: 10.5,
        xdlvtimfin_0: new Date().toISOString(),
        disbaslin1_0: 'VALUE_1',
        discrgamt5_0: 10.5,
        discrgamt4_0: 10.5,
        discrgamt6_0: 10.5,
        discrgamt7_0: 10.5,
        discrgamt8_0: 10.5,
        soplin_0: 'VALUE_1',
        poplin_0: 'VALUE_1',
        pohtyp_0: 'VALUE_1',
        linrevnum_0: 'VALUE_1',
        orddat_0: new Date().toISOString().split('T')[0],
        qtypuu_0: 10.5,
        pohfcy_0: 'VALUE_1',
        prhfcy_0: 'VALUE_1',
        pthnum_0: 'VALUE_1',
        linsta_0: 1,
        demrcpdat_0: new Date().toISOString().split('T')[0],
        demrcphou_0: 'VALUE_1',
        linvou_0: 'VALUE_1',
        ppdlin_0: 'VALUE_1',
        bpsinv_0: 'VALUE_1',
        cad_0: 'VALUE_1',
        wee_0: 'VALUE_1',
        cmmnum_0: 'VALUE_1',
        linpurtyp_0: 'VALUE_1',
        xtypobj_0: 'VALUE_1',
        bastaxlin1_0: 1,
        wipsta_0: 1,
        amttaxlin3_0: 10.5,
        dedtaxlin1_0: 'VALUE_1',
        dedtaxlin2_0: 'VALUE_1',
        dedtaxlin3_0: 'VALUE_1',
      },
      {
        x4avmotd_0: 'VALUE_2',
        zfabnum_0: 'POR0002',
        zitmreffab_0: 'VALUE_2',
        x4exclrfad_0: 'VALUE_2',
        zdatcof_0: new Date().toISOString().split('T')[0],
        x4hwee_0: 'VALUE_2',
        x4hyea_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cstpur_0: 'VALUE_2',
        lincstpur_0: 'VALUE_2',
        fcscstpur_0: 'VALUE_2',
        fcscpr_0: 'VALUE_2',
        reacstpur_0: 'VALUE_2',
        clcamt7_0: 21.0,
        stcnum_0: 'VALUE_2',
        x4avmotcomd_0: 'VALUE_2',
        x4hextrcpd_0: 'VALUE_2',
        x4hcad_0: 'VALUE_2',
        linamtcpr_0: 'Coût stock 2',
        x4flgblc_0: 'VALUE_2',
        cpramt_0: 21.0,
        xalerte_0: 'VALUE_2',
        cpr_0: 'VALUE_2',
        eccvalmaj_0: 'VALUE_2',
        eccvalmin_0: 'VALUE_2',
        clcamt3_0: 21.0,
        clcamt4_0: 21.0,
        clcamt5_0: 21.0,
        clcamt6_0: 21.0,
        xdlvtimdeb_0: new Date().toISOString(),
        likqtycoe_0: 21.0,
        cmmflg_0: 'VALUE_2',
        zsigfab_0: 'VALUE_2',
        x4pohfab_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        shiqtypuu_0: 21.0,
        x4pohagr_0: 'VALUE_2',
        x4pohbpa_0: 'VALUE_2',
        shiqtystu_0: 21.0,
        cprpri_0: 21.0,
        cmmtax_0: 'VALUE_2',
        discrgamt9_0: 21.0,
        fcyadd_0: 'VALUE_2',
        cprcur_0: 'VALUE_2',
        qtyvou_0: 21.0,
        sddlin_0: 'VALUE_2',
        lintyp_0: 'VALUE_2',
        puu_0: 'VALUE_2',
        yea_0: 'VALUE_2',
        wipnum_0: 'VALUE_2',
        mon_0: 'VALUE_2',
        discrgamt1_0: 21.0,
        pck_0: 'VALUE_2',
        lininvflg_0: 'VALUE_2',
        extrcpdat_0: new Date().toISOString().split('T')[0],
        poqlnk_0: 'VALUE_2',
        amttaxlin2_0: 21.0,
        discrgamt2_0: 21.0,
        discrgamt3_0: 21.0,
        uom_0: 'VALUE_2',
        uompuucoe_0: 'VALUE_2',
        uomflg_0: 'VALUE_2',
        dedtaxrcp_0: 'VALUE_2',
        dedtaxiss_0: 'VALUE_2',
        dedtaxoth1_0: 'VALUE_2',
        dedtaxoth2_0: 'VALUE_2',
        amttaxlin1_0: 21.0,
        rcpcleflg_0: 'VALUE_2',
        xobj1_0: 'VALUE_2',
        xobj2_0: 'VALUE_2',
        ocnlin_0: 'VALUE_2',
        ocnseq_0: 'VALUE_2',
        linocnflg_0: 'VALUE_2',
        vcrtypori_0: 'VALUE_2',
        vcrlinori_0: 'VALUE_2',
        itmrefori_0: 'VALUE_2',
        vcrseqori_0: 'VALUE_2',
        bpsnum_0: 'VALUE_2',
        vcrnumori_0: 'VALUE_2',
        poqseq_0: 'VALUE_2',
        xsoqseq_0: 'VALUE_2',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_2',
        bpainv_0: 'VALUE_2',
        invqtypuu_0: 21.0,
        invqtystu_0: 21.0,
        stu_0: 'VALUE_2',
        soqseq_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        linati_0: 'VALUE_2',
        linatiamt_0: 21.0,
        pqhnum_0: 'VALUE_2',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_2',
        linstofcy_0: 'VALUE_2',
        xversion_0: 'VALUE_2',
        linweu_0: 'VALUE_2',
        qtyweu_0: 21.0,
        itmref_0: 'VALUE_2',
        netcur_0: 'VALUE_2',
        cprcoe_0: 'VALUE_2',
        itmrefbps_0: 'VALUE_2',
        ori_0: 'VALUE_2',
        clcamt2_0: 21.0,
        demenddat_0: new Date().toISOString().split('T')[0],
        demendhou_0: 'VALUE_2',
        linocndat_0: new Date().toISOString().split('T')[0],
        linocnnum_0: 'VALUE_2',
        qtystu_0: 21.0,
        lincleflg_0: 'VALUE_2',
        linprnflg_0: 'VALUE_2',
        qtyuom_0: 21.0,
        sohnum_0: 'VALUE_2',
        clcamt1_0: 21.0,
        ofs_0: 'VALUE_2',
        sdhnum_0: 'VALUE_2',
        pohnum_0: 'VALUE_2',
        xsohnum_0: 'VALUE_2',
        wiptyp_0: 'VALUE_2',
        retrcpdat_0: new Date().toISOString().split('T')[0],
        retqtystu_0: 21.0,
        retqtypuu_0: 21.0,
        fbuflg_0: 'VALUE_2',
        useplc_0: 'VALUE_2',
        xqtystu_0: 21.0,
        ptdlin_0: 'VALUE_2',
        xsoplin_0: 'VALUE_2',
        cpy_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        rcpqtypuu_0: 21.0,
        rcpqtystu_0: 21.0,
        lininvnbr_0: 'VALUE_2',
        linrcpnbr_0: 'VALUE_2',
        invrcpnbr_0: 'VALUE_2',
        lintex_0: 'VALUE_2',
        linamt_0: 21.0,
        scoadd_0: 'VALUE_2',
        itmknd_0: 'VALUE_2',
        ybprliv_0: 'VALUE_2',
        yaddliv_0: 'VALUE_2',
        xexport_0: 'VALUE_2',
        xqty_0: 21.0,
        amttaxrcp_0: 21.0,
        amttaxiss_0: 21.0,
        amttaxoth1_0: 21.0,
        amttaxoth2_0: 21.0,
        xdlvtimfin_0: new Date().toISOString(),
        disbaslin1_0: 'VALUE_2',
        discrgamt5_0: 21.0,
        discrgamt4_0: 21.0,
        discrgamt6_0: 21.0,
        discrgamt7_0: 21.0,
        discrgamt8_0: 21.0,
        soplin_0: 'VALUE_2',
        poplin_0: 'VALUE_2',
        pohtyp_0: 'VALUE_2',
        linrevnum_0: 'VALUE_2',
        orddat_0: new Date().toISOString().split('T')[0],
        qtypuu_0: 21.0,
        pohfcy_0: 'VALUE_2',
        prhfcy_0: 'VALUE_2',
        pthnum_0: 'VALUE_2',
        linsta_0: 1,
        demrcpdat_0: new Date().toISOString().split('T')[0],
        demrcphou_0: 'VALUE_2',
        linvou_0: 'VALUE_2',
        ppdlin_0: 'VALUE_2',
        bpsinv_0: 'VALUE_2',
        cad_0: 'VALUE_2',
        wee_0: 'VALUE_2',
        cmmnum_0: 'VALUE_2',
        linpurtyp_0: 'VALUE_2',
        xtypobj_0: 'VALUE_2',
        bastaxlin1_0: 2,
        wipsta_0: 2,
        amttaxlin3_0: 21.0,
        dedtaxlin1_0: 'VALUE_2',
        dedtaxlin2_0: 'VALUE_2',
        dedtaxlin3_0: 'VALUE_2',
      },
      {
        x4avmotd_0: 'VALUE_3',
        zfabnum_0: 'POR0003',
        zitmreffab_0: 'VALUE_3',
        x4exclrfad_0: 'VALUE_3',
        zdatcof_0: new Date().toISOString().split('T')[0],
        x4hwee_0: 'VALUE_3',
        x4hyea_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cstpur_0: 'VALUE_3',
        lincstpur_0: 'VALUE_3',
        fcscstpur_0: 'VALUE_3',
        fcscpr_0: 'VALUE_3',
        reacstpur_0: 'VALUE_3',
        clcamt7_0: 31.5,
        stcnum_0: 'VALUE_3',
        x4avmotcomd_0: 'VALUE_3',
        x4hextrcpd_0: 'VALUE_3',
        x4hcad_0: 'VALUE_3',
        linamtcpr_0: 'Coût stock 3',
        x4flgblc_0: 'VALUE_3',
        cpramt_0: 31.5,
        xalerte_0: 'VALUE_3',
        cpr_0: 'VALUE_3',
        eccvalmaj_0: 'VALUE_3',
        eccvalmin_0: 'VALUE_3',
        clcamt3_0: 31.5,
        clcamt4_0: 31.5,
        clcamt5_0: 31.5,
        clcamt6_0: 31.5,
        xdlvtimdeb_0: new Date().toISOString(),
        likqtycoe_0: 31.5,
        cmmflg_0: 'VALUE_3',
        zsigfab_0: 'VALUE_3',
        x4pohfab_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        shiqtypuu_0: 31.5,
        x4pohagr_0: 'VALUE_3',
        x4pohbpa_0: 'VALUE_3',
        shiqtystu_0: 31.5,
        cprpri_0: 31.5,
        cmmtax_0: 'VALUE_3',
        discrgamt9_0: 31.5,
        fcyadd_0: 'VALUE_3',
        cprcur_0: 'VALUE_3',
        qtyvou_0: 31.5,
        sddlin_0: 'VALUE_3',
        lintyp_0: 'VALUE_3',
        puu_0: 'VALUE_3',
        yea_0: 'VALUE_3',
        wipnum_0: 'VALUE_3',
        mon_0: 'VALUE_3',
        discrgamt1_0: 31.5,
        pck_0: 'VALUE_3',
        lininvflg_0: 'VALUE_3',
        extrcpdat_0: new Date().toISOString().split('T')[0],
        poqlnk_0: 'VALUE_3',
        amttaxlin2_0: 31.5,
        discrgamt2_0: 31.5,
        discrgamt3_0: 31.5,
        uom_0: 'VALUE_3',
        uompuucoe_0: 'VALUE_3',
        uomflg_0: 'VALUE_3',
        dedtaxrcp_0: 'VALUE_3',
        dedtaxiss_0: 'VALUE_3',
        dedtaxoth1_0: 'VALUE_3',
        dedtaxoth2_0: 'VALUE_3',
        amttaxlin1_0: 31.5,
        rcpcleflg_0: 'VALUE_3',
        xobj1_0: 'VALUE_3',
        xobj2_0: 'VALUE_3',
        ocnlin_0: 'VALUE_3',
        ocnseq_0: 'VALUE_3',
        linocnflg_0: 'VALUE_3',
        vcrtypori_0: 'VALUE_3',
        vcrlinori_0: 'VALUE_3',
        itmrefori_0: 'VALUE_3',
        vcrseqori_0: 'VALUE_3',
        bpsnum_0: 'VALUE_3',
        vcrnumori_0: 'VALUE_3',
        poqseq_0: 'VALUE_3',
        xsoqseq_0: 'VALUE_3',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_3',
        bpainv_0: 'VALUE_3',
        invqtypuu_0: 31.5,
        invqtystu_0: 31.5,
        stu_0: 'VALUE_3',
        soqseq_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        linati_0: 'VALUE_3',
        linatiamt_0: 31.5,
        pqhnum_0: 'VALUE_3',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_3',
        linstofcy_0: 'VALUE_3',
        xversion_0: 'VALUE_3',
        linweu_0: 'VALUE_3',
        qtyweu_0: 31.5,
        itmref_0: 'VALUE_3',
        netcur_0: 'VALUE_3',
        cprcoe_0: 'VALUE_3',
        itmrefbps_0: 'VALUE_3',
        ori_0: 'VALUE_3',
        clcamt2_0: 31.5,
        demenddat_0: new Date().toISOString().split('T')[0],
        demendhou_0: 'VALUE_3',
        linocndat_0: new Date().toISOString().split('T')[0],
        linocnnum_0: 'VALUE_3',
        qtystu_0: 31.5,
        lincleflg_0: 'VALUE_3',
        linprnflg_0: 'VALUE_3',
        qtyuom_0: 31.5,
        sohnum_0: 'VALUE_3',
        clcamt1_0: 31.5,
        ofs_0: 'VALUE_3',
        sdhnum_0: 'VALUE_3',
        pohnum_0: 'VALUE_3',
        xsohnum_0: 'VALUE_3',
        wiptyp_0: 'VALUE_3',
        retrcpdat_0: new Date().toISOString().split('T')[0],
        retqtystu_0: 31.5,
        retqtypuu_0: 31.5,
        fbuflg_0: 'VALUE_3',
        useplc_0: 'VALUE_3',
        xqtystu_0: 31.5,
        ptdlin_0: 'VALUE_3',
        xsoplin_0: 'VALUE_3',
        cpy_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        rcpqtypuu_0: 31.5,
        rcpqtystu_0: 31.5,
        lininvnbr_0: 'VALUE_3',
        linrcpnbr_0: 'VALUE_3',
        invrcpnbr_0: 'VALUE_3',
        lintex_0: 'VALUE_3',
        linamt_0: 31.5,
        scoadd_0: 'VALUE_3',
        itmknd_0: 'VALUE_3',
        ybprliv_0: 'VALUE_3',
        yaddliv_0: 'VALUE_3',
        xexport_0: 'VALUE_3',
        xqty_0: 31.5,
        amttaxrcp_0: 31.5,
        amttaxiss_0: 31.5,
        amttaxoth1_0: 31.5,
        amttaxoth2_0: 31.5,
        xdlvtimfin_0: new Date().toISOString(),
        disbaslin1_0: 'VALUE_3',
        discrgamt5_0: 31.5,
        discrgamt4_0: 31.5,
        discrgamt6_0: 31.5,
        discrgamt7_0: 31.5,
        discrgamt8_0: 31.5,
        soplin_0: 'VALUE_3',
        poplin_0: 'VALUE_3',
        pohtyp_0: 'VALUE_3',
        linrevnum_0: 'VALUE_3',
        orddat_0: new Date().toISOString().split('T')[0],
        qtypuu_0: 31.5,
        pohfcy_0: 'VALUE_3',
        prhfcy_0: 'VALUE_3',
        pthnum_0: 'VALUE_3',
        linsta_0: 1,
        demrcpdat_0: new Date().toISOString().split('T')[0],
        demrcphou_0: 'VALUE_3',
        linvou_0: 'VALUE_3',
        ppdlin_0: 'VALUE_3',
        bpsinv_0: 'VALUE_3',
        cad_0: 'VALUE_3',
        wee_0: 'VALUE_3',
        cmmnum_0: 'VALUE_3',
        linpurtyp_0: 'VALUE_3',
        xtypobj_0: 'VALUE_3',
        bastaxlin1_0: 3,
        wipsta_0: 3,
        amttaxlin3_0: 31.5,
        dedtaxlin1_0: 'VALUE_3',
        dedtaxlin2_0: 'VALUE_3',
        dedtaxlin3_0: 'VALUE_3',
      },
      {
        x4avmotd_0: 'VALUE_4',
        zfabnum_0: 'POR0004',
        zitmreffab_0: 'VALUE_4',
        x4exclrfad_0: 'VALUE_4',
        zdatcof_0: new Date().toISOString().split('T')[0],
        x4hwee_0: 'VALUE_4',
        x4hyea_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cstpur_0: 'VALUE_4',
        lincstpur_0: 'VALUE_4',
        fcscstpur_0: 'VALUE_4',
        fcscpr_0: 'VALUE_4',
        reacstpur_0: 'VALUE_4',
        clcamt7_0: 42.0,
        stcnum_0: 'VALUE_4',
        x4avmotcomd_0: 'VALUE_4',
        x4hextrcpd_0: 'VALUE_4',
        x4hcad_0: 'VALUE_4',
        linamtcpr_0: 'Coût stock 4',
        x4flgblc_0: 'VALUE_4',
        cpramt_0: 42.0,
        xalerte_0: 'VALUE_4',
        cpr_0: 'VALUE_4',
        eccvalmaj_0: 'VALUE_4',
        eccvalmin_0: 'VALUE_4',
        clcamt3_0: 42.0,
        clcamt4_0: 42.0,
        clcamt5_0: 42.0,
        clcamt6_0: 42.0,
        xdlvtimdeb_0: new Date().toISOString(),
        likqtycoe_0: 42.0,
        cmmflg_0: 'VALUE_4',
        zsigfab_0: 'VALUE_4',
        x4pohfab_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        shiqtypuu_0: 42.0,
        x4pohagr_0: 'VALUE_4',
        x4pohbpa_0: 'VALUE_4',
        shiqtystu_0: 42.0,
        cprpri_0: 42.0,
        cmmtax_0: 'VALUE_4',
        discrgamt9_0: 42.0,
        fcyadd_0: 'VALUE_4',
        cprcur_0: 'VALUE_4',
        qtyvou_0: 42.0,
        sddlin_0: 'VALUE_4',
        lintyp_0: 'VALUE_4',
        puu_0: 'VALUE_4',
        yea_0: 'VALUE_4',
        wipnum_0: 'VALUE_4',
        mon_0: 'VALUE_4',
        discrgamt1_0: 42.0,
        pck_0: 'VALUE_4',
        lininvflg_0: 'VALUE_4',
        extrcpdat_0: new Date().toISOString().split('T')[0],
        poqlnk_0: 'VALUE_4',
        amttaxlin2_0: 42.0,
        discrgamt2_0: 42.0,
        discrgamt3_0: 42.0,
        uom_0: 'VALUE_4',
        uompuucoe_0: 'VALUE_4',
        uomflg_0: 'VALUE_4',
        dedtaxrcp_0: 'VALUE_4',
        dedtaxiss_0: 'VALUE_4',
        dedtaxoth1_0: 'VALUE_4',
        dedtaxoth2_0: 'VALUE_4',
        amttaxlin1_0: 42.0,
        rcpcleflg_0: 'VALUE_4',
        xobj1_0: 'VALUE_4',
        xobj2_0: 'VALUE_4',
        ocnlin_0: 'VALUE_4',
        ocnseq_0: 'VALUE_4',
        linocnflg_0: 'VALUE_4',
        vcrtypori_0: 'VALUE_4',
        vcrlinori_0: 'VALUE_4',
        itmrefori_0: 'VALUE_4',
        vcrseqori_0: 'VALUE_4',
        bpsnum_0: 'VALUE_4',
        vcrnumori_0: 'VALUE_4',
        poqseq_0: 'VALUE_4',
        xsoqseq_0: 'VALUE_4',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_4',
        bpainv_0: 'VALUE_4',
        invqtypuu_0: 42.0,
        invqtystu_0: 42.0,
        stu_0: 'VALUE_4',
        soqseq_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        linati_0: 'VALUE_4',
        linatiamt_0: 42.0,
        pqhnum_0: 'VALUE_4',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_4',
        linstofcy_0: 'VALUE_4',
        xversion_0: 'VALUE_4',
        linweu_0: 'VALUE_4',
        qtyweu_0: 42.0,
        itmref_0: 'VALUE_4',
        netcur_0: 'VALUE_4',
        cprcoe_0: 'VALUE_4',
        itmrefbps_0: 'VALUE_4',
        ori_0: 'VALUE_4',
        clcamt2_0: 42.0,
        demenddat_0: new Date().toISOString().split('T')[0],
        demendhou_0: 'VALUE_4',
        linocndat_0: new Date().toISOString().split('T')[0],
        linocnnum_0: 'VALUE_4',
        qtystu_0: 42.0,
        lincleflg_0: 'VALUE_4',
        linprnflg_0: 'VALUE_4',
        qtyuom_0: 42.0,
        sohnum_0: 'VALUE_4',
        clcamt1_0: 42.0,
        ofs_0: 'VALUE_4',
        sdhnum_0: 'VALUE_4',
        pohnum_0: 'VALUE_4',
        xsohnum_0: 'VALUE_4',
        wiptyp_0: 'VALUE_4',
        retrcpdat_0: new Date().toISOString().split('T')[0],
        retqtystu_0: 42.0,
        retqtypuu_0: 42.0,
        fbuflg_0: 'VALUE_4',
        useplc_0: 'VALUE_4',
        xqtystu_0: 42.0,
        ptdlin_0: 'VALUE_4',
        xsoplin_0: 'VALUE_4',
        cpy_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        rcpqtypuu_0: 42.0,
        rcpqtystu_0: 42.0,
        lininvnbr_0: 'VALUE_4',
        linrcpnbr_0: 'VALUE_4',
        invrcpnbr_0: 'VALUE_4',
        lintex_0: 'VALUE_4',
        linamt_0: 42.0,
        scoadd_0: 'VALUE_4',
        itmknd_0: 'VALUE_4',
        ybprliv_0: 'VALUE_4',
        yaddliv_0: 'VALUE_4',
        xexport_0: 'VALUE_4',
        xqty_0: 42.0,
        amttaxrcp_0: 42.0,
        amttaxiss_0: 42.0,
        amttaxoth1_0: 42.0,
        amttaxoth2_0: 42.0,
        xdlvtimfin_0: new Date().toISOString(),
        disbaslin1_0: 'VALUE_4',
        discrgamt5_0: 42.0,
        discrgamt4_0: 42.0,
        discrgamt6_0: 42.0,
        discrgamt7_0: 42.0,
        discrgamt8_0: 42.0,
        soplin_0: 'VALUE_4',
        poplin_0: 'VALUE_4',
        pohtyp_0: 'VALUE_4',
        linrevnum_0: 'VALUE_4',
        orddat_0: new Date().toISOString().split('T')[0],
        qtypuu_0: 42.0,
        pohfcy_0: 'VALUE_4',
        prhfcy_0: 'VALUE_4',
        pthnum_0: 'VALUE_4',
        linsta_0: 1,
        demrcpdat_0: new Date().toISOString().split('T')[0],
        demrcphou_0: 'VALUE_4',
        linvou_0: 'VALUE_4',
        ppdlin_0: 'VALUE_4',
        bpsinv_0: 'VALUE_4',
        cad_0: 'VALUE_4',
        wee_0: 'VALUE_4',
        cmmnum_0: 'VALUE_4',
        linpurtyp_0: 'VALUE_4',
        xtypobj_0: 'VALUE_4',
        bastaxlin1_0: 4,
        wipsta_0: 4,
        amttaxlin3_0: 42.0,
        dedtaxlin1_0: 'VALUE_4',
        dedtaxlin2_0: 'VALUE_4',
        dedtaxlin3_0: 'VALUE_4',
      },
      {
        x4avmotd_0: 'VALUE_5',
        zfabnum_0: 'POR0005',
        zitmreffab_0: 'VALUE_5',
        x4exclrfad_0: 'VALUE_5',
        zdatcof_0: new Date().toISOString().split('T')[0],
        x4hwee_0: 'VALUE_5',
        x4hyea_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cstpur_0: 'VALUE_5',
        lincstpur_0: 'VALUE_5',
        fcscstpur_0: 'VALUE_5',
        fcscpr_0: 'VALUE_5',
        reacstpur_0: 'VALUE_5',
        clcamt7_0: 52.5,
        stcnum_0: 'VALUE_5',
        x4avmotcomd_0: 'VALUE_5',
        x4hextrcpd_0: 'VALUE_5',
        x4hcad_0: 'VALUE_5',
        linamtcpr_0: 'Coût stock 5',
        x4flgblc_0: 'VALUE_5',
        cpramt_0: 52.5,
        xalerte_0: 'VALUE_5',
        cpr_0: 'VALUE_5',
        eccvalmaj_0: 'VALUE_5',
        eccvalmin_0: 'VALUE_5',
        clcamt3_0: 52.5,
        clcamt4_0: 52.5,
        clcamt5_0: 52.5,
        clcamt6_0: 52.5,
        xdlvtimdeb_0: new Date().toISOString(),
        likqtycoe_0: 52.5,
        cmmflg_0: 'VALUE_5',
        zsigfab_0: 'VALUE_5',
        x4pohfab_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        shiqtypuu_0: 52.5,
        x4pohagr_0: 'VALUE_5',
        x4pohbpa_0: 'VALUE_5',
        shiqtystu_0: 52.5,
        cprpri_0: 52.5,
        cmmtax_0: 'VALUE_5',
        discrgamt9_0: 52.5,
        fcyadd_0: 'VALUE_5',
        cprcur_0: 'VALUE_5',
        qtyvou_0: 52.5,
        sddlin_0: 'VALUE_5',
        lintyp_0: 'VALUE_5',
        puu_0: 'VALUE_5',
        yea_0: 'VALUE_5',
        wipnum_0: 'VALUE_5',
        mon_0: 'VALUE_5',
        discrgamt1_0: 52.5,
        pck_0: 'VALUE_5',
        lininvflg_0: 'VALUE_5',
        extrcpdat_0: new Date().toISOString().split('T')[0],
        poqlnk_0: 'VALUE_5',
        amttaxlin2_0: 52.5,
        discrgamt2_0: 52.5,
        discrgamt3_0: 52.5,
        uom_0: 'VALUE_5',
        uompuucoe_0: 'VALUE_5',
        uomflg_0: 'VALUE_5',
        dedtaxrcp_0: 'VALUE_5',
        dedtaxiss_0: 'VALUE_5',
        dedtaxoth1_0: 'VALUE_5',
        dedtaxoth2_0: 'VALUE_5',
        amttaxlin1_0: 52.5,
        rcpcleflg_0: 'VALUE_5',
        xobj1_0: 'VALUE_5',
        xobj2_0: 'VALUE_5',
        ocnlin_0: 'VALUE_5',
        ocnseq_0: 'VALUE_5',
        linocnflg_0: 'VALUE_5',
        vcrtypori_0: 'VALUE_5',
        vcrlinori_0: 'VALUE_5',
        itmrefori_0: 'VALUE_5',
        vcrseqori_0: 'VALUE_5',
        bpsnum_0: 'VALUE_5',
        vcrnumori_0: 'VALUE_5',
        poqseq_0: 'VALUE_5',
        xsoqseq_0: 'VALUE_5',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_5',
        bpainv_0: 'VALUE_5',
        invqtypuu_0: 52.5,
        invqtystu_0: 52.5,
        stu_0: 'VALUE_5',
        soqseq_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        linati_0: 'VALUE_5',
        linatiamt_0: 52.5,
        pqhnum_0: 'VALUE_5',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_5',
        linstofcy_0: 'VALUE_5',
        xversion_0: 'VALUE_5',
        linweu_0: 'VALUE_5',
        qtyweu_0: 52.5,
        itmref_0: 'VALUE_5',
        netcur_0: 'VALUE_5',
        cprcoe_0: 'VALUE_5',
        itmrefbps_0: 'VALUE_5',
        ori_0: 'VALUE_5',
        clcamt2_0: 52.5,
        demenddat_0: new Date().toISOString().split('T')[0],
        demendhou_0: 'VALUE_5',
        linocndat_0: new Date().toISOString().split('T')[0],
        linocnnum_0: 'VALUE_5',
        qtystu_0: 52.5,
        lincleflg_0: 'VALUE_5',
        linprnflg_0: 'VALUE_5',
        qtyuom_0: 52.5,
        sohnum_0: 'VALUE_5',
        clcamt1_0: 52.5,
        ofs_0: 'VALUE_5',
        sdhnum_0: 'VALUE_5',
        pohnum_0: 'VALUE_5',
        xsohnum_0: 'VALUE_5',
        wiptyp_0: 'VALUE_5',
        retrcpdat_0: new Date().toISOString().split('T')[0],
        retqtystu_0: 52.5,
        retqtypuu_0: 52.5,
        fbuflg_0: 'VALUE_5',
        useplc_0: 'VALUE_5',
        xqtystu_0: 52.5,
        ptdlin_0: 'VALUE_5',
        xsoplin_0: 'VALUE_5',
        cpy_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        rcpqtypuu_0: 52.5,
        rcpqtystu_0: 52.5,
        lininvnbr_0: 'VALUE_5',
        linrcpnbr_0: 'VALUE_5',
        invrcpnbr_0: 'VALUE_5',
        lintex_0: 'VALUE_5',
        linamt_0: 52.5,
        scoadd_0: 'VALUE_5',
        itmknd_0: 'VALUE_5',
        ybprliv_0: 'VALUE_5',
        yaddliv_0: 'VALUE_5',
        xexport_0: 'VALUE_5',
        xqty_0: 52.5,
        amttaxrcp_0: 52.5,
        amttaxiss_0: 52.5,
        amttaxoth1_0: 52.5,
        amttaxoth2_0: 52.5,
        xdlvtimfin_0: new Date().toISOString(),
        disbaslin1_0: 'VALUE_5',
        discrgamt5_0: 52.5,
        discrgamt4_0: 52.5,
        discrgamt6_0: 52.5,
        discrgamt7_0: 52.5,
        discrgamt8_0: 52.5,
        soplin_0: 'VALUE_5',
        poplin_0: 'VALUE_5',
        pohtyp_0: 'VALUE_5',
        linrevnum_0: 'VALUE_5',
        orddat_0: new Date().toISOString().split('T')[0],
        qtypuu_0: 52.5,
        pohfcy_0: 'VALUE_5',
        prhfcy_0: 'VALUE_5',
        pthnum_0: 'VALUE_5',
        linsta_0: 1,
        demrcpdat_0: new Date().toISOString().split('T')[0],
        demrcphou_0: 'VALUE_5',
        linvou_0: 'VALUE_5',
        ppdlin_0: 'VALUE_5',
        bpsinv_0: 'VALUE_5',
        cad_0: 'VALUE_5',
        wee_0: 'VALUE_5',
        cmmnum_0: 'VALUE_5',
        linpurtyp_0: 'VALUE_5',
        xtypobj_0: 'VALUE_5',
        bastaxlin1_0: 5,
        wipsta_0: 5,
        amttaxlin3_0: 52.5,
        dedtaxlin1_0: 'VALUE_5',
        dedtaxlin2_0: 'VALUE_5',
        dedtaxlin3_0: 'VALUE_5',
      },
      {
        x4avmotd_0: 'VALUE_6',
        zfabnum_0: 'POR0006',
        zitmreffab_0: 'VALUE_6',
        x4exclrfad_0: 'VALUE_6',
        zdatcof_0: new Date().toISOString().split('T')[0],
        x4hwee_0: 'VALUE_6',
        x4hyea_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cstpur_0: 'VALUE_6',
        lincstpur_0: 'VALUE_6',
        fcscstpur_0: 'VALUE_6',
        fcscpr_0: 'VALUE_6',
        reacstpur_0: 'VALUE_6',
        clcamt7_0: 63.0,
        stcnum_0: 'VALUE_6',
        x4avmotcomd_0: 'VALUE_6',
        x4hextrcpd_0: 'VALUE_6',
        x4hcad_0: 'VALUE_6',
        linamtcpr_0: 'Coût stock 6',
        x4flgblc_0: 'VALUE_6',
        cpramt_0: 63.0,
        xalerte_0: 'VALUE_6',
        cpr_0: 'VALUE_6',
        eccvalmaj_0: 'VALUE_6',
        eccvalmin_0: 'VALUE_6',
        clcamt3_0: 63.0,
        clcamt4_0: 63.0,
        clcamt5_0: 63.0,
        clcamt6_0: 63.0,
        xdlvtimdeb_0: new Date().toISOString(),
        likqtycoe_0: 63.0,
        cmmflg_0: 'VALUE_6',
        zsigfab_0: 'VALUE_6',
        x4pohfab_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        shiqtypuu_0: 63.0,
        x4pohagr_0: 'VALUE_6',
        x4pohbpa_0: 'VALUE_6',
        shiqtystu_0: 63.0,
        cprpri_0: 63.0,
        cmmtax_0: 'VALUE_6',
        discrgamt9_0: 63.0,
        fcyadd_0: 'VALUE_6',
        cprcur_0: 'VALUE_6',
        qtyvou_0: 63.0,
        sddlin_0: 'VALUE_6',
        lintyp_0: 'VALUE_6',
        puu_0: 'VALUE_6',
        yea_0: 'VALUE_6',
        wipnum_0: 'VALUE_6',
        mon_0: 'VALUE_6',
        discrgamt1_0: 63.0,
        pck_0: 'VALUE_6',
        lininvflg_0: 'VALUE_6',
        extrcpdat_0: new Date().toISOString().split('T')[0],
        poqlnk_0: 'VALUE_6',
        amttaxlin2_0: 63.0,
        discrgamt2_0: 63.0,
        discrgamt3_0: 63.0,
        uom_0: 'VALUE_6',
        uompuucoe_0: 'VALUE_6',
        uomflg_0: 'VALUE_6',
        dedtaxrcp_0: 'VALUE_6',
        dedtaxiss_0: 'VALUE_6',
        dedtaxoth1_0: 'VALUE_6',
        dedtaxoth2_0: 'VALUE_6',
        amttaxlin1_0: 63.0,
        rcpcleflg_0: 'VALUE_6',
        xobj1_0: 'VALUE_6',
        xobj2_0: 'VALUE_6',
        ocnlin_0: 'VALUE_6',
        ocnseq_0: 'VALUE_6',
        linocnflg_0: 'VALUE_6',
        vcrtypori_0: 'VALUE_6',
        vcrlinori_0: 'VALUE_6',
        itmrefori_0: 'VALUE_6',
        vcrseqori_0: 'VALUE_6',
        bpsnum_0: 'VALUE_6',
        vcrnumori_0: 'VALUE_6',
        poqseq_0: 'VALUE_6',
        xsoqseq_0: 'VALUE_6',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_6',
        bpainv_0: 'VALUE_6',
        invqtypuu_0: 63.0,
        invqtystu_0: 63.0,
        stu_0: 'VALUE_6',
        soqseq_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        linati_0: 'VALUE_6',
        linatiamt_0: 63.0,
        pqhnum_0: 'VALUE_6',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_6',
        linstofcy_0: 'VALUE_6',
        xversion_0: 'VALUE_6',
        linweu_0: 'VALUE_6',
        qtyweu_0: 63.0,
        itmref_0: 'VALUE_6',
        netcur_0: 'VALUE_6',
        cprcoe_0: 'VALUE_6',
        itmrefbps_0: 'VALUE_6',
        ori_0: 'VALUE_6',
        clcamt2_0: 63.0,
        demenddat_0: new Date().toISOString().split('T')[0],
        demendhou_0: 'VALUE_6',
        linocndat_0: new Date().toISOString().split('T')[0],
        linocnnum_0: 'VALUE_6',
        qtystu_0: 63.0,
        lincleflg_0: 'VALUE_6',
        linprnflg_0: 'VALUE_6',
        qtyuom_0: 63.0,
        sohnum_0: 'VALUE_6',
        clcamt1_0: 63.0,
        ofs_0: 'VALUE_6',
        sdhnum_0: 'VALUE_6',
        pohnum_0: 'VALUE_6',
        xsohnum_0: 'VALUE_6',
        wiptyp_0: 'VALUE_6',
        retrcpdat_0: new Date().toISOString().split('T')[0],
        retqtystu_0: 63.0,
        retqtypuu_0: 63.0,
        fbuflg_0: 'VALUE_6',
        useplc_0: 'VALUE_6',
        xqtystu_0: 63.0,
        ptdlin_0: 'VALUE_6',
        xsoplin_0: 'VALUE_6',
        cpy_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        rcpqtypuu_0: 63.0,
        rcpqtystu_0: 63.0,
        lininvnbr_0: 'VALUE_6',
        linrcpnbr_0: 'VALUE_6',
        invrcpnbr_0: 'VALUE_6',
        lintex_0: 'VALUE_6',
        linamt_0: 63.0,
        scoadd_0: 'VALUE_6',
        itmknd_0: 'VALUE_6',
        ybprliv_0: 'VALUE_6',
        yaddliv_0: 'VALUE_6',
        xexport_0: 'VALUE_6',
        xqty_0: 63.0,
        amttaxrcp_0: 63.0,
        amttaxiss_0: 63.0,
        amttaxoth1_0: 63.0,
        amttaxoth2_0: 63.0,
        xdlvtimfin_0: new Date().toISOString(),
        disbaslin1_0: 'VALUE_6',
        discrgamt5_0: 63.0,
        discrgamt4_0: 63.0,
        discrgamt6_0: 63.0,
        discrgamt7_0: 63.0,
        discrgamt8_0: 63.0,
        soplin_0: 'VALUE_6',
        poplin_0: 'VALUE_6',
        pohtyp_0: 'VALUE_6',
        linrevnum_0: 'VALUE_6',
        orddat_0: new Date().toISOString().split('T')[0],
        qtypuu_0: 63.0,
        pohfcy_0: 'VALUE_6',
        prhfcy_0: 'VALUE_6',
        pthnum_0: 'VALUE_6',
        linsta_0: 1,
        demrcpdat_0: new Date().toISOString().split('T')[0],
        demrcphou_0: 'VALUE_6',
        linvou_0: 'VALUE_6',
        ppdlin_0: 'VALUE_6',
        bpsinv_0: 'VALUE_6',
        cad_0: 'VALUE_6',
        wee_0: 'VALUE_6',
        cmmnum_0: 'VALUE_6',
        linpurtyp_0: 'VALUE_6',
        xtypobj_0: 'VALUE_6',
        bastaxlin1_0: 6,
        wipsta_0: 6,
        amttaxlin3_0: 63.0,
        dedtaxlin1_0: 'VALUE_6',
        dedtaxlin2_0: 'VALUE_6',
        dedtaxlin3_0: 'VALUE_6',
      },
      {
        x4avmotd_0: 'VALUE_7',
        zfabnum_0: 'POR0007',
        zitmreffab_0: 'VALUE_7',
        x4exclrfad_0: 'VALUE_7',
        zdatcof_0: new Date().toISOString().split('T')[0],
        x4hwee_0: 'VALUE_7',
        x4hyea_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cstpur_0: 'VALUE_7',
        lincstpur_0: 'VALUE_7',
        fcscstpur_0: 'VALUE_7',
        fcscpr_0: 'VALUE_7',
        reacstpur_0: 'VALUE_7',
        clcamt7_0: 73.5,
        stcnum_0: 'VALUE_7',
        x4avmotcomd_0: 'VALUE_7',
        x4hextrcpd_0: 'VALUE_7',
        x4hcad_0: 'VALUE_7',
        linamtcpr_0: 'Coût stock 7',
        x4flgblc_0: 'VALUE_7',
        cpramt_0: 73.5,
        xalerte_0: 'VALUE_7',
        cpr_0: 'VALUE_7',
        eccvalmaj_0: 'VALUE_7',
        eccvalmin_0: 'VALUE_7',
        clcamt3_0: 73.5,
        clcamt4_0: 73.5,
        clcamt5_0: 73.5,
        clcamt6_0: 73.5,
        xdlvtimdeb_0: new Date().toISOString(),
        likqtycoe_0: 73.5,
        cmmflg_0: 'VALUE_7',
        zsigfab_0: 'VALUE_7',
        x4pohfab_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        shiqtypuu_0: 73.5,
        x4pohagr_0: 'VALUE_7',
        x4pohbpa_0: 'VALUE_7',
        shiqtystu_0: 73.5,
        cprpri_0: 73.5,
        cmmtax_0: 'VALUE_7',
        discrgamt9_0: 73.5,
        fcyadd_0: 'VALUE_7',
        cprcur_0: 'VALUE_7',
        qtyvou_0: 73.5,
        sddlin_0: 'VALUE_7',
        lintyp_0: 'VALUE_7',
        puu_0: 'VALUE_7',
        yea_0: 'VALUE_7',
        wipnum_0: 'VALUE_7',
        mon_0: 'VALUE_7',
        discrgamt1_0: 73.5,
        pck_0: 'VALUE_7',
        lininvflg_0: 'VALUE_7',
        extrcpdat_0: new Date().toISOString().split('T')[0],
        poqlnk_0: 'VALUE_7',
        amttaxlin2_0: 73.5,
        discrgamt2_0: 73.5,
        discrgamt3_0: 73.5,
        uom_0: 'VALUE_7',
        uompuucoe_0: 'VALUE_7',
        uomflg_0: 'VALUE_7',
        dedtaxrcp_0: 'VALUE_7',
        dedtaxiss_0: 'VALUE_7',
        dedtaxoth1_0: 'VALUE_7',
        dedtaxoth2_0: 'VALUE_7',
        amttaxlin1_0: 73.5,
        rcpcleflg_0: 'VALUE_7',
        xobj1_0: 'VALUE_7',
        xobj2_0: 'VALUE_7',
        ocnlin_0: 'VALUE_7',
        ocnseq_0: 'VALUE_7',
        linocnflg_0: 'VALUE_7',
        vcrtypori_0: 'VALUE_7',
        vcrlinori_0: 'VALUE_7',
        itmrefori_0: 'VALUE_7',
        vcrseqori_0: 'VALUE_7',
        bpsnum_0: 'VALUE_7',
        vcrnumori_0: 'VALUE_7',
        poqseq_0: 'VALUE_7',
        xsoqseq_0: 'VALUE_7',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_7',
        bpainv_0: 'VALUE_7',
        invqtypuu_0: 73.5,
        invqtystu_0: 73.5,
        stu_0: 'VALUE_7',
        soqseq_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        linati_0: 'VALUE_7',
        linatiamt_0: 73.5,
        pqhnum_0: 'VALUE_7',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_7',
        linstofcy_0: 'VALUE_7',
        xversion_0: 'VALUE_7',
        linweu_0: 'VALUE_7',
        qtyweu_0: 73.5,
        itmref_0: 'VALUE_7',
        netcur_0: 'VALUE_7',
        cprcoe_0: 'VALUE_7',
        itmrefbps_0: 'VALUE_7',
        ori_0: 'VALUE_7',
        clcamt2_0: 73.5,
        demenddat_0: new Date().toISOString().split('T')[0],
        demendhou_0: 'VALUE_7',
        linocndat_0: new Date().toISOString().split('T')[0],
        linocnnum_0: 'VALUE_7',
        qtystu_0: 73.5,
        lincleflg_0: 'VALUE_7',
        linprnflg_0: 'VALUE_7',
        qtyuom_0: 73.5,
        sohnum_0: 'VALUE_7',
        clcamt1_0: 73.5,
        ofs_0: 'VALUE_7',
        sdhnum_0: 'VALUE_7',
        pohnum_0: 'VALUE_7',
        xsohnum_0: 'VALUE_7',
        wiptyp_0: 'VALUE_7',
        retrcpdat_0: new Date().toISOString().split('T')[0],
        retqtystu_0: 73.5,
        retqtypuu_0: 73.5,
        fbuflg_0: 'VALUE_7',
        useplc_0: 'VALUE_7',
        xqtystu_0: 73.5,
        ptdlin_0: 'VALUE_7',
        xsoplin_0: 'VALUE_7',
        cpy_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        rcpqtypuu_0: 73.5,
        rcpqtystu_0: 73.5,
        lininvnbr_0: 'VALUE_7',
        linrcpnbr_0: 'VALUE_7',
        invrcpnbr_0: 'VALUE_7',
        lintex_0: 'VALUE_7',
        linamt_0: 73.5,
        scoadd_0: 'VALUE_7',
        itmknd_0: 'VALUE_7',
        ybprliv_0: 'VALUE_7',
        yaddliv_0: 'VALUE_7',
        xexport_0: 'VALUE_7',
        xqty_0: 73.5,
        amttaxrcp_0: 73.5,
        amttaxiss_0: 73.5,
        amttaxoth1_0: 73.5,
        amttaxoth2_0: 73.5,
        xdlvtimfin_0: new Date().toISOString(),
        disbaslin1_0: 'VALUE_7',
        discrgamt5_0: 73.5,
        discrgamt4_0: 73.5,
        discrgamt6_0: 73.5,
        discrgamt7_0: 73.5,
        discrgamt8_0: 73.5,
        soplin_0: 'VALUE_7',
        poplin_0: 'VALUE_7',
        pohtyp_0: 'VALUE_7',
        linrevnum_0: 'VALUE_7',
        orddat_0: new Date().toISOString().split('T')[0],
        qtypuu_0: 73.5,
        pohfcy_0: 'VALUE_7',
        prhfcy_0: 'VALUE_7',
        pthnum_0: 'VALUE_7',
        linsta_0: 1,
        demrcpdat_0: new Date().toISOString().split('T')[0],
        demrcphou_0: 'VALUE_7',
        linvou_0: 'VALUE_7',
        ppdlin_0: 'VALUE_7',
        bpsinv_0: 'VALUE_7',
        cad_0: 'VALUE_7',
        wee_0: 'VALUE_7',
        cmmnum_0: 'VALUE_7',
        linpurtyp_0: 'VALUE_7',
        xtypobj_0: 'VALUE_7',
        bastaxlin1_0: 7,
        wipsta_0: 7,
        amttaxlin3_0: 73.5,
        dedtaxlin1_0: 'VALUE_7',
        dedtaxlin2_0: 'VALUE_7',
        dedtaxlin3_0: 'VALUE_7',
      },
      {
        x4avmotd_0: 'VALUE_8',
        zfabnum_0: 'POR0008',
        zitmreffab_0: 'VALUE_8',
        x4exclrfad_0: 'VALUE_8',
        zdatcof_0: new Date().toISOString().split('T')[0],
        x4hwee_0: 'VALUE_8',
        x4hyea_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cstpur_0: 'VALUE_8',
        lincstpur_0: 'VALUE_8',
        fcscstpur_0: 'VALUE_8',
        fcscpr_0: 'VALUE_8',
        reacstpur_0: 'VALUE_8',
        clcamt7_0: 84.0,
        stcnum_0: 'VALUE_8',
        x4avmotcomd_0: 'VALUE_8',
        x4hextrcpd_0: 'VALUE_8',
        x4hcad_0: 'VALUE_8',
        linamtcpr_0: 'Coût stock 8',
        x4flgblc_0: 'VALUE_8',
        cpramt_0: 84.0,
        xalerte_0: 'VALUE_8',
        cpr_0: 'VALUE_8',
        eccvalmaj_0: 'VALUE_8',
        eccvalmin_0: 'VALUE_8',
        clcamt3_0: 84.0,
        clcamt4_0: 84.0,
        clcamt5_0: 84.0,
        clcamt6_0: 84.0,
        xdlvtimdeb_0: new Date().toISOString(),
        likqtycoe_0: 84.0,
        cmmflg_0: 'VALUE_8',
        zsigfab_0: 'VALUE_8',
        x4pohfab_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        shiqtypuu_0: 84.0,
        x4pohagr_0: 'VALUE_8',
        x4pohbpa_0: 'VALUE_8',
        shiqtystu_0: 84.0,
        cprpri_0: 84.0,
        cmmtax_0: 'VALUE_8',
        discrgamt9_0: 84.0,
        fcyadd_0: 'VALUE_8',
        cprcur_0: 'VALUE_8',
        qtyvou_0: 84.0,
        sddlin_0: 'VALUE_8',
        lintyp_0: 'VALUE_8',
        puu_0: 'VALUE_8',
        yea_0: 'VALUE_8',
        wipnum_0: 'VALUE_8',
        mon_0: 'VALUE_8',
        discrgamt1_0: 84.0,
        pck_0: 'VALUE_8',
        lininvflg_0: 'VALUE_8',
        extrcpdat_0: new Date().toISOString().split('T')[0],
        poqlnk_0: 'VALUE_8',
        amttaxlin2_0: 84.0,
        discrgamt2_0: 84.0,
        discrgamt3_0: 84.0,
        uom_0: 'VALUE_8',
        uompuucoe_0: 'VALUE_8',
        uomflg_0: 'VALUE_8',
        dedtaxrcp_0: 'VALUE_8',
        dedtaxiss_0: 'VALUE_8',
        dedtaxoth1_0: 'VALUE_8',
        dedtaxoth2_0: 'VALUE_8',
        amttaxlin1_0: 84.0,
        rcpcleflg_0: 'VALUE_8',
        xobj1_0: 'VALUE_8',
        xobj2_0: 'VALUE_8',
        ocnlin_0: 'VALUE_8',
        ocnseq_0: 'VALUE_8',
        linocnflg_0: 'VALUE_8',
        vcrtypori_0: 'VALUE_8',
        vcrlinori_0: 'VALUE_8',
        itmrefori_0: 'VALUE_8',
        vcrseqori_0: 'VALUE_8',
        bpsnum_0: 'VALUE_8',
        vcrnumori_0: 'VALUE_8',
        poqseq_0: 'VALUE_8',
        xsoqseq_0: 'VALUE_8',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_8',
        bpainv_0: 'VALUE_8',
        invqtypuu_0: 84.0,
        invqtystu_0: 84.0,
        stu_0: 'VALUE_8',
        soqseq_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        linati_0: 'VALUE_8',
        linatiamt_0: 84.0,
        pqhnum_0: 'VALUE_8',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_8',
        linstofcy_0: 'VALUE_8',
        xversion_0: 'VALUE_8',
        linweu_0: 'VALUE_8',
        qtyweu_0: 84.0,
        itmref_0: 'VALUE_8',
        netcur_0: 'VALUE_8',
        cprcoe_0: 'VALUE_8',
        itmrefbps_0: 'VALUE_8',
        ori_0: 'VALUE_8',
        clcamt2_0: 84.0,
        demenddat_0: new Date().toISOString().split('T')[0],
        demendhou_0: 'VALUE_8',
        linocndat_0: new Date().toISOString().split('T')[0],
        linocnnum_0: 'VALUE_8',
        qtystu_0: 84.0,
        lincleflg_0: 'VALUE_8',
        linprnflg_0: 'VALUE_8',
        qtyuom_0: 84.0,
        sohnum_0: 'VALUE_8',
        clcamt1_0: 84.0,
        ofs_0: 'VALUE_8',
        sdhnum_0: 'VALUE_8',
        pohnum_0: 'VALUE_8',
        xsohnum_0: 'VALUE_8',
        wiptyp_0: 'VALUE_8',
        retrcpdat_0: new Date().toISOString().split('T')[0],
        retqtystu_0: 84.0,
        retqtypuu_0: 84.0,
        fbuflg_0: 'VALUE_8',
        useplc_0: 'VALUE_8',
        xqtystu_0: 84.0,
        ptdlin_0: 'VALUE_8',
        xsoplin_0: 'VALUE_8',
        cpy_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        rcpqtypuu_0: 84.0,
        rcpqtystu_0: 84.0,
        lininvnbr_0: 'VALUE_8',
        linrcpnbr_0: 'VALUE_8',
        invrcpnbr_0: 'VALUE_8',
        lintex_0: 'VALUE_8',
        linamt_0: 84.0,
        scoadd_0: 'VALUE_8',
        itmknd_0: 'VALUE_8',
        ybprliv_0: 'VALUE_8',
        yaddliv_0: 'VALUE_8',
        xexport_0: 'VALUE_8',
        xqty_0: 84.0,
        amttaxrcp_0: 84.0,
        amttaxiss_0: 84.0,
        amttaxoth1_0: 84.0,
        amttaxoth2_0: 84.0,
        xdlvtimfin_0: new Date().toISOString(),
        disbaslin1_0: 'VALUE_8',
        discrgamt5_0: 84.0,
        discrgamt4_0: 84.0,
        discrgamt6_0: 84.0,
        discrgamt7_0: 84.0,
        discrgamt8_0: 84.0,
        soplin_0: 'VALUE_8',
        poplin_0: 'VALUE_8',
        pohtyp_0: 'VALUE_8',
        linrevnum_0: 'VALUE_8',
        orddat_0: new Date().toISOString().split('T')[0],
        qtypuu_0: 84.0,
        pohfcy_0: 'VALUE_8',
        prhfcy_0: 'VALUE_8',
        pthnum_0: 'VALUE_8',
        linsta_0: 1,
        demrcpdat_0: new Date().toISOString().split('T')[0],
        demrcphou_0: 'VALUE_8',
        linvou_0: 'VALUE_8',
        ppdlin_0: 'VALUE_8',
        bpsinv_0: 'VALUE_8',
        cad_0: 'VALUE_8',
        wee_0: 'VALUE_8',
        cmmnum_0: 'VALUE_8',
        linpurtyp_0: 'VALUE_8',
        xtypobj_0: 'VALUE_8',
        bastaxlin1_0: 8,
        wipsta_0: 8,
        amttaxlin3_0: 84.0,
        dedtaxlin1_0: 'VALUE_8',
        dedtaxlin2_0: 'VALUE_8',
        dedtaxlin3_0: 'VALUE_8',
      },
      {
        x4avmotd_0: 'VALUE_9',
        zfabnum_0: 'POR0009',
        zitmreffab_0: 'VALUE_9',
        x4exclrfad_0: 'VALUE_9',
        zdatcof_0: new Date().toISOString().split('T')[0],
        x4hwee_0: 'VALUE_9',
        x4hyea_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cstpur_0: 'VALUE_9',
        lincstpur_0: 'VALUE_9',
        fcscstpur_0: 'VALUE_9',
        fcscpr_0: 'VALUE_9',
        reacstpur_0: 'VALUE_9',
        clcamt7_0: 94.5,
        stcnum_0: 'VALUE_9',
        x4avmotcomd_0: 'VALUE_9',
        x4hextrcpd_0: 'VALUE_9',
        x4hcad_0: 'VALUE_9',
        linamtcpr_0: 'Coût stock 9',
        x4flgblc_0: 'VALUE_9',
        cpramt_0: 94.5,
        xalerte_0: 'VALUE_9',
        cpr_0: 'VALUE_9',
        eccvalmaj_0: 'VALUE_9',
        eccvalmin_0: 'VALUE_9',
        clcamt3_0: 94.5,
        clcamt4_0: 94.5,
        clcamt5_0: 94.5,
        clcamt6_0: 94.5,
        xdlvtimdeb_0: new Date().toISOString(),
        likqtycoe_0: 94.5,
        cmmflg_0: 'VALUE_9',
        zsigfab_0: 'VALUE_9',
        x4pohfab_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        shiqtypuu_0: 94.5,
        x4pohagr_0: 'VALUE_9',
        x4pohbpa_0: 'VALUE_9',
        shiqtystu_0: 94.5,
        cprpri_0: 94.5,
        cmmtax_0: 'VALUE_9',
        discrgamt9_0: 94.5,
        fcyadd_0: 'VALUE_9',
        cprcur_0: 'VALUE_9',
        qtyvou_0: 94.5,
        sddlin_0: 'VALUE_9',
        lintyp_0: 'VALUE_9',
        puu_0: 'VALUE_9',
        yea_0: 'VALUE_9',
        wipnum_0: 'VALUE_9',
        mon_0: 'VALUE_9',
        discrgamt1_0: 94.5,
        pck_0: 'VALUE_9',
        lininvflg_0: 'VALUE_9',
        extrcpdat_0: new Date().toISOString().split('T')[0],
        poqlnk_0: 'VALUE_9',
        amttaxlin2_0: 94.5,
        discrgamt2_0: 94.5,
        discrgamt3_0: 94.5,
        uom_0: 'VALUE_9',
        uompuucoe_0: 'VALUE_9',
        uomflg_0: 'VALUE_9',
        dedtaxrcp_0: 'VALUE_9',
        dedtaxiss_0: 'VALUE_9',
        dedtaxoth1_0: 'VALUE_9',
        dedtaxoth2_0: 'VALUE_9',
        amttaxlin1_0: 94.5,
        rcpcleflg_0: 'VALUE_9',
        xobj1_0: 'VALUE_9',
        xobj2_0: 'VALUE_9',
        ocnlin_0: 'VALUE_9',
        ocnseq_0: 'VALUE_9',
        linocnflg_0: 'VALUE_9',
        vcrtypori_0: 'VALUE_9',
        vcrlinori_0: 'VALUE_9',
        itmrefori_0: 'VALUE_9',
        vcrseqori_0: 'VALUE_9',
        bpsnum_0: 'VALUE_9',
        vcrnumori_0: 'VALUE_9',
        poqseq_0: 'VALUE_9',
        xsoqseq_0: 'VALUE_9',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_9',
        bpainv_0: 'VALUE_9',
        invqtypuu_0: 94.5,
        invqtystu_0: 94.5,
        stu_0: 'VALUE_9',
        soqseq_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        linati_0: 'VALUE_9',
        linatiamt_0: 94.5,
        pqhnum_0: 'VALUE_9',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_9',
        linstofcy_0: 'VALUE_9',
        xversion_0: 'VALUE_9',
        linweu_0: 'VALUE_9',
        qtyweu_0: 94.5,
        itmref_0: 'VALUE_9',
        netcur_0: 'VALUE_9',
        cprcoe_0: 'VALUE_9',
        itmrefbps_0: 'VALUE_9',
        ori_0: 'VALUE_9',
        clcamt2_0: 94.5,
        demenddat_0: new Date().toISOString().split('T')[0],
        demendhou_0: 'VALUE_9',
        linocndat_0: new Date().toISOString().split('T')[0],
        linocnnum_0: 'VALUE_9',
        qtystu_0: 94.5,
        lincleflg_0: 'VALUE_9',
        linprnflg_0: 'VALUE_9',
        qtyuom_0: 94.5,
        sohnum_0: 'VALUE_9',
        clcamt1_0: 94.5,
        ofs_0: 'VALUE_9',
        sdhnum_0: 'VALUE_9',
        pohnum_0: 'VALUE_9',
        xsohnum_0: 'VALUE_9',
        wiptyp_0: 'VALUE_9',
        retrcpdat_0: new Date().toISOString().split('T')[0],
        retqtystu_0: 94.5,
        retqtypuu_0: 94.5,
        fbuflg_0: 'VALUE_9',
        useplc_0: 'VALUE_9',
        xqtystu_0: 94.5,
        ptdlin_0: 'VALUE_9',
        xsoplin_0: 'VALUE_9',
        cpy_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        rcpqtypuu_0: 94.5,
        rcpqtystu_0: 94.5,
        lininvnbr_0: 'VALUE_9',
        linrcpnbr_0: 'VALUE_9',
        invrcpnbr_0: 'VALUE_9',
        lintex_0: 'VALUE_9',
        linamt_0: 94.5,
        scoadd_0: 'VALUE_9',
        itmknd_0: 'VALUE_9',
        ybprliv_0: 'VALUE_9',
        yaddliv_0: 'VALUE_9',
        xexport_0: 'VALUE_9',
        xqty_0: 94.5,
        amttaxrcp_0: 94.5,
        amttaxiss_0: 94.5,
        amttaxoth1_0: 94.5,
        amttaxoth2_0: 94.5,
        xdlvtimfin_0: new Date().toISOString(),
        disbaslin1_0: 'VALUE_9',
        discrgamt5_0: 94.5,
        discrgamt4_0: 94.5,
        discrgamt6_0: 94.5,
        discrgamt7_0: 94.5,
        discrgamt8_0: 94.5,
        soplin_0: 'VALUE_9',
        poplin_0: 'VALUE_9',
        pohtyp_0: 'VALUE_9',
        linrevnum_0: 'VALUE_9',
        orddat_0: new Date().toISOString().split('T')[0],
        qtypuu_0: 94.5,
        pohfcy_0: 'VALUE_9',
        prhfcy_0: 'VALUE_9',
        pthnum_0: 'VALUE_9',
        linsta_0: 1,
        demrcpdat_0: new Date().toISOString().split('T')[0],
        demrcphou_0: 'VALUE_9',
        linvou_0: 'VALUE_9',
        ppdlin_0: 'VALUE_9',
        bpsinv_0: 'VALUE_9',
        cad_0: 'VALUE_9',
        wee_0: 'VALUE_9',
        cmmnum_0: 'VALUE_9',
        linpurtyp_0: 'VALUE_9',
        xtypobj_0: 'VALUE_9',
        bastaxlin1_0: 9,
        wipsta_0: 9,
        amttaxlin3_0: 94.5,
        dedtaxlin1_0: 'VALUE_9',
        dedtaxlin2_0: 'VALUE_9',
        dedtaxlin3_0: 'VALUE_9',
      },
      {
        x4avmotd_0: 'VALUE_10',
        zfabnum_0: 'POR0010',
        zitmreffab_0: 'VALUE_10',
        x4exclrfad_0: 'VALUE_10',
        zdatcof_0: new Date().toISOString().split('T')[0],
        x4hwee_0: 'VALUE_10',
        x4hyea_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        cstpur_0: 'VALUE_10',
        lincstpur_0: 'VALUE_10',
        fcscstpur_0: 'VALUE_10',
        fcscpr_0: 'VALUE_10',
        reacstpur_0: 'VALUE_10',
        clcamt7_0: 105.0,
        stcnum_0: 'VALUE_10',
        x4avmotcomd_0: 'VALUE_10',
        x4hextrcpd_0: 'VALUE_10',
        x4hcad_0: 'VALUE_10',
        linamtcpr_0: 'Coût stock 10',
        x4flgblc_0: 'VALUE_10',
        cpramt_0: 105.0,
        xalerte_0: 'VALUE_10',
        cpr_0: 'VALUE_10',
        eccvalmaj_0: 'VALUE_10',
        eccvalmin_0: 'VALUE_10',
        clcamt3_0: 105.0,
        clcamt4_0: 105.0,
        clcamt5_0: 105.0,
        clcamt6_0: 105.0,
        xdlvtimdeb_0: new Date().toISOString(),
        likqtycoe_0: 105.0,
        cmmflg_0: 'VALUE_10',
        zsigfab_0: 'VALUE_10',
        x4pohfab_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        shiqtypuu_0: 105.0,
        x4pohagr_0: 'VALUE_10',
        x4pohbpa_0: 'VALUE_10',
        shiqtystu_0: 105.0,
        cprpri_0: 105.0,
        cmmtax_0: 'VALUE_10',
        discrgamt9_0: 105.0,
        fcyadd_0: 'VALUE_10',
        cprcur_0: 'VALUE_10',
        qtyvou_0: 105.0,
        sddlin_0: 'VALUE_10',
        lintyp_0: 'VALUE_10',
        puu_0: 'VALUE_10',
        yea_0: 'VALUE_10',
        wipnum_0: 'VALUE_10',
        mon_0: 'VALUE_10',
        discrgamt1_0: 105.0,
        pck_0: 'VALUE_10',
        lininvflg_0: 'VALUE_10',
        extrcpdat_0: new Date().toISOString().split('T')[0],
        poqlnk_0: 'VALUE_10',
        amttaxlin2_0: 105.0,
        discrgamt2_0: 105.0,
        discrgamt3_0: 105.0,
        uom_0: 'VALUE_10',
        uompuucoe_0: 'VALUE_10',
        uomflg_0: 'VALUE_10',
        dedtaxrcp_0: 'VALUE_10',
        dedtaxiss_0: 'VALUE_10',
        dedtaxoth1_0: 'VALUE_10',
        dedtaxoth2_0: 'VALUE_10',
        amttaxlin1_0: 105.0,
        rcpcleflg_0: 'VALUE_10',
        xobj1_0: 'VALUE_10',
        xobj2_0: 'VALUE_10',
        ocnlin_0: 'VALUE_10',
        ocnseq_0: 'VALUE_10',
        linocnflg_0: 'VALUE_10',
        vcrtypori_0: 'VALUE_10',
        vcrlinori_0: 'VALUE_10',
        itmrefori_0: 'VALUE_10',
        vcrseqori_0: 'VALUE_10',
        bpsnum_0: 'VALUE_10',
        vcrnumori_0: 'VALUE_10',
        poqseq_0: 'VALUE_10',
        xsoqseq_0: 'VALUE_10',
        lasinvdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_10',
        bpainv_0: 'VALUE_10',
        invqtypuu_0: 105.0,
        invqtystu_0: 105.0,
        stu_0: 'VALUE_10',
        soqseq_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        linati_0: 'VALUE_10',
        linatiamt_0: 105.0,
        pqhnum_0: 'VALUE_10',
        lasrcpdat_0: new Date().toISOString().split('T')[0],
        creusr_0: 'VALUE_10',
        linstofcy_0: 'VALUE_10',
        xversion_0: 'VALUE_10',
        linweu_0: 'VALUE_10',
        qtyweu_0: 105.0,
        itmref_0: 'VALUE_10',
        netcur_0: 'VALUE_10',
        cprcoe_0: 'VALUE_10',
        itmrefbps_0: 'VALUE_10',
        ori_0: 'VALUE_10',
        clcamt2_0: 105.0,
        demenddat_0: new Date().toISOString().split('T')[0],
        demendhou_0: 'VALUE_10',
        linocndat_0: new Date().toISOString().split('T')[0],
        linocnnum_0: 'VALUE_10',
        qtystu_0: 105.0,
        lincleflg_0: 'VALUE_10',
        linprnflg_0: 'VALUE_10',
        qtyuom_0: 105.0,
        sohnum_0: 'VALUE_10',
        clcamt1_0: 105.0,
        ofs_0: 'VALUE_10',
        sdhnum_0: 'VALUE_10',
        pohnum_0: 'VALUE_10',
        xsohnum_0: 'VALUE_10',
        wiptyp_0: 'VALUE_10',
        retrcpdat_0: new Date().toISOString().split('T')[0],
        retqtystu_0: 105.0,
        retqtypuu_0: 105.0,
        fbuflg_0: 'VALUE_10',
        useplc_0: 'VALUE_10',
        xqtystu_0: 105.0,
        ptdlin_0: 'VALUE_10',
        xsoplin_0: 'VALUE_10',
        cpy_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        rcpqtypuu_0: 105.0,
        rcpqtystu_0: 105.0,
        lininvnbr_0: 'VALUE_10',
        linrcpnbr_0: 'VALUE_10',
        invrcpnbr_0: 'VALUE_10',
        lintex_0: 'VALUE_10',
        linamt_0: 105.0,
        scoadd_0: 'VALUE_10',
        itmknd_0: 'VALUE_10',
        ybprliv_0: 'VALUE_10',
        yaddliv_0: 'VALUE_10',
        xexport_0: 'VALUE_10',
        xqty_0: 105.0,
        amttaxrcp_0: 105.0,
        amttaxiss_0: 105.0,
        amttaxoth1_0: 105.0,
        amttaxoth2_0: 105.0,
        xdlvtimfin_0: new Date().toISOString(),
        disbaslin1_0: 'VALUE_10',
        discrgamt5_0: 105.0,
        discrgamt4_0: 105.0,
        discrgamt6_0: 105.0,
        discrgamt7_0: 105.0,
        discrgamt8_0: 105.0,
        soplin_0: 'VALUE_10',
        poplin_0: 'VALUE_10',
        pohtyp_0: 'VALUE_10',
        linrevnum_0: 'VALUE_10',
        orddat_0: new Date().toISOString().split('T')[0],
        qtypuu_0: 105.0,
        pohfcy_0: 'VALUE_10',
        prhfcy_0: 'VALUE_10',
        pthnum_0: 'VALUE_10',
        linsta_0: 1,
        demrcpdat_0: new Date().toISOString().split('T')[0],
        demrcphou_0: 'VALUE_10',
        linvou_0: 'VALUE_10',
        ppdlin_0: 'VALUE_10',
        bpsinv_0: 'VALUE_10',
        cad_0: 'VALUE_10',
        wee_0: 'VALUE_10',
        cmmnum_0: 'VALUE_10',
        linpurtyp_0: 'VALUE_10',
        xtypobj_0: 'VALUE_10',
        bastaxlin1_0: 10,
        wipsta_0: 10,
        amttaxlin3_0: 105.0,
        dedtaxlin1_0: 'VALUE_10',
        dedtaxlin2_0: 'VALUE_10',
        dedtaxlin3_0: 'VALUE_10',
      },
    ]

    await Database.table('porderq').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans porderq`)
  }
}
