import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour PORDERP
    const data = [
      {
        itmdes1_0: 'Désignation article 1',
        discrgval4_0: 'VALUE_1',
        taxiss_0: 'VALUE_1',
        taxoth1_0: 'VALUE_1',
        taxoth2_0: 'VALUE_1',
        poplin_0: 'VALUE_1',
        tsicod_0: 'VALUE_1',
        pohtyp_0: 'VALUE_1',
        linrevnum_0: 'POR0001',
        gropri_0: 10.5,
        priren_0: 10.5,
        prhfcy_0: 'VALUE_1',
        vat_0: 'VALUE_1',
        itmref_0: 'VALUE_1',
        popseq_0: 'VALUE_1',
        netpri_0: 10.5,
        pohnum_0: 'VALUE_1',
        cpy_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        linbuy_0: 'VALUE_1',
        strdat_0: new Date().toISOString().split('T')[0],
        popcreflg_0: 'VALUE_1',
        itmdes_0: 'VALUE_1',
        eecincrat_0: 'VALUE_1',
        popdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        quaflg_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        mattol_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        fcyadd_0: 'VALUE_1',
        pjt_0: 'VALUE_1',
        discrgren7_0: 'VALUE_1',
        discrgren8_0: 'VALUE_1',
        discrgren9_0: 'VALUE_1',
        discrgval8_0: 'VALUE_1',
        discrgval9_0: 'VALUE_1',
        discrgren1_0: 'VALUE_1',
        discrgren2_0: 'VALUE_1',
        discrgren3_0: 'VALUE_1',
        discrgren4_0: 'VALUE_1',
        discrgren5_0: 'VALUE_1',
        discrgren6_0: 'VALUE_1',
        oricry_0: 'VALUE_1',
        discrgval5_0: 'VALUE_1',
        discrgval6_0: 'VALUE_1',
        discrgval7_0: 'VALUE_1',
        discrgval1_0: 'VALUE_1',
        discrgval2_0: 'VALUE_1',
        discrgval3_0: 'VALUE_1',
        taxrcp_0: 'VALUE_1',
      },
      {
        itmdes1_0: 'Désignation article 2',
        discrgval4_0: 'VALUE_2',
        taxiss_0: 'VALUE_2',
        taxoth1_0: 'VALUE_2',
        taxoth2_0: 'VALUE_2',
        poplin_0: 'VALUE_2',
        tsicod_0: 'VALUE_2',
        pohtyp_0: 'VALUE_2',
        linrevnum_0: 'POR0002',
        gropri_0: 21.0,
        priren_0: 21.0,
        prhfcy_0: 'VALUE_2',
        vat_0: 'VALUE_2',
        itmref_0: 'VALUE_2',
        popseq_0: 'VALUE_2',
        netpri_0: 21.0,
        pohnum_0: 'VALUE_2',
        cpy_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        linbuy_0: 'VALUE_2',
        strdat_0: new Date().toISOString().split('T')[0],
        popcreflg_0: 'VALUE_2',
        itmdes_0: 'VALUE_2',
        eecincrat_0: 'VALUE_2',
        popdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        quaflg_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        mattol_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        fcyadd_0: 'VALUE_2',
        pjt_0: 'VALUE_2',
        discrgren7_0: 'VALUE_2',
        discrgren8_0: 'VALUE_2',
        discrgren9_0: 'VALUE_2',
        discrgval8_0: 'VALUE_2',
        discrgval9_0: 'VALUE_2',
        discrgren1_0: 'VALUE_2',
        discrgren2_0: 'VALUE_2',
        discrgren3_0: 'VALUE_2',
        discrgren4_0: 'VALUE_2',
        discrgren5_0: 'VALUE_2',
        discrgren6_0: 'VALUE_2',
        oricry_0: 'VALUE_2',
        discrgval5_0: 'VALUE_2',
        discrgval6_0: 'VALUE_2',
        discrgval7_0: 'VALUE_2',
        discrgval1_0: 'VALUE_2',
        discrgval2_0: 'VALUE_2',
        discrgval3_0: 'VALUE_2',
        taxrcp_0: 'VALUE_2',
      },
      {
        itmdes1_0: 'Désignation article 3',
        discrgval4_0: 'VALUE_3',
        taxiss_0: 'VALUE_3',
        taxoth1_0: 'VALUE_3',
        taxoth2_0: 'VALUE_3',
        poplin_0: 'VALUE_3',
        tsicod_0: 'VALUE_3',
        pohtyp_0: 'VALUE_3',
        linrevnum_0: 'POR0003',
        gropri_0: 31.5,
        priren_0: 31.5,
        prhfcy_0: 'VALUE_3',
        vat_0: 'VALUE_3',
        itmref_0: 'VALUE_3',
        popseq_0: 'VALUE_3',
        netpri_0: 31.5,
        pohnum_0: 'VALUE_3',
        cpy_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        linbuy_0: 'VALUE_3',
        strdat_0: new Date().toISOString().split('T')[0],
        popcreflg_0: 'VALUE_3',
        itmdes_0: 'VALUE_3',
        eecincrat_0: 'VALUE_3',
        popdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        quaflg_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        mattol_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        fcyadd_0: 'VALUE_3',
        pjt_0: 'VALUE_3',
        discrgren7_0: 'VALUE_3',
        discrgren8_0: 'VALUE_3',
        discrgren9_0: 'VALUE_3',
        discrgval8_0: 'VALUE_3',
        discrgval9_0: 'VALUE_3',
        discrgren1_0: 'VALUE_3',
        discrgren2_0: 'VALUE_3',
        discrgren3_0: 'VALUE_3',
        discrgren4_0: 'VALUE_3',
        discrgren5_0: 'VALUE_3',
        discrgren6_0: 'VALUE_3',
        oricry_0: 'VALUE_3',
        discrgval5_0: 'VALUE_3',
        discrgval6_0: 'VALUE_3',
        discrgval7_0: 'VALUE_3',
        discrgval1_0: 'VALUE_3',
        discrgval2_0: 'VALUE_3',
        discrgval3_0: 'VALUE_3',
        taxrcp_0: 'VALUE_3',
      },
      {
        itmdes1_0: 'Désignation article 4',
        discrgval4_0: 'VALUE_4',
        taxiss_0: 'VALUE_4',
        taxoth1_0: 'VALUE_4',
        taxoth2_0: 'VALUE_4',
        poplin_0: 'VALUE_4',
        tsicod_0: 'VALUE_4',
        pohtyp_0: 'VALUE_4',
        linrevnum_0: 'POR0004',
        gropri_0: 42.0,
        priren_0: 42.0,
        prhfcy_0: 'VALUE_4',
        vat_0: 'VALUE_4',
        itmref_0: 'VALUE_4',
        popseq_0: 'VALUE_4',
        netpri_0: 42.0,
        pohnum_0: 'VALUE_4',
        cpy_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        linbuy_0: 'VALUE_4',
        strdat_0: new Date().toISOString().split('T')[0],
        popcreflg_0: 'VALUE_4',
        itmdes_0: 'VALUE_4',
        eecincrat_0: 'VALUE_4',
        popdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        quaflg_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        mattol_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        fcyadd_0: 'VALUE_4',
        pjt_0: 'VALUE_4',
        discrgren7_0: 'VALUE_4',
        discrgren8_0: 'VALUE_4',
        discrgren9_0: 'VALUE_4',
        discrgval8_0: 'VALUE_4',
        discrgval9_0: 'VALUE_4',
        discrgren1_0: 'VALUE_4',
        discrgren2_0: 'VALUE_4',
        discrgren3_0: 'VALUE_4',
        discrgren4_0: 'VALUE_4',
        discrgren5_0: 'VALUE_4',
        discrgren6_0: 'VALUE_4',
        oricry_0: 'VALUE_4',
        discrgval5_0: 'VALUE_4',
        discrgval6_0: 'VALUE_4',
        discrgval7_0: 'VALUE_4',
        discrgval1_0: 'VALUE_4',
        discrgval2_0: 'VALUE_4',
        discrgval3_0: 'VALUE_4',
        taxrcp_0: 'VALUE_4',
      },
      {
        itmdes1_0: 'Désignation article 5',
        discrgval4_0: 'VALUE_5',
        taxiss_0: 'VALUE_5',
        taxoth1_0: 'VALUE_5',
        taxoth2_0: 'VALUE_5',
        poplin_0: 'VALUE_5',
        tsicod_0: 'VALUE_5',
        pohtyp_0: 'VALUE_5',
        linrevnum_0: 'POR0005',
        gropri_0: 52.5,
        priren_0: 52.5,
        prhfcy_0: 'VALUE_5',
        vat_0: 'VALUE_5',
        itmref_0: 'VALUE_5',
        popseq_0: 'VALUE_5',
        netpri_0: 52.5,
        pohnum_0: 'VALUE_5',
        cpy_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        linbuy_0: 'VALUE_5',
        strdat_0: new Date().toISOString().split('T')[0],
        popcreflg_0: 'VALUE_5',
        itmdes_0: 'VALUE_5',
        eecincrat_0: 'VALUE_5',
        popdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        quaflg_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        mattol_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        fcyadd_0: 'VALUE_5',
        pjt_0: 'VALUE_5',
        discrgren7_0: 'VALUE_5',
        discrgren8_0: 'VALUE_5',
        discrgren9_0: 'VALUE_5',
        discrgval8_0: 'VALUE_5',
        discrgval9_0: 'VALUE_5',
        discrgren1_0: 'VALUE_5',
        discrgren2_0: 'VALUE_5',
        discrgren3_0: 'VALUE_5',
        discrgren4_0: 'VALUE_5',
        discrgren5_0: 'VALUE_5',
        discrgren6_0: 'VALUE_5',
        oricry_0: 'VALUE_5',
        discrgval5_0: 'VALUE_5',
        discrgval6_0: 'VALUE_5',
        discrgval7_0: 'VALUE_5',
        discrgval1_0: 'VALUE_5',
        discrgval2_0: 'VALUE_5',
        discrgval3_0: 'VALUE_5',
        taxrcp_0: 'VALUE_5',
      },
      {
        itmdes1_0: 'Désignation article 6',
        discrgval4_0: 'VALUE_6',
        taxiss_0: 'VALUE_6',
        taxoth1_0: 'VALUE_6',
        taxoth2_0: 'VALUE_6',
        poplin_0: 'VALUE_6',
        tsicod_0: 'VALUE_6',
        pohtyp_0: 'VALUE_6',
        linrevnum_0: 'POR0006',
        gropri_0: 63.0,
        priren_0: 63.0,
        prhfcy_0: 'VALUE_6',
        vat_0: 'VALUE_6',
        itmref_0: 'VALUE_6',
        popseq_0: 'VALUE_6',
        netpri_0: 63.0,
        pohnum_0: 'VALUE_6',
        cpy_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        linbuy_0: 'VALUE_6',
        strdat_0: new Date().toISOString().split('T')[0],
        popcreflg_0: 'VALUE_6',
        itmdes_0: 'VALUE_6',
        eecincrat_0: 'VALUE_6',
        popdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        quaflg_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        mattol_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        fcyadd_0: 'VALUE_6',
        pjt_0: 'VALUE_6',
        discrgren7_0: 'VALUE_6',
        discrgren8_0: 'VALUE_6',
        discrgren9_0: 'VALUE_6',
        discrgval8_0: 'VALUE_6',
        discrgval9_0: 'VALUE_6',
        discrgren1_0: 'VALUE_6',
        discrgren2_0: 'VALUE_6',
        discrgren3_0: 'VALUE_6',
        discrgren4_0: 'VALUE_6',
        discrgren5_0: 'VALUE_6',
        discrgren6_0: 'VALUE_6',
        oricry_0: 'VALUE_6',
        discrgval5_0: 'VALUE_6',
        discrgval6_0: 'VALUE_6',
        discrgval7_0: 'VALUE_6',
        discrgval1_0: 'VALUE_6',
        discrgval2_0: 'VALUE_6',
        discrgval3_0: 'VALUE_6',
        taxrcp_0: 'VALUE_6',
      },
      {
        itmdes1_0: 'Désignation article 7',
        discrgval4_0: 'VALUE_7',
        taxiss_0: 'VALUE_7',
        taxoth1_0: 'VALUE_7',
        taxoth2_0: 'VALUE_7',
        poplin_0: 'VALUE_7',
        tsicod_0: 'VALUE_7',
        pohtyp_0: 'VALUE_7',
        linrevnum_0: 'POR0007',
        gropri_0: 73.5,
        priren_0: 73.5,
        prhfcy_0: 'VALUE_7',
        vat_0: 'VALUE_7',
        itmref_0: 'VALUE_7',
        popseq_0: 'VALUE_7',
        netpri_0: 73.5,
        pohnum_0: 'VALUE_7',
        cpy_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        linbuy_0: 'VALUE_7',
        strdat_0: new Date().toISOString().split('T')[0],
        popcreflg_0: 'VALUE_7',
        itmdes_0: 'VALUE_7',
        eecincrat_0: 'VALUE_7',
        popdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        quaflg_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        mattol_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        fcyadd_0: 'VALUE_7',
        pjt_0: 'VALUE_7',
        discrgren7_0: 'VALUE_7',
        discrgren8_0: 'VALUE_7',
        discrgren9_0: 'VALUE_7',
        discrgval8_0: 'VALUE_7',
        discrgval9_0: 'VALUE_7',
        discrgren1_0: 'VALUE_7',
        discrgren2_0: 'VALUE_7',
        discrgren3_0: 'VALUE_7',
        discrgren4_0: 'VALUE_7',
        discrgren5_0: 'VALUE_7',
        discrgren6_0: 'VALUE_7',
        oricry_0: 'VALUE_7',
        discrgval5_0: 'VALUE_7',
        discrgval6_0: 'VALUE_7',
        discrgval7_0: 'VALUE_7',
        discrgval1_0: 'VALUE_7',
        discrgval2_0: 'VALUE_7',
        discrgval3_0: 'VALUE_7',
        taxrcp_0: 'VALUE_7',
      },
      {
        itmdes1_0: 'Désignation article 8',
        discrgval4_0: 'VALUE_8',
        taxiss_0: 'VALUE_8',
        taxoth1_0: 'VALUE_8',
        taxoth2_0: 'VALUE_8',
        poplin_0: 'VALUE_8',
        tsicod_0: 'VALUE_8',
        pohtyp_0: 'VALUE_8',
        linrevnum_0: 'POR0008',
        gropri_0: 84.0,
        priren_0: 84.0,
        prhfcy_0: 'VALUE_8',
        vat_0: 'VALUE_8',
        itmref_0: 'VALUE_8',
        popseq_0: 'VALUE_8',
        netpri_0: 84.0,
        pohnum_0: 'VALUE_8',
        cpy_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        linbuy_0: 'VALUE_8',
        strdat_0: new Date().toISOString().split('T')[0],
        popcreflg_0: 'VALUE_8',
        itmdes_0: 'VALUE_8',
        eecincrat_0: 'VALUE_8',
        popdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        quaflg_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        mattol_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        fcyadd_0: 'VALUE_8',
        pjt_0: 'VALUE_8',
        discrgren7_0: 'VALUE_8',
        discrgren8_0: 'VALUE_8',
        discrgren9_0: 'VALUE_8',
        discrgval8_0: 'VALUE_8',
        discrgval9_0: 'VALUE_8',
        discrgren1_0: 'VALUE_8',
        discrgren2_0: 'VALUE_8',
        discrgren3_0: 'VALUE_8',
        discrgren4_0: 'VALUE_8',
        discrgren5_0: 'VALUE_8',
        discrgren6_0: 'VALUE_8',
        oricry_0: 'VALUE_8',
        discrgval5_0: 'VALUE_8',
        discrgval6_0: 'VALUE_8',
        discrgval7_0: 'VALUE_8',
        discrgval1_0: 'VALUE_8',
        discrgval2_0: 'VALUE_8',
        discrgval3_0: 'VALUE_8',
        taxrcp_0: 'VALUE_8',
      },
      {
        itmdes1_0: 'Désignation article 9',
        discrgval4_0: 'VALUE_9',
        taxiss_0: 'VALUE_9',
        taxoth1_0: 'VALUE_9',
        taxoth2_0: 'VALUE_9',
        poplin_0: 'VALUE_9',
        tsicod_0: 'VALUE_9',
        pohtyp_0: 'VALUE_9',
        linrevnum_0: 'POR0009',
        gropri_0: 94.5,
        priren_0: 94.5,
        prhfcy_0: 'VALUE_9',
        vat_0: 'VALUE_9',
        itmref_0: 'VALUE_9',
        popseq_0: 'VALUE_9',
        netpri_0: 94.5,
        pohnum_0: 'VALUE_9',
        cpy_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        linbuy_0: 'VALUE_9',
        strdat_0: new Date().toISOString().split('T')[0],
        popcreflg_0: 'VALUE_9',
        itmdes_0: 'VALUE_9',
        eecincrat_0: 'VALUE_9',
        popdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        quaflg_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        mattol_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        fcyadd_0: 'VALUE_9',
        pjt_0: 'VALUE_9',
        discrgren7_0: 'VALUE_9',
        discrgren8_0: 'VALUE_9',
        discrgren9_0: 'VALUE_9',
        discrgval8_0: 'VALUE_9',
        discrgval9_0: 'VALUE_9',
        discrgren1_0: 'VALUE_9',
        discrgren2_0: 'VALUE_9',
        discrgren3_0: 'VALUE_9',
        discrgren4_0: 'VALUE_9',
        discrgren5_0: 'VALUE_9',
        discrgren6_0: 'VALUE_9',
        oricry_0: 'VALUE_9',
        discrgval5_0: 'VALUE_9',
        discrgval6_0: 'VALUE_9',
        discrgval7_0: 'VALUE_9',
        discrgval1_0: 'VALUE_9',
        discrgval2_0: 'VALUE_9',
        discrgval3_0: 'VALUE_9',
        taxrcp_0: 'VALUE_9',
      },
      {
        itmdes1_0: 'Désignation article 10',
        discrgval4_0: 'VALUE_10',
        taxiss_0: 'VALUE_10',
        taxoth1_0: 'VALUE_10',
        taxoth2_0: 'VALUE_10',
        poplin_0: 'VALUE_10',
        tsicod_0: 'VALUE_10',
        pohtyp_0: 'VALUE_10',
        linrevnum_0: 'POR0010',
        gropri_0: 105.0,
        priren_0: 105.0,
        prhfcy_0: 'VALUE_10',
        vat_0: 'VALUE_10',
        itmref_0: 'VALUE_10',
        popseq_0: 'VALUE_10',
        netpri_0: 105.0,
        pohnum_0: 'VALUE_10',
        cpy_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        linbuy_0: 'VALUE_10',
        strdat_0: new Date().toISOString().split('T')[0],
        popcreflg_0: 'VALUE_10',
        itmdes_0: 'VALUE_10',
        eecincrat_0: 'VALUE_10',
        popdat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        quaflg_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        mattol_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        fcyadd_0: 'VALUE_10',
        pjt_0: 'VALUE_10',
        discrgren7_0: 'VALUE_10',
        discrgren8_0: 'VALUE_10',
        discrgren9_0: 'VALUE_10',
        discrgval8_0: 'VALUE_10',
        discrgval9_0: 'VALUE_10',
        discrgren1_0: 'VALUE_10',
        discrgren2_0: 'VALUE_10',
        discrgren3_0: 'VALUE_10',
        discrgren4_0: 'VALUE_10',
        discrgren5_0: 'VALUE_10',
        discrgren6_0: 'VALUE_10',
        oricry_0: 'VALUE_10',
        discrgval5_0: 'VALUE_10',
        discrgval6_0: 'VALUE_10',
        discrgval7_0: 'VALUE_10',
        discrgval1_0: 'VALUE_10',
        discrgval2_0: 'VALUE_10',
        discrgval3_0: 'VALUE_10',
        taxrcp_0: 'VALUE_10',
      },
    ]

    await Database.table('porderp').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans porderp`)
  }
}
