import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour PRECEIPT
    const data = [
      {
        trllicplate_0: 'VALUE_1',
        x1wmssas_0: 'VALUE_1',
        arvdat_0: new Date().toISOString().split('T')[0],
        dpedat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        pstflg_0: 'VALUE_1',
        totamtati_0: 10.5,
        mdl_0: 'VALUE_1',
        pjth_0: 'VALUE_1',
        invlinnbr_0: 'VALUE_1',
        betcpy_0: 'VALUE_1',
        trscod_0: 'VALUE_1',
        eecsch_0: 'VALUE_1',
        chgcoe_0: 'VALUE_1',
        totvol_0: 'VALUE_1',
        clsvcr_0: 'VALUE_1',
        tex1_0: 'VALUE_1',
        x4sdhnum_0: 'PRE0001',
        die_0: 'VALUE_1',
        totamtatil_0: 10.5,
        totamtnotl_0: 10.5,
        auuid_0: 'VALUE_1',
        xblocage_0: 'VALUE_1',
        ffwadd_0: 'VALUE_1',
        bpsnum_0: 'VALUE_1',
        totlinweu_0: 'VALUE_1',
        totlinvou_0: 'VALUE_1',
        updusr_0: 'VALUE_1',
        eecloc_0: 'VALUE_1',
        ffwnum_0: 'VALUE_1',
        bpainv_0: 'VALUE_1',
        totamtnot_0: 10.5,
        ndedat_0: new Date().toISOString().split('T')[0],
        totgrowei_0: 'VALUE_1',
        vactyp_0: 'VALUE_1',
        xncflg_0: 'VALUE_1',
        cce_0: 'VALUE_1',
        etd_0: 'VALUE_1',
        eta_0: 'VALUE_1',
        pstlinnbr_0: 'VALUE_1',
        bpsinv_0: 'VALUE_1',
        totlinamt_0: 'Total HT lignes 1',
        tottaxamt_0: 10.5,
        cai_0: 'VALUE_1',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_1',
        scuvcr_0: 'VALUE_1',
        invlinctr_0: 'VALUE_1',
        x4numint_0: 'VALUE_1',
        x4numdemand_0: 'VALUE_1',
        totnetwei_0: 'VALUE_1',
        cpy_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_1',
        credat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_1',
        betfcy_0: 'VALUE_1',
        bpocty_0: 'VALUE_1',
        bpocry_0: 'VALUE_1',
        bpoposcod_0: 'VALUE_1',
        tex2_0: 'VALUE_1',
        cur_0: 'VALUE_1',
        chgtyp_0: 'VALUE_1',
        bptnum_0: 'VALUE_1',
        linnbr_0: 'VALUE_1',
        seqvcr_0: 'VALUE_1',
        ycausrdes_0: 'VALUE_1',
        gpgcod_0: 'VALUE_1',
        rcpdat_0: new Date().toISOString().split('T')[0],
        bpaadd_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        bpsnde_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        vacbpr_0: 'VALUE_1',
        vou_0: 'VALUE_1',
        dspvou_0: 'VALUE_1',
        weu_0: 'VALUE_1',
        dspweu_0: 'VALUE_1',
        invdtavat1_0: 'VALUE_1',
        bpoadd_0: 'VALUE_1',
        bpoaddlig_0: 'VALUE_1',
        bpocrynam_0: 'VALUE_1',
        eecnum_0: 'VALUE_1',
        eecnumdeb_0: 'VALUE_1',
        invdtalin2_0: 'VALUE_1',
        eectrn_0: 'VALUE_1',
        bposat_0: 'VALUE_1',
        eecnat_0: 'VALUE_1',
        eecict_0: 'VALUE_1',
        pstdat_0: new Date().toISOString().split('T')[0],
        entcod_0: 'VALUE_1',
        purtyp_0: 'VALUE_1',
        invdtavat2_0: 'VALUE_1',
        bpapay_0: 'VALUE_1',
        typvcr_0: 'VALUE_1',
        licplate_0: 'VALUE_1',
        bponam_0: 'VALUE_1',
        dep_0: 'VALUE_1',
        tsscod_0: 'VALUE_1',
        totlinqty_0: 10.5,
        invdtalin1_0: 'VALUE_1',
        prhfcy_0: 'VALUE_1',
        pthnum_0: 'VALUE_1',
        invflg_0: 'VALUE_1',
        prnflg_0: 'VALUE_1',
      },
      {
        trllicplate_0: 'VALUE_2',
        x1wmssas_0: 'VALUE_2',
        arvdat_0: new Date().toISOString().split('T')[0],
        dpedat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        pstflg_0: 'VALUE_2',
        totamtati_0: 21.0,
        mdl_0: 'VALUE_2',
        pjth_0: 'VALUE_2',
        invlinnbr_0: 'VALUE_2',
        betcpy_0: 'VALUE_2',
        trscod_0: 'VALUE_2',
        eecsch_0: 'VALUE_2',
        chgcoe_0: 'VALUE_2',
        totvol_0: 'VALUE_2',
        clsvcr_0: 'VALUE_2',
        tex1_0: 'VALUE_2',
        x4sdhnum_0: 'PRE0002',
        die_0: 'VALUE_2',
        totamtatil_0: 21.0,
        totamtnotl_0: 21.0,
        auuid_0: 'VALUE_2',
        xblocage_0: 'VALUE_2',
        ffwadd_0: 'VALUE_2',
        bpsnum_0: 'VALUE_2',
        totlinweu_0: 'VALUE_2',
        totlinvou_0: 'VALUE_2',
        updusr_0: 'VALUE_2',
        eecloc_0: 'VALUE_2',
        ffwnum_0: 'VALUE_2',
        bpainv_0: 'VALUE_2',
        totamtnot_0: 21.0,
        ndedat_0: new Date().toISOString().split('T')[0],
        totgrowei_0: 'VALUE_2',
        vactyp_0: 'VALUE_2',
        xncflg_0: 'VALUE_2',
        cce_0: 'VALUE_2',
        etd_0: 'VALUE_2',
        eta_0: 'VALUE_2',
        pstlinnbr_0: 'VALUE_2',
        bpsinv_0: 'VALUE_2',
        totlinamt_0: 'Total HT lignes 2',
        tottaxamt_0: 21.0,
        cai_0: 'VALUE_2',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_2',
        scuvcr_0: 'VALUE_2',
        invlinctr_0: 'VALUE_2',
        x4numint_0: 'VALUE_2',
        x4numdemand_0: 'VALUE_2',
        totnetwei_0: 'VALUE_2',
        cpy_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_2',
        credat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_2',
        betfcy_0: 'VALUE_2',
        bpocty_0: 'VALUE_2',
        bpocry_0: 'VALUE_2',
        bpoposcod_0: 'VALUE_2',
        tex2_0: 'VALUE_2',
        cur_0: 'VALUE_2',
        chgtyp_0: 'VALUE_2',
        bptnum_0: 'VALUE_2',
        linnbr_0: 'VALUE_2',
        seqvcr_0: 'VALUE_2',
        ycausrdes_0: 'VALUE_2',
        gpgcod_0: 'VALUE_2',
        rcpdat_0: new Date().toISOString().split('T')[0],
        bpaadd_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        bpsnde_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        vacbpr_0: 'VALUE_2',
        vou_0: 'VALUE_2',
        dspvou_0: 'VALUE_2',
        weu_0: 'VALUE_2',
        dspweu_0: 'VALUE_2',
        invdtavat1_0: 'VALUE_2',
        bpoadd_0: 'VALUE_2',
        bpoaddlig_0: 'VALUE_2',
        bpocrynam_0: 'VALUE_2',
        eecnum_0: 'VALUE_2',
        eecnumdeb_0: 'VALUE_2',
        invdtalin2_0: 'VALUE_2',
        eectrn_0: 'VALUE_2',
        bposat_0: 'VALUE_2',
        eecnat_0: 'VALUE_2',
        eecict_0: 'VALUE_2',
        pstdat_0: new Date().toISOString().split('T')[0],
        entcod_0: 'VALUE_2',
        purtyp_0: 'VALUE_2',
        invdtavat2_0: 'VALUE_2',
        bpapay_0: 'VALUE_2',
        typvcr_0: 'VALUE_2',
        licplate_0: 'VALUE_2',
        bponam_0: 'VALUE_2',
        dep_0: 'VALUE_2',
        tsscod_0: 'VALUE_2',
        totlinqty_0: 21.0,
        invdtalin1_0: 'VALUE_2',
        prhfcy_0: 'VALUE_2',
        pthnum_0: 'VALUE_2',
        invflg_0: 'VALUE_2',
        prnflg_0: 'VALUE_2',
      },
      {
        trllicplate_0: 'VALUE_3',
        x1wmssas_0: 'VALUE_3',
        arvdat_0: new Date().toISOString().split('T')[0],
        dpedat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        pstflg_0: 'VALUE_3',
        totamtati_0: 31.5,
        mdl_0: 'VALUE_3',
        pjth_0: 'VALUE_3',
        invlinnbr_0: 'VALUE_3',
        betcpy_0: 'VALUE_3',
        trscod_0: 'VALUE_3',
        eecsch_0: 'VALUE_3',
        chgcoe_0: 'VALUE_3',
        totvol_0: 'VALUE_3',
        clsvcr_0: 'VALUE_3',
        tex1_0: 'VALUE_3',
        x4sdhnum_0: 'PRE0003',
        die_0: 'VALUE_3',
        totamtatil_0: 31.5,
        totamtnotl_0: 31.5,
        auuid_0: 'VALUE_3',
        xblocage_0: 'VALUE_3',
        ffwadd_0: 'VALUE_3',
        bpsnum_0: 'VALUE_3',
        totlinweu_0: 'VALUE_3',
        totlinvou_0: 'VALUE_3',
        updusr_0: 'VALUE_3',
        eecloc_0: 'VALUE_3',
        ffwnum_0: 'VALUE_3',
        bpainv_0: 'VALUE_3',
        totamtnot_0: 31.5,
        ndedat_0: new Date().toISOString().split('T')[0],
        totgrowei_0: 'VALUE_3',
        vactyp_0: 'VALUE_3',
        xncflg_0: 'VALUE_3',
        cce_0: 'VALUE_3',
        etd_0: 'VALUE_3',
        eta_0: 'VALUE_3',
        pstlinnbr_0: 'VALUE_3',
        bpsinv_0: 'VALUE_3',
        totlinamt_0: 'Total HT lignes 3',
        tottaxamt_0: 31.5,
        cai_0: 'VALUE_3',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_3',
        scuvcr_0: 'VALUE_3',
        invlinctr_0: 'VALUE_3',
        x4numint_0: 'VALUE_3',
        x4numdemand_0: 'VALUE_3',
        totnetwei_0: 'VALUE_3',
        cpy_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_3',
        credat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_3',
        betfcy_0: 'VALUE_3',
        bpocty_0: 'VALUE_3',
        bpocry_0: 'VALUE_3',
        bpoposcod_0: 'VALUE_3',
        tex2_0: 'VALUE_3',
        cur_0: 'VALUE_3',
        chgtyp_0: 'VALUE_3',
        bptnum_0: 'VALUE_3',
        linnbr_0: 'VALUE_3',
        seqvcr_0: 'VALUE_3',
        ycausrdes_0: 'VALUE_3',
        gpgcod_0: 'VALUE_3',
        rcpdat_0: new Date().toISOString().split('T')[0],
        bpaadd_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        bpsnde_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        vacbpr_0: 'VALUE_3',
        vou_0: 'VALUE_3',
        dspvou_0: 'VALUE_3',
        weu_0: 'VALUE_3',
        dspweu_0: 'VALUE_3',
        invdtavat1_0: 'VALUE_3',
        bpoadd_0: 'VALUE_3',
        bpoaddlig_0: 'VALUE_3',
        bpocrynam_0: 'VALUE_3',
        eecnum_0: 'VALUE_3',
        eecnumdeb_0: 'VALUE_3',
        invdtalin2_0: 'VALUE_3',
        eectrn_0: 'VALUE_3',
        bposat_0: 'VALUE_3',
        eecnat_0: 'VALUE_3',
        eecict_0: 'VALUE_3',
        pstdat_0: new Date().toISOString().split('T')[0],
        entcod_0: 'VALUE_3',
        purtyp_0: 'VALUE_3',
        invdtavat2_0: 'VALUE_3',
        bpapay_0: 'VALUE_3',
        typvcr_0: 'VALUE_3',
        licplate_0: 'VALUE_3',
        bponam_0: 'VALUE_3',
        dep_0: 'VALUE_3',
        tsscod_0: 'VALUE_3',
        totlinqty_0: 31.5,
        invdtalin1_0: 'VALUE_3',
        prhfcy_0: 'VALUE_3',
        pthnum_0: 'VALUE_3',
        invflg_0: 'VALUE_3',
        prnflg_0: 'VALUE_3',
      },
      {
        trllicplate_0: 'VALUE_4',
        x1wmssas_0: 'VALUE_4',
        arvdat_0: new Date().toISOString().split('T')[0],
        dpedat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        pstflg_0: 'VALUE_4',
        totamtati_0: 42.0,
        mdl_0: 'VALUE_4',
        pjth_0: 'VALUE_4',
        invlinnbr_0: 'VALUE_4',
        betcpy_0: 'VALUE_4',
        trscod_0: 'VALUE_4',
        eecsch_0: 'VALUE_4',
        chgcoe_0: 'VALUE_4',
        totvol_0: 'VALUE_4',
        clsvcr_0: 'VALUE_4',
        tex1_0: 'VALUE_4',
        x4sdhnum_0: 'PRE0004',
        die_0: 'VALUE_4',
        totamtatil_0: 42.0,
        totamtnotl_0: 42.0,
        auuid_0: 'VALUE_4',
        xblocage_0: 'VALUE_4',
        ffwadd_0: 'VALUE_4',
        bpsnum_0: 'VALUE_4',
        totlinweu_0: 'VALUE_4',
        totlinvou_0: 'VALUE_4',
        updusr_0: 'VALUE_4',
        eecloc_0: 'VALUE_4',
        ffwnum_0: 'VALUE_4',
        bpainv_0: 'VALUE_4',
        totamtnot_0: 42.0,
        ndedat_0: new Date().toISOString().split('T')[0],
        totgrowei_0: 'VALUE_4',
        vactyp_0: 'VALUE_4',
        xncflg_0: 'VALUE_4',
        cce_0: 'VALUE_4',
        etd_0: 'VALUE_4',
        eta_0: 'VALUE_4',
        pstlinnbr_0: 'VALUE_4',
        bpsinv_0: 'VALUE_4',
        totlinamt_0: 'Total HT lignes 4',
        tottaxamt_0: 42.0,
        cai_0: 'VALUE_4',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_4',
        scuvcr_0: 'VALUE_4',
        invlinctr_0: 'VALUE_4',
        x4numint_0: 'VALUE_4',
        x4numdemand_0: 'VALUE_4',
        totnetwei_0: 'VALUE_4',
        cpy_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_4',
        credat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_4',
        betfcy_0: 'VALUE_4',
        bpocty_0: 'VALUE_4',
        bpocry_0: 'VALUE_4',
        bpoposcod_0: 'VALUE_4',
        tex2_0: 'VALUE_4',
        cur_0: 'VALUE_4',
        chgtyp_0: 'VALUE_4',
        bptnum_0: 'VALUE_4',
        linnbr_0: 'VALUE_4',
        seqvcr_0: 'VALUE_4',
        ycausrdes_0: 'VALUE_4',
        gpgcod_0: 'VALUE_4',
        rcpdat_0: new Date().toISOString().split('T')[0],
        bpaadd_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        bpsnde_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        vacbpr_0: 'VALUE_4',
        vou_0: 'VALUE_4',
        dspvou_0: 'VALUE_4',
        weu_0: 'VALUE_4',
        dspweu_0: 'VALUE_4',
        invdtavat1_0: 'VALUE_4',
        bpoadd_0: 'VALUE_4',
        bpoaddlig_0: 'VALUE_4',
        bpocrynam_0: 'VALUE_4',
        eecnum_0: 'VALUE_4',
        eecnumdeb_0: 'VALUE_4',
        invdtalin2_0: 'VALUE_4',
        eectrn_0: 'VALUE_4',
        bposat_0: 'VALUE_4',
        eecnat_0: 'VALUE_4',
        eecict_0: 'VALUE_4',
        pstdat_0: new Date().toISOString().split('T')[0],
        entcod_0: 'VALUE_4',
        purtyp_0: 'VALUE_4',
        invdtavat2_0: 'VALUE_4',
        bpapay_0: 'VALUE_4',
        typvcr_0: 'VALUE_4',
        licplate_0: 'VALUE_4',
        bponam_0: 'VALUE_4',
        dep_0: 'VALUE_4',
        tsscod_0: 'VALUE_4',
        totlinqty_0: 42.0,
        invdtalin1_0: 'VALUE_4',
        prhfcy_0: 'VALUE_4',
        pthnum_0: 'VALUE_4',
        invflg_0: 'VALUE_4',
        prnflg_0: 'VALUE_4',
      },
      {
        trllicplate_0: 'VALUE_5',
        x1wmssas_0: 'VALUE_5',
        arvdat_0: new Date().toISOString().split('T')[0],
        dpedat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        pstflg_0: 'VALUE_5',
        totamtati_0: 52.5,
        mdl_0: 'VALUE_5',
        pjth_0: 'VALUE_5',
        invlinnbr_0: 'VALUE_5',
        betcpy_0: 'VALUE_5',
        trscod_0: 'VALUE_5',
        eecsch_0: 'VALUE_5',
        chgcoe_0: 'VALUE_5',
        totvol_0: 'VALUE_5',
        clsvcr_0: 'VALUE_5',
        tex1_0: 'VALUE_5',
        x4sdhnum_0: 'PRE0005',
        die_0: 'VALUE_5',
        totamtatil_0: 52.5,
        totamtnotl_0: 52.5,
        auuid_0: 'VALUE_5',
        xblocage_0: 'VALUE_5',
        ffwadd_0: 'VALUE_5',
        bpsnum_0: 'VALUE_5',
        totlinweu_0: 'VALUE_5',
        totlinvou_0: 'VALUE_5',
        updusr_0: 'VALUE_5',
        eecloc_0: 'VALUE_5',
        ffwnum_0: 'VALUE_5',
        bpainv_0: 'VALUE_5',
        totamtnot_0: 52.5,
        ndedat_0: new Date().toISOString().split('T')[0],
        totgrowei_0: 'VALUE_5',
        vactyp_0: 'VALUE_5',
        xncflg_0: 'VALUE_5',
        cce_0: 'VALUE_5',
        etd_0: 'VALUE_5',
        eta_0: 'VALUE_5',
        pstlinnbr_0: 'VALUE_5',
        bpsinv_0: 'VALUE_5',
        totlinamt_0: 'Total HT lignes 5',
        tottaxamt_0: 52.5,
        cai_0: 'VALUE_5',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_5',
        scuvcr_0: 'VALUE_5',
        invlinctr_0: 'VALUE_5',
        x4numint_0: 'VALUE_5',
        x4numdemand_0: 'VALUE_5',
        totnetwei_0: 'VALUE_5',
        cpy_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_5',
        credat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_5',
        betfcy_0: 'VALUE_5',
        bpocty_0: 'VALUE_5',
        bpocry_0: 'VALUE_5',
        bpoposcod_0: 'VALUE_5',
        tex2_0: 'VALUE_5',
        cur_0: 'VALUE_5',
        chgtyp_0: 'VALUE_5',
        bptnum_0: 'VALUE_5',
        linnbr_0: 'VALUE_5',
        seqvcr_0: 'VALUE_5',
        ycausrdes_0: 'VALUE_5',
        gpgcod_0: 'VALUE_5',
        rcpdat_0: new Date().toISOString().split('T')[0],
        bpaadd_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        bpsnde_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        vacbpr_0: 'VALUE_5',
        vou_0: 'VALUE_5',
        dspvou_0: 'VALUE_5',
        weu_0: 'VALUE_5',
        dspweu_0: 'VALUE_5',
        invdtavat1_0: 'VALUE_5',
        bpoadd_0: 'VALUE_5',
        bpoaddlig_0: 'VALUE_5',
        bpocrynam_0: 'VALUE_5',
        eecnum_0: 'VALUE_5',
        eecnumdeb_0: 'VALUE_5',
        invdtalin2_0: 'VALUE_5',
        eectrn_0: 'VALUE_5',
        bposat_0: 'VALUE_5',
        eecnat_0: 'VALUE_5',
        eecict_0: 'VALUE_5',
        pstdat_0: new Date().toISOString().split('T')[0],
        entcod_0: 'VALUE_5',
        purtyp_0: 'VALUE_5',
        invdtavat2_0: 'VALUE_5',
        bpapay_0: 'VALUE_5',
        typvcr_0: 'VALUE_5',
        licplate_0: 'VALUE_5',
        bponam_0: 'VALUE_5',
        dep_0: 'VALUE_5',
        tsscod_0: 'VALUE_5',
        totlinqty_0: 52.5,
        invdtalin1_0: 'VALUE_5',
        prhfcy_0: 'VALUE_5',
        pthnum_0: 'VALUE_5',
        invflg_0: 'VALUE_5',
        prnflg_0: 'VALUE_5',
      },
      {
        trllicplate_0: 'VALUE_6',
        x1wmssas_0: 'VALUE_6',
        arvdat_0: new Date().toISOString().split('T')[0],
        dpedat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        pstflg_0: 'VALUE_6',
        totamtati_0: 63.0,
        mdl_0: 'VALUE_6',
        pjth_0: 'VALUE_6',
        invlinnbr_0: 'VALUE_6',
        betcpy_0: 'VALUE_6',
        trscod_0: 'VALUE_6',
        eecsch_0: 'VALUE_6',
        chgcoe_0: 'VALUE_6',
        totvol_0: 'VALUE_6',
        clsvcr_0: 'VALUE_6',
        tex1_0: 'VALUE_6',
        x4sdhnum_0: 'PRE0006',
        die_0: 'VALUE_6',
        totamtatil_0: 63.0,
        totamtnotl_0: 63.0,
        auuid_0: 'VALUE_6',
        xblocage_0: 'VALUE_6',
        ffwadd_0: 'VALUE_6',
        bpsnum_0: 'VALUE_6',
        totlinweu_0: 'VALUE_6',
        totlinvou_0: 'VALUE_6',
        updusr_0: 'VALUE_6',
        eecloc_0: 'VALUE_6',
        ffwnum_0: 'VALUE_6',
        bpainv_0: 'VALUE_6',
        totamtnot_0: 63.0,
        ndedat_0: new Date().toISOString().split('T')[0],
        totgrowei_0: 'VALUE_6',
        vactyp_0: 'VALUE_6',
        xncflg_0: 'VALUE_6',
        cce_0: 'VALUE_6',
        etd_0: 'VALUE_6',
        eta_0: 'VALUE_6',
        pstlinnbr_0: 'VALUE_6',
        bpsinv_0: 'VALUE_6',
        totlinamt_0: 'Total HT lignes 6',
        tottaxamt_0: 63.0,
        cai_0: 'VALUE_6',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_6',
        scuvcr_0: 'VALUE_6',
        invlinctr_0: 'VALUE_6',
        x4numint_0: 'VALUE_6',
        x4numdemand_0: 'VALUE_6',
        totnetwei_0: 'VALUE_6',
        cpy_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_6',
        credat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_6',
        betfcy_0: 'VALUE_6',
        bpocty_0: 'VALUE_6',
        bpocry_0: 'VALUE_6',
        bpoposcod_0: 'VALUE_6',
        tex2_0: 'VALUE_6',
        cur_0: 'VALUE_6',
        chgtyp_0: 'VALUE_6',
        bptnum_0: 'VALUE_6',
        linnbr_0: 'VALUE_6',
        seqvcr_0: 'VALUE_6',
        ycausrdes_0: 'VALUE_6',
        gpgcod_0: 'VALUE_6',
        rcpdat_0: new Date().toISOString().split('T')[0],
        bpaadd_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        bpsnde_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        vacbpr_0: 'VALUE_6',
        vou_0: 'VALUE_6',
        dspvou_0: 'VALUE_6',
        weu_0: 'VALUE_6',
        dspweu_0: 'VALUE_6',
        invdtavat1_0: 'VALUE_6',
        bpoadd_0: 'VALUE_6',
        bpoaddlig_0: 'VALUE_6',
        bpocrynam_0: 'VALUE_6',
        eecnum_0: 'VALUE_6',
        eecnumdeb_0: 'VALUE_6',
        invdtalin2_0: 'VALUE_6',
        eectrn_0: 'VALUE_6',
        bposat_0: 'VALUE_6',
        eecnat_0: 'VALUE_6',
        eecict_0: 'VALUE_6',
        pstdat_0: new Date().toISOString().split('T')[0],
        entcod_0: 'VALUE_6',
        purtyp_0: 'VALUE_6',
        invdtavat2_0: 'VALUE_6',
        bpapay_0: 'VALUE_6',
        typvcr_0: 'VALUE_6',
        licplate_0: 'VALUE_6',
        bponam_0: 'VALUE_6',
        dep_0: 'VALUE_6',
        tsscod_0: 'VALUE_6',
        totlinqty_0: 63.0,
        invdtalin1_0: 'VALUE_6',
        prhfcy_0: 'VALUE_6',
        pthnum_0: 'VALUE_6',
        invflg_0: 'VALUE_6',
        prnflg_0: 'VALUE_6',
      },
      {
        trllicplate_0: 'VALUE_7',
        x1wmssas_0: 'VALUE_7',
        arvdat_0: new Date().toISOString().split('T')[0],
        dpedat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        pstflg_0: 'VALUE_7',
        totamtati_0: 73.5,
        mdl_0: 'VALUE_7',
        pjth_0: 'VALUE_7',
        invlinnbr_0: 'VALUE_7',
        betcpy_0: 'VALUE_7',
        trscod_0: 'VALUE_7',
        eecsch_0: 'VALUE_7',
        chgcoe_0: 'VALUE_7',
        totvol_0: 'VALUE_7',
        clsvcr_0: 'VALUE_7',
        tex1_0: 'VALUE_7',
        x4sdhnum_0: 'PRE0007',
        die_0: 'VALUE_7',
        totamtatil_0: 73.5,
        totamtnotl_0: 73.5,
        auuid_0: 'VALUE_7',
        xblocage_0: 'VALUE_7',
        ffwadd_0: 'VALUE_7',
        bpsnum_0: 'VALUE_7',
        totlinweu_0: 'VALUE_7',
        totlinvou_0: 'VALUE_7',
        updusr_0: 'VALUE_7',
        eecloc_0: 'VALUE_7',
        ffwnum_0: 'VALUE_7',
        bpainv_0: 'VALUE_7',
        totamtnot_0: 73.5,
        ndedat_0: new Date().toISOString().split('T')[0],
        totgrowei_0: 'VALUE_7',
        vactyp_0: 'VALUE_7',
        xncflg_0: 'VALUE_7',
        cce_0: 'VALUE_7',
        etd_0: 'VALUE_7',
        eta_0: 'VALUE_7',
        pstlinnbr_0: 'VALUE_7',
        bpsinv_0: 'VALUE_7',
        totlinamt_0: 'Total HT lignes 7',
        tottaxamt_0: 73.5,
        cai_0: 'VALUE_7',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_7',
        scuvcr_0: 'VALUE_7',
        invlinctr_0: 'VALUE_7',
        x4numint_0: 'VALUE_7',
        x4numdemand_0: 'VALUE_7',
        totnetwei_0: 'VALUE_7',
        cpy_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_7',
        credat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_7',
        betfcy_0: 'VALUE_7',
        bpocty_0: 'VALUE_7',
        bpocry_0: 'VALUE_7',
        bpoposcod_0: 'VALUE_7',
        tex2_0: 'VALUE_7',
        cur_0: 'VALUE_7',
        chgtyp_0: 'VALUE_7',
        bptnum_0: 'VALUE_7',
        linnbr_0: 'VALUE_7',
        seqvcr_0: 'VALUE_7',
        ycausrdes_0: 'VALUE_7',
        gpgcod_0: 'VALUE_7',
        rcpdat_0: new Date().toISOString().split('T')[0],
        bpaadd_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        bpsnde_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        vacbpr_0: 'VALUE_7',
        vou_0: 'VALUE_7',
        dspvou_0: 'VALUE_7',
        weu_0: 'VALUE_7',
        dspweu_0: 'VALUE_7',
        invdtavat1_0: 'VALUE_7',
        bpoadd_0: 'VALUE_7',
        bpoaddlig_0: 'VALUE_7',
        bpocrynam_0: 'VALUE_7',
        eecnum_0: 'VALUE_7',
        eecnumdeb_0: 'VALUE_7',
        invdtalin2_0: 'VALUE_7',
        eectrn_0: 'VALUE_7',
        bposat_0: 'VALUE_7',
        eecnat_0: 'VALUE_7',
        eecict_0: 'VALUE_7',
        pstdat_0: new Date().toISOString().split('T')[0],
        entcod_0: 'VALUE_7',
        purtyp_0: 'VALUE_7',
        invdtavat2_0: 'VALUE_7',
        bpapay_0: 'VALUE_7',
        typvcr_0: 'VALUE_7',
        licplate_0: 'VALUE_7',
        bponam_0: 'VALUE_7',
        dep_0: 'VALUE_7',
        tsscod_0: 'VALUE_7',
        totlinqty_0: 73.5,
        invdtalin1_0: 'VALUE_7',
        prhfcy_0: 'VALUE_7',
        pthnum_0: 'VALUE_7',
        invflg_0: 'VALUE_7',
        prnflg_0: 'VALUE_7',
      },
      {
        trllicplate_0: 'VALUE_8',
        x1wmssas_0: 'VALUE_8',
        arvdat_0: new Date().toISOString().split('T')[0],
        dpedat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        pstflg_0: 'VALUE_8',
        totamtati_0: 84.0,
        mdl_0: 'VALUE_8',
        pjth_0: 'VALUE_8',
        invlinnbr_0: 'VALUE_8',
        betcpy_0: 'VALUE_8',
        trscod_0: 'VALUE_8',
        eecsch_0: 'VALUE_8',
        chgcoe_0: 'VALUE_8',
        totvol_0: 'VALUE_8',
        clsvcr_0: 'VALUE_8',
        tex1_0: 'VALUE_8',
        x4sdhnum_0: 'PRE0008',
        die_0: 'VALUE_8',
        totamtatil_0: 84.0,
        totamtnotl_0: 84.0,
        auuid_0: 'VALUE_8',
        xblocage_0: 'VALUE_8',
        ffwadd_0: 'VALUE_8',
        bpsnum_0: 'VALUE_8',
        totlinweu_0: 'VALUE_8',
        totlinvou_0: 'VALUE_8',
        updusr_0: 'VALUE_8',
        eecloc_0: 'VALUE_8',
        ffwnum_0: 'VALUE_8',
        bpainv_0: 'VALUE_8',
        totamtnot_0: 84.0,
        ndedat_0: new Date().toISOString().split('T')[0],
        totgrowei_0: 'VALUE_8',
        vactyp_0: 'VALUE_8',
        xncflg_0: 'VALUE_8',
        cce_0: 'VALUE_8',
        etd_0: 'VALUE_8',
        eta_0: 'VALUE_8',
        pstlinnbr_0: 'VALUE_8',
        bpsinv_0: 'VALUE_8',
        totlinamt_0: 'Total HT lignes 8',
        tottaxamt_0: 84.0,
        cai_0: 'VALUE_8',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_8',
        scuvcr_0: 'VALUE_8',
        invlinctr_0: 'VALUE_8',
        x4numint_0: 'VALUE_8',
        x4numdemand_0: 'VALUE_8',
        totnetwei_0: 'VALUE_8',
        cpy_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_8',
        credat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_8',
        betfcy_0: 'VALUE_8',
        bpocty_0: 'VALUE_8',
        bpocry_0: 'VALUE_8',
        bpoposcod_0: 'VALUE_8',
        tex2_0: 'VALUE_8',
        cur_0: 'VALUE_8',
        chgtyp_0: 'VALUE_8',
        bptnum_0: 'VALUE_8',
        linnbr_0: 'VALUE_8',
        seqvcr_0: 'VALUE_8',
        ycausrdes_0: 'VALUE_8',
        gpgcod_0: 'VALUE_8',
        rcpdat_0: new Date().toISOString().split('T')[0],
        bpaadd_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        bpsnde_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        vacbpr_0: 'VALUE_8',
        vou_0: 'VALUE_8',
        dspvou_0: 'VALUE_8',
        weu_0: 'VALUE_8',
        dspweu_0: 'VALUE_8',
        invdtavat1_0: 'VALUE_8',
        bpoadd_0: 'VALUE_8',
        bpoaddlig_0: 'VALUE_8',
        bpocrynam_0: 'VALUE_8',
        eecnum_0: 'VALUE_8',
        eecnumdeb_0: 'VALUE_8',
        invdtalin2_0: 'VALUE_8',
        eectrn_0: 'VALUE_8',
        bposat_0: 'VALUE_8',
        eecnat_0: 'VALUE_8',
        eecict_0: 'VALUE_8',
        pstdat_0: new Date().toISOString().split('T')[0],
        entcod_0: 'VALUE_8',
        purtyp_0: 'VALUE_8',
        invdtavat2_0: 'VALUE_8',
        bpapay_0: 'VALUE_8',
        typvcr_0: 'VALUE_8',
        licplate_0: 'VALUE_8',
        bponam_0: 'VALUE_8',
        dep_0: 'VALUE_8',
        tsscod_0: 'VALUE_8',
        totlinqty_0: 84.0,
        invdtalin1_0: 'VALUE_8',
        prhfcy_0: 'VALUE_8',
        pthnum_0: 'VALUE_8',
        invflg_0: 'VALUE_8',
        prnflg_0: 'VALUE_8',
      },
      {
        trllicplate_0: 'VALUE_9',
        x1wmssas_0: 'VALUE_9',
        arvdat_0: new Date().toISOString().split('T')[0],
        dpedat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        pstflg_0: 'VALUE_9',
        totamtati_0: 94.5,
        mdl_0: 'VALUE_9',
        pjth_0: 'VALUE_9',
        invlinnbr_0: 'VALUE_9',
        betcpy_0: 'VALUE_9',
        trscod_0: 'VALUE_9',
        eecsch_0: 'VALUE_9',
        chgcoe_0: 'VALUE_9',
        totvol_0: 'VALUE_9',
        clsvcr_0: 'VALUE_9',
        tex1_0: 'VALUE_9',
        x4sdhnum_0: 'PRE0009',
        die_0: 'VALUE_9',
        totamtatil_0: 94.5,
        totamtnotl_0: 94.5,
        auuid_0: 'VALUE_9',
        xblocage_0: 'VALUE_9',
        ffwadd_0: 'VALUE_9',
        bpsnum_0: 'VALUE_9',
        totlinweu_0: 'VALUE_9',
        totlinvou_0: 'VALUE_9',
        updusr_0: 'VALUE_9',
        eecloc_0: 'VALUE_9',
        ffwnum_0: 'VALUE_9',
        bpainv_0: 'VALUE_9',
        totamtnot_0: 94.5,
        ndedat_0: new Date().toISOString().split('T')[0],
        totgrowei_0: 'VALUE_9',
        vactyp_0: 'VALUE_9',
        xncflg_0: 'VALUE_9',
        cce_0: 'VALUE_9',
        etd_0: 'VALUE_9',
        eta_0: 'VALUE_9',
        pstlinnbr_0: 'VALUE_9',
        bpsinv_0: 'VALUE_9',
        totlinamt_0: 'Total HT lignes 9',
        tottaxamt_0: 94.5,
        cai_0: 'VALUE_9',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_9',
        scuvcr_0: 'VALUE_9',
        invlinctr_0: 'VALUE_9',
        x4numint_0: 'VALUE_9',
        x4numdemand_0: 'VALUE_9',
        totnetwei_0: 'VALUE_9',
        cpy_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_9',
        credat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_9',
        betfcy_0: 'VALUE_9',
        bpocty_0: 'VALUE_9',
        bpocry_0: 'VALUE_9',
        bpoposcod_0: 'VALUE_9',
        tex2_0: 'VALUE_9',
        cur_0: 'VALUE_9',
        chgtyp_0: 'VALUE_9',
        bptnum_0: 'VALUE_9',
        linnbr_0: 'VALUE_9',
        seqvcr_0: 'VALUE_9',
        ycausrdes_0: 'VALUE_9',
        gpgcod_0: 'VALUE_9',
        rcpdat_0: new Date().toISOString().split('T')[0],
        bpaadd_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        bpsnde_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        vacbpr_0: 'VALUE_9',
        vou_0: 'VALUE_9',
        dspvou_0: 'VALUE_9',
        weu_0: 'VALUE_9',
        dspweu_0: 'VALUE_9',
        invdtavat1_0: 'VALUE_9',
        bpoadd_0: 'VALUE_9',
        bpoaddlig_0: 'VALUE_9',
        bpocrynam_0: 'VALUE_9',
        eecnum_0: 'VALUE_9',
        eecnumdeb_0: 'VALUE_9',
        invdtalin2_0: 'VALUE_9',
        eectrn_0: 'VALUE_9',
        bposat_0: 'VALUE_9',
        eecnat_0: 'VALUE_9',
        eecict_0: 'VALUE_9',
        pstdat_0: new Date().toISOString().split('T')[0],
        entcod_0: 'VALUE_9',
        purtyp_0: 'VALUE_9',
        invdtavat2_0: 'VALUE_9',
        bpapay_0: 'VALUE_9',
        typvcr_0: 'VALUE_9',
        licplate_0: 'VALUE_9',
        bponam_0: 'VALUE_9',
        dep_0: 'VALUE_9',
        tsscod_0: 'VALUE_9',
        totlinqty_0: 94.5,
        invdtalin1_0: 'VALUE_9',
        prhfcy_0: 'VALUE_9',
        pthnum_0: 'VALUE_9',
        invflg_0: 'VALUE_9',
        prnflg_0: 'VALUE_9',
      },
      {
        trllicplate_0: 'VALUE_10',
        x1wmssas_0: 'VALUE_10',
        arvdat_0: new Date().toISOString().split('T')[0],
        dpedat_0: new Date().toISOString().split('T')[0],
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        pstflg_0: 'VALUE_10',
        totamtati_0: 105.0,
        mdl_0: 'VALUE_10',
        pjth_0: 'VALUE_10',
        invlinnbr_0: 'VALUE_10',
        betcpy_0: 'VALUE_10',
        trscod_0: 'VALUE_10',
        eecsch_0: 'VALUE_10',
        chgcoe_0: 'VALUE_10',
        totvol_0: 'VALUE_10',
        clsvcr_0: 'VALUE_10',
        tex1_0: 'VALUE_10',
        x4sdhnum_0: 'PRE0010',
        die_0: 'VALUE_10',
        totamtatil_0: 105.0,
        totamtnotl_0: 105.0,
        auuid_0: 'VALUE_10',
        xblocage_0: 'VALUE_10',
        ffwadd_0: 'VALUE_10',
        bpsnum_0: 'VALUE_10',
        totlinweu_0: 'VALUE_10',
        totlinvou_0: 'VALUE_10',
        updusr_0: 'VALUE_10',
        eecloc_0: 'VALUE_10',
        ffwnum_0: 'VALUE_10',
        bpainv_0: 'VALUE_10',
        totamtnot_0: 105.0,
        ndedat_0: new Date().toISOString().split('T')[0],
        totgrowei_0: 'VALUE_10',
        vactyp_0: 'VALUE_10',
        xncflg_0: 'VALUE_10',
        cce_0: 'VALUE_10',
        etd_0: 'VALUE_10',
        eta_0: 'VALUE_10',
        pstlinnbr_0: 'VALUE_10',
        bpsinv_0: 'VALUE_10',
        totlinamt_0: 'Total HT lignes 10',
        tottaxamt_0: 105.0,
        cai_0: 'VALUE_10',
        datvlycai_0: new Date().toISOString().split('T')[0],
        ictcty_0: 'VALUE_10',
        scuvcr_0: 'VALUE_10',
        invlinctr_0: 'VALUE_10',
        x4numint_0: 'VALUE_10',
        x4numdemand_0: 'VALUE_10',
        totnetwei_0: 'VALUE_10',
        cpy_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        bprpay_0: 'VALUE_10',
        credat_0: new Date().toISOString().split('T')[0],
        wrhe_0: 'VALUE_10',
        betfcy_0: 'VALUE_10',
        bpocty_0: 'VALUE_10',
        bpocry_0: 'VALUE_10',
        bpoposcod_0: 'VALUE_10',
        tex2_0: 'VALUE_10',
        cur_0: 'VALUE_10',
        chgtyp_0: 'VALUE_10',
        bptnum_0: 'VALUE_10',
        linnbr_0: 'VALUE_10',
        seqvcr_0: 'VALUE_10',
        ycausrdes_0: 'VALUE_10',
        gpgcod_0: 'VALUE_10',
        rcpdat_0: new Date().toISOString().split('T')[0],
        bpaadd_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        bpsnde_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        vacbpr_0: 'VALUE_10',
        vou_0: 'VALUE_10',
        dspvou_0: 'VALUE_10',
        weu_0: 'VALUE_10',
        dspweu_0: 'VALUE_10',
        invdtavat1_0: 'VALUE_10',
        bpoadd_0: 'VALUE_10',
        bpoaddlig_0: 'VALUE_10',
        bpocrynam_0: 'VALUE_10',
        eecnum_0: 'VALUE_10',
        eecnumdeb_0: 'VALUE_10',
        invdtalin2_0: 'VALUE_10',
        eectrn_0: 'VALUE_10',
        bposat_0: 'VALUE_10',
        eecnat_0: 'VALUE_10',
        eecict_0: 'VALUE_10',
        pstdat_0: new Date().toISOString().split('T')[0],
        entcod_0: 'VALUE_10',
        purtyp_0: 'VALUE_10',
        invdtavat2_0: 'VALUE_10',
        bpapay_0: 'VALUE_10',
        typvcr_0: 'VALUE_10',
        licplate_0: 'VALUE_10',
        bponam_0: 'VALUE_10',
        dep_0: 'VALUE_10',
        tsscod_0: 'VALUE_10',
        totlinqty_0: 105.0,
        invdtalin1_0: 'VALUE_10',
        prhfcy_0: 'VALUE_10',
        pthnum_0: 'VALUE_10',
        invflg_0: 'VALUE_10',
        prnflg_0: 'VALUE_10',
      },
    ]

    await Database.table('preceipt').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans preceipt`)
  }
}
