import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour PINVOICE
    const data = [
      {
        bpr_0: 'VALUE_1',
        oridocnum_0: 'PIN0001',
        eectrn_0: 'VALUE_1',
        sat_0: 'VALUE_1',
        ritinv_0: 'VALUE_1',
        accdat_0: new Date().toISOString().split('T')[0],
        eecnat_0: 'VALUE_1',
        eecict_0: 'VALUE_1',
        orimod_0: 'VALUE_1',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_1',
        pivtyp_0: 'VALUE_1',
        purtyp_0: 'VALUE_1',
        invtyp_0: 'VALUE_1',
        ritnbr_0: 'VALUE_1',
        ritcod_0: 'VALUE_1',
        ritbas_0: 'VALUE_1',
        ritamtded_0: 10.5,
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        bpapay_0: 'VALUE_1',
        bprnam_0: 'Raison sociale 1',
        deptyp_0: 'VALUE_1',
        des_0: 'VALUE_1',
        ritpay_0: 'VALUE_1',
        invref_0: 'VALUE_1',
        bpaaddlig_0: 'VALUE_1',
        crynam_0: 'VALUE_1',
        eecnum_0: 'VALUE_1',
        eecnumdeb_0: 'VALUE_1',
        paz_0: 'VALUE_1',
        amtnot_0: 10.5,
        amtati_0: 10.5,
        cce_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        fcy_0: 'VALUE_1',
        per_0: 'VALUE_1',
        cpy_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        tax_0: 'VALUE_1',
        sns_0: 'VALUE_1',
        pte_0: 'VALUE_1',
        cur_0: 'VALUE_1',
        bvrbid_0: 'VALUE_1',
        num_0: 'VALUE_1',
        gte_0: 'VALUE_1',
        bprsac_0: 'VALUE_1',
        ritamt_0: 10.5,
        jou_0: 'VALUE_1',
        cty_0: 'VALUE_1',
        cry_0: 'VALUE_1',
        vac_0: 'VALUE_1',
        bprpay_0: 'VALUE_1',
        invnum_0: 'VALUE_1',
        nbrtax_0: 'VALUE_1',
        amttax_0: 10.5,
        bastax_0: 1,
        poscod_0: 'VALUE_1',
        updusr_0: 'VALUE_1',
        dedtax_0: 'VALUE_1',
        ceeflg_0: 'VALUE_1',
        cai_0: 'VALUE_1',
        datvlycai_0: new Date().toISOString().split('T')[0],
        typvcr_0: 'VALUE_1',
        clsvcr_0: 'VALUE_1',
        scuvcr_0: 'VALUE_1',
        seqvcr_0: 'VALUE_1',
        ictcty_0: 'VALUE_1',
        ffwadd_0: 'VALUE_1',
        dep_0: 'VALUE_1',
        eecloc_0: 'VALUE_1',
        ffwnum_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        bpainv_0: 'VALUE_1',
        pihtyp_0: 'VALUE_1',
        eecsch_0: 'VALUE_1',
        ratdat_0: new Date().toISOString().split('T')[0],
        fiy_0: 'VALUE_1',
        bprvcr_0: 'VALUE_1',
        strduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_1',
        xncflg_0: 'VALUE_1',
        bpycry_0: 'VALUE_1',
        bpycrynam_0: 'VALUE_1',
        nbrcpy_0: 'VALUE_1',
        led_0: 'VALUE_1',
        ublusr_0: 'VALUE_1',
        ubldat_0: new Date().toISOString().split('T')[0],
        ublamt_0: 10.5,
        twmsta_0: 1,
        xmotlit_0: 'VALUE_1',
        frm1099_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        deprat_0: 'VALUE_1',
        xrespli_0: 'VALUE_1',
        belvcs_0: 'VALUE_1',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_1',
        purprityp_0: 10.5,
        spadernum_0: 'VALUE_1',
        fld40ren_0: 'VALUE_1',
        fld41ren_0: 'VALUE_1',
        cshvat_0: 'VALUE_1',
        ratdiv_0: 'VALUE_1',
        ratmlt_0: 'VALUE_1',
        sinum_0: 'VALUE_1',
        die_0: 'VALUE_1',
        curled_0: 'VALUE_1',
        pjth_0: 'VALUE_1',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 10.5,
        amtatil_0: 10.5,
        ritbasded_0: 'VALUE_1',
        x4payyooz_0: 'VALUE_1',
        x4stayooz_0: 1,
        x4debpaz_0: 'VALUE_1',
        x4lnkyooz_0: 'VALUE_1',
        x4paysta_0: 1,
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        basdep_0: 'VALUE_1',
        porimpliqnum_0: 'VALUE_1',
        spacusdat_0: new Date().toISOString().split('T')[0],
        spacus_0: 'VALUE_1',
        spacusbpr_0: 'VALUE_1',
        box1099_0: 'VALUE_1',
        das2_0: 'VALUE_1',
        amtsubj1099_0: 10.5,
        bvrrefline_0: 'VALUE_1',
        bpynam_0: 'VALUE_1',
        bpyaddlig_0: 'VALUE_1',
        bpyposcod_0: 'VALUE_1',
        bpycty_0: 'VALUE_1',
        bpysat_0: 'VALUE_1',
      },
      {
        bpr_0: 'VALUE_2',
        oridocnum_0: 'PIN0002',
        eectrn_0: 'VALUE_2',
        sat_0: 'VALUE_2',
        ritinv_0: 'VALUE_2',
        accdat_0: new Date().toISOString().split('T')[0],
        eecnat_0: 'VALUE_2',
        eecict_0: 'VALUE_2',
        orimod_0: 'VALUE_2',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_2',
        pivtyp_0: 'VALUE_2',
        purtyp_0: 'VALUE_2',
        invtyp_0: 'VALUE_2',
        ritnbr_0: 'VALUE_2',
        ritcod_0: 'VALUE_2',
        ritbas_0: 'VALUE_2',
        ritamtded_0: 21.0,
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        bpapay_0: 'VALUE_2',
        bprnam_0: 'Raison sociale 2',
        deptyp_0: 'VALUE_2',
        des_0: 'VALUE_2',
        ritpay_0: 'VALUE_2',
        invref_0: 'VALUE_2',
        bpaaddlig_0: 'VALUE_2',
        crynam_0: 'VALUE_2',
        eecnum_0: 'VALUE_2',
        eecnumdeb_0: 'VALUE_2',
        paz_0: 'VALUE_2',
        amtnot_0: 21.0,
        amtati_0: 21.0,
        cce_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        fcy_0: 'VALUE_2',
        per_0: 'VALUE_2',
        cpy_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        tax_0: 'VALUE_2',
        sns_0: 'VALUE_2',
        pte_0: 'VALUE_2',
        cur_0: 'VALUE_2',
        bvrbid_0: 'VALUE_2',
        num_0: 'VALUE_2',
        gte_0: 'VALUE_2',
        bprsac_0: 'VALUE_2',
        ritamt_0: 21.0,
        jou_0: 'VALUE_2',
        cty_0: 'VALUE_2',
        cry_0: 'VALUE_2',
        vac_0: 'VALUE_2',
        bprpay_0: 'VALUE_2',
        invnum_0: 'VALUE_2',
        nbrtax_0: 'VALUE_2',
        amttax_0: 21.0,
        bastax_0: 2,
        poscod_0: 'VALUE_2',
        updusr_0: 'VALUE_2',
        dedtax_0: 'VALUE_2',
        ceeflg_0: 'VALUE_2',
        cai_0: 'VALUE_2',
        datvlycai_0: new Date().toISOString().split('T')[0],
        typvcr_0: 'VALUE_2',
        clsvcr_0: 'VALUE_2',
        scuvcr_0: 'VALUE_2',
        seqvcr_0: 'VALUE_2',
        ictcty_0: 'VALUE_2',
        ffwadd_0: 'VALUE_2',
        dep_0: 'VALUE_2',
        eecloc_0: 'VALUE_2',
        ffwnum_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        bpainv_0: 'VALUE_2',
        pihtyp_0: 'VALUE_2',
        eecsch_0: 'VALUE_2',
        ratdat_0: new Date().toISOString().split('T')[0],
        fiy_0: 'VALUE_2',
        bprvcr_0: 'VALUE_2',
        strduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_2',
        xncflg_0: 'VALUE_2',
        bpycry_0: 'VALUE_2',
        bpycrynam_0: 'VALUE_2',
        nbrcpy_0: 'VALUE_2',
        led_0: 'VALUE_2',
        ublusr_0: 'VALUE_2',
        ubldat_0: new Date().toISOString().split('T')[0],
        ublamt_0: 21.0,
        twmsta_0: 2,
        xmotlit_0: 'VALUE_2',
        frm1099_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        deprat_0: 'VALUE_2',
        xrespli_0: 'VALUE_2',
        belvcs_0: 'VALUE_2',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_2',
        purprityp_0: 21.0,
        spadernum_0: 'VALUE_2',
        fld40ren_0: 'VALUE_2',
        fld41ren_0: 'VALUE_2',
        cshvat_0: 'VALUE_2',
        ratdiv_0: 'VALUE_2',
        ratmlt_0: 'VALUE_2',
        sinum_0: 'VALUE_2',
        die_0: 'VALUE_2',
        curled_0: 'VALUE_2',
        pjth_0: 'VALUE_2',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 21.0,
        amtatil_0: 21.0,
        ritbasded_0: 'VALUE_2',
        x4payyooz_0: 'VALUE_2',
        x4stayooz_0: 2,
        x4debpaz_0: 'VALUE_2',
        x4lnkyooz_0: 'VALUE_2',
        x4paysta_0: 2,
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        basdep_0: 'VALUE_2',
        porimpliqnum_0: 'VALUE_2',
        spacusdat_0: new Date().toISOString().split('T')[0],
        spacus_0: 'VALUE_2',
        spacusbpr_0: 'VALUE_2',
        box1099_0: 'VALUE_2',
        das2_0: 'VALUE_2',
        amtsubj1099_0: 21.0,
        bvrrefline_0: 'VALUE_2',
        bpynam_0: 'VALUE_2',
        bpyaddlig_0: 'VALUE_2',
        bpyposcod_0: 'VALUE_2',
        bpycty_0: 'VALUE_2',
        bpysat_0: 'VALUE_2',
      },
      {
        bpr_0: 'VALUE_3',
        oridocnum_0: 'PIN0003',
        eectrn_0: 'VALUE_3',
        sat_0: 'VALUE_3',
        ritinv_0: 'VALUE_3',
        accdat_0: new Date().toISOString().split('T')[0],
        eecnat_0: 'VALUE_3',
        eecict_0: 'VALUE_3',
        orimod_0: 'VALUE_3',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_3',
        pivtyp_0: 'VALUE_3',
        purtyp_0: 'VALUE_3',
        invtyp_0: 'VALUE_3',
        ritnbr_0: 'VALUE_3',
        ritcod_0: 'VALUE_3',
        ritbas_0: 'VALUE_3',
        ritamtded_0: 31.5,
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        bpapay_0: 'VALUE_3',
        bprnam_0: 'Raison sociale 3',
        deptyp_0: 'VALUE_3',
        des_0: 'VALUE_3',
        ritpay_0: 'VALUE_3',
        invref_0: 'VALUE_3',
        bpaaddlig_0: 'VALUE_3',
        crynam_0: 'VALUE_3',
        eecnum_0: 'VALUE_3',
        eecnumdeb_0: 'VALUE_3',
        paz_0: 'VALUE_3',
        amtnot_0: 31.5,
        amtati_0: 31.5,
        cce_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        fcy_0: 'VALUE_3',
        per_0: 'VALUE_3',
        cpy_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        tax_0: 'VALUE_3',
        sns_0: 'VALUE_3',
        pte_0: 'VALUE_3',
        cur_0: 'VALUE_3',
        bvrbid_0: 'VALUE_3',
        num_0: 'VALUE_3',
        gte_0: 'VALUE_3',
        bprsac_0: 'VALUE_3',
        ritamt_0: 31.5,
        jou_0: 'VALUE_3',
        cty_0: 'VALUE_3',
        cry_0: 'VALUE_3',
        vac_0: 'VALUE_3',
        bprpay_0: 'VALUE_3',
        invnum_0: 'VALUE_3',
        nbrtax_0: 'VALUE_3',
        amttax_0: 31.5,
        bastax_0: 3,
        poscod_0: 'VALUE_3',
        updusr_0: 'VALUE_3',
        dedtax_0: 'VALUE_3',
        ceeflg_0: 'VALUE_3',
        cai_0: 'VALUE_3',
        datvlycai_0: new Date().toISOString().split('T')[0],
        typvcr_0: 'VALUE_3',
        clsvcr_0: 'VALUE_3',
        scuvcr_0: 'VALUE_3',
        seqvcr_0: 'VALUE_3',
        ictcty_0: 'VALUE_3',
        ffwadd_0: 'VALUE_3',
        dep_0: 'VALUE_3',
        eecloc_0: 'VALUE_3',
        ffwnum_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        bpainv_0: 'VALUE_3',
        pihtyp_0: 'VALUE_3',
        eecsch_0: 'VALUE_3',
        ratdat_0: new Date().toISOString().split('T')[0],
        fiy_0: 'VALUE_3',
        bprvcr_0: 'VALUE_3',
        strduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_3',
        xncflg_0: 'VALUE_3',
        bpycry_0: 'VALUE_3',
        bpycrynam_0: 'VALUE_3',
        nbrcpy_0: 'VALUE_3',
        led_0: 'VALUE_3',
        ublusr_0: 'VALUE_3',
        ubldat_0: new Date().toISOString().split('T')[0],
        ublamt_0: 31.5,
        twmsta_0: 3,
        xmotlit_0: 'VALUE_3',
        frm1099_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        deprat_0: 'VALUE_3',
        xrespli_0: 'VALUE_3',
        belvcs_0: 'VALUE_3',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_3',
        purprityp_0: 31.5,
        spadernum_0: 'VALUE_3',
        fld40ren_0: 'VALUE_3',
        fld41ren_0: 'VALUE_3',
        cshvat_0: 'VALUE_3',
        ratdiv_0: 'VALUE_3',
        ratmlt_0: 'VALUE_3',
        sinum_0: 'VALUE_3',
        die_0: 'VALUE_3',
        curled_0: 'VALUE_3',
        pjth_0: 'VALUE_3',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 31.5,
        amtatil_0: 31.5,
        ritbasded_0: 'VALUE_3',
        x4payyooz_0: 'VALUE_3',
        x4stayooz_0: 3,
        x4debpaz_0: 'VALUE_3',
        x4lnkyooz_0: 'VALUE_3',
        x4paysta_0: 3,
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        basdep_0: 'VALUE_3',
        porimpliqnum_0: 'VALUE_3',
        spacusdat_0: new Date().toISOString().split('T')[0],
        spacus_0: 'VALUE_3',
        spacusbpr_0: 'VALUE_3',
        box1099_0: 'VALUE_3',
        das2_0: 'VALUE_3',
        amtsubj1099_0: 31.5,
        bvrrefline_0: 'VALUE_3',
        bpynam_0: 'VALUE_3',
        bpyaddlig_0: 'VALUE_3',
        bpyposcod_0: 'VALUE_3',
        bpycty_0: 'VALUE_3',
        bpysat_0: 'VALUE_3',
      },
      {
        bpr_0: 'VALUE_4',
        oridocnum_0: 'PIN0004',
        eectrn_0: 'VALUE_4',
        sat_0: 'VALUE_4',
        ritinv_0: 'VALUE_4',
        accdat_0: new Date().toISOString().split('T')[0],
        eecnat_0: 'VALUE_4',
        eecict_0: 'VALUE_4',
        orimod_0: 'VALUE_4',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_4',
        pivtyp_0: 'VALUE_4',
        purtyp_0: 'VALUE_4',
        invtyp_0: 'VALUE_4',
        ritnbr_0: 'VALUE_4',
        ritcod_0: 'VALUE_4',
        ritbas_0: 'VALUE_4',
        ritamtded_0: 42.0,
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        bpapay_0: 'VALUE_4',
        bprnam_0: 'Raison sociale 4',
        deptyp_0: 'VALUE_4',
        des_0: 'VALUE_4',
        ritpay_0: 'VALUE_4',
        invref_0: 'VALUE_4',
        bpaaddlig_0: 'VALUE_4',
        crynam_0: 'VALUE_4',
        eecnum_0: 'VALUE_4',
        eecnumdeb_0: 'VALUE_4',
        paz_0: 'VALUE_4',
        amtnot_0: 42.0,
        amtati_0: 42.0,
        cce_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        fcy_0: 'VALUE_4',
        per_0: 'VALUE_4',
        cpy_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        tax_0: 'VALUE_4',
        sns_0: 'VALUE_4',
        pte_0: 'VALUE_4',
        cur_0: 'VALUE_4',
        bvrbid_0: 'VALUE_4',
        num_0: 'VALUE_4',
        gte_0: 'VALUE_4',
        bprsac_0: 'VALUE_4',
        ritamt_0: 42.0,
        jou_0: 'VALUE_4',
        cty_0: 'VALUE_4',
        cry_0: 'VALUE_4',
        vac_0: 'VALUE_4',
        bprpay_0: 'VALUE_4',
        invnum_0: 'VALUE_4',
        nbrtax_0: 'VALUE_4',
        amttax_0: 42.0,
        bastax_0: 4,
        poscod_0: 'VALUE_4',
        updusr_0: 'VALUE_4',
        dedtax_0: 'VALUE_4',
        ceeflg_0: 'VALUE_4',
        cai_0: 'VALUE_4',
        datvlycai_0: new Date().toISOString().split('T')[0],
        typvcr_0: 'VALUE_4',
        clsvcr_0: 'VALUE_4',
        scuvcr_0: 'VALUE_4',
        seqvcr_0: 'VALUE_4',
        ictcty_0: 'VALUE_4',
        ffwadd_0: 'VALUE_4',
        dep_0: 'VALUE_4',
        eecloc_0: 'VALUE_4',
        ffwnum_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        bpainv_0: 'VALUE_4',
        pihtyp_0: 'VALUE_4',
        eecsch_0: 'VALUE_4',
        ratdat_0: new Date().toISOString().split('T')[0],
        fiy_0: 'VALUE_4',
        bprvcr_0: 'VALUE_4',
        strduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_4',
        xncflg_0: 'VALUE_4',
        bpycry_0: 'VALUE_4',
        bpycrynam_0: 'VALUE_4',
        nbrcpy_0: 'VALUE_4',
        led_0: 'VALUE_4',
        ublusr_0: 'VALUE_4',
        ubldat_0: new Date().toISOString().split('T')[0],
        ublamt_0: 42.0,
        twmsta_0: 4,
        xmotlit_0: 'VALUE_4',
        frm1099_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        deprat_0: 'VALUE_4',
        xrespli_0: 'VALUE_4',
        belvcs_0: 'VALUE_4',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_4',
        purprityp_0: 42.0,
        spadernum_0: 'VALUE_4',
        fld40ren_0: 'VALUE_4',
        fld41ren_0: 'VALUE_4',
        cshvat_0: 'VALUE_4',
        ratdiv_0: 'VALUE_4',
        ratmlt_0: 'VALUE_4',
        sinum_0: 'VALUE_4',
        die_0: 'VALUE_4',
        curled_0: 'VALUE_4',
        pjth_0: 'VALUE_4',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 42.0,
        amtatil_0: 42.0,
        ritbasded_0: 'VALUE_4',
        x4payyooz_0: 'VALUE_4',
        x4stayooz_0: 4,
        x4debpaz_0: 'VALUE_4',
        x4lnkyooz_0: 'VALUE_4',
        x4paysta_0: 4,
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        basdep_0: 'VALUE_4',
        porimpliqnum_0: 'VALUE_4',
        spacusdat_0: new Date().toISOString().split('T')[0],
        spacus_0: 'VALUE_4',
        spacusbpr_0: 'VALUE_4',
        box1099_0: 'VALUE_4',
        das2_0: 'VALUE_4',
        amtsubj1099_0: 42.0,
        bvrrefline_0: 'VALUE_4',
        bpynam_0: 'VALUE_4',
        bpyaddlig_0: 'VALUE_4',
        bpyposcod_0: 'VALUE_4',
        bpycty_0: 'VALUE_4',
        bpysat_0: 'VALUE_4',
      },
      {
        bpr_0: 'VALUE_5',
        oridocnum_0: 'PIN0005',
        eectrn_0: 'VALUE_5',
        sat_0: 'VALUE_5',
        ritinv_0: 'VALUE_5',
        accdat_0: new Date().toISOString().split('T')[0],
        eecnat_0: 'VALUE_5',
        eecict_0: 'VALUE_5',
        orimod_0: 'VALUE_5',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_5',
        pivtyp_0: 'VALUE_5',
        purtyp_0: 'VALUE_5',
        invtyp_0: 'VALUE_5',
        ritnbr_0: 'VALUE_5',
        ritcod_0: 'VALUE_5',
        ritbas_0: 'VALUE_5',
        ritamtded_0: 52.5,
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        bpapay_0: 'VALUE_5',
        bprnam_0: 'Raison sociale 5',
        deptyp_0: 'VALUE_5',
        des_0: 'VALUE_5',
        ritpay_0: 'VALUE_5',
        invref_0: 'VALUE_5',
        bpaaddlig_0: 'VALUE_5',
        crynam_0: 'VALUE_5',
        eecnum_0: 'VALUE_5',
        eecnumdeb_0: 'VALUE_5',
        paz_0: 'VALUE_5',
        amtnot_0: 52.5,
        amtati_0: 52.5,
        cce_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        fcy_0: 'VALUE_5',
        per_0: 'VALUE_5',
        cpy_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        tax_0: 'VALUE_5',
        sns_0: 'VALUE_5',
        pte_0: 'VALUE_5',
        cur_0: 'VALUE_5',
        bvrbid_0: 'VALUE_5',
        num_0: 'VALUE_5',
        gte_0: 'VALUE_5',
        bprsac_0: 'VALUE_5',
        ritamt_0: 52.5,
        jou_0: 'VALUE_5',
        cty_0: 'VALUE_5',
        cry_0: 'VALUE_5',
        vac_0: 'VALUE_5',
        bprpay_0: 'VALUE_5',
        invnum_0: 'VALUE_5',
        nbrtax_0: 'VALUE_5',
        amttax_0: 52.5,
        bastax_0: 5,
        poscod_0: 'VALUE_5',
        updusr_0: 'VALUE_5',
        dedtax_0: 'VALUE_5',
        ceeflg_0: 'VALUE_5',
        cai_0: 'VALUE_5',
        datvlycai_0: new Date().toISOString().split('T')[0],
        typvcr_0: 'VALUE_5',
        clsvcr_0: 'VALUE_5',
        scuvcr_0: 'VALUE_5',
        seqvcr_0: 'VALUE_5',
        ictcty_0: 'VALUE_5',
        ffwadd_0: 'VALUE_5',
        dep_0: 'VALUE_5',
        eecloc_0: 'VALUE_5',
        ffwnum_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        bpainv_0: 'VALUE_5',
        pihtyp_0: 'VALUE_5',
        eecsch_0: 'VALUE_5',
        ratdat_0: new Date().toISOString().split('T')[0],
        fiy_0: 'VALUE_5',
        bprvcr_0: 'VALUE_5',
        strduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_5',
        xncflg_0: 'VALUE_5',
        bpycry_0: 'VALUE_5',
        bpycrynam_0: 'VALUE_5',
        nbrcpy_0: 'VALUE_5',
        led_0: 'VALUE_5',
        ublusr_0: 'VALUE_5',
        ubldat_0: new Date().toISOString().split('T')[0],
        ublamt_0: 52.5,
        twmsta_0: 5,
        xmotlit_0: 'VALUE_5',
        frm1099_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        deprat_0: 'VALUE_5',
        xrespli_0: 'VALUE_5',
        belvcs_0: 'VALUE_5',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_5',
        purprityp_0: 52.5,
        spadernum_0: 'VALUE_5',
        fld40ren_0: 'VALUE_5',
        fld41ren_0: 'VALUE_5',
        cshvat_0: 'VALUE_5',
        ratdiv_0: 'VALUE_5',
        ratmlt_0: 'VALUE_5',
        sinum_0: 'VALUE_5',
        die_0: 'VALUE_5',
        curled_0: 'VALUE_5',
        pjth_0: 'VALUE_5',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 52.5,
        amtatil_0: 52.5,
        ritbasded_0: 'VALUE_5',
        x4payyooz_0: 'VALUE_5',
        x4stayooz_0: 5,
        x4debpaz_0: 'VALUE_5',
        x4lnkyooz_0: 'VALUE_5',
        x4paysta_0: 5,
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        basdep_0: 'VALUE_5',
        porimpliqnum_0: 'VALUE_5',
        spacusdat_0: new Date().toISOString().split('T')[0],
        spacus_0: 'VALUE_5',
        spacusbpr_0: 'VALUE_5',
        box1099_0: 'VALUE_5',
        das2_0: 'VALUE_5',
        amtsubj1099_0: 52.5,
        bvrrefline_0: 'VALUE_5',
        bpynam_0: 'VALUE_5',
        bpyaddlig_0: 'VALUE_5',
        bpyposcod_0: 'VALUE_5',
        bpycty_0: 'VALUE_5',
        bpysat_0: 'VALUE_5',
      },
      {
        bpr_0: 'VALUE_6',
        oridocnum_0: 'PIN0006',
        eectrn_0: 'VALUE_6',
        sat_0: 'VALUE_6',
        ritinv_0: 'VALUE_6',
        accdat_0: new Date().toISOString().split('T')[0],
        eecnat_0: 'VALUE_6',
        eecict_0: 'VALUE_6',
        orimod_0: 'VALUE_6',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_6',
        pivtyp_0: 'VALUE_6',
        purtyp_0: 'VALUE_6',
        invtyp_0: 'VALUE_6',
        ritnbr_0: 'VALUE_6',
        ritcod_0: 'VALUE_6',
        ritbas_0: 'VALUE_6',
        ritamtded_0: 63.0,
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        bpapay_0: 'VALUE_6',
        bprnam_0: 'Raison sociale 6',
        deptyp_0: 'VALUE_6',
        des_0: 'VALUE_6',
        ritpay_0: 'VALUE_6',
        invref_0: 'VALUE_6',
        bpaaddlig_0: 'VALUE_6',
        crynam_0: 'VALUE_6',
        eecnum_0: 'VALUE_6',
        eecnumdeb_0: 'VALUE_6',
        paz_0: 'VALUE_6',
        amtnot_0: 63.0,
        amtati_0: 63.0,
        cce_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        fcy_0: 'VALUE_6',
        per_0: 'VALUE_6',
        cpy_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        tax_0: 'VALUE_6',
        sns_0: 'VALUE_6',
        pte_0: 'VALUE_6',
        cur_0: 'VALUE_6',
        bvrbid_0: 'VALUE_6',
        num_0: 'VALUE_6',
        gte_0: 'VALUE_6',
        bprsac_0: 'VALUE_6',
        ritamt_0: 63.0,
        jou_0: 'VALUE_6',
        cty_0: 'VALUE_6',
        cry_0: 'VALUE_6',
        vac_0: 'VALUE_6',
        bprpay_0: 'VALUE_6',
        invnum_0: 'VALUE_6',
        nbrtax_0: 'VALUE_6',
        amttax_0: 63.0,
        bastax_0: 6,
        poscod_0: 'VALUE_6',
        updusr_0: 'VALUE_6',
        dedtax_0: 'VALUE_6',
        ceeflg_0: 'VALUE_6',
        cai_0: 'VALUE_6',
        datvlycai_0: new Date().toISOString().split('T')[0],
        typvcr_0: 'VALUE_6',
        clsvcr_0: 'VALUE_6',
        scuvcr_0: 'VALUE_6',
        seqvcr_0: 'VALUE_6',
        ictcty_0: 'VALUE_6',
        ffwadd_0: 'VALUE_6',
        dep_0: 'VALUE_6',
        eecloc_0: 'VALUE_6',
        ffwnum_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        bpainv_0: 'VALUE_6',
        pihtyp_0: 'VALUE_6',
        eecsch_0: 'VALUE_6',
        ratdat_0: new Date().toISOString().split('T')[0],
        fiy_0: 'VALUE_6',
        bprvcr_0: 'VALUE_6',
        strduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_6',
        xncflg_0: 'VALUE_6',
        bpycry_0: 'VALUE_6',
        bpycrynam_0: 'VALUE_6',
        nbrcpy_0: 'VALUE_6',
        led_0: 'VALUE_6',
        ublusr_0: 'VALUE_6',
        ubldat_0: new Date().toISOString().split('T')[0],
        ublamt_0: 63.0,
        twmsta_0: 6,
        xmotlit_0: 'VALUE_6',
        frm1099_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        deprat_0: 'VALUE_6',
        xrespli_0: 'VALUE_6',
        belvcs_0: 'VALUE_6',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_6',
        purprityp_0: 63.0,
        spadernum_0: 'VALUE_6',
        fld40ren_0: 'VALUE_6',
        fld41ren_0: 'VALUE_6',
        cshvat_0: 'VALUE_6',
        ratdiv_0: 'VALUE_6',
        ratmlt_0: 'VALUE_6',
        sinum_0: 'VALUE_6',
        die_0: 'VALUE_6',
        curled_0: 'VALUE_6',
        pjth_0: 'VALUE_6',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 63.0,
        amtatil_0: 63.0,
        ritbasded_0: 'VALUE_6',
        x4payyooz_0: 'VALUE_6',
        x4stayooz_0: 6,
        x4debpaz_0: 'VALUE_6',
        x4lnkyooz_0: 'VALUE_6',
        x4paysta_0: 6,
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        basdep_0: 'VALUE_6',
        porimpliqnum_0: 'VALUE_6',
        spacusdat_0: new Date().toISOString().split('T')[0],
        spacus_0: 'VALUE_6',
        spacusbpr_0: 'VALUE_6',
        box1099_0: 'VALUE_6',
        das2_0: 'VALUE_6',
        amtsubj1099_0: 63.0,
        bvrrefline_0: 'VALUE_6',
        bpynam_0: 'VALUE_6',
        bpyaddlig_0: 'VALUE_6',
        bpyposcod_0: 'VALUE_6',
        bpycty_0: 'VALUE_6',
        bpysat_0: 'VALUE_6',
      },
      {
        bpr_0: 'VALUE_7',
        oridocnum_0: 'PIN0007',
        eectrn_0: 'VALUE_7',
        sat_0: 'VALUE_7',
        ritinv_0: 'VALUE_7',
        accdat_0: new Date().toISOString().split('T')[0],
        eecnat_0: 'VALUE_7',
        eecict_0: 'VALUE_7',
        orimod_0: 'VALUE_7',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_7',
        pivtyp_0: 'VALUE_7',
        purtyp_0: 'VALUE_7',
        invtyp_0: 'VALUE_7',
        ritnbr_0: 'VALUE_7',
        ritcod_0: 'VALUE_7',
        ritbas_0: 'VALUE_7',
        ritamtded_0: 73.5,
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        bpapay_0: 'VALUE_7',
        bprnam_0: 'Raison sociale 7',
        deptyp_0: 'VALUE_7',
        des_0: 'VALUE_7',
        ritpay_0: 'VALUE_7',
        invref_0: 'VALUE_7',
        bpaaddlig_0: 'VALUE_7',
        crynam_0: 'VALUE_7',
        eecnum_0: 'VALUE_7',
        eecnumdeb_0: 'VALUE_7',
        paz_0: 'VALUE_7',
        amtnot_0: 73.5,
        amtati_0: 73.5,
        cce_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        fcy_0: 'VALUE_7',
        per_0: 'VALUE_7',
        cpy_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        tax_0: 'VALUE_7',
        sns_0: 'VALUE_7',
        pte_0: 'VALUE_7',
        cur_0: 'VALUE_7',
        bvrbid_0: 'VALUE_7',
        num_0: 'VALUE_7',
        gte_0: 'VALUE_7',
        bprsac_0: 'VALUE_7',
        ritamt_0: 73.5,
        jou_0: 'VALUE_7',
        cty_0: 'VALUE_7',
        cry_0: 'VALUE_7',
        vac_0: 'VALUE_7',
        bprpay_0: 'VALUE_7',
        invnum_0: 'VALUE_7',
        nbrtax_0: 'VALUE_7',
        amttax_0: 73.5,
        bastax_0: 7,
        poscod_0: 'VALUE_7',
        updusr_0: 'VALUE_7',
        dedtax_0: 'VALUE_7',
        ceeflg_0: 'VALUE_7',
        cai_0: 'VALUE_7',
        datvlycai_0: new Date().toISOString().split('T')[0],
        typvcr_0: 'VALUE_7',
        clsvcr_0: 'VALUE_7',
        scuvcr_0: 'VALUE_7',
        seqvcr_0: 'VALUE_7',
        ictcty_0: 'VALUE_7',
        ffwadd_0: 'VALUE_7',
        dep_0: 'VALUE_7',
        eecloc_0: 'VALUE_7',
        ffwnum_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        bpainv_0: 'VALUE_7',
        pihtyp_0: 'VALUE_7',
        eecsch_0: 'VALUE_7',
        ratdat_0: new Date().toISOString().split('T')[0],
        fiy_0: 'VALUE_7',
        bprvcr_0: 'VALUE_7',
        strduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_7',
        xncflg_0: 'VALUE_7',
        bpycry_0: 'VALUE_7',
        bpycrynam_0: 'VALUE_7',
        nbrcpy_0: 'VALUE_7',
        led_0: 'VALUE_7',
        ublusr_0: 'VALUE_7',
        ubldat_0: new Date().toISOString().split('T')[0],
        ublamt_0: 73.5,
        twmsta_0: 7,
        xmotlit_0: 'VALUE_7',
        frm1099_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        deprat_0: 'VALUE_7',
        xrespli_0: 'VALUE_7',
        belvcs_0: 'VALUE_7',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_7',
        purprityp_0: 73.5,
        spadernum_0: 'VALUE_7',
        fld40ren_0: 'VALUE_7',
        fld41ren_0: 'VALUE_7',
        cshvat_0: 'VALUE_7',
        ratdiv_0: 'VALUE_7',
        ratmlt_0: 'VALUE_7',
        sinum_0: 'VALUE_7',
        die_0: 'VALUE_7',
        curled_0: 'VALUE_7',
        pjth_0: 'VALUE_7',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 73.5,
        amtatil_0: 73.5,
        ritbasded_0: 'VALUE_7',
        x4payyooz_0: 'VALUE_7',
        x4stayooz_0: 7,
        x4debpaz_0: 'VALUE_7',
        x4lnkyooz_0: 'VALUE_7',
        x4paysta_0: 7,
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        basdep_0: 'VALUE_7',
        porimpliqnum_0: 'VALUE_7',
        spacusdat_0: new Date().toISOString().split('T')[0],
        spacus_0: 'VALUE_7',
        spacusbpr_0: 'VALUE_7',
        box1099_0: 'VALUE_7',
        das2_0: 'VALUE_7',
        amtsubj1099_0: 73.5,
        bvrrefline_0: 'VALUE_7',
        bpynam_0: 'VALUE_7',
        bpyaddlig_0: 'VALUE_7',
        bpyposcod_0: 'VALUE_7',
        bpycty_0: 'VALUE_7',
        bpysat_0: 'VALUE_7',
      },
      {
        bpr_0: 'VALUE_8',
        oridocnum_0: 'PIN0008',
        eectrn_0: 'VALUE_8',
        sat_0: 'VALUE_8',
        ritinv_0: 'VALUE_8',
        accdat_0: new Date().toISOString().split('T')[0],
        eecnat_0: 'VALUE_8',
        eecict_0: 'VALUE_8',
        orimod_0: 'VALUE_8',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_8',
        pivtyp_0: 'VALUE_8',
        purtyp_0: 'VALUE_8',
        invtyp_0: 'VALUE_8',
        ritnbr_0: 'VALUE_8',
        ritcod_0: 'VALUE_8',
        ritbas_0: 'VALUE_8',
        ritamtded_0: 84.0,
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        bpapay_0: 'VALUE_8',
        bprnam_0: 'Raison sociale 8',
        deptyp_0: 'VALUE_8',
        des_0: 'VALUE_8',
        ritpay_0: 'VALUE_8',
        invref_0: 'VALUE_8',
        bpaaddlig_0: 'VALUE_8',
        crynam_0: 'VALUE_8',
        eecnum_0: 'VALUE_8',
        eecnumdeb_0: 'VALUE_8',
        paz_0: 'VALUE_8',
        amtnot_0: 84.0,
        amtati_0: 84.0,
        cce_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        fcy_0: 'VALUE_8',
        per_0: 'VALUE_8',
        cpy_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        tax_0: 'VALUE_8',
        sns_0: 'VALUE_8',
        pte_0: 'VALUE_8',
        cur_0: 'VALUE_8',
        bvrbid_0: 'VALUE_8',
        num_0: 'VALUE_8',
        gte_0: 'VALUE_8',
        bprsac_0: 'VALUE_8',
        ritamt_0: 84.0,
        jou_0: 'VALUE_8',
        cty_0: 'VALUE_8',
        cry_0: 'VALUE_8',
        vac_0: 'VALUE_8',
        bprpay_0: 'VALUE_8',
        invnum_0: 'VALUE_8',
        nbrtax_0: 'VALUE_8',
        amttax_0: 84.0,
        bastax_0: 8,
        poscod_0: 'VALUE_8',
        updusr_0: 'VALUE_8',
        dedtax_0: 'VALUE_8',
        ceeflg_0: 'VALUE_8',
        cai_0: 'VALUE_8',
        datvlycai_0: new Date().toISOString().split('T')[0],
        typvcr_0: 'VALUE_8',
        clsvcr_0: 'VALUE_8',
        scuvcr_0: 'VALUE_8',
        seqvcr_0: 'VALUE_8',
        ictcty_0: 'VALUE_8',
        ffwadd_0: 'VALUE_8',
        dep_0: 'VALUE_8',
        eecloc_0: 'VALUE_8',
        ffwnum_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        bpainv_0: 'VALUE_8',
        pihtyp_0: 'VALUE_8',
        eecsch_0: 'VALUE_8',
        ratdat_0: new Date().toISOString().split('T')[0],
        fiy_0: 'VALUE_8',
        bprvcr_0: 'VALUE_8',
        strduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_8',
        xncflg_0: 'VALUE_8',
        bpycry_0: 'VALUE_8',
        bpycrynam_0: 'VALUE_8',
        nbrcpy_0: 'VALUE_8',
        led_0: 'VALUE_8',
        ublusr_0: 'VALUE_8',
        ubldat_0: new Date().toISOString().split('T')[0],
        ublamt_0: 84.0,
        twmsta_0: 8,
        xmotlit_0: 'VALUE_8',
        frm1099_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        deprat_0: 'VALUE_8',
        xrespli_0: 'VALUE_8',
        belvcs_0: 'VALUE_8',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_8',
        purprityp_0: 84.0,
        spadernum_0: 'VALUE_8',
        fld40ren_0: 'VALUE_8',
        fld41ren_0: 'VALUE_8',
        cshvat_0: 'VALUE_8',
        ratdiv_0: 'VALUE_8',
        ratmlt_0: 'VALUE_8',
        sinum_0: 'VALUE_8',
        die_0: 'VALUE_8',
        curled_0: 'VALUE_8',
        pjth_0: 'VALUE_8',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 84.0,
        amtatil_0: 84.0,
        ritbasded_0: 'VALUE_8',
        x4payyooz_0: 'VALUE_8',
        x4stayooz_0: 8,
        x4debpaz_0: 'VALUE_8',
        x4lnkyooz_0: 'VALUE_8',
        x4paysta_0: 8,
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        basdep_0: 'VALUE_8',
        porimpliqnum_0: 'VALUE_8',
        spacusdat_0: new Date().toISOString().split('T')[0],
        spacus_0: 'VALUE_8',
        spacusbpr_0: 'VALUE_8',
        box1099_0: 'VALUE_8',
        das2_0: 'VALUE_8',
        amtsubj1099_0: 84.0,
        bvrrefline_0: 'VALUE_8',
        bpynam_0: 'VALUE_8',
        bpyaddlig_0: 'VALUE_8',
        bpyposcod_0: 'VALUE_8',
        bpycty_0: 'VALUE_8',
        bpysat_0: 'VALUE_8',
      },
      {
        bpr_0: 'VALUE_9',
        oridocnum_0: 'PIN0009',
        eectrn_0: 'VALUE_9',
        sat_0: 'VALUE_9',
        ritinv_0: 'VALUE_9',
        accdat_0: new Date().toISOString().split('T')[0],
        eecnat_0: 'VALUE_9',
        eecict_0: 'VALUE_9',
        orimod_0: 'VALUE_9',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_9',
        pivtyp_0: 'VALUE_9',
        purtyp_0: 'VALUE_9',
        invtyp_0: 'VALUE_9',
        ritnbr_0: 'VALUE_9',
        ritcod_0: 'VALUE_9',
        ritbas_0: 'VALUE_9',
        ritamtded_0: 94.5,
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        bpapay_0: 'VALUE_9',
        bprnam_0: 'Raison sociale 9',
        deptyp_0: 'VALUE_9',
        des_0: 'VALUE_9',
        ritpay_0: 'VALUE_9',
        invref_0: 'VALUE_9',
        bpaaddlig_0: 'VALUE_9',
        crynam_0: 'VALUE_9',
        eecnum_0: 'VALUE_9',
        eecnumdeb_0: 'VALUE_9',
        paz_0: 'VALUE_9',
        amtnot_0: 94.5,
        amtati_0: 94.5,
        cce_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        fcy_0: 'VALUE_9',
        per_0: 'VALUE_9',
        cpy_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        tax_0: 'VALUE_9',
        sns_0: 'VALUE_9',
        pte_0: 'VALUE_9',
        cur_0: 'VALUE_9',
        bvrbid_0: 'VALUE_9',
        num_0: 'VALUE_9',
        gte_0: 'VALUE_9',
        bprsac_0: 'VALUE_9',
        ritamt_0: 94.5,
        jou_0: 'VALUE_9',
        cty_0: 'VALUE_9',
        cry_0: 'VALUE_9',
        vac_0: 'VALUE_9',
        bprpay_0: 'VALUE_9',
        invnum_0: 'VALUE_9',
        nbrtax_0: 'VALUE_9',
        amttax_0: 94.5,
        bastax_0: 9,
        poscod_0: 'VALUE_9',
        updusr_0: 'VALUE_9',
        dedtax_0: 'VALUE_9',
        ceeflg_0: 'VALUE_9',
        cai_0: 'VALUE_9',
        datvlycai_0: new Date().toISOString().split('T')[0],
        typvcr_0: 'VALUE_9',
        clsvcr_0: 'VALUE_9',
        scuvcr_0: 'VALUE_9',
        seqvcr_0: 'VALUE_9',
        ictcty_0: 'VALUE_9',
        ffwadd_0: 'VALUE_9',
        dep_0: 'VALUE_9',
        eecloc_0: 'VALUE_9',
        ffwnum_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        bpainv_0: 'VALUE_9',
        pihtyp_0: 'VALUE_9',
        eecsch_0: 'VALUE_9',
        ratdat_0: new Date().toISOString().split('T')[0],
        fiy_0: 'VALUE_9',
        bprvcr_0: 'VALUE_9',
        strduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_9',
        xncflg_0: 'VALUE_9',
        bpycry_0: 'VALUE_9',
        bpycrynam_0: 'VALUE_9',
        nbrcpy_0: 'VALUE_9',
        led_0: 'VALUE_9',
        ublusr_0: 'VALUE_9',
        ubldat_0: new Date().toISOString().split('T')[0],
        ublamt_0: 94.5,
        twmsta_0: 9,
        xmotlit_0: 'VALUE_9',
        frm1099_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        deprat_0: 'VALUE_9',
        xrespli_0: 'VALUE_9',
        belvcs_0: 'VALUE_9',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_9',
        purprityp_0: 94.5,
        spadernum_0: 'VALUE_9',
        fld40ren_0: 'VALUE_9',
        fld41ren_0: 'VALUE_9',
        cshvat_0: 'VALUE_9',
        ratdiv_0: 'VALUE_9',
        ratmlt_0: 'VALUE_9',
        sinum_0: 'VALUE_9',
        die_0: 'VALUE_9',
        curled_0: 'VALUE_9',
        pjth_0: 'VALUE_9',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 94.5,
        amtatil_0: 94.5,
        ritbasded_0: 'VALUE_9',
        x4payyooz_0: 'VALUE_9',
        x4stayooz_0: 9,
        x4debpaz_0: 'VALUE_9',
        x4lnkyooz_0: 'VALUE_9',
        x4paysta_0: 9,
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        basdep_0: 'VALUE_9',
        porimpliqnum_0: 'VALUE_9',
        spacusdat_0: new Date().toISOString().split('T')[0],
        spacus_0: 'VALUE_9',
        spacusbpr_0: 'VALUE_9',
        box1099_0: 'VALUE_9',
        das2_0: 'VALUE_9',
        amtsubj1099_0: 94.5,
        bvrrefline_0: 'VALUE_9',
        bpynam_0: 'VALUE_9',
        bpyaddlig_0: 'VALUE_9',
        bpyposcod_0: 'VALUE_9',
        bpycty_0: 'VALUE_9',
        bpysat_0: 'VALUE_9',
      },
      {
        bpr_0: 'VALUE_10',
        oridocnum_0: 'PIN0010',
        eectrn_0: 'VALUE_10',
        sat_0: 'VALUE_10',
        ritinv_0: 'VALUE_10',
        accdat_0: new Date().toISOString().split('T')[0],
        eecnat_0: 'VALUE_10',
        eecict_0: 'VALUE_10',
        orimod_0: 'VALUE_10',
        bprdat_0: new Date().toISOString().split('T')[0],
        accnum_0: 'VALUE_10',
        pivtyp_0: 'VALUE_10',
        purtyp_0: 'VALUE_10',
        invtyp_0: 'VALUE_10',
        ritnbr_0: 'VALUE_10',
        ritcod_0: 'VALUE_10',
        ritbas_0: 'VALUE_10',
        ritamtded_0: 105.0,
        strdatsvc_0: new Date().toISOString().split('T')[0],
        enddatsvc_0: new Date().toISOString().split('T')[0],
        lasdatsvc_0: new Date().toISOString().split('T')[0],
        bpapay_0: 'VALUE_10',
        bprnam_0: 'Raison sociale 10',
        deptyp_0: 'VALUE_10',
        des_0: 'VALUE_10',
        ritpay_0: 'VALUE_10',
        invref_0: 'VALUE_10',
        bpaaddlig_0: 'VALUE_10',
        crynam_0: 'VALUE_10',
        eecnum_0: 'VALUE_10',
        eecnumdeb_0: 'VALUE_10',
        paz_0: 'VALUE_10',
        amtnot_0: 105.0,
        amtati_0: 105.0,
        cce_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        fcy_0: 'VALUE_10',
        per_0: 'VALUE_10',
        cpy_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        tax_0: 'VALUE_10',
        sns_0: 'VALUE_10',
        pte_0: 'VALUE_10',
        cur_0: 'VALUE_10',
        bvrbid_0: 'VALUE_10',
        num_0: 'VALUE_10',
        gte_0: 'VALUE_10',
        bprsac_0: 'VALUE_10',
        ritamt_0: 105.0,
        jou_0: 'VALUE_10',
        cty_0: 'VALUE_10',
        cry_0: 'VALUE_10',
        vac_0: 'VALUE_10',
        bprpay_0: 'VALUE_10',
        invnum_0: 'VALUE_10',
        nbrtax_0: 'VALUE_10',
        amttax_0: 105.0,
        bastax_0: 10,
        poscod_0: 'VALUE_10',
        updusr_0: 'VALUE_10',
        dedtax_0: 'VALUE_10',
        ceeflg_0: 'VALUE_10',
        cai_0: 'VALUE_10',
        datvlycai_0: new Date().toISOString().split('T')[0],
        typvcr_0: 'VALUE_10',
        clsvcr_0: 'VALUE_10',
        scuvcr_0: 'VALUE_10',
        seqvcr_0: 'VALUE_10',
        ictcty_0: 'VALUE_10',
        ffwadd_0: 'VALUE_10',
        dep_0: 'VALUE_10',
        eecloc_0: 'VALUE_10',
        ffwnum_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        bpainv_0: 'VALUE_10',
        pihtyp_0: 'VALUE_10',
        eecsch_0: 'VALUE_10',
        ratdat_0: new Date().toISOString().split('T')[0],
        fiy_0: 'VALUE_10',
        bprvcr_0: 'VALUE_10',
        strduddat_0: new Date().toISOString().split('T')[0],
        sta_0: 1,
        curtyp_0: 'VALUE_10',
        xncflg_0: 'VALUE_10',
        bpycry_0: 'VALUE_10',
        bpycrynam_0: 'VALUE_10',
        nbrcpy_0: 'VALUE_10',
        led_0: 'VALUE_10',
        ublusr_0: 'VALUE_10',
        ubldat_0: new Date().toISOString().split('T')[0],
        ublamt_0: 105.0,
        twmsta_0: 10,
        xmotlit_0: 'VALUE_10',
        frm1099_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        deprat_0: 'VALUE_10',
        xrespli_0: 'VALUE_10',
        belvcs_0: 'VALUE_10',
        rcrdat_0: new Date().toISOString().split('T')[0],
        rcrnum_0: 'VALUE_10',
        purprityp_0: 105.0,
        spadernum_0: 'VALUE_10',
        fld40ren_0: 'VALUE_10',
        fld41ren_0: 'VALUE_10',
        cshvat_0: 'VALUE_10',
        ratdiv_0: 'VALUE_10',
        ratmlt_0: 'VALUE_10',
        sinum_0: 'VALUE_10',
        die_0: 'VALUE_10',
        curled_0: 'VALUE_10',
        pjth_0: 'VALUE_10',
        vatdat_0: new Date().toISOString().split('T')[0],
        amtnotl_0: 105.0,
        amtatil_0: 105.0,
        ritbasded_0: 'VALUE_10',
        x4payyooz_0: 'VALUE_10',
        x4stayooz_0: 10,
        x4debpaz_0: 'VALUE_10',
        x4lnkyooz_0: 'VALUE_10',
        x4paysta_0: 10,
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        basdep_0: 'VALUE_10',
        porimpliqnum_0: 'VALUE_10',
        spacusdat_0: new Date().toISOString().split('T')[0],
        spacus_0: 'VALUE_10',
        spacusbpr_0: 'VALUE_10',
        box1099_0: 'VALUE_10',
        das2_0: 'VALUE_10',
        amtsubj1099_0: 105.0,
        bvrrefline_0: 'VALUE_10',
        bpynam_0: 'VALUE_10',
        bpyaddlig_0: 'VALUE_10',
        bpyposcod_0: 'VALUE_10',
        bpycty_0: 'VALUE_10',
        bpysat_0: 'VALUE_10',
      },
    ]

    await Database.table('pinvoice').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans pinvoice`)
  }
}
