import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour BOM
    const data = [
      {
        upddat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'BOM0001',
        bomalttyp_0: 'VALUE_1',
        bomdesaxx_0: 'Désignation entête 1',
        usesta_0: 1,
        bomrle_0: 'VALUE_1',
        basqty_0: 10.5,
        qtycod_0: 10.5,
        bohstrdat_0: new Date().toISOString().split('T')[0],
        bohenddat_0: new Date().toISOString().split('T')[0],
        acscod_0: 'VALUE_1',
        credat_0: new Date().toISOString().split('T')[0],
        heatex_0: 'VALUE_1',
        bomalt_0: 'VALUE_1',
        xexpinfdat_0: new Date().toISOString().split('T')[0],
        x1_prefix_0: 'VALUE_1',
        ident1_0: 'VALUE_1',
        xexpinf_0: 'VALUE_1',
        updusr_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        itmref_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        npipro_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcommcpvv_0: 'VALUE_1',
        xnbempr_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        plmatturl_0: 'VALUE_1',
        xcfcod_0: 'VALUE_1',
      },
      {
        upddat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'BOM0002',
        bomalttyp_0: 'VALUE_2',
        bomdesaxx_0: 'Désignation entête 2',
        usesta_0: 1,
        bomrle_0: 'VALUE_2',
        basqty_0: 21.0,
        qtycod_0: 21.0,
        bohstrdat_0: new Date().toISOString().split('T')[0],
        bohenddat_0: new Date().toISOString().split('T')[0],
        acscod_0: 'VALUE_2',
        credat_0: new Date().toISOString().split('T')[0],
        heatex_0: 'VALUE_2',
        bomalt_0: 'VALUE_2',
        xexpinfdat_0: new Date().toISOString().split('T')[0],
        x1_prefix_0: 'VALUE_2',
        ident1_0: 'VALUE_2',
        xexpinf_0: 'VALUE_2',
        updusr_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        itmref_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        npipro_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcommcpvv_0: 'VALUE_2',
        xnbempr_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        plmatturl_0: 'VALUE_2',
        xcfcod_0: 'VALUE_2',
      },
      {
        upddat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'BOM0003',
        bomalttyp_0: 'VALUE_3',
        bomdesaxx_0: 'Désignation entête 3',
        usesta_0: 1,
        bomrle_0: 'VALUE_3',
        basqty_0: 31.5,
        qtycod_0: 31.5,
        bohstrdat_0: new Date().toISOString().split('T')[0],
        bohenddat_0: new Date().toISOString().split('T')[0],
        acscod_0: 'VALUE_3',
        credat_0: new Date().toISOString().split('T')[0],
        heatex_0: 'VALUE_3',
        bomalt_0: 'VALUE_3',
        xexpinfdat_0: new Date().toISOString().split('T')[0],
        x1_prefix_0: 'VALUE_3',
        ident1_0: 'VALUE_3',
        xexpinf_0: 'VALUE_3',
        updusr_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        itmref_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        npipro_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcommcpvv_0: 'VALUE_3',
        xnbempr_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        plmatturl_0: 'VALUE_3',
        xcfcod_0: 'VALUE_3',
      },
      {
        upddat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'BOM0004',
        bomalttyp_0: 'VALUE_4',
        bomdesaxx_0: 'Désignation entête 4',
        usesta_0: 1,
        bomrle_0: 'VALUE_4',
        basqty_0: 42.0,
        qtycod_0: 42.0,
        bohstrdat_0: new Date().toISOString().split('T')[0],
        bohenddat_0: new Date().toISOString().split('T')[0],
        acscod_0: 'VALUE_4',
        credat_0: new Date().toISOString().split('T')[0],
        heatex_0: 'VALUE_4',
        bomalt_0: 'VALUE_4',
        xexpinfdat_0: new Date().toISOString().split('T')[0],
        x1_prefix_0: 'VALUE_4',
        ident1_0: 'VALUE_4',
        xexpinf_0: 'VALUE_4',
        updusr_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        itmref_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        npipro_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcommcpvv_0: 'VALUE_4',
        xnbempr_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        plmatturl_0: 'VALUE_4',
        xcfcod_0: 'VALUE_4',
      },
      {
        upddat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'BOM0005',
        bomalttyp_0: 'VALUE_5',
        bomdesaxx_0: 'Désignation entête 5',
        usesta_0: 1,
        bomrle_0: 'VALUE_5',
        basqty_0: 52.5,
        qtycod_0: 52.5,
        bohstrdat_0: new Date().toISOString().split('T')[0],
        bohenddat_0: new Date().toISOString().split('T')[0],
        acscod_0: 'VALUE_5',
        credat_0: new Date().toISOString().split('T')[0],
        heatex_0: 'VALUE_5',
        bomalt_0: 'VALUE_5',
        xexpinfdat_0: new Date().toISOString().split('T')[0],
        x1_prefix_0: 'VALUE_5',
        ident1_0: 'VALUE_5',
        xexpinf_0: 'VALUE_5',
        updusr_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        itmref_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        npipro_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcommcpvv_0: 'VALUE_5',
        xnbempr_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        plmatturl_0: 'VALUE_5',
        xcfcod_0: 'VALUE_5',
      },
      {
        upddat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'BOM0006',
        bomalttyp_0: 'VALUE_6',
        bomdesaxx_0: 'Désignation entête 6',
        usesta_0: 1,
        bomrle_0: 'VALUE_6',
        basqty_0: 63.0,
        qtycod_0: 63.0,
        bohstrdat_0: new Date().toISOString().split('T')[0],
        bohenddat_0: new Date().toISOString().split('T')[0],
        acscod_0: 'VALUE_6',
        credat_0: new Date().toISOString().split('T')[0],
        heatex_0: 'VALUE_6',
        bomalt_0: 'VALUE_6',
        xexpinfdat_0: new Date().toISOString().split('T')[0],
        x1_prefix_0: 'VALUE_6',
        ident1_0: 'VALUE_6',
        xexpinf_0: 'VALUE_6',
        updusr_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        itmref_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        npipro_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcommcpvv_0: 'VALUE_6',
        xnbempr_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        plmatturl_0: 'VALUE_6',
        xcfcod_0: 'VALUE_6',
      },
      {
        upddat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'BOM0007',
        bomalttyp_0: 'VALUE_7',
        bomdesaxx_0: 'Désignation entête 7',
        usesta_0: 1,
        bomrle_0: 'VALUE_7',
        basqty_0: 73.5,
        qtycod_0: 73.5,
        bohstrdat_0: new Date().toISOString().split('T')[0],
        bohenddat_0: new Date().toISOString().split('T')[0],
        acscod_0: 'VALUE_7',
        credat_0: new Date().toISOString().split('T')[0],
        heatex_0: 'VALUE_7',
        bomalt_0: 'VALUE_7',
        xexpinfdat_0: new Date().toISOString().split('T')[0],
        x1_prefix_0: 'VALUE_7',
        ident1_0: 'VALUE_7',
        xexpinf_0: 'VALUE_7',
        updusr_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        itmref_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        npipro_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcommcpvv_0: 'VALUE_7',
        xnbempr_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        plmatturl_0: 'VALUE_7',
        xcfcod_0: 'VALUE_7',
      },
      {
        upddat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'BOM0008',
        bomalttyp_0: 'VALUE_8',
        bomdesaxx_0: 'Désignation entête 8',
        usesta_0: 1,
        bomrle_0: 'VALUE_8',
        basqty_0: 84.0,
        qtycod_0: 84.0,
        bohstrdat_0: new Date().toISOString().split('T')[0],
        bohenddat_0: new Date().toISOString().split('T')[0],
        acscod_0: 'VALUE_8',
        credat_0: new Date().toISOString().split('T')[0],
        heatex_0: 'VALUE_8',
        bomalt_0: 'VALUE_8',
        xexpinfdat_0: new Date().toISOString().split('T')[0],
        x1_prefix_0: 'VALUE_8',
        ident1_0: 'VALUE_8',
        xexpinf_0: 'VALUE_8',
        updusr_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        itmref_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        npipro_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcommcpvv_0: 'VALUE_8',
        xnbempr_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        plmatturl_0: 'VALUE_8',
        xcfcod_0: 'VALUE_8',
      },
      {
        upddat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'BOM0009',
        bomalttyp_0: 'VALUE_9',
        bomdesaxx_0: 'Désignation entête 9',
        usesta_0: 1,
        bomrle_0: 'VALUE_9',
        basqty_0: 94.5,
        qtycod_0: 94.5,
        bohstrdat_0: new Date().toISOString().split('T')[0],
        bohenddat_0: new Date().toISOString().split('T')[0],
        acscod_0: 'VALUE_9',
        credat_0: new Date().toISOString().split('T')[0],
        heatex_0: 'VALUE_9',
        bomalt_0: 'VALUE_9',
        xexpinfdat_0: new Date().toISOString().split('T')[0],
        x1_prefix_0: 'VALUE_9',
        ident1_0: 'VALUE_9',
        xexpinf_0: 'VALUE_9',
        updusr_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        itmref_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        npipro_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcommcpvv_0: 'VALUE_9',
        xnbempr_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        plmatturl_0: 'VALUE_9',
        xcfcod_0: 'VALUE_9',
      },
      {
        upddat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'BOM0010',
        bomalttyp_0: 'VALUE_10',
        bomdesaxx_0: 'Désignation entête 10',
        usesta_0: 1,
        bomrle_0: 'VALUE_10',
        basqty_0: 105.0,
        qtycod_0: 105.0,
        bohstrdat_0: new Date().toISOString().split('T')[0],
        bohenddat_0: new Date().toISOString().split('T')[0],
        acscod_0: 'VALUE_10',
        credat_0: new Date().toISOString().split('T')[0],
        heatex_0: 'VALUE_10',
        bomalt_0: 'VALUE_10',
        xexpinfdat_0: new Date().toISOString().split('T')[0],
        x1_prefix_0: 'VALUE_10',
        ident1_0: 'VALUE_10',
        xexpinf_0: 'VALUE_10',
        updusr_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        itmref_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        npipro_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        xcommcpvv_0: 'VALUE_10',
        xnbempr_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        plmatturl_0: 'VALUE_10',
        xcfcod_0: 'VALUE_10',
      },
    ]

    await Database.table('bom').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans bom`)
  }
}
