import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour BOMD
    const data = [
      {
        openumlev_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        bomstucoe_0: 'VALUE_1',
        bomqty_0: 10.5,
        pkc_0: 'VALUE_1',
        x4pkc_0: 'VALUE_1',
        bomalttyp_0: 'VALUE_1',
        xcombomp_0: 'VALUE_1',
        cpnitmref_0: 'BOM0001',
        bomstrlot_0: 'VALUE_1',
        bomendlot_0: 'VALUE_1',
        cpnope_0: 'VALUE_1',
        bomofs_0: 'VALUE_1',
        bomseq_0: 'VALUE_1',
        bomstrdat_0: new Date().toISOString().split('T')[0],
        bomenddat_0: new Date().toISOString().split('T')[0],
        ocnprn_0: 'VALUE_1',
        invprn_0: 'VALUE_1',
        cpntyp_0: 'VALUE_1',
        bomseqnum_0: 'VALUE_1',
        likqtycod_0: 10.5,
        qtyrnd_0: 10.5,
        bomsho_0: 'VALUE_1',
        likqty_0: 10.5,
        picprn_0: 'VALUE_1',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_1',
        forsel_0: 'VALUE_1',
        bomuom_0: 'VALUE_1',
        itmref_0: 'VALUE_1',
        cstflg_0: 'VALUE_1',
        ndeprn_0: 'VALUE_1',
        likrle_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        xversion_0: 'VALUE_1',
        bomtexnum_0: 'VALUE_1',
        sca_0: 'VALUE_1',
        x1cni_0: 'VALUE_1',
        x1toprep_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccrlegrp_0: 'VALUE_1',
        eccvalmaj_0: 'VALUE_1',
        eccvalmin_0: 'VALUE_1',
        levset_0: 'VALUE_1',
        xqsp_0: 'VALUE_1',
        xiformule_0: 'VALUE_1',
        itmtolpos_0: 'VALUE_1',
        itmtolneg_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        forqty_0: 10.5,
        ctn_0: 'VALUE_1',
        x4limend_0: 'VALUE_1',
        x4limflg_0: 'VALUE_1',
        x4limtyp_0: 'VALUE_1',
        x4limstr_0: 'VALUE_1',
        scoflg_0: 'VALUE_1',
        bomalt_0: 'VALUE_1',
      },
      {
        openumlev_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        bomstucoe_0: 'VALUE_2',
        bomqty_0: 21.0,
        pkc_0: 'VALUE_2',
        x4pkc_0: 'VALUE_2',
        bomalttyp_0: 'VALUE_2',
        xcombomp_0: 'VALUE_2',
        cpnitmref_0: 'BOM0002',
        bomstrlot_0: 'VALUE_2',
        bomendlot_0: 'VALUE_2',
        cpnope_0: 'VALUE_2',
        bomofs_0: 'VALUE_2',
        bomseq_0: 'VALUE_2',
        bomstrdat_0: new Date().toISOString().split('T')[0],
        bomenddat_0: new Date().toISOString().split('T')[0],
        ocnprn_0: 'VALUE_2',
        invprn_0: 'VALUE_2',
        cpntyp_0: 'VALUE_2',
        bomseqnum_0: 'VALUE_2',
        likqtycod_0: 21.0,
        qtyrnd_0: 21.0,
        bomsho_0: 'VALUE_2',
        likqty_0: 21.0,
        picprn_0: 'VALUE_2',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_2',
        forsel_0: 'VALUE_2',
        bomuom_0: 'VALUE_2',
        itmref_0: 'VALUE_2',
        cstflg_0: 'VALUE_2',
        ndeprn_0: 'VALUE_2',
        likrle_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        xversion_0: 'VALUE_2',
        bomtexnum_0: 'VALUE_2',
        sca_0: 'VALUE_2',
        x1cni_0: 'VALUE_2',
        x1toprep_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccrlegrp_0: 'VALUE_2',
        eccvalmaj_0: 'VALUE_2',
        eccvalmin_0: 'VALUE_2',
        levset_0: 'VALUE_2',
        xqsp_0: 'VALUE_2',
        xiformule_0: 'VALUE_2',
        itmtolpos_0: 'VALUE_2',
        itmtolneg_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        forqty_0: 21.0,
        ctn_0: 'VALUE_2',
        x4limend_0: 'VALUE_2',
        x4limflg_0: 'VALUE_2',
        x4limtyp_0: 'VALUE_2',
        x4limstr_0: 'VALUE_2',
        scoflg_0: 'VALUE_2',
        bomalt_0: 'VALUE_2',
      },
      {
        openumlev_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        bomstucoe_0: 'VALUE_3',
        bomqty_0: 31.5,
        pkc_0: 'VALUE_3',
        x4pkc_0: 'VALUE_3',
        bomalttyp_0: 'VALUE_3',
        xcombomp_0: 'VALUE_3',
        cpnitmref_0: 'BOM0003',
        bomstrlot_0: 'VALUE_3',
        bomendlot_0: 'VALUE_3',
        cpnope_0: 'VALUE_3',
        bomofs_0: 'VALUE_3',
        bomseq_0: 'VALUE_3',
        bomstrdat_0: new Date().toISOString().split('T')[0],
        bomenddat_0: new Date().toISOString().split('T')[0],
        ocnprn_0: 'VALUE_3',
        invprn_0: 'VALUE_3',
        cpntyp_0: 'VALUE_3',
        bomseqnum_0: 'VALUE_3',
        likqtycod_0: 31.5,
        qtyrnd_0: 31.5,
        bomsho_0: 'VALUE_3',
        likqty_0: 31.5,
        picprn_0: 'VALUE_3',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_3',
        forsel_0: 'VALUE_3',
        bomuom_0: 'VALUE_3',
        itmref_0: 'VALUE_3',
        cstflg_0: 'VALUE_3',
        ndeprn_0: 'VALUE_3',
        likrle_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        xversion_0: 'VALUE_3',
        bomtexnum_0: 'VALUE_3',
        sca_0: 'VALUE_3',
        x1cni_0: 'VALUE_3',
        x1toprep_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccrlegrp_0: 'VALUE_3',
        eccvalmaj_0: 'VALUE_3',
        eccvalmin_0: 'VALUE_3',
        levset_0: 'VALUE_3',
        xqsp_0: 'VALUE_3',
        xiformule_0: 'VALUE_3',
        itmtolpos_0: 'VALUE_3',
        itmtolneg_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        forqty_0: 31.5,
        ctn_0: 'VALUE_3',
        x4limend_0: 'VALUE_3',
        x4limflg_0: 'VALUE_3',
        x4limtyp_0: 'VALUE_3',
        x4limstr_0: 'VALUE_3',
        scoflg_0: 'VALUE_3',
        bomalt_0: 'VALUE_3',
      },
      {
        openumlev_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        bomstucoe_0: 'VALUE_4',
        bomqty_0: 42.0,
        pkc_0: 'VALUE_4',
        x4pkc_0: 'VALUE_4',
        bomalttyp_0: 'VALUE_4',
        xcombomp_0: 'VALUE_4',
        cpnitmref_0: 'BOM0004',
        bomstrlot_0: 'VALUE_4',
        bomendlot_0: 'VALUE_4',
        cpnope_0: 'VALUE_4',
        bomofs_0: 'VALUE_4',
        bomseq_0: 'VALUE_4',
        bomstrdat_0: new Date().toISOString().split('T')[0],
        bomenddat_0: new Date().toISOString().split('T')[0],
        ocnprn_0: 'VALUE_4',
        invprn_0: 'VALUE_4',
        cpntyp_0: 'VALUE_4',
        bomseqnum_0: 'VALUE_4',
        likqtycod_0: 42.0,
        qtyrnd_0: 42.0,
        bomsho_0: 'VALUE_4',
        likqty_0: 42.0,
        picprn_0: 'VALUE_4',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_4',
        forsel_0: 'VALUE_4',
        bomuom_0: 'VALUE_4',
        itmref_0: 'VALUE_4',
        cstflg_0: 'VALUE_4',
        ndeprn_0: 'VALUE_4',
        likrle_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        xversion_0: 'VALUE_4',
        bomtexnum_0: 'VALUE_4',
        sca_0: 'VALUE_4',
        x1cni_0: 'VALUE_4',
        x1toprep_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccrlegrp_0: 'VALUE_4',
        eccvalmaj_0: 'VALUE_4',
        eccvalmin_0: 'VALUE_4',
        levset_0: 'VALUE_4',
        xqsp_0: 'VALUE_4',
        xiformule_0: 'VALUE_4',
        itmtolpos_0: 'VALUE_4',
        itmtolneg_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        forqty_0: 42.0,
        ctn_0: 'VALUE_4',
        x4limend_0: 'VALUE_4',
        x4limflg_0: 'VALUE_4',
        x4limtyp_0: 'VALUE_4',
        x4limstr_0: 'VALUE_4',
        scoflg_0: 'VALUE_4',
        bomalt_0: 'VALUE_4',
      },
      {
        openumlev_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        bomstucoe_0: 'VALUE_5',
        bomqty_0: 52.5,
        pkc_0: 'VALUE_5',
        x4pkc_0: 'VALUE_5',
        bomalttyp_0: 'VALUE_5',
        xcombomp_0: 'VALUE_5',
        cpnitmref_0: 'BOM0005',
        bomstrlot_0: 'VALUE_5',
        bomendlot_0: 'VALUE_5',
        cpnope_0: 'VALUE_5',
        bomofs_0: 'VALUE_5',
        bomseq_0: 'VALUE_5',
        bomstrdat_0: new Date().toISOString().split('T')[0],
        bomenddat_0: new Date().toISOString().split('T')[0],
        ocnprn_0: 'VALUE_5',
        invprn_0: 'VALUE_5',
        cpntyp_0: 'VALUE_5',
        bomseqnum_0: 'VALUE_5',
        likqtycod_0: 52.5,
        qtyrnd_0: 52.5,
        bomsho_0: 'VALUE_5',
        likqty_0: 52.5,
        picprn_0: 'VALUE_5',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_5',
        forsel_0: 'VALUE_5',
        bomuom_0: 'VALUE_5',
        itmref_0: 'VALUE_5',
        cstflg_0: 'VALUE_5',
        ndeprn_0: 'VALUE_5',
        likrle_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        xversion_0: 'VALUE_5',
        bomtexnum_0: 'VALUE_5',
        sca_0: 'VALUE_5',
        x1cni_0: 'VALUE_5',
        x1toprep_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccrlegrp_0: 'VALUE_5',
        eccvalmaj_0: 'VALUE_5',
        eccvalmin_0: 'VALUE_5',
        levset_0: 'VALUE_5',
        xqsp_0: 'VALUE_5',
        xiformule_0: 'VALUE_5',
        itmtolpos_0: 'VALUE_5',
        itmtolneg_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        forqty_0: 52.5,
        ctn_0: 'VALUE_5',
        x4limend_0: 'VALUE_5',
        x4limflg_0: 'VALUE_5',
        x4limtyp_0: 'VALUE_5',
        x4limstr_0: 'VALUE_5',
        scoflg_0: 'VALUE_5',
        bomalt_0: 'VALUE_5',
      },
      {
        openumlev_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        bomstucoe_0: 'VALUE_6',
        bomqty_0: 63.0,
        pkc_0: 'VALUE_6',
        x4pkc_0: 'VALUE_6',
        bomalttyp_0: 'VALUE_6',
        xcombomp_0: 'VALUE_6',
        cpnitmref_0: 'BOM0006',
        bomstrlot_0: 'VALUE_6',
        bomendlot_0: 'VALUE_6',
        cpnope_0: 'VALUE_6',
        bomofs_0: 'VALUE_6',
        bomseq_0: 'VALUE_6',
        bomstrdat_0: new Date().toISOString().split('T')[0],
        bomenddat_0: new Date().toISOString().split('T')[0],
        ocnprn_0: 'VALUE_6',
        invprn_0: 'VALUE_6',
        cpntyp_0: 'VALUE_6',
        bomseqnum_0: 'VALUE_6',
        likqtycod_0: 63.0,
        qtyrnd_0: 63.0,
        bomsho_0: 'VALUE_6',
        likqty_0: 63.0,
        picprn_0: 'VALUE_6',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_6',
        forsel_0: 'VALUE_6',
        bomuom_0: 'VALUE_6',
        itmref_0: 'VALUE_6',
        cstflg_0: 'VALUE_6',
        ndeprn_0: 'VALUE_6',
        likrle_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        xversion_0: 'VALUE_6',
        bomtexnum_0: 'VALUE_6',
        sca_0: 'VALUE_6',
        x1cni_0: 'VALUE_6',
        x1toprep_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccrlegrp_0: 'VALUE_6',
        eccvalmaj_0: 'VALUE_6',
        eccvalmin_0: 'VALUE_6',
        levset_0: 'VALUE_6',
        xqsp_0: 'VALUE_6',
        xiformule_0: 'VALUE_6',
        itmtolpos_0: 'VALUE_6',
        itmtolneg_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        forqty_0: 63.0,
        ctn_0: 'VALUE_6',
        x4limend_0: 'VALUE_6',
        x4limflg_0: 'VALUE_6',
        x4limtyp_0: 'VALUE_6',
        x4limstr_0: 'VALUE_6',
        scoflg_0: 'VALUE_6',
        bomalt_0: 'VALUE_6',
      },
      {
        openumlev_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        bomstucoe_0: 'VALUE_7',
        bomqty_0: 73.5,
        pkc_0: 'VALUE_7',
        x4pkc_0: 'VALUE_7',
        bomalttyp_0: 'VALUE_7',
        xcombomp_0: 'VALUE_7',
        cpnitmref_0: 'BOM0007',
        bomstrlot_0: 'VALUE_7',
        bomendlot_0: 'VALUE_7',
        cpnope_0: 'VALUE_7',
        bomofs_0: 'VALUE_7',
        bomseq_0: 'VALUE_7',
        bomstrdat_0: new Date().toISOString().split('T')[0],
        bomenddat_0: new Date().toISOString().split('T')[0],
        ocnprn_0: 'VALUE_7',
        invprn_0: 'VALUE_7',
        cpntyp_0: 'VALUE_7',
        bomseqnum_0: 'VALUE_7',
        likqtycod_0: 73.5,
        qtyrnd_0: 73.5,
        bomsho_0: 'VALUE_7',
        likqty_0: 73.5,
        picprn_0: 'VALUE_7',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_7',
        forsel_0: 'VALUE_7',
        bomuom_0: 'VALUE_7',
        itmref_0: 'VALUE_7',
        cstflg_0: 'VALUE_7',
        ndeprn_0: 'VALUE_7',
        likrle_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        xversion_0: 'VALUE_7',
        bomtexnum_0: 'VALUE_7',
        sca_0: 'VALUE_7',
        x1cni_0: 'VALUE_7',
        x1toprep_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccrlegrp_0: 'VALUE_7',
        eccvalmaj_0: 'VALUE_7',
        eccvalmin_0: 'VALUE_7',
        levset_0: 'VALUE_7',
        xqsp_0: 'VALUE_7',
        xiformule_0: 'VALUE_7',
        itmtolpos_0: 'VALUE_7',
        itmtolneg_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        forqty_0: 73.5,
        ctn_0: 'VALUE_7',
        x4limend_0: 'VALUE_7',
        x4limflg_0: 'VALUE_7',
        x4limtyp_0: 'VALUE_7',
        x4limstr_0: 'VALUE_7',
        scoflg_0: 'VALUE_7',
        bomalt_0: 'VALUE_7',
      },
      {
        openumlev_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        bomstucoe_0: 'VALUE_8',
        bomqty_0: 84.0,
        pkc_0: 'VALUE_8',
        x4pkc_0: 'VALUE_8',
        bomalttyp_0: 'VALUE_8',
        xcombomp_0: 'VALUE_8',
        cpnitmref_0: 'BOM0008',
        bomstrlot_0: 'VALUE_8',
        bomendlot_0: 'VALUE_8',
        cpnope_0: 'VALUE_8',
        bomofs_0: 'VALUE_8',
        bomseq_0: 'VALUE_8',
        bomstrdat_0: new Date().toISOString().split('T')[0],
        bomenddat_0: new Date().toISOString().split('T')[0],
        ocnprn_0: 'VALUE_8',
        invprn_0: 'VALUE_8',
        cpntyp_0: 'VALUE_8',
        bomseqnum_0: 'VALUE_8',
        likqtycod_0: 84.0,
        qtyrnd_0: 84.0,
        bomsho_0: 'VALUE_8',
        likqty_0: 84.0,
        picprn_0: 'VALUE_8',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_8',
        forsel_0: 'VALUE_8',
        bomuom_0: 'VALUE_8',
        itmref_0: 'VALUE_8',
        cstflg_0: 'VALUE_8',
        ndeprn_0: 'VALUE_8',
        likrle_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        xversion_0: 'VALUE_8',
        bomtexnum_0: 'VALUE_8',
        sca_0: 'VALUE_8',
        x1cni_0: 'VALUE_8',
        x1toprep_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccrlegrp_0: 'VALUE_8',
        eccvalmaj_0: 'VALUE_8',
        eccvalmin_0: 'VALUE_8',
        levset_0: 'VALUE_8',
        xqsp_0: 'VALUE_8',
        xiformule_0: 'VALUE_8',
        itmtolpos_0: 'VALUE_8',
        itmtolneg_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        forqty_0: 84.0,
        ctn_0: 'VALUE_8',
        x4limend_0: 'VALUE_8',
        x4limflg_0: 'VALUE_8',
        x4limtyp_0: 'VALUE_8',
        x4limstr_0: 'VALUE_8',
        scoflg_0: 'VALUE_8',
        bomalt_0: 'VALUE_8',
      },
      {
        openumlev_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        bomstucoe_0: 'VALUE_9',
        bomqty_0: 94.5,
        pkc_0: 'VALUE_9',
        x4pkc_0: 'VALUE_9',
        bomalttyp_0: 'VALUE_9',
        xcombomp_0: 'VALUE_9',
        cpnitmref_0: 'BOM0009',
        bomstrlot_0: 'VALUE_9',
        bomendlot_0: 'VALUE_9',
        cpnope_0: 'VALUE_9',
        bomofs_0: 'VALUE_9',
        bomseq_0: 'VALUE_9',
        bomstrdat_0: new Date().toISOString().split('T')[0],
        bomenddat_0: new Date().toISOString().split('T')[0],
        ocnprn_0: 'VALUE_9',
        invprn_0: 'VALUE_9',
        cpntyp_0: 'VALUE_9',
        bomseqnum_0: 'VALUE_9',
        likqtycod_0: 94.5,
        qtyrnd_0: 94.5,
        bomsho_0: 'VALUE_9',
        likqty_0: 94.5,
        picprn_0: 'VALUE_9',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_9',
        forsel_0: 'VALUE_9',
        bomuom_0: 'VALUE_9',
        itmref_0: 'VALUE_9',
        cstflg_0: 'VALUE_9',
        ndeprn_0: 'VALUE_9',
        likrle_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        xversion_0: 'VALUE_9',
        bomtexnum_0: 'VALUE_9',
        sca_0: 'VALUE_9',
        x1cni_0: 'VALUE_9',
        x1toprep_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccrlegrp_0: 'VALUE_9',
        eccvalmaj_0: 'VALUE_9',
        eccvalmin_0: 'VALUE_9',
        levset_0: 'VALUE_9',
        xqsp_0: 'VALUE_9',
        xiformule_0: 'VALUE_9',
        itmtolpos_0: 'VALUE_9',
        itmtolneg_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        forqty_0: 94.5,
        ctn_0: 'VALUE_9',
        x4limend_0: 'VALUE_9',
        x4limflg_0: 'VALUE_9',
        x4limtyp_0: 'VALUE_9',
        x4limstr_0: 'VALUE_9',
        scoflg_0: 'VALUE_9',
        bomalt_0: 'VALUE_9',
      },
      {
        openumlev_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        bomstucoe_0: 'VALUE_10',
        bomqty_0: 105.0,
        pkc_0: 'VALUE_10',
        x4pkc_0: 'VALUE_10',
        bomalttyp_0: 'VALUE_10',
        xcombomp_0: 'VALUE_10',
        cpnitmref_0: 'BOM0010',
        bomstrlot_0: 'VALUE_10',
        bomendlot_0: 'VALUE_10',
        cpnope_0: 'VALUE_10',
        bomofs_0: 'VALUE_10',
        bomseq_0: 'VALUE_10',
        bomstrdat_0: new Date().toISOString().split('T')[0],
        bomenddat_0: new Date().toISOString().split('T')[0],
        ocnprn_0: 'VALUE_10',
        invprn_0: 'VALUE_10',
        cpntyp_0: 'VALUE_10',
        bomseqnum_0: 'VALUE_10',
        likqtycod_0: 105.0,
        qtyrnd_0: 105.0,
        bomsho_0: 'VALUE_10',
        likqty_0: 105.0,
        picprn_0: 'VALUE_10',
        credat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_10',
        forsel_0: 'VALUE_10',
        bomuom_0: 'VALUE_10',
        itmref_0: 'VALUE_10',
        cstflg_0: 'VALUE_10',
        ndeprn_0: 'VALUE_10',
        likrle_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        xversion_0: 'VALUE_10',
        bomtexnum_0: 'VALUE_10',
        sca_0: 'VALUE_10',
        x1cni_0: 'VALUE_10',
        x1toprep_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccrlegrp_0: 'VALUE_10',
        eccvalmaj_0: 'VALUE_10',
        eccvalmin_0: 'VALUE_10',
        levset_0: 'VALUE_10',
        xqsp_0: 'VALUE_10',
        xiformule_0: 'VALUE_10',
        itmtolpos_0: 'VALUE_10',
        itmtolneg_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        forqty_0: 105.0,
        ctn_0: 'VALUE_10',
        x4limend_0: 'VALUE_10',
        x4limflg_0: 'VALUE_10',
        x4limtyp_0: 'VALUE_10',
        x4limstr_0: 'VALUE_10',
        scoflg_0: 'VALUE_10',
        bomalt_0: 'VALUE_10',
      },
    ]

    await Database.table('bomd').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans bomd`)
  }
}
