import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour ROUTING
    const data = [
      {
        fcy_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        itmref_0: 'ROU0001',
        expnum_0: 'VALUE_1',
        cfmflg_0: 'VALUE_1',
        ident1_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_1',
        credat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'VALUE_1',
        acscod_0: 'VALUE_1',
        roualt_0: 'VALUE_1',
        laswordat_0: new Date().toISOString().split('T')[0],
        lasworqty_0: 10.5,
        wormaxqty_0: 10.5,
        worminqty_0: 10.5,
        plnnum_0: 'VALUE_1',
        wortyp_0: 'VALUE_1',
        timuomcod_0: new Date().toISOString(),
        rouenddat_0: new Date().toISOString().split('T')[0],
        roustrdat_0: new Date().toISOString().split('T')[0],
        usesta_0: 1,
        roudesaxx_0: 'Désignation entête 1',
        roudes_0: 'VALUE_1',
        roupct_0: 'VALUE_1',
        texnum_0: 'VALUE_1',
      },
      {
        fcy_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        itmref_0: 'ROU0002',
        expnum_0: 'VALUE_2',
        cfmflg_0: 'VALUE_2',
        ident1_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_2',
        credat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'VALUE_2',
        acscod_0: 'VALUE_2',
        roualt_0: 'VALUE_2',
        laswordat_0: new Date().toISOString().split('T')[0],
        lasworqty_0: 21.0,
        wormaxqty_0: 21.0,
        worminqty_0: 21.0,
        plnnum_0: 'VALUE_2',
        wortyp_0: 'VALUE_2',
        timuomcod_0: new Date().toISOString(),
        rouenddat_0: new Date().toISOString().split('T')[0],
        roustrdat_0: new Date().toISOString().split('T')[0],
        usesta_0: 1,
        roudesaxx_0: 'Désignation entête 2',
        roudes_0: 'VALUE_2',
        roupct_0: 'VALUE_2',
        texnum_0: 'VALUE_2',
      },
      {
        fcy_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        itmref_0: 'ROU0003',
        expnum_0: 'VALUE_3',
        cfmflg_0: 'VALUE_3',
        ident1_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_3',
        credat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'VALUE_3',
        acscod_0: 'VALUE_3',
        roualt_0: 'VALUE_3',
        laswordat_0: new Date().toISOString().split('T')[0],
        lasworqty_0: 31.5,
        wormaxqty_0: 31.5,
        worminqty_0: 31.5,
        plnnum_0: 'VALUE_3',
        wortyp_0: 'VALUE_3',
        timuomcod_0: new Date().toISOString(),
        rouenddat_0: new Date().toISOString().split('T')[0],
        roustrdat_0: new Date().toISOString().split('T')[0],
        usesta_0: 1,
        roudesaxx_0: 'Désignation entête 3',
        roudes_0: 'VALUE_3',
        roupct_0: 'VALUE_3',
        texnum_0: 'VALUE_3',
      },
      {
        fcy_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        itmref_0: 'ROU0004',
        expnum_0: 'VALUE_4',
        cfmflg_0: 'VALUE_4',
        ident1_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_4',
        credat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'VALUE_4',
        acscod_0: 'VALUE_4',
        roualt_0: 'VALUE_4',
        laswordat_0: new Date().toISOString().split('T')[0],
        lasworqty_0: 42.0,
        wormaxqty_0: 42.0,
        worminqty_0: 42.0,
        plnnum_0: 'VALUE_4',
        wortyp_0: 'VALUE_4',
        timuomcod_0: new Date().toISOString(),
        rouenddat_0: new Date().toISOString().split('T')[0],
        roustrdat_0: new Date().toISOString().split('T')[0],
        usesta_0: 1,
        roudesaxx_0: 'Désignation entête 4',
        roudes_0: 'VALUE_4',
        roupct_0: 'VALUE_4',
        texnum_0: 'VALUE_4',
      },
      {
        fcy_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        itmref_0: 'ROU0005',
        expnum_0: 'VALUE_5',
        cfmflg_0: 'VALUE_5',
        ident1_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_5',
        credat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'VALUE_5',
        acscod_0: 'VALUE_5',
        roualt_0: 'VALUE_5',
        laswordat_0: new Date().toISOString().split('T')[0],
        lasworqty_0: 52.5,
        wormaxqty_0: 52.5,
        worminqty_0: 52.5,
        plnnum_0: 'VALUE_5',
        wortyp_0: 'VALUE_5',
        timuomcod_0: new Date().toISOString(),
        rouenddat_0: new Date().toISOString().split('T')[0],
        roustrdat_0: new Date().toISOString().split('T')[0],
        usesta_0: 1,
        roudesaxx_0: 'Désignation entête 5',
        roudes_0: 'VALUE_5',
        roupct_0: 'VALUE_5',
        texnum_0: 'VALUE_5',
      },
      {
        fcy_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        itmref_0: 'ROU0006',
        expnum_0: 'VALUE_6',
        cfmflg_0: 'VALUE_6',
        ident1_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_6',
        credat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'VALUE_6',
        acscod_0: 'VALUE_6',
        roualt_0: 'VALUE_6',
        laswordat_0: new Date().toISOString().split('T')[0],
        lasworqty_0: 63.0,
        wormaxqty_0: 63.0,
        worminqty_0: 63.0,
        plnnum_0: 'VALUE_6',
        wortyp_0: 'VALUE_6',
        timuomcod_0: new Date().toISOString(),
        rouenddat_0: new Date().toISOString().split('T')[0],
        roustrdat_0: new Date().toISOString().split('T')[0],
        usesta_0: 1,
        roudesaxx_0: 'Désignation entête 6',
        roudes_0: 'VALUE_6',
        roupct_0: 'VALUE_6',
        texnum_0: 'VALUE_6',
      },
      {
        fcy_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        itmref_0: 'ROU0007',
        expnum_0: 'VALUE_7',
        cfmflg_0: 'VALUE_7',
        ident1_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_7',
        credat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'VALUE_7',
        acscod_0: 'VALUE_7',
        roualt_0: 'VALUE_7',
        laswordat_0: new Date().toISOString().split('T')[0],
        lasworqty_0: 73.5,
        wormaxqty_0: 73.5,
        worminqty_0: 73.5,
        plnnum_0: 'VALUE_7',
        wortyp_0: 'VALUE_7',
        timuomcod_0: new Date().toISOString(),
        rouenddat_0: new Date().toISOString().split('T')[0],
        roustrdat_0: new Date().toISOString().split('T')[0],
        usesta_0: 1,
        roudesaxx_0: 'Désignation entête 7',
        roudes_0: 'VALUE_7',
        roupct_0: 'VALUE_7',
        texnum_0: 'VALUE_7',
      },
      {
        fcy_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        itmref_0: 'ROU0008',
        expnum_0: 'VALUE_8',
        cfmflg_0: 'VALUE_8',
        ident1_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_8',
        credat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'VALUE_8',
        acscod_0: 'VALUE_8',
        roualt_0: 'VALUE_8',
        laswordat_0: new Date().toISOString().split('T')[0],
        lasworqty_0: 84.0,
        wormaxqty_0: 84.0,
        worminqty_0: 84.0,
        plnnum_0: 'VALUE_8',
        wortyp_0: 'VALUE_8',
        timuomcod_0: new Date().toISOString(),
        rouenddat_0: new Date().toISOString().split('T')[0],
        roustrdat_0: new Date().toISOString().split('T')[0],
        usesta_0: 1,
        roudesaxx_0: 'Désignation entête 8',
        roudes_0: 'VALUE_8',
        roupct_0: 'VALUE_8',
        texnum_0: 'VALUE_8',
      },
      {
        fcy_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        itmref_0: 'ROU0009',
        expnum_0: 'VALUE_9',
        cfmflg_0: 'VALUE_9',
        ident1_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_9',
        credat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'VALUE_9',
        acscod_0: 'VALUE_9',
        roualt_0: 'VALUE_9',
        laswordat_0: new Date().toISOString().split('T')[0],
        lasworqty_0: 94.5,
        wormaxqty_0: 94.5,
        worminqty_0: 94.5,
        plnnum_0: 'VALUE_9',
        wortyp_0: 'VALUE_9',
        timuomcod_0: new Date().toISOString(),
        rouenddat_0: new Date().toISOString().split('T')[0],
        roustrdat_0: new Date().toISOString().split('T')[0],
        usesta_0: 1,
        roudesaxx_0: 'Désignation entête 9',
        roudes_0: 'VALUE_9',
        roupct_0: 'VALUE_9',
        texnum_0: 'VALUE_9',
      },
      {
        fcy_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        itmref_0: 'ROU0010',
        expnum_0: 'VALUE_10',
        cfmflg_0: 'VALUE_10',
        ident1_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        updusr_0: 'VALUE_10',
        credat_0: new Date().toISOString().split('T')[0],
        cfgvcrnum_0: 'VALUE_10',
        acscod_0: 'VALUE_10',
        roualt_0: 'VALUE_10',
        laswordat_0: new Date().toISOString().split('T')[0],
        lasworqty_0: 105.0,
        wormaxqty_0: 105.0,
        worminqty_0: 105.0,
        plnnum_0: 'VALUE_10',
        wortyp_0: 'VALUE_10',
        timuomcod_0: new Date().toISOString(),
        rouenddat_0: new Date().toISOString().split('T')[0],
        roustrdat_0: new Date().toISOString().split('T')[0],
        usesta_0: 1,
        roudesaxx_0: 'Désignation entête 10',
        roudes_0: 'VALUE_10',
        roupct_0: 'VALUE_10',
        texnum_0: 'VALUE_10',
      },
    ]

    await Database.table('routing').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans routing`)
  }
}
