import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour MFGHEAD
    const data = [
      {
        clodat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_1',
        trkfirstc_0: 'VALUE_1',
        trklast_0: 'VALUE_1',
        trklastc_0: 'VALUE_1',
        xtypobj_0: 'VALUE_1',
        plnfcy_0: 'VALUE_1',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_1',
        mfgmod_0: 'VALUE_1',
        rejcplqty_0: 10.5,
        opeclenbr_0: 'VALUE_1',
        scdmod_0: 'VALUE_1',
        ltiredcoe_0: 'VALUE_1',
        quacplqty_0: 10.5,
        avamfgqty_0: 10.5,
        clcscdlti_0: 'VALUE_1',
        typmod_0: 'VALUE_1',
        scdflg_0: 'VALUE_1',
        matlinnbr_0: 'VALUE_1',
        detallnbr_0: 'VALUE_1',
        ovrallnbr_0: 'VALUE_1',
        shtmatnbr_0: 'VALUE_1',
        prpmatnbr_0: 'VALUE_1',
        prpsta_0: 1,
        mfgtrkflg_0: 'VALUE_1',
        credat_0: new Date().toISOString().split('T')[0],
        x4numint_0: 'VALUE_1',
        wggflg_0: 'VALUE_1',
        wggsta_0: 1,
        cplqty_0: 10.5,
        itmlinnbr_0: 'VALUE_1',
        opelinnbr_0: 'VALUE_1',
        itmclenbr_0: 'VALUE_1',
        matclenbr_0: 'VALUE_1',
        infcapstr_0: 'VALUE_1',
        infcapend_0: 'VALUE_1',
        roualt_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_1',
        objdat_0: new Date().toISOString().split('T')[0],
        fitcapstr_0: 'VALUE_1',
        fitcapend_0: 'VALUE_1',
        mfgnum_0: 'MFG0001',
        allsta_0: 1,
        mfgtex_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        extqty_0: 10.5,
        enddat_0: new Date().toISOString().split('T')[0],
        optusr_0: 'VALUE_1',
        optflg_0: 'VALUE_1',
        xobj1_0: 'VALUE_1',
        xobj2_0: 'VALUE_1',
        xblocage_0: 'VALUE_1',
        cfmflg_0: 'VALUE_1',
        stu_0: 'VALUE_1',
        updusr_0: 'VALUE_1',
        rounum_0: 'VALUE_1',
        rmnextqty_0: 10.5,
        mfgpio_0: 'VALUE_1',
        xncflg_0: 'VALUE_1',
        xacflg_0: 'VALUE_1',
        xtypof_0: 'VALUE_1',
        strdat_0: new Date().toISOString().split('T')[0],
        xstaoutc_0: 1,
        xstaclo_0: 1,
        xdescdat_0: 'Date descente 1',
        xdesctim_0: new Date().toISOString(),
        x4panne_0: 'VALUE_1',
        xsstypot_0: 'VALUE_1',
        xnivmntc_0: 'VALUE_1',
        x4interdat_0: new Date().toISOString().split('T')[0],
        susflg_0: 'VALUE_1',
        mtoref_0: 'VALUE_1',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        sinum_0: 'VALUE_1',
        gfspubtim_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        npipro_0: 'VALUE_1',
        x4savori_0: 'VALUE_1',
        x1prpsta_0: 1,
        x1wavprep_0: 'VALUE_1',
        x1pdpgen_0: 'VALUE_1',
        upddattim_0: new Date().toISOString().split('T')[0],
        roueccmaj_0: 'VALUE_1',
        roueccmin_0: 'VALUE_1',
        latenddat_0: new Date().toISOString().split('T')[0],
        xobj3_0: 'VALUE_1',
        earstrdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_1',
      },
      {
        clodat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_2',
        trkfirstc_0: 'VALUE_2',
        trklast_0: 'VALUE_2',
        trklastc_0: 'VALUE_2',
        xtypobj_0: 'VALUE_2',
        plnfcy_0: 'VALUE_2',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_2',
        mfgmod_0: 'VALUE_2',
        rejcplqty_0: 21.0,
        opeclenbr_0: 'VALUE_2',
        scdmod_0: 'VALUE_2',
        ltiredcoe_0: 'VALUE_2',
        quacplqty_0: 21.0,
        avamfgqty_0: 21.0,
        clcscdlti_0: 'VALUE_2',
        typmod_0: 'VALUE_2',
        scdflg_0: 'VALUE_2',
        matlinnbr_0: 'VALUE_2',
        detallnbr_0: 'VALUE_2',
        ovrallnbr_0: 'VALUE_2',
        shtmatnbr_0: 'VALUE_2',
        prpmatnbr_0: 'VALUE_2',
        prpsta_0: 2,
        mfgtrkflg_0: 'VALUE_2',
        credat_0: new Date().toISOString().split('T')[0],
        x4numint_0: 'VALUE_2',
        wggflg_0: 'VALUE_2',
        wggsta_0: 2,
        cplqty_0: 21.0,
        itmlinnbr_0: 'VALUE_2',
        opelinnbr_0: 'VALUE_2',
        itmclenbr_0: 'VALUE_2',
        matclenbr_0: 'VALUE_2',
        infcapstr_0: 'VALUE_2',
        infcapend_0: 'VALUE_2',
        roualt_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_2',
        objdat_0: new Date().toISOString().split('T')[0],
        fitcapstr_0: 'VALUE_2',
        fitcapend_0: 'VALUE_2',
        mfgnum_0: 'MFG0002',
        allsta_0: 2,
        mfgtex_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        extqty_0: 21.0,
        enddat_0: new Date().toISOString().split('T')[0],
        optusr_0: 'VALUE_2',
        optflg_0: 'VALUE_2',
        xobj1_0: 'VALUE_2',
        xobj2_0: 'VALUE_2',
        xblocage_0: 'VALUE_2',
        cfmflg_0: 'VALUE_2',
        stu_0: 'VALUE_2',
        updusr_0: 'VALUE_2',
        rounum_0: 'VALUE_2',
        rmnextqty_0: 21.0,
        mfgpio_0: 'VALUE_2',
        xncflg_0: 'VALUE_2',
        xacflg_0: 'VALUE_2',
        xtypof_0: 'VALUE_2',
        strdat_0: new Date().toISOString().split('T')[0],
        xstaoutc_0: 2,
        xstaclo_0: 2,
        xdescdat_0: 'Date descente 2',
        xdesctim_0: new Date().toISOString(),
        x4panne_0: 'VALUE_2',
        xsstypot_0: 'VALUE_2',
        xnivmntc_0: 'VALUE_2',
        x4interdat_0: new Date().toISOString().split('T')[0],
        susflg_0: 'VALUE_2',
        mtoref_0: 'VALUE_2',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        sinum_0: 'VALUE_2',
        gfspubtim_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        npipro_0: 'VALUE_2',
        x4savori_0: 'VALUE_2',
        x1prpsta_0: 2,
        x1wavprep_0: 'VALUE_2',
        x1pdpgen_0: 'VALUE_2',
        upddattim_0: new Date().toISOString().split('T')[0],
        roueccmaj_0: 'VALUE_2',
        roueccmin_0: 'VALUE_2',
        latenddat_0: new Date().toISOString().split('T')[0],
        xobj3_0: 'VALUE_2',
        earstrdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_2',
      },
      {
        clodat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_3',
        trkfirstc_0: 'VALUE_3',
        trklast_0: 'VALUE_3',
        trklastc_0: 'VALUE_3',
        xtypobj_0: 'VALUE_3',
        plnfcy_0: 'VALUE_3',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_3',
        mfgmod_0: 'VALUE_3',
        rejcplqty_0: 31.5,
        opeclenbr_0: 'VALUE_3',
        scdmod_0: 'VALUE_3',
        ltiredcoe_0: 'VALUE_3',
        quacplqty_0: 31.5,
        avamfgqty_0: 31.5,
        clcscdlti_0: 'VALUE_3',
        typmod_0: 'VALUE_3',
        scdflg_0: 'VALUE_3',
        matlinnbr_0: 'VALUE_3',
        detallnbr_0: 'VALUE_3',
        ovrallnbr_0: 'VALUE_3',
        shtmatnbr_0: 'VALUE_3',
        prpmatnbr_0: 'VALUE_3',
        prpsta_0: 3,
        mfgtrkflg_0: 'VALUE_3',
        credat_0: new Date().toISOString().split('T')[0],
        x4numint_0: 'VALUE_3',
        wggflg_0: 'VALUE_3',
        wggsta_0: 3,
        cplqty_0: 31.5,
        itmlinnbr_0: 'VALUE_3',
        opelinnbr_0: 'VALUE_3',
        itmclenbr_0: 'VALUE_3',
        matclenbr_0: 'VALUE_3',
        infcapstr_0: 'VALUE_3',
        infcapend_0: 'VALUE_3',
        roualt_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_3',
        objdat_0: new Date().toISOString().split('T')[0],
        fitcapstr_0: 'VALUE_3',
        fitcapend_0: 'VALUE_3',
        mfgnum_0: 'MFG0003',
        allsta_0: 3,
        mfgtex_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        extqty_0: 31.5,
        enddat_0: new Date().toISOString().split('T')[0],
        optusr_0: 'VALUE_3',
        optflg_0: 'VALUE_3',
        xobj1_0: 'VALUE_3',
        xobj2_0: 'VALUE_3',
        xblocage_0: 'VALUE_3',
        cfmflg_0: 'VALUE_3',
        stu_0: 'VALUE_3',
        updusr_0: 'VALUE_3',
        rounum_0: 'VALUE_3',
        rmnextqty_0: 31.5,
        mfgpio_0: 'VALUE_3',
        xncflg_0: 'VALUE_3',
        xacflg_0: 'VALUE_3',
        xtypof_0: 'VALUE_3',
        strdat_0: new Date().toISOString().split('T')[0],
        xstaoutc_0: 3,
        xstaclo_0: 3,
        xdescdat_0: 'Date descente 3',
        xdesctim_0: new Date().toISOString(),
        x4panne_0: 'VALUE_3',
        xsstypot_0: 'VALUE_3',
        xnivmntc_0: 'VALUE_3',
        x4interdat_0: new Date().toISOString().split('T')[0],
        susflg_0: 'VALUE_3',
        mtoref_0: 'VALUE_3',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        sinum_0: 'VALUE_3',
        gfspubtim_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        npipro_0: 'VALUE_3',
        x4savori_0: 'VALUE_3',
        x1prpsta_0: 3,
        x1wavprep_0: 'VALUE_3',
        x1pdpgen_0: 'VALUE_3',
        upddattim_0: new Date().toISOString().split('T')[0],
        roueccmaj_0: 'VALUE_3',
        roueccmin_0: 'VALUE_3',
        latenddat_0: new Date().toISOString().split('T')[0],
        xobj3_0: 'VALUE_3',
        earstrdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_3',
      },
      {
        clodat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_4',
        trkfirstc_0: 'VALUE_4',
        trklast_0: 'VALUE_4',
        trklastc_0: 'VALUE_4',
        xtypobj_0: 'VALUE_4',
        plnfcy_0: 'VALUE_4',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_4',
        mfgmod_0: 'VALUE_4',
        rejcplqty_0: 42.0,
        opeclenbr_0: 'VALUE_4',
        scdmod_0: 'VALUE_4',
        ltiredcoe_0: 'VALUE_4',
        quacplqty_0: 42.0,
        avamfgqty_0: 42.0,
        clcscdlti_0: 'VALUE_4',
        typmod_0: 'VALUE_4',
        scdflg_0: 'VALUE_4',
        matlinnbr_0: 'VALUE_4',
        detallnbr_0: 'VALUE_4',
        ovrallnbr_0: 'VALUE_4',
        shtmatnbr_0: 'VALUE_4',
        prpmatnbr_0: 'VALUE_4',
        prpsta_0: 4,
        mfgtrkflg_0: 'VALUE_4',
        credat_0: new Date().toISOString().split('T')[0],
        x4numint_0: 'VALUE_4',
        wggflg_0: 'VALUE_4',
        wggsta_0: 4,
        cplqty_0: 42.0,
        itmlinnbr_0: 'VALUE_4',
        opelinnbr_0: 'VALUE_4',
        itmclenbr_0: 'VALUE_4',
        matclenbr_0: 'VALUE_4',
        infcapstr_0: 'VALUE_4',
        infcapend_0: 'VALUE_4',
        roualt_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_4',
        objdat_0: new Date().toISOString().split('T')[0],
        fitcapstr_0: 'VALUE_4',
        fitcapend_0: 'VALUE_4',
        mfgnum_0: 'MFG0004',
        allsta_0: 4,
        mfgtex_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        extqty_0: 42.0,
        enddat_0: new Date().toISOString().split('T')[0],
        optusr_0: 'VALUE_4',
        optflg_0: 'VALUE_4',
        xobj1_0: 'VALUE_4',
        xobj2_0: 'VALUE_4',
        xblocage_0: 'VALUE_4',
        cfmflg_0: 'VALUE_4',
        stu_0: 'VALUE_4',
        updusr_0: 'VALUE_4',
        rounum_0: 'VALUE_4',
        rmnextqty_0: 42.0,
        mfgpio_0: 'VALUE_4',
        xncflg_0: 'VALUE_4',
        xacflg_0: 'VALUE_4',
        xtypof_0: 'VALUE_4',
        strdat_0: new Date().toISOString().split('T')[0],
        xstaoutc_0: 4,
        xstaclo_0: 4,
        xdescdat_0: 'Date descente 4',
        xdesctim_0: new Date().toISOString(),
        x4panne_0: 'VALUE_4',
        xsstypot_0: 'VALUE_4',
        xnivmntc_0: 'VALUE_4',
        x4interdat_0: new Date().toISOString().split('T')[0],
        susflg_0: 'VALUE_4',
        mtoref_0: 'VALUE_4',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        sinum_0: 'VALUE_4',
        gfspubtim_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        npipro_0: 'VALUE_4',
        x4savori_0: 'VALUE_4',
        x1prpsta_0: 4,
        x1wavprep_0: 'VALUE_4',
        x1pdpgen_0: 'VALUE_4',
        upddattim_0: new Date().toISOString().split('T')[0],
        roueccmaj_0: 'VALUE_4',
        roueccmin_0: 'VALUE_4',
        latenddat_0: new Date().toISOString().split('T')[0],
        xobj3_0: 'VALUE_4',
        earstrdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_4',
      },
      {
        clodat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_5',
        trkfirstc_0: 'VALUE_5',
        trklast_0: 'VALUE_5',
        trklastc_0: 'VALUE_5',
        xtypobj_0: 'VALUE_5',
        plnfcy_0: 'VALUE_5',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_5',
        mfgmod_0: 'VALUE_5',
        rejcplqty_0: 52.5,
        opeclenbr_0: 'VALUE_5',
        scdmod_0: 'VALUE_5',
        ltiredcoe_0: 'VALUE_5',
        quacplqty_0: 52.5,
        avamfgqty_0: 52.5,
        clcscdlti_0: 'VALUE_5',
        typmod_0: 'VALUE_5',
        scdflg_0: 'VALUE_5',
        matlinnbr_0: 'VALUE_5',
        detallnbr_0: 'VALUE_5',
        ovrallnbr_0: 'VALUE_5',
        shtmatnbr_0: 'VALUE_5',
        prpmatnbr_0: 'VALUE_5',
        prpsta_0: 5,
        mfgtrkflg_0: 'VALUE_5',
        credat_0: new Date().toISOString().split('T')[0],
        x4numint_0: 'VALUE_5',
        wggflg_0: 'VALUE_5',
        wggsta_0: 5,
        cplqty_0: 52.5,
        itmlinnbr_0: 'VALUE_5',
        opelinnbr_0: 'VALUE_5',
        itmclenbr_0: 'VALUE_5',
        matclenbr_0: 'VALUE_5',
        infcapstr_0: 'VALUE_5',
        infcapend_0: 'VALUE_5',
        roualt_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_5',
        objdat_0: new Date().toISOString().split('T')[0],
        fitcapstr_0: 'VALUE_5',
        fitcapend_0: 'VALUE_5',
        mfgnum_0: 'MFG0005',
        allsta_0: 5,
        mfgtex_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        extqty_0: 52.5,
        enddat_0: new Date().toISOString().split('T')[0],
        optusr_0: 'VALUE_5',
        optflg_0: 'VALUE_5',
        xobj1_0: 'VALUE_5',
        xobj2_0: 'VALUE_5',
        xblocage_0: 'VALUE_5',
        cfmflg_0: 'VALUE_5',
        stu_0: 'VALUE_5',
        updusr_0: 'VALUE_5',
        rounum_0: 'VALUE_5',
        rmnextqty_0: 52.5,
        mfgpio_0: 'VALUE_5',
        xncflg_0: 'VALUE_5',
        xacflg_0: 'VALUE_5',
        xtypof_0: 'VALUE_5',
        strdat_0: new Date().toISOString().split('T')[0],
        xstaoutc_0: 5,
        xstaclo_0: 5,
        xdescdat_0: 'Date descente 5',
        xdesctim_0: new Date().toISOString(),
        x4panne_0: 'VALUE_5',
        xsstypot_0: 'VALUE_5',
        xnivmntc_0: 'VALUE_5',
        x4interdat_0: new Date().toISOString().split('T')[0],
        susflg_0: 'VALUE_5',
        mtoref_0: 'VALUE_5',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        sinum_0: 'VALUE_5',
        gfspubtim_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        npipro_0: 'VALUE_5',
        x4savori_0: 'VALUE_5',
        x1prpsta_0: 5,
        x1wavprep_0: 'VALUE_5',
        x1pdpgen_0: 'VALUE_5',
        upddattim_0: new Date().toISOString().split('T')[0],
        roueccmaj_0: 'VALUE_5',
        roueccmin_0: 'VALUE_5',
        latenddat_0: new Date().toISOString().split('T')[0],
        xobj3_0: 'VALUE_5',
        earstrdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_5',
      },
      {
        clodat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_6',
        trkfirstc_0: 'VALUE_6',
        trklast_0: 'VALUE_6',
        trklastc_0: 'VALUE_6',
        xtypobj_0: 'VALUE_6',
        plnfcy_0: 'VALUE_6',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_6',
        mfgmod_0: 'VALUE_6',
        rejcplqty_0: 63.0,
        opeclenbr_0: 'VALUE_6',
        scdmod_0: 'VALUE_6',
        ltiredcoe_0: 'VALUE_6',
        quacplqty_0: 63.0,
        avamfgqty_0: 63.0,
        clcscdlti_0: 'VALUE_6',
        typmod_0: 'VALUE_6',
        scdflg_0: 'VALUE_6',
        matlinnbr_0: 'VALUE_6',
        detallnbr_0: 'VALUE_6',
        ovrallnbr_0: 'VALUE_6',
        shtmatnbr_0: 'VALUE_6',
        prpmatnbr_0: 'VALUE_6',
        prpsta_0: 6,
        mfgtrkflg_0: 'VALUE_6',
        credat_0: new Date().toISOString().split('T')[0],
        x4numint_0: 'VALUE_6',
        wggflg_0: 'VALUE_6',
        wggsta_0: 6,
        cplqty_0: 63.0,
        itmlinnbr_0: 'VALUE_6',
        opelinnbr_0: 'VALUE_6',
        itmclenbr_0: 'VALUE_6',
        matclenbr_0: 'VALUE_6',
        infcapstr_0: 'VALUE_6',
        infcapend_0: 'VALUE_6',
        roualt_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_6',
        objdat_0: new Date().toISOString().split('T')[0],
        fitcapstr_0: 'VALUE_6',
        fitcapend_0: 'VALUE_6',
        mfgnum_0: 'MFG0006',
        allsta_0: 6,
        mfgtex_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        extqty_0: 63.0,
        enddat_0: new Date().toISOString().split('T')[0],
        optusr_0: 'VALUE_6',
        optflg_0: 'VALUE_6',
        xobj1_0: 'VALUE_6',
        xobj2_0: 'VALUE_6',
        xblocage_0: 'VALUE_6',
        cfmflg_0: 'VALUE_6',
        stu_0: 'VALUE_6',
        updusr_0: 'VALUE_6',
        rounum_0: 'VALUE_6',
        rmnextqty_0: 63.0,
        mfgpio_0: 'VALUE_6',
        xncflg_0: 'VALUE_6',
        xacflg_0: 'VALUE_6',
        xtypof_0: 'VALUE_6',
        strdat_0: new Date().toISOString().split('T')[0],
        xstaoutc_0: 6,
        xstaclo_0: 6,
        xdescdat_0: 'Date descente 6',
        xdesctim_0: new Date().toISOString(),
        x4panne_0: 'VALUE_6',
        xsstypot_0: 'VALUE_6',
        xnivmntc_0: 'VALUE_6',
        x4interdat_0: new Date().toISOString().split('T')[0],
        susflg_0: 'VALUE_6',
        mtoref_0: 'VALUE_6',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        sinum_0: 'VALUE_6',
        gfspubtim_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        npipro_0: 'VALUE_6',
        x4savori_0: 'VALUE_6',
        x1prpsta_0: 6,
        x1wavprep_0: 'VALUE_6',
        x1pdpgen_0: 'VALUE_6',
        upddattim_0: new Date().toISOString().split('T')[0],
        roueccmaj_0: 'VALUE_6',
        roueccmin_0: 'VALUE_6',
        latenddat_0: new Date().toISOString().split('T')[0],
        xobj3_0: 'VALUE_6',
        earstrdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_6',
      },
      {
        clodat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_7',
        trkfirstc_0: 'VALUE_7',
        trklast_0: 'VALUE_7',
        trklastc_0: 'VALUE_7',
        xtypobj_0: 'VALUE_7',
        plnfcy_0: 'VALUE_7',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_7',
        mfgmod_0: 'VALUE_7',
        rejcplqty_0: 73.5,
        opeclenbr_0: 'VALUE_7',
        scdmod_0: 'VALUE_7',
        ltiredcoe_0: 'VALUE_7',
        quacplqty_0: 73.5,
        avamfgqty_0: 73.5,
        clcscdlti_0: 'VALUE_7',
        typmod_0: 'VALUE_7',
        scdflg_0: 'VALUE_7',
        matlinnbr_0: 'VALUE_7',
        detallnbr_0: 'VALUE_7',
        ovrallnbr_0: 'VALUE_7',
        shtmatnbr_0: 'VALUE_7',
        prpmatnbr_0: 'VALUE_7',
        prpsta_0: 7,
        mfgtrkflg_0: 'VALUE_7',
        credat_0: new Date().toISOString().split('T')[0],
        x4numint_0: 'VALUE_7',
        wggflg_0: 'VALUE_7',
        wggsta_0: 7,
        cplqty_0: 73.5,
        itmlinnbr_0: 'VALUE_7',
        opelinnbr_0: 'VALUE_7',
        itmclenbr_0: 'VALUE_7',
        matclenbr_0: 'VALUE_7',
        infcapstr_0: 'VALUE_7',
        infcapend_0: 'VALUE_7',
        roualt_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_7',
        objdat_0: new Date().toISOString().split('T')[0],
        fitcapstr_0: 'VALUE_7',
        fitcapend_0: 'VALUE_7',
        mfgnum_0: 'MFG0007',
        allsta_0: 7,
        mfgtex_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        extqty_0: 73.5,
        enddat_0: new Date().toISOString().split('T')[0],
        optusr_0: 'VALUE_7',
        optflg_0: 'VALUE_7',
        xobj1_0: 'VALUE_7',
        xobj2_0: 'VALUE_7',
        xblocage_0: 'VALUE_7',
        cfmflg_0: 'VALUE_7',
        stu_0: 'VALUE_7',
        updusr_0: 'VALUE_7',
        rounum_0: 'VALUE_7',
        rmnextqty_0: 73.5,
        mfgpio_0: 'VALUE_7',
        xncflg_0: 'VALUE_7',
        xacflg_0: 'VALUE_7',
        xtypof_0: 'VALUE_7',
        strdat_0: new Date().toISOString().split('T')[0],
        xstaoutc_0: 7,
        xstaclo_0: 7,
        xdescdat_0: 'Date descente 7',
        xdesctim_0: new Date().toISOString(),
        x4panne_0: 'VALUE_7',
        xsstypot_0: 'VALUE_7',
        xnivmntc_0: 'VALUE_7',
        x4interdat_0: new Date().toISOString().split('T')[0],
        susflg_0: 'VALUE_7',
        mtoref_0: 'VALUE_7',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        sinum_0: 'VALUE_7',
        gfspubtim_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        npipro_0: 'VALUE_7',
        x4savori_0: 'VALUE_7',
        x1prpsta_0: 7,
        x1wavprep_0: 'VALUE_7',
        x1pdpgen_0: 'VALUE_7',
        upddattim_0: new Date().toISOString().split('T')[0],
        roueccmaj_0: 'VALUE_7',
        roueccmin_0: 'VALUE_7',
        latenddat_0: new Date().toISOString().split('T')[0],
        xobj3_0: 'VALUE_7',
        earstrdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_7',
      },
      {
        clodat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_8',
        trkfirstc_0: 'VALUE_8',
        trklast_0: 'VALUE_8',
        trklastc_0: 'VALUE_8',
        xtypobj_0: 'VALUE_8',
        plnfcy_0: 'VALUE_8',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_8',
        mfgmod_0: 'VALUE_8',
        rejcplqty_0: 84.0,
        opeclenbr_0: 'VALUE_8',
        scdmod_0: 'VALUE_8',
        ltiredcoe_0: 'VALUE_8',
        quacplqty_0: 84.0,
        avamfgqty_0: 84.0,
        clcscdlti_0: 'VALUE_8',
        typmod_0: 'VALUE_8',
        scdflg_0: 'VALUE_8',
        matlinnbr_0: 'VALUE_8',
        detallnbr_0: 'VALUE_8',
        ovrallnbr_0: 'VALUE_8',
        shtmatnbr_0: 'VALUE_8',
        prpmatnbr_0: 'VALUE_8',
        prpsta_0: 8,
        mfgtrkflg_0: 'VALUE_8',
        credat_0: new Date().toISOString().split('T')[0],
        x4numint_0: 'VALUE_8',
        wggflg_0: 'VALUE_8',
        wggsta_0: 8,
        cplqty_0: 84.0,
        itmlinnbr_0: 'VALUE_8',
        opelinnbr_0: 'VALUE_8',
        itmclenbr_0: 'VALUE_8',
        matclenbr_0: 'VALUE_8',
        infcapstr_0: 'VALUE_8',
        infcapend_0: 'VALUE_8',
        roualt_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_8',
        objdat_0: new Date().toISOString().split('T')[0],
        fitcapstr_0: 'VALUE_8',
        fitcapend_0: 'VALUE_8',
        mfgnum_0: 'MFG0008',
        allsta_0: 8,
        mfgtex_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        extqty_0: 84.0,
        enddat_0: new Date().toISOString().split('T')[0],
        optusr_0: 'VALUE_8',
        optflg_0: 'VALUE_8',
        xobj1_0: 'VALUE_8',
        xobj2_0: 'VALUE_8',
        xblocage_0: 'VALUE_8',
        cfmflg_0: 'VALUE_8',
        stu_0: 'VALUE_8',
        updusr_0: 'VALUE_8',
        rounum_0: 'VALUE_8',
        rmnextqty_0: 84.0,
        mfgpio_0: 'VALUE_8',
        xncflg_0: 'VALUE_8',
        xacflg_0: 'VALUE_8',
        xtypof_0: 'VALUE_8',
        strdat_0: new Date().toISOString().split('T')[0],
        xstaoutc_0: 8,
        xstaclo_0: 8,
        xdescdat_0: 'Date descente 8',
        xdesctim_0: new Date().toISOString(),
        x4panne_0: 'VALUE_8',
        xsstypot_0: 'VALUE_8',
        xnivmntc_0: 'VALUE_8',
        x4interdat_0: new Date().toISOString().split('T')[0],
        susflg_0: 'VALUE_8',
        mtoref_0: 'VALUE_8',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        sinum_0: 'VALUE_8',
        gfspubtim_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        npipro_0: 'VALUE_8',
        x4savori_0: 'VALUE_8',
        x1prpsta_0: 8,
        x1wavprep_0: 'VALUE_8',
        x1pdpgen_0: 'VALUE_8',
        upddattim_0: new Date().toISOString().split('T')[0],
        roueccmaj_0: 'VALUE_8',
        roueccmin_0: 'VALUE_8',
        latenddat_0: new Date().toISOString().split('T')[0],
        xobj3_0: 'VALUE_8',
        earstrdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_8',
      },
      {
        clodat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_9',
        trkfirstc_0: 'VALUE_9',
        trklast_0: 'VALUE_9',
        trklastc_0: 'VALUE_9',
        xtypobj_0: 'VALUE_9',
        plnfcy_0: 'VALUE_9',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_9',
        mfgmod_0: 'VALUE_9',
        rejcplqty_0: 94.5,
        opeclenbr_0: 'VALUE_9',
        scdmod_0: 'VALUE_9',
        ltiredcoe_0: 'VALUE_9',
        quacplqty_0: 94.5,
        avamfgqty_0: 94.5,
        clcscdlti_0: 'VALUE_9',
        typmod_0: 'VALUE_9',
        scdflg_0: 'VALUE_9',
        matlinnbr_0: 'VALUE_9',
        detallnbr_0: 'VALUE_9',
        ovrallnbr_0: 'VALUE_9',
        shtmatnbr_0: 'VALUE_9',
        prpmatnbr_0: 'VALUE_9',
        prpsta_0: 9,
        mfgtrkflg_0: 'VALUE_9',
        credat_0: new Date().toISOString().split('T')[0],
        x4numint_0: 'VALUE_9',
        wggflg_0: 'VALUE_9',
        wggsta_0: 9,
        cplqty_0: 94.5,
        itmlinnbr_0: 'VALUE_9',
        opelinnbr_0: 'VALUE_9',
        itmclenbr_0: 'VALUE_9',
        matclenbr_0: 'VALUE_9',
        infcapstr_0: 'VALUE_9',
        infcapend_0: 'VALUE_9',
        roualt_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_9',
        objdat_0: new Date().toISOString().split('T')[0],
        fitcapstr_0: 'VALUE_9',
        fitcapend_0: 'VALUE_9',
        mfgnum_0: 'MFG0009',
        allsta_0: 9,
        mfgtex_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        extqty_0: 94.5,
        enddat_0: new Date().toISOString().split('T')[0],
        optusr_0: 'VALUE_9',
        optflg_0: 'VALUE_9',
        xobj1_0: 'VALUE_9',
        xobj2_0: 'VALUE_9',
        xblocage_0: 'VALUE_9',
        cfmflg_0: 'VALUE_9',
        stu_0: 'VALUE_9',
        updusr_0: 'VALUE_9',
        rounum_0: 'VALUE_9',
        rmnextqty_0: 94.5,
        mfgpio_0: 'VALUE_9',
        xncflg_0: 'VALUE_9',
        xacflg_0: 'VALUE_9',
        xtypof_0: 'VALUE_9',
        strdat_0: new Date().toISOString().split('T')[0],
        xstaoutc_0: 9,
        xstaclo_0: 9,
        xdescdat_0: 'Date descente 9',
        xdesctim_0: new Date().toISOString(),
        x4panne_0: 'VALUE_9',
        xsstypot_0: 'VALUE_9',
        xnivmntc_0: 'VALUE_9',
        x4interdat_0: new Date().toISOString().split('T')[0],
        susflg_0: 'VALUE_9',
        mtoref_0: 'VALUE_9',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        sinum_0: 'VALUE_9',
        gfspubtim_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        npipro_0: 'VALUE_9',
        x4savori_0: 'VALUE_9',
        x1prpsta_0: 9,
        x1wavprep_0: 'VALUE_9',
        x1pdpgen_0: 'VALUE_9',
        upddattim_0: new Date().toISOString().split('T')[0],
        roueccmaj_0: 'VALUE_9',
        roueccmin_0: 'VALUE_9',
        latenddat_0: new Date().toISOString().split('T')[0],
        xobj3_0: 'VALUE_9',
        earstrdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_9',
      },
      {
        clodat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_10',
        trkfirstc_0: 'VALUE_10',
        trklast_0: 'VALUE_10',
        trklastc_0: 'VALUE_10',
        xtypobj_0: 'VALUE_10',
        plnfcy_0: 'VALUE_10',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_10',
        mfgmod_0: 'VALUE_10',
        rejcplqty_0: 105.0,
        opeclenbr_0: 'VALUE_10',
        scdmod_0: 'VALUE_10',
        ltiredcoe_0: 'VALUE_10',
        quacplqty_0: 105.0,
        avamfgqty_0: 105.0,
        clcscdlti_0: 'VALUE_10',
        typmod_0: 'VALUE_10',
        scdflg_0: 'VALUE_10',
        matlinnbr_0: 'VALUE_10',
        detallnbr_0: 'VALUE_10',
        ovrallnbr_0: 'VALUE_10',
        shtmatnbr_0: 'VALUE_10',
        prpmatnbr_0: 'VALUE_10',
        prpsta_0: 10,
        mfgtrkflg_0: 'VALUE_10',
        credat_0: new Date().toISOString().split('T')[0],
        x4numint_0: 'VALUE_10',
        wggflg_0: 'VALUE_10',
        wggsta_0: 10,
        cplqty_0: 105.0,
        itmlinnbr_0: 'VALUE_10',
        opelinnbr_0: 'VALUE_10',
        itmclenbr_0: 'VALUE_10',
        matclenbr_0: 'VALUE_10',
        infcapstr_0: 'VALUE_10',
        infcapend_0: 'VALUE_10',
        roualt_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        x4numdemand_0: 'VALUE_10',
        objdat_0: new Date().toISOString().split('T')[0],
        fitcapstr_0: 'VALUE_10',
        fitcapend_0: 'VALUE_10',
        mfgnum_0: 'MFG0010',
        allsta_0: 10,
        mfgtex_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        extqty_0: 105.0,
        enddat_0: new Date().toISOString().split('T')[0],
        optusr_0: 'VALUE_10',
        optflg_0: 'VALUE_10',
        xobj1_0: 'VALUE_10',
        xobj2_0: 'VALUE_10',
        xblocage_0: 'VALUE_10',
        cfmflg_0: 'VALUE_10',
        stu_0: 'VALUE_10',
        updusr_0: 'VALUE_10',
        rounum_0: 'VALUE_10',
        rmnextqty_0: 105.0,
        mfgpio_0: 'VALUE_10',
        xncflg_0: 'VALUE_10',
        xacflg_0: 'VALUE_10',
        xtypof_0: 'VALUE_10',
        strdat_0: new Date().toISOString().split('T')[0],
        xstaoutc_0: 10,
        xstaclo_0: 10,
        xdescdat_0: 'Date descente 10',
        xdesctim_0: new Date().toISOString(),
        x4panne_0: 'VALUE_10',
        xsstypot_0: 'VALUE_10',
        xnivmntc_0: 'VALUE_10',
        x4interdat_0: new Date().toISOString().split('T')[0],
        susflg_0: 'VALUE_10',
        mtoref_0: 'VALUE_10',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        sinum_0: 'VALUE_10',
        gfspubtim_0: new Date().toISOString(),
        credattim_0: new Date().toISOString().split('T')[0],
        npipro_0: 'VALUE_10',
        x4savori_0: 'VALUE_10',
        x1prpsta_0: 10,
        x1wavprep_0: 'VALUE_10',
        x1pdpgen_0: 'VALUE_10',
        upddattim_0: new Date().toISOString().split('T')[0],
        roueccmaj_0: 'VALUE_10',
        roueccmin_0: 'VALUE_10',
        latenddat_0: new Date().toISOString().split('T')[0],
        xobj3_0: 'VALUE_10',
        earstrdat_0: new Date().toISOString().split('T')[0],
        auuid_0: 'VALUE_10',
      },
    ]

    await Database.table('mfghead').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans mfghead`)
  }
}
