import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour MFGITM
    const data = [
      {
        cstflg_0: 'VALUE_1',
        updusr_0: 'VALUE_1',
        vcrnumori_0: 'VALUE_1',
        vcrtypori_0: 'VALUE_1',
        vcrlinori_0: 'VALUE_1',
        pjt_0: 'VALUE_1',
        tclcod_0: 'VALUE_1',
        rmnextqty_0: 10.5,
        lot_0: 'VALUE_1',
        mfgpio_0: 'VALUE_1',
        bomalt_0: 'VALUE_1',
        bpctypden_0: 'VALUE_1',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        fmi_0: 'VALUE_1',
        x4datref_0: 'MFG0001',
        itmtyp_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_1',
        eccvalmin_0: 'VALUE_1',
        xnbempr_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        trkfirstc_0: 'VALUE_1',
        trklastc_0: 'VALUE_1',
        itmlin_0: 'VALUE_1',
        plnfcy_0: 'VALUE_1',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_1',
        x4datper_0: new Date().toISOString().split('T')[0],
        itmsta_0: 1,
        wipnum_0: 'VALUE_1',
        mfgdes_0: 'Désignation OF 1',
        uom_0: 'VALUE_1',
        uomextqty_0: 10.5,
        uomstucoe_0: 'VALUE_1',
        rejcplqty_0: 10.5,
        quacplqty_0: 10.5,
        mfitrkflg_0: 'VALUE_1',
        clodat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_1',
        trklast_0: 'VALUE_1',
        tsicod_0: 'VALUE_1',
        cplqty_0: 10.5,
        basqty_0: 10.5,
        bomofs_0: 'VALUE_1',
        likqtycod_0: 10.5,
        qtyrnd_0: 10.5,
        likqty_0: 10.5,
        bomope_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        mfgnum_0: 'VALUE_1',
        abccls_0: 'VALUE_1',
        expnum_0: 'VALUE_1',
        bpcnum_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        mfglin_0: 'VALUE_1',
        extqty_0: 10.5,
        itmref_0: 'VALUE_1',
        vcrseqori_0: 'VALUE_1',
        xversionc_0: 'VALUE_1',
        planner_0: 'VALUE_1',
        stu_0: 'VALUE_1',
      },
      {
        cstflg_0: 'VALUE_2',
        updusr_0: 'VALUE_2',
        vcrnumori_0: 'VALUE_2',
        vcrtypori_0: 'VALUE_2',
        vcrlinori_0: 'VALUE_2',
        pjt_0: 'VALUE_2',
        tclcod_0: 'VALUE_2',
        rmnextqty_0: 21.0,
        lot_0: 'VALUE_2',
        mfgpio_0: 'VALUE_2',
        bomalt_0: 'VALUE_2',
        bpctypden_0: 'VALUE_2',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        fmi_0: 'VALUE_2',
        x4datref_0: 'MFG0002',
        itmtyp_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_2',
        eccvalmin_0: 'VALUE_2',
        xnbempr_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        trkfirstc_0: 'VALUE_2',
        trklastc_0: 'VALUE_2',
        itmlin_0: 'VALUE_2',
        plnfcy_0: 'VALUE_2',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_2',
        x4datper_0: new Date().toISOString().split('T')[0],
        itmsta_0: 2,
        wipnum_0: 'VALUE_2',
        mfgdes_0: 'Désignation OF 2',
        uom_0: 'VALUE_2',
        uomextqty_0: 21.0,
        uomstucoe_0: 'VALUE_2',
        rejcplqty_0: 21.0,
        quacplqty_0: 21.0,
        mfitrkflg_0: 'VALUE_2',
        clodat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_2',
        trklast_0: 'VALUE_2',
        tsicod_0: 'VALUE_2',
        cplqty_0: 21.0,
        basqty_0: 21.0,
        bomofs_0: 'VALUE_2',
        likqtycod_0: 21.0,
        qtyrnd_0: 21.0,
        likqty_0: 21.0,
        bomope_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        mfgnum_0: 'VALUE_2',
        abccls_0: 'VALUE_2',
        expnum_0: 'VALUE_2',
        bpcnum_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        mfglin_0: 'VALUE_2',
        extqty_0: 21.0,
        itmref_0: 'VALUE_2',
        vcrseqori_0: 'VALUE_2',
        xversionc_0: 'VALUE_2',
        planner_0: 'VALUE_2',
        stu_0: 'VALUE_2',
      },
      {
        cstflg_0: 'VALUE_3',
        updusr_0: 'VALUE_3',
        vcrnumori_0: 'VALUE_3',
        vcrtypori_0: 'VALUE_3',
        vcrlinori_0: 'VALUE_3',
        pjt_0: 'VALUE_3',
        tclcod_0: 'VALUE_3',
        rmnextqty_0: 31.5,
        lot_0: 'VALUE_3',
        mfgpio_0: 'VALUE_3',
        bomalt_0: 'VALUE_3',
        bpctypden_0: 'VALUE_3',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        fmi_0: 'VALUE_3',
        x4datref_0: 'MFG0003',
        itmtyp_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_3',
        eccvalmin_0: 'VALUE_3',
        xnbempr_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        trkfirstc_0: 'VALUE_3',
        trklastc_0: 'VALUE_3',
        itmlin_0: 'VALUE_3',
        plnfcy_0: 'VALUE_3',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_3',
        x4datper_0: new Date().toISOString().split('T')[0],
        itmsta_0: 3,
        wipnum_0: 'VALUE_3',
        mfgdes_0: 'Désignation OF 3',
        uom_0: 'VALUE_3',
        uomextqty_0: 31.5,
        uomstucoe_0: 'VALUE_3',
        rejcplqty_0: 31.5,
        quacplqty_0: 31.5,
        mfitrkflg_0: 'VALUE_3',
        clodat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_3',
        trklast_0: 'VALUE_3',
        tsicod_0: 'VALUE_3',
        cplqty_0: 31.5,
        basqty_0: 31.5,
        bomofs_0: 'VALUE_3',
        likqtycod_0: 31.5,
        qtyrnd_0: 31.5,
        likqty_0: 31.5,
        bomope_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        mfgnum_0: 'VALUE_3',
        abccls_0: 'VALUE_3',
        expnum_0: 'VALUE_3',
        bpcnum_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        mfglin_0: 'VALUE_3',
        extqty_0: 31.5,
        itmref_0: 'VALUE_3',
        vcrseqori_0: 'VALUE_3',
        xversionc_0: 'VALUE_3',
        planner_0: 'VALUE_3',
        stu_0: 'VALUE_3',
      },
      {
        cstflg_0: 'VALUE_4',
        updusr_0: 'VALUE_4',
        vcrnumori_0: 'VALUE_4',
        vcrtypori_0: 'VALUE_4',
        vcrlinori_0: 'VALUE_4',
        pjt_0: 'VALUE_4',
        tclcod_0: 'VALUE_4',
        rmnextqty_0: 42.0,
        lot_0: 'VALUE_4',
        mfgpio_0: 'VALUE_4',
        bomalt_0: 'VALUE_4',
        bpctypden_0: 'VALUE_4',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        fmi_0: 'VALUE_4',
        x4datref_0: 'MFG0004',
        itmtyp_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_4',
        eccvalmin_0: 'VALUE_4',
        xnbempr_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        trkfirstc_0: 'VALUE_4',
        trklastc_0: 'VALUE_4',
        itmlin_0: 'VALUE_4',
        plnfcy_0: 'VALUE_4',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_4',
        x4datper_0: new Date().toISOString().split('T')[0],
        itmsta_0: 4,
        wipnum_0: 'VALUE_4',
        mfgdes_0: 'Désignation OF 4',
        uom_0: 'VALUE_4',
        uomextqty_0: 42.0,
        uomstucoe_0: 'VALUE_4',
        rejcplqty_0: 42.0,
        quacplqty_0: 42.0,
        mfitrkflg_0: 'VALUE_4',
        clodat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_4',
        trklast_0: 'VALUE_4',
        tsicod_0: 'VALUE_4',
        cplqty_0: 42.0,
        basqty_0: 42.0,
        bomofs_0: 'VALUE_4',
        likqtycod_0: 42.0,
        qtyrnd_0: 42.0,
        likqty_0: 42.0,
        bomope_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        mfgnum_0: 'VALUE_4',
        abccls_0: 'VALUE_4',
        expnum_0: 'VALUE_4',
        bpcnum_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        mfglin_0: 'VALUE_4',
        extqty_0: 42.0,
        itmref_0: 'VALUE_4',
        vcrseqori_0: 'VALUE_4',
        xversionc_0: 'VALUE_4',
        planner_0: 'VALUE_4',
        stu_0: 'VALUE_4',
      },
      {
        cstflg_0: 'VALUE_5',
        updusr_0: 'VALUE_5',
        vcrnumori_0: 'VALUE_5',
        vcrtypori_0: 'VALUE_5',
        vcrlinori_0: 'VALUE_5',
        pjt_0: 'VALUE_5',
        tclcod_0: 'VALUE_5',
        rmnextqty_0: 52.5,
        lot_0: 'VALUE_5',
        mfgpio_0: 'VALUE_5',
        bomalt_0: 'VALUE_5',
        bpctypden_0: 'VALUE_5',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        fmi_0: 'VALUE_5',
        x4datref_0: 'MFG0005',
        itmtyp_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_5',
        eccvalmin_0: 'VALUE_5',
        xnbempr_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        trkfirstc_0: 'VALUE_5',
        trklastc_0: 'VALUE_5',
        itmlin_0: 'VALUE_5',
        plnfcy_0: 'VALUE_5',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_5',
        x4datper_0: new Date().toISOString().split('T')[0],
        itmsta_0: 5,
        wipnum_0: 'VALUE_5',
        mfgdes_0: 'Désignation OF 5',
        uom_0: 'VALUE_5',
        uomextqty_0: 52.5,
        uomstucoe_0: 'VALUE_5',
        rejcplqty_0: 52.5,
        quacplqty_0: 52.5,
        mfitrkflg_0: 'VALUE_5',
        clodat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_5',
        trklast_0: 'VALUE_5',
        tsicod_0: 'VALUE_5',
        cplqty_0: 52.5,
        basqty_0: 52.5,
        bomofs_0: 'VALUE_5',
        likqtycod_0: 52.5,
        qtyrnd_0: 52.5,
        likqty_0: 52.5,
        bomope_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        mfgnum_0: 'VALUE_5',
        abccls_0: 'VALUE_5',
        expnum_0: 'VALUE_5',
        bpcnum_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        mfglin_0: 'VALUE_5',
        extqty_0: 52.5,
        itmref_0: 'VALUE_5',
        vcrseqori_0: 'VALUE_5',
        xversionc_0: 'VALUE_5',
        planner_0: 'VALUE_5',
        stu_0: 'VALUE_5',
      },
      {
        cstflg_0: 'VALUE_6',
        updusr_0: 'VALUE_6',
        vcrnumori_0: 'VALUE_6',
        vcrtypori_0: 'VALUE_6',
        vcrlinori_0: 'VALUE_6',
        pjt_0: 'VALUE_6',
        tclcod_0: 'VALUE_6',
        rmnextqty_0: 63.0,
        lot_0: 'VALUE_6',
        mfgpio_0: 'VALUE_6',
        bomalt_0: 'VALUE_6',
        bpctypden_0: 'VALUE_6',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        fmi_0: 'VALUE_6',
        x4datref_0: 'MFG0006',
        itmtyp_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_6',
        eccvalmin_0: 'VALUE_6',
        xnbempr_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        trkfirstc_0: 'VALUE_6',
        trklastc_0: 'VALUE_6',
        itmlin_0: 'VALUE_6',
        plnfcy_0: 'VALUE_6',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_6',
        x4datper_0: new Date().toISOString().split('T')[0],
        itmsta_0: 6,
        wipnum_0: 'VALUE_6',
        mfgdes_0: 'Désignation OF 6',
        uom_0: 'VALUE_6',
        uomextqty_0: 63.0,
        uomstucoe_0: 'VALUE_6',
        rejcplqty_0: 63.0,
        quacplqty_0: 63.0,
        mfitrkflg_0: 'VALUE_6',
        clodat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_6',
        trklast_0: 'VALUE_6',
        tsicod_0: 'VALUE_6',
        cplqty_0: 63.0,
        basqty_0: 63.0,
        bomofs_0: 'VALUE_6',
        likqtycod_0: 63.0,
        qtyrnd_0: 63.0,
        likqty_0: 63.0,
        bomope_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        mfgnum_0: 'VALUE_6',
        abccls_0: 'VALUE_6',
        expnum_0: 'VALUE_6',
        bpcnum_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        mfglin_0: 'VALUE_6',
        extqty_0: 63.0,
        itmref_0: 'VALUE_6',
        vcrseqori_0: 'VALUE_6',
        xversionc_0: 'VALUE_6',
        planner_0: 'VALUE_6',
        stu_0: 'VALUE_6',
      },
      {
        cstflg_0: 'VALUE_7',
        updusr_0: 'VALUE_7',
        vcrnumori_0: 'VALUE_7',
        vcrtypori_0: 'VALUE_7',
        vcrlinori_0: 'VALUE_7',
        pjt_0: 'VALUE_7',
        tclcod_0: 'VALUE_7',
        rmnextqty_0: 73.5,
        lot_0: 'VALUE_7',
        mfgpio_0: 'VALUE_7',
        bomalt_0: 'VALUE_7',
        bpctypden_0: 'VALUE_7',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        fmi_0: 'VALUE_7',
        x4datref_0: 'MFG0007',
        itmtyp_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_7',
        eccvalmin_0: 'VALUE_7',
        xnbempr_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        trkfirstc_0: 'VALUE_7',
        trklastc_0: 'VALUE_7',
        itmlin_0: 'VALUE_7',
        plnfcy_0: 'VALUE_7',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_7',
        x4datper_0: new Date().toISOString().split('T')[0],
        itmsta_0: 7,
        wipnum_0: 'VALUE_7',
        mfgdes_0: 'Désignation OF 7',
        uom_0: 'VALUE_7',
        uomextqty_0: 73.5,
        uomstucoe_0: 'VALUE_7',
        rejcplqty_0: 73.5,
        quacplqty_0: 73.5,
        mfitrkflg_0: 'VALUE_7',
        clodat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_7',
        trklast_0: 'VALUE_7',
        tsicod_0: 'VALUE_7',
        cplqty_0: 73.5,
        basqty_0: 73.5,
        bomofs_0: 'VALUE_7',
        likqtycod_0: 73.5,
        qtyrnd_0: 73.5,
        likqty_0: 73.5,
        bomope_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        mfgnum_0: 'VALUE_7',
        abccls_0: 'VALUE_7',
        expnum_0: 'VALUE_7',
        bpcnum_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        mfglin_0: 'VALUE_7',
        extqty_0: 73.5,
        itmref_0: 'VALUE_7',
        vcrseqori_0: 'VALUE_7',
        xversionc_0: 'VALUE_7',
        planner_0: 'VALUE_7',
        stu_0: 'VALUE_7',
      },
      {
        cstflg_0: 'VALUE_8',
        updusr_0: 'VALUE_8',
        vcrnumori_0: 'VALUE_8',
        vcrtypori_0: 'VALUE_8',
        vcrlinori_0: 'VALUE_8',
        pjt_0: 'VALUE_8',
        tclcod_0: 'VALUE_8',
        rmnextqty_0: 84.0,
        lot_0: 'VALUE_8',
        mfgpio_0: 'VALUE_8',
        bomalt_0: 'VALUE_8',
        bpctypden_0: 'VALUE_8',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        fmi_0: 'VALUE_8',
        x4datref_0: 'MFG0008',
        itmtyp_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_8',
        eccvalmin_0: 'VALUE_8',
        xnbempr_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        trkfirstc_0: 'VALUE_8',
        trklastc_0: 'VALUE_8',
        itmlin_0: 'VALUE_8',
        plnfcy_0: 'VALUE_8',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_8',
        x4datper_0: new Date().toISOString().split('T')[0],
        itmsta_0: 8,
        wipnum_0: 'VALUE_8',
        mfgdes_0: 'Désignation OF 8',
        uom_0: 'VALUE_8',
        uomextqty_0: 84.0,
        uomstucoe_0: 'VALUE_8',
        rejcplqty_0: 84.0,
        quacplqty_0: 84.0,
        mfitrkflg_0: 'VALUE_8',
        clodat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_8',
        trklast_0: 'VALUE_8',
        tsicod_0: 'VALUE_8',
        cplqty_0: 84.0,
        basqty_0: 84.0,
        bomofs_0: 'VALUE_8',
        likqtycod_0: 84.0,
        qtyrnd_0: 84.0,
        likqty_0: 84.0,
        bomope_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        mfgnum_0: 'VALUE_8',
        abccls_0: 'VALUE_8',
        expnum_0: 'VALUE_8',
        bpcnum_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        mfglin_0: 'VALUE_8',
        extqty_0: 84.0,
        itmref_0: 'VALUE_8',
        vcrseqori_0: 'VALUE_8',
        xversionc_0: 'VALUE_8',
        planner_0: 'VALUE_8',
        stu_0: 'VALUE_8',
      },
      {
        cstflg_0: 'VALUE_9',
        updusr_0: 'VALUE_9',
        vcrnumori_0: 'VALUE_9',
        vcrtypori_0: 'VALUE_9',
        vcrlinori_0: 'VALUE_9',
        pjt_0: 'VALUE_9',
        tclcod_0: 'VALUE_9',
        rmnextqty_0: 94.5,
        lot_0: 'VALUE_9',
        mfgpio_0: 'VALUE_9',
        bomalt_0: 'VALUE_9',
        bpctypden_0: 'VALUE_9',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        fmi_0: 'VALUE_9',
        x4datref_0: 'MFG0009',
        itmtyp_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_9',
        eccvalmin_0: 'VALUE_9',
        xnbempr_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        trkfirstc_0: 'VALUE_9',
        trklastc_0: 'VALUE_9',
        itmlin_0: 'VALUE_9',
        plnfcy_0: 'VALUE_9',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_9',
        x4datper_0: new Date().toISOString().split('T')[0],
        itmsta_0: 9,
        wipnum_0: 'VALUE_9',
        mfgdes_0: 'Désignation OF 9',
        uom_0: 'VALUE_9',
        uomextqty_0: 94.5,
        uomstucoe_0: 'VALUE_9',
        rejcplqty_0: 94.5,
        quacplqty_0: 94.5,
        mfitrkflg_0: 'VALUE_9',
        clodat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_9',
        trklast_0: 'VALUE_9',
        tsicod_0: 'VALUE_9',
        cplqty_0: 94.5,
        basqty_0: 94.5,
        bomofs_0: 'VALUE_9',
        likqtycod_0: 94.5,
        qtyrnd_0: 94.5,
        likqty_0: 94.5,
        bomope_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        mfgnum_0: 'VALUE_9',
        abccls_0: 'VALUE_9',
        expnum_0: 'VALUE_9',
        bpcnum_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        mfglin_0: 'VALUE_9',
        extqty_0: 94.5,
        itmref_0: 'VALUE_9',
        vcrseqori_0: 'VALUE_9',
        xversionc_0: 'VALUE_9',
        planner_0: 'VALUE_9',
        stu_0: 'VALUE_9',
      },
      {
        cstflg_0: 'VALUE_10',
        updusr_0: 'VALUE_10',
        vcrnumori_0: 'VALUE_10',
        vcrtypori_0: 'VALUE_10',
        vcrlinori_0: 'VALUE_10',
        pjt_0: 'VALUE_10',
        tclcod_0: 'VALUE_10',
        rmnextqty_0: 105.0,
        lot_0: 'VALUE_10',
        mfgpio_0: 'VALUE_10',
        bomalt_0: 'VALUE_10',
        bpctypden_0: 'VALUE_10',
        strdat_0: new Date().toISOString().split('T')[0],
        enddat_0: new Date().toISOString().split('T')[0],
        fmi_0: 'VALUE_10',
        x4datref_0: 'MFG0010',
        itmtyp_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        eccvalmaj_0: 'VALUE_10',
        eccvalmin_0: 'VALUE_10',
        xnbempr_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        trkfirstc_0: 'VALUE_10',
        trklastc_0: 'VALUE_10',
        itmlin_0: 'VALUE_10',
        plnfcy_0: 'VALUE_10',
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_10',
        x4datper_0: new Date().toISOString().split('T')[0],
        itmsta_0: 10,
        wipnum_0: 'VALUE_10',
        mfgdes_0: 'Désignation OF 10',
        uom_0: 'VALUE_10',
        uomextqty_0: 105.0,
        uomstucoe_0: 'VALUE_10',
        rejcplqty_0: 105.0,
        quacplqty_0: 105.0,
        mfitrkflg_0: 'VALUE_10',
        clodat_0: new Date().toISOString().split('T')[0],
        credat_0: new Date().toISOString().split('T')[0],
        trkfirst_0: 'VALUE_10',
        trklast_0: 'VALUE_10',
        tsicod_0: 'VALUE_10',
        cplqty_0: 105.0,
        basqty_0: 105.0,
        bomofs_0: 'VALUE_10',
        likqtycod_0: 105.0,
        qtyrnd_0: 105.0,
        likqty_0: 105.0,
        bomope_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        mfgnum_0: 'VALUE_10',
        abccls_0: 'VALUE_10',
        expnum_0: 'VALUE_10',
        bpcnum_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        mfglin_0: 'VALUE_10',
        extqty_0: 105.0,
        itmref_0: 'VALUE_10',
        vcrseqori_0: 'VALUE_10',
        xversionc_0: 'VALUE_10',
        planner_0: 'VALUE_10',
        stu_0: 'VALUE_10',
      },
    ]

    await Database.table('mfgitm').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans mfgitm`)
  }
}
