import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Database from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  async run() {
    // Données fictives pour MFGOPE
    const data = [
      {
        cplwst_0: 'VALUE_1',
        plnfcy_0: 'VALUE_1',
        stdlab_0: 'VALUE_1',
        extlab_0: 'VALUE_1',
        cpllab_0: 'VALUE_1',
        frcstrdat_0: new Date().toISOString().split('T')[0],
        opestrcoe_0: 'VALUE_1',
        extstrqty_0: 10.5,
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_1',
        stdwstnbr_0: 'VALUE_1',
        extsettim_0: new Date().toISOString(),
        cplsettim_0: new Date().toISOString(),
        bprnum_0: 'MFG0001',
        stdopetim_0: new Date().toISOString(),
        psptim_0: new Date().toISOString(),
        rejcplqty_0: 10.5,
        quacplqty_0: 10.5,
        mfotrkflg_0: 'VALUE_1',
        trkfirst_0: 'VALUE_1',
        trkfirstc_0: 'VALUE_1',
        trklast_0: 'VALUE_1',
        trklastc_0: 'VALUE_1',
        stdwst_0: 'VALUE_1',
        extwst_0: 'VALUE_1',
        cplqty_0: 10.5,
        extpri_0: 10.5,
        cplpri_0: 10.5,
        basqty_0: 10.5,
        timcod_0: new Date().toISOString(),
        shr_0: 'VALUE_1',
        frcstrhou_0: 'VALUE_1',
        extwstnbr_0: 'VALUE_1',
        cplwstnbr_0: 'VALUE_1',
        extstuqty_0: 10.5,
        stdsettim_0: new Date().toISOString(),
        stdqty_0: 10.5,
        opesplnum_0: 'VALUE_1',
        refpri_0: 10.5,
        xmachine_0: 'VALUE_1',
        credat_0: new Date().toISOString().split('T')[0],
        wsteff_0: 'VALUE_1',
        wipnum_0: 'VALUE_1',
        poplin_0: 'VALUE_1',
        scocod_0: 'VALUE_1',
        scoitmref_0: 'VALUE_1',
        splcod_0: 'VALUE_1',
        splmaxnbr_0: 'VALUE_1',
        altopecod_0: 'VALUE_1',
        rstmac_0: 'VALUE_1',
        grpsettim_0: new Date().toISOString(),
        opeplnnum_0: 'VALUE_1',
        operoupct_0: 'VALUE_1',
        equnum_0: 'VALUE_1',
        fxgnum_0: 'VALUE_1',
        eff_0: 'VALUE_1',
        prptim_0: new Date().toISOString(),
        timuomcod_0: new Date().toISOString(),
        pohnum_0: 'VALUE_1',
        fitcapstr_0: 'VALUE_1',
        fitcapend_0: 'VALUE_1',
        infcapstr_0: 'VALUE_1',
        infcapend_0: 'VALUE_1',
        mfotex_0: 'VALUE_1',
        openum_0: 'VALUE_1',
        openumlev_0: 'VALUE_1',
        rplind_0: 'VALUE_1',
        updusr_0: 'VALUE_1',
        upddat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_1',
        cad_0: 'VALUE_1',
        prgnum_0: 'VALUE_1',
        creusr_0: 'VALUE_1',
        waitim_0: new Date().toISOString(),
        extqty_0: 10.5,
        opelabcoe_0: 'VALUE_1',
        teccrd_0: 'VALUE_1',
        schgrp_0: 'VALUE_1',
        popseq_0: 'VALUE_1',
        opesta_0: 1,
        setlabcoe_0: 'VALUE_1',
        roodes_0: 'Désignation opération 1',
        opeuom_0: 'VALUE_1',
        invqty_0: 10.5,
        extunttim_0: new Date().toISOString(),
        extopetim_0: new Date().toISOString(),
        cplopetim_0: new Date().toISOString(),
        opsnum_0: 'VALUE_1',
        cplunttim_0: new Date().toISOString(),
        stdunttim_0: new Date().toISOString(),
        rouopenum_0: 'VALUE_1',
        opestucoe_0: 'VALUE_1',
        cplcrg_0: 'VALUE_1',
        scowst_0: 'VALUE_1',
        mfgnum_0: 'VALUE_1',
        bpaadd_0: 'VALUE_1',
        mfgpio_0: 'VALUE_1',
        scolti_0: 'VALUE_1',
        xcadtheo_0: 'VALUE_1',
        opestr_0: 'VALUE_1',
        opeend_0: 'VALUE_1',
        x4limend_0: 'VALUE_1',
        x4limflg_0: 'VALUE_1',
        x4limtyp_0: 'VALUE_1',
        x4limstr_0: 'VALUE_1',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xsernum_0: 'VALUE_1',
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        stdlabnbr_0: 'VALUE_1',
        extlabnbr_0: 'VALUE_1',
        cpllabnbr_0: 'VALUE_1',
        x4collab_0: 'VALUE_1',
        rootimcod_0: new Date().toISOString(),
        scopuu_0: 'VALUE_1',
        x4plngmao_0: 'VALUE_1',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1ftcod_0: 'VALUE_1',
        x1teccrd_0: 'VALUE_1',
        xempreinte_0: 'VALUE_1',
        auuid_0: 'VALUE_1',
        x4pfinflg_0: 'VALUE_1',
        schsbb_0: 'VALUE_1',
      },
      {
        cplwst_0: 'VALUE_2',
        plnfcy_0: 'VALUE_2',
        stdlab_0: 'VALUE_2',
        extlab_0: 'VALUE_2',
        cpllab_0: 'VALUE_2',
        frcstrdat_0: new Date().toISOString().split('T')[0],
        opestrcoe_0: 'VALUE_2',
        extstrqty_0: 21.0,
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_2',
        stdwstnbr_0: 'VALUE_2',
        extsettim_0: new Date().toISOString(),
        cplsettim_0: new Date().toISOString(),
        bprnum_0: 'MFG0002',
        stdopetim_0: new Date().toISOString(),
        psptim_0: new Date().toISOString(),
        rejcplqty_0: 21.0,
        quacplqty_0: 21.0,
        mfotrkflg_0: 'VALUE_2',
        trkfirst_0: 'VALUE_2',
        trkfirstc_0: 'VALUE_2',
        trklast_0: 'VALUE_2',
        trklastc_0: 'VALUE_2',
        stdwst_0: 'VALUE_2',
        extwst_0: 'VALUE_2',
        cplqty_0: 21.0,
        extpri_0: 21.0,
        cplpri_0: 21.0,
        basqty_0: 21.0,
        timcod_0: new Date().toISOString(),
        shr_0: 'VALUE_2',
        frcstrhou_0: 'VALUE_2',
        extwstnbr_0: 'VALUE_2',
        cplwstnbr_0: 'VALUE_2',
        extstuqty_0: 21.0,
        stdsettim_0: new Date().toISOString(),
        stdqty_0: 21.0,
        opesplnum_0: 'VALUE_2',
        refpri_0: 21.0,
        xmachine_0: 'VALUE_2',
        credat_0: new Date().toISOString().split('T')[0],
        wsteff_0: 'VALUE_2',
        wipnum_0: 'VALUE_2',
        poplin_0: 'VALUE_2',
        scocod_0: 'VALUE_2',
        scoitmref_0: 'VALUE_2',
        splcod_0: 'VALUE_2',
        splmaxnbr_0: 'VALUE_2',
        altopecod_0: 'VALUE_2',
        rstmac_0: 'VALUE_2',
        grpsettim_0: new Date().toISOString(),
        opeplnnum_0: 'VALUE_2',
        operoupct_0: 'VALUE_2',
        equnum_0: 'VALUE_2',
        fxgnum_0: 'VALUE_2',
        eff_0: 'VALUE_2',
        prptim_0: new Date().toISOString(),
        timuomcod_0: new Date().toISOString(),
        pohnum_0: 'VALUE_2',
        fitcapstr_0: 'VALUE_2',
        fitcapend_0: 'VALUE_2',
        infcapstr_0: 'VALUE_2',
        infcapend_0: 'VALUE_2',
        mfotex_0: 'VALUE_2',
        openum_0: 'VALUE_2',
        openumlev_0: 'VALUE_2',
        rplind_0: 'VALUE_2',
        updusr_0: 'VALUE_2',
        upddat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_2',
        cad_0: 'VALUE_2',
        prgnum_0: 'VALUE_2',
        creusr_0: 'VALUE_2',
        waitim_0: new Date().toISOString(),
        extqty_0: 21.0,
        opelabcoe_0: 'VALUE_2',
        teccrd_0: 'VALUE_2',
        schgrp_0: 'VALUE_2',
        popseq_0: 'VALUE_2',
        opesta_0: 2,
        setlabcoe_0: 'VALUE_2',
        roodes_0: 'Désignation opération 2',
        opeuom_0: 'VALUE_2',
        invqty_0: 21.0,
        extunttim_0: new Date().toISOString(),
        extopetim_0: new Date().toISOString(),
        cplopetim_0: new Date().toISOString(),
        opsnum_0: 'VALUE_2',
        cplunttim_0: new Date().toISOString(),
        stdunttim_0: new Date().toISOString(),
        rouopenum_0: 'VALUE_2',
        opestucoe_0: 'VALUE_2',
        cplcrg_0: 'VALUE_2',
        scowst_0: 'VALUE_2',
        mfgnum_0: 'VALUE_2',
        bpaadd_0: 'VALUE_2',
        mfgpio_0: 'VALUE_2',
        scolti_0: 'VALUE_2',
        xcadtheo_0: 'VALUE_2',
        opestr_0: 'VALUE_2',
        opeend_0: 'VALUE_2',
        x4limend_0: 'VALUE_2',
        x4limflg_0: 'VALUE_2',
        x4limtyp_0: 'VALUE_2',
        x4limstr_0: 'VALUE_2',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xsernum_0: 'VALUE_2',
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        stdlabnbr_0: 'VALUE_2',
        extlabnbr_0: 'VALUE_2',
        cpllabnbr_0: 'VALUE_2',
        x4collab_0: 'VALUE_2',
        rootimcod_0: new Date().toISOString(),
        scopuu_0: 'VALUE_2',
        x4plngmao_0: 'VALUE_2',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1ftcod_0: 'VALUE_2',
        x1teccrd_0: 'VALUE_2',
        xempreinte_0: 'VALUE_2',
        auuid_0: 'VALUE_2',
        x4pfinflg_0: 'VALUE_2',
        schsbb_0: 'VALUE_2',
      },
      {
        cplwst_0: 'VALUE_3',
        plnfcy_0: 'VALUE_3',
        stdlab_0: 'VALUE_3',
        extlab_0: 'VALUE_3',
        cpllab_0: 'VALUE_3',
        frcstrdat_0: new Date().toISOString().split('T')[0],
        opestrcoe_0: 'VALUE_3',
        extstrqty_0: 31.5,
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_3',
        stdwstnbr_0: 'VALUE_3',
        extsettim_0: new Date().toISOString(),
        cplsettim_0: new Date().toISOString(),
        bprnum_0: 'MFG0003',
        stdopetim_0: new Date().toISOString(),
        psptim_0: new Date().toISOString(),
        rejcplqty_0: 31.5,
        quacplqty_0: 31.5,
        mfotrkflg_0: 'VALUE_3',
        trkfirst_0: 'VALUE_3',
        trkfirstc_0: 'VALUE_3',
        trklast_0: 'VALUE_3',
        trklastc_0: 'VALUE_3',
        stdwst_0: 'VALUE_3',
        extwst_0: 'VALUE_3',
        cplqty_0: 31.5,
        extpri_0: 31.5,
        cplpri_0: 31.5,
        basqty_0: 31.5,
        timcod_0: new Date().toISOString(),
        shr_0: 'VALUE_3',
        frcstrhou_0: 'VALUE_3',
        extwstnbr_0: 'VALUE_3',
        cplwstnbr_0: 'VALUE_3',
        extstuqty_0: 31.5,
        stdsettim_0: new Date().toISOString(),
        stdqty_0: 31.5,
        opesplnum_0: 'VALUE_3',
        refpri_0: 31.5,
        xmachine_0: 'VALUE_3',
        credat_0: new Date().toISOString().split('T')[0],
        wsteff_0: 'VALUE_3',
        wipnum_0: 'VALUE_3',
        poplin_0: 'VALUE_3',
        scocod_0: 'VALUE_3',
        scoitmref_0: 'VALUE_3',
        splcod_0: 'VALUE_3',
        splmaxnbr_0: 'VALUE_3',
        altopecod_0: 'VALUE_3',
        rstmac_0: 'VALUE_3',
        grpsettim_0: new Date().toISOString(),
        opeplnnum_0: 'VALUE_3',
        operoupct_0: 'VALUE_3',
        equnum_0: 'VALUE_3',
        fxgnum_0: 'VALUE_3',
        eff_0: 'VALUE_3',
        prptim_0: new Date().toISOString(),
        timuomcod_0: new Date().toISOString(),
        pohnum_0: 'VALUE_3',
        fitcapstr_0: 'VALUE_3',
        fitcapend_0: 'VALUE_3',
        infcapstr_0: 'VALUE_3',
        infcapend_0: 'VALUE_3',
        mfotex_0: 'VALUE_3',
        openum_0: 'VALUE_3',
        openumlev_0: 'VALUE_3',
        rplind_0: 'VALUE_3',
        updusr_0: 'VALUE_3',
        upddat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_3',
        cad_0: 'VALUE_3',
        prgnum_0: 'VALUE_3',
        creusr_0: 'VALUE_3',
        waitim_0: new Date().toISOString(),
        extqty_0: 31.5,
        opelabcoe_0: 'VALUE_3',
        teccrd_0: 'VALUE_3',
        schgrp_0: 'VALUE_3',
        popseq_0: 'VALUE_3',
        opesta_0: 3,
        setlabcoe_0: 'VALUE_3',
        roodes_0: 'Désignation opération 3',
        opeuom_0: 'VALUE_3',
        invqty_0: 31.5,
        extunttim_0: new Date().toISOString(),
        extopetim_0: new Date().toISOString(),
        cplopetim_0: new Date().toISOString(),
        opsnum_0: 'VALUE_3',
        cplunttim_0: new Date().toISOString(),
        stdunttim_0: new Date().toISOString(),
        rouopenum_0: 'VALUE_3',
        opestucoe_0: 'VALUE_3',
        cplcrg_0: 'VALUE_3',
        scowst_0: 'VALUE_3',
        mfgnum_0: 'VALUE_3',
        bpaadd_0: 'VALUE_3',
        mfgpio_0: 'VALUE_3',
        scolti_0: 'VALUE_3',
        xcadtheo_0: 'VALUE_3',
        opestr_0: 'VALUE_3',
        opeend_0: 'VALUE_3',
        x4limend_0: 'VALUE_3',
        x4limflg_0: 'VALUE_3',
        x4limtyp_0: 'VALUE_3',
        x4limstr_0: 'VALUE_3',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xsernum_0: 'VALUE_3',
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        stdlabnbr_0: 'VALUE_3',
        extlabnbr_0: 'VALUE_3',
        cpllabnbr_0: 'VALUE_3',
        x4collab_0: 'VALUE_3',
        rootimcod_0: new Date().toISOString(),
        scopuu_0: 'VALUE_3',
        x4plngmao_0: 'VALUE_3',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1ftcod_0: 'VALUE_3',
        x1teccrd_0: 'VALUE_3',
        xempreinte_0: 'VALUE_3',
        auuid_0: 'VALUE_3',
        x4pfinflg_0: 'VALUE_3',
        schsbb_0: 'VALUE_3',
      },
      {
        cplwst_0: 'VALUE_4',
        plnfcy_0: 'VALUE_4',
        stdlab_0: 'VALUE_4',
        extlab_0: 'VALUE_4',
        cpllab_0: 'VALUE_4',
        frcstrdat_0: new Date().toISOString().split('T')[0],
        opestrcoe_0: 'VALUE_4',
        extstrqty_0: 42.0,
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_4',
        stdwstnbr_0: 'VALUE_4',
        extsettim_0: new Date().toISOString(),
        cplsettim_0: new Date().toISOString(),
        bprnum_0: 'MFG0004',
        stdopetim_0: new Date().toISOString(),
        psptim_0: new Date().toISOString(),
        rejcplqty_0: 42.0,
        quacplqty_0: 42.0,
        mfotrkflg_0: 'VALUE_4',
        trkfirst_0: 'VALUE_4',
        trkfirstc_0: 'VALUE_4',
        trklast_0: 'VALUE_4',
        trklastc_0: 'VALUE_4',
        stdwst_0: 'VALUE_4',
        extwst_0: 'VALUE_4',
        cplqty_0: 42.0,
        extpri_0: 42.0,
        cplpri_0: 42.0,
        basqty_0: 42.0,
        timcod_0: new Date().toISOString(),
        shr_0: 'VALUE_4',
        frcstrhou_0: 'VALUE_4',
        extwstnbr_0: 'VALUE_4',
        cplwstnbr_0: 'VALUE_4',
        extstuqty_0: 42.0,
        stdsettim_0: new Date().toISOString(),
        stdqty_0: 42.0,
        opesplnum_0: 'VALUE_4',
        refpri_0: 42.0,
        xmachine_0: 'VALUE_4',
        credat_0: new Date().toISOString().split('T')[0],
        wsteff_0: 'VALUE_4',
        wipnum_0: 'VALUE_4',
        poplin_0: 'VALUE_4',
        scocod_0: 'VALUE_4',
        scoitmref_0: 'VALUE_4',
        splcod_0: 'VALUE_4',
        splmaxnbr_0: 'VALUE_4',
        altopecod_0: 'VALUE_4',
        rstmac_0: 'VALUE_4',
        grpsettim_0: new Date().toISOString(),
        opeplnnum_0: 'VALUE_4',
        operoupct_0: 'VALUE_4',
        equnum_0: 'VALUE_4',
        fxgnum_0: 'VALUE_4',
        eff_0: 'VALUE_4',
        prptim_0: new Date().toISOString(),
        timuomcod_0: new Date().toISOString(),
        pohnum_0: 'VALUE_4',
        fitcapstr_0: 'VALUE_4',
        fitcapend_0: 'VALUE_4',
        infcapstr_0: 'VALUE_4',
        infcapend_0: 'VALUE_4',
        mfotex_0: 'VALUE_4',
        openum_0: 'VALUE_4',
        openumlev_0: 'VALUE_4',
        rplind_0: 'VALUE_4',
        updusr_0: 'VALUE_4',
        upddat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_4',
        cad_0: 'VALUE_4',
        prgnum_0: 'VALUE_4',
        creusr_0: 'VALUE_4',
        waitim_0: new Date().toISOString(),
        extqty_0: 42.0,
        opelabcoe_0: 'VALUE_4',
        teccrd_0: 'VALUE_4',
        schgrp_0: 'VALUE_4',
        popseq_0: 'VALUE_4',
        opesta_0: 4,
        setlabcoe_0: 'VALUE_4',
        roodes_0: 'Désignation opération 4',
        opeuom_0: 'VALUE_4',
        invqty_0: 42.0,
        extunttim_0: new Date().toISOString(),
        extopetim_0: new Date().toISOString(),
        cplopetim_0: new Date().toISOString(),
        opsnum_0: 'VALUE_4',
        cplunttim_0: new Date().toISOString(),
        stdunttim_0: new Date().toISOString(),
        rouopenum_0: 'VALUE_4',
        opestucoe_0: 'VALUE_4',
        cplcrg_0: 'VALUE_4',
        scowst_0: 'VALUE_4',
        mfgnum_0: 'VALUE_4',
        bpaadd_0: 'VALUE_4',
        mfgpio_0: 'VALUE_4',
        scolti_0: 'VALUE_4',
        xcadtheo_0: 'VALUE_4',
        opestr_0: 'VALUE_4',
        opeend_0: 'VALUE_4',
        x4limend_0: 'VALUE_4',
        x4limflg_0: 'VALUE_4',
        x4limtyp_0: 'VALUE_4',
        x4limstr_0: 'VALUE_4',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xsernum_0: 'VALUE_4',
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        stdlabnbr_0: 'VALUE_4',
        extlabnbr_0: 'VALUE_4',
        cpllabnbr_0: 'VALUE_4',
        x4collab_0: 'VALUE_4',
        rootimcod_0: new Date().toISOString(),
        scopuu_0: 'VALUE_4',
        x4plngmao_0: 'VALUE_4',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1ftcod_0: 'VALUE_4',
        x1teccrd_0: 'VALUE_4',
        xempreinte_0: 'VALUE_4',
        auuid_0: 'VALUE_4',
        x4pfinflg_0: 'VALUE_4',
        schsbb_0: 'VALUE_4',
      },
      {
        cplwst_0: 'VALUE_5',
        plnfcy_0: 'VALUE_5',
        stdlab_0: 'VALUE_5',
        extlab_0: 'VALUE_5',
        cpllab_0: 'VALUE_5',
        frcstrdat_0: new Date().toISOString().split('T')[0],
        opestrcoe_0: 'VALUE_5',
        extstrqty_0: 52.5,
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_5',
        stdwstnbr_0: 'VALUE_5',
        extsettim_0: new Date().toISOString(),
        cplsettim_0: new Date().toISOString(),
        bprnum_0: 'MFG0005',
        stdopetim_0: new Date().toISOString(),
        psptim_0: new Date().toISOString(),
        rejcplqty_0: 52.5,
        quacplqty_0: 52.5,
        mfotrkflg_0: 'VALUE_5',
        trkfirst_0: 'VALUE_5',
        trkfirstc_0: 'VALUE_5',
        trklast_0: 'VALUE_5',
        trklastc_0: 'VALUE_5',
        stdwst_0: 'VALUE_5',
        extwst_0: 'VALUE_5',
        cplqty_0: 52.5,
        extpri_0: 52.5,
        cplpri_0: 52.5,
        basqty_0: 52.5,
        timcod_0: new Date().toISOString(),
        shr_0: 'VALUE_5',
        frcstrhou_0: 'VALUE_5',
        extwstnbr_0: 'VALUE_5',
        cplwstnbr_0: 'VALUE_5',
        extstuqty_0: 52.5,
        stdsettim_0: new Date().toISOString(),
        stdqty_0: 52.5,
        opesplnum_0: 'VALUE_5',
        refpri_0: 52.5,
        xmachine_0: 'VALUE_5',
        credat_0: new Date().toISOString().split('T')[0],
        wsteff_0: 'VALUE_5',
        wipnum_0: 'VALUE_5',
        poplin_0: 'VALUE_5',
        scocod_0: 'VALUE_5',
        scoitmref_0: 'VALUE_5',
        splcod_0: 'VALUE_5',
        splmaxnbr_0: 'VALUE_5',
        altopecod_0: 'VALUE_5',
        rstmac_0: 'VALUE_5',
        grpsettim_0: new Date().toISOString(),
        opeplnnum_0: 'VALUE_5',
        operoupct_0: 'VALUE_5',
        equnum_0: 'VALUE_5',
        fxgnum_0: 'VALUE_5',
        eff_0: 'VALUE_5',
        prptim_0: new Date().toISOString(),
        timuomcod_0: new Date().toISOString(),
        pohnum_0: 'VALUE_5',
        fitcapstr_0: 'VALUE_5',
        fitcapend_0: 'VALUE_5',
        infcapstr_0: 'VALUE_5',
        infcapend_0: 'VALUE_5',
        mfotex_0: 'VALUE_5',
        openum_0: 'VALUE_5',
        openumlev_0: 'VALUE_5',
        rplind_0: 'VALUE_5',
        updusr_0: 'VALUE_5',
        upddat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_5',
        cad_0: 'VALUE_5',
        prgnum_0: 'VALUE_5',
        creusr_0: 'VALUE_5',
        waitim_0: new Date().toISOString(),
        extqty_0: 52.5,
        opelabcoe_0: 'VALUE_5',
        teccrd_0: 'VALUE_5',
        schgrp_0: 'VALUE_5',
        popseq_0: 'VALUE_5',
        opesta_0: 5,
        setlabcoe_0: 'VALUE_5',
        roodes_0: 'Désignation opération 5',
        opeuom_0: 'VALUE_5',
        invqty_0: 52.5,
        extunttim_0: new Date().toISOString(),
        extopetim_0: new Date().toISOString(),
        cplopetim_0: new Date().toISOString(),
        opsnum_0: 'VALUE_5',
        cplunttim_0: new Date().toISOString(),
        stdunttim_0: new Date().toISOString(),
        rouopenum_0: 'VALUE_5',
        opestucoe_0: 'VALUE_5',
        cplcrg_0: 'VALUE_5',
        scowst_0: 'VALUE_5',
        mfgnum_0: 'VALUE_5',
        bpaadd_0: 'VALUE_5',
        mfgpio_0: 'VALUE_5',
        scolti_0: 'VALUE_5',
        xcadtheo_0: 'VALUE_5',
        opestr_0: 'VALUE_5',
        opeend_0: 'VALUE_5',
        x4limend_0: 'VALUE_5',
        x4limflg_0: 'VALUE_5',
        x4limtyp_0: 'VALUE_5',
        x4limstr_0: 'VALUE_5',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xsernum_0: 'VALUE_5',
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        stdlabnbr_0: 'VALUE_5',
        extlabnbr_0: 'VALUE_5',
        cpllabnbr_0: 'VALUE_5',
        x4collab_0: 'VALUE_5',
        rootimcod_0: new Date().toISOString(),
        scopuu_0: 'VALUE_5',
        x4plngmao_0: 'VALUE_5',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1ftcod_0: 'VALUE_5',
        x1teccrd_0: 'VALUE_5',
        xempreinte_0: 'VALUE_5',
        auuid_0: 'VALUE_5',
        x4pfinflg_0: 'VALUE_5',
        schsbb_0: 'VALUE_5',
      },
      {
        cplwst_0: 'VALUE_6',
        plnfcy_0: 'VALUE_6',
        stdlab_0: 'VALUE_6',
        extlab_0: 'VALUE_6',
        cpllab_0: 'VALUE_6',
        frcstrdat_0: new Date().toISOString().split('T')[0],
        opestrcoe_0: 'VALUE_6',
        extstrqty_0: 63.0,
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_6',
        stdwstnbr_0: 'VALUE_6',
        extsettim_0: new Date().toISOString(),
        cplsettim_0: new Date().toISOString(),
        bprnum_0: 'MFG0006',
        stdopetim_0: new Date().toISOString(),
        psptim_0: new Date().toISOString(),
        rejcplqty_0: 63.0,
        quacplqty_0: 63.0,
        mfotrkflg_0: 'VALUE_6',
        trkfirst_0: 'VALUE_6',
        trkfirstc_0: 'VALUE_6',
        trklast_0: 'VALUE_6',
        trklastc_0: 'VALUE_6',
        stdwst_0: 'VALUE_6',
        extwst_0: 'VALUE_6',
        cplqty_0: 63.0,
        extpri_0: 63.0,
        cplpri_0: 63.0,
        basqty_0: 63.0,
        timcod_0: new Date().toISOString(),
        shr_0: 'VALUE_6',
        frcstrhou_0: 'VALUE_6',
        extwstnbr_0: 'VALUE_6',
        cplwstnbr_0: 'VALUE_6',
        extstuqty_0: 63.0,
        stdsettim_0: new Date().toISOString(),
        stdqty_0: 63.0,
        opesplnum_0: 'VALUE_6',
        refpri_0: 63.0,
        xmachine_0: 'VALUE_6',
        credat_0: new Date().toISOString().split('T')[0],
        wsteff_0: 'VALUE_6',
        wipnum_0: 'VALUE_6',
        poplin_0: 'VALUE_6',
        scocod_0: 'VALUE_6',
        scoitmref_0: 'VALUE_6',
        splcod_0: 'VALUE_6',
        splmaxnbr_0: 'VALUE_6',
        altopecod_0: 'VALUE_6',
        rstmac_0: 'VALUE_6',
        grpsettim_0: new Date().toISOString(),
        opeplnnum_0: 'VALUE_6',
        operoupct_0: 'VALUE_6',
        equnum_0: 'VALUE_6',
        fxgnum_0: 'VALUE_6',
        eff_0: 'VALUE_6',
        prptim_0: new Date().toISOString(),
        timuomcod_0: new Date().toISOString(),
        pohnum_0: 'VALUE_6',
        fitcapstr_0: 'VALUE_6',
        fitcapend_0: 'VALUE_6',
        infcapstr_0: 'VALUE_6',
        infcapend_0: 'VALUE_6',
        mfotex_0: 'VALUE_6',
        openum_0: 'VALUE_6',
        openumlev_0: 'VALUE_6',
        rplind_0: 'VALUE_6',
        updusr_0: 'VALUE_6',
        upddat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_6',
        cad_0: 'VALUE_6',
        prgnum_0: 'VALUE_6',
        creusr_0: 'VALUE_6',
        waitim_0: new Date().toISOString(),
        extqty_0: 63.0,
        opelabcoe_0: 'VALUE_6',
        teccrd_0: 'VALUE_6',
        schgrp_0: 'VALUE_6',
        popseq_0: 'VALUE_6',
        opesta_0: 6,
        setlabcoe_0: 'VALUE_6',
        roodes_0: 'Désignation opération 6',
        opeuom_0: 'VALUE_6',
        invqty_0: 63.0,
        extunttim_0: new Date().toISOString(),
        extopetim_0: new Date().toISOString(),
        cplopetim_0: new Date().toISOString(),
        opsnum_0: 'VALUE_6',
        cplunttim_0: new Date().toISOString(),
        stdunttim_0: new Date().toISOString(),
        rouopenum_0: 'VALUE_6',
        opestucoe_0: 'VALUE_6',
        cplcrg_0: 'VALUE_6',
        scowst_0: 'VALUE_6',
        mfgnum_0: 'VALUE_6',
        bpaadd_0: 'VALUE_6',
        mfgpio_0: 'VALUE_6',
        scolti_0: 'VALUE_6',
        xcadtheo_0: 'VALUE_6',
        opestr_0: 'VALUE_6',
        opeend_0: 'VALUE_6',
        x4limend_0: 'VALUE_6',
        x4limflg_0: 'VALUE_6',
        x4limtyp_0: 'VALUE_6',
        x4limstr_0: 'VALUE_6',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xsernum_0: 'VALUE_6',
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        stdlabnbr_0: 'VALUE_6',
        extlabnbr_0: 'VALUE_6',
        cpllabnbr_0: 'VALUE_6',
        x4collab_0: 'VALUE_6',
        rootimcod_0: new Date().toISOString(),
        scopuu_0: 'VALUE_6',
        x4plngmao_0: 'VALUE_6',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1ftcod_0: 'VALUE_6',
        x1teccrd_0: 'VALUE_6',
        xempreinte_0: 'VALUE_6',
        auuid_0: 'VALUE_6',
        x4pfinflg_0: 'VALUE_6',
        schsbb_0: 'VALUE_6',
      },
      {
        cplwst_0: 'VALUE_7',
        plnfcy_0: 'VALUE_7',
        stdlab_0: 'VALUE_7',
        extlab_0: 'VALUE_7',
        cpllab_0: 'VALUE_7',
        frcstrdat_0: new Date().toISOString().split('T')[0],
        opestrcoe_0: 'VALUE_7',
        extstrqty_0: 73.5,
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_7',
        stdwstnbr_0: 'VALUE_7',
        extsettim_0: new Date().toISOString(),
        cplsettim_0: new Date().toISOString(),
        bprnum_0: 'MFG0007',
        stdopetim_0: new Date().toISOString(),
        psptim_0: new Date().toISOString(),
        rejcplqty_0: 73.5,
        quacplqty_0: 73.5,
        mfotrkflg_0: 'VALUE_7',
        trkfirst_0: 'VALUE_7',
        trkfirstc_0: 'VALUE_7',
        trklast_0: 'VALUE_7',
        trklastc_0: 'VALUE_7',
        stdwst_0: 'VALUE_7',
        extwst_0: 'VALUE_7',
        cplqty_0: 73.5,
        extpri_0: 73.5,
        cplpri_0: 73.5,
        basqty_0: 73.5,
        timcod_0: new Date().toISOString(),
        shr_0: 'VALUE_7',
        frcstrhou_0: 'VALUE_7',
        extwstnbr_0: 'VALUE_7',
        cplwstnbr_0: 'VALUE_7',
        extstuqty_0: 73.5,
        stdsettim_0: new Date().toISOString(),
        stdqty_0: 73.5,
        opesplnum_0: 'VALUE_7',
        refpri_0: 73.5,
        xmachine_0: 'VALUE_7',
        credat_0: new Date().toISOString().split('T')[0],
        wsteff_0: 'VALUE_7',
        wipnum_0: 'VALUE_7',
        poplin_0: 'VALUE_7',
        scocod_0: 'VALUE_7',
        scoitmref_0: 'VALUE_7',
        splcod_0: 'VALUE_7',
        splmaxnbr_0: 'VALUE_7',
        altopecod_0: 'VALUE_7',
        rstmac_0: 'VALUE_7',
        grpsettim_0: new Date().toISOString(),
        opeplnnum_0: 'VALUE_7',
        operoupct_0: 'VALUE_7',
        equnum_0: 'VALUE_7',
        fxgnum_0: 'VALUE_7',
        eff_0: 'VALUE_7',
        prptim_0: new Date().toISOString(),
        timuomcod_0: new Date().toISOString(),
        pohnum_0: 'VALUE_7',
        fitcapstr_0: 'VALUE_7',
        fitcapend_0: 'VALUE_7',
        infcapstr_0: 'VALUE_7',
        infcapend_0: 'VALUE_7',
        mfotex_0: 'VALUE_7',
        openum_0: 'VALUE_7',
        openumlev_0: 'VALUE_7',
        rplind_0: 'VALUE_7',
        updusr_0: 'VALUE_7',
        upddat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_7',
        cad_0: 'VALUE_7',
        prgnum_0: 'VALUE_7',
        creusr_0: 'VALUE_7',
        waitim_0: new Date().toISOString(),
        extqty_0: 73.5,
        opelabcoe_0: 'VALUE_7',
        teccrd_0: 'VALUE_7',
        schgrp_0: 'VALUE_7',
        popseq_0: 'VALUE_7',
        opesta_0: 7,
        setlabcoe_0: 'VALUE_7',
        roodes_0: 'Désignation opération 7',
        opeuom_0: 'VALUE_7',
        invqty_0: 73.5,
        extunttim_0: new Date().toISOString(),
        extopetim_0: new Date().toISOString(),
        cplopetim_0: new Date().toISOString(),
        opsnum_0: 'VALUE_7',
        cplunttim_0: new Date().toISOString(),
        stdunttim_0: new Date().toISOString(),
        rouopenum_0: 'VALUE_7',
        opestucoe_0: 'VALUE_7',
        cplcrg_0: 'VALUE_7',
        scowst_0: 'VALUE_7',
        mfgnum_0: 'VALUE_7',
        bpaadd_0: 'VALUE_7',
        mfgpio_0: 'VALUE_7',
        scolti_0: 'VALUE_7',
        xcadtheo_0: 'VALUE_7',
        opestr_0: 'VALUE_7',
        opeend_0: 'VALUE_7',
        x4limend_0: 'VALUE_7',
        x4limflg_0: 'VALUE_7',
        x4limtyp_0: 'VALUE_7',
        x4limstr_0: 'VALUE_7',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xsernum_0: 'VALUE_7',
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        stdlabnbr_0: 'VALUE_7',
        extlabnbr_0: 'VALUE_7',
        cpllabnbr_0: 'VALUE_7',
        x4collab_0: 'VALUE_7',
        rootimcod_0: new Date().toISOString(),
        scopuu_0: 'VALUE_7',
        x4plngmao_0: 'VALUE_7',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1ftcod_0: 'VALUE_7',
        x1teccrd_0: 'VALUE_7',
        xempreinte_0: 'VALUE_7',
        auuid_0: 'VALUE_7',
        x4pfinflg_0: 'VALUE_7',
        schsbb_0: 'VALUE_7',
      },
      {
        cplwst_0: 'VALUE_8',
        plnfcy_0: 'VALUE_8',
        stdlab_0: 'VALUE_8',
        extlab_0: 'VALUE_8',
        cpllab_0: 'VALUE_8',
        frcstrdat_0: new Date().toISOString().split('T')[0],
        opestrcoe_0: 'VALUE_8',
        extstrqty_0: 84.0,
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_8',
        stdwstnbr_0: 'VALUE_8',
        extsettim_0: new Date().toISOString(),
        cplsettim_0: new Date().toISOString(),
        bprnum_0: 'MFG0008',
        stdopetim_0: new Date().toISOString(),
        psptim_0: new Date().toISOString(),
        rejcplqty_0: 84.0,
        quacplqty_0: 84.0,
        mfotrkflg_0: 'VALUE_8',
        trkfirst_0: 'VALUE_8',
        trkfirstc_0: 'VALUE_8',
        trklast_0: 'VALUE_8',
        trklastc_0: 'VALUE_8',
        stdwst_0: 'VALUE_8',
        extwst_0: 'VALUE_8',
        cplqty_0: 84.0,
        extpri_0: 84.0,
        cplpri_0: 84.0,
        basqty_0: 84.0,
        timcod_0: new Date().toISOString(),
        shr_0: 'VALUE_8',
        frcstrhou_0: 'VALUE_8',
        extwstnbr_0: 'VALUE_8',
        cplwstnbr_0: 'VALUE_8',
        extstuqty_0: 84.0,
        stdsettim_0: new Date().toISOString(),
        stdqty_0: 84.0,
        opesplnum_0: 'VALUE_8',
        refpri_0: 84.0,
        xmachine_0: 'VALUE_8',
        credat_0: new Date().toISOString().split('T')[0],
        wsteff_0: 'VALUE_8',
        wipnum_0: 'VALUE_8',
        poplin_0: 'VALUE_8',
        scocod_0: 'VALUE_8',
        scoitmref_0: 'VALUE_8',
        splcod_0: 'VALUE_8',
        splmaxnbr_0: 'VALUE_8',
        altopecod_0: 'VALUE_8',
        rstmac_0: 'VALUE_8',
        grpsettim_0: new Date().toISOString(),
        opeplnnum_0: 'VALUE_8',
        operoupct_0: 'VALUE_8',
        equnum_0: 'VALUE_8',
        fxgnum_0: 'VALUE_8',
        eff_0: 'VALUE_8',
        prptim_0: new Date().toISOString(),
        timuomcod_0: new Date().toISOString(),
        pohnum_0: 'VALUE_8',
        fitcapstr_0: 'VALUE_8',
        fitcapend_0: 'VALUE_8',
        infcapstr_0: 'VALUE_8',
        infcapend_0: 'VALUE_8',
        mfotex_0: 'VALUE_8',
        openum_0: 'VALUE_8',
        openumlev_0: 'VALUE_8',
        rplind_0: 'VALUE_8',
        updusr_0: 'VALUE_8',
        upddat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_8',
        cad_0: 'VALUE_8',
        prgnum_0: 'VALUE_8',
        creusr_0: 'VALUE_8',
        waitim_0: new Date().toISOString(),
        extqty_0: 84.0,
        opelabcoe_0: 'VALUE_8',
        teccrd_0: 'VALUE_8',
        schgrp_0: 'VALUE_8',
        popseq_0: 'VALUE_8',
        opesta_0: 8,
        setlabcoe_0: 'VALUE_8',
        roodes_0: 'Désignation opération 8',
        opeuom_0: 'VALUE_8',
        invqty_0: 84.0,
        extunttim_0: new Date().toISOString(),
        extopetim_0: new Date().toISOString(),
        cplopetim_0: new Date().toISOString(),
        opsnum_0: 'VALUE_8',
        cplunttim_0: new Date().toISOString(),
        stdunttim_0: new Date().toISOString(),
        rouopenum_0: 'VALUE_8',
        opestucoe_0: 'VALUE_8',
        cplcrg_0: 'VALUE_8',
        scowst_0: 'VALUE_8',
        mfgnum_0: 'VALUE_8',
        bpaadd_0: 'VALUE_8',
        mfgpio_0: 'VALUE_8',
        scolti_0: 'VALUE_8',
        xcadtheo_0: 'VALUE_8',
        opestr_0: 'VALUE_8',
        opeend_0: 'VALUE_8',
        x4limend_0: 'VALUE_8',
        x4limflg_0: 'VALUE_8',
        x4limtyp_0: 'VALUE_8',
        x4limstr_0: 'VALUE_8',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xsernum_0: 'VALUE_8',
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        stdlabnbr_0: 'VALUE_8',
        extlabnbr_0: 'VALUE_8',
        cpllabnbr_0: 'VALUE_8',
        x4collab_0: 'VALUE_8',
        rootimcod_0: new Date().toISOString(),
        scopuu_0: 'VALUE_8',
        x4plngmao_0: 'VALUE_8',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1ftcod_0: 'VALUE_8',
        x1teccrd_0: 'VALUE_8',
        xempreinte_0: 'VALUE_8',
        auuid_0: 'VALUE_8',
        x4pfinflg_0: 'VALUE_8',
        schsbb_0: 'VALUE_8',
      },
      {
        cplwst_0: 'VALUE_9',
        plnfcy_0: 'VALUE_9',
        stdlab_0: 'VALUE_9',
        extlab_0: 'VALUE_9',
        cpllab_0: 'VALUE_9',
        frcstrdat_0: new Date().toISOString().split('T')[0],
        opestrcoe_0: 'VALUE_9',
        extstrqty_0: 94.5,
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_9',
        stdwstnbr_0: 'VALUE_9',
        extsettim_0: new Date().toISOString(),
        cplsettim_0: new Date().toISOString(),
        bprnum_0: 'MFG0009',
        stdopetim_0: new Date().toISOString(),
        psptim_0: new Date().toISOString(),
        rejcplqty_0: 94.5,
        quacplqty_0: 94.5,
        mfotrkflg_0: 'VALUE_9',
        trkfirst_0: 'VALUE_9',
        trkfirstc_0: 'VALUE_9',
        trklast_0: 'VALUE_9',
        trklastc_0: 'VALUE_9',
        stdwst_0: 'VALUE_9',
        extwst_0: 'VALUE_9',
        cplqty_0: 94.5,
        extpri_0: 94.5,
        cplpri_0: 94.5,
        basqty_0: 94.5,
        timcod_0: new Date().toISOString(),
        shr_0: 'VALUE_9',
        frcstrhou_0: 'VALUE_9',
        extwstnbr_0: 'VALUE_9',
        cplwstnbr_0: 'VALUE_9',
        extstuqty_0: 94.5,
        stdsettim_0: new Date().toISOString(),
        stdqty_0: 94.5,
        opesplnum_0: 'VALUE_9',
        refpri_0: 94.5,
        xmachine_0: 'VALUE_9',
        credat_0: new Date().toISOString().split('T')[0],
        wsteff_0: 'VALUE_9',
        wipnum_0: 'VALUE_9',
        poplin_0: 'VALUE_9',
        scocod_0: 'VALUE_9',
        scoitmref_0: 'VALUE_9',
        splcod_0: 'VALUE_9',
        splmaxnbr_0: 'VALUE_9',
        altopecod_0: 'VALUE_9',
        rstmac_0: 'VALUE_9',
        grpsettim_0: new Date().toISOString(),
        opeplnnum_0: 'VALUE_9',
        operoupct_0: 'VALUE_9',
        equnum_0: 'VALUE_9',
        fxgnum_0: 'VALUE_9',
        eff_0: 'VALUE_9',
        prptim_0: new Date().toISOString(),
        timuomcod_0: new Date().toISOString(),
        pohnum_0: 'VALUE_9',
        fitcapstr_0: 'VALUE_9',
        fitcapend_0: 'VALUE_9',
        infcapstr_0: 'VALUE_9',
        infcapend_0: 'VALUE_9',
        mfotex_0: 'VALUE_9',
        openum_0: 'VALUE_9',
        openumlev_0: 'VALUE_9',
        rplind_0: 'VALUE_9',
        updusr_0: 'VALUE_9',
        upddat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_9',
        cad_0: 'VALUE_9',
        prgnum_0: 'VALUE_9',
        creusr_0: 'VALUE_9',
        waitim_0: new Date().toISOString(),
        extqty_0: 94.5,
        opelabcoe_0: 'VALUE_9',
        teccrd_0: 'VALUE_9',
        schgrp_0: 'VALUE_9',
        popseq_0: 'VALUE_9',
        opesta_0: 9,
        setlabcoe_0: 'VALUE_9',
        roodes_0: 'Désignation opération 9',
        opeuom_0: 'VALUE_9',
        invqty_0: 94.5,
        extunttim_0: new Date().toISOString(),
        extopetim_0: new Date().toISOString(),
        cplopetim_0: new Date().toISOString(),
        opsnum_0: 'VALUE_9',
        cplunttim_0: new Date().toISOString(),
        stdunttim_0: new Date().toISOString(),
        rouopenum_0: 'VALUE_9',
        opestucoe_0: 'VALUE_9',
        cplcrg_0: 'VALUE_9',
        scowst_0: 'VALUE_9',
        mfgnum_0: 'VALUE_9',
        bpaadd_0: 'VALUE_9',
        mfgpio_0: 'VALUE_9',
        scolti_0: 'VALUE_9',
        xcadtheo_0: 'VALUE_9',
        opestr_0: 'VALUE_9',
        opeend_0: 'VALUE_9',
        x4limend_0: 'VALUE_9',
        x4limflg_0: 'VALUE_9',
        x4limtyp_0: 'VALUE_9',
        x4limstr_0: 'VALUE_9',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xsernum_0: 'VALUE_9',
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        stdlabnbr_0: 'VALUE_9',
        extlabnbr_0: 'VALUE_9',
        cpllabnbr_0: 'VALUE_9',
        x4collab_0: 'VALUE_9',
        rootimcod_0: new Date().toISOString(),
        scopuu_0: 'VALUE_9',
        x4plngmao_0: 'VALUE_9',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1ftcod_0: 'VALUE_9',
        x1teccrd_0: 'VALUE_9',
        xempreinte_0: 'VALUE_9',
        auuid_0: 'VALUE_9',
        x4pfinflg_0: 'VALUE_9',
        schsbb_0: 'VALUE_9',
      },
      {
        cplwst_0: 'VALUE_10',
        plnfcy_0: 'VALUE_10',
        stdlab_0: 'VALUE_10',
        extlab_0: 'VALUE_10',
        cpllab_0: 'VALUE_10',
        frcstrdat_0: new Date().toISOString().split('T')[0],
        opestrcoe_0: 'VALUE_10',
        extstrqty_0: 105.0,
        mfgsta_0: 1,
        mfgfcy_0: 'VALUE_10',
        stdwstnbr_0: 'VALUE_10',
        extsettim_0: new Date().toISOString(),
        cplsettim_0: new Date().toISOString(),
        bprnum_0: 'MFG0010',
        stdopetim_0: new Date().toISOString(),
        psptim_0: new Date().toISOString(),
        rejcplqty_0: 105.0,
        quacplqty_0: 105.0,
        mfotrkflg_0: 'VALUE_10',
        trkfirst_0: 'VALUE_10',
        trkfirstc_0: 'VALUE_10',
        trklast_0: 'VALUE_10',
        trklastc_0: 'VALUE_10',
        stdwst_0: 'VALUE_10',
        extwst_0: 'VALUE_10',
        cplqty_0: 105.0,
        extpri_0: 105.0,
        cplpri_0: 105.0,
        basqty_0: 105.0,
        timcod_0: new Date().toISOString(),
        shr_0: 'VALUE_10',
        frcstrhou_0: 'VALUE_10',
        extwstnbr_0: 'VALUE_10',
        cplwstnbr_0: 'VALUE_10',
        extstuqty_0: 105.0,
        stdsettim_0: new Date().toISOString(),
        stdqty_0: 105.0,
        opesplnum_0: 'VALUE_10',
        refpri_0: 105.0,
        xmachine_0: 'VALUE_10',
        credat_0: new Date().toISOString().split('T')[0],
        wsteff_0: 'VALUE_10',
        wipnum_0: 'VALUE_10',
        poplin_0: 'VALUE_10',
        scocod_0: 'VALUE_10',
        scoitmref_0: 'VALUE_10',
        splcod_0: 'VALUE_10',
        splmaxnbr_0: 'VALUE_10',
        altopecod_0: 'VALUE_10',
        rstmac_0: 'VALUE_10',
        grpsettim_0: new Date().toISOString(),
        opeplnnum_0: 'VALUE_10',
        operoupct_0: 'VALUE_10',
        equnum_0: 'VALUE_10',
        fxgnum_0: 'VALUE_10',
        eff_0: 'VALUE_10',
        prptim_0: new Date().toISOString(),
        timuomcod_0: new Date().toISOString(),
        pohnum_0: 'VALUE_10',
        fitcapstr_0: 'VALUE_10',
        fitcapend_0: 'VALUE_10',
        infcapstr_0: 'VALUE_10',
        infcapend_0: 'VALUE_10',
        mfotex_0: 'VALUE_10',
        openum_0: 'VALUE_10',
        openumlev_0: 'VALUE_10',
        rplind_0: 'VALUE_10',
        updusr_0: 'VALUE_10',
        upddat_0: new Date().toISOString().split('T')[0],
        expnum_0: 'VALUE_10',
        cad_0: 'VALUE_10',
        prgnum_0: 'VALUE_10',
        creusr_0: 'VALUE_10',
        waitim_0: new Date().toISOString(),
        extqty_0: 105.0,
        opelabcoe_0: 'VALUE_10',
        teccrd_0: 'VALUE_10',
        schgrp_0: 'VALUE_10',
        popseq_0: 'VALUE_10',
        opesta_0: 10,
        setlabcoe_0: 'VALUE_10',
        roodes_0: 'Désignation opération 10',
        opeuom_0: 'VALUE_10',
        invqty_0: 105.0,
        extunttim_0: new Date().toISOString(),
        extopetim_0: new Date().toISOString(),
        cplopetim_0: new Date().toISOString(),
        opsnum_0: 'VALUE_10',
        cplunttim_0: new Date().toISOString(),
        stdunttim_0: new Date().toISOString(),
        rouopenum_0: 'VALUE_10',
        opestucoe_0: 'VALUE_10',
        cplcrg_0: 'VALUE_10',
        scowst_0: 'VALUE_10',
        mfgnum_0: 'VALUE_10',
        bpaadd_0: 'VALUE_10',
        mfgpio_0: 'VALUE_10',
        scolti_0: 'VALUE_10',
        xcadtheo_0: 'VALUE_10',
        opestr_0: 'VALUE_10',
        opeend_0: 'VALUE_10',
        x4limend_0: 'VALUE_10',
        x4limflg_0: 'VALUE_10',
        x4limtyp_0: 'VALUE_10',
        x4limstr_0: 'VALUE_10',
        xdatrefend_0: new Date().toISOString().split('T')[0],
        xsernum_0: 'VALUE_10',
        xdatrefstr_0: new Date().toISOString().split('T')[0],
        stdlabnbr_0: 'VALUE_10',
        extlabnbr_0: 'VALUE_10',
        cpllabnbr_0: 'VALUE_10',
        x4collab_0: 'VALUE_10',
        rootimcod_0: new Date().toISOString(),
        scopuu_0: 'VALUE_10',
        x4plngmao_0: 'VALUE_10',
        credattim_0: new Date().toISOString().split('T')[0],
        upddattim_0: new Date().toISOString().split('T')[0],
        x1ftcod_0: 'VALUE_10',
        x1teccrd_0: 'VALUE_10',
        xempreinte_0: 'VALUE_10',
        auuid_0: 'VALUE_10',
        x4pfinflg_0: 'VALUE_10',
        schsbb_0: 'VALUE_10',
      },
    ]

    await Database.table('mfgope').multiInsert(data)
    
    console.log(`✓ {data.length} enregistrements insérés dans mfgope`)
  }
}
